### ISSUE TITLE
Feature gates "ExperimentalVirtiofsSupport" and "CPUManager" not compatible - Not able to guarantee QoS in pod due to virtiofs container

### ISSUE THREAD

**Issue by amandachow** [kubevirt/kubevirt#10005]
**What happened**:
I am using the "ExperimentalVirtiofsSupport" and "CPUManager" together. I spin up a VMI with `dedicatedCpuPlacement: true`. The VMI fails to create because pod QoS cannot be guaranteed. The error I get comes from [vmi.go](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/watch/vmi.go#L649-L655):
```
// fail vmi creation if CPU pinning has been requested but the Pod QOS is not Guaranteed
podQosClass := pod.Status.QOSClass
if podQosClass != k8sv1.PodQOSGuaranteed && vmi.IsCPUDedicated() {
	c.recorder.Eventf(vmi, k8sv1.EventTypeWarning, FailedGuaranteePodResourcesReason, "failed to guarantee pod resources")
	syncErr = &syncErrorImpl{fmt.Errorf("failed to guarantee pod resources"), FailedGuaranteePodResourcesReason}
	break
}
```

I checked the virt-launcher pod to see if all containers have an equal request and limit for CPU and memory. The virtiofs container did not:
```
  - args:
    [...]
    command:
    - /usr/libexec/virtiofsd
    [...]
    name: virtiofs-data-egress
    resources:
      limits:
        cpu: 100m
        memory: 80M
      requests:
        cpu: 10m
        memory: 1M
```

So out of the box, VMIs will fail to create when these two flags are both enabled.

**What you expected to happen**:
I'd expect that a VMI with `dedicatedCpuPlacement` is able to create successfully when these two feature gates are enabled, without the need for `supportContainerResources` overrides.

This means if a VMI spec enables `dedicatedCpuPlacement`, the virtiofs containers should be created with equal memory and CPU limits and requests.

**How to reproduce it (as minimally and precisely as possible)**:
Enable the two feature flags in the kubevirt configuration:
```
developerConfiguration:
  featureGates:
  - ExperimentalVirtiofsSupport
  - CPUManager
```

Create a VMI with:
```
spec:
  domain:
    cpu:
      dedicatedCpuPlacement: true
```

The VMI will be stuck in Scheduling.

**Additional context**:

My workaround is to manually set the resource limits for virtiofs containers in the kubevirt configuration to satisfy the QoS check:
```
supportContainerResources:
  - type: virtiofs
    resources:
      limits:
        cpu: 100m
        memory: 80M
      requests:
        cpu: 100m
        memory: 80M
```

This solves the problem.

Also, I noticed that `resourcesForVirtioFSContainer` already supports this. [virtiofs.go](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/virtiofs.go#L40C15-L40C15):
 ```
func resourcesForVirtioFSContainer(dedicatedCPUs bool, guaranteedQOS bool, config *virtconfig.ClusterConfig) k8sv1.ResourceRequirements {
```

But `guaranteedQOS` is hardcoded to false in the only place that uses it. [virtiofs.go](https://github.com/kubevirt/kubevirt/blob/0b4b2860d4c548aa323d195cd294ef5a71799a7a/pkg/virt-controller/services/virtiofs.go#L157):
```
func generateContainerFromVolume(volume *v1.Volume, image string, config *virtconfig.ClusterConfig) k8sv1.Container {
	resources := resourcesForVirtioFSContainer(false, false, config)
```

I'm happy to contribute a fix to check if dedicatedCpu is enabled and if so, set guaranteedQOS to true, unless there's already a reason kubevirt doesn't do this.

**Environment**:
- KubeVirt version (use `virtctl version`): `Server Version: v1.0.0-beta.0`
- Kubernetes version (use `kubectl version`): `Server Version: v1.25.10+rke2r1`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
