### ISSUE TITLE
RBAC for clone DataVolume not works when using dataVolumeTemplates.

### ISSUE THREAD

**Issue by cybercoder** [kubevirt/kubevirt#10011]
**What happened**:
cluster role binding works for a stand-alone ```DataVolume```, But not works when using ```dataVolumeTemplates```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdi-cloner
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["*"]
```
And the Tenant side Role and RoleBindings:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-admin
  namespace: t1
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["clone.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-admin-rolebinding
  namespace: t1
subjects:
- kind: Group
  name: k3sTenantAdmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tenant-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdi-cloner-rolebinding
  namespace: public-images
subjects:
- kind: Group
  name: k3sTenantAdmin
  namespace: t1
roleRef:
  kind: ClusterRole
  name: cdi-cloner
  apiGroup: rbac.authorization.k8s.io
```
**Additional context**:
My K3S cluster uses OIDC within external IAM and works properly When I clone a DataVolume. the RBAC allows me to do that, but when use templateDataVolumes there's an Authorization error.

```
{
	"apiVersion": "cdi.kubevirt.io/v1beta1",
	"kind": "DataVolume",
	"metadata": {
		"name": "vm01",
        "annotations": {
            "cdi.kubevirt.io/storage.deleteAfterCompletion": "false"
        }
	},
	"spec": {
		"source": {
			"pvc": {
				"namespace": "public-images",
				"name": "ubuntu-mantic"
			}
		},
		"pvc": {
			"accessModes": [
				"ReadWriteOnce"
			],
			"resources": {
				"requests": {
					"storage": "6Gi"
				}
			}
		}
	}
}
```
Works properly in the t1 namespace. but when try to clone in VM creation time using ```dataVolumeTemplates```:
```
{
  "apiVersion": "kubevirt.io/v1",
  "kind": "VirtualMachine",
  "metadata": {
    "name": "vm01-mantic"
  },
  "spec": {
    "dataVolumeTemplates": [
        {
            "apiVersion": "cdi.kubevirt.io/v1beta1",
            "kind": "DataVolume",
            "metadata": {
                "name": "vm01-disk0",
                "annotations": {
                    "cdi.kubevirt.io/storage.deleteAfterCompletion": "false"
                }
            },
            "spec": {
                "source": {
                    "pvc": {
                        "namespace": "public-images",
                        "name": "ubuntu-mantic"
                    }
                },
                "pvc": {
                    "accessModes": [
                        "ReadWriteOnce"
                    ],
                    "resources": {
                        "requests": {
                            "storage": "6Gi"
                        }
                    }
                }
            }
        }
    ],
    "running": true,
    "template": {
      "metadata": {
        "labels": {
          "kubevirt.io/size": "small",
          "kubevirt.io/domain": "vm01-mantic"
        }
      },
      "spec": {
        "domain": {
          "devices": {
            "disks": [
              {
                "name": "disk0",
                "disk": {
                  "bus": "virtio"
                }
              },
              {
                "name": "cloudinitdisk",
                "disk": {
                  "bus": "virtio"
                }
              }
            ],
            "interfaces": [
              {
                "name": "default",
                "masquerade": {}
              }
            ]
          },
          "resources": {
            "requests": {
              "memory": "64M"
            }
          }
        },
        "networks": [
          {
            "name": "default",
            "pod": {}
          }
        ],
        "volumes": [
          {
            "name": "disk0",
            "dataVolume": {
              "name": "vm01-disk0"
            }
          },
          {
            "name": "cloudinitdisk",
            "cloudInitNoCloud": {
              "userDataBase64": ""
            }
          }
        ]
      }
    }
  }
}
```
get this error:
```
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "admission webhook \"virtualmachine-validator.kubevirt.io\" denied the request: Authorization failed, message is: User system:serviceaccount:t1:default has insufficient permissions in clone source namespace public-images",
    "reason": "Invalid",
    "details": {
        "causes": [
            {
                "reason": "FieldValueInvalid",
                "message": "Authorization failed, message is: User system:serviceaccount:t1:default has insufficient permissions in clone source namespace public-images",
                "field": "spec.dataVolumeTemplates[0]"
            }
        ]
    },
    "code": 422
}
```
**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.1, 0.59.2
- Kubernetes version (use `kubectl version`): v1.26.5+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Bare-Metal
- OS (e.g. from /etc/os-release): Focal
- Kernel (e.g. `uname -a`): 5.4.0-150-generic
- Install tools: N/A
- Others: N/A
