### ISSUE TITLE
How to skip installation when deploying windows system

### ISSUE THREAD

**Issue by ILoveYou00** [kubevirt/kubevirt#10029]
**I use a pure windows.iso to deploy, boot successfully and install into the desktop, then upload this already installed system disk.img to another pvc through virtctl command, after starting vm windows system reported error: 0x00007FF78B863EF0 command referenced The 0x00007FF78B863E79 memory cannot be wnitten.**

## Start the pure windows.iso yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: nfs-storage

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win2k12-iso1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12-iso1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win-apps
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
## The second time using the disk.img with the system already installed, the yaml content is as follows

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: my-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: my-vm
    spec:
      domain:
        devices:
          disks:
            - name: my-disk
              disk:
                bus: sata
          interfaces:
            - name: default
              bridge: {}
        resources:
          requests:
            memory: 4000M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: my-disk
          persistentVolumeClaim:
            claimName: win10-app-iso
```
**What is the problem, is the yaml not written right or can't use disk.img directly, please give us some pointers.**
