### ISSUE TITLE
Define tpm passthrough for virtual machines

### ISSUE THREAD

**Issue by benth42** [kubevirt/kubevirt#10061]
Hello,

I'm creating this post to know if you have a plan to permit the definition of tpm passthrough in the vm yaml definition ?

Indeed I have the needs for  tpm passthrough to /dev/tpmrm0 from inside the guest to the host hypervisor.
The device /dev/tpmrm0  can be accessed by multiple VM.

A working exemple of libvirt domain xml : 
```xml
    <tpm model='tpm-tis'>
      <backend type='passthrough'>
        <device path='/dev/tpmrm0'/>
      </backend>
    </tpm>
```

The libvirt doc : [libvirt tpm domain defintion](https://libvirt.org/formatdomain.html#tpm-device)

I suppose an option, a possibility, could be in the yaml to expand the tpm part ? Perhaps with :
```yaml
tpm:
  model: tpm-tis
  backend: passthrough
    device: /dev/tpmrm0
```

or for emulated one
```yaml
tpm:
  model: tpm-tis
  backend: emulator
```

Well is it possible ? Any opinion about this request ?
Thank you in advance.

Regards,
