### ISSUE TITLE
Launcher pod “Terminating” immediately when be created

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10123]
**What happened**:
When I create a vm with kubevirt 1.0, the launcher pod "Terminating" when be created. Meanwhile the annotations "kubevirt.io/keep-launcher-alive-after-failure: 'true'" doesn't work.
While I change to kubevirt 0.59, the pod can running and vm start success.

**What you expected to happen**:
Launcher pod running and vm start success.

**How to reproduce it (as minimally and precisely as possible)**:
Create vm like what I do with kubevirt 0.59

**Additional context**:
the vm yaml I exec :
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: zal-vm-1719
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: zal-vm-1719
        kubevirt.io/domain: zal-vm-1719
      annotations:
        kubevirt.io/keep-launcher-alive-after-failure: 'true'
    spec:
      domain:
        machine:
          type: q35
        cpu:
          cores: 2
        resources:
          requests:
            memory: 1024M
        devices:
          autoattachMemBalloon: false
          disks:
          - disk:
              bus: virtio
            name: root-device
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - name: root-device
        persistentVolumeClaim:
          claimName: zal-centos-1
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            disable_root: False
            password: root
            chpasswd:
                 list: |
                        root:root
                 expire: False
            ssh_pwauth: True
        name: cloudinitdisk
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0
- Kubernetes version (use `kubectl version`): v1.21.5
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): 4.19
- Install tools: N/A
- Others: N/A
