### ISSUE TITLE
Support IPv6 pod networks

### ISSUE THREAD

**Issue by booxter** [kubevirt/kubevirt#1017]
Current implementation of networking layer assumes that pod networks carry IPv4 addresses. I believe there is a way to deploy k8s with IPv6 networks instead. For example, refer to https://www.projectcalico.org/enable-ipv6-on-kubernetes-with-project-calico/

The assumption about IPv4 is made in several places: when extracting the address from pod network interface; when serving leases with DHCPv4 server; when not advertising MTU via Router Advertisements.

**Comment by fabiand** [comment]
I do agree that we should support a Kubernetes cluster run with IPv6.

But let me highlight that in stock Kube (i.e. not with multus) you can have either IPv4 OR IPv6, not both of them together. Further more, regardless of the protocol, a pod will only have a single address.

But yes again, we should also support if Kube is run in IPv6 native mode.

**Comment by yuvalif** [comment]
could we break that to steps:
(1) given that k8s uses calico and configured with ipv6 addresses, and given that our VM supports ipv6, we should be able to have an ipv6 address allocated to the VM. We will have to make sure that there is nothing which is ipv4 specific in our kubevirt code when moving the ipv6 pod IP to the VM, and that our internal DHCP server does not have any issues with that
(2) support cases where the CNI supports dual stack or multiple IPs

**Comment by fabiand** [comment]
partially depends on https://github.com/kubevirt/kubevirt/issues/1067

**Comment by fabiand** [comment]
@yuvalif in a first step I'd aim for single stack IPv6, thus aiming that our components are IPv6 ready.
Because this is what is supported today, and we also need ipv6 readiness in our components to support dual-stack.

Makes sense?

**Comment by booxter** [comment]
Still a reasonable issue / enhancement.

**Comment by SchSeba** [comment]
Still relevant 
/remove-lifecycle stale

**Comment by fabiand** [comment]
IPv6 can be delivered via additional networks, closing this as I did not see a strong push for this feature.

**Comment by larcher** [comment]
Apologies for bumping an old issue.   
@fabiand you say "IPv6 can be delivered via additional networks" -- can you provide an example, or point me toward the relevant docs?

I've been using the [Interfaces and Networks](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html) page so far.  My config is similar to the first example on that page.  That's working for IPv4 -- the VM receives an address over DHCP  -- but not for IPv6.  

Our cluster is currently using Kubevirt 0.16.0, but we'll be upgrading soon to 0.20.1

Thanks!


Our

**Comment by fabiand** [comment]
Hey Larry.

Usually I am referring to multus backed networks as explained here:
https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html#multus

With L2 networks provided by multus you can tie your VM into your existing
netwoirk or create an isolatd segment, and offer IPv6 on it.

**Comment by phoracek** [comment]
@larcher, not sure if you are familiar with Multus. In short, it allows you to connect your Pod/VM to an additional network. For instance, you can use [network-addons-operator](https://github.com/kubevirt/cluster-network-addons-operator) to install [Linux bridge CNI](https://github.com/kubevirt/cluster-network-addons-operator#linux-bridge). Then you would configure a Linux bridge on your nodes, connect them to external network, anything you want. Then you create a `NetworkAttachmentDefinition` exposing given bridge:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br10-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br10
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "br10-net",
      "plugins" : [
        {
          "type": "bridge",
          "bridge": "br10",
          "ipam": {}
        },
        {
          "type": "tuning"
        }
      ]
    }'
```

And finally, you can attach your VM to this bridge by following VM config:

```yaml
kind: VM
spec:
  domain:
    devices:
      interfaces:
        - name: default
          masquerade: {}
        - name: br10-net
          bridge: {}
  networks:
  - name: default
    pod: {} # Stock pod network
  - name: br10-net
    multus: # Secondary bridge network
      networkName: br10-net
``` 

By the way, we have a PR changing the Interfaces and Networks page to use `masquerade` instead of `bridge` for the pod network. Would be great if you could try it. There are known issues with the `bridge` binding. https://github.com/kubevirt/user-guide/pull/266
