### ISSUE TITLE
Two virtual machines created in the same cluster using masquerade mode have the same ip address

### ISSUE THREAD

**Issue by ILoveYou00** [kubevirt/kubevirt#10171]
## Environment
1. k8s : 1.23.0
2. kubevirt ： 0.58.0
3. Virtual machine image：windows server 2022 and centos7
4. yaml 
The deployment files for centos7 and windows 2022 are used as follows.
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win-2022
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win-2022
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win10-2022
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10-2022
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos7
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos7
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-centos7
      - name: harddrive
        persistentVolumeClaim:
          claimName: centos7
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
5. ip

centos

```yaml
2: ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:65:78:64 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 brd 10.0.2.255 scope global noprefixroute dynamic ens1
       valid_lft 86298923sec preferred_lft 86298923sec
    inet6 fe80::1c13:5294:2ac2:11e9/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
Windows is 10.0.2.2 like centos.

6. I manually configured the ip in windows as follows
![image](https://github.com/kubevirt/kubevirt/assets/99113924/a281d0c6-a30f-4d88-8e2b-01b99c573e1a)

I can't connect to the network with manually configured ip, I would like to know what is the problem and what can I do to make the ip not the same, thank you!
