### ISSUE TITLE
cloudInitNoCloud.networkDataSecretRef，cloudinit no network config applied

### ISSUE THREAD

**Issue by coldzerofear** [kubevirt/kubevirt#10180]
**What happened**:
Referencing networkconfig as a secret, cloudinit will not apply it，But using networkDataBase64 is no problem，I'm not sure if this is cloudinit's err

**What you expected to happen**:
The secret method seems to accommodate longer script content, and I hope to initialize the network config normally

**How to reproduce it (as minimally and precisely as possible)**:
use cloudInitNoCloud.networkDataSecretRef ，cloudinit no network config applied

**Additional context**:
cloudinit log 
```txt
2023-07-27 07:52:00,261 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2023-07-27 07:52:00,437 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2023-07-27 07:52:00,437 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2023-07-27 07:52:00,655 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpw9UCfY//network-config (quiet=False)
2023-07-27 07:52:00,655 - util.py[DEBUG]: Read 216 bytes from /run/cloud-init/tmp/tmpw9UCfY//network-config
    init.apply_network_config(bring_up=bool(mode != sources.DSMODE_LOCAL))
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 702, in apply_network_config
2023-07-27 07:57:02,424 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2023-07-27 07:57:02,465 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
2023-07-27 07:57:02,911 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
```
cloudinit error function
```python
    def apply_network_config(self, bring_up):
        # get a network config
        netcfg, src = self._find_networking_config()
        if netcfg is None:
            LOG.info("network config is disabled by %s", src)
            return

        # request an update if needed/available
        if self.datasource is not NULL_DATA_SOURCE:
            if not self.is_new_instance():
                if not self.datasource.update_metadata([EventType.BOOT]):
                    LOG.debug(
                        "No network config applied. Neither a new instance"
                        " nor datasource network update on '%s' event",
                        EventType.BOOT)
                    # nothing new, but ensure proper names
                    self._apply_netcfg_names(netcfg)
                    return
                else:
                    # refresh netcfg after update
                    netcfg, src = self._find_networking_config()
```

this is vm yaml
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    dcloud.tydic.io/disk-templates: '[{"metadata":{"annotations":{"dcloud.tydic.io/setControllerReference":"true"},"name":"root-0"},"spec":{"dataSource":{"image":{"name":"cwytestcentos8"}},"storage":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"ceph-hdd-block"}}}]'
  name: vm-test
  namespace: default
spec:
  running: true
  template:
    metadata:
      annotations:
        p4p1.default.kubernetes.io/logical_switch: p4p1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
          sockets: 1
          threads: 1
        devices:
          autoattachMemBalloon: false
          disks:
          - disk:
              bus: virtio
            name: root-0
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - macvtap: {}
            name: hostnetwork
            macAddress: 
          networkInterfaceMultiqueue: true
          rng: {}
        ioThreadsPolicy: auto
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
      networks:
      - multus:
          default: true
          networkName: default/p4p1
        name: hostnetwork
      nodeSelector:
        kubernetes.io/hostname: k8s-18
      terminationGracePeriodSeconds: 0
      volumes:
      - name: root-0
        persistentVolumeClaim:
          claimName: root-0
      - cloudInitNoCloud:
          networkDataSecretRef: 
            name: vm-test
          secretRef: 
            name: vm-test
        name: cloudinitdisk
```
this is secret yaml
```yaml
apiVersion: v1
data:
  networkdata: dmVyc2lvbjogMQpjb25maWc6Ci0gdHlwZTogcGh5c2ljYWwKICBuYW1lOiAiZXRoMCIKICBtdHU6IDE1MDAKICBtYWNfYWRkcmVzczogIjAwOjAwOjAwOjljOjg0OmZiIgogIHN1Ym5ldHM6CiAgLSB0eXBlOiBzdGF0aWMKICAgIGFkZHJlc3M6IDE3Mi4zMS4wLjU2CiAgICBuZXRtYXNrOiAyNTUuMjU1LjI1NS4wCiAgICBkbnNfbmFtZXNlcnZlcnM6CiAgICAtIDE3Mi4zMS4wLjE2Cg==
  userdata: I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiBUcnVlCnRpbWV6b25lOiBBc2lhL1NoYW5naGFpCmRpc2FibGVfcm9vdDogZmFsc2UKY2hwYXNzd2Q6IHsibGlzdCI6InJvb3Q6MTIzNDU2IixleHBpcmU6IEZhbHNlfQ==
kind: Secret
metadata:
  labels:
    kubevirt.io/secret: vm-test
  name: vm-test
  namespace: default
type: Opaque
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.3
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):  5.4.230-1.el8.elrepo.x86_64

**Comment by ormergi** [comment]
@coldzerofear also, I would dubble check the cloud-init network data:
```
version: 1
config:
- type: physical
  name: eth0
  mtu: 1500
  mac_address: 00:00:00:9c:84:fb  <------------------------- not set in VM spec
  subnets:
  - type: static
    address: 172.31.0.56
    netmask: 255.255.255.0
    dns_nameservers:
    - 172.31.0.16
```
It configures an interface by matching MAC address, but the interface MAC address is not set in the  VM spec.
