### ISSUE TITLE
Add serial and console schemas

### ISSUE THREAD

**Issue by sungwonh** [kubevirt/kubevirt#102]
VM spec needs "serials" and "consoles" as below to set up a serial console in a guest virtual machine. But schema.go does not have "serials" and "consoles" schemas.

Without a serial console, "cannot find character device <null>" error occurs when attempting to connect to a guest virtual machine.

```
apiVersion: kubevirt.io/v1alpha1
kind: VM
metadata:
  name: testvm
spec:
  domain:
    devices:
      graphics:
      - autoPort: "yes"
        type: vnc
        listen:
          type: address
          address: 127.0.0.1
      interfaces:
      - source:
          network: default
        type: network
      video:
      - Model:
          heads: 1
          type: cirrus
          vram: 16384
      disks:
      - type: file
        shapshot: internal
        device: disk
        driver:
          name: qemu
          type: qcow2
        diskSource:
          file: /var/lib/libvirt/images/cirros-0.3.4-x86_64-disk.img
        diskTarget:
          dev: hda
          bus: ide
      serials:
      - type: pty
        target:
          port: 0
      consoles:
      - type: pty
        target:
          type: serial
          port: 0
    memory:
      unit: KiB
      value: 524288
    name: testvm
    os:
      type:
        os: hvm
    type: qemu
  nodeSelector:
    kubernetes.io/hostname: master
```

**Comment by sungwonh** [comment]
I was able to connect to a guest VM console using the above VM spec after applying below commit.

https://github.com/sungwonh/kubevirt/commit/d24b903a6b0bbe2a562b774db7eb535dd6915c61

**Comment by rmohr** [comment]
@sungwonh very nice! :+1: 

Are you interested in creating a Pull Request for these changes?

**Comment by sungwonh** [comment]
@rmohr 
Yes, I am!
I just created a Pull Request for these changes.

**Comment by rmohr** [comment]
@sungwonh A side note: I see that you are also adding a `vnc` device. If you are using the vagrant environment ( and not the demo, the demo is a little bit behind regarding to that), you can als add a `spice` device there:

```yaml
      graphics:
      - autoPort: "yes"
        defaultMode: any
        type: spice
```

This has the advantage, that we are taking care of the port forwarding for spice via a proxy through kubernetes.
You can then directly connect to your VM from your machine via

```
cluster/kubectl.sh spice <vmname>
```

if you have `remote-viewer` installed.

Here is an [example yaml](https://github.com/kubevirt/kubevirt/blob/bfd0205ce7d41a0ee51e3e15ce75d4f5dd7050c1/cluster/vm.yaml).

More details on how this works can be found in the [getting started guide](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#accessing-the-domain-via-the-vms-spice-subresource)
