### ISSUE TITLE
Add a KubeVirt setting that allows adding custom labels to the ServiceMonitor

### ISSUE THREAD

**Issue by elchenberg** [kubevirt/kubevirt#10219]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

I want to collect the kubevirt-prometheus-metrics. I have configured KubeVirt to create a service monitor:

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
  [...]
spec:
  monitorAccount: kube-prometheus-stack-prometheus
  monitorNamespace: monitoring
  serviceMonitorNamespace: kubevirt
  [...]
```

This seems to work without issues because now there is a ServiceMonitor in my kubevirt namespace. But the metrics are not collected because my Prometheus is configured with a `serviceMonitorSelector`:

```yaml
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
```

I could not find a way to tell KubeVirt to add this label to the ServiceMonitor.

**Describe the solution you'd like**:

The KubeVirt CRD has a `serviceMonitorSelector` (or `serviceMonitorLabel`, `serviceMonitorAdditionalLabels`, ...) setting that can be used to configure a label that will be added to the ServiceMonitor, for example:

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
  [...]
spec:
  monitorAccount: kube-prometheus-stack-prometheus
  monitorNamespace: monitoring
  serviceMonitorNamespace: kubevirt
  serviceMonitorSelector:
    release: kube-prometheus-stack
  [...]
```

**Describe alternatives you've considered**:

I added the label manually and Prometheus started to scrape the metrics. But since the ServiceMonitor is managed by the virt-operator I would like to avoid manual changes.

**Additional context**:

Kubevirt v1.0.0
