### ISSUE TITLE
Using accessCredentials.userPassword secret resulted in the loss of vmi IP status

### ISSUE THREAD

**Issue by coldzerofear** [kubevirt/kubevirt#10210]
**What happened**:
When using macvtap cni to provide network for the vm, the ip state of the vmi is synchronously changed through qemu agent，If the VM also uses accessCredentials.userPassword at this time, it will cause the IP status of the VMI to be lost when synchronizing the userpassword

**What you expected to happen**:

vm configured userpassword secret and macvtap network
```yaml
…………
    spec:
      accessCredentials:
      - userPassword:
          propagationMethod:
            qemuGuestAgent: {}
          source:
            secret:
              secretName: 83da2c03-d274-4104-988d-c1f230a0e36f-userpassword
      domain:
        devices:
          interfaces:
          - macAddress: 52:54:00:cc:ab:52
            macvtap: {}
            model: virtio
            name: eth0
…………
```
Listening for the vmi status, it was found that the vmi ip disappeared after being synchronized and updated through qemu agent
```text
[root@srv11-kvm ~]# kubectl get vmi 83da2c03-d274-4104-988d-c1f230a0e36f -w
NAME                                   AGE     PHASE     IP             NODENAME   READY
83da2c03-d274-4104-988d-c1f230a0e36f   9m53s   Running   172.31.0.138   k8s-04     True
83da2c03-d274-4104-988d-c1f230a0e36f   10m     Running                  k8s-04     True
```
Normal after deleting the userpassword secret and restarting the VM. I suspect that there was a conflict between the two running at the same time, as the latter's update overwrites the former's update

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1、vm use macvtap cni
2、vm config userPassword secret
3、create vm
4、watch vmi ip status

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.3
