### ISSUE TITLE
I'm trying to create a windows VM and using virtio driver and getting error:

### ISSUE THREAD

**Issue by ILoveYou00** [kubevirt/kubevirt#10223]
1. yaml
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win-2022-template
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win-2022-template
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 2
            cdrom:
              bus: virtio
            name: cdromiso
          - cdrom:
              bus: virtio
            name: virtiocontainerdisk
          interfaces:
          - name: default
            model: virtio
            bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: test1
      - name: harddrive
        persistentVolumeClaim:
          claimName: win-2022-template
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```

```yaml
 persistentVolumeClaim:
          claimName: test1  # This one is windows-server-2022.iso
```
```yaml
persistentVolumeClaim:
          claimName: win-2022-template #This is my defined disk size
```

report an error:
* spec.template.spec.domain.devices.disks[1].cdrom.bus: Bus type virtio is invalid for CD-ROM device
* spec.template.spec.domain.devices.disks[2].cdrom.bus: Bus type virtio is invalid for CD-ROM device

What changes should I make to create
