### ISSUE TITLE
Remove volumeName and reference volumes from disks with the disk name

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1024]
###  Here what we do right now with disks

We reference a volume with an extra `volumeName` entry.

Here an example disk entry:

```yaml
      - disk:
          bus: virtio
        name: registrydisk
        volumeName: registryvolume
```

and here the matching volumes entry:
 
```yaml
  volumes:
  - name: registryvolume
    registryDisk:
      image: kubevirt/cirros-registry-disk-demo:devel
```

On pods it works differently. There every `volumeMount` has a name, which also matches the name of a volume.

We can do the same. Let the name of the disk reference a volume and remove `volumeName` in order to converge with how things are expressed on pods.

Follow up of this discussion: https://groups.google.com/d/msgid/kubevirt-dev/cfced0d7-7e24-4e99-a837-e1f2386ae94d%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by fabiand** [comment]
Taking the discussion from the [Network API discussion here](https://docs.google.com/a/redhat.com/document/d/10rXr91aqn8MvVcLgHw33WX8BaQwHPZERp25PHxoZGgw/edit?pli=1&disco=AAAAB-Hqdzs).

For reference:

Now:
```
disks:
- disk: {}
  name: fedora
  volumeName: fedora
…
volumes:
- name: fedora
  registryDisk:
    image: foo/bar
```

Then:
```
disks:
- disk: {}
  name: fedora
…
volumes:
- name: fedora
  registryDisk:
    image: foo/bar
```
