### ISSUE TITLE
miss  ipv6 address when passt interface

### ISSUE THREAD

**Issue by weizhoublue** [kubevirt/kubevirt#10259]
according to the document https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#passt , the passt supports IPv6 out of the box , and no need to configuring IPv6 manually.

but in my cluster with kubevirt v1.0.0 and dual-stack CNI, the VM with passt interface does not assign the ipv6 address

```
cat <<EOF | kubectl apply -f -
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-passthrough
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - passt: {}
            name: red
          rng: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: red
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: kubevirt/fedora-with-test-tooling-container-disk:devel
        name: containerdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #!/bin/bash
            echo "fedora" |passwd fedora --stdin
EOF
```

in the VM , just got ipv4 address (172.19.0.102/16)
```
~# virtctl console vm-passthrough-macvlan1
Successfully connected to vm-passthrough-macvlan1 console. The escape sequence is ^]
[fedora@vm-passthrough-macvlan1 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 172.19.0.102/16 brd 172.19.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe12:3456/64 scope link
       valid_lft forever preferred_lft forever
```

the corresponding launcher pod , there is ipv4(172.19.0.102/16) and ipv6(fc00:f853:ccd:e793::140/64) address assinged by the CNI. 
```
$ virt-launcher-vm-passthrough-macvlan1-5bkwn bashr-vm-passthrough-macvlan1-5bkwn
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-5.1$
bash-5.1$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 7a:64:93:ee:de:a3 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.102/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::140/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::7864:93ff:feee:dea3/64 scope link
       valid_lft forever preferred_lft forever
4: veth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether be:ee:2d:a7:37:01 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::bcee:2dff:fea7:3701/64 scope link
       valid_lft forever preferred_lft forever
```

I tested it with calico and underlay CNI , the result is same.

according to my understanding, if the CNI assigns dual-stack IP to the launcher pod,  the ipv6 address of launcher pod will be copied to the VM interface ?
