### ISSUE TITLE
VM CPU hotplug issue: VMI does not migrate after a socket count change

### ISSUE THREAD

**Issue by fl64** [kubevirt/kubevirt#10260]
**What happened**:

I've created a following virtual machine:

```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    vm: vm101
  name: vm-linux-101
  namespace: vms
spec:
  liveUpdateFeatures:
    cpu:
      maxSockets: 4
  running: true
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
      labels:
        kubevirt.io/vm: vm-linux
        vm: vm101
    spec:
      domain:
        cpu:
          cores: 1
          model: Nehalem
          sockets: 1
          threads: 1
        devices:
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        memory:
          guest: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: linux-boot-101
        name: boot
```

The creation was successful, after which I modified 

```yaml
spec:
  template:
    spec:
      domain:
        cpu:
          sockets: 2
```

And no migration of VM happend. Also weird logs in controller in the same time:

```
virt-handler {"component":"virt-handler","kind":"","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"vm-linux-101","namespace":"vms","pos":"vm.go:1912","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm-linux-101\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-08-08T18:11:54.707154Z","uid":"20b88522-0f9d-431a-a705-d671fbcea344"}
```

**What you expected to happen**:

After changing the number of sockets, the changes applied to VMI

**How to reproduce it (as minimally and precisely as possible)**:

Just apply VM manifest and after creation make changes to socket count

**Additional context**:

I did a manual migration of the VM, then in the VM I saw the new CPUs but they are labeled as `offline`.

htop output here:

```
  CPU[ *                          0.0%] Tasks: 13, 0 thr, 63 kthr; 1 running
  CPU[                         offline] Load average: 0.00 0.01 0.00 
  Mem[||#*@@@               36.5M/977M] Uptime: 00:03:42
  Swp[                           0K/0K]
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel (e.g. `uname -a`): 5.15.0-69-generic
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Hi @fl64,
Your VM cannot migrate because you are using bridge binding for your network. This is one of the limitations of migration-based CPU hotplug.
/cc @enp0s3 @vladikr Do we have documentation for this?

**Comment by enp0s3** [comment]
Hi,

Upstream documentation is still WIP, I hope to post a doc. PR next week. @fl64 @xpivarc I will keep you updated.

**Comment by xpivarc** [comment]
@fl64 Thanks for pointing that out. That should work. Do you have a workload updater configured?

**Comment by fl64** [comment]
@xpivarc I missed this setting :(

```yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    evictionStrategy: LiveMigrate
    developerConfiguration:
      featureGates: ["Macvtap","HotplugVolumes","Snapshot","ExpandDisks","Root","VMLiveUpdateFeatures","VMExport","Sidecar","VolumeSnapshotDataSource"]
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy:
    # added this:
    workloadUpdateMethods:
      - LiveMigrate

```

I added it and now the migration works after changing the number of sockets. But after migration only one processor is online, the rest are offline.

**Comment by enp0s3** [comment]
@fl64 Can you please check the following:
* whether the `HotVCPUChange` condition exists on the VMI status? 
* whether the `currentCPUTopology` in the VMI status equals to the topology in the spec?

**Comment by fl64** [comment]
@enp0s3 nope, just these:
```json
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-08-09T07:20:38Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": null,
      "status": "True",
      "type": "LiveMigratable"
    }
```
after migration i got:
```json
 kubectl get virtualmachineinstances.kubevirt.io vm-linux-101 -o json | jq '{ spec: .spec.domain.cpu, status: .status.currentCPUTopology }'
{
  "spec": {
    "cores": 1,
    "maxSockets": 4,
    "model": "Nehalem",
    "sockets": 2,
    "threads": 1
  },
  "status": {
    "cores": 1,
    "sockets": 2,
    "threads": 1
  }
}
```

**Comment by fl64** [comment]
I have checked it again:
Conditions just after creation on VM:
```yaml
- lastProbeTime: null
  lastTransitionTime: "2023-08-09T08:49:44Z"
  status: "True"
  type: Ready
- lastProbeTime: null
  lastTransitionTime: null
  status: "True"
  type: LiveMigratable
```
after changes:
```yaml
- lastProbeTime: null
  lastTransitionTime: "2023-08-09T08:49:44Z"
  status: "True"
  type: Ready
- lastProbeTime: null
  lastTransitionTime: null
  status: "True"
  type: LiveMigratable
- lastProbeTime: null
  lastTransitionTime: null
  status: "True"
  type: HotVCPUChange
```

at migration:
```yaml
- lastProbeTime: null
  lastTransitionTime: "2023-08-09T08:55:21Z"
  message: corresponding condition of pod readiness gate "kubevirt.io/virtual-machine-unpaused" does not exist.
  reason: ReadinessGatesNotReady
  status: "False"
  type: Ready
- lastProbeTime: null
  lastTransitionTime: null
  status: "True"
  type: LiveMigratable
```
