### ISSUE TITLE
Disk Serial Number not work on Window Server 2008 R2

### ISSUE THREAD

**Issue by Clyam** [kubevirt/kubevirt#10317]
**What happened**:
Hi，I'm trying to specify the serial number of one disk ，in order to identify the device after the vm started，so that the startup script will help me to init and format the device automatically。
window server 2012 and later is working fine，but window server 2008 R2 can not get the serial number。 
![image](https://github.com/kubevirt/kubevirt/assets/26684002/b7e868ca-6552-48a0-b530-58d6cc0456b0)
![image](https://github.com/kubevirt/kubevirt/assets/26684002/69c75815-22ef-455a-bab5-7726ad28af46)

**What you expected to happen**:
The ID should be what I set。 '945B95EK'

or 

any other way to identify the device that I added in the vm  

**How to reproduce it (as minimally and precisely as possible)**:
use window server 2008R2 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  1.0.0
- Kubernetes version (use `kubectl version`):  2.26.4
- VM or VMI specifications: 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windowserver2008-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName:  local-path
root@autovirt-k8s-training02-01:/opt/kubevirt/vm-wintest-scripts# cat vm-winserver2008-virtualbox.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-winserver2008-virtualbox
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm-winserver2008-virtualbox
    spec:
      domain:
        devices:
          disks:
          - name: rootpath
            bootOrder: 1
            disk:
              bus: sata
          - name: data
            serial: 945B95EK
            disk:
              bus: sata
          - name: cloudinitdisk
            cdrom:
              bus: sata
              readonly: true
          interfaces:
          - name: default
            model: e1000
            masquerade: {}
        resources:
          requests:
            memory: 4G
            cpu: 2
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootpath
          containerDisk:
            image: jenkins-virtualmachine/windowserver2008:6.1.7601
        - name: data
          persistentVolumeClaim:
            claimName: windowserver2008-pvc-test
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #ps1
              New-item -Path K:\jenkins -ItemType Directory
```
Thanks。
