### ISSUE TITLE
Unable to create VM on K3OS

### ISSUE THREAD

**Issue by cybercoder** [kubevirt/kubevirt#10344]
**What happened**:
k3os config:

```
k3os:
  modules:
    - kvm
    - vhost_net
  password: 123456
  dns_nameservers:
  - 8.8.4.4
  - 4.2.2.2
  ntp_servers:
  - 1.asia.pool.ntp.org
  k3s_args:
  - server
#  - "--cluster-reset"
  - "--node-ip=x.x.x.x"
  - "--node-external-ip=x.x.x.x"
  - "--disable-network-policy"
  - "--disable=service-lb"
  - "--disable=traefik"
  - "--disable=local-storage"
  - "--write-kubeconfig-mode=0644"
  - "--flannel-backend=none"
  - --kube-apiserver-arg
  - allow-privileged=true
  - --kube-apiserver-arg
  - oidc-username-claim=email
  - --kube-apiserver-arg
  - oidc-groups-claim=groups
  - --kube-apiserver-arg
  - oidc-client-id=k3s
  - --kube-apiserver-arg
  - oidc-issuer-url=https://iam.stg.ik8s.ir/oidc
  - --kube-apiserver-arg
  - cors-allowed-origins=http://localhost:3000
```
I've enabled guest virtualization on vmware esxi for this lab machine.

But there's errors with virt-handler on VM creation time:
```
virt-handler
{"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:275","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-08-25T15:29:46.497525Z"}
virt-handler
{"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:345","timestamp":"2023-08-25T15:29:46.497685Z"}
virt-handler
{"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:346","timestamp":"2023-08-25T15:29:46.497732Z"}
virt-handler
{"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:347","timestamp":"2023-08-25T15:29:46.497760Z"}
virt-handler
{"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.22.2+k3s2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): k3os
- Kernel (e.g. `uname -a`): 5.4.0-88-generic
- Install tools: N/A
- Others: Nested Virtualization enabled in ESXI
