### ISSUE TITLE
cannot found vm after create it 

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#10359]
**What happened**:

Create a vm by the following steps, but I can't get the vm after create it : 
```
root@node1:~/cxl# cat vm-example.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootfs
          containerDisk:
            image: kubevirt/cirros-registry-disk-demo
        - name: cloudinit
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
root@node1:~/cxl#
root@node1:~/cxl#
root@node1:~/cxl# kubectl apply -f vm-example.yaml
virtualmachine.kubevirt.io/testvm created
root@node1:~/cxl#
root@node1:~/cxl# kubectl get vm -A
No resources found
```

NOTE:  vmi resource works fine.

virt-controller log : 
```
{"component":"virt-controller","kind":"","level":"error","msg":"Updating api version annotations failed","name":"testvm","namespace":"default","pos":"vm.go:274","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"testvm\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-08-30T05:51:21.380229Z","uid":"a7e4d760-c2a8-4389-9a34-87216f8efe2c"}
{"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine default/testvm","pos":"vm.go:240","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"testvm\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-08-30T05:51:21.380323Z"}
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.24.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): `Linux node1 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`   
- Install tools: N/A
- Others: N/A
