### ISSUE TITLE
Need help with sriov not using OpenShift SR-IOV operator.

### ISSUE THREAD

**Issue by ns-rlewkowicz** [kubevirt/kubevirt#10358]
**Description**:
I would like to setup an sriov network not using this operator and I would like to manually configure the network attachment. I think we're using this:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin
Which I believe was the intel plugin which is commonly and sporadically referenced in the docs.

**What you expected**:
Someone else set up some of the underlying features and I don't want to go step on toes. I'd like docs that cover the core resources without an additional operator. 

I'd also like some understanding of how to get this into the VM and what I should expect for troubleshooting. Is dhcp supposed to just work? Of course it's redhat centric with redhat centric commands. 

From inside the vm, if I have 3 seemingly functional sriov nics how do I get the ips defined in my config to those vms? 

**URL**:
https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#how-to-expose-sr-iov-vfs-to-kubevirt

**Additional context**:
Add any other context about the issue here.

**Comment by aburdenthehand** [comment]
FYI @phoracek

**Comment by ormergi** [comment]
Hi Rayn,

On Kubevirt CI we setup ephemeral cluster for SR-IOV networking testings, not using the SR-IOV network operator.
You can refer to KubevirtCi repo to see how we configure ephemeral clusters for SR-IOV networking:
https://github.com/kubevirt/kubevirtci/tree/main/cluster-up/cluster/kind-1.27-sriov
https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind-1.27-sriov/config_sriov_cluster.sh

Basically first thing you need to do is make sure the relevant nodes has SR-IOV and IOMMU enabled in BIOS and kernel according to your HW.

As you figured out, to expose the nodes SR-IOV resources you need to deply [SR-IOV device plugin ](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin) 
You need to compose the SR-IOV device plugin configuration according to the cluster nodes and desired outcome

To use it in VMs you will need to deploy [Multus](https://github.com/k8snetworkplumbingwg/multus) and [SR-IOV](https://github.com/k8snetworkplumbingwg/sriov-cni) CNIs.

See the following gist, it present  an example for`NetworkAttachmentDefinition` for SR-IOV networking, VM spec with SR-IOV interfaces, and configuring static IP address using cloud-init.
https://gist.github.com/ormergi/8ac7da8efad3d6b5fe3c57edcc212e1b

I still recommend you to use the https://github.com/k8snetworkplumbingwg/multus) and [SR-IOV](https://github.com/k8snetworkplumbingwg/sriov-network-operator), it does most of the above and more automaticlly, enable changes on day2 and more..

If you have more questions feel free to ask on this thread.

**Comment by ns-rlewkowicz** [comment]
@EdDev 

> Not using the SR-IOV operator or using it, has no influence on KubeVirt. Kubevirt, once it detects the VM/VMI spec with the SR-IOV in it, will create the virt-launcher pod with the multus annotation that will eventually cause the VF to get plugged into the pod.

I believe I've made it through this. I'd like to give the exact exact output, but networking is hiccuped in np this morning. The following yaml creates my vmi. Only the userdata and container disk image are redacted. It's just ubuntu. 

This successfully allocated the ips to the virt launcher pod using multus and sriov. 

Lots of issues and posts online make it seem as if from here, I should be able to do dhcp on these virtual interfaces and just have those ips that are on the pod, in the vm. 

@ormergi This is awesome! Wish I had found it a week ago lol. My colleague took a similar approach. I was convinced there was some mechanisms that would allow me to avoid static setting in the cloud config.  

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: widget
spec: {}
status: {}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: sriov-vf/sriov_PF_1
  labels:
    argocd.argoproj.io/instance: sriov-plugin.dp-iad0
  name: vlan737-1
  namespace: widget
spec:
  config: '
  "type": "sriov",
  "cniVersion": "0.3.1",
  "vlan": 737,
  "name": "vlan737-1",
  "spoofchk": "off",
  "ipam": {
    "type": "host-local",
    "ranges": [
      [
        {
          "subnet": "10.136.208.0/20",
          "rangeStart": "10.136.223.250",
          "rangeEnd": "10.136.223.254",
          "gateway": "10.136.208.1"
        }
      ]
    ]
  }
}
'
---
apiVersion: v1
kind: Secret
metadata:
  name: userdata
  namespace: widget
  labels:
    kubevirt.io/secret: userdata
type: Opaque
data:
  userdata: redact
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: widget01
  namespace: widget
  labels:
    app.kubernetes.io/instance: virtual-machines
    app.kubernetes.io/name: dp-lab-ryan
    app.netskope.io/ansible_group: widget
    app.netskope.io/name: widget
    kubevirt.io/domain: widget01
    netskope.io/vm: "true"
spec:
  domain:
    resources:
      requests:
        cpu: "3"
        memory: 3Gi
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
        - name: emptydisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
      - name: sriov-1
        sriov: {}
      - name: sriov-2
        sriov: {}
      - name: sriov-3
        sriov: {}
  networks:
  - name: default
    pod: {}
  - name: sriov-1
    multus:
      networkName: widget/vlan737-1
  - name: sriov-2
    multus:
      networkName: widget/vlan737-1
  - name: sriov-3
    multus:
      networkName: widget/vlan737-1
  volumes:
    - name: emptydisk
      emptyDisk:
        capacity: 30Gi
    - containerDisk:
        image: redact
      name: containerdisk
    - cloudInitNoCloud:
        secretRef:
          name: userdata
      name: cloudinitdisk
```
