### ISSUE TITLE
Modify the container permissions of the starting VM pod

### ISSUE THREAD

**Issue by ILoveYou00** [kubevirt/kubevirt#10395]
## Deploying yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-centos
  name: centos-1
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: centos-1
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: local-path
      source:
        registry:
          url: docker://beyond.io:5000/centos7-500g:1.0
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-centos
      annotations:
          #kubernetes.customized/fabric-multi-networks: mgr-220-0,data-221-31
        kubernetes.customized/fabric-reservation: network-centos-1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
            - name: default
              bridge: {}
              model: virtio
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: centos-1
        name: datavolumedisk1
```
##  Creating Virtual Machines

![image](https://github.com/kubevirt/kubevirt/assets/99113924/0c348476-be2e-4cb8-bb5a-e4b1a66716a7)

## Modifying Container Permissions
```
kubectl edit pod virt-launcher-centos-1-m2qbh
```
![1694053311997](https://github.com/kubevirt/kubevirt/assets/99113924/35f4701a-d5f2-4507-a75c-26524be80b65)
If you change it to true, it will fail, is there any way to increase the container permissions?
