### ISSUE TITLE
Interface Tags Not Showing in meta_data.json

### ISSUE THREAD

**Issue by ns-rlewkowicz** [kubevirt/kubevirt#10401]
**What happened**:
Tagged interfaces, but no tags in meta_data.json 

**What you expected to happen**:
Tagged interfaces, tags in meta_data.json 

**How to reproduce it (as minimally and precisely as possible)**:
VMI with SRIOV
```
...
      interfaces:
      - name: default
        masquerade: {}
      - name: sriov-1
        tag: "1"
        sriov: {}
      - name: sriov-2
        tag: "2"
        sriov: {}
...
  networks:
  - name: default
    pod: {}
  - name: sriov-1
    multus:
      networkName: default/enp1s0f1
  - name: sriov-2
    multus:
      networkName: default/enp1s0f1
```

**Additional context**:
Perhaps it's because it's an SRIOV interface the tags don't work? 

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.58.1", GitCommit:"3951090bffaf56814889bcf44ec8db53a4e0b24e", GitTreeState:"clean", BuildDate:"2023-02-10T20:08:40Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.0.0", GitCommit:"579bb66545630d93b29d0399219aaa51c3f0a00b", GitTreeState:"clean", BuildDate:"2023-07-06T18:46:13Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
