### ISSUE TITLE
VM fails to boot in nested environment with virtio disk

### ISSUE THREAD

**Issue by scydas** [kubevirt/kubevirt#10430]
**What happened**:

vm status is running, but 
![image](https://github.com/kubevirt/kubevirt/assets/22952515/392925bb-daf0-499b-96bc-e7d346ad10f4)

**What you expected to happen**:

vm real runing

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
![image](https://github.com/kubevirt/kubevirt/assets/22952515/55d9e094-0a21-403d-9afc-8a6be5b78dc1)
![image](https://github.com/kubevirt/kubevirt/assets/22952515/efe95b8f-436d-4604-beee-32fa43faac82)

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.2
- Kubernetes version (use `kubectl version`): v1.23.10
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```
- Cloud provider or hardware configuration: 
vsphere virtual machine
![image](https://github.com/kubevirt/kubevirt/assets/22952515/59f58f07-1ced-4272-85b6-a3049824c557)

- OS (e.g. from /etc/os-release): 
![image](https://github.com/kubevirt/kubevirt/assets/22952515/bce96766-77ec-46a6-8eb6-1e52e9538386)
- Kernel (e.g. `uname -a`): 
```
Linux master 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
