### ISSUE TITLE
When creating an ubuntu VM, see that the VM memory is less than the actual allocated

### ISSUE THREAD

**Issue by ILoveYou00** [kubevirt/kubevirt#10452]
## yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-path
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: ubuntu
      - name: harddrive
        persistentVolumeClaim:
          claimName: ubuntu-template
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
## The situation is as follows
![image](https://github.com/kubevirt/kubevirt/assets/99113924/0d1ea73b-0c90-45ea-b757-45157c1ce786)
