### ISSUE TITLE
VM with liveUpdateFeatures is created with only one socket

### ISSUE THREAD

**Issue by fl64** [kubevirt/kubevirt#10462]
**What happened**:
I create VM with liveUpdateFeatures enabled feature and with the following cpu topology:

```yaml
spec:
  liveUpdateFeatures:
    cpu: {}
  template:
    spec:
      domain:
        cpu:
          cores: 1
          model: Nehalem
          threads: 1
          sockets: 3
```

After creating the VM, I only see 1 CPU (although I expected to see 3, according to topology).

**What you expected to happen**:
The number of CPUs in the running machine corresponds to the number specified in the CPU topology.

**How to reproduce it (as minimally and precisely as possible)**:
Just deploy this manifest:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    vm: vm101
  name: vms
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    cdi.kubevirt.io/storage.deleteAfterCompletion: "false"
  labels:
    vm: vm101
  name: linux-boot-101
  namespace: vms
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
    volumeMode: Block
  source:
    registry:
      pullMethod: node
      url: docker://docker.io/fl64/alpine-3-18:latest
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    vm: vm101
  name: vm-linux-101
  namespace: vms
spec:
  liveUpdateFeatures:
    cpu: {}
  running: true
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
      labels:
        kubevirt.io/vm: vm-linux
        vm: vm101
    spec:
      domain:
        cpu:
          cores: 1
          model: Nehalem
          sockets: 3
          threads: 1
        devices:
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        memory:
          guest: 1Gi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 3
      volumes:
      - dataVolume:
          name: linux-boot-101
        name: boot
```

**Additional context**:
If I change the number of sockets, for example to 2, after the livemigration process I see 2 CPUs.

Everything fine with sockets count without liveUpdateFeatures. I see all 3 CPUs.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.8
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
