### ISSUE TITLE
Live migration with Affinity

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10475]
**Is your feature request related to a problem? Please describe**:
Right now, live migration can not select node for target launcher pod. I think add Affinity for target launcher pod is not difficult. Do we need this feature?

**Describe the solution you'd like**:
Create VirtualMachineInstanceMigration like this :
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceMigration
metadata:
  name: migration-job
spec:
  vmiName: vmi-fedora
  Affinity: XXXXXXX
```
will add Affinity on target launcher pod after all Affinity like NodeAffinityForHostModelCpuModel has been setted. 

**Describe alternatives you've considered**:

**Additional context**:
