### ISSUE TITLE
VM's root partition doesn't fit the DV size

### ISSUE THREAD

**Issue by 66545shiwo** [kubevirt/kubevirt#10474]
**What happened**:
The root disk of the VM does not match the size of the cloned PVC by DV.

**What you expected to happen**:
vm's root disk fits the cloned pvc size.

**How to reproduce it (as minimally and precisely as possible)**:
My source PVC(CAPACITY:19Gi):
```
# kubectl get pvc -n vm-images 
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
centos7.7-desk   Bound    pvc-8009ab0a-3f72-4fd3-8116-10cd4b11dcc2   19Gi       RWO            rook-ceph-block   4d7h
```
And I created a vm by `dataVolumeTemplates`(CAPACITY:50Gi):
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "centos-x86-7.7-desk-test"
  namespace: default
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: centos7.7-desk-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-ceph-block
      source:
        pvc:
          name: centos7.7-desk
          namespace: vm-images
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: centos.dd
    spec:
      domain:
        devices:
          disks:
            - name: bootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - disk:
              name: serviceaccountdisk
          interfaces:
            - name: default
              bridge: {}
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: serviceaccountdisk
          serviceAccount:
            serviceAccountName: clone-user
        - dataVolume:
            name: centos7.7-desk-dv
          name: bootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: True
              users:
                - name: dev
              chpasswd:
                list: |
                  root:root123
                  dev:dev123
                expire: False
```
The capacity of the root disk for the VM, however, is 17.5Gi:

```
# kubectl get dv 
NAME                PHASE       PROGRESS   RESTARTS   AGE
centos7.7-desk-dv   Succeeded   100.0%                27m

# kubectl get pvc 
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
centos7.7-desk-dv        Bound    pvc-32e64519-5046-4278-8578-067f195f43a1   50Gi       RWO            rook-ceph-block   27m

# kubectl get vm 
NAME                       AGE   STATUS    READY
centos-x86-7.7-desk-test   25m   Running   True
# virtctl console centos-x86-7.7-desk-test 
Successfully connected to centos-x86-7.7-desk-test console. The escape sequence is ^]

[root@centos-x86-7 ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0    1M  0 disk 
vda    253:0    0 17.5G  0 disk 
├─vda1 253:1    0    1G  0 part /boot
├─vda2 253:2    0 1023M  0 part [SWAP]
└─vda3 253:3    0 15.5G  0 part /
vdb    253:16   0    1M  0 disk 
# fdisk -l 

Disk /dev/vda: 18.8 GB, 18789433344 bytes, 36698112 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000d92c5

   Device Boot      Start         End      Blocks   Id  System
/dev/vda1   *        2048     2099199     1048576   83  Linux
/dev/vda2         2099200     4194303     1047552   82  Linux swap / Solaris
/dev/vda3         4194304    36698078    16251887+  83  Linux

Disk /dev/vdb: 1 MB, 1048576 bytes, 2048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sda: 1 MB, 1048576 bytes, 2048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.27.6
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: private kubernetes
- OS (e.g. from /etc/os-release): centos7.6
- Kernel (e.g. `uname -a`): 4.19.12-1.el7.elrepo.x86_64
- Install tools: N/A
- Others: CDI: 1.57
