### ISSUE TITLE
Expand liveUpdateFeatures to live update pod field when update vm

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10485]
**Is your feature request related to a problem? Please describe**:
Some CNI just like kube-ovn use pod annotations to setup pod network. Update pod annotations when update vm.spec.template.metadata.annotations is useful.　

**Describe the solution you'd like**:
We can create vm like:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: false
  liveUpdateFeatures:
    annotations: {
        upatepod: true
    }
template:
```
and it will update launcher pod annotations when update vm.spec.template.metadata.annotations.

**Describe alternatives you've considered**:

**Additional context**:
