### ISSUE TITLE
kubevirt cannot discover all hostdevices

### ISSUE THREAD

**Issue by gunine** [kubevirt/kubevirt#10503]
**What happened**:
KubeVirt's embedded device controller is unable to discover all host devices.
We have one Fiber Channel (FC) Card which has two ports and followings are the output the lspci. 
Both of the two controllers are bound to vfio-pci driver already.
```
$ lspci -nnk
...
0002:01:00.0 Fibre Channel [0c04]: QLogic Corp. ISP2812-based 64/32G Fibre Channel to PCIe Controller [1077:2281] (rev 02)
	Subsystem: Hewlett Packard Enterprise SN1610Q – 2P Enhanced 32GFC Dual Port Fibre Channel Host Bus Adapter [1590:02d4]
	Kernel driver in use: vfio-pci
	Kernel modules: qla2xxx
0002:01:00.1 Fibre Channel [0c04]: QLogic Corp. ISP2812-based 64/32G Fibre Channel to PCIe Controller [1077:2281] (rev 02)
	Subsystem: Hewlett Packard Enterprise SN1610Q – 2P Enhanced 32GFC Dual Port Fibre Channel Host Bus Adapter [1590:02d4]
	Kernel driver in use: vfio-pci
	Kernel modules: qla2xxx
...
```

To passthrough the two controllers to VM, we added both vendor id and product id two permittedHostDevices as follows.
```
...
configuration:
      permittedHostDevices:
        pciHostDevices:
        - externalResourceProvider: false
          pciVendorSelector: 1077:2281
          resourceName: marvell.com/fc
...
```
However, kubevirt only discovers 1 device as follows.
```
...
  allocatable:
    ...
    marvell.com/fc: "1"
    memory: 535073216Ki
    ovs-cni.network.kubevirt.io/br-int: 1k
    ovs-cni.network.kubevirt.io/br-tun: 1k
    pods: "110"
  capacity:
    ...
    marvell.com/fc: "1"
    memory: 535175616Ki
    ovs-cni.network.kubevirt.io/br-int: 1k
    ovs-cni.network.kubevirt.io/br-tun: 1k
    pods: "110"
...
```

**What you expected to happen**:
Kubevirt should discover two FC controllers not 1.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Additional context**:
N/A

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): 1.27.6
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Rocky 8,8
- Kernel (e.g. `uname -a`): 4.18.0-477.21.1.el8_8.aarch64
- Install tools: N/A
- Others: N/A
