### ISSUE TITLE
VMs without guest memory settings cannot start

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#10521]
**What happened**:

I created a VM without an instancetype nor any other settings related to guest memory. The VM was created successfully (it passed vm-mutator/vm-admitter), but it cannot be started, because a VMI cannot be created from it (VMI does not pass vmi-admitter).

**What you expected to happen**:
I expected the created VM to be able to start. When no memory is specified, the vmi-mutator should set a default value (e.g. `512Mi` and similar to CPUs, e.g. if no CPU is provided we default to 1 socket, 1 core, 1 thread).

**How to reproduce it (as minimally and precisely as possible)**:
- Create VM with provided YAML
- Run `virtctl start vm-cirros`
- Run `kubectl get vm vm-cirros -o yaml` to observe failure in status conditions

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-cirros
spec:
  running: false
  template:
    spec:
      domain:
        devices: {}
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: containerdisk

```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
