### ISSUE TITLE
Disk expansion failure

### ISSUE THREAD

**Issue by znaive** [kubevirt/kubevirt#10552]
Environment:

KubeVirt version : v0.58.0
Kubernetes version : v1.23.0

1. I added a data disk to the virtual machine
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win2012-migration2
spec:
  storageClassName: loop3-carina
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

2. Shutting down the virtual machine
3. I expanded the pvc to 4G.

```yaml
$ kubectl edit pvc ....
$ kubectl get pvc
kubevirt1010   data01                  Bound    pvc-5ba2b465-a231-44a7-a989-6be0edf238e1   4Gi        RWO            loop3-carina   85m
```
4. Turn on the virtual machine
```yaml
virtctl start vm-name
```
5. View Virtual Machine
![image](https://github.com/kubevirt/kubevirt/assets/140578525/db8b168a-eea2-4184-8cd2-889cc9cd1aef)

Even if I format the data disk in the VM, or disable and then enable it still doesn't work, is it unsupported?
