### ISSUE TITLE
virtctl create vm with --volume-import may lead to VMs taking ownership of cloned DVs

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#10592]
**What happened**:

`virtctl create vm --volume-import=type:pvc,name:fedora,namespace:default,size:10Gi` will result in a VM with the following dataVolumeTemplates:

```
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: fedora
    spec:
      source:
        pvc:
          name: fedora
          namespace: default
      storage:
        resources:
          requests:
            storage: 10Gi
```

If the PVC that is going to be cloned was created from a DV and is in the same namespace as the VM then the VM is going to take ownership of the already existing DV, which can lead to confusing behavior.

**What you expected to happen**:

The source and name of a volume to be imported with `type:pvc` and `type:snapshot` should be decoupled, e.g. like with `--volume-clone-pvc`, which has two parameters `src` and `name`.

**How to reproduce it (as minimally and precisely as possible)**:

- Create DV named fedora in namespace default (see [1])
- Create VM with `virtctl create vm --name fedora --volume-import=type:pvc,name:fedora,namespace:default,size:10Gi`
- Delete VM with `kubectl delete vm fedora`
- Observe DV `fedora` being deleted too

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1]

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  labels:
    instancetype.kubevirt.io/default-preference: fedora
    instancetype.kubevirt.io/default-instancetype: u1.medium
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/fedora:latest
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```
