### ISSUE TITLE
VM Migrations fail on clusters with cri-o version v1.28 

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/kubevirt#10616]
**What happened**:

The latest 1.28 release of cri-o has broken the migration conformance tests. This was encountered when trying to update the version of cri-o in kubevirtci[1]

It looks like we depend on the Image ID including the image digest[2] when creating the migration template which is no longer the case due to changes with how cri-o handles the image ID [3].

`{"component":"virt-controller","level":"info","msg":"reenqueuing Migration kubevirt-test-default1/test-migration-xpb7q","pos":"migration.go:233","reason":"failed to render launch manifest: can not proceed with the migration when no reproducible image digest can be detected: failed to identify image digest for container \"registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel\" with id \"8aba57ea67e3518f3b7fcbf32954bd2c0bd60d46ed55672a0fcec66076d4a6d4\"","timestamp":"2023-10-23T15:22:33.398815Z"}`

```
[root@node02 vagrant]# crictl images -o yaml registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel
images:
- id: 8aba57ea67e3518f3b7fcbf32954bd2c0bd60d46ed55672a0fcec66076d4a6d4
  pinned: false
  repoDigests:
  - registry:5000/kubevirt/alpine-with-test-tooling-container-disk@sha256:6f11f0558a09ae3d3cb88935d88d00f9f8e32f2396f251efc4a88d41bb0204ba
  repoTags:
  - registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel
  size: "160773933"
  spec: null
  uid: null
  username: ""
```

I ran the sig-compute-migrations suite against the newly published provider and this results in the majority of tests failing.

[1] https://github.com/kubevirt/kubevirtci/pull/1078
[2] https://github.com/kubevirt/kubevirt/blob/40b219b37714475a998c2cfd6129b9635400502a/pkg/container-disk/container-disk.go#L443
[3] https://github.com/cri-o/cri-o/pull/7149

**What you expected to happen**:
Migration to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to migrate a containerdisk based VM with crio v1.28 as the container runtime

**Additional context**:
Failed check-provision logs: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1078/check-provision-k8s-1.28/1716431053721178112

**Environment**:
- KubeVirt version (use `virtctl version`): Latest main (ae1014b26f9c49c373891903e83c6cc07d31e3b8)
- Kubernetes version (use `kubectl version`): v1.28.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: kubevirtci
- OS (e.g. from /etc/os-release): CentOS Stream 9
- Kernel (e.g. `uname -a`): 5.14.0-372.el9.x86_64
- Install tools: N/A
- Others: crio v1.28.1
