### ISSUE TITLE
 Convert vmware's vmdk to qcow2 through the tool qemu; the virtual machine fails to start

### ISSUE THREAD

**Issue by ZhangSetSail** [kubevirt/kubevirt#10644]
**What happened**:

the virtual machine fails to start

**What you expected to happen**:

Virtual machine started successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow this [document](https://www.cnblogs.com/rainbow-tan/p/16543513.html)
2. create dv
```
virtctl image-upload xxx
```
3. create vmi
<img width="696" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/5815da91-25de-4a7f-8889-4c6cd26b7c63">
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk 
        persistentVolumeClaim:
          claimName: cen7 
```

**Additional context**:

I want to test migrating a virtual machine on vmware to kubevirt. At the same time, I want to migrate the status of the original virtual machine to kubevirt.
The exported formats in vmware are OVF and OVA, while the formats accepted by kubevirt are image, ISO, and qcow2. So I looked for some tools to convert and encountered this problem.

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`): 1.23
- VM or VMI specifications: 
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
