### ISSUE TITLE
VirtualMachineInstance.status.guestOSInfo switch between having a value and empty value

### ISSUE THREAD

**Issue by moshuipan** [kubevirt/kubevirt#10660]
**What happened**:
VirtualMachineInstance.status.guestOSInfo always empty,but somtimes which have a value, the vm's status is running.

```yaml
status:
  activePods:
    42a8a6d4-bbe1-4ad1-9746-fc7ee4c69ae3: xxxxx
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-01T09:07:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  - lastProbeTime: "2023-11-01T09:08:24Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  - lastProbeTime: null
    lastTransitionTime: "2023-11-01T09:08:37Z"
    status: "True"
    type: AccessCredentialsSynchronized
  guestOSInfo:     #**this filed always empty**
    id: centos
    kernelRelease: 3.10.0-1160.88.1.el7.x86_64
    kernelVersion: '#1 SMP Tue Mar 7 15:41:52 UTC 2023'
    name: CentOS Linux
    prettyName: CentOS Linux 7 (Core)
    version: "7"
    versionId: "7"
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    ipAddress: xxxxx
    ipAddresses:
    - xxxx
    - xxx
    mac: xxxx
    name: xxx
    queueCount: 1
```

**What you expected to happen**:
the running vm has a correct VirtualMachineInstance.status.guestOSInfo  field

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.23.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 5.14.0-1.0.38.x86_64
- Install tools: N/A
- Others: N/A
