### ISSUE TITLE
Make mac address specifiable

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1069]
We need a field to specify the MAC address of a network interface i.e.

```yaml
kind: VM
spec:
  interfaces:
  - name: foo
    mac: 00:00:11:22:33:44
```

It could be that the mac is not selectable for all model or all banckends.
