### ISSUE TITLE
the original launcher Pod Error after the migration

### ISSUE THREAD

**Issue by Icarus9913** [kubevirt/kubevirt#10695]
**What happened**:
Once I create a vm and migrate it, the new migrated Pod runs well but the previous pod container guest-console-log  exit with code 1. Consequently, the pod's Status.Phase is Error

**What you expected to happen**:
The original completed with Succeed status

**How to reproduce it (as minimally and precisely as possible)**:
1. create a VM
2. migrate it

**Additional context**:
/

**Environment**:
- KubeVirt version (use `virtctl version`): `v1.1.0`
- Kubernetes version (use `kubectl version`): `v1.27.1`
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: kubevirt/cirros-container-disk-demo:latest
        name: containerdisk
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
