### ISSUE TITLE
Support to set a specify  hostName for a CloneVM

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10742]
**Is your feature request related to a problem? Please describe**:
sometimes we want to set hostname for CloneVM just as the VM which can be set hostname.

**Describe the solution you'd like**:
we can writer a yaml file to set CloneVM hostname. 
we can set <**hostname: vmclone**>
```yaml
kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
  name: testclone
spec:
  # target definitions hostname
  hostname: vmclone
```
**Describe alternatives you've considered**:
**Additional context**:
