### ISSUE TITLE
How to clone a virtual machine using pvc？

### ISSUE THREAD

**Issue by binweee** [kubevirt/kubevirt#10744]
I use CDI to import the local centos image into the pvc. The command is as follows
```
virtctl image-upload \
  --image-path='CentOS-7-x86_64-Minimal-2009.iso' \
  --pvc-name=centos \
  --pvc-size=4G \
  --uploadproxy-url=https://10.104.37.186:443 \
  --storage-class='managed-nfs-storage' \
  --insecure
```
Then after creating a 20G pvc, I used the following yaml to create the virtual machine
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-centos
spec:
  running: true
  template:
    metadata:
      labels:
        app: centos
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - bootOrder: 1
              name: cdromiso
              cdrom:
                bus: sata
            - disk:
                bus: sata
              name: disk1
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - persistentVolumeClaim:
          claimName: centos
        name: cdromiso
      - name: disk1
        persistentVolumeClaim:
          claimName: pvc-vm1
```
I have completed the installation of the system and performed some operations on the system. For example, I downloaded docker using yum, and now I want to use this virtual machine as a template to create an identical virtual machine. The new virtual machine also has docker downloaded by yum, and the new virtual machine also uses pvc as disk.
How to do it？
