### ISSUE TITLE
virt-launcher pod usage 300Mi+ mem

### ISSUE THREAD

**Issue by Erick-shi** [kubevirt/kubevirt#10793]
**What happened**:
My kubevirt env. when lauche a vm ,but the virt-launcher pod usage 300Mi + mem , that's  normal phenomenon？
```bash
[root@master ~]# kubectl  top pod
NAME                               CPU(cores)   MEMORY(bytes)
virt-launcher-myvmi-4cz28          4m           302Mi
virt-launcher-testvm-nic-2-87z5d   305m         303Mi
virt-launcher-testvm-small-xtctd   3m           368Mi
virt-launcher-vm-multi-nic-rfkkw   344m         333Mi
[root@master ~]#
```

**What you expected to happen**:
I think the virt-launcher should use less mem.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl  top pod

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0
- Kubernetes version (use `kubectl version`): v1.26.11
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vladikr** [comment]
@Erick-shi could you please add the vmi and the pod specs?

**Comment by Erick-shi** [comment]
hi, this is my vm yaml
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-multi-nic
spec:
  #runStrategy: RerunOnFailure
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-multi-nic
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - masquerade: {}
              model: virtio
              name: pod-net
            - name: vm-multi-nic
              bridge: {}
        resources:
          requests:
            memory: 664M
      networks:
      - name: pod-net
        pod: {}
      - name: vm-multi-nic
        multus:
          networkName: default/bridge-test
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: my-vmi-secret
```
and can find the vm use vm
```bash
[root@master mutinic]# kubectl  top pod
NAME                               CPU(cores)   MEMORY(bytes)
virt-launcher-myvmi-4cz28          4m           304Mi
virt-launcher-testvm-small-llzl4   4m           354Mi
virt-launcher-vm-multi-nic-hvrvj   716m         363Mi
[root@master mutinic]#
```
if I have any wrong, please point out.

**Comment by matthewei** [comment]
could you use prometheus to monitor it? if you don't have prometheus and I think you can login the virt-launcher-pod and execute the fllowing command `virsh dommemstat 1`

**Comment by Erick-shi** [comment]
> could you use prometheus to monitor it? if you don't have prometheus and I think you can login the virt-launcher-pod and execute the fllowing command `virsh dommemstat 1`
```bash
```bash
[root@node-1 ~]# kubectl  top pods
NAME                                      CPU(cores)   MEMORY(bytes)
virt-launcher-cirros-openstack-vm-wgfcz   6m           340Mi
virt-launcher-testvm-wbqzk                4m           288Mi
[root@node-1 ~]# kubectl  exec -it virt-launcher-cirros-openstack-vm-wgfcz bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead
bash-5.1$ virsh list
Authorization not available. Check if polkit service is running or see debug message for more information.
 Id   Name                          State
---------------------------------------------
 1    default_cirros-openstack-vm   running

bash-5.1$ virsh dommemstat default_cirros-openstack-vm
Authorization not available. Check if polkit service is running or see debug message for more information.
actual 1048576
swap_in 0
swap_out 0
major_fault 25
minor_fault 869917
unused 979504
available 1016252
usable 916780
last_update 1702344098
rss 287828

bash-5.1$
```

**Comment by Longchuanzheng** [comment]
You can add `overcommitGuestOverhead: true` in 
```
spec:
  template:
    spec:
      domain:
        resources:
          overcommitGuestOverhead: true
          requests:
            memory: 1024M
```
to disable it.
