### ISSUE TITLE
cpu host-passthrough failed

### ISSUE THREAD

**Issue by cyent** [kubevirt/kubevirt#10830]
**What happened**:
I want to enable cpu host-passthrough, but it failed

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: scrapy
  namespace: biz-scrapy
spec:
  runStrategy: Manual
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      domain:
        devices:
          disks:
            - name: sys
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        cpu:
          cores: 4
          model: host-passthrough
        resources:
          requests:
            memory: 12Gi
          limits:
            memory: 12Gi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: sys
          dataVolume:
            name: scrapy-sys
```

```
kubectl describe vmi scrapy -n biz-scrapy
Name:         scrapy
Namespace:    biz-scrapy
Labels:       kubevirt.io/nodeName=k8s-202
Annotations:  kubevirt.io/allow-pod-bridge-network-live-migration: true
              kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1
              kubevirt.io/vm-generation: 1
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2023-12-04T07:14:13Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  9
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  scrapy
    UID:                   665377bf-a1f7-439f-afe9-ebdecddcfc5a
  Resource Version:        10763416
  UID:                     d46a5b69-46e2-4f78-a26e-a70f49cbec74
Spec:
  Architecture:  amd64
  Domain:
    Cpu:
      Cores:  4
      Model:  host-passthrough
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   sys
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  36936d68-15a5-5aad-b572-af5df8cf80d2
    Machine:
      Type:  q35
    Resources:
      Limits:
        Memory:  12Gi
      Requests:
        Memory:       12Gi
  Eviction Strategy:  None
  Networks:
    Name:  default
    Pod:
  Volumes:
    Data Volume:
      Name:  scrapy-sys
    Name:    sys
Status:
  Active Pods:
    689ad1df-42b7-431d-bb88-788016f1d6fa:  k8s-202
  Conditions:
    Last Probe Time:       2023-12-04T07:19:39Z
    Last Transition Time:  2023-12-04T07:19:39Z
    Message:               virt-launcher pod is terminating
    Reason:                PodTerminating
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
  Current CPU Topology:
    Cores:    4
    Sockets:  1
    Threads:  1
  Guest OS Info:
  Interfaces:
    Info Source:  domain
    Ip Address:   10.5.244.2
    Ip Addresses:
      10.5.244.2
    Mac:                             00:00:00:0e:fd:63
    Name:                            default
    Queue Count:                     1
  Launcher Container Image Version:  quay.io/kubevirt/virt-launcher:v1.1.0
  Machine:
    Type:  pc-q35-rhel9.2.0
  Memory:
    Guest Current:      12Gi
  Migration Method:     LiveMigration
  Migration Transport:  Unix
  Node Name:            k8s-202
  Phase:                Failed
  Phase Transition Timestamps:
    Phase:                        Pending
    Phase Transition Timestamp:   2023-12-04T07:14:13Z
    Phase:                        Scheduling
    Phase Transition Timestamp:   2023-12-04T07:14:14Z
    Phase:                        Scheduled
    Phase Transition Timestamp:   2023-12-04T07:14:24Z
    Phase:                        Failed
    Phase Transition Timestamp:   2023-12-04T07:20:06Z
  Qos Class:                      Burstable
  Runtime User:                   107
  Selinux Context:                none
  Virtual Machine Revision Name:  revision-start-vm-665377bf-a1f7-439f-afe9-ebdecddcfc5a-1
  Volume Status:
    Name:  sys
    Persistent Volume Claim Info:
      Access Modes:
        ReadWriteMany
      Capacity:
        Storage:            50Gi
      Filesystem Overhead:  0
      Requests:
        Storage:    50Gi
      Volume Mode:  Block
    Target:         vda
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  28m                 virtualmachine-controller  Created virtual machine pod virt-launcher-scrapy-h8rt6
  Warning  SyncFailed        23m (x18 over 28m)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: CPU mode 'host-passthrough' for x86_64 qemu domain on x86_64 host is not supported by hypervisor')"
  Warning  SyncFailed        22m                 virt-handler               failed to detect VMI pod: dial unix //pods/689ad1df-42b7-431d-bb88-788016f1d6fa/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused
  Warning  Stopped           22m                 virt-handler               The VirtualMachineInstance crashed.
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0
- Kubernetes version (use `kubectl version`): v1.28.2
- OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): Linux k8s-202 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- CPU：
```
processor       : 23
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping        : 4
microcode       : 0x42e
cpu MHz         : 1200.000
cache size      : 15360 KB
physical id     : 1
siblings        : 12
core id         : 5
cpu cores       : 6
apicid          : 43
initial apicid  : 43
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 4201.56
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
- Machine: Dell PowerEdge R620
