### ISSUE TITLE
Implement greater fidelity in selecting virtual function devices to pass through

### ISSUE THREAD

**Issue by notgull** [kubevirt/kubevirt#10850]
**Is your feature request related to a problem? Please describe**:

I am working with an SRIOV-enabled PCI-e device that isn't a network interface. It exports a fixed number of virtual functions (VFs) which I intend to forward into virtual machines created by Kubevirt. Since it is not a network interface I was going to use the PCI passthrough functionality as described [here](https://kubevirt.io/user-guide/virtual_machines/host-devices/), as opposed to Multus/CNI.

However, for this device each VF corresponds to a specific resource identifier. To clarify, the first and second VFs refer to entirely different, persistent resources that need to be assigned to specific VMs. However, Kubevirt only supports selecting devices based on their PCI vendor ID and PCI device ID's. Since both VFs have the same vendor and PCI ID, there is no way in Kubevirt's CR to differentiate between them.

```yaml
    configuration:
      permittedHostDevices:
        pciHostDevices:
        - pciVendorSelector: 1111:2222 # <-- multiple devices can have this ID
          resourceName: devices.kubevirt.io/foobar
```

**Describe the solution you'd like**:

I would like to see an index-based solution, where the user can select the `N`th device that matches the particular vendor/PCI ID pair. For instance, the manifest would then read:

```yaml
    configuration:
      permittedHostDevices:
        pciHostDevices:
        - pciVendorSelector: 1111:2222
          resourceName: devices.kubevirt.io/foobar1
          index: 1 # <-- select the second (zero-indexed) device that matches the PCI vendor selector
        - pciVendorSelector: 1111:2222
          resourceName: devices.kubevirt.io/foobar2
          index: 2 # <-- select the third (zero-indexed) device that matches the PCI vendor selector
```

This would allow me to specifically assign VF 1 to a virtual machine, and VF 2 to another virtual machine of my choosing.

**Describe alternatives you've considered**:

Alternative ways of differentiating between one or more PCI devices with the same vendor/device ID combination. For instance, the PCI address could also be used here:

```yaml
    configuration:
      permittedHostDevices:
        pciHostDevices:
        - pciAddress: 85:00.0 # <-- different kind of selector
          resourceName: devices.kubevirt.io/foobar
```

As far as I am aware, however, the PCI address can vary from system to system. So I imagine that it is not a very reliable form of addressing PCI-e devices.

[This article](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-pci-devices) also mentions ways of identifying PCI devices using a string-based identifier. However, it seems to be Windows-exclusive from a brief investigation.

**Additional context**:

I will submit a PR once the maintainers decide which design works best for their use case.

**Comment by xpivarc** [comment]
@vladikr any thoughts?

**Comment by vladikr** [comment]
Hi @notgull 

The `permittedHostDevices` API was designed to handle identical stateless devices. It can be enhanced.
However, I'm not sure that the suggested indexes are the right approach.
Think about having multiple identical cards on multiple nodes. Manually indexing will not scale.

On a small scale, you can write your own device plugin that will allocate a device by a PCI address on a node with a specific resource name. 
Then, you can add the device as an externalResourceProvider,:

```
configuration:
      permittedHostDevices:
        pciHostDevices:
        - pciVendorSelector: 1111:2222
          resourceName: devices.kubevirt.io/foobar1
          externalResourceProvider: true
```

I wonder what is the purpose of these devices. Are these VFs stateful?
In this case, I think [Dynamic Resource Allocation](https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/), which we are planning to integrate once it's stable, will be a better fit, rather than the current API.
