### ISSUE TITLE
vm ip is diffrent from kubectl get vmi 

### ISSUE THREAD

**Issue by Erick-shi** [kubevirt/kubevirt#10887]
**What happened**:
when I create a pysical network with  **bridge-test** ,
```yaml
apiVersion: "k8s.cni.cncf.io/v1"kind: NetworkAttachmentDefinitionmetadata:  name: bridge-testspec:  config: '{
      "cniVersion": "0.4.0",
      "name": "bridge-test",
      "type": "bridge",
      "bridge": "br1",
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.32.0/24",
        "rangeStart": "172.16.32.226",
        "rangeEnd": "172.16.32.228",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.16.32.1"
      }
    }'
```
and I want to  create a vm with the **bridge-test** network, with yml
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: nginx-provisioner
  name: cirros-openstack-vm-special-ip
  namespace: default
spec:
  running: true
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"interface":"vm-multi-nic","name":"bridge-test","namespace":"default","ips": ["172.16.32.226/24"] }]'
        #k8s.v1.cni.cncf.io/networks: bridge-test@eth0
      labels:
        kubevirt.io/vm: nginx-provisioner
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: vm-multi-nic
            bridge: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: vm-multi-nic
        multus:
          default: true
          networkName: default/bridge-test
      volumes:
      - dataVolume:
          name: fedora-nginx
        name: datavolumedisk1
      - cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                addresses: [ 172.16.32.226/24 ]
          userData: |
            #!/bin/sh
            # removing instances ensures cloud init will execute again after reboot
            mkdir ~/123
            sudo echo -e "zlinux\nzlinux" | passwd root
            rm -rf /var/lib/cloud/instances
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: fedora-nginx
    spec:
      storage:
        storageClassName: managed-nfs-storage
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 24Gi
      source: # clone from source dv
        pvc:
          namespace: vm-images
          name: fedora-cloud-base-1 # the dv need prepare
```
and then  I have create the vm successed, but the ip is diffrent
```bash
[root@master mutinic]# kubectl  get vmi
NAME                             AGE   PHASE     IP              NODENAME   READYcirros-openstack-vm-special-ip   15m   Running   172.16.32.228   master     True[root@master mutinic]# virtctl  console cirros-openstack-vm-special-ip
Successfully connected to cirros-openstack-vm-special-ip console. The escape sequence is ^]

[root@cirros-openstack-vm-special-ip ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 8e:e6:ef:fd:09:3c brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 172.16.32.226/24 brd 172.16.32.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8ce6:efff:fefd:93c/64 scope link
       valid_lft forever preferred_lft forever
[root@cirros-openstack-vm-special-ip ~]#
```
why this is happend?

**What you expected to happen**:
I think I create a vm  with a speical IP, and I have declare the IP  address with the annotations.
the vm get the ip should be same as the declare IP.

**Comment by Erick-shi** [comment]
maybe I was mistake to use it, I can work around from :
1.  define the interface use static ip
2. annatition the interface in the virtualmachine yml
3. se ip use the cloudint

**Comment by orelmisan** [comment]
Hi @Erick-shi, I'm not really sure what your desired state is, but please note that you don't need to manually set the `k8s.v1.cni.cncf.io/networks` annotation on the VMI.

When you define a multus network, KubeVirt (or more precisely the VMI controller) creates the virt-launcher pod with the required `k8s.v1.cni.cncf.io/networks` annotation to be consumed by Multus.

Please note that virt-controller also [copies](https://github.com/kubevirt/kubevirt/blob/836ed33f8ecc33f85da52b6c44a4bbaab2d941de/pkg/virt-controller/services/template.go#L1344) VMI annotations to the virt-launcher pod - so manually setting the `k8s.v1.cni.cncf.io/networks` probably confuses the system.

/sig-network

@AlonaKaplan @EdDev

**Comment by Erick-shi** [comment]
@orelmisan 
hi, thanks for your reply. I want set a static ip for my vm, for example I want to set my vm ip is `172.16.32.226 ` and I have set `172.16.32.226 ` use cloudInit.  I finaly  get the `172.16.32.226 `, but I use `kubectl get vmi` the ip address show me `172.16.32.228`, l want  the vm ip is same as the kubevirt show me.

```bash
[root@master mutinic]# kubectl  get vmi
NAME                             AGE   PHASE     IP              NODENAME   READYcirros-openstack-vm-special-ip   15m   Running   172.16.32.228   master     True
[root@master mutinic]# virtctl  console cirros-openstack-vm-special-ip
Successfully connected to cirros-openstack-vm-special-ip console. The escape sequence is ^]

[root@cirros-openstack-vm-special-ip ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 8e:e6:ef:fd:09:3c brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 172.16.32.226/24 brd 172.16.32.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8ce6:efff:fefd:93c/64 scope link
       valid_lft forever preferred_lft forever
[root@cirros-openstack-vm-special-ip ~]#
```

**Comment by Erick-shi** [comment]
@orelmisan  may I am mistake. I have test the issue retry,
1.  defile a static ip with  static ip like `172.16.32.226`
  ```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "bridge-test",
      "type": "bridge",
      "capabilities": { "ips": true },
      "bridge": "br1",
      "ipam": {
        "type": "static",
          "addresses": [
                        {
                          "address": "172.16.32.226/24",
                          "gateway": "172.16.32.1"
                        }
                    ]
      }
    }'
```
2.  defile a virtualmachine yaml 
```yaml
      networks:
      - name: vm-multi-nic
        multus:
          default: true
          networkName: default/static
      - cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                addresses: [ 172.16.32.226/24 ]
```
and it work for me.  Are my testing steps correct?  And  I have two question, 
1. when I set a static  ip for vm , should  I define a `NetworkAttachmentDefinition` every time?  
2. I   deliberately manually defined two NetworkAttachmentDefinitions, and their IPs are the same, but the virtual machine can still be created normally. Does kubevirt have no IP detection function?
