### ISSUE TITLE
VM using macvtap interface failed to start in kind cluster, complaining about not finding tap device

### ISSUE THREAD

**Issue by hujun-open** [kubevirt/kubevirt#10901]
**What happened**:
I have a kind cluster inside a single ubuntu22.04 VM, trying to create a VM with macvtap interface, however the VM failed to start, and the kubectl describe the vm pod returns error like following:
```
Warning  Failed          5m53s                 kubelet            Error: failed to generate container "9454865b31e2ed0c0eb5c61e91b1bab8 │
│ ac9bdb34a7c7a1a1f419188db2e552ee" spec: failed to apply OCI options: lstat /dev/tap76: no such file or directory
```
however even though the worker node (which is a docker container given this is kind cluster) doesn't have /dev/tap76,  I could manually create a macvtap interface via "ip link" command without issue on the worker node:
```
root@kind-worker:/# ip link add link eth0 name mac1 type macvtap mode bridge
root@kind-worker:/# ip link set mac1 up
root@kind-worker:/# ip -d link show mac1
78: mac1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 0e:8c:2c:78:b5:92 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535
    macvtap mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```
not sure if I miss anything

**What you expected to happen**:
I expect VM to start normally

**How to reproduce it (as minimally and precisely as possible)**:
1. install a kind cluster inside a ubuntu 22.04 VM, with a control node and a worker node
2. install kubevirt v1.1.0
3. install multus
4. install macvtap cni according to the instructions on https://github.com/kubevirt/macvtap-cni
5. create a kubevirt vm with macvtap interface

**Additional context**:
macvtap CNI configmap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: macvtap-deviceplugin-config
data:
  DP_MACVTAP_CONF: >-
    [ {
        "name" : "eth0",
        "lowerDevice" : "eth0",
        "mode": "bridge",
        "capacity" : 5
     } ]
```
network-attach-def
```
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: dataplane
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/eth0
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "dataplane",
      "type": "macvtap",
      "mtu": 1500
    }'
```
VM
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-macvtap
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: dataplane
            macvtap: {}
          rng: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - name: dataplane
        multus:
          networkName: dataplane
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.0
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
- VM or VMI specifications: see above
- Cloud provider or hardware configuration: kind cluster
- OS (e.g. from /etc/os-release): host is a ubuntu 22.04 VM 
- Kernel (e.g. `uname -a`): `Linux kindvm 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A
