### ISSUE TITLE
vm failed to start in a dual-stack k8s cluster, with err: failed to setup link [k6t-eth0]: failed to add IP address [fd10:0:2::1/120] on link k6t-eth0: permission denied 

### ISSUE THREAD

**Issue by hujun-open** [kubevirt/kubevirt#10910]
**What happened**:
I created a dual-stack k8s cluster, and VM with masquerade interface failed to start, with following error msg:

```
 Events:                                                                                                                               │
│   Type     Reason            Age   From                       Message                                                                 │
│   ----     ------            ----  ----                       -------                                                                 │
│   Normal   SuccessfulCreate  15s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-macvtap-fjnjr          │
│   Warning  SyncFailed        8s    virt-handler               failed to configure vmi network: setup failed, err: Critical network er │
│ ror: failed to setup link [k6t-eth0]: failed to add IP address [fd10:0:2::1/120] on link k6t-eth0: permission denied                  │
│   Warning  Stopped           8s    virt-handler               The VirtualMachineInstance crashed.                                     │
│   Normal   SuccessfulDelete  8s    virtualmachine-controller  Deleted virtual machine pod virt-launcher-testvm-macvtap-fjnjr   
```
I am new to dual-stack k8s cluster, but with a normal pod does get both an IPv4 and an IPv6 address on eth0, I can ping v6 fine; however I can't add a new IPv6 address, the error msg is also `RTNETLINK answers: Permission denied`, then I noticed that IPv6 is actually disabled inside the pod, maybe this is the reason why the VM failed to start, however I am not sure if this is expected in a dual-stack k8s cluster, and I also don't know how to change these ipv6 kernel setting for the virt-laucher pod given user has no way to change the virt-launch pod settings to add sysctl setting

following is within a normal pod in this dual-stack cluster
```
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if78: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 3e:11:fd:4a:2b:b5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.40/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:42::28/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::3c11:fdff:fe4a:2bb5/64 scope link
       valid_lft forever preferred_lft forever
3: net1@if79: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8000 qdisc noqueue state UP group default
    link/ether 76:c5:cd:19:6b:92 brd ff:ff:ff:ff:ff:ff link-netnsid 0
/ # ip addr add 2001:dead::1/96 dev net1
RTNETLINK answers: Permission denied
/ # sysctl net.ipv6.conf.default.disable_ipv6
net.ipv6.conf.default.disable_ipv6 = 1
/ # sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1

```

**What you expected to happen**:
VM start normally

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1. use kubeadm to create a dual-stack cluster
2. create a VM like following:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-macvtap
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: dataplane
            macvtap: {}
          rng: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - name: dataplane
        multus:
          networkName: dataplane
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                eth0:
                  dhcp4: true
                  addresses: [ fd10:0:2::2/120 ]
                  gateway6: fd10:0:2::1
            userDataBase64: SGkuXG4=

```

**Additional context**:
I am using flannel CNI with vxlan backend, along with multus

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```
- VM or VMI specifications: see above
- Cloud provider or hardware configuration: a single node dual-stack cluster inside a ubuntu22.04 VM
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): `Linux k8svm 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64` x86_64 GNU/Linux
- Install tools: kubeadm
- Others: N/A
