### ISSUE TITLE
Create different vmclone Object with the same target.name

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10935]
**What happened**:
We can create different vmclone Object with the same `target.name` and there is on blocking behavior or error messages.

![image](https://github.com/kubevirt/kubevirt/assets/86186853/106532de-10aa-4d9d-a23a-5e8e8d155c88)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. To create a source vm which we want to be cloned.
2. To edit the first vmclone file.
```yaml
apiVersion: clone.kubevirt.io/v1alpha1
kind: VirtualMachineClone
metadata:
  annotations:
  name: vm-clone-1
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-targer 
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-clone-target
```
4. To edit the second vmclone file
```yaml
apiVersion: clone.kubevirt.io/v1alpha1
kind: VirtualMachineClone
metadata:
  annotations:
  name: vm-clone-2
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-targer 
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-clone-target
```
5. you can find that the `vm-clone-1` has been created successfully and the `vm-clone-2` status is in `RestoreInProgress`. That isn't expected. If the system has the same name we can't allow admin to create new vmclone object.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.0
- Kubernetes version (use `kubectl version`): 1.25
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
