### ISSUE TITLE
Specify a node to create a VM

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10937]
**Is your feature request related to a problem? Please describe**:

Though we have [Node assignment](https://kubevirt.io/user-guide/operations/node_assignment/) to chose which node to be scheduled. But in some scenarios we still need to specify an exact node to create a virtual machine and the function is the same to K8s' POD.

**Describe the solution you'd like**:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-cirros
spec:
  template:
    spec:
      nodeName: host-0-1

```

**Describe alternatives you've considered**:

**Additional context**:

**Comment by chenxinlong** [comment]
You can specify an exact node by using nodeSelector described in [Node assignment](https://kubevirt.io/user-guide/operations/node_assignment/), like : 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvmi-ephemeral
spec:
  nodeSelector:
    kubernetes.io/hostname: worker001
```
