### ISSUE TITLE
virt-launcher was OOM killed by kubelet with dedicatedCpuPlacement enabled

### ISSUE THREAD

**Issue by gunine** [kubevirt/kubevirt#10959]
**What happened**:
The VM (virt-launcher container) is killed by kubelet with ```dedicatedCpuPlacement``` option on in VM manifest.
With ```dedicatedCpuPlacement``` option, I can observe kubevirt automatically adds ```limits``` value to virt-launcher POD manifest, and this in turn leads VM OOM kill. 

**What you expected to happen**:
VM should not be killed by kubelet, on ```dedicatedCpuPlacement``` option enabled.

**How to reproduce it (as minimally and precisely as possible)**:
Spawn a VM with ```dedicatedCpuPlacement``` option enabled, and execute a memory intensive workload. In my case, I ran SPEC CPU benchmark tool.

**Additional context**:
Kubevirt should not add ```limits``` attribute to ```virt-launcher``` POD with ```dedicatedCpuPlacement``` option enabled.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.27.5
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2024-01-02T03:51:17Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  generation: 15
  name: vm
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
      name: vm-boot-dv
    spec:
      preallocation: true
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: hostpath-csi
      source:
        pvc:
          name: rocky-9-image
          namespace: imagevolume
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
          model: host-passthrough
          sockets: 2
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: bootdisk
          interfaces:
          - bridge: {}
            name: default
          - bridge: {}
            macAddress: 02:00:00:18:92:ed
            name: external-net-net
        firmware:
          bootloader:
            efi:
              secureBoot: false
        ioThreadsPolicy: auto
        machine:
          type: q35
        memory:
          guest: 160Gi
        resources: {}
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: external-net
        name: external-net-net
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      terminationGracePeriodSeconds: 30
      volumes:
      - dataVolume:
          name: vm-boot-dv
        name: bootdisk
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Rocky 8.8
- Kernel (e.g. `uname -a`): 4.18.0-477.13.1.el8_8.x86_64
- Install tools: N/A
- Others: N/A
