### ISSUE TITLE
Pod Network Interface Attachment Fails on Windows Machines in KubeVirt

### ISSUE THREAD

**Issue by vishal-denge** [kubevirt/kubevirt#10968]
**What happened**:

I am using K3S. 
While successfully attaching a pod network interface to Linux machines like Fedora within KubeVirt, I observed the presence of the pod network in both the pod and the Fedora VM. Unfortunately, the same procedure fails when attempting to attach a pod network to Windows machines. In this scenario, the pod network is visible within the pod but not on the Windows machine

**What you expected to happen**:
Windows machines should have a pod network interface assigned to it with some IP address

**How to reproduce it (as minimally and precisely as possible)**:
By launching any Windows machine 

**Additional context**:
I want a Windows machine that should get the IP address or pod network interface

**Environment**:
- KubeVirt version (use `virtctl version v0.58.0`): [v1.28.5+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.28.5%2Bk3s1)
- Kubernetes version (use `kubectl version`): K3S v1.28.4+k3s2   
- VM or VMI specifications: Ubuntu 22.04.3 LTS
- Cloud provider or hardware configuration: Vcenter
- OS (e.g. from /etc/os-release):  Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vishal-denge** [comment]
![MicrosoftTeams-image (1)](https://github.com/kubevirt/kubevirt/assets/24609427/1da4b44f-05e1-4f15-91e1-31c6f706bbd1)
<img width="797" alt="MicrosoftTeams-image (2)" src="https://github.com/kubevirt/kubevirt/assets/24609427/4a04486f-f4ab-428c-9eff-567a63a603bb">

Given are the screenshots

from windows 10 Version

**Comment by maiqueb** [comment]
/sig network

Please share your vm / vmi spec file. Without that, we have 0 chance of reproducing this.

**Comment by vishal-denge** [comment]
Hi, here it the file
`apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: iso-win10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: iso-win10
    spec:
      domain:
        cpu:
          cores: 16
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 1
            disk:
              bus: sata
            name: harddrive
          - bootOrder: 3
            cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 32G
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win10
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk
`

**Comment by orelmisan** [comment]
@vishal-denge could you please put the YAML file in a code block so its structure will be kept?
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by vishal-denge** [comment]
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: iso-win10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: iso-win10
    spec:
      domain:
        cpu:
          cores: 16
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 1
            disk:
              bus: sata
            name: harddrive
          - bootOrder: 3
            cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 32G
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win10
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk

```
