### ISSUE TITLE
Support for VMPORT entries in the VM features xml domain.

### ISSUE THREAD

**Issue by LunarInterface** [kubevirt/kubevirt#10985]
**Is your feature request related to a problem? Please describe**:
Before I moved to kubvirt, I used the vmport disable function directly to the xml of virsh.
Like the kvm hidden function, it is very important as a function that can hide virtual machines, but unfortunately, kubirt does not support the vmport disable function.

If vmport is not disabled as well as simply kvm hidden, vmware virtual devices remain in the device manager, and a specific application may notice virtualization.

**Describe the solution you'd like**:
As shown below, I would like to add the vmport disable function like the kvm hidden function.
```
spec:
      domain:
        machine:
          # This value indicates QEMU machine type.
          type: q35
            #pc-q35
        ### disable BIOS ###
        firmware:
          bootloader:
            efi: {}
        features:
          acpi: {}
          kvm:
            hidden: true
          ### require support ###
          vmport:
            hidden: true            
```

**Describe alternatives you've considered**:
This is the xml that was originally used by the virsh.
```
  <features>
    <acpi/>
    <apic/>
    <kvm>
      <hidden state='on'/>
    </kvm>
    <vmport state='off'/>
```

**Additional context**:
If I have time, I want to try to do some PR myself, should I modify the Go?
