### ISSUE TITLE
Debian12 + K8s-v1.23.17+Kubevirt 0.59.2 create vmi, get error message in virt-launcher pod "Failed to connect socket to '/var/run/libvirt/virtqemud-sock" 

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11019]
**What happened**:
Create test fedora vmi, failure to run. get error in  virt-launcher pod: Failed to connect socket to '/var/run/libvirt/virtqemud-sock

full log:
```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2024-01-14T11:49:39.565048Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2024-01-14T11:49:39.565091Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2024-01-14T11:49:39.565644Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2024-01-14T11:49:39.566028Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2024-01-14T11:49:39.566155Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 13 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2024-01-14T11:49:39.571788Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2024-01-14T11:49:39.571878Z"}
```

**What you expected to happen**:
create fedora vmi successfully, and it runs.

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T10:58:20Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.59.2", GitCommit:"60c2b5f73fe610635c992bd1005df1bfb324dbf0", GitTreeState:"clean", BuildDate:"2023-06-20T16:35:57Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
Note: I tested kubervirt v0.59.2, v1.0.0, v1.0.1, all failure, though here I just past error from kubevirt v0.59.2 as it is more clear.

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:27:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 2048M
    devices:
      interfaces:
      - name: default
        masquerade: {}
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    persistentVolumeClaim:
          claimName: linuxhd
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
```
-PVC specification:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linuxhd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
```
- Cloud provider or hardware configuration:
physical server, with CPU type "Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz"
- OS (e.g. from /etc/os-release):
"Debian GNU/Linux 12 (bookworm)"

- Kernel (e.g. `uname -a`):
Linux iZuf66a853qmyl37zcry1uZ 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

- Others: 
Kubevirt version (as I said, I tested v0.59.2, v1.0.0, v1.0.1, current error message is reported by v0.59.2)
longhorn(v1.5.3) (the storage is working fine, as I tried to created a nginx pod by using pvc created by longhorn)
docker client/server version: 23.0.6
libvirtd (9.0.0) installed
run virt-host-validate qemu:
```
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : PASS
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)
```
libvirtd service status:
```
○ libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; preset: enabled)
     Active: inactive (dead) since Sun 2024-01-14 19:49:05 CST; 27min ago
   Duration: 2min 2.275s
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 2249974 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 2249974 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 1.0M
        CPU: 520ms
     CGroup: /system.slice/libvirtd.service
             ├─1034631 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─1034632 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

Jan 14 19:47:02 iZuf66a853qmyl37zcry1uZ systemd[1]: Starting libvirtd.service - Virtualization daemon...
Jan 14 19:47:02 iZuf66a853qmyl37zcry1uZ systemd[1]: Started libvirtd.service - Virtualization daemon.
Jan 14 19:47:03 iZuf66a853qmyl37zcry1uZ dnsmasq[1034631]: read /etc/hosts - 8 names
Jan 14 19:47:03 iZuf66a853qmyl37zcry1uZ dnsmasq[1034631]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 names
Jan 14 19:47:03 iZuf66a853qmyl37zcry1uZ dnsmasq-dhcp[1034631]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Jan 14 19:49:05 iZuf66a853qmyl37zcry1uZ systemd[1]: libvirtd.service: Deactivated successfully.
Jan 14 19:49:05 iZuf66a853qmyl37zcry1uZ systemd[1]: libvirtd.service: Unit process 1034631 (dnsmasq) remains running after unit stopped.
Jan 14 19:49:05 iZuf66a853qmyl37zcry1uZ systemd[1]: libvirtd.service: Unit process 1034632 (dnsmasq) remains running after unit stopped.
````
