### ISSUE TITLE
Debian 12 + Docker 24.0.7 + k8s v1.24.17 + Kubevirt v1.1.1, create example vmi, get error message panic: timed out waiting for domain to be defined

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11037]
**What happened**:
apply the fedoral vmi yaml, get error message: panic: timed out waiting for domain to be defined during triggering "virt-launcher", and vmi PHASE is "Failed"

**What you expected to happen**:
apply the  fedoral vmi yaml, the vmi is running.

**How to reproduce it (as minimally and precisely as possible)**:
Apply below example yamls
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linuxhd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      interfaces:
      - name: default
        masquerade: {}
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    persistentVolumeClaim:
          claimName: linuxhd
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```
**Additional context**:
full log from virt-launcher pod is below:
```
### Logs for virt-launcher-testvmi-nocloud-w2cz9, namespace default, docker container 5c8a4af690fa83acea938844e17fa0ec8f0e064c2ec561b34684f5f330a2b03f ###
{"component":"virt-launcher-monitor","level":"error","msg":"could not create up serial console term file: /var/run/kubevirt-private/dd93fafd-1867-4d08-a420-a1a9dd6e40ff/virt-serial0-log-sigTerm","pos":"virt-launcher-monitor.go:72","reason":"open /var/run/kubevirt-private/dd93fafd-1867-4d08-a420-a1a9dd6e40ff/virt-serial0-log-sigTerm: no such file or directory","timestamp":"2024-01-18T13:03:38.567118Z"}
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2024-01-18T13:03:38.610975Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2024-01-18T13:03:38.611092Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:563","timestamp":"2024-01-18T13:03:38.611380Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:571","timestamp":"2024-01-18T13:03:38.611940Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"44","timestamp":"2024-01-18T13:03:38.632000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvmi-nocloud","subcomponent":"libvirt","thread":"44","timestamp":"2024-01-18T13:03:38.632000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"44","timestamp":"2024-01-18T13:03:38.632000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"44","timestamp":"2024-01-18T13:03:38.632000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"44","timestamp":"2024-01-18T13:03:38.632000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:579","timestamp":"2024-01-18T13:03:39.115515Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:562","timestamp":"2024-01-18T13:03:39.120432Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2024-01-18T13:03:39.121026Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0xc0004ef3e0?, 0xc0004ef200, 0xc00058e000, {0x1f07208, 0xc0002f6270})
        cmd/virt-launcher/virt-launcher.go:255 +0x625
main.main()
        cmd/virt-launcher/virt-launcher.go:483 +0x1205
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:192","timestamp":"2024-01-18T13:09:24.130449Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:210","timestamp":"2024-01-18T13:09:24.130659Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"failed to open file /var/run/kubevirt/passt.log","pos":"virt-launcher-monitor.go:421","reason":"open /var/run/kubevirt/passt.log: no such file or directory","timestamp":"2024-01-18T13:09:24.130741Z"}
### Logs for virt-launcher-testvmi-nocloud-w2cz9, namespace default, docker container 7bfdaab8ba82a672a432e502100f7e9367f9a4782fba47cc62591a1cbebb3def ###
### Logs for virt-launcher-testvmi-nocloud-w2cz9, namespace default, docker container 05962788821a7ccfc60af86b8a5d9885c8eb5742f101486ec2f3234c68dd8ab0 ###
Thu Jan 18 13:09:32 2024
error: socket /var/run/kubevirt-ephemeral-disks/container-disk-data/dd93fafd-1867-4d08-a420-a1a9dd6e40ff/disk_0.sock does not exist anymore
```
**Environment**:
- KubeVirt version (use `virtctl version`):  v1.1.1
- Kubernetes version (use `kubectl version`): v1.24.17
- Cloud provider or hardware configuration: Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz
- OS (e.g. from /etc/os-release): Debian GNU/Linux 12 (bookworm)
- Install tools: storage longhorn v1.5.3
