### ISSUE TITLE
VirtualMachine with Preference using preferSpread but without Instancetype cannot be created

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11057]
**What happened**:

When trying to create a VirtualMachine which is using a VirtualMachinePreference that sets the CPU topology to `preferSpread` but not specifying a VirtualMachineInstancetype, the VM creation fails and the `virt-api` VM admitter panics/crashes.

```
{"component":"virt-api","level":"info","msg":"http: panic serving 192.168.66.101:64673: runtime error: invalid memory address or nil pointer dereference\ngoroutine 621 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1868 +0xb9\npanic({0x1fee540?, 0x3a3f480?})\n\tGOROOT/src/runtime/panic.go:920 +0x270\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.(*VMsAdmitter).applyInstancetypeToVm(0xc0034d5220, 0xc004b2dc00)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:280 +0x26b\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.(*VMsAdmitter).Admit(0xc0034d5220, 0xc000e662d0)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:146 +0x2a5\nkubevirt.io/kubevirt/pkg/util/webhooks/validating-webhooks.Serve({0x2805d70, 0xc003514380}, 0x0?, {0x27f3b80, 0xc0034d5220})\n\tpkg/util/webhooks/validating-webhooks/validating-webhook.go:73 +0xba\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook.ServeVMs({0x2805d70, 0xc003514380}, 0x0?, 0xc003c5e7e0, {0x2833908?, 0xc0002b4500}, 0xc005a9c9c0)\n\tpkg/virt-api/webhooks/validating-webhook/validating-webhook.go:43 +0x167\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerValidatingWebhooks.func3({0x2805d70?, 0xc003514380?}, 0x7e2f8d?)\n\tpkg/virt-api/api.go:874 +0x31\nnet/http.HandlerFunc.ServeHTTP(0x10?, {0x2805d70?, 0xc003514380?}, 0xc0022f64ac?)\n\tGOROOT/src/net/http/server.go:2136 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x412065?, {0x2805d70, 0xc003514380}, 0xc00353a300)\n\tGOROOT/src/net/http/server.go:2514 +0x142\nnet/http.serverHandler.ServeHTTP({0x27fa120?}, {0x2805d70?, 0xc003514380?}, 0x6?)\n\tGOROOT/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc000e8b710, {0x2814258, 0xc0052acd80})\n\tGOROOT/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 205\n\tGOROOT/src/net/http/server.go:3086 +0x5cb\n","pos":"server.go:3214","timestamp":"2024-01-22T09:25:53.523171Z"}
```

**What you expected to happen**:

The VirtualMachine was created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Use attached YAML to create a VM and observe `virt-api` logs. 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-9htzn
spec:
  preference:
    name: centos.stream9.dpdk
  running: false
  template:
    spec:
      domain:
        devices: {}
        memory:
          guest: 1536Mi
        resources: {}
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/centos-stream:9
        name: vm-9htzn-containerdisk-0
status: {}
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
