### ISSUE TITLE
Migrating a vmware VM of RHEL7 to kubevirt , VM startup failed with error `dracut-initqueue timeout`

### ISSUE THREAD

**Issue by yehaifeng** [kubevirt/kubevirt#11133]
**What happened**:

Migrating a vmware VM of RHEL7 to kubevirt , VM startup failed with error `dracut-initqueue timeout`.

```
[186.175174] dracut-initqueue[268]: Warning: dracut-initqueue timeout - starting timeout scripts
[186.175675] dracut-initqueue[268]: Warning: Could not boot.
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.1.1
- Kubernetes version (use `kubectl version`): v1.28.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Stream release 8
- Kernel (e.g. `uname -a`): 4.18.0-338.el8.x86_64
- Install tools: N/A
- Others: N/A

**Comment by yehaifeng** [comment]
This is the description of this vm.

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: oracle-succdb-55a223
  namespace: vlan55
  labels:
    kubevirt.io/os: rhel7
  annotations:
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/os: rhel7
      annotations:
        ovn.kubernetes.io/ip_address: 192.168.55.223
        ovn.kubernetes.io/mac_address: 00:50:56:b7:15:08
    spec:
      domain:
        devices:
          useVirtioTransitional: true
          disks:
          - disk:
              bus: virtio
            name: rootdisk
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "0.1"
            memory: 100Mi
      terminationGracePeriodSeconds: 180
      volumes:
      - persistentVolumeClaim:
          claimName: oracle-55a223-disk1
        name: rootdisk
```
