### ISSUE TITLE
How to add multiple DNS search domains and DNS ndots option to a guest VM's search list of /etc/resolv.conf

### ISSUE THREAD

**Issue by kcao3** [kubevirt/kubevirt#11165]
**What happened**:

Hello. I recently have deployed a Kubevirt VM (version v1.1.0) in my Kubernetes cluster (version v1.29.1 managed kubeadm) using this exact YAML manifest: https://kubevirt.io/labs/manifests/vm.yaml. Everything seems running just fine. However, from inside the VM, I noticed for some reason its DNS search domains only shows this ONE entry from /etc/resolv.conf:
```
search default.svc.cluster.local
nameserver <kube-dns_CLUSTER_IP>

```
**What you expected to happen**:

Does anyone know how to reconfigure the guest VM so that it can use more DNS search domains in its /etc/resolv.conf just like the default settings used by kubernetes for standard (non-vm based) pod containers? For example:

```
search default.svc.cluster.local svc.cluster.local cluster.local <external_domain1_from_upstream> <external_domain2_from_upstream> <external_domain3_from_upstream> 
options ndots:5
```

**How to reproduce it (as minimally and precisely as possible)**:

`wget https://kubevirt.io/labs/manifests/vm.yaml`
`kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml`
`virtctl start testvm`

**Additional context**:
I also tried adding a dnsConfig and dnsPolicy entry to the spec.template.spec section of this VM manfiest: https://kubevirt.io/labs/manifests/vm.yaml like the following:
```
dnsConfig:
  option:
  - name: ndots
    value: "5"
  nameservers:
  - <kube-dns_CLUSTER_IP>
  searches:
  - default.svc.cluster.local
  -  svc.cluster.local
  - cluster.local
  - <external_domain1_from_upstream>     
  - <external_domain2_from_upstream>
  - <external_domain3_from_upstream>
dnsPolicy: "None"

```
However, things are still NOT working correctly. It appears for some reason, only ONE single entry from the DNS search domains can be passed to the guest VM while the ndot option can NOT although from the logs of the virt-launcher component, it appears the virt-launcher did see all of them. Below is a portion of the virt-launcher's log that I can see:

```
`{"component": "virt-launcher", "level": "info", "mgs": "Found search domains in /etc/resolv.conf: default.svc.cluster.local,svc.cluster.local,cluster.local,<external_domain1_from_upstream>,<external_domain2_from_upstream>,<external_domain3_from_upstream>", "pos":"network.go.172","timestamp":"xxxx}}`
```
Has anyone ever run into this issue with a Kubevirt VM and know how to resolve it? Thank you so much in advance for your time and support.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0
- Kubernetes version (use `kubectl version`): v1.29.1
- VM or VMI specifications: https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): RHEL9.3
- Kernel (e.g. `uname -a`): 6.1.11-1.el8.elrepo 
- Install tools: kubeadm
- Others: N/A
