### ISSUE TITLE
Handler Mem/CPU request configurable?

### ISSUE THREAD

**Issue by ffppmm** [kubevirt/kubevirt#11172]
Hi,

this is more a question than an Issue. Can the cpu request be configured? We see a lot of Alerts regarding "Pod virt-handler-XXX cpu usage exceeds the CPU requested". So I thought I would give it a little more than 10m. Can this somehow be configured? From the code I see it hard coded: https://github.com/kubevirt/kubevirt/blob/417acc22ae6efc7d58f996c370226ef35ebc9654/pkg/virt-operator/resource/generate/components/daemonsets.go#L323

Maybe you could also guide me, how to find out why this alert fires, should I provide logs, maybe this is really a misbehavior 😞 

Regards Philipp

**Comment by fossedihelm** [comment]
Hey @ffppmm KubeVirt components can be customized via `customizeComponents` patches. In particular, for your case you can follow the mitigation procedure described here: https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedCPU.html
```
spec:
  customizeComponents:
    patches:
    - type:
      resourceName: <component>
      resourceType: DaemonSet
      type: strategic
      patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-handler","resources":{"requests":{"cpu":" <cpu_request> "}}}]}}}}'
```
Consider that the virt-handler pods are Burstable so some spikes can be reasonable.
There can be several reasons, but in general, is only a specific handler producing the alert? How many vms are running in the "alerted" virt-handler node?
Thank you!
