### ISSUE TITLE
Windows 10/11 and iscsi claim doesn't work

### ISSUE THREAD

**Issue by depeo10** [kubevirt/kubevirt#11208]
Hello,

I'm trying to install a Windows 11 VM on kubevirt. So I start the windows 11 installation, click browse and select the redhat virtio drivers(tested both virtio-latest.iso and virtio-stable.iso).  The installation is copying the files without any problem and then reboots.

After reboot the vm is paused and describe shows this error:
```
    Message:               VMI was paused, low-level IO error detected
    Reason:                PausedIOError
    Status:                True
```

I use the driver "Redhat Virtio pass-trough controller".

There is nothing obvious om the logs on the iscsi host.
Linux installs fine with the same yamls, so this is a Windows 10 and11 issue only. Any ideas?

Here are the yamls i'm using:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-claim
spec:
  resources:
    requests:
      storage: 200Gi
  volumeMode: Block
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
```

---
```
piVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows
    spec:
      domain:
        clock
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
        cpu:
          cores: 32
          model: host-passthrough
        devices:
          autoattachGraphicsDevice: true
          gpus:
          - deviceName: amd.com/6950xt
            name: gpu1
          - deviceName: amd.com/6950xt_audio
            name: gpu2
          disks:
          - lun:
              bus: scsi
            name: pvcdisk
          - cdrom:
              bus: sata
            name: winiso
          - cdrom:
              bus: sata
            name: virtio
          interfaces:
           - name: ovs-vlan-10
             bridge: {}
          tpm: {}
        features:
          acpi: {}
          apic: {}
          kvm:
            hidden: true
          hyperv:
            vendorid:
              enabled: true
              vendorid: 53572b
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 16Gi
      networks:
      - name: ovs-vlan-10
        multus:
         networkName: ovs-vlan-10
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pvcdisk
        persistentVolumeClaim:
          claimName: windows-claim
      - name: winiso
        persistentVolumeClaim:
          claimName: win11iso-pvc
      - name: virtio
        persistentVolumeClaim:
          claimName: virtio-pvc
          
```
          
**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0
- Kubernetes version (use `kubectl version`): v1.29.0+k3s1
- VM or VMI specifications: vm
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): 6.6.9-200.fc39.x86_64 (fedora coreos)
- Install tools: N/A
- Others: N/A
