### ISSUE TITLE
Cannot apply updates from a GitOps manager (Rancher Fleet etc.). Generation field implicitly added

### ISSUE THREAD

**Issue by saffronjam** [kubevirt/kubevirt#11273]
**What happened**:
I am using Rancher Fleet (https://fleet.rancher.io/) to provide GitOps for my services. I tried using this with KubeVirt VMs in my K8s cluster using the following manifest:

```yml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu
  namespace: demo
  labels:
    app.kubernetes.io/name: ubuntu
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ubuntu
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          rng: {}
        resources:
          requests:
            cpu: '2'
            memory: 2Gi
            
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - default
              - name: cloud
                passwd: $6$rounds=4096$UIgXBH0f$P/GBRWeOe/VKbzjUysjAcGKrRV5w8REGMC7Yo.8aoKYgak0Dl.7P0Bn39Eerwbnz9/AnAFiRa/zHPnOlCv56f0
                shell: /bin/bash
                lock-passwd: false
                ssh_pwauth: True
                chpasswd: { expire: False }
                sudo: ALL=(ALL) NOPASSWD:ALL
            ssh_pwauth: False

        name: cloudinit
```

Then when using pushing my changes to Git, the VM is created as it should. But it seems that it adds `generation` to the manifest, which will mismatch with Fleet in Rancher, causing the following error message when any subsequent changes are made. For example, updating `spec.domain.resources.requests.cpu`.
`NotReady(1) [Bundle demo-manifests]; virtualmachine.kubevirt.io demo/ubuntu [progressing] VirtualMachine generation is 2, but latest observed generation is 1`
Even though, as you can see in the manifest, there is no `generation` specified. 

Eventually, the resources are deleted, probably as a fallback for Rancher Fleet, and everything is recreated. But this is NOT desirable, since it could cause me data loss. 

This might be intentional behavior, but it is unexpected from a users perspective, and I am unable to use Rancher with Fleet. 

**What you expected to happen**:
The Git-managed VM manifest should match the one deployed, there should be no implicitly added fields.

**How to reproduce it (as minimally and precisely as possible)**:
Use some GitOps platform (Rancher with Fleet, ArgoCD etc.), deploy the manifest above.  Then make some updates, and push the changes. 

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T10:58:20Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T11:56:11Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11+rke2r1", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T21:08:55Z", GoVersion:"go1.20.11 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- VM or VMI specifications: See above
- Cloud provider or hardware configuration: On premise
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
