### ISSUE TITLE
CDI Quick lab seems to be missing one thing...

### ISSUE THREAD

**Issue by dcjulian29** [kubevirt/kubevirt#11280]
So the first time I went through the CDI lab, the import process failed. I was only able to fix it by updating one line in the example dv_fedora.yml example

**What you expected**:
Not to run into problems... ;)

**URL**:
https://kubevirt.io/labs/kubernetes/lab2.html

**Additional context**:
I fixed the problem by adding additional text to the downloaded YAML file: my entire YAML file that worked was:

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fedora"
spec:
  storage:
#     --\/
    accessModes:
      - ReadWriteOnce
#    --/\
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz"
```

It mostly complained about the access modes line. after adding it to the Yaml, I was able to complete the lab
