### ISSUE TITLE
virtctl vnc cen7.9 fail

### ISSUE THREAD

**Issue by 475556023** [kubevirt/kubevirt#11309]
help me

- kubernetes version：

>Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

- virtctl version：

>Client Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T10:58:20Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T11:56:11Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

- Execute Command：

root@master1:~/kubevirt# virtctl vnc cen7.9
>{"component":"","level":"info","msg":"--proxy-only is set to false, listening on 127.0.0.1\n","pos":"vnc.go:116","timestamp":"2024-02-20T22:52:05.345163Z"}
{"component":"","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:157","timestamp":"2024-02-20T22:52:05.345686Z"}
{"component":"","level":"error","msg":"remote-viewer execution failed: exit status 1, output: \n(remote-viewer:107032): Gtk-WARNING **: 22:52:05.416: cannot open display: \n","pos":"vnc.go:293","timestamp":"2024-02-20T22:52:05.420252Z"}

- vm and related states：

root@master1:~# kubectl get vm
NAME     AGE   STATUS    READY
cen7.9   73m   Running   True

root@master1:~# kubectl get vmi
NAME     AGE   PHASE     IP            NODENAME   READY
cen7.9   72m   Running   100.64.1.18   node1      True

root@master1:~# kubectl get pod
NAME                                      READY   STATUS    RESTARTS   AGE
virt-launcher-cen7.9-88vzh                2/2     Running   0          72m

- virt-handler logs：

root@master1:~# kubectl logs -f -n kubevirt virt-handler-xhfmt
>{"component":"virt-handler","kind":"","level":"info","msg":"Websocket connection upgraded","name":"cen7.9","namespace":"default","pos":"console.go:305","timestamp":"2024-02-20T14:54:34.040859Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-handler","kind":"","level":"info","msg":"Connecting to /proc/81918/root/var/run/kubevirt-private/95a8b808-7773-4598-84ae-8fa1396957b1/virt-vnc","name":"cen7.9","namespace":"default","pos":"console.go:284","timestamp":"2024-02-20T14:54:34.040903Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-handler","kind":"","level":"info","msg":"Connected to /proc/81918/root/var/run/kubevirt-private/95a8b808-7773-4598-84ae-8fa1396957b1/virt-vnc","name":"cen7.9","namespace":"default","pos":"console.go:290","timestamp":"2024-02-20T14:54:34.040951Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from client (virt-api) websocket","name":"cen7.9","namespace":"default","pos":"console.go:323","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2024-02-20T14:54:34.088858Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-handler","kind":"","level":"error","msg":"Error in proxing websocket and unix socket","name":"cen7.9","namespace":"default","pos":"console.go:332","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2024-02-20T14:54:34.089249Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-handler","level":"info","msg":"http: response.WriteHeader on hijacked connection from kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful/v3.(*Response).WriteHeader (response.go:221)\n","pos":"server.go:3230","timestamp":"2024-02-20T14:54:34.089582Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from unix socket","name":"cen7.9","namespace":"default","pos":"console.go:317","reason":"read unix @->/var/run/kubevirt-private/95a8b808-7773-4598-84ae-8fa1396957b1/virt-vnc: use of closed network connection","timestamp":"2024-02-20T14:54:34.090143Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}

- virt-launcher logs：

root@master1:~# kubectl logs -f virt-launcher-cen7.9-88vzh 
>{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"cen7.9","namespace":"default","pos":"server.go:208","timestamp":"2024-02-20T14:47:34.578152Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1353","timestamp":"2024-02-20T14:52:34.571217Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"cen7.9","namespace":"default","pos":"server.go:208","timestamp":"2024-02-20T14:52:34.574058Z","uid":"95a8b808-7773-4598-84ae-8fa1396957b1"}
{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1353","timestamp":"2024-02-20T14:57:34.570194Z"}

- image：CentOS-7-x86_64-DVD-2009.iso

virtctl image-upload pvc iso-cen7 --size=10Gi --image-path=/root/kubevirt/CentOS-7-x86_64-DVD-2009.iso --uploadproxy-url=https://10.96.3.74 --insecure

- create vm file：

root@master1:~/kubevirt# cat vm-centos7.9.yaml 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: cen7.9
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: cen7.9
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: sata
            name: harddrive
          interfaces:
          - masquerade: {}
            model: e1000 
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-cen7
      - name: harddrive
        hostDisk:
          capacity: 20Gi
          path: /data/vms/disk.img
          type: DiskOrCreate
```

**Comment by scydas** [comment]
system kernel version is ？

**Comment by scydas** [comment]
> virtctl vnc cen7.9
can you try this command
virtctl console cen7.9

**Comment by 475556023** [comment]
> can you try this command virtctl console cen7.9

![Uploading 屏幕截图 2024-02-21 153627.png…]()

**Comment by 475556023** [comment]
> can you try this command virtctl console cen7.9

After executing the command, a prompt appears on the screen, and then there is nothing else to do and no other operations can be performed
```
root@master1:~# virtctl console cen7.9
Successfully connected to cen7.9 console. The escape sequence is ^]

```

**Comment by scydas** [comment]
Has virtualization been turned on successfully?

**Comment by 475556023** [comment]
> Has virtualization been turned on successfully?

Virtualization activation should be successful

kubectl edit -n kubevirt kubevirt kubevirt
```
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - HostDisk
      useEmulation: true
```

I created a VM using this file and executed the [virtctl console testvm] command, which allowed me to enter the VM normally

```
root@master1:~/kubevirt# virtctl console testvm
Successfully connected to testvm console. The escape sequence is ^]

login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
testvm login: cirros
Password: 
$ ls /
bin         home        lib64       mnt         root        tmp
boot        init        linuxrc     old-root    run         usr
dev         initrd.img  lost+found  opt         sbin        var
etc         lib         media       proc        sys         vmlinuz
$ 

```
testvm.yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

**Comment by scydas** [comment]
vm-centos7.9.yaml file has some errors.
You are installing vm from a cdrom, but you don't have a pvc for vm, and the cdrom is read-only.

**Comment by 475556023** [comment]
> vm-centos7.9.yaml file has some errors. You are installing vm from a cdrom, but you don't have a pvc for vm, and the cdrom is read-only.

This is the PVC I provided to cen7.9
```
root@master1:~# kubectl get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
iso-cen7   Bound    pvc-69536346-7a62-4df0-b99b-fa75ec3b29d8   10Gi       RWO            nfs-storage    19h

```

How should I modify this file, vm centros7.9.yaml
vm-centos7.9.yaml
```
root@master1:~/kubevirt# cat vm-centos7.9.yaml 
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: cen7.9
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: cen7.9
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: sata
            name: harddrive
          interfaces:
          - masquerade: {}
            model: e1000 
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-cen7
      - name: harddrive
        hostDisk:
          capacity: 20Gi
          path: /data/vms/disk.img
          type: DiskOrCreate
```

virt-launcher-cen7.9 pod describe 
```
root@master1:~# kubectl describe pod virt-launcher-cen7.9-2ms59 
Name:             virt-launcher-cen7.9-2ms59
Namespace:        default
Priority:         0
Service Account:  default
Node:             node1/192.168.100.22
Start Time:       Wed, 21 Feb 2024 17:13:42 +0800
Labels:           kubevirt.io=virt-launcher
                  kubevirt.io/created-by=dcf7c2a7-311d-416d-b4bb-fa98007e2492
                  kubevirt.io/domain=cen7.9
                  kubevirt.io/nodeName=node1
                  vm.kubevirt.io/name=cen7
Annotations:      kubectl.kubernetes.io/default-container: compute
                  kubevirt.io/domain: cen7.9
                  kubevirt.io/migrationTransportUnix: true
                  kubevirt.io/vm-generation: 4
                  post.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--unfreeze", "--name", "cen7.9", "--namespace", "default"]
                  post.hook.backup.velero.io/container: compute
                  pre.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--freeze", "--name", "cen7.9", "--namespace", "default"]
                  pre.hook.backup.velero.io/container: compute
                  traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
Status:           Running
IP:               100.64.1.30
IPs:
  IP:           100.64.1.30
Controlled By:  VirtualMachineInstance/cen7.9
Containers:
  compute:
    Container ID:  containerd://46fb592634e1cd08c845004e23a8f675cb98133e74c20beed8930ab5d318dbfe
    Image:         quay.io/kubevirt/virt-launcher:v1.1.1
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:4fbfd76561667e98fafc75c0b804f77df251f96471d1121d69f149cf8fb9a4d8
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher-monitor
      --qemu-timeout
      295s
      --name
      cen7.9
      --uid
      dcf7c2a7-311d-416d-b4bb-fa98007e2492
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --grace-period-seconds
      45
      --hook-sidecars
      0
      --ovmf-path
      /usr/share/OVMF
      --run-as-nonroot
      --allow-emulation
    State:          Running
      Started:      Wed, 21 Feb 2024 17:13:43 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      devices.kubevirt.io/tun:  1
    Requests:
      cpu:                      200m
      devices.kubevirt.io/tun:  1
      ephemeral-storage:        50M
      memory:                   2266050250
    Environment:
      XDG_CACHE_HOME:   /var/run/kubevirt-private
      XDG_CONFIG_HOME:  /var/run/kubevirt-private
      XDG_RUNTIME_DIR:  /var/run
      POD_NAME:         virt-launcher-cen7.9-2ms59 (v1:metadata.name)
    Mounts:
      /var/run/kubevirt from public (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-private from private (rw)
      /var/run/kubevirt-private/vmi-disks/cdromiso from cdromiso (rw)
      /var/run/kubevirt-private/vmi-disks/harddrive from harddrive (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/hotplug-disks from hotplug-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
  guest-console-log:
    Container ID:  containerd://ab7774ab618c540247b0ef6d1c637cda691e14c6ea8503e0b37be413f36d2d10
    Image:         quay.io/kubevirt/virt-launcher:v1.1.1
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:4fbfd76561667e98fafc75c0b804f77df251f96471d1121d69f149cf8fb9a4d8
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-tail
    Args:
      --logfile
      /var/run/kubevirt-private/dcf7c2a7-311d-416d-b4bb-fa98007e2492/virt-serial0-log
    State:          Running
      Started:      Wed, 21 Feb 2024 17:13:43 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     15m
      memory:  60M
    Requests:
      cpu:     5m
      memory:  35M
    Environment:
      VIRT_LAUNCHER_LOG_VERBOSITY:  2
    Mounts:
      /var/run/kubevirt-private from private (ro)
Readiness Gates:
  Type                                   Status
  kubevirt.io/virtual-machine-unpaused   True 
Conditions:
  Type                                   Status
  kubevirt.io/virtual-machine-unpaused   True 
  Initialized                            True 
  Ready                                  True 
  ContainersReady                        True 
  PodScheduled                           True 
Volumes:
  private:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  public:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  container-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  cdromiso:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  iso-cen7
    ReadOnly:   false
  harddrive:
    Type:          HostPath (bare host directory volume)
    Path:          /data/vms
    HostPathType:  DirectoryOrCreate
  hotplug-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/arch=amd64
                 kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  20s   default-scheduler  Successfully assigned default/virt-launcher-cen7.9-2ms59 to node1
  Normal  Pulled     19s   kubelet            Container image "quay.io/kubevirt/virt-launcher:v1.1.1" already present on machine
  Normal  Created    19s   kubelet            Created container compute
  Normal  Started    19s   kubelet            Started container compute
  Normal  Pulled     19s   kubelet            Container image "quay.io/kubevirt/virt-launcher:v1.1.1" already present on machine
  Normal  Created    19s   kubelet            Created container guest-console-log
  Normal  Started    19s   kubelet            Started container guest-console-log

```
