### ISSUE TITLE
Allocation of host USB device doesn't update number resources exposed by `node.status.allocatable` 

### ISSUE THREAD

**Issue by rpieczon** [kubevirt/kubevirt#11328]
**What happened**:

Define pool of USB devices:
```  
    ...
    permittedHostDevices:
      usb:
      - resourceName: company.com/wifi-dongle
        selectors:
        - product: "0888"
          vendor: "0034"
     ...
```

Verify `company.com/wifi-dongle` are correctly reported by node (there are two instances of USB devices available on a host):

```
  status:
    allocatable:
      company.com/wifi-dongle: "2"
    capacity:
      company.com/wifi-dongle: "2"
```

Run VM allocating resources from created pool:

```
    spec:
      domain:
        devices:
          hostDevices:
            - deviceName: company.com/wifi-dongle
              name: wfd1
            - deviceName: company.com/wifi-dongle
              name: wfd2
```
Verify `allocatable` reported for `company.com/wifi-dongle`:

```
  status:
    allocatable:
      company.com/wifi-dongle: "2"
    capacity:
      company.com/wifi-dongle: "2"
```

**What you expected to happen**:

Node shall report:

```
  status:
    allocatable:
      company.com/wifi-dongle: "0"
    capacity:
      company.com/wifi-dongle: "2"
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.1
- Kubernetes version (use `kubectl version`): v1.27.9+rke2r1
- OS (e.g. from /etc/os-release): ubuntu:22.04
- Kernel (e.g. `uname -a`): `Linux r1s01-r32 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
