### ISSUE TITLE
Ability to specify a disks serial

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1133]
For q guest it is crucial that certain devices never change their identity.

A disks identity is mainly maintained by it's serial, thus we should have the ability to specific a disks serial.
If i.e. a disks serial changes, then this could break a multipath setup within a guest, or even easier change the name and identifier within the guest, which could in the worst case lead to data loss.

API idea:

```yaml

kind: VirtualMachine
spec:
  domain:
    devices:
      disks:
      - name: mypvcdisk
        volumeName: mypvc
        serial: "WD-WMAP9A966149"
        disk: {}
```

This maps to the libvirt serial, see https://libvirt.org/formatdomain.html#elementsDisks:

> serial: If present, this specify serial number of virtual hard drive. For example, it may look like <serial>WD-WMAP9A966149</serial>. Not supported for scsi-block devices, that is those using disk type 'block' using device 'lun' on bus 'scsi'. Since 0.7.1
