### ISSUE TITLE
Windows2016 migration from vmware to kubevirt error: `INACCESSBILE BOOT DEVICE`

### ISSUE THREAD

**Issue by yehaifeng** [kubevirt/kubevirt#11332]
**What happened**:

Import disk from vsphere to kubevirt using cdi, then start a vm from this disk. But it started fail with the error `INACCESSBILE BOOT DEVICE`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. Import disk using cdi
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: qanf-47a240-disk1
  namespace: vlan47
spec:
  source:
    vddk:
      backingFile: "[datacstore1 (33)] D-QANF-47.240/D-QANF-47.240.vmdk"
      url: "https://192.168.12.11"
      uuid: "4237c38c-1031-a06e-ef29-70243d0777a1"
      thumbprint: "98:A4:E0:63:C5:EB:23:C5:17:AB:B9:96:C9:FE:9A:55:C2:A5:FC:B9"
      secretRef: "vddk-credentials"
      initImageURL: "vipharbor.99bill.com/hci/vddk:v6.5.4"
  storage:
    storageClassName: ceph-block
    volumeMode: Block
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "200Gi"
```
3. Start a vm
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: qanf-47a240
  namespace: vlan47
  labels:
    kubevirt.io/os: windows
  annotations:
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: rescue-windows2016
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      source:
        http:
          url: http://192.168.91.17/soft/os/iso/cn_windows_server_2016_updated_feb_2018_x64_dvd_11636703.iso
  template:
    metadata:
    spec:
      domain:
        devices:
          useVirtioTransitional: true
          disks:
          - disk:
              bus: virtio
            name: rootdisk
            bootOrder: 1
          - name: rescue
            cdrom:
              bus: sata
            bootOrder: 2
          - name: virtiocontainerdisk
            cdrom:
              bus: sata
            bootOrder: 3
        cpu:
          cores: 4
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "0.1"
            memory: 100Mi
      volumes:
      - persistentVolumeClaim:
          claimName: qanf-47a240-disk1
        name: rootdisk
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk
      - dataVolume:
          name: rescue-windows2016
        name: rescue
````
5. Error 

`INACCESSBILE BOOT DEVICE` with windows blue screen.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1
- Kubernetes version (use `kubectl version`): 1.28.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Stream release 9
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by yehaifeng** [comment]
![b](https://github.com/kubevirt/kubevirt/assets/12188412/bae2112c-f8fa-4aab-9327-a03803776e2f)

**Comment by fabiand** [comment]
On vmware, what kind of bus was used for the root disk?

Usually you have to run images through tools like virt-v2v or https://github.com/kubev2v/forklift (also using virt-v2v) in order to update Windows to inject the new drivers, and modify Windows to boot from a new bus.

**Comment by yehaifeng** [comment]
@fabiand Thanks for you reply. 

vm started success after using `virt-v2v` convert 

```
virt-v2v -v -x -o local -os /var/tmp/ -of qcow2 -ip elm.pw -ic vpx://elm@192.168.12.11/HOST/D-esxi6.0/192.168.70.101?no_verify=1 D-QANF-47.240
```

Then upload this image to kubevirt using cdi.

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: qanf-47a240
  namespace: vlan47
  labels:
    kubevirt.io/os: windows
  annotations:
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: qanf-47a240-disk1
    spec:
      storage:
        volumeMode: Block
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 200Gi
      source:
        http:
          url: http://192.168.9.217/soft/D-QANF-47.240-sda
  template:
    metadata:
    spec:
      domain:
        devices:
          useVirtioTransitional: true
          disks:
          - disk:
              bus: virtio
            name: rootdisk
            bootOrder: 1
        cpu:
          cores: 4
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "0.1"
            memory: 100Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - dataVolume:
          name: qanf-47a240-disk1
        name: rootdisk
```
