### ISSUE TITLE
VM ownerReferences are not getting set on already existing disks(PVCs) 

### ISSUE THREAD

**Issue by shubhamyelikar** [kubevirt/kubevirt#11519]
**What happened**:
As part of our product development, we are working on a use case involving the backup and restore of KubeVirt VMs. However, we have encountered an issue where the VM is not setting owner references on pre-existing PVCs.
During the restore process, we initially restore the data part (PVC) and then proceed with the VM restoration. Unfortunately, we observe that owner references are not getting set on the PVCs in this scenario.
Consequently, when we delete the VM, the associated PVCs are not being cleaned up, PVCs are remaining dangling there.

**What you expected to happen**:
It is expected that VM ownerReferences should get added on already existing PVCs.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

I have a VM defined with associated DataVolumeTemplates in a YAML configuration.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: shubh
  labels:
    app: centos-stream8-fit-python
    vm.kubevirt.io/template: centos-stream8-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.25.0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: centos-stream8-fit-python
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos-stream8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos-stream8-fit-python
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: centos-stream8-fit-python
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
          name: cloudinitdisk
```
After creating the VM, This PVC is dynamically created based on the specified DataVolumeTemplates.
And i can see PVC is having ownerReferences of VM.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: snapshot
    cdi.kubevirt.io/ownedByDataVolume: shubh/centos-stream8-fit-python
    cdi.kubevirt.io/readyForTransfer: "true"
    cdi.kubevirt.io/smartCloneSnapshot: openshift-virtualization-os-images/cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
    cdi.kubevirt.io/storage.condition.running: "False"
    cdi.kubevirt.io/storage.condition.running.message: Clone Complete
    cdi.kubevirt.io/storage.condition.running.reason: Completed
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
    k8s.io/CloneOf: "true"
    k8s.io/SmartCloneRequest: "true"
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  creationTimestamp: "2024-03-15T07:39:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.13.7
    cdi-controller: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
    cdi.kubevirt.io: cdi-smart-clone
    kubevirt.io/created-by: 4a022f50-4f77-4deb-aed7-da8c3469011a
  name: centos-stream8-fit-python
  namespace: shubh
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: centos-stream8-fit-python
    uid: 4a022f50-4f77-4deb-aed7-da8c3469011a
  resourceVersion: "185230772"
  uid: 5e1e70c4-74ca-427f-a398-d9ff22f4bcfe
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
  resources:
    requests:
      storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
  ```
  

Now we have taken the backup of this VM and PVC.
During restore process, the PVCs are restored first.
Restored PVC YAML
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/allowClaimAdoption: "true"
    cdi.kubevirt.io/storage.populatedFor: "centos-stream8-fit-python"
    cdi.kubevirt.io/cloneType: snapshot
    cdi.kubevirt.io/ownedByDataVolume: shubh/centos-stream8-fit-python
    cdi.kubevirt.io/readyForTransfer: "true"
    cdi.kubevirt.io/smartCloneSnapshot: openshift-virtualization-os-images/cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
    cdi.kubevirt.io/storage.condition.running: "False"
    cdi.kubevirt.io/storage.condition.running.message: Clone Complete
    cdi.kubevirt.io/storage.condition.running.reason: Completed
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
    k8s.io/CloneOf: "true"
    k8s.io/SmartCloneRequest: "true"
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  creationTimestamp: "2024-03-15T07:39:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.13.7
    cdi-controller: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
    cdi.kubevirt.io: cdi-smart-clone
    kubevirt.io/created-by: 4a022f50-4f77-4deb-aed7-da8c3469011a
  name: centos-stream8-fit-python
  namespace: shubh
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: cdi-tmp-6416b584-b3ad-40c2-9c59-2f81bd39d8ed
  resources:
    requests:
      storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
```
During PVC creation we have added following annotations on the PVC as per [this](https://github.com/kubevirt/containerized-data-importer/pull/3029/files) PR.
```
cdi.kubevirt.io/allowClaimAdoption: "true"
cdi.kubevirt.io/storage.populatedFor: "centos-stream8-fit-python"
```
& then restored the above VM.
Despite having the necessary annotations set during PVC creation, the `ownerReferences` are not being added to the restored PVCs.
As a result, when I delete the restored VM, the associated PVCs remain dangling indefinitely

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  
```
Client Version: version.Info{GitVersion:"v1.1.0", GitCommit:"e8e638edc22587ec7be2cc3d983b61763e33f973", GitTreeState:"clean", BuildDate:"2023-11-06T16:34:32Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.59.2-47-ge9b3a6f01", GitCommit:"e9b3a6f01a0e19b6f0d3729da8c8133846c5f75e", GitTreeState:"clean", BuildDate:"2023-12-14T10:45:59Z", GoVersion:"go1.19.13 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`): 1.26
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: shubh
  labels:
    app: centos-stream8-fit-python
    vm.kubevirt.io/template: centos-stream8-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.25.0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: centos-stream8-fit-python
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos-stream8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos-stream8-fit-python
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: centos-stream8-fit-python
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: 08nm-1jcl-x5au
              chpasswd: { expire: False }
          name: cloudinitdisk
```
- Cloud provider or hardware configuration: OCP
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
