### ISSUE TITLE
 Launch Multiple VMs from a datavolume [Windows] 

### ISSUE THREAD

**Issue by Neoclassic** [kubevirt/kubevirt#11514]
Hi,
I create a datavolume and created a VM
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mywindowsvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mywindowsvm
    spec:
      domain:
        cpu:
          cores: 4
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        devices:
          blockMultiQueue: true
          disks:
            - bootOrder: 1
              disk:
                bus: sata
              name: cdromiso
            - bootOrder: 2
              disk:
                bus: virtio
              name: virtiocontainerdisk
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      nodeSelector:
        beta.kubernetes.io/instance-type: m5.metal
      volumes:
      - name: cdromiso
        dataVolume:
          name: windowsvm
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk

```
Now when i created another VM windowsvm2 using the same datavolume, i could see the files created by the windowsvm in windowsvm.

My question is how to create multiple isolated VMs using the same data volume. 

My another question is even if i add another disk it is not visible in the Windows VM.
