### ISSUE TITLE
Passing env/secret into a WindowsVM

### ISSUE THREAD

**Issue by Neoclassic** [kubevirt/kubevirt#11530]
I have a windows image ready in qcow2 format. Now I want to inject some configuration at startup. I tried configDrive but its not visible in the VM created. 
Any other way to achieve this ?

**Comment by victortoso** [comment]
Just to confirm with you, you tested this and it didn't work?
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init

**Comment by victortoso** [comment]
I expected that to work, just in case, what error do you see? Can you share the configuration you have tried?

**Comment by akalenyu** [comment]
This came up before at https://github.com/kubevirt/kubevirt/issues/7992#issuecomment-1171329507
maybe the author could share how he achieved it

**Comment by Neoclassic** [comment]
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: myvm
    spec:
      domain:
        cpu:
          cores: 4
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        devices:
          blockMultiQueue: true
          disks:
            - bootOrder: 1
              disk:
                bus: sata
              name: cdromiso
            - bootOrder: 2
              disk:
                bus: virtio
              name: virtiocontainerdisk
            - bootOrder: 3
              disk:
                bus: virtio
              name: disk3
            - bootOrder: 4
              disk:
                bus: virtio
              name: config-volume
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      nodeSelector:
        beta.kubernetes.io/instance-type: m5.metal
      volumes:
      - name: cdromiso
        dataVolume:
          name: myvm
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk

      - cloudInitNoCloud:
          userData: |
            manage_etc_hosts: true
            hostname: myvm
            bootcmd:
            - 'powershell.exe -ExecutionPolicy bypass -Command $env:CUSTOM_VAR="dakshverma"'
        name: disk3
      - name: config-volume
        configMap:
          name: windows-vm-env

```

This is the VM definition. There is no error as such, but i cant see the envs  or any file containing config.
