### ISSUE TITLE
Is it feasible to use Python Client to create virtual machines?

### ISSUE THREAD

**Issue by hjxgitcode** [kubevirt/kubevirt#11558]
I want to use Python Client to operate KubeVirt to manage virtual machines,Execution a python code just like 
`kubectl apply - f testvm.yaml`

testvm.yaml:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
---
apiVersion: v1
kind: Service
metadata:
  name: vm-ssh
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 24
    targetPort: 22
    name: test
  selector:
    kubevirt.io/domain: testvm
    kubevirt.io/size: small
```
