### ISSUE TITLE
Slow network speed in kubevirt vm

### ISSUE THREAD

**Issue by kaplan-michael** [kubevirt/kubevirt#11646]
**What happened**:
I have deployed a default fedora template and the network speed is pretty slow(~80Mbit/s) on both multus network attachment(goes to a vlan on a switch) and masqurade 

I have tested it with  iperf3 running on the vm and on machine running on the vlan.
I have tested it in a regular pod and the speeds there reach ~900Mbit/s which is expected as the network cards/switching support max 1Gbit/s

Note: 
I have seen https://github.com/kubevirt/kubevirt/issues/2918 but haven't found any info there what could be the cause, or how can debug further.
**What you expected to happen**:
I expect the network speed in a kubevirt VM to match the one that is observed in regular pods.

**How to reproduce it (as minimally and precisely as possible)**:
Run default fedora/centos template
test the speed with iperf3

**Additional context**:
I have OVS deployed through kubevirt operator. 

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1
- Kubernetes version (use `kubectl version`): v1.28.2-3598+6e2789bbd58938 (OKD)
- VM or VMI specifications: default fedora template
- Cloud provider or hardware configuration: baremetal nodes
- OS (e.g. from /etc/os-release): Fedora CoreOS 39.20240210.3.0
- Kernel (e.g. `uname -a`): Linux node.... 6.7.4-200.fc39.x86_64  SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux
- Install tools: kubevirt operator 1.11.0 from okd OperatorHub
- Others: N/A

**Comment by maiqueb** [comment]
Please share your VM specs. We don't know what plugins you're using, nor what configurations you have on them.

Also share your network-attachment definitions. 

What MTUs are you using on your network ? 

Are you using a physical network ?

**Comment by kaplan-michael** [comment]
Hey, sorry for later reply. 
# VM Specs:
this is the yaml I create the VMs with
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-vm
  namespace: vms
spec:
  dataVolumeTemplates:
    - metadata:
        name: centos-vm
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: kubevirt-os-images
        storage:
          volumeMode: Block
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
          resources:
            requests:
              storage: 50Gi
          accessModes:
            - ReadWriteMany
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: { }
              model: virtio
              name: default
        resources:
          requests:
            memory: 16G
            cpu: '8'
      volumes:
        - dataVolume:
            name: centos-vm
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: mkaplan
          name: cloudinitdisk
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              configDrive: {}
            source:
              secret:
                secretName: mkaplan-key
      networks:
        - multus:
            networkName: lan-vlan-1
          name: default
```
# NAD:
this is the network attachement definition.
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: "2024-02-12T16:24:00Z"
  generation: 5
  name: lan-vlan-1
  namespace: vms
  resourceVersion: "23790599"
  uid: cd4a3706-89d0-44a4-a437-69aaba0689c1
spec:
  config: '{"bridge":"br-ex","type":"ovs","cniVersion":"0.4.0","vlan":1}'
  ```
# MTU:
MTUs on br-ex is the default that was set by OKD/kubevirt(mtu 1500)
MTU on the gw is also the default mtu 1500
MTU on the switch(vlans) is also 1500. 
  
# Network
Yes it is a physical 1G network with 10G uplink to GW
# Environment:
no I'm not in any nested virt. It's not virtualized at all. It is all baremetal nodes.
I'm not sure what you mean? If you mean arm64 on x86_64 nodes and so on -> I don't do any hardware emulation.
It's mostly stock cluster. 

# Notes
It could definitely be the network itself, but from what I debuged, that seemed just fine.
