### ISSUE TITLE
virt-controller should not need cluster-admin role

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1166]
I just noticed the following ClusterRoleBinding in our manifests. 

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-controller-cluster-admin
  namespace: {{.Namespace}}
  labels:
    kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubevirt-controller
    namespace: {{.Namespace}}
```

virt-controller needs a very targeted set of permissions rather than being given the entire cluster-admin role.

There is already a virt-controller CLusterRole. That role needs to be expanded to include anything that might be missing, and ClusterRoleBinding related to assigning cluster-admin to the virt-controller service account needs to go away.
