### ISSUE TITLE
launcher in progress, but status still unscheduled

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1175]
I have the situation that a VM's status is not scheduled (missing ready node), but the launcher is actually already launching:

```
$ oc get pods --all-namespaces | grep launcher ; oc get -o yaml vmi testvm | tail
myproject               virt-launcher-testvm-nt7q9       0/2       ContainerCreating   0          1m
    name: cloudinitvolume
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-06-18T19:04:27Z
    message: '0/1 nodes are available: 1 MatchNodeSelector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Scheduling
```

**Comment by fabiand** [comment]
not sure if it's relevant, but after scheudling I get:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-06-18T19:09:48Z
    message: 'server error. command Launcher.Sync failed: hardware emulation device
      ''/dev/kvm'' not present'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized
  interfaces:
  - ipAddress: 172.17.0.9
  nodeName: localhost
  phase: Scheduled
```

With emulation enabled:

```
$ oc get configmap kubevirt-config -o yaml
apiVersion: v1
data:
  debug.allowEmulation: "true"
kind: ConfigMap
metadata:
  creationTimestamp: 2018-06-18T19:00:30Z
  name: kubevirt-config
  namespace: myproject
  resourceVersion: "1801"
  selfLink: /api/v1/namespaces/myproject/configmaps/kubevirt-config
  uid: df20acd0-7329-11e8-bb08-2280bb71811b
```
