### ISSUE TITLE
Cannot create an AMD64 VM on a hybrid AMD+ARM64 cluster

### ISSUE THREAD

**Issue by ader1990** [kubevirt/kubevirt#11774]
**What happened**:
I have a k8s cluster with 1 AMD64 worker node and 2 ARM64 nodes (one control plane and one worker node).
When I try to create an ARM64 VM, all works fine.
When I try to create an AMD64 VM by setting the architecture, I get this error:

```
The request is invalid: spec.template.spec.architecture: multi-architecture feature gate is not enabled in kubevirt-config, invalid entry spec.template.spec.architecture
```

But my multi-architecture feature gate is already enabled:

```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  finalizers:
  - foregroundDeleteKubeVirt
  generation: 4
  labels:
    argocd.argoproj.io/instance: kubevirt
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - Multiarchitecture
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}

```

Is this a supported scenario?

Running the latest release of Kubevirt v1.2.0.
