### ISSUE TITLE
VirtualMachineInstance create failed

### ISSUE THREAD

**Issue by jiangxiaobin96** [kubevirt/kubevirt#11787]
Error when creating VirtualMachineInstance.
- error of pod/virt-launcher-testvm-2dskd
```
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"46","timestamp":"2024-04-24T17:22:50.394000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"46","timestamp":"2024-04-24T17:22:50.394000Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:143","timestamp":"2024-04-24T17:27:53.868555Z"}
```
- cluster information
```
kubevirt       pod/virt-api-56fbd84dd5-b6tdd              1/1     Running   0          8h
kubevirt       pod/virt-api-56fbd84dd5-zh7qz              1/1     Running   0          8h
kubevirt       pod/virt-controller-7f68fbd688-8gk2b       1/1     Running   0          8h
kubevirt       pod/virt-controller-7f68fbd688-rmlsz       1/1     Running   0          8h
kubevirt       pod/virt-handler-k4dns                     1/1     Running   0          8h
kubevirt       pod/virt-handler-zgkjq                     1/1     Running   0          8h
kubevirt       pod/virt-launcher-testvm-2dskd             0/2     Error     0          7h57m
kubevirt       pod/virt-operator-8b8d65f8f-2wtnr          1/1     Running   0          8h
kubevirt       pod/virt-operator-8b8d65f8f-6ps6l          1/1     Running   0          8h
```
```
virtctl version
Client Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T20:34:24Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.0.1", GitCommit:"5e8660a7ba53fe05266a20960f4e8e1ef3e1104b", GitTreeState:"clean", BuildDate:"2023-10-17T20:33:17Z", GoVersion:"go1.19.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```
- host information
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- kubevirt deployment
```
wget https://github.com/kubevirt/kubevirt/releases/download/v1.2.0/kubevirt-operator.yaml
wget https://github.com/kubevirt/kubevirt/releases/download/v1.2.0/kubevirt-cr.yaml

sudo kubectl apply -f kubevirt-operator.yaml --kubeconfig ~/.kube/config
sudo kubectl apply -f kubevirt-cr.yaml --kubeconfig ~/.kube/config
```
- vm deployment
```
sudo kubectl apply -f vm.yaml --kubeconfig ~/.kube/config
cat vm.yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
    debugLogs: "true"
    logVerbosity: "6"
  name: testvm
  namespace: kubevirt
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: docker.io/kubevirt/cirros-registry-disk-demo
```
