### ISSUE TITLE
VM in CrashLoopBackOff state once CPU sockets are added [CPU Hotplug], virtio-mem-pci reports not enough space error.

### ISSUE THREAD

**Issue by nepomucen** [kubevirt/kubevirt#11912]
**What happened**:
I added extra CPU sockets through CPU Hotplug feature, this in turn caused the VM to loop into CrashLoopBackOff state, and its corresponding VMI in Scheduling state, reporting on Status:

```
 lastTransitionTime: "2024-05-14T08:33:42Z"
    message: 'server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10,
      Message=''internal error: QEMU unexpectedly closed the monitor (vm=''testing-cpu-hotplug-14''):
      2024-05-14T08:33:42.215448Z qemu-kvm: -device {\"driver\":\"virtio-mem-pci\",\"node\":0,\"block-size\":2097152,\"memdev\":\"memvirtiomem0\",\"id\":\"virtiomem0\",\"bus\":\"pci.10\",\"addr\":\"0x0\"}:
      not enough space, currently 0x0 in use of total space for memory devices 0x165a100000'')"'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized 
```
This cycle repeats each time kubevirt tries to re-schedule the VM to another node.
I've check and there is more than enough memory and CPU resources available on the node:
```
~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          754Gi       122Gi       592Gi        16Mi        39Gi       626Gi
Swap:            0B          0B          0B
```

**What you expected to happen**:
VM can be LiveMigrated without any problem.
Quoting [official](https://kubevirt.io/user-guide/operations/cpu_hotplug/#limitations) doc: 

> Current CPU hotplug implementation involves live-migration of the VM workload.

**How to reproduce it (as minimally and precisely as possible)**:
- Install kubevirt 1.0.1
- Create VM
- Enable CPU Hotplug
- Patch VM's `/spec/template/spec/domain/cpu/sockets` with the new value, e.g. 2=>3
Up to this moment everything works fine, but I need to restart the VM to see a hot plugged CPU 
- Restart VM
- Upgrade kubevirt to 1.2.0
- Patch VM's `/spec/template/spec/domain/cpu/sockets` once again with the new value, e.g. 3=>4
- Here the VMI keeps staying in Scheduling state for ever.

**Additional context**:
kubevirt was upgraded from 1.0.1 => 1.2.0

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.25.14
- VM or VMI specifications: 
```
spec:
  running: true
  template:
    metadata:
      labels:
        role: worker
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          model: host-passthrough
          sockets: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: overcloud_network
        machine:
          type: q35
        memory:
          guest: 32G
        resources: {}
      evictionStrategy: LiveMigrate
      hostname: testing-cpu-hotplug-14
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): "20.04.6 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by acardace** [comment]
@nepomucen I followed your reproduction steps but was not able to reproduce the bug you're experiencing.

On v1.0.1, did you enabled the `vmLiveUpdateFeatures` feature gate and set `maxSockets` in the VM spec? You say you had to restart the VM to see the additional sockets, that's not expected unless you missed one of the mentioned steps.

When on v1.2.0, did you again enable `vmLiveUpdateFeatures` and set `spec.configuration.vmRolloutStrategy` to `LiveUpdate` in the KubeVirt CR before attempting the hotplug?

In v1.2.0 it's not required that you set `spec.domain.cpu.maxSockets`.

**Comment by nepomucen** [comment]
@acardace Thank you for picking up my bug report and reproducing my case.

It helped me to understand, where lays the exact problem in my environment's setup, and maybe also finds some imperfection in feature documentation (please read my suggestion at the end of my reply). 

In short. It works now, even on v1.0.1 !.

- This's the config I used for the initial bug report:

```
#KV's CR
  spec:       
   liveUpdateFeatures:
    cpu:
```
      
#VMs spec           
 ```
cpu:
    cores: 6
    model: host-passthrough
  memory:
    guest: 32G
```

Forgot to mention, I switched from `instanceType` to inline resource declaration, as this is a prerequisite of CPUHotPlug feature.

```
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: testing
  namespace: testing
spec:
  cpu:
    guest: 6
    model: host-passthrough
  memory:
    guest: 32G
```
  
and translated it into VM spec as follow:

```
       cpu:
          cores: 6
          model: host-passthrough
        memory:
          guest: 32G
```

With the above test manifest file I'm getting a very generic `HotPlugCPUError` after patching the running VM's CPU sockets.

- Patch command used:

```
kubectl patch vm testing-worker-20 --type='json' \
-p='[{"op": "replace", "path": "/spec/template/spec/domain/cpu/sockets", "value": 2}]

```

- This is what I see on VMI's status.
>  - lastProbeTime: null
>     lastTransitionTime: "2024-09-24T09:19:03Z"
>     message: 'Error encountered while handling CPU change request: the server rejected
>       our request due to an error in our request'
>     reason: HotPlugCPUError
>     status: "True"
>     type: Failure

logs from virt-controller:
```
virt-controller-7b777fb8cf-7kbvh virt-controller {"component":"virt-controller","kind":"","level":"error","msg":"Reconciling the VirtualMachine failed.","name":"testing-worker-14","namespace":"testing","pos":"vm.go:385","reason":"Error encountered while handling CPU change request: the server rejected our request due to an error in our request","timestamp":"2024-09-23T15:23:46.034591Z","uid":"1961a109-eed9-4a51-86f6-3d4658df90ff"}
virt-controller-7b777fb8cf-7kbvh virt-controller {"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine testing/testing-worker-14","pos":"vm.go:278","reason":"Error encountered while handling CPU change request: the server rejected our request due to an error in our request","timestamp":"2024-09-23T15:23:46.052673Z"}
virt-controller-7b777fb8cf-7kbvh virt-controller {"component":"virt-controller","kind":"","level":"error","msg":"Reconciling the VirtualMachine failed.","name":"testing-worker-14","namespace":"testing","pos":"vm.go:385","reason":"Error encountered while handling CPU change request: the server rejected our request due to an error in our request","timestamp":"2024-09-23T15:23:46.059943Z","uid":"1961a109-eed9-4a51-86f6-3d4658df90ff"}
```

- To fix the problem with hot plugging a CPU, I needed to declare sockets explicitly in VM spec.

  You can treat this bug report as a feature misuse by the end user, or a little gap in [CPU Hotplug's feature documentation](https://kubevirt.io/user-guide/compute/cpu_hotplug/), which shows as an example works around VMIs resources not VMs, and doesn't mention, that `doman.cpu.sockets` field needs to be declared explicitly in VM spec.
