### ISSUE TITLE
Unable to start a VirtualMachineInstance on Mac Apple Silicon.

### ISSUE THREAD

**Issue by valebes** [kubevirt/kubevirt#11917]
**What happened**:
It is impossible to run a VM on a MacBook Pro M1 Pro (Apple Silicon/aarch64).
When doing a `kubectl get vmi -o yaml` I get the following error:

`    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T15:29:49Z"
      message: 'server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10,
        Message=''unsupported configuration: CPU mode ''host-passthrough'' for aarch64
        qemu domain on aarch64 host is not supported by hypervisor'')"'
      reason: Synchronizing with the Domain failed.
`

**What you expected to happen**:
The VM should start properly.

**How to reproduce it (as minimally and precisely as possible)**:
As suggested in kubevirt/kubevirt#10055, I enabled SW Emulation.
Moreover, I'm trying to run an ARM64 vm.
I used the following config for the virtual machine instance:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvm
spec:
  domain:
    machine:
      type: virt
    cpu:
      model: host-passthrough
    devices:
      disks:
        - disk:
            bus: virtio
          name: harddisk
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: harddisk
      persistentVolumeClaim:
        claimName: arm-dv
```

I found one with the same problem [here](https://www.reddit.com/r/kubernetes/comments/17jvy7i/trying_to_run_kubevirt_on_minikube/).

**Additional context**:
No other things to report.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.0
- Kubernetes version (use `kubectl version`): v1.29.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: MacBook Pro M1 Pro
- OS (e.g. from /etc/os-release): Sonoma 14.5 (MacOS)
- Kernel (e.g. `uname -a`): Darwin
- Install tools: brew
- Others: N/A
