### ISSUE TITLE
Guest VMs are not up, when Host VM OS is ubuntu 22.04 and kernel 5.15

### ISSUE THREAD

**Issue by scydas** [kubevirt/kubevirt#11920]
**What happened**:
The Host OS  ubuntu 22.04 and kernel 5.15.0-57-generic , We are seeing the Kubevirt images not up properly, due to which we are not able to login to the VMs.

vnc error:
![image](https://github.com/kubevirt/kubevirt/assets/22952515/ceafec93-cbae-4879-ad2c-063a8c1507cf)

virt-launcher log:
![image](https://github.com/kubevirt/kubevirt/assets/22952515/252cbfdf-b513-4bc8-94d1-2a6ec66a8853)

virt-handler log:
![image](https://github.com/kubevirt/kubevirt/assets/22952515/6b4fd356-eac2-4719-bc5f-bfe735056c46)

**What you expected to happen**:
The guest VMs should be running and user should be able to get into the guest VMs without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
Create Ubuntu 22.04 VM with kernel 5.15.0-57-generic,(issue seen on kernels 5.8+).
Install k8s, kubevirt.
Create VMs using kubevirt on the Ubuntu 22.04 VMs with kernel 5.15.

**Additional context**:
use https://kubevirt.io/labs/manifests/vm.yaml creat vm also error
![image](https://github.com/kubevirt/kubevirt/assets/22952515/98a4dfe2-cfd7-4499-ab26-25668626b040)

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0
- Kubernetes version (use `kubectl version`): v1.28.6
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04（Host）
- Kernel (e.g. `uname -a`): 5.15.0-78-generic
- Install tools: operator
- Others: N/A

**Comment by alicefr** [comment]
Can you please provide us the VM yaml you used?

**Comment by alicefr** [comment]
I would try to increase the memory given to the guest, just as an easy check. Then, you should try to run virt-host-validate to check if there are any issues on your nodes (see the [kubevirt documentation](https://kubevirt.io/user-guide/debug_virt_stack/privileged-node-debugging/#validating-the-host-for-virtualization))

**Comment by victortoso** [comment]
Just to be sure, your node OS is `ubuntu 22.04` with kernel `5.15`* and with that, you see crashes in both `ubuntu 22.04` VMs and also `cirros` (kernel 4.4.0?"

**Comment by scydas** [comment]
> Can you please provide us the VM yaml you used for the first VM

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test2
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
      name: test2-rootdisk
      namespace: default
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
      source:
        registry:
          url: docker://system-images/ubuntu-22.04-x86_64:v1
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: test2-rootdisk
        name: rootdisk
      - cloudInitNoCloud:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiB0cnVlCmRpc2FibGVfcm9vdDogZmFsc2UKY2hwYXNzd2Q6IHsibGlzdCI6ICJyb290OmRhbmdlcm91cyIsIGV4cGlyZTogRmFsc2V9CgoKcnVuY21kOgogIC0gc2VkIC1pICIvI1w/UGVybWl0Um9vdExvZ2luL3MvXi4qJC9QZXJtaXRSb290TG9naW4geWVzL2ciIC9ldGMvc3NoL3NzaGRfY29uZmlnCiAgLSBzeXN0ZW1jdGwgcmVzdGFydCBzc2guc2VydmljZQogIC0gZGhjbGllbnQgLXIgJiYgZGhjbGllbnQ=
        name: cloudinitdisk
```

system image dockerfile:
```
FROM scratch
ADD --chown=107:107 ubuntu-22.04-x86_64.img /disk/
```
os img : 
https://cloud-images.ubuntu.com/jammy/20230828/jammy-server-cloudimg-amd64.img
