### ISSUE TITLE
Whether Kubvirt feature HostDevices support identify hot-pluggable USB device 

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11979]
According to docement https://kubevirt.io/user-guide/virtual_machines/host-devices/#usb-host-passthrough, in order to support identify USB device, one option is enable HostDevices, and modify KubeVirt-CR yaml to add related vendor id and product id. 

My question is whether  Kubvirt feature HostDevices support hot-pluggable USB device? If I switch different USB device, just modify KubeVirt-CR yaml, update new vendorid and productid, reapply KubeVirt-CR yaml, but NO NEED shutdown related vm and start vm. (Based on my test, I have to shutdown vm and start vm to take affect if we attach a different USB device)

BTW, I know another option support hot-plug, https://kubevirt.io/user-guide/operations/client_passthrough/ but I would like to verify whether HostDevices feature support.

My KubeVirt-CR yaml  example
```
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    vmRolloutStrategy: "LiveUpdate"
    permittedHostDevices:
      usb:
        - resourceName: kubevirt.io/storage
          selectors:
            - vendor: "xxxx"
              product: "xxxx"
    developerConfiguration:
      featureGates:
         - HostDevices
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```
