### ISSUE TITLE
Report VM conditions as kubernetes events

### ISSUE THREAD

**Issue by bc185174** [kubevirt/kubevirt#12046]
**Is your feature request related to a problem? Please describe**:

There are already a number of events on the VM and VMI resources but it seems like a few conditions are missing. This is ideal for configuration/state changes and being able to report those using a common interface.

**Describe the solution you'd like**:

Its quite common to report conditions as k8s events that automated processes (i.e. event sourcing) can work with. Ultimately, it avoids external dependencies having to understand the kubevirt schema and just the core `Event` schema.

For example:

```yaml
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: null
      message: 'cannot migrate VMI: PVC vm-1-disk is not shared, live migration
        requires that all PVCs must be shared (using ReadWriteMany access mode)'
      reason: DisksNotLiveMigratable
      status: "False"
      type: LiveMigratable
```

Reports as:

```yaml
apiVersion: v1
count: 1
eventTime: null
involvedObject:
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  name: vm-1
  namespace: vm-ns
kind: Event
message: 'cannot migrate VMI: PVC vm-1-disk is not shared, live migration
        requires that all PVCs must be shared (using ReadWriteMany access mode)'
metadata:
  name: vm-1.uuid
  namespace: vm-ns
reason: LiveMigratable
reportingComponent: ""
reportingInstance: ""
source:
  component: virt-handler
type: Normal
```

If wanted to go one step further, these can be reported as metrics too including the reason, status, and type as labels.

**Describe alternatives you've considered**:

Writing a custom parser for the VM conditions is a bit cumbersome...

**Additional context**:

**Comment by fabiand** [comment]
That's a neat idea.
Is this something you could contribute?

**Comment by bc185174** [comment]
> That's a neat idea. Is this something you could contribute?

Yeah more than happy to 💯

**Comment by fabiand** [comment]
That would be really awesome!

Helping users to understand what is happening on the cluster is valueable.

One thing to keep in mind: What component is emitting the event? I'd say VMs?

cc @xpivarc @acardace

**Comment by bc185174** [comment]
> That would be really awesome!
> 
> Helping users to understand what is happening on the cluster is valueable.
> 
> One thing to keep in mind: What component is emitting the event? I'd say VMs?
> 
> cc @xpivarc @acardace

I'd agree. From what I have looked at already, the VM conditions give us some great insights into if VM is running, stopped and/or live-migratable.

**Comment by fabiand** [comment]
Yep, and surfacing this into events is great, as this is giving us a "timeline".

**Comment by Acedus** [comment]
Hi there, I'd like to tackle this if possible!

From what I could see (and was stated by @bc185174) many VM states and conditions are already being surfaced via the the various controller event recorders.

Is the request here to change the current event format to utilize the VM status condition information or to simply add more events for states that aren't being emitted (e.g. `Paused`, `Resumed`, etc.)?

Example for `Paused` (added paused `SyncEvent`, neglected to alter `calulcatePausedCondition` return value for this example):

```go
func (d *VirtualMachineController) updatePausedConditions(vmi *v1.VirtualMachineInstance, domain *api.Domain, condManager *controller.VirtualMachineInstanceConditionManager) {

	// Update paused condition in case VMI was paused / unpaused
	if domain != nil && domain.Status.Status == api.Paused {
		if !condManager.HasCondition(vmi, v1.VirtualMachineInstancePaused) {
			calculatePausedCondition(vmi, domain.Status.Reason)
                        // Surface paused Event
                        d.recorder.Event(vmi, k8sv1.EventTypeNormal, v1.Paused.String(), vmi.Status.Conditions[len(vmi.Status.Conditions)-1].Message)
		}

	} else if condManager.HasCondition(vmi, v1.VirtualMachineInstancePaused) {
		log.Log.Object(vmi).V(3).Info("Removing paused condition")
		condManager.RemoveCondition(vmi, v1.VirtualMachineInstancePaused)
	}
}
```

```yaml
apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-06-24T07:01:14Z"
involvedObject:
  apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  name: vm-example
  namespace: example
kind: Event
message: VMI was paused by user
metadata:
  name: vm-example.17dbdea306af850d
  namespace: example
reason: Paused
reportingComponent: virt-handler
reportingInstance: node01
source:
  component: virt-handler
  host: node01
type: Normal
```

**Comment by bc185174** [comment]
Yeah I have no issue with this if you'd like to pick it up. So currently, the following events are reported on the virtual machine CR.

```bash
56m         Normal    SuccessfulDataVolumeCreate    virtualmachine/vm-2                                                   Created DataVolume vm-2-disk
8m          Normal    SuccessfulCreate              virtualmachineinstance/vm-2                                           Created virtual machine pod virt-launcher-vm-2-z4f44
91s         Normal    SuccessfulDelete              virtualmachineinstance/vm-2                                           Deleted virtual machine pod virt-launcher-vm-2-z4f44
91s         Normal    SuccessfulDelete              virtualmachine/vm-2                                                   Stopped the virtual machine by deleting the virtual machine instance 8be33335-6d62-4361-baf1-350b2c593f4a
80s         Normal    SuccessfulCreate              virtualmachineinstance/vm-2                                           Created virtual machine pod virt-launcher-vm-2-vmwhg
80s         Normal    SuccessfulCreate              virtualmachine/vm-2                                                   Started the virtual machine by creating the new virtual machine instance vm-2
41s         Normal    Created                       virtualmachineinstance/vm-2                                           VirtualMachineInstance defined.
41s         Normal    Started                       virtualmachineinstance/vm-2                                           VirtualMachineInstance started.
```

These conditions are not being emitted - understanding if a VM is running, live-migratable, and if the data volumes are ready.

```yaml
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-24T09:25:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: All of the VMI's DVs are bound and not running
    reason: AllDVsReady
    status: "True"
    type: DataVolumesReady
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
```

I do like the idea you propose on `Paused` and `Resumed` reasons.
