### ISSUE TITLE
IO policy is overwritten to thread for virtio-scsi

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#12112]
**What happened**:
The IO policy for scsi disk is always set to thread

**What you expected to happen**:
Be able to set the IO policy independently from the iothreads

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Start a VM with a disk with this configuration:
```yaml
  domain:
    ioThreadsPolicy: auto
    devices:
      disks:
      - disk:
          bus: scsi 
        name: containerdisk
        io: native

```

and verify the yaml:
```xml
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' error_policy='stop' io='threads' discard='unmap'/>
      <source file='/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2' index='2'/>
      <backingStore type='file' index='3'>
        <format type='qcow2'/>
        <source file='/var/run/kubevirt/container-disks/disk_0.img'/>
      </backingStore>
      <target dev='sda' bus='scsi'/>
      <alias name='ua-containerdisk'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>

```
