### ISSUE TITLE
Create arm64 vm on amd64 host Failed

### ISSUE THREAD

**Issue by YingML** [kubevirt/kubevirt#12176]
I have set useEmulation: true .

Failed to create arm64 VM on amd64 host by following yaml content.

Does kubevirt support creation of arm64 VMs on amd64 hosts? If so, how to create it?
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: arm64_vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: arm64_vm
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        devices:
          interfaces:
          - name: default
            masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: efi
          - disk:
              bus: virtio
            name: varstore
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
              #machine:
              #type: virt
        resources:
          requests:
            memory: 1024M
      networks:
          - name: default
            pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: ubuntu-22.04-server-cloudimg-arm64
      - name: efi
        persistentVolumeClaim:
          claimName: efi
      - name: varstore
        persistentVolumeClaim:
          claimName: varstore
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
```
