### ISSUE TITLE
Error in starting VM.

### ISSUE THREAD

**Issue by Amit-limbasiya** [kubevirt/kubevirt#12221]
I am creating vm through the yaml file. 
It is creating the VM, but when I try to turn the VM on, it is giving error as **image does not found**.

Here is the description of the VM through `kubectl describe vm testvm1` command.
```
Name:         testvm1
Namespace:    default
Labels:       kubevirt-manager.io/managed=true
              kubevirt.io/domain=testvm1
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1
API Version:  kubevirt.io/v1
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2024-06-26T06:36:11Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
  Generation:        2
  Resource Version:  748845
  UID:               0ce29ab3-bd57-472d-9f74-46b54fd374e1
Spec:
  Running:  true
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt-manager.io/managed:  true
        kubevirt.io/domain:           testvm1
    Spec:
      Architecture:  amd64
      Domain:
        Cpu:
          Cores:    1
          Sockets:  1
          Threads:  1
        Devices:
          Disks:
            Disk:
            Name:  disk1
            Disk:
              Bus:  virtio
            Name:   disk3
          Interfaces:
            Bridge:
            Name:                        net1
          Network Interface Multiqueue:  true
        Machine:
          Type:  q35
        Resources:
          Requests:
            Memory:  512Mi
      Networks:
        Name:  net1
        Pod:
      Node Selector:
        kubernetes.io/hostname:  minikube
      Priority Class Name:       vm-standard
      Volumes:
        Data Volume:
          Name:  default-testvm-disk1
        Name:    disk1
        Cloud Init No Cloud:
          Network Data:  version: 1
config:
    - type: physical
      name: enp1s0
      subnets:
      - type: dhcp
    - type: nameserver
      address:
      - '8.8.8.8'
      - '8.8.4.4'

          User Data:  #cloud-config
manage_etc_hosts: true
hostname: testvm1

        Name:  disk3
Status:
  Conditions:
    Last Probe Time:       2024-06-26T09:41:56Z
    Last Transition Time:  2024-06-26T09:41:56Z
    Message:               VMI does not exist
    Reason:                VMINotExists
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               All of the VMI's DVs are bound and not running
    Reason:                AllDVsReady
    Status:                True
    Type:                  DataVolumesReady
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade, bridge with kubevirt.io/allow-pod-bridge-network-live-migration VM annotation or a migratable plugin to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
  Desired Generation:      2
  Observed Generation:     2
  Printable Status:        CrashLoopBackOff
  Run Strategy:            Always
  Start Failure:
    Consecutive Fail Count:  39
    Last Failed VMIUID:      7e9ab3b8-8d09-4df8-888c-fd54829beeac
    Retry After Timestamp:   2024-06-26T09:46:56Z
  Volume Snapshot Statuses:
    Enabled:  false
    Name:     disk1
    Reason:   No VolumeSnapshotClass: Volume snapshots are not configured for this StorageClass [standard] [disk1]
    Enabled:  false
    Name:     disk3
    Reason:   Snapshot is not supported for this volumeSource type [disk3]
Events:
  Type    Reason            Age                  From                       Message
  ----    ------            ----                 ----                       -------
  Normal  SuccessfulDelete  11m (x28 over 153m)  virtualmachine-controller  (combined from similar events): Stopped the virtual machine by deleting the virtual machine instance f613da14-9693-445c-9524-3e489b826f27
  Normal  SuccessfulCreate  87s (x39 over 3h6m)  virtualmachine-controller  Started the virtual machine by creating the new virtual machine instance testvm1
```

When try to turn on VM, it(VM) gives error as **CrashLoopBackOff**. can not create VMI. NO VMI created.

What should be the reason and how to resolve the error to make the VM turn on.

**Comment by xpivarc** [comment]
@Amit-limbasiya You mentioned that you see ` image does not found.` message. Can you copy-paste the whole message?

**Comment by Amit-limbasiya** [comment]
Above was the output of describe command. Here in every reason attribute, you can see different reasons, why it fails. In the first status.conditions.reason (4th attribute in status section) you can see VMI does not exists.
```
Status:
  Conditions:
    Last Probe Time:       2024-06-26T09:41:56Z
    Last Transition Time:  2024-06-26T09:41:56Z
    Message:               VMI does not exist
    Reason:                VMINotExists
    Status:                False
    Type:                  Ready
```

**Comment by xpivarc** [comment]
There should be a vmi called `testvm1` once the controller starts the VM. Please post the yaml of the vmi in order to see the problem. Also post full yaml of the VM, it is most likely some misconfiguration if you saw  `image does not found.`

**Comment by Amit-limbasiya** [comment]
I am using kubevirt manager to deploy my application. it is open source project. so I am using it to deploy the VM.
I dont have the yaml file for this example.

But, I have one yaml file to create VM and I got the similar issue when I apply that yaml file. I am sharing that file with you.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-persistent
  name: vm-alpine-persistent
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-with-existing-dv
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
          - masquerade: {}
            name: default
        resources:
          requests:
            memory: 256Mi
            cpu: 1
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: my-data-volume
        name: datavolumedisk1
```
I have one data volume name my-data-volume.
When i apply this file it is also giving the same error.
