### ISSUE TITLE
Network initialization for the VM with network bridge interface inside AWS EKS cluster with vpc-cni 

### ISSUE THREAD

**Issue by sergs-pci** [kubevirt/kubevirt#12236]
**What happened**:
In the Virtual Machine that I created in AWS EKS k8s cluster following this documentation
https://kubevirt.io/quickstart_cloud/
https://kubevirt.io/labs/kubernetes/lab1.html
https://kubevirt.io/labs/kubernetes/lab2.html
I tried the bridge and masquerade network interfaces for the cirros demo VM I found that  bridge networks don't work. I can't resolve DNS, ping external resources etc from testvm-bridge, from another VM with masquerade it works

**What you expected to happen**:
Be able use external network from VM with bridge network interface, e.g
ping 8.8.8.8
nslookup google com
etc

**How to reproduce it (as minimally and precisely as possible)**:
Repeat steps in AWS EKS k8s cluster from documentation
https://kubevirt.io/quickstart_cloud/
https://kubevirt.io/labs/kubernetes/lab1.html
modify VM's manifest to use bridge network
try to ping anything from the VM

**Additional context**:
Simultaneously, I repeated the steps above in my local minikube with flannel CNI and both VMs(bridge and masquerade).
Both VMs had normal network connectivity. 
I checked the VM scheduled not only on the usual m5.large nodes with enabled nested virtualization. To avoid software emulation for virtualization, I created the node c5.metal, where I run the the bridge VM with KVM virtualization, but it also doesn't help.

console log for bridge VM:

> login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
> 
> 
> $ ip r
> default via 169.254.1.1 dev eth0
> 169.254.1.1 dev eth0
> $ ping 8.8.8.8
> PING 8.8.8.8 (8.8.8.8): 56 data bytes
> ^C
> --- 8.8.8.8 ping statistics ---
> 3 packets transmitted, 0 packets received, 100% packet loss
> $ ifconfig
> eth0      Link encap:Ethernet  HWaddr 42:D2:47:70:AB:11
>           inet addr:10.0.44.100  Bcast:10.255.255.255  Mask:255.255.255.255
>           inet6 addr: fe80::40d2:47ff:fe70:ab11/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
>           RX packets:13 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:30 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:1882 (1.8 KiB)  TX bytes:2181 (2.1 KiB)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:18 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:18 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1
>           RX bytes:1964 (1.9 KiB)  TX bytes:1964 (1.9 KiB)

The same commands are used in masquerade VM

> login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
> 
> 
> 
> $ ip r
> default via 10.0.2.1 dev eth0
> 10.0.2.0/24 dev eth0  src 10.0.2.2
> $ ping 8.8.8.8
> PING 8.8.8.8 (8.8.8.8): 56 data bytes
> 64 bytes from 8.8.8.8: seq=0 ttl=53 time=4.129 ms
> 64 bytes from 8.8.8.8: seq=1 ttl=53 time=1.748 ms
> 64 bytes from 8.8.8.8: seq=2 ttl=53 time=1.829 ms
> ^C
> --- 8.8.8.8 ping statistics ---
> 3 packets transmitted, 3 packets received, 0% packet loss
> round-trip min/avg/max = 1.748/2.568/4.129 ms
> 
> $ ifconfig
> eth0      Link encap:Ethernet  HWaddr 32:E2:1A:FE:15:FE
>           inet addr:10.0.2.2  Bcast:10.0.2.255  Mask:255.255.255.0
>           inet6 addr: fe80::30e2:1aff:fefe:15fe/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
>           RX packets:26 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:3137 (3.0 KiB)  TX bytes:2493 (2.4 KiB)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Environment**:
- KubeVirt version (use `virtctl version`): 
`Server Version: version.Info{GitVersion:"v1.2.1", GitCommit:"1a482dff915c80c7837530db5e049ef8aff624ca", GitTreeState:"clean", BuildDate:"2024-05-28T10:27:54Z", GoVersion:"go1.21.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}`

- Kubernetes version (use `kubectl version`): 
`Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b`

- VM or VMI specifications:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-bridge
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm-bridge
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

- Cloud provider or hardware configuration: AWS EKS v 1.30(also tried on v1.29), VPC-CNI v1.18.2-eksbuild.1
- OS (e.g. from /etc/os-release): Amazon Linux 2, AMI version 1.30.0-20240605
