### ISSUE TITLE
VirtualMachineInstanceMigrationState is not set until after a migration completes

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#12260]
**What happened**:
When trying to understand progress of a migration, I wanted to see some information from the VirtualMachineInstanceMigrationState. However during the migration this field was empty, so I could not get the information I wanted.

**What you expected to happen**:
During an active migration the VirtualMachineInstanceMigrationState is populated with information indicating the status of the migration.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt a storage live migration by enabling the following feature gates:
```
      - VolumesUpdateStrategy
      - VolumeMigration
      - VMLiveUpdateFeatures
```
and set the `vmRolloutStrategy: LiveUpdate`

Now modify a running VM with a new DataVolume disk, and appropriate volumeUpdateStrategy. This will cause a disk live migration. But the state is never updated in the migration resource.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): 1.29
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-fedora-datavolume
  name: vm-example
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-fedora-datavolume
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        ioThreadsPolicy: auto
        machine:
          type: q35
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: fedora-dv2
        name: datavolumedisk1
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-dv2
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/centos-stream:9
  storage:
    resources:
      requests:
        storage: 30Gi
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
@alicefr Not sure if this is purely a storage live migration issue or if any live migration has this issue.

**Comment by alicefr** [comment]
@awels do you mean the status of the vmim right not the migrationState in the VMI object? Was the migration running?

**Comment by alicefr** [comment]
ok what I got while the VMIM running is that only the source pod is populated:
```yaml
status:
  migrationState:
    sourcePod: virt-launcher-vm-dv-b77cz
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2024-07-15T17:14:51Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2024-07-15T17:14:51Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2024-07-15T17:14:54Z"
  - phase: PreparingTarget
    phaseTransitionTimestamp: "2024-07-15T17:14:54Z"
  - phase: TargetReady
    phaseTransitionTimestamp: "2024-07-15T17:14:54Z"
  - phase: Running
    phaseTransitionTimestamp: "2024-07-15T17:14:54Z"

```
