### ISSUE TITLE
kubevirt crd modify log level adjustment does not take effect

### ISSUE THREAD

**Issue by mansoncui** [kubevirt/kubevirt#12458]
kubevirt-cr.yaml modify log level adjustment does not take effect
```
cat  kubevirt-cr.yaml 
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      logVerbosity:
        virtAPI: 4
        virtController: 4
        virtHandler: 4
        virtLauncher: 4

kubectl apply -f  kubevirt-cr.yaml 
```
kubectl get deploy -n kubevirt  virt-api -o yaml  log level 2
```
apiVersion: apps/v1
kind: Deployment
metadata:
......
......
      containers:
      - args:
        - --port
        - "8443"
        - --console-server-port
        - "8186"
        - --subresources-only
        - -v
        - "2"
        command:
        - virt-api
        image: xxxxx/kubevirt/virt-api:v1.2.1
        imagePullPolicy: IfNotPresent
        name: virt-api
......
......
  replicas: 1
  updatedReplicas: 1
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.1
- Kubernetes version (use `kubectl version`): 1.29.0
- VM or VMI specifications:  2c4g
- Cloud provider or hardware configuration: Deploy on physical machine
- OS (e.g. from /etc/os-release): ubuntu 22 
- Kernel (e.g. `uname -a`): 5.15.0-82-generic 
- Install tools: operate install 
- Others:
