### ISSUE TITLE
Question: Why does KubeVirt add extra cpu.feature in domain XML

### ISSUE THREAD

**Issue by Yu-Jack** [kubevirt/kubevirt#12481]
## Question 

When I create a VM with specific cpu model and without specifying any CPU features like this.

```yaml
spec:
  architecture: amd64
  domain:
    cpu:
      cores: 1
      model: IvyBridge
      sockets: 1
      threads: 1
```

However, I get the following domain XML after dumping. I'm not sure why these features are automatically added to the domain XML.

```xml
<cpu mode='custom' match='exact' check='full'>
  <model fallback='forbid'>IvyBridge</model>
  <topology sockets='1' dies='1' cores='1' threads='1'/>
  <feature policy='require' name='hypervisor'/>
  <feature policy='require' name='arat'/>
  <feature policy='require' name='xsaveopt'/>
</cpu>
```

Is there any hidden mechanisms?

## Environment

KubeVirt Version: v1.1
