### ISSUE TITLE
Unable to schedule virt-api, virt-controller and virt-handler to specify node with nodeselector and tollerations

### ISSUE THREAD

**Issue by kesavakadiyala** [kubevirt/kubevirt#12501]
**What happened**:
Whenever I tried to deploy Kubevirt, their respective components virt-api, virt-controller and virt-handler are going to node where there are no taints and labels. I want to specify nodeSelector and tollerations for components virt-api, virt-controller and virt-handler. I tried to patch nothing has been working out.

apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}

**What you expected to happen**:
I expect components virt-api, virt-controller and virt-handler to deploy in specific pod where there are labels and taints set

**How to reproduce it (as minimally and precisely as possible)**:
$ VERSION="$(curl --silent https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)"
$ kubectl create --filename="https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml"
kubectl create --filename="https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml"

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"1.2.2", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.22.4", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T21:32:21Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-gke.1326000
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by fossedihelm** [comment]
Hey @kesavakadiyala You can also define a custom node placement in your KubeVirt CR, that will override the default configuration.
https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement

**Comment by bhat39a** [comment]
Hi @kesavakadiyala you have to update the nodeselector in your kubevirt CR. I am using the below config.

```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  workloads:
    nodePlacement:
      nodeSelector:
        NodeType: xxxxx
      tolerations:
      - key: "runner"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  infra:
    nodePlacement:
      nodeSelector:
        NodeType: xxxx
      tolerations:
      - key: "runner"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
```
