### ISSUE TITLE
Add virtio-rng support

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1260]
> As a user I want to be able to provide my guest with good random numbers. One way to achieve this is by using a virtio RNG device.

Design: https://docs.google.com/document/d/1G75lPm0dCf3ZcFnG6NJpUDZgTaQnFKKM7_glpXzH9uc/edit#

This issue is about adding a virtio rng device type including it's knbos, and two configuration profiles which reflect the oVirt and OpenStack configuration.

The device can be added by a user on demand (thus is _not_ automatically added to each VM).

The device should expose all the detailed settings you can configure on the the virtio-rng device.
And in addition it must expose a `profile` field which will set the knobs (i.e. backend, rate period and byets) according to profiles derived from oVirt and OpenStack.
A user can eitehr set the knbos himself, or choose from these two options.

The backend should be `/dev/random` if available or `dev/urandom` as a fallback.

# API

```yaml
kind: VMI
spec:
  domain:
    devices:
      rng:
        profile: ovirt  # DEFAULT
        # OR
        profile: openstack
        # OR
        rate: 
          period: 2000
          bytes: 1234
      …
```

libvirt reference. https://libvirt.org/formatdomain.html#elementsRng

Open Questions
- Is hardware RNG slower? Wouldn’t it be better to use /dev/urandom?
- If we know explicitly that a hardware RNG is present, we should request it (device plugins?), otherwise don’t request it and use /dev/random
  - This can be a follow up a) expose hwrng via DP, add virt controller awareness for hwrng devies
- How can we schedule nodes?
- How do we accommodate device plugins (unlimited devices?)
- A daemonset might need to prepare something?
