### ISSUE TITLE
vms cannot obtain ip addr

### ISSUE THREAD

**Issue by OAMchronicle** [kubevirt/kubevirt#12602]
**What happened**:
networks use default pod, interfaces mode use bridge. When I successfully created the VMs and then deleted and recreated them, the VMs could not obtain the IP address

**What you expected to happen**:
When I delete and then recreate the VMs, I can obtain the IP address

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian-vm-2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: debian-vm-2
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
                  #            - name: vmboot
                  #              disk:
                  #                bus: scsi
                  #              shareable: true
          filesystems:
            - name: vmboot
              virtiofs: {}
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            cpu: 1
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          persistentVolumeClaim:
            claimName: debian
        - name: vmboot
          persistentVolumeClaim:
            claimName: test-boot
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: True
              chpasswd:
                expire: False
              users:
                - default
                - name: root
                  lock_passwd: false
                  hashed_passwd: $6$rounds=4096$RheREhE.SgLmJvHp$uy/ufIQWc39LDxDuaIOrRn6PDPrl5nnm5tWzQKqqBa7uEjX3WIzgqpB1l5McvJJoT9paSXJnGjugeypyxNUx30
```
After creating the VMs according to the above file, delete the VMs and then recreate them

**Additional context**:
kubevirt: 1.2.0
kubernetes: 1.27.16
cni:(I tried using both, but neither of them worked)
  calico: 3.25.0
  cilium:  1.15.8

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  Debian GNU/Linux 12 (bookworm)
- Kernel (e.g. `uname -a`): 6.1.0-23-amd64
- Install tools: N/A
- Others: N/A
