### ISSUE TITLE
Hotplug is misbehaving when the volume migration feature gate is enabled

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#12670]
**What happened**:
When the volume migration feature gate is enabled, the volume hotplug action is misinterpreted as a replacement operation and hotplug doesn't work.

**What you expected to happen**:
Hotplug the volume as when the feature gate is disabled

**How to reproduce it (as minimally and precisely as possible)**:
Enable the volume migration feature gate:
```bash
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/vmRolloutStrategy", "value": "LiveUpdate"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=merge -p='{"spec": {"workloadUpdateStrategy": { "workloadUpdateMethods" : []}}}'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/workloadUpdateStrategy/workloadUpdateMethods/-", "value": "LiveMigrate"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=merge -p='{"spec": {"configuration": {"developerConfiguration": { "featureGates" : []}}}}'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VMLiveUpdateFeatures"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VolumesUpdateStrategy"}]'
kubectl patch kubevirt kubevirt -n kubevirt --type=json -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "VolumeMigration"}]'
```
Add a volume to a VM:
```bash
$ virtctl addvolume  --volume-name  hotplugdisk vm-dv
```
Check the VM:
```
  status:
    conditions:
[...]
    - lastProbeTime: null
      lastTransitionTime: "2024-08-26T11:14:23Z"
      message: the volumes replacement is effective only after restart
      status: "True"
      type: RestartRequired
```
