### ISSUE TITLE
disk.dev is used in documentation, but this feature does not exist

### ISSUE THREAD

**Issue by CrimsonFez** [kubevirt/kubevirt#12707]
**Description**:
When specifying a disk config in the domain, the documentation uses disk.dev. This is invalid configuration.
[Here is an example in the docs](https://kubevirt.io/user-guide/user_workloads/startup_scripts/#inject-ssh-key-using-a-custom-shell-script)
```yaml
...
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          dev: vda
      - name: cloudinitdisk
        disk:
          dev: vdb
...
```

**What you expected**:
Either add support for this in the API or correct the documentation.

**URL**:
https://kubevirt.io/user-guide/user_workloads/startup_scripts/#inject-ssh-key-using-a-custom-shell-script

**Additional context**:
I've seen this issue previously mentioned, #2402.
