### ISSUE TITLE
Specify pci topology and host bridges

### ISSUE THREAD

**Issue by dhruvik7** [kubevirt/kubevirt#12728]
**Is your feature request related to a problem? Please describe**:
We are using large multi-GPU machines with passthrough and want to be able to specify the guest PCI topology

**Describe the solution you'd like**:
In the host devices/GPU specification, some way to specify virtual bridges and topology

**Describe alternatives you've considered**:
This seems possible with the sidecar but we've had issues getting that to work

**Comment by vladikr** [comment]
@dhruvik7 yes, this could be very tricky to achieve by manually editing the controllers and bridges... 
Could you please provide an example of the configuration you have now and the desired one with changes?

Is this manual PCI topology needed to better align devices to physical cpus or anything else?

**Comment by dhruvik7** [comment]
Hi @vladikr , here is the current (old) and what we are looking for (new): https://gist.github.com/dhruvik7/d43932bf7c21c37fc719c92503a2bd5e 

Indeed, the goal is to better align devices to physical CPUs and also to represent certain devices sharing a host bridge (GPU and NIC)

**Comment by vladikr** [comment]
@dhruvik7 Thank you, I'll take a look.

Ideally KubeVirt should be able to achieve this instead of letting users manually configure this. We need to find a better API to express this intent.
Perhaps defining a group across virtual devices, something like:
```

kind: VirtualMachineInstance
spec:
  domain:
    devices:
      gpus:
      - deviceName: example.com/MY_GPU
        name: gpu1
        group: mygroup1
      interfaces:
      - name: test1
        bridge: {}
        group: mygroup1
```

Regarding physical cpus alignment to devices; in the past, I tried to expose this information using device metadata: https://github.com/kubevirt/kubevirt/pull/6946


I would start by writing user stories so we could start designing this better.

**Comment by mezuzza** [comment]
Hey @vladikr,
Thanks for the help. I work with @dhruvik7 on this product. It sounds like we can work around this using the [hook sidecar](https://kubevirt.io/user-guide/user_workloads/hook-sidecar/). Could you confirm that this is true?

Would you happen to know how we can confirm that the sidecar is being called? This is the config map minus the specific code:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: topo-mapper
data:
  topo.py: |
    #!/usr/bin/env python
    <Code here>
```

This is the VM config minus the spec

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    hooks.kubevirt.io/hookSidecars: >
      [
          {
              "args": ["--version", "v1alpha2"],
              "configMap": {"name": "topo-mapper", "key": "topo.py", "hookPath": "/usr/bin/onDefineDomain"}
          }
      ]
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: mez-topo-vm-2
```

I see no indication that this stuff gets called. Would the logs be a part of the virt-launcher pod?
