### ISSUE TITLE
Device plugin for /dev/net/tun not necessary

### ISSUE THREAD

**Issue by ansiwen** [kubevirt/kubevirt#1276]
/kind enhancement

The device manager of virt-handler creates a device plugin for both `/dev/kvm` and `/dev/net/tun`. However, the latter is not required. The `NET_ADMIN` capability is sufficient. As opposed to `/dev/kvm`, unprivileged containers can either create the device by themselves with 
```
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 600 /dev/net/tun
```

or they can be created with a hostPath volume within the pod specification, like for example this:

```
apiVersion: v1
kind: Pod
metadata:
  name: kvm-and-tun-consumer
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sleep", "123"]
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
    volumeMounts:
    - mountPath: /dev/net/tun
      name: dev-tun
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: false
  volumes:
  - hostPath:
      path: /dev/net/tun
      type: CharDevice
    name: dev-tun
```

So there is no need to manage a `devices.kubevirt.io/tun` resource.
