### ISSUE TITLE
Migration pending because of activePods not updated

### ISSUE THREAD

**Issue by AllenXu93** [kubevirt/kubevirt#12773]
**What happened**:
I had a vm created, and create a VirtualMachineInstanceMigration to make vm migrate to another node;

Then I tried another VirtualMachineInstanceMigration, VirtualMachineInstanceMigration CR is pending.
In virt-controller logs, it occurs: 
```
{"component":"virt-controller","kind":"","level":"info","msg":"Waiting to schedule target pod for migration because there are already multiple pods running for vmi default/testvm","name":"migration-jobq7r2j","namespace":"default","pos":"migration.go:998","timestamp":"2024-09-09T10:18:10.882038Z","uid":"ea29bd5e-5e12-4d4e-9af3-f2a5820e113f"}```
```

There are two launcher pods, one is in `Completed` phase because of first migration, the second is `Running`.

```
kubectl get po
NAME                         READY   STATUS      RESTARTS   AGE
virt-launcher-testvm-htmzg   3/3     Running     0          11m
virt-launcher-testvm-n2lww   0/3     Completed   0          12m
```

In vmi status,  activePods has both two pods, it shoud be only one pod which is `Running`

```
status:
  activePods:
    de5d7166-9b5b-441c-a03a-5b131b3d5243: yj-qaovnk8swork-02
    e19201bc-9cb1-46bc-af3d-687d9c9419fb: yj-qaovnk8swork-01
```

**What you expected to happen**:
vm can be migrated twice.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a vm
2. create a VirtualMachineInstanceMigration, which is successed
3. Then create another VirtualMachineInstanceMigration, which will be pending.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.2
- Kubernetes version (use `kubectl version`): v1.28.11
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 5Gi
            cpu: 4
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: harbor.weizhipin.com/cloud-native/kubevirt/centos:7.3
            path: /var/lib/libvirt/images/CentOS-7.3-Mulitiqueue.qcow2
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: test
              ssh_pwauth: True
              chpasswd: { expire: False }
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
