### ISSUE TITLE
StorageMigrations fails from RWX to RWX DataVolume

### ISSUE THREAD

**Issue by oujonny** [kubevirt/kubevirt#12811]
**What happened**:
I try to make use of StorageMigration by following this guide: https://kubevirt.io/user-guide/storage/volume_migration/
Right now the migration gets triggered but then fails with this error message:
`Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=84, Domain=10, Message='Operation not supported: use of 'VIR_MIGRATE_PARAM_MIGRATE_DISKS' requires use of 'VIR_MIGRATE_NON_SHARED_DISK' or 'VIR_MIGRATE_NON_SHARED_INC' flag'`

**What you expected to happen**:
The LiveMigration should be successful and the new instance runs on the new DV.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two RWX StorageClasses
2. Create a VM with DataVolumeTemplate which uses one of the StorageClasses
3. Create a new DV on the other StorageClass
4. Update the VM spec to use the new DV
5. LiveMigration should get trigger and fail with the error.

**Additional context**:
I currently running KubeVirt on main branch version (image tag: 20240911_926edf646) because of this issue here: https://github.com/kubevirt/kubevirt/issues/12519

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): 1.30.0
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-dv
  name: vm-dv
spec:
  updateVolumesStrategy: Migration
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
#        name: src-dv
        name: dst-dv
      spec:
        storage:
          accessModes:
            - ReadWriteMany
          volumeMode: Block
          resources:
            requests:
              storage: 10Gi
          storageClassName: sc-san-standard
        source:
          http:
            url: http://192.168.160.22/jammy-server-cloudimg-amd64.img
  runStrategy: "Always"
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-dv
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: datavolumedisk1
          interfaces:
            - masquerade: {}
              name: default
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
#            name: src-dv
            name: dst-dv
          name: datavolumedisk1
      networks:
        - name: default
          pod: {}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 24.04 LTS
- Kernel (e.g. `uname -a`): Linux 6.8.0-40-generic
- Install tools: N/A
- Others: N/A
