### ISSUE TITLE
[Solved] What is the default login password for containerDisk Ubuntu images from kubevirt quay.io?

### ISSUE THREAD

**Issue by garygan89** [kubevirt/kubevirt#12912]
**Description**:
The doc only mentioned the username `ubuntu`, but left out the password. I've tried other commonly used password but no avail:
- ubuntu
- password
- admin

**What you expected**:
A password to login.

**URL**:
[Provide a link to the documentation.](https://quay.io/repository/containerdisks/ubuntu?tab=info)

**Additional context**:
![image](https://github.com/user-attachments/assets/bf1601d5-8837-4269-a095-b5ed61ed3c67)

**Solved**

Adding a `userData` key in `cloudInitNoCloud` block.

```
...
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
```
