### ISSUE TITLE
Unexpected CPU Throttling with K0s even with dedicatedCpuPlacement

### ISSUE THREAD

**Issue by mega-alex** [kubevirt/kubevirt#12970]
**What happened**:
When deploying a KubeVirt VM, we can't achieve 100% CPU usage without throttling. This is despite enabling CPUManager static policy, and the VM pod being given the Guaranteed QOS along with the kubevirt options for dedicated CPU placement. We don't see this issue on other K8s distributions like rke2 with the same manifest, and can achieve 100% utilization of cores. We also don't see this issue when running regular pods, it seems like it is only an issue when running a kubevirt VM.

We've documented this issue [here](https://github.com/k0sproject/k0s/issues/4954) on the K0s side, and while it certainly seems to be related to an issue with the cgroup management in K0s, the fact that we can't reproduce the issue with a regular pod makes us think there might be something on the kubevirt side we can try to tweak.

**What you expected to happen**:

Be able to peg a CPU core at 100%

**How to reproduce it (as minimally and precisely as possible)**:

#### Install K0s and set a few flags to enable static CPU manager support: 

k0ctl config:
```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: cluster
spec:
  hosts:
  - ssh:
      # server-a - Controller
      address:  <controller ip>
      user: user
      port: 22
    role: controller
    installFlags:
      - --debug
  - ssh:
      # server-b - Worker
      address: <worker ip>
      user: user
      port: 22
    role: worker
    installFlags:
        - --debug
        - --kubelet-extra-args="--cpu-manager-policy=static --kube-reserved=cpu=1,memory=1Gi"
         # Label for sriov-network-operator & openebs topology
        - --labels="feature.node.kubernetes.io/network-sriov.capable=true"
  k0s:
    version: "v1.30.4+k0s.0"
    versionChannel: stable
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: cluster
```

You could also try this with the role set to `single` and only use one host.

#### Install kubevirt and deploy VM 

Kubevirt VM:
```yaml
 apiVersion: kubevirt.io/v1
 kind: VirtualMachine
 metadata:
   name: fedora-test
   namespace: vituralmachines
 spec:
   # runStrategy: Always
   template:
     spec:
       domain:
         ioThreadsPolicy: auto
         cpu:
            cores: 16
            model: host-model
            dedicatedCpuPlacement: true
            numa:
              guestMappingPassthrough: { }
         memory:
           hugepages:
             pageSize: 1Gi
         resources:
           limits:
             memory: 64Gi
         devices:
           # autoattachSerialConsole: true
           # autoattachMemBalloon: false
           # autoattachGraphicsDevice: false
           disks:
             - name: containerdisk
               disk:
                 bus: virtio
             - name: cloudinitdisk
               disk:
                 bus: virtio
           interfaces:
             - masquerade: {}
               pciAddress: "0000:09:00.0"
               name: default
           # rng: {}
       networks:
       - name: default
         pod: {}
       terminationGracePeriodSeconds: 10
       volumes:
         - name: containerdisk
           containerDisk:
             image: kubevirt/fedora-cloud-container-disk-demo:latest
         - name: cloudinitdisk
           cloudInitNoCloud:
             userData: |-
               #cloud-config
               password: fedora
               chpasswd: { expire: False }
 ```

On that VM run something like `for i in $(seq $(getconf _NPROCESSORS_ONLN)); do yes > /dev/null & done` and you'll see that the CPU cores won't be pegged at 100%. 

**Additional context**:

See the linked k0s issue for some initial `cgroup` debugging showing throttling issues. 

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.1
- Kubernetes version (use `kubectl version`): v1.30.4+k0s
- VM or VMI specifications: Listed above
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Debian 12
- Kernel (e.g. `uname -a`): 6.1.106-3
