### ISSUE TITLE
Incorrect operator behavior when using customizeComponents.patches

### ISSUE THREAD

**Issue by eshikhov** [kubevirt/kubevirt#12983]
When using customizeComponents.patches to change a virt-handler resource in a statement, a DaemonSet creation error occurs

I am using this config
```
customizeComponents:
  patches:
    - resourceType: DaemonSet
      resourceName: virt-handler
      patch: '[{"op": "add", "path": "/spec/template/spec/initContainers/1", "value": {"name": "disable-node-labeller", "image": "docker.io/bitnami/kubectl:1.30", "imagePullPolicy": "IfNotPresent", "env": [{"name": "NODE_NAME", "valueFrom": {"fieldRef": {"fieldPath": "spec.nodeName"}}}], "command": ["/bin/sh", "-c", "kubectl annotate nodes $NODE_NAME node-labeller.kubevirt.io/skip-node=true"]}}]'
      type: json
```

I see this error in the operator logs

```
{"component":"virt-operator","level":"error","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:743","reason":"unable to create daemonset &DaemonSet{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:DaemonSetSpec{Selector:nil,Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {[] [] [] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil <nil> [] []}},UpdateStrategy:DaemonSetUpdateStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,},Status:DaemonSetStatus{CurrentNumberScheduled:0,NumberMisscheduled:0,DesiredNumberScheduled:0,NumberReady:0,ObservedGeneration:0,UpdatedNumberScheduled:0,NumberAvailable:0,NumberUnavailable:0,CollisionCount:nil,Conditions:[]DaemonSetCondition{},},}: DaemonSet.apps \"virt-handler\" is invalid: [spec.template.spec.initContainers[2].name: Duplicate value: \"disable-node-labeller\", spec.template.spec.initContainers[3].name: Duplicate value: \"disable-node-labeller\", spec.template.spec.initContainers[4].name: Duplicate value: \"disable-node-labeller\", spec.template.spec.initContainers[5].name: Duplicate value: \"disable-node-labeller\"]","timestamp":"2024-10-02T08:57:33.200260Z"}
```

After restarting the operator pod (virt-operator), there are no errors and the DaemonSet is successfully created and my patch with the initcontainer is applied.

Log file from the operator pod:

[virt-operator.log](https://github.com/user-attachments/files/17227502/virt-operator.log)

**Environment**:
- KubeVirt version: v1.3.1
- Kubernetes version: v1.30.3
- OS: talos
- Kernel: 6.6.52-talos

**Comment by eshikhov** [comment]
The name “disable-node-labeller” is unique and the patch is inserted into a specific path /spec/template/spec/initContainers/1, but as I understand it, the operator tries to execute this patch multiple times, which is why there is an error with a duplicate name in the logs. But after restarting the operator pod, the logic works correctly and the patch is executed once.

**Comment by iholder101** [comment]
Thanks @eshikhov! Is the issue still relevant?

I wonder if we ever tried to use an "add" type patch as part of `customizeComponents`. It is part of the reconciler, so I think it may be running in a loop every once in a while, adding more and more init containers as you said. But would have to dive into that.

**Comment by eshikhov** [comment]
@iholder101 Yes, relevant

**Comment by dhiller** [comment]
/remove-lifecycle rotten

🏓 @iholder101 @enp0s3

**Comment by iholder101** [comment]
Hey @eshikhov!

As I wrote in the [comment above](https://github.com/kubevirt/kubevirt/issues/12983#issuecomment-2575517187), using "add" as part of `customizeComponents` is problematic since it is being reconciled, re-adding every reconcile loop which leads to the `spec.template.spec.initContainers[3].name: Duplicate value: \"disable-node-labeller\"` error.

A possible solution is to use a merge patch type instead, and do something like:
```yaml
patches:
  - resourceType: DaemonSet
    resourceName: virt-handler
    patch: >-
      {
        "spec": {
          "template": {
            "spec": {
              "initContainers": [
                {
                  "name": "disable-node-labeller",
                  "command": [
                    "...",
                  ]
                }
              ]
            }
          }
        }
      }
    type: merge
```

@eshikhov let me know if the issue can be closed or if I can help with anything else.
