### ISSUE TITLE
Rename registryDisk to containerDisk

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1308]
Today we have a volume source called `registryDisk`.

1. The term itself implies that there is a disk registry, which is technically right, but might be misleading.
2. The API could lead to the impression that the whole container is used as the disk source for the VM. but in reality it is a file within the container which is used as a disk image.

These two points are worth to resolve, in order to not block us to actually eveolve other stories around registries and containers in the future (i.e. meaning of a real container in the vm spec, or other registries).

An alternative API could be along the lines of:

```yaml
kind: VM
spec:
  …
  volumes:
  - name: wooooah
    containerDisk:
      image: quay.io/bob/ubuntu:latest
      path: /disk.img
```

I could actuall yimagine that path defaults to a certain path, or that a glob is used by default. (i.e. first file in / or so).

**Comment by fabiand** [comment]
To me this kind of API cleanup would be something for 1.0

**Comment by rmohr** [comment]
For me it is equally clear/unclear if the `container` is the disk or if we have a disk inside the container, no matter if we call it `registryDisk` or `containerDisk`. Also `imageDisk` would be an option to align it with the `image` term on pods.

But whatever is clearer for the majority works for me.

**Comment by aglitke** [comment]
I like containerDisk but I wonder if diskPath would be better than just path.

**Comment by j-griffith** [comment]
imageDisk is rather intuitive to me, but I wouldn't complain about containerDisk either.  I have to poke around a bit WRT the suggestion from @aglitke on using diskPath, seems like we naturally used that for some local variables so maybe that was the natural choice to begin with?

**Comment by davidvossel** [comment]
I'm good with something that looks like this. 

```
kind: VM
spec:
  …
  volumes:
  - name: wooooah
    containerDisk:
      image: quay.io/bob/ubuntu:latest
      path: /disk.img
```

Calling it "containerDisk" implies it's a disk that lives in a container. The "image" variable in the containerDisk spec indicates the container image to use which has the disk. All of that seems to mesh well with me. 

So, just from that spec I can derive two things without prior knowledge of what a containerDisk is.. 1. This volume has something to do with containers, and 2. I can specify what container image to use. That's the general idea
