### ISSUE TITLE
windows disk offline

### ISSUE THREAD

**Issue by yunzck8s** [kubevirt/kubevirt#13092]
**What happened**:

I created a Windows machine，use the following configuration:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-cirros-datavolume
  name: windows
  namespace: vms
spec:
  dataVolumeTemplates:
  - metadata:
      name: windows-pvc
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50G
        storageClassName: openebs-hostpath
      source:
        blank: {}
  running: false
  instancetype:
    kind: VirtualMachineInstancetype
    name: clarge
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-datavolume
    spec:
      domain:
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: pvcdisk
          - disk:
              bus: virtio
            name: windows-pvc
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk
      - name: pvcdisk
        persistentVolumeClaim:
          claimName: win2k16
      - dataVolume:
          name: windows-pvc
        name: windows-pvc
```
```
virtctl image-upload dv win2k16  
  --image-path=/root/cn_windows_server_2016_x64_dvd_9327743.iso     
  --access-mode=ReadWriteOnce    
  --size=6G   
  --storage-class=openebs-hostpath  
  --uploadproxy-url=https://10.102.22.6:443   
   --insecure    
  --wait-secs=240 --force-bind  
  -n vms
```
![1](https://github.com/user-attachments/assets/78ffae06-5795-490c-a6aa-93ef778bd4ab)

When I configured the system to select a disk, I did not see the 50G PVC I mounted. After loading the driver, the mounted disk was displayed, but it was offline.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.1
- Kubernetes version (use `kubectl version`): v1.30.5
- OS (e.g. from /etc/os-release): rocky 9.4
- Kernel (e.g. `uname -a`): 5.14.0-427.13.1.el9_4.x86_64
