### ISSUE TITLE
KubevirtVmHighMemoryUsage firing even though compute has memory limit higher then requested amount

### ISSUE THREAD

**Issue by SPodjasek** [kubevirt/kubevirt#13102]
We're observing frequent alerts of this kind for one of VM's (running Windows Server), despite setting memory limit higher then memory request - as described in runbook:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: virt-launcher-vm-....
spec:
  containers:
  - name: compute
    resources:
      limits:
        memory: 71146Mi
      requests:
        memory: 66026Mi
```

https://github.com/kubevirt/kubevirt/blob/15090de920b2345df8f56eb70a3d6ecc64d60992/pkg/monitoring/rules/alerts/vms.go#L32-L44
