### ISSUE TITLE
Kubevirt Windows cloudInitNoCloud

### ISSUE THREAD

**Issue by lygopher** [kubevirt/kubevirt#13119]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.
I want to create windows in kubevirt and then initialize the windows user password through cloudInitNoCloud, but I can't find the relevant configuration
**Describe the solution you'd like**:
How to configure Windows user password in cloudInitNoCloud
**Describe alternatives you've considered**:

**Additional context**:
I tried to configure Windows according to the configuration of linux cloudInitNoCloud, but it didn't work
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win10-cloudinit
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-cloudinit
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          interfaces:
            - masquerade: { }
              model: e1000
              name: default
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: cdrom
            - cdrom:
                bus: sata
              name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
        - name: default
          pod: { }
      volumes:
        - name: cdrom
          persistentVolumeClaim:
            claimName: win10-cloudinit
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: admin
              password: 12345678
              chpasswd: { expire: False }
          name: cloudinitdisk
```
Can anyone give me some examples or documentation?
