### ISSUE TITLE
Cannot ping ARM virtual machine with more than 1 socket due to vCPU hotplug error

### ISSUE THREAD

**Issue by jangel97** [kubevirt/kubevirt#13118]
When creating an ARM virtual machine (VM) with more than 1 socket (as specified in the `sockets` field of the `cpu` section in the YAML manifest), the VM cannot be pinged, and the following event is observed in the logs of the VMI:

```
Warning  SyncFailed        54s   virt-handler                 server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: vcpu '2' is missing hotplug data')"
```

**Environment:**

- KubeVirt version: `kubevirt-hyperconverged-operator.v4.16.3        OpenShift Virtualization`
- OpenShift version: `4.16.4`
- Kubernetes version: `v1.29.6+aba1e8d`
- Virtualization architecture: ARM64
- Storage backend: NFS

**Steps to reproduce:**

1. Create a VirtualMachine manifest with the following specifications:
    - Architecture: ARM64
    - CPU: 2 sockets, 2 cores, 1 thread
    - Disk: Root disk and cloud-init disk
    - Network: Masquerade
    - Storage: NFS (ReadWriteMany)
2. Deploy the VM in the cluster.
3. Attempt to ping the VM or access it after creation.

**VM Manifest:**

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    redhatit_kubevirtvm_automation_data: provisioning-configuration
  labels:
    app: armpocrhel8
    app_code: ansi-001
    kubevirt.io: redhatit
    kubevirt.io/domain: armpocrhel8
    managed: DIS
    name: armpocrhel8
    servicephase: Production
  name: armpocrhel8
  namespace: dis--runtime-int
spec:
  tolerations:
  - effect: NoSchedule
    key: paas.redhat.com/arch
    value: arm64
    operator: Equal
  dataVolumeTemplates:
  - metadata:
      name: rootdisk-armpocrhel8
    spec:
      source:
        registry:
          url: docker://images.paas/it-uis/it-base-rhel8_arm
      storage:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 30Gi
        storageClassName: rh-restricted-nfs
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: armpocrhel8
    spec:
      tolerations:
      - effect: NoSchedule
        key: paas.redhat.com/arch
        value: arm64
        operator: Equal
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            configDrive: {}
          source:
            secret:
              secretName: provisioning-ssh-public-key
      architecture: arm64
      domain:
        cpu:
          cores: 2
          sockets: 2
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        features:
          smm:
            enabled: false
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rootdisk-armpocrhel8
        name: rootdisk
      - cloudInitConfigDrive:
          userData: |
            #cloud-config
            users:
              - default
              - name: cloud-user
                lock_passwd: true
        name: cloudinitdisk
```

**Expected behavior:**

The VM should be accessible and pingable after creation when using more than 1 socket.

**Actual behavior:**

The VM is not pingable, and the following event is observed:
```
Warning  SyncFailed        54s   virt-handler                 server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: vcpu '2' is missing hotplug data')"
```

**Additional information:**

- Reducing the socket count to 1 makes the VM pingable and operational.
- AMD64 VM works no matter the socket count value.
