### ISSUE TITLE
e1000 ens1: Reset adapter

### ISSUE THREAD

**Issue by IanMoroney** [kubevirt/kubevirt#13239]
**What happened**:
Weird issue with an ubuntu 22.04 guest VM. DHCP network goes up and down constantly.
The correct IP address gets issued (the container's IP) when looking at `ip addr` and the connection is up. A few seconds later, the  nic is down with `no carrier`. A few seconds later, it's back up again.

Journalctl shows this:

![image](https://github.com/user-attachments/assets/84b2e576-6540-4a86-a989-10e8e7923f64)

If I set the ip to static assignment, it doesn't go up and down, but other issues occur (some dns addresses, but not all, won't resolve, can't download some things via curl or wget, but i can ping the address) so static isn't an option either.

If I install the VM from scratch, the same behaviour is seen in the ubuntu installer when it's selecting the network. Set it to dhcp and it goes up and down ad infinitum.

It's worth mentioning that my VNC connection to the VM stays solid while this is occurring, so it doesn't seem like it's a problem with the host, or with k8s, or with kube-virt as a hypervisor. It just seems to affect the guest VM OS.

**What you expected to happen**:
The network should stay up and not reset.

**How to reproduce it (as minimally and precisely as possible)**:
Try installing an ubuntu 22.04.5 guest on kube-virt running on microk8s.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v1.3.1", GitCommit:"ed1e7ae8548d319fa7aacf315ad198f7241287c5", GitTreeState:"clean", BuildDate:"2024-08-22T08:52:25Z", GoVersion:"go1.22.2 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2
```
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-ubuntu-clarge-ubuntu-2204-2204
  name: vm-ubuntu-clarge-ubuntu-2204
spec:
  dataVolumeTemplates:
  - metadata:
      name: ubuntu2204vm
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        blank: {}
  instancetype:
    kind: VirtualMachineInstancetype
    name: clarge
  preference:
    kind: VirtualMachinePreference
    name: ubuntu
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-ubuntu-clarge-ubuntu-2204
    spec:
      domain:
        devices:
          disks:
          - cdrom:
              bus: sata
            name: ubuntu2204iso
          - disk:
              bus: virtio
            name: ubuntu2204vm
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
            - name: br0
              bridge: {}
          gpus:
            - name: gpu1
              deviceName: gpu.intel.com/i915
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        resources: {}
      terminationGracePeriodSeconds: 0
      networks:
        - name: br0
          pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
        name: virtiocontainerdisk
      - dataVolume:
          name: ubuntu2204iso
        name: ubuntu2204iso
      - dataVolume:
          name: ubuntu2204vm
        name: ubuntu2204vm
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 24.04.1 on host, Ubuntu 22.04.5 on guest
- Kernel (e.g. `uname -a`): 6.8.0-48-generic on host and guest
