### ISSUE TITLE
Log span about VirtualMachineInstancePresets deprecation without any usage of it

### ISSUE THREAD

**Issue by vladimirfx** [kubevirt/kubevirt#13242]
**What happened**:

Continues log emission without any reference to VirtualMachineInstancePresets in cluster configuration:

`W1113 06:26:40.352146 1 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.`

**What you expected to happen**:

No log spamming if I do not use the deprecated feature.

**How to reproduce it (as minimally and precisely as possible)**:

Install Kubevirt and create a VM.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.3.1
- Kubernetes version (use `kubectl version`): 1.30.5
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vladimirfx** [comment]
> @vladimirfx on your cluster, are there any VMs using presets? Did you actually use this feature?

No, nothing is mentioned `VirtualMachineInstancePresets`, even in annotations. Not instances of VirtualMachineInstancePresets in the cluster.

Actual VM config:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: reporting-vm
  namespace: reporting
spec:
  running: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reporting-vm
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 5Gi
        devices:
          disks:
          - disk:
              bus: sata
            name: datavolumevolume
          interfaces:
          - name: network
            model: rtl8139
            bridge: {}
          rng: {}
        machine:
          type: "q35"
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 5Gi
            cpu: 2
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: reporting-dv
        name: datavolumevolume
      networks:
      - name: network
        pod: {}

```
