### ISSUE TITLE
virtctl console got stuck,expandDisk featuregate failed

### ISSUE THREAD

**Issue by Forrest-Tao** [kubevirt/kubevirt#13264]
**What happened**:
After executing the `virtctl console vmname `  command, it got stuck

1. Created a PVC with ubuntu `disk.img`, then created a snapshot for it
2. Used this snapshot to create a new PVC
3. Then used this PVC as the system disk to start an Ubuntu VM
4. Finally, used `virtctl console vmname` to interact with the VM, but found it stuck 

Here is my yamls.

```yaml
---
#create one snapshot of the img original
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ubuntu-img-ori-snap
spec:
  volumeSnapshotClassName: lvmpv-snapclass
  source:
    persistentVolumeClaimName: ubuntu-img-ori
---
#create one pvc using the snapshot
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-2-sysdata
spec:
  storageClassName: openebs-lvmpv
  dataSource:
    kind: VolumeSnapshot
    name: ubuntu-img-ori-snap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
#create one vm using the pvc
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-snapshot-test
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: sysdata
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: sysdata
          persistentVolumeClaim:
            claimName: vm-2-sysdata
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm1
              chpasswd:
                list: |
                  ubuntu:ubuntu
                expire: False
```
Hear is my vm & vmi status, they looks great
``` bash
root@mc-master01:/home/wtadmin/yst/cloudinit-demo/snap# k get vm
NAME                     AGE     STATUS    READY
ubuntu-snapshot-test-2   5m33s   Running   True
root@mc-master01:/home/wtadmin/yst/cloudinit-demo/snap# k get vmi
NAME                     AGE     PHASE     IP              NODENAME        READY
ubuntu-snapshot-test-2   5m36s   Running   172.31.201.34   mc-registry01   True
```
But I found the vm was strucked.
``` bash
root@mc-master01:/home/wtadmin/yst/cloudinit-demo/snap# virtctl console ubuntu-snapshot-test-2
Successfully connected to ubuntu-snapshot-test-2 console. The escape sequence is ^]
```
I checked the status of the PVC
``` bash
root@mc-registry01:/var/lib/kubelet/pods/95b16aed-140f-4e4f-9b4e-f4bca6f20088/volumes/kubernetes.io~csi/pvc-b234432f-7949-4c4f-befb-77a9cf4e9de8/mount# ls
disk.img  lost+found
root@mc-registry01:/var/lib/kubelet/pods/95b16aed-140f-4e4f-9b4e-f4bca6f20088/volumes/kubernetes.io~csi/pvc-b234432f-7949-4c4f-befb-77a9cf4e9de8/mount# du -s
24     
```
logs of the `comput`  container of the virt-launcher pod

```bash
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa84003290 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"26","timestamp":"2024-11-16T15:15:35.248000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=0x7ffa78002f80, (VM: name=default_ubuntu-snapshot-test-2, uuid=caae5740-98e0-5877-bbdc-69199088e11a), flags=0x0","pos":"virDomainGetXMLDesc:2819","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.248000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa78002f80 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.249000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=0x7ffa800048b0, (VM: name=default_ubuntu-snapshot-test-2, uuid=caae5740-98e0-5877-bbdc-69199088e11a), state=0x7ffa80000b80, reason=0x7ffa80000b84, flags=0x0","pos":"virDomainGetState:2714","subcomponent":"libvirt","thread":"28","timestamp":"2024-11-16T15:15:35.251000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa800048b0 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"28","timestamp":"2024-11-16T15:15:35.251000Z"}
{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1316","timestamp":"2024-11-16T15:15:35.254343Z"}
{"component":"virt-launcher","level":"info","msg":"conn=0x7ffa40013190, name=default_ubuntu-snapshot-test-2","pos":"virDomainLookupByName:449","subcomponent":"libvirt","thread":"32","timestamp":"2024-11-16T15:15:35.254000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa84003b30 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"32","timestamp":"2024-11-16T15:15:35.254000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=0x7ffa64001460, (VM: name=default_ubuntu-snapshot-test-2, uuid=caae5740-98e0-5877-bbdc-69199088e11a), state=0x7ffa64003360, reason=0x7ffa64003364, flags=0x0","pos":"virDomainGetState:2714","subcomponent":"libvirt","thread":"33","timestamp":"2024-11-16T15:15:35.255000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa64001460 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"33","timestamp":"2024-11-16T15:15:35.255000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=0x7ffa840032e0, (VM: name=default_ubuntu-snapshot-test-2, uuid=caae5740-98e0-5877-bbdc-69199088e11a), flags=0x0","pos":"virDomainGetXMLDesc:2819","subcomponent":"libvirt","thread":"26","timestamp":"2024-11-16T15:15:35.255000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa840032e0 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"26","timestamp":"2024-11-16T15:15:35.255000Z"}
{"component":"virt-launcher","level":"info","msg":"dom=0x7ffa78003410, (VM: name=default_ubuntu-snapshot-test-2, uuid=caae5740-98e0-5877-bbdc-69199088e11a), info=0x7ffa8aa6c8a0, flags=0x0","pos":"virDomainGetBlockInfo:6626","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.257000Z"}
{"component":"virt-launcher","level":"info","msg":"Starting job: API=remoteDispatchDomainGetBlockInfo job=query agentJob=none asyncJob=none (vm=0x7ffa7c01d930 name=default_ubuntu-snapshot-test-2, current job=none agentJob=none async=none)","pos":"virDomainObjBeginJobInternal:318","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.257000Z"}
{"component":"virt-launcher","level":"info","msg":"Started job: query (async=none vm=0x7ffa7c01d930 name=default_ubuntu-snapshot-test-2)","pos":"virDomainObjBeginJobInternal:382","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.257000Z"}
{"component":"virt-launcher","level":"info","msg":"Entering monitor (mon=0x7ffa7c01f180 vm=0x7ffa7c01d930 name=default_ubuntu-snapshot-test-2)","pos":"qemuDomainObjEnterMonitorInternal:6430","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.257000Z"}
{"component":"virt-launcher","level":"info","msg":"Exited monitor (mon=0x7ffa7c01f180 vm=0x7ffa7c01d930 name=default_ubuntu-snapshot-test-2)","pos":"qemuDomainObjExitMonitor:6459","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.264000Z"}
{"component":"virt-launcher","level":"info","msg":"Check if path /var/run/kubevirt-private/vmi-disks/sysdata/disk.img with FS magic 61267 is shared","pos":"virFileIsSharedFSType:3618","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.264000Z"}
{"component":"virt-launcher","level":"info","msg":"Stopping job: query (async=none vm=0x7ffa7c01d930 name=default_ubuntu-snapshot-test-2)","pos":"virDomainObjEndJob:613","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.264000Z"}
{"component":"virt-launcher","level":"info","msg":"release domain 0x7ffa78003410 default_ubuntu-snapshot-test-2 caae5740-98e0-5877-bbdc-69199088e11a","pos":"virDomainDispose:326","subcomponent":"libvirt","thread":"30","timestamp":"2024-11-16T15:15:35.264000Z"}
{"component":"virt-launcher","level":"info","msg":"disk size is not 1MiB-aligned. Adjusting from 56822417326 down to 56822333440.","pos":"util.go:226","timestamp":"2024-11-16T15:15:35.264835Z"}
{"component":"virt-launcher","level":"info","msg":"Not expanding disks, ExpandDisks featuregate disabled","pos":"manager.go:1427","timestamp":"2024-11-16T15:15:35.264871Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"ubuntu-snapshot-test-2","namespace":"default","pos":"server.go:208","timestamp":"2024-11-16T15:15:35.264905Z","uid":"ea3f7954-cc9c-4505-802d-ad983bc45e73"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:35.448274Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:36.447776Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:37.448028Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:38.448276Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:39.448435Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:40.447684Z"}
{"component":"virt-launcher","level":"info","msg":"Refreshing. domainName default_ubuntu-snapshot-test-2 pid 80","pos":"monitor.go:143","timestamp":"2024-11-16T15:15:41.447555Z"}
{"compone
```

Why is it "Not expanding disks", I have already  opend  `ExpandDisks` featuregate.

``` bash
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1","kind":"KubeVirt","metadata":{"annotations":{},"name":"kubevirt","namespace":"kubevirt"},"spec":{"configuration":{"developerConfiguration":{"featureGates":["Root","HostDisk","LiveMigration"]}}}}
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  creationTimestamp: "2024-10-14T01:52:20Z"
  finalizers:
  - foregroundDeleteKubeVirt
  generation: 14
  name: kubevirt
  namespace: kubevirt
  resourceVersion: "72713623"
  uid: 1662ea37-e4c1-47bc-82af-0de75065af76
spec:
  configuration:
    developerConfiguration:
      featureGates:
      - Root
      - HostDisk
      - Snapshot
      - HotplugVolumes
      - VolumeSnapshotDataSource
      - ExpandDisks
 ...
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.1", GitCommit:"ed1e7ae8548d319fa7aacf315ad198f7241287c5
- Kubernetes version (use `kubectl version`): Kubernetes v1.29.5
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: useEmulation: true
- OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`):  x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A
