### ISSUE TITLE
virt-handler memory consumption is very high

### ISSUE THREAD

**Issue by anvarik** [kubevirt/kubevirt#13295]
[cluster-profiler-results.zip](https://github.com/user-attachments/files/17926117/cluster-profiler-results.zip)

**What happened**:
We are deploying Windows images to KubeVirt, and virt-handler memory consumption increases over time. While running kubevirt v1.2.0 for three weeks, each virt-handler consumed around 7–12 GB of memory.

Yesterday, we upgraded to v1.4.0. For the first 10 hours, the three virt-handler pods maintained approximately 100 MB of memory usage. 24 hours later one of the virt-handlers has reached 7 GB, while the other two are around 800 MB - I think this trend will continue to escalate exponentially.

**What you expected to happen**:
Memory consumption should be lower.

**How to reproduce it (as minimally and precisely as possible)**:
We are deploying windows 2022 images to kubevirt.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): we have multiple clusters ranging from 1.29.7 and 1.30.4
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  annotations:
    helm.sh/hook: pre-upgrade,pre-install,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "3"
    helm.sh/resource-policy: keep
  generation: 2
  labels:
    app: document
    app.kubernetes.io/instance: document
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: document
  name: document
  namespace: kubevirt
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: document
      app.kubernetes.io/name: document
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "false"
            ISTIO_META_DNS_AUTO_ALLOCATE: "false"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: document
      name: document
    spec:
      domain:
        devices:
          disks:
          - name: kubevirt-volume
          - cdrom:
              bus: sata
            name: downward-api-disk
          - cdrom:
              bus: sata
            name: configmap-disk
          interfaces:
          - masquerade: {}
            name: kubevirt-network
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
      livenessProbe:
        failureThreshold: 6
        httpGet:
          path: /healthz/live
          port: 5000
        periodSeconds: 300
        successThreshold: 1
      networks:
      - name: kubevirt-network
        pod: {}
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      readinessProbe:
        failureThreshold: 5
        httpGet:
          path: /vmready
          port: 5000
        periodSeconds: 300
        successThreshold: 1
      tolerations:
      - key: CriticalAddonsOnlycode
        operator: Exists
      volumes:
      - containerDisk:
          image: registry.io/image:12345
        name: kubevirt-volume
      - downwardAPI:
          fields:
          - fieldRef:
              fieldPath: metadata.name
            path: k8s_pod_name
          - fieldRef:
              fieldPath: metadata.namespace
            path: k8s_namespace_name
        name: downward-api-disk
      - configMap:
          name: configmap
        name: configmap-disk
```

- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): windows 2022
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
