### ISSUE TITLE
Specify the service accounts mounted into the VM

### ISSUE THREAD

**Issue by Helen300** [kubevirt/kubevirt#13311]
**Is your feature request related to a problem? Please describe**:

I want to mount an EKS service account containing an IAM role. Currently, when I mount this service account as a [filesystem into the VM following these instructions here ](https://kubevirt.io/user-guide/storage/disks_and_volumes/#as-a-filesystem_2), it only mounts the service account at [this specific path](https://github.com/kubevirt/kubevirt/commit/b69c8449a01b6054cf5828bd1041044ef48f3107#diff-a3d824da3c42420cd5cbb0a4a2c0e7b5bfddd819652788a0596d195dc6e31fa5R54-R55) into the VM. However, looking at the virt launcher pod spec, it seems that the virt launcher pod actually has two mounts associated with an EKS service account - the kubernetes component and the eks component. 

Below is a portion of the virt launcher pod spec
```
Environment:
    # SOME AWS ENV VARIABLES HERE
Mounts:
    /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
    /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-j8cqt (ro)
```

Whereas, the service account that is mounted into the VM only contains one of the mounts because of the source [dir specified here](https://github.com/kubevirt/kubevirt/commit/b69c8449a01b6054cf5828bd1041044ef48f3107#diff-a3d824da3c42420cd5cbb0a4a2c0e7b5bfddd819652788a0596d195dc6e31fa5R54-R55). 
More context: https://github.com/kubevirt/kubevirt/blob/2fb611a54b6f52e3586e677512ffc8c60e8d252c/pkg/virt-controller/services/virtiofs.go#L147
```
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-j8cqt (ro)
```

Essentially, I want to mount a different service account into my VM other than the one at the hardcoded path. Are there any recommended approaches to resolving this? Thanks!

Some suggested approaches:
- recursively looking in /var/run/secrets for serviceaccounts and mounting all those
- changing the way that serviceAccount is mounted by specifying the paths that we want to mount rather than a single hardcoded path 
- perhaps we need sidecars to inject the additional service account tokens into the VM?

**Describe the solution you'd like**:

I would like to either see all service accounts mounted on the virt launcher pod to also get mounted into the VM or be able to specify the path to the service account that I want mounted from the pod into the VM.

**Comment by alicefr** [comment]
@Helen300 can you please share the yaml of your VM?

I'm a bit confused by the description, however, one thing is the pod and the other is the VM. You only get the service account in the VM which you declared in the VM specification. The pod could have additional SAs, but they might be proper to the pod and not belonging to the VM.  IOW, you should only care about the SAs that you declared in the you VM.

**Comment by Helen300** [comment]
hi @alicefr , thanks for your response! Here's my VM spec
```
apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
    creationTimestamp: "2024-11-20T18:18:47Z"
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    generation: 2
    name: ubuntu
    namespace: default
  spec:
    running: true
    template:
      metadata:
        creationTimestamp: null
        name: ubuntu
      spec:
        architecture: amd64
        domain:
          cpu:
            cores: 8
            dedicatedCpuPlacement: true
          devices:
            filesystems:
            - name: service-account
              virtiofs: {}
          firmware: {}
          machine:
            type: q35
          memory:
            guest: 8192M
          resources:
            limits:
              memory: 9216M
        networks:
        - name: default
          pod: {}
        volumes:
        - containerDisk:
            image: image
          name: containerdisk
        - cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp100s0:
                  dhcp4: true
            secretRef:
              name: cloud-init-ubuntu
          name: cloudinit
        - name: service-account
          serviceAccount:
            serviceAccountName: default
```

**Comment by seastco** [comment]
+1 thanks for raising this @Helen300, I ran into this a month ago but did not root cause it. it looks like when annotating a service account with the EKS annotation and attaching this to a pod, the pod is indeed getting two tokens. it would be great for KubeVirt to support mounting multiple tokens or being able to specify the token to mount into the VM.

**Comment by Helen300** [comment]
It appears that the additional service account information is added to the pod via this https://github.com/aws/amazon-eks-pod-identity-webhook#amazon-eks-pod-identity-webhook

**Comment by alicefr** [comment]
@Helen300 thanks for the investigations and information!
It appears to me that we would need to extend KubeVirt to support additional service account locations. 

One option could be to introduce a new webhook which injects a second virtiofs container which added the SA with the custom path, and then a kubevirt sidecar which adds the path in the XML. Doable, but not very straightforward.

I don't think this can be in the VM API but it needs to be rather a configuration extension and option which we need to add into the kubevirt operator/controller to check for custom locations and additional tokens.

Do you think you can work on this?

**Comment by aerosouund** [comment]
@Helen300 
are you working on this ? if not, can i work on it please ?

**Comment by Helen300** [comment]
Hi @aerosouund , feel free to work on this. I have started to work on this a bit so will share what I ended up doing / last blockers

Note: Decided to write a solution  that is specific to service accounts that have the EKS annotation - so not supporting just any service accounts audiences. Future extensions can probably be made the same way. 

1. First, a webhook that will modify the VM spec. I was intending for this to webhook to act upon VM resources. It would check to see if a service account is mounted as volume. If so, then it would look up the service account resource in kube, see if there is an eks annotation and if so, modify the VM spec directly to add a filesystem entry for the virtiofs container corresponding to the eks service account token mount. Then this should add a label to the VM resource that specifies the name of the filesystem device and that there is a eks annotation on the service account volume
2. Another webhook that modifies the virt launcher pod. This webhook will simply inject a virtiofs container to the pod. The container will creates the socket for the corresponding eks service account token in the same way that it does for any virtiofs container. I have this portion written and tested that it can successfully inject the necessary containers given that the VM spec is setup properly. 

Did you have a different solution in mind?

**Comment by aerosouund** [comment]
@Helen300 
Thanks alot for the detailed description
Trying to make sense of your solution, so i will rephrase what i understand and please correct me if i am wrong. First of all..

> It would check to see if a service account is mounted as volume.

How might this look ? I envision something like this (in the vm spec)

```yaml
  volumes:
  - name: service-account1
    serviceAccount:  # the webhook checks for this key in volumes
      serviceAccountName: default
  - name: service-account2
    serviceAccount: 
      serviceAccountName: some-eks-sa
```
If the webhook found them.. then as you say
> modify the VM spec directly to add a filesystem entry for the virtiofs container corresponding to the eks service account token mount

So, what gets added by the webhook is this

```yaml
      filesystems:
      - name: service-account  #those
        virtiofs: {}
      - name: service-account2
        virtiofs: {}
```

For the next step, you say

> This webhook will simply inject a virtiofs container to the pod. The container will creates the socket for the corresponding eks service account token in the same way that it does for any virtiofs container

so when the virt-launcher pod gets created, this webhook will add a virtioFS container per service account found in the vm definition. You say you already have some code written down for this, would love to see it!

Which leaves the last step

>Last thing is that the [amazon eks identity webhook](https://github.com/aws/amazon-eks-pod-identity-webhook#amazon-eks-pod-identity-webhook) that injects the eks specific token also injects environment variables. These env variables are also needed in addition to the token so we need some way to mount these env variables into the VM itself, I was thinking through the cloudinit, we can look at the env variables on the virt launcher pod and write these into the VM.

I believe this is the only AWS EKS specific part in this flow. You do highlight that the eks annotation will be checked on SAs in the first step

>  then it would look up the service account resource in kube, see if there is an eks annotation

I suggest we do it without checking for the annotation, which will make this solution more generalizable. i.e: if a VM spec has a service account token mount of any type do the edits as suggested above. Not sure if this will work generally so if you have any info to suggest otherwise please let me know
What we can do instead is if the eks annotations are found on a service account add the AWS env vars by reading them from the virt-launcher pod spec through cloud init as you say. I still don't fully have an idea on when this check will take place but this is how i think it should go

Please let me know what you think

**Comment by Helen300** [comment]
> How might this look ? I envision something like this (in the vm spec)

> ```
>   volumes:
>   - name: service-account-1
>     serviceAccount:  # the webhook checks for this key in volumes
>       serviceAccountName: default
>   - name: service-account-2
>     serviceAccount: 
>       serviceAccountName: some-eks-sa
> ```

Yes, we would check for this in the VM spec to see if a service account is specified as volume on the VM. 

And yes, the webhook would need to add something like this. However, for the NOTE below, this filesystem device for the kube token part of the service account would've needed to be added already by the user who attached the service account as a volume in the first place. Thus, what needs to be added is actually the third filesystem device shown below. 

>       filesystems:
>       - name: service-account-1 
>         virtiofs: {}
>       - name: service-account-2 # SEE NOTE HERE
>         virtiofs: {}
>        - name: service-account-2-eks # SEE NOTE HERE, this is actually what the webhook needs to add
>           virtiofs: {}
> 


> I suggest we do it without checking for the annotation, which will make this solution more generalizable. 
> i.e: if a VM spec has a service account token mount of any type do the edits as suggested above. Not sure if this will work generally so if you have any info to suggest otherwise please let me know
> What we can do instead is if the eks annotations are found on a service account add the AWS env vars by reading them from the virt-launcher pod spec through cloud init as you say. I still don't fully have an idea on when this check will take place but this is how i think it should go

Reason why I think we shouldn't initially make the solution more generalizable is because we only know that the following is true for service accounts for EKS annotations. The path that we use for the virtiofs container to create the socket is tied to a path that we know which is specific to the eks service accounts, specifically this is `/var/run/secrets/eks.amazonaws.com/serviceaccount`. We don't know if other integrations with service accounts follow the same pattern. 

I'm still thinking about the cloudinit portion, because if the user themselves have injected cloudinit data to the VM already, then it may be difficult or maybe a little odd to try to merge that user data with the user data that we want to inject for mounting the virtiofs in the VM and also including the env variables...

**Comment by aerosouund** [comment]
Thanks for the clarification, one more question though. In this context how is `service-account-2-eks` different from `service-account-2`. In the example i show SA 1 is the kubernetes SA and SA 2 is the EKS SA. If this is the case would there still be a `service-account-2-eks` ? Highly appreciate your clarification here or if my understanding of SAs is lacking something.

```
- name: service-account-1 # SEE NOTE HERE - the user should've added this already for the kube token
    virtiofs: {}
  - name: service-account-2 # SEE NOTE HERE - the user should've added this already for the kube token
    virtiofs: {}
  - name: service-account-2-eks # SEE NOTE HERE, this is actually what the webhook needs to add
    virtiofs: {}
```

> The path that we use for the virtiofs container to create the socket is tied to a path that we know which is specific to the eks service accounts, specifically this is /var/run/secrets/eks.amazonaws.com/serviceaccount

Correct, my suggestion of generalization was based on the fact that any service account that integrates with anything will end up as a volume mounted on /var/run/secrets/something. If this is not the case then indeed we should focus on an AWS EKS solution at the current stage.

> I'm still thinking about the cloudinit portion, because if the user themselves have injected cloudinit data to the VM already, then it may be difficult or maybe a little odd to try to merge that user data with the user data that we want to inject for mounting the virtiofs in the VM and also including the env variables...

True, one way of doing this is by creating a configmap with a shell script that exports those vars, and then in the cloudinit just adding

```
source thatfile.sh
```
while we still would be merging something to the cloudinit but atleast its a single line. is there any other way that kubevirt supports to load env vars into a VM ?

**Comment by aqilbeig** [comment]
Thanks for picking this up. We are also struggling with the same. 

I don't think there would be two different service accounts as virt-launcher pod would be created with the same serviceAccount name mentioned in the VMspec using [this](https://kubevirt.io/user-guide/storage/disks_and_volumes/#as-a-filesystem_2)

e.g.

I do have the following in my VM spec:
```
              devices:
                filesystems:
                - name: serviceaccount-fs
                  virtiofs: {}
            volumes:
            - name: serviceaccount-fs
              serviceAccount:
                serviceAccountName: kubevirtpoc
```

and virt-launched pod has now both the default and eks token:

snippet of virt-launcher pod:
```
  serviceAccount: kubevirtpoc
  serviceAccountName: kubevirtpoc
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - emptyDir: {}
    name: virtiofs-containers
  - name: kube-api-access-r7qzj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
```

@Helen300 Could we mount the complete /var/run/secrets as a whole to VM as both the tokens reside in the same parent directory. Is is possible to modify the ServiceAccountSourceDir to `/var/run/secrets` so that VM could have all the token within this parent directory?

**Comment by aerosouund** [comment]
@aqilbeig 
> Is is possible to modify the ServiceAccountSourceDir to /var/run/secrets so that VM could have all the token within this parent directory?
yes thats a potential solution. If the entirety of `/var/run/secrets` is exported to the VM through virtiofs then it would work, however it neglects the AWS credentials env vars. we need them to be on the vm somehow and also it would leave a part that the user will need to specify manually. I.E what are the tokens mounted in `/var/run/secrets` and when to use each.. etc.

If this is ok we can go with that solution

**Comment by Helen300** [comment]
> @Helen300 Could we mount the complete /var/run/secrets as a whole to VM as both the tokens reside in 
> the same parent directory. Is is possible to modify the ServiceAccountSourceDir to `/var/run/secrets` so 
> that VM could have all the token within this parent directory?

@aqilbeig This was something I also considered initially, if we did this, it may be as simple as just changing a single line in kubevirt. However, I'm not sure if other members of the community would agree that this is the best solution. @alicefr what do you think? I know you mentioned that you would prefer an infrastructure extension to kubevirt (via webhooks/sidecars) rather than an API extension/change. Another reason why I think this might not be the best idea is that there could be other things written to `/var/run/secrets` that is not related to service account tokens and maybe we don't want to implicitly just mount into the VM. Do you know what `var/run/secrets` generally contains if not just service account tokens? Separately, same as what @aerosouund mentioned, this would still neglect the env variables. 

Re: @aerosouund

> Thanks for the clarification, one more question though. In this context how is service-account-2-eks different from service-account-2. In the example i show SA 1 is the kubernetes SA and SA 2 is the EKS SA. If this is the case would there still be a service-account-2-eks ? Highly appreciate your clarification here or if my understanding of SAs is lacking something.

Let me clarify this. 

For each of the service account volumes specified here, they correspond to a separate service account kube resource. With the current setup of service account volumes in kubevirt, each one of these needs a corresponding [virtiofs filesystem device see here ](https://kubevirt.io/user-guide/storage/disks_and_volumes/#as-a-filesystem_2). However, due to this hardcoded value in kubevirt
```
	// ServiceAccountSourceDir represents the location where the ServiceAccount token is attached to the pod
	ServiceAccountSourceDir = "/var/run/secrets/kubernetes.io/serviceaccount/"
```
The token that it mounts into the VM corresponding to that service account volume is just the token for the kube api. The EKS token is at a separate path. As such, the final spec should look something like this, and I'll note down which part the webhook needs to add exactly. 

```
   filesystems:
  # This mount maps to the regular-sa-without-eks-annotation kube service account token, volume: service-account-1
  - name: service-account-1
    virtiofs: {}
# This mount maps to the some-eks-annotated-sa service account token, volume: service-account-2
  - name: service-account-2
    virtiofs: {}
# The webhook needs to add this entry, which will correspond to the other virtiofs container that we need to inject into the virt launcher pod
  - name: service-account-2-eks
    virtiofs: {}
 # These volumes are specified by the writer of the VM spec
  volumes:
  - name: service-account-1
    serviceAccount:
      serviceAccountName: regular-sa-without-eks-annotation
  - name: service-account-2
    serviceAccount: 
      serviceAccountName: some-eks-annotated-sa
```


> Correct, my suggestion of generalization was based on the fact that any service account that integrates 
> with anything will end up as a volume mounted on /var/run/secrets/something. If this is not the case then indeed we should focus on an AWS EKS solution at the current stage.
I think it makes sense to me to impose that the webhook integrates with anything that follows this pattern /var/run/secrets/something. For just an initial solution, i still think it would be good to focus on the EKS. 

I might be able to finish the rest of the code for my suggested implementation this week and figure out the env variables issue just to check the idea works end to end, hope you don't mind me doing that @aerosouund since you asked if you could work on it!
