### ISSUE TITLE
Controller metrics are broken without guest agent

### ISSUE THREAD

**Issue by crabique** [kubevirt/kubevirt#13346]
**What happened**:
#12802 introduced a new metric that relies on the guest agent to fetch the IP addresses for each interface of a VMI, relying on the IP address to be the unique label value that sets the time-series apart.

Unfortunately, when any VMI has multiple interfaces but does not have a guest agent installed, the `address` label of the resulting metric is `""` for all of them, which is not a unique label. 

This causes the metrics engine to fail due to time-series collision: leader controller pod is returning this on `/metrics` endpoint with HTTP response code 500:
```
An error has occurred while serving metrics:

1 error(s) occurred:

* collected metric "kubevirt_vmi_status_addresses" { label:{name:"address" value:""} label:{name:"name" value:"<redacted>"} label:{name:"namespace" value:"<redacted>"} label:{name:"node" value:"<redacted>"} label:{name:"type" value:"InternalIP"} gauge:{value:1}} was collected before with the same name and label values
```

**What you expected to happen**:
The metrics are served properly.

**How to reproduce it (as minimally and precisely as possible)**:
- create a VM with 2 interfaces and not install/disable the guest agent
- port-forward the controller pods and check the `/metrics` endpoint on both of them

**Additional context**:
According to docs, the agent is optional, so having the agent installed should not be a requirement for having properly working controller metrics. Current behavior causes the `kubevirt_virt_controller_ready` metric to not include the broken controller and triggers the [LowVirtControllersCount](http://kubevirt.io/monitoring/runbooks/LowVirtControllersCount.html) alert.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.4.0

**Comment by crabique** [comment]
> @crabique can you share more details about the VM network configurations?

Sure, the VMs use Multus networks and the affected VMs look like this (only the relevant parts here):
```yaml
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
          - name: networkA
            bridge: {}
          - name: networkB
            bridge: {}
      networks:
      - name: networkA
        multus:
          networkName: cluster/networkA
      - name: networkB
        multus:
          networkName: cluster/networkB
```

Both networks are configured with `"ipam": {}` in `NetworkAttachmentDefinition.spec.config`
