### ISSUE TITLE
After live migration, `guest-console-log` fails, but VM runs well

### ISSUE THREAD

**Issue by Yu-Jack** [kubevirt/kubevirt#13466]
**What happened**:
In Harvester, when we upgrade the Harvester, we'll live-migrate VMs to another node. During this process, we observed an issue which the `guest-console-log` fails, but the VM runs well.

This was container status when we were trying to reproduce this issue with live migration. We also find the `virt-tail` [returns timeout in 20 seconds](https://github.com/kubevirt/kubevirt/blob/d89e90569461b119a7a5d3a96027e63c4c39b0ee/cmd/virt-tail/main.go#L142) if the file doesn't exist. Based on the container status, we know the `guest-console-log` waited for 20 seconds. However, VM runs well.

```yaml
containerStatuses:
- containerID: containerd://f654f08fbaacf40e404a8b049a3190387184a5fdd89fb9caa7796558b60fc425
  name: compute
  ready: true
  restartCount: 0
  started: true
  state:
    running:
      startedAt: "2024-12-06T06:46:56Z"
- containerID: containerd://fa5b7ca1d47d16837a4025a60f180f844fb6d455ca4f8ccfd3c2b4f211549767
  name: guest-console-log
  ready: false
  restartCount: 0
  started: false
  state:
    terminated:
      containerID: containerd://fa5b7ca1d47d16837a4025a60f180f844fb6d455ca4f8ccfd3c2b4f211549767
      exitCode: 1
      finishedAt: "2024-12-06T06:47:17Z"
      reason: Error
      startedAt: "2024-12-06T06:46:56Z"
```

**What you expected to happen**:
We expect the `guest-console-log` should also run well after live migration. Maybe we could add some retry mechanisms?

**How to reproduce it (as minimally and precisely as possible)**:
It might not be 100% to reproduce it, but there is still a change that it could happen.

1. Start a VM with hotplug volume
2. **Run cpu-intensive task, such as stress test.**
3. Live-migrate  the VM to another node

**Additional context**:
Related Issue: https://github.com/harvester/harvester/issues/7068

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1 or 1.2.2
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: Ubuntu Cloud Image
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by Yu-Jack** [comment]
But, there is a different situation.

When I was trying to migrate the VM, the compute container in new pod was stuck for a while. In this case, guest-console-log failed either. I think It's expected because the compute container wasn't ready.

![image](https://github.com/user-attachments/assets/75be74f5-925a-4035-baa2-25d8e9c27a1b)

**Comment by Yu-Jack** [comment]
I did some tests and passed the timeout to virt-tail.

The virt-launcher-monitor took 21 seconds to execute `PreStartHook`. 

![image](https://github.com/user-attachments/assets/7610201c-2f8f-4f01-a9ad-8799620b8af8)

This is my pod spec. 
``` yaml
containers:

- command:
  - /usr/bin/virt-launcher-monitor
  - --qemu-timeout
  - 289s
  image: jk82421/virt-launcher:v1.2.2.1

- args:
    - --logfile
    - /var/run/kubevirt-private/78d366fa-5251-459f-9cad-ae4be65fad35/virt-serial0-log
    - --socket-timeout
    - 289s
  command:
    - /usr/bin/virt-tail
  image: jk82421/virt-launcher:v1.2.2.1
```

It should raise a timeout error in the guest-console-log with original image version. It seems the result is good with my built image version.

```yaml
containerStatuses:
- containerID: containerd://b06391c9be347795f07a749a8cf146568a0f9acd8ad0801d98f7eed5e604336c
  image: docker.io/jk82421/virt-launcher:v1.2.2.1
  imageID: docker.io/jk82421/virt-launcher@sha256:01f1f7f88f9689d2485adba555bd05a6fcee43c0f27a8a53e64a1cb37064bbdf
  lastState: {}
  name: compute
  ready: true
  restartCount: 0
  started: true
  state:
    running:
      startedAt: "2024-12-13T07:02:05Z"
- containerID: containerd://d471543a47f6e2087aa88019f5da92e474d219d2a7613864b638e2b1bdb49dfc
  image: docker.io/jk82421/virt-launcher:v1.2.2.1
  imageID: docker.io/jk82421/virt-launcher@sha256:01f1f7f88f9689d2485adba555bd05a6fcee43c0f27a8a53e64a1cb37064bbdf
  lastState: {}
  name: guest-console-log
  ready: true
  restartCount: 0
  started: true
  state:
    running:
      startedAt: "2024-12-13T07:02:05Z"
```
