### ISSUE TITLE
Example VMs/VMIs to use instance types

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#13511]
Today, all of the example VMs/VMIs under `./examples` are being defined by manually populating the spec.

This encourages users to do the same instead of using instance types in order to define them. Using instance types in the examples will help users understand how to define VMs more easily and use the newer recommended approach for doing so.

**Describe the solution you'd like**:
Use instance types for examples VMs/VMIs.
I think that keeping one or two examples with the current approach is also valuable.

**Comment by iholder101** [comment]
/good-first-issue

@lyarwood do you still plan working on this?

**Comment by Ashlok2003** [comment]
I'm still trying to understand things properly, so I just want to confirm before proceeding. Should all files inside the ./examples directory be updated in this manner?

```
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: small-instance
spec:
  cpu:
    guest: 1
  memory:
    guest: 128Mi
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: alpine-preference
spec:
  devices:
    preferredDiskBus: virtio
  firmware:
    preferredUseEfi: true
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  instancetype:
    name: small-instance
    kind: VirtualMachineInstancetype
  preference:
    name: alpine-preference
    kind: VirtualMachinePreference
  dataVolumeTemplates:
  - metadata:
     // Rest of the `configurations`
```
