### ISSUE TITLE
KubeClientCertificateExpiration is constantly triggered

### ISSUE THREAD

**Issue by davralin** [kubevirt/kubevirt#13548]
**What happened**:
With kube-prom-stack pre-installed in my cluster, I keep getting flapping  alerts about a ClientCertificate expiring within the next 24 hours.

I have tracked the issue back to when I deploy something with `kind: KubeVirt`.

**What you expected to happen**:
Not getting the alerts
OR
be able to configure/override a value that mitigates it.

**How to reproduce it (as minimally and precisely as possible)**:
Install kube-prom-stack, have the default alerts enabled.

Add something with `kind: KubeVirt`, wait for alerts to roll in.

**Additional context**:
The rule in question is in `kube-prom-kubernetes-system-apiserver`.
The actuall rule triggered is:
````yaml
  - name: kubernetes-system-apiserver
    rules:
    - alert: KubeClientCertificateExpiration
      annotations:
        description: A client certificate used to authenticate to kubernetes apiserver
          is expiring in less than 7.0 days on cluster {{ $labels.cluster }}.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration
        summary: Client certificate is about to expire.
      expr: |-
        histogram_quantile(0.01, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
        and
        on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
      for: 5m
      labels:
        severity: warning
    - alert: KubeClientCertificateExpiration
      annotations:
        description: A client certificate used to authenticate to kubernetes apiserver
          is expiring in less than 24.0 hours on cluster {{ $labels.cluster }}.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration
        summary: Client certificate is about to expire.
      expr: |-
        histogram_quantile(0.01, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
        and
        on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
      for: 5m
      labels:
        severity: critical
````
Note that the warning-alert is never triggered.

I am assuming there is some sort of short-lived certificate used here, but I can't find it anywhere.

After setting:
````yaml
        spec:
          certificateRotateStrategy:
            selfSigned:
              ca:
                duration: 168h
                renewBefore: 48h
              server:
                duration: 72h
                renewBefore: 48h
````
All the secrets in kube-virt namespace have the correct `kubevirt.io/duration` set.
I have also checked tls.cert from all the services, they are all "longer-lived"

Very open to having set the wrong values here, I had to find a hint of those values from a non-related issue on github, and then going through the CRD's for information - some place where this information is available would be very welcome!

**Environment**:
- KubeVirt version (use `virtctl version`): v1.4.0
- Kubernetes version (use `kubectl version`): v1.32.0 (but it was also an issue with v1.31.4)
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Dell OptiPlex 3090
- OS (e.g. from /etc/os-release): Talos 1.8
- Kernel (e.g. `uname -a`): 6.6.x
- Install tools: Flux
- Others: N/A

[Here is my kube-prom-stack config](https://github.com/davralin/cluster-ops/blob/main/kubernetes/monitoring/homeprod/kube-prometheus-stack/helm-release.yaml)
[Here is my kube-virt-config](https://github.com/davralin/cluster-ops/blob/main/kubernetes/apps/kubevirt/helm-release-kubevirt.yaml)

**Comment by enp0s3** [comment]
@davralin Hi! Do you still consider this issue open?

**Comment by davralin** [comment]
> @davralin Hi! Do you still consider this issue open?

Not sure if you mean something else than what I mean.

The issue is still open, there's no workarounds, and I have no idea if it's a config issue on my end, or if there's a bug somewhere here.

**Comment by enp0s3** [comment]
@davralin Sorry for misunderstanding, I saw that you liked the response of dosubot, therefore I assumed it addressed your issue

**Comment by davralin** [comment]
> @davralin Sorry for misunderstanding, I saw that you liked the response of dosubot, therefore I assumed it addressed your issue

Ahh yes!

No, it was more of an acknowledgment. It was actually a good response, just didn't help me  :)

**Comment by NATICH** [comment]
Can i edit the severity of the alert to be warning ?
i didnt find where it configured in my cluster 
k8s v1.25.1
prometheus 2.41.0

**Comment by enp0s3** [comment]
@davralin Hi. I was trying to reproduce your issue, but w/o success.
Please correct me if I am wrong, but you are saying that:
```
        spec:
          certificateRotateStrategy:
            selfSigned:
              ca:
                duration: 168h
                renewBefore: 48h
              server:
                duration: 72h
                renewBefore: 48h
```
Actually silence the `KubeClientCertificateExpiration` alert?
