### ISSUE TITLE
Failed to connect VM

### ISSUE THREAD

**Issue by LeoHsu0705** [kubevirt/kubevirt#13593]
My VM expose with kubernetes service type LoadBalancer, it distribute a external-ip for me.
the GKE firewall already allow the port 3389 and 27017.
but i still can't connect the vm with this external-ip. also the virtvnc can't search my VM
Why? what should i supposed to do?

![截圖 2024-12-24 下午3 29 55](https://github.com/user-attachments/assets/daaa0a11-cc2d-42a7-9023-cdd9aa006bc9)
![截圖 2024-12-24 下午2 49 45](https://github.com/user-attachments/assets/8635285b-eb92-46d0-954e-26378dc4cd10)
![截圖 2024-12-24 下午3 10 03](https://github.com/user-attachments/assets/6bbf2e04-2d7a-418f-a6c7-8cba8d9c7f67)
![截圖 2024-12-24 下午3 16 49](https://github.com/user-attachments/assets/0ea264d6-1d04-40dc-bcaa-2a59fb3e0004)

this is my yaml.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-test
  namespace: kubevirt
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-test
    spec:
      domain:
        cpu:
          cores: 4
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
        devices:
          disks:
          - cdrom:
              bus: sata
            name: windows
            bootOrder: 1
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 2
          - cdrom:
              bus: sata
            name: virtiocontainer
            bootOrder: 3
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
            ports:
              - port: 3389
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: windows
        persistentVolumeClaim:
          claimName: windows-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10-drive
      - name: virtiocontainer
        containerDisk:
          image: kubevirt/virtio-container-disk
---
apiVersion: v1
kind: Service
metadata:
  name: win10-test
  namespace: kubevirt
spec:
  type: LoadBalancer
  loadBalancerIP: 
  externalTrafficPolicy: Cluster
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 3389
  selector:
    kubevirt.io/domain: win10-test
```
    
Environment:
System: MacOS
KubeVirt version (use virtctl version): v1.1.0
KubeVirt-CR version : v1.1.0
Kubernetes version (use kubectl version): v1.30.3
CDI version: v1.61.0
Cloud provider or hardware configuration: GCP (Google Cloud Platform)
