### ISSUE TITLE
Hotpluging cpu not working as expected

### ISSUE THREAD

**Issue by naftalyava** [kubevirt/kubevirt#13608]
**What happened**:
1. Created a vm. [1 socket, 1 core, 1 thread]
2. Edited the vm by increasing sockets to 2.
3. Witnessed VM live migrated to another node.
4. Logged in into the vm but both /proc/cpuinfo and lscpu show only 1 socket.

**What you expected to happen**:
I expected to see 2 sockets inside my vm.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

VM definition:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm-1
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: fedora-vm-1
    spec:
      domain:
        cpu:
          cores: 1
          threads: 1
          sockets: 1
          maxSockets: 4
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            macAddress: de:ad:be:ef:00:01
        resources:
          requests:
            memory: 2048M    # Increased memory for Fedora
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:38
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              user: fedora
```

Kubevirt config:
```
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - VMLiveUpdateFeatures
      - LiveMigration
      - HotplugNICs
      - Snapshot
    vmRolloutStrategy: LiveUpdate
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy:
    workloadUpdateMethods:
    - LiveMigrate
```

After I edit teh sockets number:
```
naftaly@vm0:~$ k get vmi
NAME          AGE   PHASE     IP           NODENAME   READY
fedora-vm-1   78s   Running   10.0.3.194   vm4        True
naftaly@vm0:~$ k get vmi
NAME          AGE   PHASE     IP           NODENAME   READY
fedora-vm-1   79s   Running   10.0.1.223   vm1        True
```

describe vm:

```
naftaly@vm0:~$ k describe vm fedora-vm-1
Name:         fedora-vm-1
Namespace:    kube-system
Labels:       <none>
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1
API Version:  kubevirt.io/v1
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2024-12-27T20:05:25Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
  Generation:        2
  Resource Version:  214688
  UID:               34bae842-75a4-463f-b0eb-c1b036fcc5b6
Spec:
  Run Strategy:  Always
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt.io/domain:  fedora-vm-1
        kubevirt.io/size:    small
    Spec:
      Architecture:  amd64
      Domain:
        Cpu:
          Cores:        1
          Max Sockets:  4
          Sockets:      2
          Threads:      1
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   containerdisk
            Disk:
              Bus:  virtio
            Name:   cloudinitdisk
          Interfaces:
            Mac Address:  de:ad:be:ef:00:01
            Masquerade:
            Name:  default
        Machine:
          Type:  q35
        Resources:
          Requests:
            Memory:  2048M
      Networks:
        Name:  default
        Pod:
      Volumes:
        Container Disk:
          Image:  quay.io/containerdisks/fedora:38
        Name:     containerdisk
        Cloud Init No Cloud:
          User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
ssh_pwauth: True
user: fedora

        Name:  cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2024-12-27T20:06:44Z
    Status:                True
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  StorageLiveMigratable
    Last Probe Time:       2024-12-27T20:05:43Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  AgentConnected
  Created:                 true
  Desired Generation:      2
  Observed Generation:     1
  Printable Status:        Running
  Ready:                   true
  Run Strategy:            Always
  Volume Snapshot Statuses:
    Enabled:  false
    Name:     containerdisk
    Reason:   Snapshot is not supported for this volumeSource type [containerdisk]
    Enabled:  false
    Name:     cloudinitdisk
    Reason:   Snapshot is not supported for this volumeSource type [cloudinitdisk]
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  2m6s  virtualmachine-controller  Started the virtual machine by creating the new virtual machine instance fedora-vm-1
naftaly@vm0:~$ 
```

Something intresting from the virt-launcher pod:

```
<vcpus>
    <vcpu id="0" enabled="yes" hotpluggable="no" order="1"></vcpu>
    <vcpu id="1" enabled="no" hotpluggable="yes"></vcpu>
    <vcpu id="2" enabled="no" hotpluggable="yes"></vcpu>
    <vcpu id="3" enabled="no" hotpluggable="yes"></vcpu>
</vcpus>
```

dmesg inside the vm:

```
[   17.109016] APIC: NR_CPUS/possible_cpus limit of 1 reached. Processor 1/0x1 ignored.
[   17.111501] ACPI: Unable to map lapic to logical cpu number
[   17.114709] acpi LNXCPU:01: Enumeration failure
```

kubevirt version 1.4.0

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.4.0
- Kubernetes version (use `kubectl version`): v1.32.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: GCE with nested virtualization enabled
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): 
  host: Linux vm0 6.8.0-1020-gcp #22~22.04.1-Ubuntu SMP Mon Dec  9 20:42:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
  guest: Linux fedora-vm-1 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A
