### ISSUE TITLE
Kubevirt doesn't work on a system with selinux in disabled or permissive mode.

### ISSUE THREAD

**Issue by nahsi** [kubevirt/kubevirt#13607]
I'm using talos version 1.9.0 where selinux is disabled but `/sys/fs/selinux` exists in preparation for enabling selinux in future releases.

On that system kubevirt cannot start vm with errors like
```
❯ kubectl -n kubevirt logs virt-handler-2fttw | grep selinux
Defaulted container "virt-handler" out of: virt-handler, virt-launcher (init)
Error: failed to get selinux label for file /proc/self/fd/4: error reading fgetxattr: no data available
  virt-chroot selinux relabel [flags]
virt-chroot selinux relabel <new-label> <file-path>
failed to get selinux label for file /proc/self/fd/4: error reading fgetxattr: no data available
{"component":"virt-handler","level":"error","msg":"Relabeling a file faild, continuing since selinux is permissive.","pos":"labels.go:186","reason":"error relabeling file root: /, relative: /dev/net/tun with label system_u:object_r:container_file_t:s0. Reason: exit status 1","timestamp":"2024-12-25T09:43:54.899733Z"}
Error: failed to get selinux label for file /proc/self/fd/3: error reading fgetxattr: no data available
  virt-chroot selinux relabel [flags]
virt-chroot selinux relabel <new-label> <file-path>
failed to get selinux label for file /proc/self/fd/3: error reading fgetxattr: no data available
{"component":"virt-handler","level":"error","msg":"Relabeling a file faild, continuing since selinux is permissive.","pos":"labels.go:186","reason":"error relabeling file root: /, relative: /dev/null with label system_u:object_r:container_file_t:s0. Reason: exit status 1","timestamp":"2024-12-25T09:43:54.901980Z"}
{"component":"virt-handler","level":"error","msg":"failed to configure pod network","pos":"netpod.go:200","reason":"could not retrieve pid 20913 selinux label: getxattr /proc/20913/attr/current: operation not supported","timestamp":"2024-12-25T09:54:16.256900Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"0000000000000000000000000000000000000000000000000000000000000011","namespace":"0xb994940f0a9b6b8d32b25d57b6ef7c49c00316ea","pos":"vm.go:2146","reason":"failed to configure vmi network: setup failed, err: Critical network error: could not retrieve pid 20913 selinux label: getxattr /proc/20913/attr/current: operation not supported","timestamp":"2024-12-25T09:54:16.256983Z","uid":"6cc6ea97-cbc9-43c4-8fc3-7117cf6766b6"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance 0xb994940f0a9b6b8d32b25d57b6ef7c49c00316ea/0000000000000000000000000000000000000000000000000000000000000011","pos":"vm.go:1807","reason":"failed to configure vmi network: setup failed, err: Critical network error: could not retrieve pid 20913 selinux label: getxattr /proc/20913/attr/current: operation not supported","timestamp":"2024-12-25T09:54:16.268489Z"}
{"component":"virt-handler","level":"error","msg":"failed to configure pod network","pos":"netpod.go:200","reason":"could not retrieve pid 21966 selinux label: getxattr /proc/21966/attr/current: operation not supported","timestamp":"2024-12-25T09:54:29.230349Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"0000000000000000000000000000000000000000000000000000000000000011","namespace":"0xb994940f0a9b6b8d32b25d57b6ef7c49c00316ea","pos":"vm.go:2146","reason":"failed to configure vmi network: setup failed, err: Critical network error: could not retrieve pid 21966 selinux label: getxattr /proc/21966/attr/current: operation not supported","timestamp":"2024-12-25T09:54:29.230451Z","uid":"f89f069d-b309-4b6a-8574-ecf08f3ea024"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance 0xb994940f0a9b6b8d32b25d57b6ef7c49c00316ea/0000000000000000000000000000000000000000000000000000000000000011","pos":"vm.go:1807","reason":"failed to configure vmi network: setup failed, err: Critical network error: could not retrieve pid 21966 selinux label: getxattr /proc/21966/attr/current: operation not supported","timestamp":"2024-12-25T09:54:29.240911Z"}
```
It looks like no matter what the selinux state is kubevirt only checks the existence of `/sys/fs/selinux` and if it exists it assumes selinux is enabled and enforced.

**What you expected to happen**:
If selinux is disabled or set to permissive mode kubevirt shouldn't do anything related to selinux

**How to reproduce it (as minimally and precisely as possible)**:
Install talos linux version 1.9.0 https://www.talos.dev/v1.9/talos-guides/install/ , run kubevirt and run vm.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.40.0
- Kubernetes version (use `kubectl version`): 1.32.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): talos 1.9.0
- Kernel (e.g. `uname -a`):  6.12.5
- Install tools: N/A
- Others: N/A

**Comment by iholder101** [comment]
Thanks @nahsi!

The error seems to come from here:
https://github.com/kubevirt/kubevirt/blob/a724aff0139167ee3997d55ee90cbbb4439aafcd/cmd/virt-chroot/selinux.go#L83

However, before the command is being run by virt-handler, we check for SELinux existence here:
https://github.com/kubevirt/kubevirt/blob/a724aff0139167ee3997d55ee90cbbb4439aafcd/cmd/virt-handler/virt-handler.go#L389

And we do that by checking if SELinux is disabled:
https://github.com/kubevirt/kubevirt/blob/a724aff0139167ee3997d55ee90cbbb4439aafcd/pkg/virt-handler/selinux/labels.go#L67

@nahsi is SELinux disabled or on a Permissive mode on your system?

**Comment by nahsi** [comment]
I think this particular log comes from disabled selinux.
I also tried with selinux set to permissive and got same or similar errors

**Comment by iholder101** [comment]
> I think this particular log comes from disabled (selinux=0 in kernel cmd) selinux. I also tried with selinux set to permissive and got same or similar errors

I'd appreciate if you can check the following to understand why virt-handler tries to perform this re-labeling. To do that, you can exec into virt-handler and execute the virt-chroot command the code above is running:
```
> k exec -it -n kubevirt virt-handler-btpfm -- /bin/sh -c "virt-chroot --mount /proc/1/ns/mnt selinux getenforce"
enforcing
```

**Comment by arthurkay** [comment]
@iholder101 I am also facing the same challenge and a check on the SELinux shows that it is in permissive mode according to your suggested method using the following command:

> kubectl exec -it -n kubevirt virt-handler-hngta -- /bin/sh -c "virt-chroot --mount /proc/1/ns/mnt selinux getenforce"
permissive

**Comment by kvaps** [comment]
Hey, I just reported the same issue to Talos Linux

https://github.com/siderolabs/talos/issues/10083#issuecomment-2568801695

**Comment by kvaps** [comment]
Okay I found workaround:


```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disable-selinux
  namespace: cozy-kubevirt
  labels:
    app: disable-selinux
spec:
  selector:
    matchLabels:
      app: disable-selinux
  template:
    metadata:
      labels:
        app: disable-selinux
    spec:
      containers:
      - command:
        - sh
        - -exc
        - test -f /sys/fs/selinux/enforce && mount -t tmpfs tmpfs /host/sys/fs/selinux || sleep infinity
        image: docker.io/library/alpine
        name: mount
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          mountPropagation: Bidirectional
          name: host-root
      hostIPC: true
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /
        name: host-root
```
