### ISSUE TITLE
lastTransitionTime not set on conditions of VirtualMachine

### ISSUE THREAD

**Issue by seifane** [kubevirt/kubevirt#13658]
**What happened**:
Some (maybe all) conditions do not have a last transition time set. This seems to go against the schema that requires this field to always be set.

**What you expected to happen**:
`lastTransitionTime` on `VirtualMachines` to always be set.

**How to reproduce it (as minimally and precisely as possible)**:
- Fresh install of KubeVirt.
- `kubectl apply` a `VirtualMachine`
- `kubectl virt start vm`
- `kubectl get vm -o json`

The conditions will contain null `lastTransitionTime`
```
{
  "apiVersion": "kubevirt.io/v1",
  "kind": "VirtualMachine",
  "metadata": {...},
  "spec": {...},
  "status": {
    "conditions": [
      {
        "lastProbeTime": null,
        "lastTransitionTime": "2025-01-08T15:40:25Z",
        "status": "True",
        "type": "Ready"
      },
      {
        "lastProbeTime": null,
        "lastTransitionTime": null,
        "status": "True",
        "type": "LiveMigratable"
      },
      {
        "lastProbeTime": null,
        "lastTransitionTime": null,
        "status": "True",
        "type": "StorageLiveMigratable"
      }
    ],
    ...
  }
}

```

**Additional context**:
See definitions for `io.k8s.apimachinery.pkg.apis.meta.v1.Condition`.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.4.0
- Kubernetes version (use `kubectl version`): 1.31.2
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Talos
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
