### ISSUE TITLE
allow for multiple interfaces connected to the same network

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#1366]
/kind enhancement

Once this: https://github.com/kubevirt/kubevirt/pull/1342 is delivered, it should be possible to expose a network from the host into the VM. 
As noted there, the underlying device plugin, as well as the API defined with kubevirt, allows for multiple interfaces on the pod, to be connected to the same network. Hence, it should be possible to connect multiple interfaces from the VM into the ones on the pod (currently only one of the is selected, and exposed to the VM).
Would suggest the following addition to the VMI yaml:
```yaml
networks:
  - name: red 
    resource:
      resourceName: bridge.network.kubevirt.io/red
      resourceCount: 3
```

One of the usecases for that, would be running a virtual router inside kubevirt. The router needs multiple interfaces on the machine it is running on, and will manage vlans on them.
On the other end, its will be connected to a trunk interface on the host.

**Comment by rmohr** [comment]
I am not sure if adding `resourceCount: 3` there. You would then have to reference the same `networks` entry three times from different interfaces. I think the correct way for this would be:

```yaml
networks:
  - name: red1
    resource:
      resourceName: bridge.network.kubevirt.io/red
  - name: red2
    resource:
      resourceName: bridge.network.kubevirt.io/red
  - name: red3
    resource:
      resourceName: bridge.network.kubevirt.io/red
```
