### ISSUE TITLE
annotation "kubevirt.io/created-by" for VMI pod is not readable

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#1369]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
VMI's uid is used in the pod annotation, at the first look I don't know what it is, after some time I figure out it's VMI's uid.

```
# oc get pod virt-launcher-fedora-x49wl -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubevirt.io/created-by: 4f29741d-8fd3-11e8-ac3d-28d24493810c
    kubevirt.io/owned-by: virt-handler
    openshift.io/scc: privileged
  creationTimestamp: 2018-07-25T06:23:56Z
  generateName: virt-launcher-fedora-

```
**What you expected to happen**:
uid is not clear enough to user, how about to use VMI's domain?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by rmohr** [comment]
Hm, they are only meant for controller itself. In the past k8s did the same way. Now controllerRefs are used. I think we will do the same. I can't remember right now why I postponed that on the last refactoring round. These annotations will completely go away.

You will then see something like this instead:

```yaml
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineInstance
    name: fedora-x49wl
    uid: de3f0a39-8fef-11e8-bd33-525500d15501
```
