### ISSUE TITLE
Whereabouts & migration

### ISSUE THREAD

**Issue by kfox1111** [kubevirt/kubevirt#13709]
**What happened**:
Have a multus network using whereabouts. Things seemed to be working well, until I live migrated a vm, then launched a new vm.

Before launching the new vm, I could see the migrated vm on the network. It had the expected ip.

On launching the new vm, it also got assigned the migrated vm's ip.

Doing a describe on the migrated vm's vmi showed it having a different whereabouts ip. same in the whereabouts ip.

So, during migration it seems the ip is preserved in the vm properly, but the new pod gets a new ip assigned to it and the old one is dropped, allowing it to be reassigned.

**What you expected to happen**:
Migration would still reserve the ip so other vms wont pick it up.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a network via whereabouts. launch a vm, migrate it, then add another vm. both will have the same ip

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.0
- Kubernetes version (use `kubectl version`): v1.32.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by kfox1111** [comment]
Connectivity was preserved, until the new vm got the same ip and disrupted it.

```
          interfaces:
          - name: default
            masquerade: {}
          - name: home
            bridge: {}
```

```
      networks:
      - name: default
        pod: {}
      - name: home
        multus:
          networkName: home
```

------


So, whats the recommended way of keeping ip's consistent on a vm with multus? Is there any way to use a pool of ip's to do it? or do you have to make a networkattachment for each vm with the static ip specified?
