### ISSUE TITLE
Admission controller not checking for non existing PVC claims

### ISSUE THREAD

**Issue by grafuls** [kubevirt/kubevirt#1370]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Admission controller webhook not checking for missing PVC when creating VMI with non existing claim.

**What you expected to happen**:
Tried creating a VMI with a definition for a pvc claim that was not yet created.
Given that the admission controller was enabled, I was expecting to get validation error for the non existing PVC claim but didn't.

**How to reproduce it (as minimally and precisely as possible)**:
Try creating a VMI with a definition for a non existing PVC claim.

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-10T22:32:34Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rmohr** [comment]
@grafuls thanks for the report.

> Tried creating a VMI with a definition for a pvc claim that was not yet created.
> Given that the admission controller was enabled, I was expecting to get validation error for the non existing PVC claim but didn't.

You should see on the vmi object itself something like this:

```yaml
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-07-25T09:41:48Z
      message: persistentvolumeclaim "disk-alpine1" not found
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Scheduling
```

if you type `kubectl get vmi myvmi -o yaml`.

That is the intended behavour. Since k8s is declarative every valid object can be posted. If objects it depends on already exist does not matter since they could appear anytime. So as soon as you create the PVC, the vm start will just continue.

Note that you can also see in the event log that it can't start:

```
LAST SEEN   FIRST SEEN   COUNT     NAME                                           KIND                     SUBOBJECT   TYPE      REASON                    SOURCE                        MESSAGE
26s         3m           14        virt-launcher-vmi-pvc-5snm4.1544934776b121f4   Pod                                  Warning   FailedScheduling          default-scheduler             persistentvolumeclaim "disk-alpine1" not found
```

if you type `kubectl get events`.
