### ISSUE TITLE
startupProbe support

### ISSUE THREAD

**Issue by kfox1111** [kubevirt/kubevirt#13734]
**Is your feature request related to a problem? Please describe**:
You can specify livenessProbes and readynessProbes in a VMI but not startupProbes.

**Describe the solution you'd like**:
The ability to also specify startupProbes

**Comment by shankeleven** [comment]
I'd be happy to work on this

**Comment by kfox1111** [comment]
I dont think it is much different then regular checks implementation wise?

It just suppresses the actions of liveness/readyness checks while the startupProbe is incomplete:
https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/#startup-probe

With just readyness/liveness, often you have to have loose tests/timing to make sure it covers the time it takes for the containers to startup properly. This is especially true of vms that may take much longer to start. Startup probes let you have readyness/liveness probes that are much looser defined that prevent tight readyness/liveness probes that fail too fast from affecting things during startup.

**Comment by iholder101** [comment]
Thank you @kfox1111! This is an interesting idea.

So IIUC the need is to know when the guest had booted, and right now there's no probe to indicate that?
Is there a reason you advocate specifically for a probe? I think you can know when the guest is running via the `GuestNotRunning` VMI condition:

```yaml
  status:
    activePods:
      0a0513d7-0359-49f4-86e6-5fc4b5f8a1c4: node02
    conditions:
    - lastProbeTime: "2025-02-05T09:31:38Z"
      lastTransitionTime: "2025-02-05T09:31:38Z"
      message: Guest VM is not reported as running
      reason: GuestNotRunning
      status: "False"
      type: Ready
```
