### ISSUE TITLE
Watchdog device Diag288 support for s390x based VM

### ISSUE THREAD

**Issue by HarshithaMS005** [kubevirt/kubevirt#13826]
**What happened**:
Currently watchdog with I6300ESB is supported for x86, for s390x I6300ESB is not supported watch dog device it is failing with below error while vm creation:
> server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: QEMU unexpectedly closed the monitor (vm='default_rhel-8-scarlet-walrus-70'): 2025-01-31T07:57:04.087004Z qemu-kvm: -device {\"driver\":\"i6300esb\",\"id\":\"ua-i6300esb-watchdog\",\"bus\":\"pci.0\",\"addr\":\"0x1\"}: 'i6300esb' is not a valid device model name')"

**What you expected to happen**:
As the watchdog device model I6300ESB is not supported for s390x, we need to add s390x supported watch dog device ie., Diag288 device model.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a s390x based VM with below yaml configuration. This config tries to create a Diag288 watchdog device on a VM with the poweroff action and this is expected to expose the device as /dev/watchdog inside the VM. But as Diag288 isn't a supported device on kubevirt, this doesn't work.

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-alpine
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-alpine
    spec:
      domain:
        devices:
          watchdog:
            name: diag288-watchdog
            diag288:
              action: "poweroff"
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/alpine-container-disk-demo:20241001_0a74910ea-s390x
        name: containerdisk
```
