### ISSUE TITLE
CI: Testing Kubevirt with supported Istio version

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#13832]
As of today, we test Kubevirt & Istio integration on CI using Istio v1.15.0, which is ancient version that is not supported anymore or tested with k8s versions Kubevirt supports.

In addition,the istio version CI runs blocks development that utilize newer k8s features in k8s version Kubevirt supports. For example: https://github.com/kubevirt/kubevirt/pull/13422

CI should use supported Istio version to unblock development (https://github.com/kubevirt/kubevirt/pull/13422) and  have proper verification on CI.

**Comment by ormergi** [comment]
Posting here for visibility:
 
Hi, I managed to make istio-1.24 work on kubevirtci cluster, and verified istio tests are passing.
Including on kubevirt that is build with https://github.com/kubevirt/kubevirt/pull/13422.

While troubleshooting the issues with 1.24 on kubevirtci, I saw istio-cni is not deployed as privileged , result VM creation failures.The privileged change is introduced in 1.24.
Istio 1.23 should work as expected, I suggest using this version.

In addition, IstioOperator API has been changed, see bellow config that worked for me:

kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    global:
      jwtPolicy: first-party-jwt
    cni:
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      privileged: true
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug
    pilot:
      cni:
        enabled: true
        provider: "multus"
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni

The missing configuration are:

    spec.values.pilot.cni
    This is a new API for triggering CNI deployment.
    The filed provider=multus acts like the known chained=false option (maybe in can be removed, need to verify).
    sidecarInjectorWebhook
    On istio >= 1.19, istio will append 'default/istio-cni' to the pod's k8s.v1.cni.cncf.io/networks is exist. Result in VMs failures.
    This cant work for kubevirtci env because we do not create the istio-cni NAD in the default namespace, but at the test namespace.
    In general it seems wrong because it means all pods in the cluster can connect to the mesh, becasuse all pods can connect to a NAD resied in default namespaces, no isolation allowed.

Related Istio issues
https://github.com/istio/istio/issues/54820
https://github.com/istio/istio/issues/54815

**Comment by ormergi** [comment]
The following config works with Istio 1.24.3
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        securityContext:
          seLinuxOptions:
            type: spc_t
  values:
    global:
      jwtPolicy: third-party-jwt
    cni:
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug
    pilot:
      cni:
        enabled: true
        provider: "multus"
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
```
Missing part was setting Isito CNI pods with seLinuxOptions spc_t, following discussion at https://github.com/istio/istio/issues/54815
