### ISSUE TITLE
panic: timed out waiting for domain to be defined (machine-id not available)

### ISSUE THREAD

**Issue by hivenet-fabioferreira** [kubevirt/kubevirt#13860]
**What happened**:
On launching a virtual machine instance it terminates automatically after some seconds.

Check there the logs:
```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:88","timestamp":"2025-02-04T14:20:06.332134Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:91","timestamp":"2025-02-04T14:20:06.332158Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:545","timestamp":"2025-02-04T14:20:06.332256Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:553","timestamp":"2025-02-04T14:20:06.332454Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 10.5.0, package: 5.el9 (builder@centos.org, 2024-08-09-10:14:52, )","subcomponent":"libvirt","thread":"42","timestamp":"2025-02-04T14:20:06.346000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vmi-cirros","subcomponent":"libvirt","thread":"42","timestamp":"2025-02-04T14:20:06.346000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"42","timestamp":"2025-02-04T14:20:06.346000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"42","timestamp":"2025-02-04T14:20:06.346000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:561","timestamp":"2025-02-04T14:20:06.834291Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:563","timestamp":"2025-02-04T14:20:06.838673Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2025-02-04T14:20:06.838975Z"}
panic: timed out waiting for domain to be defined
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:198","timestamp":"2025-02-04T14:25:17.845716Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:216","timestamp":"2025-02-04T14:25:17.845890Z"}
```

It seems `/etc/machine-id`and `/var/lib/dbus/machine-id` do not exist. 

**What you expected to happen**:
The virtual machine to start with success.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply virtual machine instance with the next specifications
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-cirros
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
    resources:
      requests:
        memory: 512M
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/kubevirt/cirros-container-disk-demo
```

**Additional context**:
Besides this problem I had to change the group owner of `/dev/kvm` to match the same GID of "qemu" (107) in the host machine. This is only a temporary solution to get rid of the permissions problem accessing this directory.

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T08:23:36Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T09:51:17Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`): v1.30.5+k3s1
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-cirros
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
    resources:
      requests:
        memory: 512M
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/kubevirt/cirros-container-disk-demo
```
- Cloud provider or hardware configuration: Bare metal. Nested virtualization is enabled and kvm is installed.
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
``` 
- Kernel (e.g. `uname -a`):
```
Linux  6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
```
- Install tools: N/A
- Others: N/A
