### ISSUE TITLE
Ensure that virt-controller assesses partially complete launcher pods properly

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1388]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

If the launcher pod is still controlled by virt-controller, and the `compute` container terminated, the vmi was stuck in `scheduled` since the pod did not completely terminate because of an exit code `0` but also never got ready, since we don't restart the `compute` container.

Here an example of the situation:

```yaml
  status:
    - containerID: docker://d0a0a8402ae770511746f681a56766665dfc2ea789b1a47aa6502f189619ae3b
      image: kubevirt/virt-launcher:devel
      imageID: docker-pullable://registry:5000/kubevirt/virt-launcher@sha256:c51f0799611fbadf2bb8c2d96afd7915d2c6d79ea7cd957f17fdd4000991335e
      lastState: {}
      name: compute
      ready: false
      restartCount: 0
      state:
        terminated:
          containerID: docker://d0a0a8402ae770511746f681a56766665dfc2ea789b1a47aa6502f189619ae3b
          exitCode: 0
          finishedAt: 2018-07-30T12:03:29Z
          reason: Completed
          startedAt: 2018-07-30T12:03:29Z
    - image: registry:5000/kubevirt/cirros-registry-disk-demo:devel
      imageID: ""
      lastState: {}
      name: volumeregistryvolume
      ready: false
      restartCount: 0
      state:
        waiting:
          reason: ContainerCreating
    hostIP: 192.168.66.101
    phase: Pending
```

The pod is in phase `Pending` and later in `Running` until the last pod termintes but the whole pod never gets ready.

Hitting this is not that likely since `virt-launcher` has to exit in that stage with a `0` exit code but it can happen.

**What you expected to happen**:

The virtual machine should go to a failed state.
