### ISSUE TITLE
instancetypes: Expanding VMs with inferFromVolume fails

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#13952]
**What happened**:

Expanding a virtual machine that uses inferFromVolume fails.

**What you expected to happen**:

Expanding a virtual machine that uses inferFromVolume should give the correct result.
That is a virtual machine with the inferred instancetype and/or preference expanded into the virtual machine's definition.

**How to reproduce it (as minimally and precisely as possible)**:

Create DV:

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
spec:
  source:
      registry:
         url: docker://quay.io/containerdisks/fedora:41
  storage:
    resources:
      requests:
        storage: "10Gi"
```

Run `virtctl create` and pipe it into `virtctl expand`:

```
virtctl create vm --volume-import=type:pvc,src:default/fedora | virtctl expand -f -
error expanding VirtualMachine - vm-ngwjt in namespace - default: resource name may not be empty
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
