### ISSUE TITLE
VM Restore object unexpectedly deleted by the controller

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#13956]
**What happened**:
VM restore object failed to complete because the target VM is already exists. However when I delete the target VM
The restore doesn't happen and suddenly the VM restore object itself also disappears.

**What you expected to happen**:
VM restore controller to eventually restore the VM, since target VM was deleted and restore can proceed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Cirros VM from project examples `examples/vm-cirros.yaml` (no need to launch the VM)
2. Create VM snapshot, source is the Cirros VM
```
kind: VirtualMachineSnapshot
metadata:
  name: snapshot-vm-cirros
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros
```
3. Wait for snapshot to complete.
4. Create VM restore object for `vm-cirros`
```
kind: VirtualMachineRestore
metadata:
  name: vm-restore-cirros
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros
  virtualMachineSnapshotName: snapshot-vm-cirros
```
5. Observe the VM restore status, should error with target already exists
6. Delete the vm-cirros VM
7. Observe the VM restore, it should disappear as well.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): main
