### ISSUE TITLE
RFE: Delay virt-launcher pod until importer pod is finished

### ISSUE THREAD

**Issue by jhassigrkt** [kubevirt/kubevirt#14003]
**Is your feature request related to a problem? Please describe**:
When using CDI to download an image to a PVC while deploying a VM, the VM will start before the importer pod is finished importing the data. This causes the VM (windows in this case) to sit at the boot manager either alerting that Windows failed to start, or that it cannot find proper boot media.

**Describe the solution you'd like**:
A method to have the virt-launcher pod delay starting until after the importer pod is finished. Being able to use an initContainer and sleep for ## Minutes could help in a "hope it completes in ## Minutes" fashion. A more proper solution of having an annotation or something of the sort that can watch for the import to be complete would be ... more proper.

**Describe alternatives you've considered**:

**Additional context**:
We are using Codefresh (ArgoCD on the backend) and helm to accomplish our VM Deploys thus a "kubectl wait" is not possible in our scenario. 

```
PVC YAML:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vm.computerName }}-dv
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.source: "s3"
    cdi.kubevirt.io/storage.import.endpoint: "s3://our/s3/endpoint/image.img"
    cdi.kubevirt.io/storage.import.secretName: "a secret"
    cdi.kubevirt.io/storage.import.certConfigMap: "a cert map"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.vm.rootdisk }}Gi
  storageClassName: ceph-block
  volumeMode: Block
```
```
VM YAML:
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.vm.computerName }}
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/compute: unconfined
        sidecar.istio.io/inject: 'true'
    spec:
      evictionStrategy: LiveMigrate
      terminationGracePeriodSeconds: 30
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv:
              present: true
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
        memory:
          guest: {{ .Values.vm.memory }}Gi
        cpu:  #Total vCPU = (cores * sockets * threads)
          cores: 1
          sockets: {{ .Values.vm.vcpu }}
          threads: 1
        devices:
          disks:
          - name: harddrive
            disk: {}
          - name: sysprep
            cdrom:
              bus: sata
          inputs:
              - bus: virtio
                name: tablet
                type: tablet
          interfaces:
            - binding:
                name: passt
              name: passt
        machine:
          type: q35
      volumes:
        - name: harddrive
          persistentVolumeClaim:
            claimName: {{ .Values.vm.computerName }}-dv
        - name: sysprep
          sysprep:
            configMap:
              name: {{ .Values.vm.computerName }}-sysprep-cm
      networks:
      - name: passt
        pod: {}
```

**Comment by awels** [comment]
Our answer is going to be use DataVolumes. DataVolumes are fully integrated with VMs and VMs will wait to start until the DV is complete. DataVolumes also provide a number of other benefits. You can use DataVolumes stand alone (create one ahead of time) or as part of the VM spec by using DataVolumeTemplates in the VM. This then ties the VM disk lifecycle to the VM lifecycle.

**Comment by jhassigrkt** [comment]
@awels  do DataVolumes support the same annotations as the PVCs?

  annotations:
    cdi.kubevirt.io/storage.import.source: "s3"
    cdi.kubevirt.io/storage.import.endpoint: "s3://our/s3/endpoint/image.img"
    cdi.kubevirt.io/storage.import.secretName: "a secret"
    cdi.kubevirt.io/storage.import.certConfigMap: "a cert map"

**Comment by awels** [comment]
So those annotations are actually internal CDI implementation details. The equivalent DataVolume will look something like this
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Values.vm.computerName }}-dv
spec:
  source:
      s3:
         url: "s3://our/s3/endpoint/image.img"
         secretRef: "secret"
         certConfigMap: "configMap"
  storage:
    resources:
      requests:
        storage: {{ .Values.vm.rootdisk }}Gi
```
More information on DataVolumes can be found [here](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/datavolumes.md)

I will also mention [StorageProfiles](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/storageprofile.md) which are used by CDI to fill in missing fields in spec. As you might have noticed in the above example volumeMode and accessModes are missing. Because the storage profile for rook ceph knows that the preferred combination for rook-ceph is RWX block, it will create the PVC with RWX block.

If you are going to use DataVolumes with ArgoCD, I highly suggest using DataVolumeTemplates so you don't get any synchronization issues with Argo. The DataVolume is automatically generated from the VM spec (when using DataVolumeTemplates), and the matching PVC is generated from the DataVolume.
