### ISSUE TITLE
Missing Windows Docs for ConfigMap/Secret as Disk/Fs

### ISSUE THREAD

**Issue by steven-freed** [kubevirt/kubevirt#14077]
**Description**:
No documentation on how to use a configmap or secret as a disk/fs for Windows OS.

**What you expected**:
A cloud-config with Windows commands, similar to the present examples with linux sh commands.  
For example, the cloud-config linux sh commands you currently have in the docs are...
```yaml
#cloud-config
password: fedora
chpasswd: { expire: False }
bootcmd:
  # mount the ConfigMap
  - "sudo mkdir /mnt/app-config"
  - "sudo mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
```

**URL**:
[Disks and Volumes - ConfigMap](https://kubevirt.io/user-guide/storage/disks_and_volumes/#configmap)
[Disks and Volumes - Secrets](https://kubevirt.io/user-guide/storage/disks_and_volumes/#secret)

**Additional context**:
I am struggling to get a configmap or secret mounted in a windows 10 VM. The VM has cloudbaseinit installed and the ConfigDrive service enabled. I believe adding Windows docs would greatly benefit the community. I do see an [old issue](https://github.com/kubevirt/kubevirt/issues/11530) regarding this same problem that never had a resolution.
