### ISSUE TITLE
memory hotplug doesn't work with alpine-container-disk-demo

### ISSUE THREAD

**Issue by Barakmor1** [kubevirt/kubevirt#14095]
**What happened**:

I have a kubevirtCI cluster with nodes with 5Gi,
I attempted to increase the memory of the following VM to 2Gi:

```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    special: vm-migratable
  name: vm-migratable
spec:
  running: true
  template:
    metadata:
      labels:
        special: vm-migratable
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
          interfaces:
            - masquerade: {}
              name: default
        memory:
          guest: 1Gi
          maxGuest: 2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: kubevirt/alpine-container-disk-demo:devel
          name: containerdisk
```

I used the following kubevirtCR.spec setup:

```
  spec:
    certificateRotateStrategy: {}
    configuration:
      developerConfiguration: {}
      vmRolloutStrategy: LiveUpdate
    customizeComponents: {}
    imagePullPolicy: IfNotPresent
    workloadUpdateStrategy:
      workloadUpdateMethods:
      - LiveMigrate
```

I tried using memory hotplug during live migration. While the migration completed successfully, the VMI got stuck in this state:

```
bmordeha@fedora:~/Work/kubevirt$ k get vmi -oyaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
...
  spec:
...
      memory:
        guest: 2Gi
        maxGuest: 2Gi
      resources:
        requests:
          memory: 2Gi
...
  status:
...
    memory:
      guestAtBoot: 1Gi
      guestCurrent: 1Gi
      guestRequested: 2Gi
...
```

Additionally, the guest is still reporting the old memory value:

```
bmordeha@fedora:~/Work/kubevirt$ v console vm-migratable
WARNING: usage of '/home/bmordeha/Work/kubevirt/kubevirtci/cluster-up/virtctl.sh' is deprecated!
         see: https://github.com/kubevirt/kubevirtci/issues/1277
selecting podman as container runtime
WARNING: /home/bmordeha/Work/kubevirt/kubevirtci/cluster-up//../_out not found, falling back to parent
         /home/bmordeha/Work/kubevirt/kubevirtci/cluster-up//../../_out
Successfully connected to vm-migratable console. The escape sequence is ^]

/ # free -m
             total       used       free     shared    buffers     cached
Mem:           996         25        970         15          0         15
-/+ buffers/cache:         10        986
Swap:            0          0          0
/ # 
```
I couldn't find any events or conditions related to the issue, but here are the logs from the target launcher:

```
connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"22","timestamp":"2025-03-03T12:52:38.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"25","timestamp":"2025-03-03T12:52:39.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"23","timestamp":"2025-03-03T12:52:40.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"26","timestamp":"2025-03-03T12:52:41.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"25","timestamp":"2025-03-03T12:52:42.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"23","timestamp":"2025-03-03T12:52:43.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"26","timestamp":"2025-03-03T12:52:44.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"24","timestamp":"2025-03-03T12:52:45.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"22","timestamp":"2025-03-03T12:52:46.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"25","timestamp":"2025-03-03T12:52:47.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"24","timestamp":"2025-03-03T12:52:48.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"22","timestamp":"2025-03-03T12:52:49.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"25","timestamp":"2025-03-03T12:52:50.289000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"23","timestamp":"2025-03-03T12:52:51.288000Z"}
{"component":"virt-launcher","level":"error","msg":"Guest agent is not responding: QEMU guest agent is not connected","pos":"qemuDomainAgentAvailable:7114","subcomponent":"libvirt","thread":"26","timestamp":"2025-03-03T12:52:52.288000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"failed to sync guest time","name":"vm-migratable","namespace":"default","pos":"manager.go:387","timestamp":"2025-03-03T12:52:53.288883Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to set time: QEMU agent unresponsive, virError(Code=86, Domain=10, Message='Guest agent is not responding: QEMU guest agent is not connected')","name":"vm-migratable","namespace":"default","pos":"manager.go:376","timestamp":"2025-03-03T12:52:53.288976Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm-migratable","namespace":"default","pos":"server.go:208","timestamp":"2025-03-03T12:54:07.330629Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm-migratable","namespace":"default","pos":"server.go:208","timestamp":"2025-03-03T12:59:07.331243Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm-migratable","namespace":"default","pos":"server.go:208","timestamp":"2025-03-03T13:04:07.332998Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm-migratable","namespace":"default","pos":"server.go:208","timestamp":"2025-03-03T13:09:07.330258Z","uid":"702b4053-736f-40cb-9b97-647fc5df2348"}
```

**What you expected to happen**:
the hotplug to work

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): 32
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
