### ISSUE TITLE
Windows 11 works with persistentVolumeClaim but not with containerDisk

### ISSUE THREAD

**Issue by dren-dk** [kubevirt/kubevirt#14188]
**What happened**:

I'm trying to build a new container with windows 11, I have the OS installed and booting from a persistentVolumeClaim, but when I create a containerDisk and try to boot from that I immediately get a message saying:
```
Booting from Hard Disk...

A disk read error occurred
Press Ctrl+Alt+Del to restart
```

I'm using virtio and windows 11 was installed on virtio initially.

This VM definition works:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: working
spec:
  running: true
  template:
    metadata:
      annotations:
        debugLogs: "true"
      creationTimestamp: null
      labels:
        debugLogs: "true"
        disableFirewall: "true"
        vmName: win11-23h2
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 2
            disk:
              bus: virtio
            name: boot
          - disk:
              bus: virtio
            name: service
          - disk:
              bus: virtio
            name: tools
          - cdrom:
              bus: sata
            name: secret-volume
          interfaces:
          - bridge: {}
            macAddress: 02:05:11:b0:42:42
            name: default
            ports:
            - port: 22
            - port: 80
            - port: 443
            - port: 3389
            - port: 3400
          tpm: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources:
          requests:
            memory: 8Gi
      networks:
      - name: default
        pod: {}
      nodeSelector:
        type: RS-8537R4
      volumes:
      - name: boot
        persistentVolumeClaim:
          claimName: win11-23h2
      - containerDisk:
          image: registry.stibo.dk/rm/public/kubevirt/build-agent-service:ae7bf3c6a7f766b4969ded4655b3f90be6c879ad
        name: service
      - containerDisk:
          image: registry.stibo.dk/containers/public/windows-vm-tools-container:042e374c3816efcad014312fed7833b4dd20b1df
        name: tools
      - name: secret-volume
        secret:
          secretName: service-mode
```

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fails
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm-vc2022-win11
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: boot
          - disk:
              bus: virtio
            name: service
          - disk:
              bus: virtio
            name: tools
          - cdrom:
              bus: sata
            name: windows-secret-volume
          interfaces:
          - bridge: {}
            macAddress: 02:05:11:b0:42:42
            name: default
          tpm: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        machine:
          type: q35
        memory:
          guest: 10Gi
        resources:
          requests:
            memory: 10Gi
      livenessProbe:
        failureThreshold: 10
        httpGet:
          path: /admin/healthcheck
          port: 3400
        initialDelaySeconds: 600
        periodSeconds: 60
        timeoutSeconds: 60
      networks:
      - name: default
        pod: {}
      nodeSelector:
        type: RS-8537R4
      volumes:
      - containerDisk:
          image: kubevirt.stibo.dk/vm/win11:23H2-minimal-20250310-2
        name: boot
      - containerDisk:
          image: registry.stibo.dk/rm/public/kubevirt/build-agent-service:f0440165911a0902e5450d602e785a4dfcc53171
        name: service
      - containerDisk:
          image: registry.stibo.dk/containers/public/windows-vm-tools-container:042e374c3816efcad014312fed7833b4dd20b1df
        name: tools
      - name: windows-secret-volume
        secret:
          secretName: vm-vc2022-win11

```

**Environment**:

- KubeVirt version (use `virtctl version`): Server Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T09:51:17Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): Server Version: v1.30.4
- Cloud provider or hardware configuration: bare metal
