### ISSUE TITLE
Can't read memory from /dev/mem

### ISSUE THREAD

**Issue by groundsada** [kubevirt/kubevirt#14210]
This is the YAML for the VMI I'm using:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm
spec:
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
        devices:
          autoattachGraphicsDevice: true
          autoattachSerialConsole: true
          disks:
          - disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: virtiocontainerdisk
            bootOrder: 1
          - disk:
              bus: virtio
            name: cloudinit
        machine:
          type: q35
        resources:
          limits:
            cpu: 800m
            memory: 8Gi
          requests:
            cpu: 800m
            memory: 8Gi
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
        name: virtiocontainerdisk
      - emptyDisk:
          capacity: 16Gi
        name: harddrive
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            disk_setup:
              /dev/vda:
                table_type: gpt
                layout: True
                overwrite: True
            fs_setup:
              - device: /dev/vda
                partition: 1
                filesystem: xfs
            mounts:
             - [ vda, /opt/data ]
        name: cloudinit
```

This same YAML works on some nodes in my cluster but not others. I'm using Kubernetes 1.28. This was first noticed in v.1.4.0 and is still there in v1.5.0-rc.2

The `virt-launcher` pod gets into Error 2/3 a minute into starting, and virt-handler on that node goes into CrashLoopBackOff.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.4.0 and v1.5.0-rc.2
- Kubernetes version (use `kubectl version`): 1.28
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-94-generic
