### ISSUE TITLE
Virt-launcher pod does not inherit VMI annotation `kubectl.kubernetes.io/default-container`

### ISSUE THREAD

**Issue by seastco** [kubevirt/kubevirt#14221]
**What happened**:
I set the `kubectl.kubernetes.io/default-container` annotation on my VMI to `guest-console-log`:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: guest-console-log
```

However the virt-launcher-pod is still set to `compute`:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: compute
```

**What you expected to happen**:
I expected the virt-launcher pod to inherit the annotation. I am setting other annotations on the VMI that the virt-launcher pod is properly inheriting.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add `kubectl.kubernetes.io/default-container` annotation to the VMI spec, e.g:

```
Spec: kubevirtcorev1.VirtualMachineSpec{
	Running: ptr.To(true),
	Template: &kubevirtcorev1.VirtualMachineInstanceTemplateSpec{
		ObjectMeta: k8smetav1.ObjectMeta{
			Name:        resource.Name,
			Labels:      labels,
			Annotations: annotations,
		},
		Spec: kubevirtcorev1.VirtualMachineInstanceSpec{
			Tolerations: getTolerations(),
			Domain:      kubevirtcorev1.DomainSpec{},
		},
	},
},
```
2. Create VMI
3. Observe that virt-launcher pod does not inherit it.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1
- Kubernetes version (use `kubectl version`): v1.28.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): `22.04.5 LTS (Jammy Jellyfish)`
