### ISSUE TITLE
Can't attach PVCs

### ISSUE THREAD

**Issue by groundsada** [kubevirt/kubevirt#14239]
When I add a PersistentVolumeClaim, my KubeVirt VM fails, and my virt-launcher pod goes back from Ready 3/3 to Error 2/3.

The YAML that breaks:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm
spec:
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: virtiocontainerdisk
            bootOrder: 1
          - disk:
              bus: virtio
            name: cloudinitdisk
          - name: vivado-volume
            disk: 
              bus: virtio
        machine:
          type: q35
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
      volumes:
      - name: vivado-volume
        persistentVolumeClaim:
          claimName: vivado-volume
      - containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
        name: virtiocontainerdisk
      - emptyDisk:
          capacity: 16Gi
        name: harddrive
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: ubuntu
            chpasswd: { expire: False }
        name: cloudinitdisk
```

The YAML that works:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm
spec:
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: virtiocontainerdisk
            bootOrder: 1
          - disk:
              bus: virtio
            name: cloudinitdisk
          - name: vivado-volume
            disk: 
              bus: virtio
        machine:
          type: q35
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
        name: virtiocontainerdisk
      - emptyDisk:
          capacity: 16Gi
        name: harddrive
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: ubuntu
            chpasswd: { expire: False }
        name: cloudinitdisk
```

**Environment**:
- KubeVirt version (use `virtctl version`): KubeVirt v1.5.0-rc.2, virtctl below:
```
virtctl version
Client Version: version.Info{GitVersion:"1.4.0", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.23.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v1.4.0", GitCommit:"9b9b3d4e7b681af96ca1b6b6a5cea75e2f05ce5b", GitTreeState:"clean", BuildDate:"2024-11-13T09:51:17Z", GoVersion:"go1.22.8 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`): 
```
kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.28.11
```
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15
- Kubernetes not k3s or something else
