### ISSUE TITLE
The virtual machine starts normally for the first time. Network loss after restart

### ISSUE THREAD

**Issue by huliangshan** [kubevirt/kubevirt#14314]
The virtual machine starts normally for the first time. Network loss after restart

![Image](https://github.com/user-attachments/assets/6661b0e5-59f9-4638-a764-48144d1a2d62)

**Environment**:
- KubeVirt version (use `virtctl version`): 1.5.0
- Kubernetes version (use `kubectl version`): v1.24.17
- VM or VMI specifications: 
`
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-rg-dv
  name: vm-rg-dv
  namespace: kubevirt-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-rg-dv 
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 4Gi
        devices:
          interfaces:
          - name: default
            masquerade: {}  
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 8Gi
      networks:
      - name: default
        pod: {}  
      volumes:
      - dataVolume:
          name: dv-vm-registry 
        name: datavolumedisk1
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: ubuntu
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
  dataVolumeTemplates:
  - metadata:
      name: dv-vm-registry
    spec:
      storage:
        storageClassName: rook-cephfs-retain 
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
      source:
        registry:
          url: docker:/xxx.com/library/ubuntu-focal-server:20.04
`
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): 20.04.6 LTS
- Kernel (e.g. `uname -a`): 5.4.0-196-generic
- Install tools: 
- Others:

**Comment by EdDev** [comment]
> Another related issue was resolved by addressing a problem with randomly generated MAC addresses on VM startup. To ensure a consistent MAC address, you can explicitly define it in the VM Spec or use KubeMacPool to automate the MAC address assignment https://github.com/kubevirt/kubevirt/issues/9993.

This seems to be your problem.
Let us know if it solved it for you.

**Comment by huliangshan** [comment]
@EdDev I can solve this problem using cloud int 
```yaml
cloudInitNoCloud:
          userData: |
            #cloud-config
            user: ubuntu
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            write_files:
              - path: /etc/systemd/system/fix-network.service
                content: |
                  [Unit]
                  Description=Fix network on boot
                  After=network.target

                  [Service]
                  Type=oneshot
                  ExecStart=/bin/sh -c "ip link set enp1s0 up && dhclient enp1s0"

                  [Install]
                  WantedBy=multi-user.target
            runcmd:
              - systemctl enable fix-network.service
              - systemctl start fix-network.service
```
