### ISSUE TITLE
IP change after live migration

### ISSUE THREAD

**Issue by cloudcafetech** [kubevirt/kubevirt#14320]
I am using Kubevirt along with Multus & whereabouts.

My network attachment definition as follows 

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-whereabouts
  namespace: virtualmachines
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-whereabouts",
      "type": "bridge",
      "bridge": "br0",
      "promiscMode": true,       
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.0.0/24",
        "range_start": "192.168.0.20",
        "range_end": "192.168.0.50",
        "gateway": "192.168.0.1",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
```

After successful migration all good except IP change from **192.168.0.20** to **192.168.0.21**

![Image](https://github.com/user-attachments/assets/74f14ad6-6d86-4796-b2b5-d51af84b15f0)

I want keep same IP (192.168.0.20) when VM launch first time, after migration as well.

**Comment by cloudcafetech** [comment]
If I use multiple NAD with suggested configuration

> range_start and range_end to the same IP

Then how to configure KubeVirt to use multiple NAD for migrations in configuration (point no. 2) - can I use wildcard ( bridge-whereabouts-vm-* )

**Comment by cloudcafetech** [comment]
Then what is the best solutions for my scenario?

**Comment by orelmisan** [comment]
Hi @cloudcafetech.
Could you please share your VM spec?

In general, having a "sticky IP" when migrating is dependent on your cluster's network provider.
I know OVN-K has this capability (it may require deploying additional components though).

With regards to your question about migration network, please note that this is a network on which the migration traffic runs.
It is an optional secondary network for connecting virt-handlers (on migration, two virt-launcher pods are connected via their virt-handlers).
https://kubevirt.io/user-guide/compute/live_migration/#using-a-different-network-for-migrations

**Comment by cloudcafetech** [comment]
@orelmisan 

VM specs as follows.. and I am using cillium cni. 

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-external-vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-external-vm
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 2
        memory:
          guest: 4G
        machine:
          type: q35
        devices:
          rng: {}
          disks:
            - name: ubuntu-external-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: external
            bridge: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
      networks:
      - name: external
        multus:
          default: true
          networkName: virtualmachines/bridge-whereabouts
      volumes:
        - name: ubuntu-external-pvc
          persistentVolumeClaim:
            claimName: ubuntu-external-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:          
            userData: |-
              #cloud-config
              hostname: kv-ubuntu-ext
              user: abcdef
              password: password
              chpasswd: { expire: False }
              
```

**Comment by orelmisan** [comment]
Thank you for providing the VM spec @cloudcafetech.
I assumed you were using the Multus default network feature and bridge binding, but wanted to make sure.

Have you considered using the Masquerade binding?
https://kubevirt.io/user-guide/network/interfaces_and_networks/#masquerade

**Comment by cloudcafetech** [comment]
@orelmisan 

>I assumed you were using the Multus default network feature and bridge binding, but wanted to make sure.

Yes

Don't want to use k8s service that is why not considering masquerade.

**Comment by orelmisan** [comment]
Thank you for sharing. It would be helpful if you could please provide more details about your use case. Having a better understanding of your scenario will give the community more context and make it easier to offer useful suggestions or solutions.

**Comment by cloudcafetech** [comment]
@orelmisan 
Look, use case is very simple. 

VM IP should remain same (stable) if VM move one to another node. So end user of VM should not feel there is change.

**Comment by EdDev** [comment]
> [@cloudcafetech](https://github.com/cloudcafetech) sticky IPs is not implemented at kubevirt or whereabouts, you should use a KubeVirt aware network provider like ovn-kubernetes.

To emphasize, the change in the IP is due to the IPAM used in conjunction of the bridge binding that reflects the IP from the pod to the guest.

Most users choose to use secondary networks and not the primary in such cases.
Your replacement of the primary cluster network with multus is uncommon, limiting your options.

You could try this: Remove `default: true` from the multus network, making it a secondary network and remove IPAM configuration from the NAD.
Use cloud-init network v2 to configure a specific IP in the guest or manage IPs in the network using your own dhcp server.

**Comment by cloudcafetech** [comment]
@EdDev Thanks.

If I remove default: true and use both primary (internal: pod & secondary (external: multus) as below then from host I can see external interface down but from VMI its show UP.

- VM yaml

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-external-vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-external-vm
      annotations:
        #kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 2
        memory:
          guest: 4G
        machine:
          type: q35
        devices:
          rng: {}
          disks:
            - name: ubuntu-external-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: internal
            masquerade: {}
          - name: external
            bridge: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
      networks:
      - name: internal
        pod: {}
      - name: external
        multus:
          #default: true
          networkName: virtualmachines/bridge-whereabouts
      volumes:
        - name: ubuntu-external-pvc
          persistentVolumeClaim:
            claimName: ubuntu-external-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              hostname: kv-ubuntu-ext
              user: cloudcafe
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: false
```

- Inside VM

```
cloudcafe@kv-ubuntu-ext:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:d4:67:00:00:0c brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 metric 100 brd 10.0.2.255 scope global dynamic enp1s0
       valid_lft 86313541sec preferred_lft 86313541sec
    inet6 fe80::d4:67ff:fe00:c/64 scope link
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:d4:67:00:00:0d brd ff:ff:ff:ff:ff:ff
```

- cli

```
kubectl  get po,vm,vmi | grep ubuntu-external-vm

pod/virt-launcher-ubuntu-external-vm-h4mnd        2/2     Running     0          10m
virtualmachine.kubevirt.io/ubuntu-external-vm   10m   Running   True
virtualmachineinstance.kubevirt.io/ubuntu-external-vm   10m   Running   10.96.1.110   lenevo-ts-w2   True

kubectl get vmi ubuntu-external-vm -o jsonpath='{.status.interfaces}' | jq

[
  {
    "infoSource": "domain",
    "ipAddress": "10.96.1.110",
    "ipAddresses": [
      "10.96.1.110"
    ],
    "linkState": "up",
    "mac": "02:d4:67:00:00:0c",
    "name": "internal",
    "podInterfaceName": "eth0",
    "queueCount": 1
  },
  {
    "infoSource": "domain, multus-status",
    "ipAddress": "192.168.0.20",
    "ipAddresses": [
      "192.168.0.20"
    ],
    "linkState": "up",
    "mac": "02:d4:67:00:00:0d",
    "name": "external",
    "podInterfaceName": "pod3c4623849a4",
    "queueCount": 1
  }
]
```
