### ISSUE TITLE
Create DataVolume Error， importer.go:137] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied

### ISSUE THREAD

**Issue by huliangshan** [kubevirt/kubevirt#14335]
[](importer.go:137] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied)

![Image](https://github.com/user-attachments/assets/9889e98d-8611-40b3-8239-6b882b8a5f66)

**Environment**:
- KubeVirt version (use `virtctl version`): v1.5.0 
- Kubernetes version (use `kubectl version`): v1.24.17
- DataVolume specifications: 
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-rbd
  namespace: kubevirt-test
spec:
  source:
    registry:
      url: docker://xxx.com/library/ubuntu-focal-server:20.04
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: rook-ceph-block
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS 
- Kernel (e.g. `uname -a`): 5.4.0-196-generic 
- Install tools: rook-ceph
- Others: N/A
