### ISSUE TITLE
Restoring a VM not compatible with gitops

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/kubevirt#14372]
**What happened**:
Restoring a VM creates new PVCs/DataVolumes and updates the VM spec to restore to these new resources. If the original yaml is reapplied, the changes to the VM spec (new pvc references) are rolled back.  If the VM uses dataVolumeTemplates, new DataVolumes will be created by virt-controller. When the VM is started (or restarted if already running), the vm will use the new dataVolume templates and "old" DVs/PVCs that are not dataVolume templates. 

**What you expected to happen**:
I think the only way to avoid this is for VM restore process to not use new names for volumes.

When VW restore was initially designed, we decided to use new/random names for the following reasons:

1. It is safer. VolumeSnapshots can only be restored to new PVCs. By restoring to new, random named PVCs, we have the ability to rollback to original PVCs if creating the PVCs form VolumeSnapshots fails. Otherwise, the original PVCs have to be deleted first. If creating the new PVCs from VolumeSnapshots fails, we cannot rollback
2. It could be considered problematic to delete/create PVCs/DVs that were not created by virt-controller (i.e. not DataVolume templates). Could have collisions with gitops or other external controllers that could be managing those resources

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1. Apply yaml below
2. Snapshot VM
3. Stop VM
4. Restore VM
5. Observe that `cirros-rootdisk` DV/PVC is deleted. There is a new `restore-XXX-rootdisk` DV + PVC. New `restore-XXX-datadisk` PVC. VM yaml updated to refer to new resources.
6. Apply yaml again
7. Observe that VM is referring to original resources. Also virt-controller will create a new `cirros-rootdisk` DV/PVC.
8. Starting the VM wil use new `cirros-rootdisk` and old `cirros-datadisk`

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  dataVolumeTemplates:
  - metadata:
      name: cirros-rootdisk
    spec:
      storage:
        resources:
          requests:
            storage: 1Gi
      source:
        registry:
          url: docker://registry:5000/kubevirt/cirros-container-disk-demo:devel
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: datadisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 128Mi
      volumes:
      - dataVolume:
          name: cirros-rootdisk
        name: rootdisk
      - dataVolume:
          name: cirros-datadisk
        name: datadisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-datadisk
spec:
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 256Mi
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by SkalaNetworks** [comment]
If I'm not mistaken, VM Restores allow to restore in a VM that isn't the source VM. This is effectively like cloning a VM, except nothing is changed about it (labels, annotations, MAC addr...)

This is useful to keep the initial VM while debugging a snapshot. But of course, the VM created is nowhere to be found in your Git.  This isn't too problematic because you can re-create the VM object in your Git, matching what was generated by the VMRestore.

When it comes to restoring a VM from a snapshot "onto itself", my current hack is to modify my VM in the Git to match what was changed by the VMRestore. Usually, it involves removing references to DataVolumes and replacing by the persistentVolumeClaims. Could it be a good idea for the restore controller to generate a DataVolume matching the snapshotted one instead of a PVC?

**Comment by SkalaNetworks** [comment]
Hi, I think I'll start working on this as I'm in need of a fully GitOps-compatible workflow.

Here's the problems I see right now with snapshots/restores:
- Modifying any parameter of the VM using GitOps AFTER a Snapshot and then triggering a restore will mark the VM as OutOfSync, this is in my opinion acceptable. You've restored your VM to a previous state, it means editing your VM on Git to make it synced again.
- Restoring a VM that uses dataVolumeTemplates will re-trigger the creation of a new DV. I'm not sure how to fix that. I personally try not to use dataVolumeTemplates when doing GitOps because it ties the lifeycycle of the DV with the VM. I prefer creating DVs manually and mounting them on the VM. In any case, from a GitOps point of view, this behaviour is not acceptable.
- Restoring a VM that uses DVs that have been created externally will make the VM OutOfSync because Kubevirt overwrites the VM with PVC mounts instead of DV mounts. What I mean by that is that any reference to the datavolumes is wiped, and Kubevirt will only get interested in the PVCs. To fix that, you need to find the name of the PVCs created by Kubevirt after the restore (`restore-xxx-oldpvcname`) and edit your VM in Git to reflect the changes. That means removing references to DVs and instead using persistentVolumes. That's a lot of work that could be skipped.

I think it's next to impossible to fully reconciliate GitOps with snapshots. We could imagine adding a field in VirtualMachine CRDs to reference a VMSnapshot, and populate the volumes based on that reference. But that means losing control of the volumes if you want to detach them or edit them.

I also think that the restore logic should create DVs associated with the PVCs when doing the restore. If I write a VM mounting a DV I created by hand like this : 
```yaml
      - dataVolume:
          name: cirros-datadisk
        name: datadisk
```
... I want when restoring my VM to have a restored DV, and not just a restored PVC like what Kubevirt does right now. This would mean editing my VM in Git to change the name of the mounted DV (for example restored-xxx-dv) instead of also changing the volume type to persistentVolumes.

Giving the option to users to choose the name of the restored volume could be a good middleground to help with reconciling their GitOps manifest with what Kubevirt restored.  

Right now this function does that job:
```yaml
func restorePVCName(vmRestore *snapshotv1.VirtualMachineRestore, name string) string {
	return fmt.Sprintf("restore-%s-%s", vmRestore.UID, name)
}
```

Making `vmRestore.UID` a parameter in the CRD could alleviate some problems. It also risks conflicts with already existing resources if the user runs the same restore twice without changing the ID.

Also @mhenriks  you said
>  I think the only way to avoid this is for VM restore process to not use new names for volumes.

This implies, as you've stated, deleting the original PVCs. I guess it might be desirable for some users? Maybe making it an option in the CRD, something like "overwriteExistingVolumes: true" ?

Let's not forget snapshot restores can be done on a completely new instance of a VM too, not just on the source. In that case, predictable names would make more sense. Having both options sound like a good comprise to me.

I'd like to know what people think before pushing some code!
