### ISSUE TITLE
failed to create GPU host-devices: the number of GPU/s do not match the number of devices:\nGPU: [{gpu1 nvidia.com/gpu <nil> } {gpu2 nvidia.com/gpu <nil> }]\nDevice: []

### ISSUE THREAD

**Issue by huliangshan** [kubevirt/kubevirt#14387]
Kubevirt uses Nvidia A30 PCI
```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - DataVolumes
      - HotplugVolumes
      - Snapshot
      - HostDevices
      - GPU
    permittedHostDevices:
      pciHostDevices:
      - externalResourceProvider: false
        pciVendorSelector: 10de:20b7
        resourceName: nvidia.com/gpu
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```
get PCI Id

![Image](https://github.com/user-attachments/assets/94ec4d85-5199-4b96-bacc-fd82a53fa0d1)

kubelet with nvidia A30 (nvidia-device-plugin)

![Image](https://github.com/user-attachments/assets/991a0420-760c-44e3-aef3-bf5dd227280c)

virt handle
```yaml
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-rg-dv-gpu","namespace":"kubevirt-test","pos":"vm.go:2053","reason":"server error. command SyncVMI failed: \"failed to create GPU host-devices: the number of GPU/s do not match the number of devices:\\nGPU: [{gpu1 nvidia.com/gpu <nil> } {gpu2 nvidia.com/gpu <nil> }]\\nDevice: []\"","timestamp":"2025-04-01T03:27:02.386077Z","uid":"c899ee06-fc9e-491e-90a3-2e56777b12c7"}
```
**Environment**:
- KubeVirt version (use `virtctl version`): v1.5.0
- Kubernetes version (use `kubectl version`): v1.24.17 
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-rg-dv-gpu
  name: vm-rg-dv-gpu
  namespace: kubevirt-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-rg-dv-gpu
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 4Gi
        devices:
          gpus:
          - deviceName: nvidia.com/gpu  # 第一个 GPU
            name: gpu1
          - deviceName: nvidia.com/gpu  # 第二个 GPU
            name: gpu2
          interfaces:
          - name: default
            masquerade: {}  # 使用NAT网络
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 8Gi
      networks:
      - name: default
        pod: {}  # 使用Pod网络
      volumes:
      - dataVolume:
          name: dv-vm-registry-gpu
        name: datavolumedisk1
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: ubuntu
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: True
            write_files:
              - path: /etc/systemd/system/fix-network.service
                content: |
                  [Unit]
                  Description=Fix network on boot
                  After=network.target

                  [Service]
                  Type=oneshot
                  ExecStart=/bin/sh -c "ip link set enp1s0 up && dhclient enp1s0"

                  [Install]
                  WantedBy=multi-user.target
            runcmd:
              - systemctl enable fix-network.service
              - systemctl start fix-network.service  
  dataVolumeTemplates:
  - metadata:
      name: dv-vm-registry-gpu
    spec:
      storage:
        storageClassName: rook-cephfs 
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
      source:
        registry:
          url: docker://xxx.com/library/ubuntu-focal-server:20.04
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): 22.04.5 LTS (Jammy Jellyfish)
- Kernel (e.g. `uname -a`): 5.15.0-125-generic 
- Install tools: nvidia-device-plugin
- Others: N/A
