### ISSUE TITLE
Installation fails on Rancher RKE2

### ISSUE THREAD

**Issue by max06** [kubevirt/kubevirt#14429]
**What happened**:
Following the installation steps for kind, the job triggered by `kubectl create -f "https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml"` gets stuck in pending, due to not being schedulable.

The error message is showing: 

```text
0/4 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/etcd: }. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```

**What you expected to happen**:
The triggered job should finish without issues.

**How to reproduce it (as minimally and precisely as possible)**:
Have a rancher-managed rke2 cluster looking similar to:

```text
(deployments) vscode ➜ /workspaces/deployments (main) $ kubectl get nodes --selector kubernetes.io/os=linux
NAME       STATUS   ROLES                              AGE   VERSION
srv-pi01   Ready    control-plane,etcd,master,worker   21d   v1.31.7+rke2r1
srv-pi02   Ready    control-plane,etcd,master,worker   21d   v1.31.7+rke2r1
srv-pi03   Ready    control-plane,etcd,master,worker   21d   v1.31.7+rke2r1
srv-pi04   Ready    worker                             21d   v1.31.7+rke2r1
```

Notice the etcd role.

Deploy kubevirt following the instructions outlined for kind clusters.

**Additional context**:
Following kustomize patch solves the issue:

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  infra:
    nodePlacement:
      tolerations:
        - key: node-role.kubernetes.io/etcd
          operator: Exists
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.5.0
- Kubernetes version (use `kubectl version`): v1.31.7+rke2r1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: 4xRaspberry Pi 5 16G
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
