### ISSUE TITLE
v1.4.0 -> v1.5.0, can no longer change the ownership of virtiofs

### ISSUE THREAD

**Issue by seastco** [kubevirt/kubevirt#14522]
In my KubeVirt VM's cloud-init, I am mounting a virtiofs and am unable to change the ownership:
```
echo "data-egress /home/seastco/data-egress virtiofs defaults 0 1" | sudo tee -a /etc/fstab
sudo mount -a /etc/fstab --verbose
chown seastco:seastco /home/seastco/data-egress
chown: changing ownership of '/home/seastco/data-egress': Operation not permitted
```
This worked in `v1.4.0` but does **not** work in `v1.5.0`. I suspect this is related to [this](https://github.com/kubevirt/kubevirt/pull/11997/files?diff=split&w=1#diff-4f63bfc8c68701e06b06c1993792f5288c71c18b1697fe352d124f7e0d3a946f) change where the privileged security profile was removed.

How do I go about changing the ownership of this virtiofs? I tried some different mounting options but was not able to resolve this.

VMI spec:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: ubuntu
  namespace: seastco-b61e7-mdl69
spec:
  architecture: amd64
  domain:
    cpu:
      cores: 4
      dedicatedCpuPlacement: true
      model: host-model
    devices:
      disks:
      - disk:
          bus: sata
        name: containerdisk
      - disk:
          bus: sata
        name: cloudinit
      filesystems:
      - name: data-egress
        virtiofs: {}
      interfaces:
      - masquerade: {}
        name: default
        pciAddress: 0000:64:00.0
    features:
      acpi:
        enabled: true
    firmware:
      uuid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    machine:
      type: q35
    memory:
      guest: 8192M
    resources:
      limits:
        memory: 9216M
      requests:
        memory: 9216M
  evictionStrategy: None
  networks:
  - name: default
    pod: {}
  volumes:
  - containerDisk:
      image: my-ubuntu-containerdisk-v1.0.0
    name: containerdisk
  - name: data-egress
    persistentVolumeClaim:
      claimName: ubuntu-data-egress
  - cloudInitNoCloud:
      networkData: |
        version: 2
        ethernets:
          enp100s0:
            dhcp4: true
      secretRef:
        name: cloud-init-ubuntu
    name: cloudinit
```

**Comment by seastco** [comment]
@dosu hmm so that would involve changing the ownership of the PVC on the host? is there any other way to enable this through the VMI spec or a virtiofs mount option that I'm missing?

**Comment by seastco** [comment]
@dosubot The PVC is created right before my VMI is being created. I won't know the host path ahead of time or have host access. I need to change ownership to my user `seastco`.

Here is the PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-data-egress
  namespace: seastco-a16b4-mdd59
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-csi
  volumeMode: Filesystem
  volumeName: pvc-5e7be9b2-48c9-4f80-a4ad-c4fc5d1ef159
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3459701040Ki
  phase: Bound
```

On the host the PVC is owned by root:
```
drwx------ 4 root root 4096 Apr 18 14:17 pvc-5e7be9b2-48c9-4f80-a4ad-c4fc5d1ef159

[root@ip-10-10-10-10 pvc-5e7be9b2-48c9-4f80-a4ad-c4fc5d1ef159]# ls -l
total 8
drwx------ 2 root root 4096 Apr 18 14:17 data
drwx------ 2 root root 4096 Apr 18 14:17 metadata
```
