### ISSUE TITLE
Libvirt error when trying to create a VM with passthrough GPU

### ISSUE THREAD

**Issue by nrogerarkhn** [kubevirt/kubevirt#14593]
Hello,

This might not be a bug as much as a request for help, do not hesitate to correct this post in any relevant way. I'm stuck and have no idea how to proceed. I would really appreciate it if someone could give me any pointers. Thanks in advance!

**What happened**:
Libvirt error when starting a VM/VMI when using passthrough GPU.
```
LibvirtError(Code=1, Domain=10, Message='internal error: QEMU unexpectedly closed the monitor (vm='arkhn_testvm'): 
  2025-04-25T14:42:06.039307Z qemu-kvm: -device 
    {"driver":"vfio-pci",
    "host":"0000:35:00.0",
    "id":"ua-hostdevice-gpu1",
    "bus":"pci.8","addr":"0x0"}: VFIO_MAP_DMA failed: Cannot allocate memory
  2025-04-25T14:42:06.587713Z qemu-kvm: -device
    {"driver":"vfio-pci",
    "host":"0000:35:00.0",
    "id":"ua-hostdevice-gpu1",
    "bus":"pci.8",
    "addr":"0x0"}: vfio 0000:35:00.0: failed to setup container for group 75: memory listener initialization failed: Region pc.bios: vfio_container_dma_map (0x5632ad2e1e80, 0xfffc0000, 0x40000, 0x7fdf48200000) = -2 (No such file or directory)')
```

**What you expected to happen**:
No error and the VM launching with GPU accessible.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install [Nvidia drivers](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#pre-installation-actions)
2. Install Nvidia utilities for Kubevirt using VFIO ([plugin](https://github.com/NVIDIA/kubevirt-gpu-device-plugin/tree/master), [GPU operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-kubevirt.html))
3. Prepare Kubevirt to use passthrough GPU ([doc](https://kubevirt.io/user-guide/compute/host-devices/#preparation-of-pci-devices-for-passthrough))
4. Try to launch a VM with GPU

**Additional context**:
- Followed [this post](https://unix.stackexchange.com/questions/728620/no-way-to-pass-to-virtual-machine-this-old-scsi-controller) and edited limits and rules.
- The GPUs appear allocatable in Kubernetes
![Image](https://github.com/user-attachments/assets/e11f0622-acdd-4195-83f1-d50c8ac29560)
- VMs without GPUs run fine.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.5.0
- Kubernetes version (use `kubectl version`): 1.28.4 with k3s
- VM or VMI specifications:
```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          gpus:
            - deviceName: "nvidia.com/TU104GL_TESLA_T4"
              name: gpu1
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk: {}
            name: cloudinitdisk
        resources:
          requests:
            memory: 4096Mi
      terminationGracePeriodSeconds: 0
      hostname: my-hostname-testvmw
      volumes:
      - containerDisk:
          image: test/debian-kubevirt:latest
          imagePullPolicy: Always
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user:
              name: debian
              groups: sudo
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
        name: cloudinitdisk
```
- Cloud provider or hardware configuration: AWS g4dn.metal
- OS (e.g. from /etc/os-release): Debian 12
- Kernel (e.g. `uname -a`): 6.1.0-33-cloud-amd64
- Install tools: [Ansible Galaxy role](https://galaxy.ansible.com/ui/standalone/roles/xanmanning/k3s/) for Kubernetes, ArgoCD specific app for Kubevirt
- Others: N/A

**Comment by victortoso** [comment]
> The GPUs appear allocatable in Kubernetes

For that, it is sufficient the device-plugin see the card in the Node. Which you have.

> VFIO_MAP_DMA failed: Cannot allocate memory

It is not an error I'm familiar with but it does not necessary imply the Pod needs more memory. I'm wondering if QEMU/Guest can actually access the device. Have you done the `unbind & bind` step from the [doc?](https://kubevirt.io/user-guide/compute/host-devices/#preparation-of-pci-devices-for-passthrough) I think `lsmod` in the host should help verify.

**Comment by nrogerarkhn** [comment]
As far as I understand, the unbind & bind step is to ensure the devices use vfio-pci, and it looks like it does:
```bash
root@ip-172-31-11-37 ~> lspci -nnk | rg -i "nvidia|vfio"
18:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
19:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
35:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
36:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
e7:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
e8:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
f4:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
f5:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nvidia_drm, nvidia
```
Furthermore, for a reason I don't understand, I don't have the `/sys/bus/pci/drivers/nvidia` path on the machine, so I cannot strictly follow the documentation.

Concerning the bot answer,

1. IOMMU is enabled
2. The module is loaded (see the `lspci` above)
3. I didn't have that part, so I added `iommu=pt` to my grub config but it didn't change anything about the error
4. According to the `lspci` above I think the GPUs have the correct driver binding
5. I think I didn't make a mistake, here's an excerpt from my Kubevirt config:
```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - HostDevices
      - ExpandDisks
      - ExperimentalVirtiofsSupport
      - GPU
      - DisableMDEVConfiguration
    permittedHostDevices:
      pciHostDevices:
      - externalResourceProvider: true
        pciVendorSelector: 10DE:1EB8
        resourceName: nvidia.com/TU104GL_TESLA_T4
```
6. All Nvidia-related pods are green, and I don't think the issue mentioned about Kubevirt's original plugin is relevant, but I might be wrong
7. I didn't extensively check about the kernel compatibility, to be fair
8. I didn't see anything relevant in the `dmesg`, except from some lines saying the GPUs are already bound to vfio-pci
