### ISSUE TITLE
arbitrary annotations not propagating beyond VM

### ISSUE THREAD

**Issue by ianb-mp** [kubevirt/kubevirt#14707]
**What happened**:

The arbitrary annotation in my VM manifest is not propagating to VMI or pod. I added an annotation like this:

```yaml
apiVersion: kubevirt.io/v1                                                                                                                                                                                          
kind: VirtualMachine                                                                                                                                                                                                
metadata:                                                                                                                                                                                                           
  annotations:                                                                                                                                                                                                      
    example.com/SpecialID: "12341234"
```

**What you expected to happen**:

Since PR https://github.com/kubevirt/kubevirt/pull/2627  it should be possible to include a arbitrary annotations and have them propagate to VMI and pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add any custom annotation to VM manifest
2. Deploy VM
3. Check annotations in resulting VMI and pod objects

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.4.0
- Kubernetes version (use `kubectl version`): v1.31.2+k0s
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
