### ISSUE TITLE
accessCredentials with sshPublicKey added to the root user even though disable_root: true

### ISSUE THREAD

**Issue by bataliero** [kubevirt/kubevirt#14727]
**What happened**:
When using accessCredentials with sshPublicKey in a VirtualMachinePool definition, the SSH keys are added to the root user even though disable_root: true.

**What you expected to happen**:
The SSH public keys defined in the accessCredentials section should be propagated to the `default` user specified in the cloud-init configuration when `disable_root: true` is set.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: generic-vm
spec:
  replicas: 1
  selector:
    matchLabels:
      kubevirt.io/vmPool: generic-pool
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmPool: generic-pool
    spec:
      runStrategy: Always
      dataVolumeTemplates:
        - metadata:
            name: vm-storage
          spec:
            pvc:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 40Gi
            source:
              pvc:
                name: base-rocky9-image
                namespace: default
      template:
        metadata:
          labels:
            kubevirt.io/vmPool: generic-pool
        spec:
          domain:
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: datavolumedisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - name: bridge-net
                  bridge: {}
            resources:
              requests:
                memory: 2G
          networks:
            - name: bridge-net
              multus:
                networkName: generic-bridge
          accessCredentials:
            - sshPublicKey:
                source:
                  secret:
                    secretName: ssh-key-secret
                propagationMethod:
                  noCloud: {}
          volumes:
            - dataVolume:
                name: vm-storage
              name: datavolumedisk
            - cloudInitNoCloud:
                userData: |
                  #cloud-config
                  runcmd:
                    - [systemctl, enable, --now, qemu-guest-agent]
                  disable_root: true
                  users:
                    - default
                  system_info:
                    default_user:
                      name: admin_user
                      groups: wheel
                      lock_passwd: false
                      shell: /bin/bash
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      passwd: <hashed-password>
              name: cloudinitdisk
```

Tested on `https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.5-20241118.0.x86_64.qcow2`

**Additional context**:

```
[root@vm-generic ~]# cat /root/.ssh/authorized_keys
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"NONE\" rather than the user \"root\".';echo;sleep 10;exit 142" ssh-ed25519 AAAAC3.... <user>
ssh-ed25519 AAAAC3.... <user2>
ssh-ed25519 AAAAC3.... <user3>
```

````
apiVersion: v1
kind: Secret
metadata:
  name: ssh-public-key
  # namespace: default
type: Opaque
stringData:
  keys.pub: |
ssh-ed25519 AAAAC3.... <user>
ssh-ed25519 AAAAC3.... <user2>
ssh-ed25519 AAAAC3.... <user3>
```


**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v1.5.0", GitCommit:"522b44c0ce8d1909618324cb083d69e5c7a0a234", GitTreeState:"clean", BuildDate:"2025-03-13T18:12:11Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.5.0", GitCommit:"522b44c0ce8d1909618324cb083d69e5c7a0a234", GitTreeState:"clean", BuildDate:"2025-03-13T19:53:21Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.4+k3s1
- VM or VMI specifications: (https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.5-20241118.0.x86_64.qcow2)
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): host of k3s kernel version 5.14.0-503.15.1.el9_5.x86_64
