### ISSUE TITLE
High virt-tail cpu usage in machines with serial port configured with getty

### ISSUE THREAD

**Issue by leleobhz** [kubevirt/kubevirt#14753]
**What happened**:
Machines that does have serial port auto attached and virtualized linux inside opens a getty session on serial port leads to high cpu usage on virt-tail container. Both EFI and BIOS Vms does have this behaviour, so firmware declaration does not appear to change the issue.

**What you expected to happen**:
virt-tail container do not costs about 8% of host CPU per vm

**How to reproduce it (as minimally and precisely as possible)**:

1) Yaml:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
spec:
  template:
    spec:
        devices:
          autoattachSerialConsole: true
        firmware:
          bootloader:
            bios:
              useSerial: true
```

2) On virtual machine:

```
cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-6.1.0-35-amd64 root=UUID=<redacted> ro console=tty0 console=ttyS0,115200n8
systemctl enable serial-getty@ttyS0.service
```

3) Obseve CPU usage on host
