### ISSUE TITLE
kubevirt cannot boot gentoo qcow2 image but qemu can

### ISSUE THREAD

**Issue by davidshen84** [kubevirt/kubevirt#14806]
**What happened**:
I can boot gentoo qcow2 image using qemu directly, but the kernel crashed when booting from kubevirt

**What you expected to happen**:
I can boot gentoo in kubevirt

**How to reproduce it (as minimally and precisely as possible)**:

- Download the gentoo qcow2 image from https://www.gentoo.org/downloads/
- Upload the image and create a ContainerDisk resource
  - `kubectl virt image-upload dv gentoo-dv --size=50Gi --image-path=/download/di-amd64-console-20250518T165514Z.qcow2 --uploadproxy-url=https://127.0.0.1:8443 --insecure --access-mode ReadWriteOnce --force-bind`
- Create the VM resource

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gentoo
  namespace: default
spec:
  runStrategy: Manual
  template:
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
        memory:
          guest: 8Gi
        features:
          smm:
            enabled: true
          acpi: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: gentoo-dv
              disk:
                bus: virtio
      volumes:
        - name: gentoo-dv
          dataVolume:
            name: gentoo-dv
```
- Start and attach to the VMI

**Additional context**:
I can see the boot menu and interact with it, but the kernel crashed soon after. It looks like Gentoo requires a very new EFI Bios image of OVMF_CODE_4M

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v1.5.1", GitCommit:"04b1fda82c3b1ec3f01298e5dd5f7a6468cac0fc", GitTreeState:"clean", BuildDate:"2025-05-06T06:51:44Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.5.1", GitCommit:"04b1fda82c3b1ec3f01298e5dd5f7a6468cac0fc", GitTreeState:"clean", BuildDate:"2025-05-06T08:27:02Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`): v1.31.4+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu WSL2 on Windows 11
- Kernel (e.g. `uname -a`): 5.15.167.4-microsoft-standard-WSL2
- Install tools: N/A
- Others: N/A
