### ISSUE TITLE
host model doesn't exist in cpu model labels

### ISSUE THREAD

**Issue by Yu-Jack** [kubevirt/kubevirt#14813]
**What happened**:
When starting a VM with specific `cpu.model`  from `host-model-cpu.node.kubevirt.io/{model_name}` in the node, the VM failed to start.

**What you expected to happen**:
The VM should start successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Before starting a VM, get the model name from `host-model-cpu.node.kubevirt.io/{model_name}` labels in the node
2. Start a VM with `cpu.model: {model_name}`
3. VM fails to start

The nodeSelector in the Pod is `cpu-model.node.kubevirt.io: {model_name}`, but that label doesn't exist in the node. 

**Additional context**:
Downstream issue: https://github.com/harvester/harvester/issues/8361

I checked the code base. https://github.com/kubevirt/kubevirt/blob/0bb85f4fc1f240ac35e80aee87446ebd6d50c5ea/pkg/virt-handler/node-labeller/node_labeller.go#L233-L301

I think we should add:

```diff
newLabels[kubevirtv1.CPUModelVendorLabel+n.cpuModelVendor] = "true"
newLabels[kubevirtv1.HostModelCPULabel+hostCpuModel.Name] = "true"
+ newLabels[kubevirtv1.CPUModelVendorLabel+hostCpuModel.Name] = "true"
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.4.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by Yu-Jack** [comment]
@Barakmor1 Hi,

What if we have these two nodes and we want to schedule it to the node A? As I know so far, it will be randomly scheduled to one of them with `host-model`. In that case, how do we schedule it to node A or B with `cpu.model`?

```yaml
# node A
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
host-model-cpu.node.kubevirt.io/EPYC-Rome: "true"
````

```yaml
# node B
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/EPYC-Rome: "true"
cpu-model.node.kubevirt.io/IvyBridge: "true"
cpu-model.node.kubevirt.io/IvyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Nehalem-IBRS: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/SandyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
cpu-model.node.kubevirt.io/Westmere-IBRS: "true"
host-model-cpu.node.kubevirt.io/EPYC-Genoa: "true"
````

**Comment by Yu-Jack** [comment]
Hi @Barakmor1,

What if we have these two nodes and we want to schedule it to the node A? As I know so far, it will be randomly scheduled to one of them with `host-model`. In that case, how do we schedule it to node A with only `cpu.model`?

```yaml
# node A
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
host-model-cpu.node.kubevirt.io/EPYC-Rome: "true"

# node B
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/EPYC-Rome: "true"
cpu-model.node.kubevirt.io/IvyBridge: "true"
cpu-model.node.kubevirt.io/IvyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Nehalem-IBRS: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/SandyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
cpu-model.node.kubevirt.io/Westmere-IBRS: "true"
host-model-cpu.node.kubevirt.io/EPYC-Genoa: "true"
````

**Comment by iholder101** [comment]
Hey @Yu-Jack!

In the [linked bug](https://github.com/harvester/harvester/issues/8361), I see you've configured your VM in the following way:
```yaml
spec:
  template:
    spec:
      domain:
        cpu:
          model: EPYC-Rome
```

And that the pod resulted with:
```yaml
  nodeSelector:
    cpu-model.node.kubevirt.io/EPYC-Rome: "true"
```

In the comment above, node B has a `cpu-model.node.kubevirt.io/EPYC-Rome: "true"` label.

Everything looks good to me. What am I missing?

In addition, please add the exact error that you're seeing and provide necessary logs (e.g. virt-controller, virt-launcher, etc) which would be helpful to debug this.

**Comment by Yu-Jack** [comment]
Hi @iholder101 

In that case, there are two nodes. User expects the VM is scheduled to node A, but it's scheduled node B due to `nodeSelector: cpu-model.node.kubevirt.io/EPYC-Rome: "true"`. That label doesn't exist in the node A. However, I'm trying to understand what user wants right now. 

However, I'm also wondering how it schedules the VM to the node A with a specified `cpu.model`.  In my view, I think `cpu.mode: EPYC-Rome` should work in the both nodes even though the host model in node A is `EPYC-Rome`.

```yaml
# node A
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
host-model-cpu.node.kubevirt.io/EPYC-Rome: "true"

# node B
cpu-model.node.kubevirt.io/Dhyana: "true"
cpu-model.node.kubevirt.io/EPYC: "true"
cpu-model.node.kubevirt.io/EPYC-IBPB: "true"
cpu-model.node.kubevirt.io/EPYC-Rome: "true"
cpu-model.node.kubevirt.io/IvyBridge: "true"
cpu-model.node.kubevirt.io/IvyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Nehalem: "true"
cpu-model.node.kubevirt.io/Nehalem-IBRS: "true"
cpu-model.node.kubevirt.io/Opteron_G3: "true"
cpu-model.node.kubevirt.io/Penryn: "true"
cpu-model.node.kubevirt.io/SandyBridge: "true"
cpu-model.node.kubevirt.io/SandyBridge-IBRS: "true"
cpu-model.node.kubevirt.io/Westmere: "true"
cpu-model.node.kubevirt.io/Westmere-IBRS: "true"
host-model-cpu.node.kubevirt.io/EPYC-Genoa: "true"
```
