### ISSUE TITLE
access to block hotplug volumes lost when cpuset changes for container

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/kubevirt#14825]
**What happened**:
CPU set changes, which can occur way later in pod lifecycle (potentially days later)
Can disrupt the block volume hotplug mechanism by reloading the systemd unit
(and thus reverting kubevirt's device allow list for the container)

**What you expected to happen**:
Hotplugged volumes consistently stay accessible in virt launcher
(resync in handler kind of achieves this with a huge delay)

**How to reproduce it (as minimally and precisely as possible)**:
This is reproducible in kubevirtci with 2 nodes (cordon ctrl plane for reproducing):
1. Create a non-QoS-Guaranteed VM
2. Hotplug a block PVC into the VM
3. Create a guaranteed pod with 2 CPUs (this will result in a cpuset change for the virt-launcher)
4. Attempt to read from the hotplugged block volume inside the virt launcher
```bash
bash-5.1$ head -c 10 /var/run/kubevirt/hotplug-disks/example-volume-hotplug
head: cannot open '/var/run/kubevirt/hotplug-disks/example-volume-hotplug' for reading: Operation not permitted
```

**Additional context**:
This can be reduced further to issuing a runtime update to the cpu set of the systemd unit
of the virt-launcher. On the node:
```bash
systemctl set-property --runtime crio-17f74e1bdb05666d72672f4cce004416f9232c089921cd12a3a443c4080ba1fa.scope AllowedCPUs=0,3-5
```
Which would reload the unit and revoke access to the block volume in the container, until the next domain resync.

<details>
<summary>+ Expand reproducer</summary>

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-test-tooling-cloudinit
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: alpine-test-tooling-cloudinit
        kubevirt.io/vm: alpine-test-tooling-cloudinit
        bad.io/really: huh
    spec:
      domain:
        devices:
          disks:
          - disk: {bus: virtio}
            name: disk0
          - disk: {bus: virtio}
            name: cloudinitdisk
        resources:
          requests: {memory: 512Mi}
          limits: {memory: 512Mi}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/alpine-with-test-tooling-container-disk:v1.3.0
          imagePullPolicy: IfNotPresent
        name: disk0
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh
            set -ex

            echo 'HELLO printed from cloud-init userdata'
            touch /root/bar.txt
        name: cloudinitdisk
```

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-volume-hotplug
spec:
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 1Gi
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-pvc
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  containers:
  - image: quay.io/centos/centos:stream9
    command: ["/bin/bash"]
    args: ["-c", "sleep 360000"]
    resources:
      limits:
        cpu: 2
        memory: 600M
      requests:
        cpu: 2
        memory: 600M
    name: test
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    volumeDevices:
    - name: mypvc
      devicePath: /dev/mydisk
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: simple-pvc
```
</details>

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
