### ISSUE TITLE
nodePlacement tolerations are not applied to VMIs

### ISSUE THREAD

**Issue by max06** [kubevirt/kubevirt#14831]
**What happened**:
Using a small rke2 cluster with 3 control-plane and 1 worker nodes I tried removing the limitations for VM workloads to make use of all 4 nodes.

For that, I patched the kubevirt-operator CR as described in the [documentation](https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement):

```yaml
spec:
  workloads:
    nodePlacement:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists

# for completeness, all other changes I did to the CR
  configuration:
    developerConfiguration:
      featureGates: []
    vmRolloutStrategy: LiveUpdate
  infra:
    nodePlacement:
      tolerations:
      - key: node-role.kubernetes.io/etcd
        operator: Exists
  workloadUpdateStrategy:
    workloadUpdateMethods:
    - LiveMigrate
```

**What you expected to happen**:
I expected (at least) new VMs to be deployed including these tolerations.

**How to reproduce it (as minimally and precisely as possible)**:
Install v1.5.1 as described in your quickstart guides. 
Either patch the operator CR before creation or after applying, add:

```yaml
spec:
  workloads:
    nodePlacement:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
```

Make sure virt-handler pods get deployed on the control-plane nodes. (I had to redeploy the operator to make that work!)

If necessary, disable the worker nodes by setting the node label `kubevirt.io/schedulable=false`.

Deploy a test vm - it avoids the control-plane nodes, becoming unschedulable.

Deploy a second test vm, adding

```yaml
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: node-role.kubernetes.io/etcd
          operator: Exists
```

The vm should be created on one of the control-plane nodes.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 

```text
Client Version: version.Info{GitVersion:"v1.5.0", GitCommit:"522b44c0ce8d1909618324cb083d69e5c7a0a234", GitTreeState:"clean", BuildDate:"2025-03-13T18:12:11Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.5.1", GitCommit:"04b1fda82c3b1ec3f01298e5dd5f7a6468cac0fc", GitTreeState:"clean", BuildDate:"2025-05-06T08:10:01Z", GoVersion:"go1.23.4 X:nocoverageredesign", Compiler:"gc", Platform:"linux/arm64"}
```

- Kubernetes version (use `kubectl version`): `v1.31.7+rke2r1`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Raspberry Pi 5 (16G) x4
- OS (e.g. from /etc/os-release): debian 12
- Kernel (e.g. `uname -a`): `6.6.51+rpt-rpi-2712`
- Install tools: N/A
- Others: N/A
