### ISSUE TITLE
[s390x] In VMI when spec.domain.memory.maxGuest is set, getting error "Memory hotplug is only available for x86_64 and arm64 VMs"

### ISSUE THREAD

**Issue by chandramerla** [kubevirt/kubevirt#14856]
In s390x memory hotplug is not supported, but in case if I create a NEW VMI (not hotplug) with spec.domain.memory.maxGuest set to some value, I'm getting error that Memory hotplug is only available for x86 and arm64. Actually as said above it is fresh VM creation, not really a hot plug.

**What happened**:

**What you expected to happen**:
This error should appear only when we really hot plug memory, not when creating a new VM. If maxGuest shouldn't be set the error should be different.

**How to reproduce it (as minimally and precisely as possible)**:
In s390x based cluster, in a VMI spec set some value to spec.domain.memory.maxGuest (same as spec.domain.memory.Guest or different - doesn't matter), getting above error.

**Additional context**:
kubevirt 1.5

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v1.5.0-78-gd053ac5c56", GitCommit:"d053ac5c5693177c43252b11992127c94e4aa817", GitTreeState:"clean", BuildDate:"2025-04-22T20:18:40Z", GoVersion:"go1.23.6 (Red Hat 1.23.6-2.el9_6) X:strictfipsruntime", Compiler:"gc", Platform:"darwin/arm64"}

- Kubernetes version (use `kubectl version`): N/A
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.3
WARNING: version difference between client (1.29) and server (1.32) exceeds the supported minor version skew of +/-1

- VM or VMI specifications: N/A

- Cloud provider or hardware configuration: s390x (IBM Z) VM
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by iholder101** [comment]
Thanks @chandramerla!

> I'm getting error that Memory hotplug is only available for x86 and arm64

Can you share the exact error you're seeing please?

**Comment by chandramerla** [comment]
> Thanks [@chandramerla](https://github.com/chandramerla)!
> 
> > I'm getting error that Memory hotplug is only available for x86 and arm64
> 
> Can you share the exact error you're seeing please?

I've added the error in the title ie., "Memory hotplug is only available for x86_64 and arm64 VMs"

Below is the yaml I used:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: example
  annotations:
    description: VM example
  labels:
    app: example
    os.template.kubevirt.io/fedora: 'true'
spec:
  runStrategy: Halted
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: example
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        memory:
          guest: 2Gi
          maxGuest: 2Gi
      hostname: example
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: 'quay.io/containerdisks/fedora'
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk

```
