### ISSUE TITLE
With a headless svc, no dns entry gets created

### ISSUE THREAD

**Issue by hu1buerger** [kubevirt/kubevirt#14934]
**What happened**:
dig of hostname.subdomain inside the vm returns an empty result

**What you expected to happen**:

i would expect a dns entry to be created when a headless svc exists and the vm can resolve it self (see #9760)

**How to reproduce it (as minimally and precisely as possible)**:
- deploy the yaml file in additional context
- then `virtctl ssh vm/vm` => then 
<details>
<summary> dig vm.testvm  log </summary>

```
ubuntu@vm:~$ dig vm.testvm

; <<>> DiG 9.18.30-0ubuntu0.24.04.2-Ubuntu <<>> vm.testvm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3244
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;vm.testvm.                     IN      A

;; AUTHORITY SECTION:
.                       30      IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2025061600 1800 900 604800 86400

;; Query time: 2 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jun 16 13:39:21 UTC 2025
;; MSG SIZE  rcvd: 113

ubuntu@vm:~$ 
```

</details>

**Additional context**:
there are no other svc, vms, vmis etc in that namespace. 
```
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  pvc:
    storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  source:
    http:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    subdomain: testvm
  name: vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        subdomain: testvm
    spec:
      hostname: vm
      subdomain: testvm
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 8Gi
      volumes:
      - dataVolume:
            name: vm
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            ssh_pwauth: True 
            password: passw0rd
            chpasswd: { expire: False }
        name: cloudinitdisk
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm1
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  pvc:
    storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  source:
    http:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
 # labels:
 #   subdomain: testvm
  name: vm1
spec:
  runStrategy: Always
  template:
#    metadata:
#      labels:
#        subdomain: testvm
    spec:
      hostname: vm1
      subdomain: testvm
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 8Gi
      volumes:
      - dataVolume:
            name: vm1
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            ssh_pwauth: True 
            password: passw0rd
            chpasswd: { expire: False }
        name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: testvm
spec:
  selector:
    subdomain: testvm
  #clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
```

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.5.0
- Kubernetes version (use `kubectl version`): v1.30.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by hu1buerger** [comment]
This is IMHO 1:1 of the documentation [see](https://kubevirt.io/user-guide/network/dns/)

**Comment by hu1buerger** [comment]
@dosu with `vm.testvm.namespace.svc.cluster.local.` i get an A record

**Comment by oshoval** [comment]
The scope of the feature didn't focus on it.
We tried to add the minimum (see please reason on release note of PR desc [2])
We added [1] only `subdomain.namespace.svc.cluster.local` to the search domains
addressing k8s bug https://github.com/kubernetes/kubernetes/issues/48019

However i do see it is mentioned on the docs, will need to recall.

As far as i remember, the VM inherits `/etc/resolv.conf` of the pod, that depends on the BM, and sometimes the entry that would, make your dig work `namespace.svc.cluster.local` is there and sometimes not, for example if there are already many entries, some will be dropped (FIFO).

Can you `cat /etc/resolv.conf ` in the VM please ?

Did you follow all those steps: (I believe so, after all, the full FQDN does work, `vm` is the relevant one, not `vm1`)
```
In order to have the DNS entry added by k8s,
a headless service in the same namespace of the VMIs should exists.
It should be named as the subdomain.
The service should have a selector matching the VMIs in the subdomain.
```

cc @rabin-io maybe have insights about it please

[1] https://github.com/kubevirt/kubevirt/pull/6508/commits/e595fb0ca3446d301f0a51c1aadd7619e93d9e0d#diff-6195f79775d647bf1326abb78839f0964a4d70461d2100fa2c7813def045e568R94
[2] https://github.com/kubevirt/kubevirt/pull/6508

**Comment by hu1buerger** [comment]
Sure

**Comment by hu1buerger** [comment]
@oshoval here is the resolv.conf

```
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
...

nameserver 127.0.0.53
options edns0 trust-ad
search testvm.<namespace>.svc.cluster.local <namespace>.svc.cluster.local svc.cluster.local cluster.local default.svc.cluster.local
```

i already changed the subdomain and service

**Comment by oshoval** [comment]
Thanks

Meanwhile you are not blocked right ?
`vm.testvm.namespace.svc.cluster.local` and `vm` lookups should work

Need to discuss what is the action item, as the original feature was to support the FQDN not `vm.testvm`
it might be a regression, but not sure if it is related yet to kubevirt or k8s, and how we will address it (maybe docs need to be changed, but yet to decide).

**Comment by hu1buerger** [comment]
Thanks for the update. Unfortunately, this (bug|regression|feature|.*) blocks my current workflow — I rely on transparently resolving VM hostnames without needing to know the FQDN, as I deploy across multiple clusters that each have different namespaces and cluster domains. Having to explicitly define or be aware of the FQDN adds significant complexity and reduces the portability of my deployments.

Is there a possible workaround or configuration that could maintain the previous resolution behavior?

**Comment by oshoval** [comment]
sorry, not something i know about by heart yet without checking
will updated once we do

maybe it is related to coreDNS `fallthrough`, but need to check deeper

EDIT - found something related to `ndots`, processing and will update

**Comment by oshoval** [comment]
Hi
Can you please try
`dig +search +ndots=2 vm.testvm` ?
if it works can you please try to add `options ndots:2` to the `/etc/resolv.conf` ?
and then both 
`dig +search vm.testvm`
and `nslookup vm.testvm` should work

As far as i understand, since ndots default is 1, it doesnt append search path if there is 1 dot already in the query.

Note that the virt-launcher pod has `ndots:5` but the guest doesnt inherit it.
So far it seems it depends on the local resolver.

Note please that the documentation is older than the original PR which fixes subdomain as a whole
https://github.com/kubevirt/kubevirt/pull/6508 (2021)
and the user-guide was updated on 2020 https://github.com/kubevirt/user-guide/pull/316/files#diff-b45ea3ae30a12634dcfe94c7cf2e051a762663178758d302baea8ed271f8a38eR63

Some interesting reading about it:
https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
https://socketdaddy.com/kubernetes/understanding-ndots-in-dns-configurations/

You can try this workaround please (use cloud-init to set ndots)
It might depend on the guest OS, tried with fedora.
Add please this volume (or change the userData you already have)
```
      volumes:
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            bootcmd:
            - nmcli connection modify "System eth0" ipv4.dns-options "ndots:2"
            - nmcli connection up "System eth0"
        name: cloudinitdisk
```

Full manifest:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: oper-test-vm
  name: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm
    spec:
      subdomain: mysubdomain
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: ""
        resources:
          requests:
            memory: 1024Mi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:20250706_c5e2a979ac
          imagePullPolicy: IfNotPresent
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            bootcmd:
            - nmcli connection modify "System eth0" ipv4.dns-options "ndots:2"
            - nmcli connection up "System eth0"
        name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: mysubdomain
spec:
  selector:
    kubevirt.io/vm: fedora-vm
  clusterIP: None
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
```
