### ISSUE TITLE
Unable to configure kubevirt.spec.configuration.architectureConfiguration for s390x

### ISSUE THREAD

**Issue by chandramerla** [kubevirt/kubevirt#14953]
**What happened**:

Unable to configure kubevirt.spec.configuration.architectureConfiguration for s390x

**What you expected to happen**:

In kubevirt.spec.configuration.architectureConfiguration, s390x section is missing unlike other architectures. This doesn't allow a user of s390x cluster to do architecture configuration like machineType, emulatedMachines & ovmfPath.

So similar to other architectures, better we allow configuring architecture related fields like machineType, emulatedMachines & ovmfPath for s390x as well.

**Additional context**:
As shown below configuration available for other architectures, but not for s390x. All these values are hardcoded in the code for s390x, than available in the KubeVirt configuration.
```
apiVersion: kubevirt.io/v1
kind: KubeVirt
spec:
  configuration:
    architectureConfiguration:
      amd64:
        emulatedMachines:
        - q35*
        - pc-q35*
        machineType: pc-q35-rhel9.6.0
        ovmfPath: /usr/share/OVMF
      arm64:
        emulatedMachines:
        - virt*
        machineType: virt-rhel9.6.0
        ovmfPath: /usr/share/AAVMF
```

**Environment**:
- KubeVirt version (use `virtctl version`):
$virtctl version
Client Version: version.Info{GitVersion:"v1.5.0-78-gd053ac5c56", GitCommit:"d053ac5c5693177c43252b11992127c94e4aa817", GitTreeState:"clean", BuildDate:"2025-04-22T20:18:40Z", GoVersion:"go1.23.6 (Red Hat 1.23.6-2.el9_6) X:strictfipsruntime", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{GitVersion:"v1.5.1-69-g0eba961584", GitCommit:"0eba961584aa59fab5b93a19e5616e2bb6cb3285", GitTreeState:"clean", BuildDate:"2025-06-04T06:20:33Z", GoVersion:"go1.23.6 (Red Hat 1.23.6-2.el9_6) X:strictfipsruntime", Compiler:"gc", Platform:"linux/s390x"}

- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: s390x based cluster
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
