### ISSUE TITLE
No support for ipv6 dnsConfig nameserver addresses

### ISSUE THREAD

**Issue by BeefaloKing** [kubevirt/kubevirt#15011]
**What happened**:
Unable to add ipv6 nameservers to /etc/resolv.conf. IPv4 addresses work just fine.

**What you expected to happen**:
Both IPv4 and IPv6 nameservers to be accepted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with the following spec
```
spec:
  dnsConfig:
    nameservers:
      - '12.34.56.78'
      - 'a2c6:7638:979c:a8fa:7b5b:b2a9:ba87:3f46'
```

Note that only the IPv4 nameserver will be added to /etc/resolve.conf.

**Additional context**:
Looks like the regex here only accepts IPv4 addresses. https://github.com/kubevirt/kubevirt/blob/f8ec3b41426cf6df0eaba43447b39fd0b6dbd1da/pkg/network/dns/resolveconf.go#L42

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
