### ISSUE TITLE
DataVolumeTemplates doesn't copy PVC source to created DataVolume

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#1507]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When creating a Virtual Machine using a DataVolumeTemplates, the created Data Volume does not pick up a pvc 'source' and thus doesn't trigger the creation of the cloner pods.

**What you expected to happen**:
The created DV contains the pvc source from the Template.

**How to reproduce it (as minimally and precisely as possible)**:
Apply this yaml file:
```yaml
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: test
  name: test
spec:
  dataVolumeTemplates:
  - metadata:
      name: vm-test-dv-01
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 13224673
      source:
        pvc:
          name: template-test-dv-01
          namespace: default
    status: {}
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: test
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            volumeName: test-datavolume
        machine:
          type: q35
        resources:
          requests:
            memory: 64Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: vm-test-dv-01
        name: test-datavolume
status: {}
```
The created DV yaml looks like this:
```yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  annotations:
    kubevirt.io/owned-by: virt-controller
  clusterName: ""
  creationTimestamp: 2018-09-12T18:59:23Z
  generation: 1
  labels:
    kubevirt.io/created-by: f6c06ae0-b6bd-11e8-b14c-525500d15501
  name: vm-test-dv-01
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: test
    uid: f6c06ae0-b6bd-11e8-b14c-525500d15501
  resourceVersion: "30499"
  selfLink: /apis/cdi.kubevirt.io/v1alpha1/namespaces/default/datavolumes/vm-test-dv-01
  uid: f6c16fa7-b6bd-11e8-b14c-525500d15501
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "13224673"
  source: {}
status: {}
```
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.8.0-16+8112d64eda7255-dirty", GitCommit:"8112d64eda725594210ca7f0255a1343b6d4904e", GitTreeState:"dirty", BuildDate:"2018-09-06T12:38:00Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.8.0-16+8112d64eda7255-dirty", GitCommit:"8112d64eda725594210ca7f0255a1343b6d4904e", GitTreeState:"dirty", BuildDate:"2018-09-06T12:38:00Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
- VM or VMI specifications:
See reproducer.
- Cloud provider or hardware configuration:
N/A
- OS (e.g. from /etc/os-release):
kubevirtci development environment.
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
CDI version: latest master (that includes support for data volumes cloning)
