### ISSUE TITLE
PodPresets for devices.disk and volumes

### ISSUE THREAD

**Issue by ant31** [kubevirt/kubevirt#1528]
/kind enhancement

I've wanted to create presets with images, e.g:
```
kind: VirtualMachine
metadata:
   labels:
       kubespray.io/image: ubuntu-1604
```
and 
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstancePreset
metadata:
  generation: 1
  name: image-ubuntu-1604
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
          name: registrydisk
          volumeName: registryvolume
  selector:
    matchLabels:
      kubespray.io/image: ubuntu-1604
  volumes:
  - name: registryvolume
    registryDisk:
      image: quay.io/kubespray/vm-ubuntu-1604:latest
```

I would expect to have a merge and the disk and volume appended to the VM spec
