### ISSUE TITLE
virtctl vnc fails to quick if VM is running but is not

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1538]
/kind bug

**What happened**:
VMI in an error condition:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-09-24T07:37:28Z
    message: 'server error. command Launcher.Sync failed: virError(Code=1, Domain=10,
      Message=''internal error: process exited while connecting to monitor: 2018-09-24T07:37:28.537019Z
      qemu-system-x86_64: -drive file=/var/run/kubevirt-private/vmi-disks/rootvolume/disk.img,format=raw,if=none,id=drive-ua-rootdisk:
      Could not open ''/var/run/kubevirt-private/vmi-disks/rootvolume/disk.img'':
      Permission denied'')'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized
  interfaces:
  - ipAddress: 172.17.0.13
  nodeName: localhost
  phase: Running
```

and this fails:

```
$ virtctl vnc node
I0924 09:36:43.536733    5957 vnc.go:119] connection timeout: 1m0s
$
```

The bug is that this fails right away, it does not fail after 1m0s (as it's stated).

**What you expected to happen**:
That it waits 1min0s before it fails.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.8.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
