### ISSUE TITLE
virtctl console fails if VM is marked as running but is not

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1539]
/kind bug

**What happened**:

```
$ virtctl console node
Successfully connected to node console. The escape sequence is ^]
                                                                 Virtual Machine's /var/run/kubevirt-private/79f2438a-bfcc-11e8-b6af-5254000b34fc/virt-serial0 socket is currently unavailable
```

when a VMI is in this state:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-09-24T07:37:28Z
    message: 'server error. command Launcher.Sync failed: virError(Code=1, Domain=10,
      Message=''internal error: process exited while connecting to monitor: 2018-09-24T07:37:28.537019Z
      qemu-system-x86_64: -drive file=/var/run/kubevirt-private/vmi-disks/rootvolume/disk.img,format=raw,if=none,id=drive-ua-rootdisk:
      Could not open ''/var/run/kubevirt-private/vmi-disks/rootvolume/disk.img'':
      Permission denied'')'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized
  interfaces:
  - ipAddress: 172.17.0.13
  nodeName: localhost
  phase: Running
```

**What you expected to happen**:
Console does nto connect while the VM is in a bad state OR it waits until it's good

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.8.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
