### ISSUE TITLE
Custom DHCP Options

### ISSUE THREAD

**Issue by gageorsburn** [kubevirt/kubevirt#1579]
As a virtual network operator, I want to be able to pass custom dhcp arguments such as `dhcp.OptionTFTPServerName` so that virtual network appliances will be able to load configuration. An extendable solution should be implemented so that any dhcp options that do not interfere with what kubevirt interface setup requires.

As an example the api could look like,

```
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: registrydisk
        volumeName: registryvolume
      interfaces:
      - bridge: {}
        name: default
        dhcpOptions: 
        - dhcpCode: 150
           value: tftp.default.svc.cluster.local
```
