### ISSUE TITLE
Kubevirt 0.8.0 virt-handler DS only run Pods in computes nodes when deployed in OpenShift

### ISSUE THREAD

**Issue by jtudelag** [kubevirt/kubevirt#1581]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

After deploying kubevirt 0.8.0 on an OCP 3.10.45 cluster deployed on AWS,  virt-handler DS Pods were only running in compute Nodes.

```
 oc get ds
NAME           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
virt-handler   4         2         2         2            2           <none>          2h
```

I would say the main reason is that there is a default node selector in the master-config.yaml. This could be avoided by having  kube-system annotated with:
```
openshift.io/node-selector: ""
```
Which I dont think is the right solution. For OpenShift deployments, I would create a separated Namespace: "kube-virt" for example, with this annotation in place to avoid this situation. The rest of "privileged" namespaces in OCP such as openshift-node, openshift-infra, etc, have this annotation by default.

```
 oc export project kube-system
Command "export" is deprecated, use the oc get --export
apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c5,c0
    openshift.io/sa.scc.supplemental-groups: 1000020000/10000
    openshift.io/sa.scc.uid-range: 1000020000/10000
  creationTimestamp: null
  name: kube-system
spec:
  finalizers:
  - kubernetes
  - openshift.io/origin
status:
  phase: Active
```

**What you expected to happen**:

The virt-handler DS to have as many replicas as nodes in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy kubevirt 0.8.0 (I bet any kubevirt version would behave the same) on an OCP 3.10.45 cluster, with a default project NodeSelector set in the master.config.yaml

```
....
projectConfig:
  defaultNodeSelector: node-role.kubernetes.io/compute=true
  projectRequestMessage: ''
  projectRequestTemplate: ''
.....
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.8.0
- OpenShift version (use `kubectl version`): 3.10.45
- VM or VMI specifications:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): RHEL 7.5
- Install tools: https://kubevirt.io/user-guide/#/installation/README
