### ISSUE TITLE
VM fails to start with "XML error: Memory size must be specified via <memory> or in the <numa> configuration"

### ISSUE THREAD

**Issue by fromanirh** [kubevirt/kubevirt#1585]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I'm trying to run a EL7.5 VM for benchmark purposes. The startup fails with the error reported above

**What you expected to happen**:
The VM starts

**How to reproduce it (as minimally and precisely as possible)**:
I used this YAML:

```  
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: rhel7.5
  name: rhel-75-pbench
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/os: rhel7.5
    spec:
      resources:
        requests:
          memory: 2G
      machine:
        type: "q35"
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
            volumeName: rootvolume
      terminationGracePeriodSeconds: 0
      volumes:
      - name: rootvolume
        persistentVolumeClaim:
          claimName: rhel-75-pbench-pvc
```  

seems consistent with the example in https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vm-template-rhel7.yaml

**Anything else we need to know?**:
I'm running kubevirt on top of https://www.okd.io/ (3.10) on top of RHEL7.5 (bare metal provisioning)
Presets as per https://github.com/fabiand/common-templates seems to be unrelated

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.8.0", GitCommit:"6165ead7201d8b96946fdfcfb026e44b86d3d980", GitTreeState:"clean", BuildDate:"2018-09-05T15:38:18Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.9.0-alpha.1", GitCommit:"de6e6c0e25bfdc8b1fb36e401da49f6e786ce875", GitTreeState:"clean", BuildDate:"2018-09-27T07:44:26Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-21T21:02:15Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-21T21:02:15Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
see above

- Cloud provider or hardware configuration:
bare metal.

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"

- Install tools:
ansible playbook as per okd.io instructions
other installed components:
CDI 1.2.0
hostpath-provisioner 2ee4064d4d65

**Comment by rmohr** [comment]
@fromanirh so there is definitely a bug. The message you get is total garbage, since it should fail much earlier. The reason you get this error is that the `resources` section is wrong. It needs to be under `spec.domain`:

```yaml
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: rhel7.5
  name: rhel-75-pbench
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/os: rhel7.5
    spec:
      machine:
        type: "q35"
      domain:
        resources:
          requests:
            memory: 2G
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
            volumeName: rootvolume
      terminationGracePeriodSeconds: 0
      volumes:
      - name: rootvolume
        persistentVolumeClaim:
          claimName: rhel-75-pbench-pvc
```

In your case the `resources` section gets silently removed during the post and then there is no memory requested.
