### ISSUE TITLE
Set default label on VirtualMachine

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1686]
/kind enhancement

**What happened**:
Trying to expose a VM using a service using `kubectl`
Currently it is not possible to use the service creation feature of `kubectl` with VMs, as we do not set the default labels `kubectl` is using (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/generate/versioned/service_basic.go#L238-L242).

**What you expected to happen**:
To be able to use this stcok tool to expose ports of my vm

**How to reproduce it (as minimally and precisely as possible)**:
Try:
```
$ kubectl create service nodeport my-vm --tcp=5678:8080
```

**Anything else we need to know?**:
The create command is usnig some stock labels which we might want to add to our VirtualMachine as well in order to let them be propagated to the pod, which would then allow a user to use kubectl create.

This might eliminate the need for virtctl expose.

**Comment by fabiand** [comment]
The labels are applied by "tooling" thus kubectl is doing it itself, it's not by infrastructure. it's a convention, not enforced.

because in kubectl the generators are setting it, for us the generator are templates, thus the templates should be setting it.

Infrastructure has no requirement to add these labels, but it's the tooling and tooling integration.

**Comment by rmohr** [comment]
@fabiand the code you point to adds a label to the service. Is that what you meant? From your description it looks like you want to have some "default" labels on the VMI/Pod?

**Comment by fabiand** [comment]
> @fabiand the code you point to adds a label to the service. Is that what you meant? 

Yes, kubectl is setting a `select` on the service it creates.

> From your description it looks like you want to have some "default" labels on the VMI/Pod?

… we should set the correct label on our VM pods in order to let these services (above) be selecting our (vm) pods.

**Comment by rmohr** [comment]
@fabiand What I want to get at is that I am not aware of any "default" labels which would be added to a pod. If there are no labels on creation time on the pod, then you can't use `kubectl expose` either.

If I deploy this yaml:
```
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

I get that response:

```bash
$ kubectl expose pods task-pv-pod
error: couldn't retrieve selectors via --selector flag or introspection: the pod has no labels and cannot be exposed
See 'kubectl expose -h' for help and examples.
```

So kubectl does nothing. If you add labels to `spec.template.metadata.labels` on e.g. a `Deployment`, or on a `VirtualMachine` they will be propagated to the pod in a similar way. Sadly `kubectl` explicitly understands all resources like `Deployment`. If we would have labels it would still not work to use `kubectl expose` on vms directly.
