### ISSUE TITLE
cross namespace cloning doesnt work for datavolumes

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1747]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
create a vm with datavolume template trying to clone a pvc from another namespace

**What you expected to happen**:
vm started with a new pvc created as a clone of the one specified in spec

**How to reproduce it (as minimally and precisely as possible)**:
create the following yaml
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  generation: 1
  name: sleepy-rulo
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
      name: sleepy-rulo-vol0
    spec:
      pvc:
        accessModes:
       - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        pvc:
          name: rhel-8.0-beta-1-x86_64-kvm.qcow2
          namespace: golden
    status: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: sleepy-rulo
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            volumeName: sleepy-rulo-vol0
          - cdrom:
              bus: sata
            name: cloudinitdisk
            volumeName: cloudinitvolume
          interfaces:
          - bridge: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: sleepy-rulo-vol0
        name: sleepy-rulo-vol0
      - cloudInitNoCloud:
          userData: |
           #cloud-config
            hostname: sleepy-rulo
            ssh_pwauth: True
            disable_root: false
        name: cloudinitvolume
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
