### ISSUE TITLE
Allow setting attributes like `snapshot` and `cache` when using a PersistentVolumeClaim

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#184]
At the moment virt-handler is completely overriding the `PersistentVolumeClaim` section.

So a transformation of

```yaml
      disks:
      - type: network
        snapshot: external
        device: disk
        driver:
          name: qemu
          type: raw
          cache: none
        source:
          host:
            name: iscsi-demo-target
            port: "3260"
          protocol: iscsi
          name: iqn.2017-01.io.kubevirt:sn.42/2
        target:
          dev: vda
```

to a volume claim is currently not possible.
