### ISSUE TITLE
DHCP server does not work because VM has the wrong mac address with canal CNI

### ISSUE THREAD

**Issue by justinbarrick** [kubevirt/kubevirt#1850]
It appears that the DHCP server is not able to issue leases because the mac address assigned to the VM is not actually set.

**What happened**:

DHCP failed to get a lease:

```
Starting network...
udhcpc (v1.23.2) started
Sending discover...
Sending discover...
Sending discover...
Usage: /sbin/cirros-dhcpc <up|down>
No lease, failing
WARN: /etc/rc3.d/S40-network failed
```

Also notice that the Mac address is not what I have configured: `52:54:00:93:17:63`

```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 52:54:00:1F:59:33  
          inet6 addr: fe80::5054:ff:fe1f:5933/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:24 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2376 (2.3 KiB)  TX bytes:1332 (1.3 KiB)
```

**What you expected to happen**:

DHCP should get a lease.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  name: testvm
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          volumeName: containervolume
          disk:
            bus: virtio
        - name: cloudinitdisk
          volumeName: cloudinitvolume
          disk:
            bus: virtio
      interfaces:
      - name: default
        bridge: {}
        macAddress: "52:54:00:93:17:63"
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containervolume
      containerDisk:
        image: kubevirt/cirros-registry-disk-demo
    - name: cloudinitvolume
      cloudInitNoCloud:
        userDataBase64: SGkuXG4= 
```

Run it and connect to the console:

```
kubectl apply -f vm.yaml
virtctl console testvm
```
