### ISSUE TITLE
Live migrations fail when VMI has cloud-init user data defined

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1865]
/kind bug

**What happened**:

Migrating a VMI that defines cloud-init userdata fails. The failure appears to be occurring from within libvirt.  

I believe this worked correctly when migrations were first introduced. I think this may be related to some of the libvirt changes that occurred recently. We recently updated the libvirt packages in our virt-launcher container from 4.2.0 to 4.10.0 which could be related. 

**How to reproduce it (as minimally and precisely as possible)**:

using this VMI

```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: vmi-ephemeral
  name: vmi-ephemeral
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
        volumeName: registryvolume
      - disk:
          bus: virtio
        name: cloudinitdisk
        volumeName: cloudinitvolume
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/cirros-container-disk-demo:devel
    name: registryvolume
  - cloudInitNoCloud:
      userData: |
        #!/bin/sh

        echo 'printed from cloud-init userdata'
    name: cloudinitvolume
```

and then migrating with this migration job.
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceMigration
metadata:
  creationTimestamp: null
  name: migration-job
spec:
  vmiName: vmi-ephemeral
status: {}
```

The migration job will fail and report a libvirt error.
