### ISSUE TITLE
Edit role should be able to access the kubevirt subresource

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#1937]
# Bug
CI is failing in [kubevirt-ansible](https://github.com/kubevirt/kubevirt-ansible/pull/536) an rbac test that checks if the `edit` role has `get` access on the kubevirt subresource.  I confirmed this is also happening locally.  Deploy kubevirt with the kubevirt-operator, login to a user with edit permissions, then `kubectl get apiservices v1alpha2.subresources.kubevirt.io`

After adding this ClusterRole to edit, it works. 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    kubevirt.io: ""
  name: test-subresource
rules:
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - create
  - update
```

 /kind bug
