### ISSUE TITLE
dataVolumeTemplates are broken

### ISSUE THREAD

**Issue by gites** [kubevirt/kubevirt#1940]
**Is this a BUG REPORT**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Getting the following errors when deploying VM with `dataVolumeTemplates`
```
kubectl create -f vm5-ubuntu.yaml 
service/vm5-ubuntu unchanged
Error from server (Invalid): error when creating "vm5-ubuntu.yaml": admission webhook "virtualmachine-validator.kubevirt.io" denied the request: spec.dataVolumeTemplates.spec.resizeTo in body is a forbidden property, spec.dataVolumeTemplates.status in body is required

```

vm5-ubuntu.yaml 
```yaml
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  name: vm5-ubuntu
spec:
  running: true
  template:
    metadata:
      labels:
        guest: vm5-ubuntu
        kubevirt.io/size: medium
    spec:
      domain:
        devices:
          disks:
            - name: vm5-ubuntu-datavolume1
              volumeName: vm5-ubuntu-datavolume1
              disk:
                bus: virtio
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                bus: virtio
      volumes:
        - dataVolume:
            name: vm5-ubuntu-datavolume1
          name: vm5-ubuntu-datavolume1
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: root
              chpasswd: { expire: False }
              ssh_pwauth: True
  dataVolumeTemplates:
    - metadata:
        name: vm5-ubuntu-datavolume1
      spec:
        resizeTo: max 
        source:
          http:
            url: http://image-repo.default/bionic-server-cloudimg-amd64.img
        pvc:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "55Gi"
```
**What you expected to happen**:

Proper volume should be created and attached to the VM.

**How to reproduce it (as minimally and precisely as possible)**:
Try to create VM from yaml file posted above.

**Anything else we need to know?**:

Everything is ok when I separately create `DataVolume` and attach it to the VM.
```yaml
---
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: vm5-ubuntu-datavolume1
spec:
  resizeTo: max
  source:
      http:
         url: "http://image-repo.default/bionic-server-cloudimg-amd64.img"
  pvc:
    storageClassName: "rook-ceph-block"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 55Gi

```
The `spec.resizeTo` filed for `DataVolume` was added in `containerized-data-importer`  `v1.4.0`

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.12.0", GitCommit:"6dd9e09dc172387422fa454eda893e987bc213e9", GitTreeState:"clean", BuildDate:"2019-01-11T18:26:11Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.12.0", GitCommit:"6dd9e09dc172387422fa454eda893e987bc213e9", GitTreeState:"clean", BuildDate:"2019-01-11T18:26:11Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
Posted above.

- Cloud provider or hardware configuration:
On prem hardware.

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux dev-wac-s1 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
