### ISSUE TITLE
fedora-container-disk does not fully apply cloudinit with multus

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1943]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
deploy a simple manifest using fedora-container-disk and cloudinit content with runcmds containing ip address commands ( to set a secondary nic provided through multus ) statically 
the runcmds dont work

**What you expected to happen**:
the runcmd work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the same manifest using old fedora-registry-disk container images properly launches the indicated command 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.12.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by karmab** [comment]
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: fedora1
  name: fedora1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
            volumeName: containervolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
          interfaces:
          - bridge: {}
            name: default
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containervolume
        containerDisk:
          image: docker.io/kubevirt/fedora-cloud-registry-disk-demo:latest
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
            - echo ftw > /ftw.txt
        name: cloudinitvolume

**Comment by karmab** [comment]
here s a sample yml

```
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: fedora1
  name: fedora1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
            volumeName: containervolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
          interfaces:
          - bridge: {}
            name: default
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containervolume
        containerDisk:
          image: docker.io/kubevirt/fedora-cloud-registry-disk-demo:latest
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
            - echo ftw > /ftw.txt
        name: cloudinitvolume
```
