### ISSUE TITLE
Required API parameters could be empty

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/kubevirt#1990]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
When creating a `VirtualMachine` object and sending following `spec`:
```yaml
spec:
  running: false
  template:
    spec: {}
```

It fails, because `domain` is required for `VirtualMachineInstanceSpec`. So when we add an empty `domain` spec, it complains, that `devices` are required parameter, when we add also empty `devices` parameter, it succeed:

```yaml
spec:
  running: false
  template:
    spec:
      domain:
        devices: {}
```

**What you expected to happen**:
Either we should not accept empty required parameters or `devices` and `domain` parameters shouldn't be required.

**How to reproduce it (as minimally and precisely as possible)**:
Create VM with following spec:

```yaml
spec:
  running: false
  template:
    spec:
      domain:
        devices: {}
```

It succeed with empty devices, but devices are required parameter.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.13
- Kubernetes version (use `kubectl version`): 
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by pkliczewski** [comment]
@fabiand @stu-gott Any thoughts?

**Comment by fabiand** [comment]
Hm. Low priority enhancement?

@davidvossel ?

**Comment by davidvossel** [comment]
Is there a use-case for having a VMI without any devices? If so, then it shouldn't be required. If not, then we should ensure devices is both required and not empty.

**Comment by mmazur** [comment]
@davidvossel this came up when trying to change vm state with ansible modules. Doing something like this:

```
    - name: shutdown test-working VM
      kubevirt_vm:
        state: stopped
        name: test-working
        namespace: default
```

won't ever have any actual devices or anything in the k8s api call. In such a case the only really required part is `spec.running` and the whole of `spec.template` could be optional. However that's not the case.

So the question here is: which parts of `spec.template` should we really need to specify when all we're interested in is starting/stopping a vm?
