### ISSUE TITLE
404 when using virtctl console to access VM

### ISSUE THREAD

**Issue by bharatnc** [kubevirt/kubevirt#2031]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

I deployed a VM and tried to do `virtctl console <vm-name>`.

Got this error message:  `Can't connect to websocket (404): 404 page not found`

**What you expected to happen**:

Connect to the VM - serial terminal should open up.

**How to reproduce it (as minimally and precisely as possible)**:

Use this manifest and put it inot a file called `vm.yaml`.

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels: 
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              volumeName: containervolume
              disk:
                bus: virtio
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containervolume
          containerDisk:
            image: kubevirt/cirros-registry-disk-demo
        - name: cloudinitvolume
          cloudInitNoCloud:
            userDataBase64: SGkuXG4= 
```
```bash
kubectl apply -f . vm.yaml 

virtctl console testvm
```

Using minikube kubernetes cluster as the test environment: minikube version: v0.34.1.
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): GitVersion:"v0.14.0"
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications: provided above -  v1alpha3
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): Mac OS Sierra
- Kernel (e.g. `uname -a`): Darwin Kernel Version 16.7.0
- Install tools:
- Others:
minikube version: minikube version: v0.34.1
