### ISSUE TITLE
Use API server aggregation

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#205]
With https://github.com/kubernetes/sample-apiserver and https://github.com/kubernetes/apiserver basically functional, we can start transferring our virt-api server to an aggregate apiserver.

We still have to figure out some details:
 * What exactly does it support
 * Validation
 * ...

**Comment by fabiand** [comment]
Yes, this is surely the right long term direction.

I guess this is impacted by the availability of the required support in K8s.

**Comment by fabiand** [comment]
Just came across this https://github.com/kubernetes-incubator/apiserver-builder

**Comment by fabiand** [comment]
Let me also reference https://docs.google.com/document/d/1y16jKL2hMjQO0trYBJJSczPAWj8vAgNFrdTZeCincmI/edit# which has an extensive comparison.

**Comment by fabiand** [comment]
@stu-gott there seems to be a way to avoid TLS, see https://github.com/kubernetes/apiextensions-apiserver/blob/master/artifacts/example/apiservice.yaml :

```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.apiextensions.k8s.io
spec:
  insecureSkipTLSVerify: true
...
```
