### ISSUE TITLE
kvm, tun and vhost-net resources are not reported after kubelet restart

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#2098]
/kind bug

**What happened**:

After `systemctl restart kubelet` (or `systemctl restart origin-node` on OpenShift), `kvm`, `tun` and `vhost-net` resources are reported empty.

**What you expected to happen**:

Those resource should keep their original value.

**How to reproduce it**:

Prepare the cluster:

```shell
make cluster-up
make cluster-sync
```

List node resources:

```shell
./cluster/kubectl.sh get nodes -o yaml
```

```yaml
...
    allocatable:
      cpu: "5"
      devices.kubevirt.io/kvm: "110"
      devices.kubevirt.io/tun: "110"
      devices.kubevirt.io/vhost-net: "110"
      hugepages-1Gi: "0"
      hugepages-2Mi: 128Mi
      memory: 4679260Ki
      pods: "110"
...
```

Restart kubelet:

```shell
./cluster/cli.sh ssh node01 'sudo systemctl restart kubelet'
```

After a while, list node resources again:

```shell
./cluster/kubectl.sh get nodes -o yaml
```

```yaml
...
    allocatable:
      cpu: "5"
      devices.kubevirt.io/kvm: "0"
      devices.kubevirt.io/tun: "0"
      devices.kubevirt.io/vhost-net: "0"
      hugepages-1Gi: "0"
      hugepages-2Mi: 128Mi
      memory: 4679260Ki
      pods: "110"
...
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version: used master branch
- Cloud provider or hardware configuration: local kubevirtci, tested with os-3.11.0-crio and k8s-multus-1.13.3
