### ISSUE TITLE
get the vmi status

### ISSUE THREAD

**Issue by majorinche** [kubevirt/kubevirt#2110]
hello
    how can i custom define the output of oc get vmi
like following, we have 5 items: NAME,AGE,PHASE,IP and NODENAME, but i'd like to add more item.

[root@infra1 ~]# oc get vmi
NAME      AGE       PHASE     IP            NODENAME
ceshi     8m        Running   10.129.1.51   master1.sonic.com

in which code file i need to modify

thank you
majorin

**Comment by rmohr** [comment]
Hi @majorinche, what you see there is configured by us server-side. You can change it on your running deployment if you like. When updating KubeVirt you will always have to perform that custom step though. To add more fields, do something like this:

```
kubectl edit customresourcedefinitions virtualmachineinstances.kubevirt.io
```

You can change this section so that it suits your needs:

```yaml
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .status.interfaces[0].ipAddress
    name: IP
    type: string
  - JSONPath: .status.nodeName
    name: NodeName
    type: string
```

You can solve this also purely on the client side: https://kubernetes.io/docs/reference/kubectl/overview/#custom-columns.
