### ISSUE TITLE
it not works that cloud-init config ssh-authorized-keys

### ISSUE THREAD

**Issue by volume-ji** [kubevirt/kubevirt#2156]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
  I test the function of cloudinit nocloud by referring to the document: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/startup-scripts.html, it looks like that it not works when I config the cloudInitNoCloud.userData.ssh-authorized-keys and cloudInitNoCloud.userData.ssh_authorized_keys. but it works that I use cloud-init script ethier  userData or userDataBase64. As follow:

```
[root@paas-controller-172-21-0-2:/home/ubuntu/kubevirt/vm/cloudinit]$ cat bionic-cloudinit-config.yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-multus-multiple-net
  name: bionic-cloudinit-config
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: knitter1
    machine:
      type: ""
    resources:
      requests:
        memory: 2048M
  networks:
  - name: knitter1
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/bionic-container-disk-demo:latest
    name: containerdisk
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
[root@paas-controller-172-21-0-2:/home/ubuntu/kubevirt/vm/cloudinit]$ kubectl get po -o wide
NAME                                          READY     STATUS    RESTARTS   AGE       IP             NODE
virt-launcher-bionic-cloudinit-config-42z85   2/2       Running   0          12m       172.20.0.211   172.21.0.2
[root@paas-controller-172-21-0-2:/home/ubuntu/kubevirt/vm/cloudinit]$ ssh ubuntu@172.20.0.211 -i vmkey
ubuntu@172.20.0.211: Permission denied (publickey).
[root@paas-controller-172-21-0-2:/home/ubuntu/kubevirt/vm/cloudinit]$ ping 172.20.0.211
PING 172.20.0.211 (172.20.0.211) 56(84) bytes of data.
64 bytes from 172.20.0.211: icmp_seq=1 ttl=64 time=0.363 ms
64 bytes from 172.20.0.211: icmp_seq=2 ttl=64 time=0.133 ms

```

**What you expected to happen**:
what I expected is that It is also ok that I use cloudinit nocloud config, like cloudinit nocloud script

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f bionic-cloudinit-config.yaml
wait a moment...
ping podIP OK
ssh ubuntu@IP -i vmkey

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.15.0
- Kubernetes version (use `kubectl version`): 1.10.6
- VM or VMI specifications: cloudinit nocloud config
- Cloud provider or hardware configuration: no
- OS (e.g. from /etc/os-release): centos(ourself version release)
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:
