### ISSUE TITLE
secret/configmap volume is failure beacuse of defining domain error.

### ISSUE THREAD

**Issue by volume-ji** [kubevirt/kubevirt#2167]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
create vmi using configmap/secret volume by the direct of document "https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerDisk"， qemu process is not OK, check that there are some loop error logs in vmpod/compute container as follow and finally vmpod get a Error state:
```
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-private/secret-disks/app-secret-disk.iso set to none","pos":"converter.go:166","timestamp":"2019-04-03T01:59:48.657197Z"}
{"component":"virt-launcher","level":"error","msg":"missing target information for device /var/run/kubevirt-private/secret-disks/app-secret-disk.iso","pos":"virDomainDiskDefParseXML:9680","subcomponent":"libvirt","timestamp":"2019-04-03T01:59:48.657000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"vmi-secret","namespace":"default","pos":"libvirt_helper.go:96","reason":"virError(Code=20, Domain=20, Message='missing target information for device /var/run/kubevirt-private/secret-disks/app-secret-disk.iso')","timestamp":"2019-04-03T01:59:48.657841Z","uid":"f6320c6b-55b3-11e9-82d2-0c1262f5429b"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vmi-secret","namespace":"default","pos":"server.go:123","reason":"virError(Code=20, Domain=20, Message='missing target information for device /var/run/kubevirt-private/secret-disks/app-secret-disk.iso')","timestamp":"2019-04-03T01:59:48.657877Z","uid":"f6320c6b-55b3-11e9-82d2-0c1262f5429b"}
```
but I can find the app-secret-disk.iso device in vmpod/compute when the vmpod is Running as follow:
```
[root@vmi-secret secret-disks]# pwd
/var/run/kubevirt-private/secret-disks
[root@vmi-secret secret-disks]# ls -la
total 372
drwxr-xr-x 2 qemu qemu     33 Apr  3 01:58 .
drwxr-xr-x 8 root root    188 Apr  3 01:58 ..
-rw-r--r-- 1 root root 378880 Apr  3 01:59 app-secret-disk.iso
```
**What you expected to happen**:
vmpod Running, qemu process ok and virtctl console vmi is useful

**How to reproduce it (as minimally and precisely as possible)**:
by the direct of document "https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerDisk" configMap and secret section.

**Anything else we need to know?**:
my configMap:  
```
kubectl create cm vmi-cm --from-literal=vmidisk=configmap --from-literal=app=configmap
```
option my secret:
```
kubectl create secret generic vmi-secret --from-literal=key1=supersecret --from-literal=key2=topsecret
```
my vmi specifications:
```
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-multus-multiple-net
  name: vmi-secret
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitnoscriptdisk
      - disk: {}
        name: app-secret-disk
        # set serial
        serial: D23YZ9W6WA5DJ487
      interfaces:
      - bridge: {}
        name: default
    machine:
      type: ""
    resources:
      requests:
        memory: 4096M
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - name: cloudinitnoscriptdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
        bootcmd:
          # mount the secret
          - "mkdir /mnt/app-secret"
          - "mount /dev/$(lsblk --nodeps -no name,serial | grep D23YZ9W6WA5DJ487 | cut -f1 -d' ') /mnt/secret"
  - name: app-secret-disk
    secret:
       secretName: vmi-secret
```
**Environment**:
- KubeVirt version (use `virtctl version`): v0.15.0
- Kubernetes version (use `kubectl version`): v1.10.6
- VM or VMI specifications:  default/vmi-secret
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools: 
- Others:
