### ISSUE TITLE
cdi image upload pod doesn't start

### ISSUE THREAD

**Issue by Bashorsselenberg** [kubevirt/kubevirt#2184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
I run the Kubevirt demo's on my systems and it works good with the Cirros-VM. Now, i want to run bigger virtual machines. I want to run my own virtual machines from my regular KVM hypervisor (seperated environment) on Kubevirt. So i installed a Centos7 VM on KVM and copied the .qcow2 file to the Kubernetes cluster running kubevirt and the CDI components. 

All the pods are running properly. I created a PV and PVC and then i wanted to copy the .qcow2 file to it, in order to attach this to a kubevirt VM.

`kubectl get pv`
centos7pv   10Gi       RWO            Retain           Bound    default/centos7pvc   manual
`kubectl get pvc`
centos7pvc           Bound     centos7pv   10Gi       RWO            manual    
       
I run the command: `./virtctl image-upload --uploadproxy-url=https://10.0.0.173:31125/v1alpha3/upload --image-path=centos7.0.qcow2 --no-create --pvc-name=centos7pvc --pvc-size=10Gi --wait-secs=300 --insecure`

It says:
Waiting for the PVC centos7pvc upload pod to be running...
It hangs and doesn't start. 
default       cdi-upload-centos7pvc                  0/1     Pending   0          26s

When i describe the pod:

  Warning  FailedScheduling  10m (x2 over 10m)  default-scheduler  persistentvolumeclaim "centos7pvc-scratch" not found
  Warning  FailedScheduling  1s (x22 over 10m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

It also creates a 'scratch' pvc
`kubectl get pvc`
centos7pvc           Bound     centos7pv   10Gi       RWO            manual   
centos7pvc-scratch   Pending                                                    manual         83s

**What you expected to happen**:
I didn't expect the name centos7pvc-scratch because that's not the name i created for the pv and PVC. I just expected the .qcow2 file in my PVC so i can create a new vm with this disk attached. 

**How to reproduce it (as minimally and precisely as possible)**:
Use a regular KVM hypervisor and installed Centos7.
Copy the qcow2 file to the Kubernetes cluster with CDI components.
Nodeport the API and upload proxy (don't know why i need this).
Created PV and PVC.
Run the ./virtctl image-upload command (as described).

**Anything else we need to know?**:
And i just want to run KVM-Vmachines in the Kubernetes cluster with Kubevirt. And in the end, i want to run Windows 10-vm. I don't know how to do this according to the kubevirt documentation, i'm pretty new to this. Thanks in advance.

**Environment**:
- KubeVirt version v0.16.0
- Kubernetes version v1.13.4
- CDI v1.7.0
- OS Ubuntu 18.04
- Kernel Linux k8smaster 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmohr** [comment]
@awels @aglitke maybe you can explain what @Bashorsselenberg is seeing?

**Comment by awels** [comment]
@rmohr and @Bashorsselenberg So the problem is that for upload to fully work, we need some temporary space (we have to have the whole file in that space before being able to convert to the target space, and because of the potential size of the image we try to create another PVC to temporarily store it in). Anyway since it looks like you are manually creating the PV and PVC, you will have to create another PV of the same size, then the scratch space can get created and the upload will succeed.

If you want to avoid the whole scratch space situation, download CDI 1.8.0 (released on Friday) and convert the image to RAW before uploading, then it should not need the scratch space because it doesn't have to convert the image.

https://github.com/kubevirt/containerized-data-importer/blob/master/doc/supported_operations.md has a matrix of which combinations of operations requires scratch space and which ones don't.

**Comment by mhenriks** [comment]
Hi @Bashorsselenberg, CDI uses "scratch" PVCs to temporarily store qcow2 files while they are being converted to raw (KubeVirt only runs on raw).  After the conversion, the scratch PVC is deleted.  It would appear that the scratch PVC could not be created in your case.  What is the storage configuration in your cluster?  Do you have a dynamic provisioner?  Is there a default StorageClass?

**Comment by Bashorsselenberg** [comment]
Thanks in advance for the help! This is really appreciated.
Still having some trouble for running the virtual machines, but i get closer.

- Updated CDI v1.7.0 to v1.8.0
- Using a small alpine VM now for testing, so converted the KVM .qcow2 to .raw
- Still the same issue with the scratch space. So manually created 1 PV, 1 PV-scratch and a 1 PVC.
- Used the command: `./virtctl image-upload --uploadproxy-url=https://10.0.0.173:31125 --pvc-name=alpine-disk --pvc-size=10Gi --image-path=/home/user/alpine/alpinedisk.raw --insecure --no-create`

And it this works, many thanks! Now there is another issue (maybe if i have to create a new issue ...?)

Now i created a new virtual machine and everything seems to be running. so far so good.. but when i connect to it. Nothing appears, it says: succesfully connected to...   But there is no login screen.
So i described the VM pod, gives me the following.

Warning  Unhealthy  6m30s  kubelet, k8sworker02  Readiness probe failed: cat: /var/run/kubevirt-infra/healthy: No such file or directory

VM is created using the following yaml.

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: alpine-vm
spec:
  terminationGracePeriodSeconds: 0
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: pvcdisk
        disk:
          bus: virtio
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: alpine-disk
```
Trying to find out this issues, i think nothing is wrong with the YAML and pvc-disks (according to issue  #36 https://github.com/kubevirt/demo/issues/36). I'm curious whats wrong this time.

Thanks in advance!

**Comment by rmohr** [comment]
Could you also do a `describe` on the VMI itself and post the output?

**Comment by Bashorsselenberg** [comment]
Yes, provides me the following output:

Name:         alpine-vm
Namespace:    default
Labels:       kubevirt.io/nodeName=k8sworker02
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachineInstance","metadata":{"annotations":{},"name":"alpine-vm","namespace":"default"...
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-04-17T13:29:17Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:        7
  Resource Version:  216423
  Self Link:         /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/alpine-vm
  UID:               cd1a99a3-6114-11e9-8349-56c7ecf7df74
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   pvcdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  55b91fb5-10ff-467f-aa1d-8352dc5539fd
    Machine:
      Type:  q35
    Resources:
      Requests:
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Name:  pvcdisk
    Persistent Volume Claim:
      Claim Name:  alpine-disk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI with non-shared PVCs
    Reason:                DisksNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2019-04-17T13:29:24Z
    Status:                True
    Type:                  Ready
  Interfaces:
    Ip Address:      10.244.2.29
    Mac:             0a:58:0a:f4:02:1d
    Name:            default
  Migration Method:  BlockMigration
  Node Name:         k8sworker02
  Phase:             Running
Events:
  Type    Reason            Age                From                       Message
  ----    ------            ----               ----                       -------
  Normal  SuccessfulCreate  43m                virtualmachine-controller  Created virtual machine pod virt-launcher-alpine-vm-knffv
  Normal  Started           43m                virt-handler, k8sworker02  VirtualMachineInstance started.
  Normal  Created           43m (x3 over 43m)  virt-handler, k8sworker02  VirtualMachineInstance defined.

**Comment by Bashorsselenberg** [comment]
And the output of the pod itself:

```
Name:               virt-launcher-alpine-vm-knffv
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               k8sworker02/10.0.0.175
Start Time:         Wed, 17 Apr 2019 15:29:18 +0200
Labels:             kubevirt.io=virt-launcher
                    kubevirt.io/created-by=cd1a99a3-6114-11e9-8349-56c7ecf7df74
Annotations:        kubevirt.io/domain: alpine-vm
Status:             Running
IP:                 10.244.2.29
Controlled By:      VirtualMachineInstance/alpine-vm
Containers:
  compute:
    Container ID:  docker://1fdc3f4024d095c23692b5b2c1006135adfb72e9f17e03177cf312db9d865cdc
    Image:         index.docker.io/kubevirt/virt-launcher:v0.16.0
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:b7fafd2a7123906d68dce50d949b5514677ceb10b316a0908821cc7e19831c7e
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      alpine-vm
      --uid
      cd1a99a3-6114-11e9-8349-56c7ecf7df74
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --readiness-file
      /var/run/kubevirt-infra/healthy
      --grace-period-seconds
      15
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
    State:          Running
      Started:      Wed, 17 Apr 2019 15:29:19 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
    Requests:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      memory:                         1187554432
    Readiness:                        exec [cat /var/run/kubevirt-infra/healthy] delay=2s timeout=5s period=2s #success=1 #failure=5
    Environment:                      <none>
    Mounts:
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-infra from infra-ready-mount (rw)
      /var/run/kubevirt-private/vmi-disks/pvcdisk from pvcdisk (rw)
      /var/run/libvirt from libvirt-runtime (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pvcdisk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  alpine-disk
    ReadOnly:   false
  infra-ready-mount:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  libvirt-runtime:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  ephemeral-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                  Message
  ----     ------     ----  ----                  -------
  Normal   Scheduled  45m   default-scheduler     Successfully assigned default/virt-launcher-alpine-vm-knffv to k8sworker02
  Normal   Pulled     45m   kubelet, k8sworker02  Container image "index.docker.io/kubevirt/virt-launcher:v0.16.0" already present on machine
  Normal   Created    45m   kubelet, k8sworker02  Created container
  Normal   Started    45m   kubelet, k8sworker02  Started container
  Warning  Unhealthy  45m   kubelet, k8sworker02  Readiness probe failed: cat: /var/run/kubevirt-infra/healthy: No such file or directory
```

**Comment by rmohr** [comment]
How do you try to connect? Via `virtctl vnc` or `virtctl console`?

**Comment by Bashorsselenberg** [comment]
On the K8s-master node itself (GUI). Start a terminal and type `./virtctl console alpine-vm`
Only says:
Succesfully connected to the alpine-vm console. The escape sequence is ^]

But vnc says. no bootable device.. hmm

**Comment by rmohr** [comment]
Ok, that explains that. `virtcl console` can connect to the serial device of the VMI, but the machine does not send anything because it is not booting. Hard to tell why it is not booting.

**Comment by awels** [comment]
Usually if it is not booting it doesn't like the contents of the disk. You said it works if you import the image instead of uploading right? @Bashorsselenberg

**Comment by Bashorsselenberg** [comment]
Hello, it doesn't work yet..
I tried Lubuntu18.10. Exported the .qcow2 disk to my Kubevirt environment. Converted it to lubuntu.raw
Added it to the PVC, and mounted in a LubuntuVM.yaml but this also gives me: No bootable device...

**Comment by Bashorsselenberg** [comment]
Tried multiple VM's now, but none of them are able to boot.

**Comment by awels** [comment]
An import and an upload are different. An import retrieves the image from an external http source. For instance:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cirros"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
```
That will connect to an http endpoint on the internet to get the image. You should then be able to create a VM(I) using that image.

**Comment by Bashorsselenberg** [comment]
Yes, but i would like to use my KVM virtual machines in my Kubernetes cluster running Kubevirt.

**Comment by awels** [comment]
Right, I am just verifying that if you do that, it actually works for you.

**Comment by Bashorsselenberg** [comment]
Yes so it works for me. But the only problem that is left is that the machine don't boot. Still no luck.
This is for the use-case where i got the KVM .qcow2 files into the pvc, and then i try to boot it up as described. Hopefully somebody knows the issue here?

Thanks in advance!

**Comment by awels** [comment]
So I am trying to determine that if you IMPORT the vm does boot, upload and import are two distinct operations with distinct code paths. If import works and boots, and upload 'works' but doesn't boot, there is a potential issue in the upload. But if import doesn't boot either, its more likely to be an issue in your environment. Just trying go through the debug steps to figure out where to look next.

**Comment by Bashorsselenberg** [comment]
I'm sorry for my misunderstandings. I am a little new to this. But thanks for the help.
So as far as i understand now, i used the import function and that worked for me for the small Cirros VM.

Created manually a PV and PVC
```

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cirros-disk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cirros-disk
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

And then the Cirros VM:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: cirros-vm
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: cirros-disk
status: {}
```

It took about 2 minutes to access it, it had to load someting i dont know (1/20, 2/20 steps.. and so on) but this works for me. Thanks! :)

So the upload doesn't seem to work yet.. those VM's are not booting.

Thanks in advance!

**Comment by Bashorsselenberg** [comment]
Another update, If i replace the Cirros source with an Ubuntu source (https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img), is also says, no bootable device..

**Comment by awels** [comment]
One important thing that might not be immediately obvious, The size of the requested storage should be equal or larger than the virtual disk size. 
I am seeing this in your example, which is sufficient for the cirros case (its really small) but for something like ubuntu I would expect a minimum of about 8G.
```yaml
  resources:
    requests:
      storage: 1Gi
```

The importer pod log should tell you if this is the case, but I suspect it is. The easiest way to find out the virtual size of the disk image is by running 'qemu-img info https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img
That should give you the virtual size of the disk. Then create a PV of sufficient size and a matching PVC and it should work.

Its possible the same thing is true for the upload, the upload server pod log should have a message as well if the virtual size is larger than the PVC size.

**Comment by Bashorsselenberg** [comment]
Thnx for the tip!, but the virtual disk size of Ubuntu is 2.2Gi and my PV and PVC are 10Gi. So unfortunately this is not the problem for this case.

**Comment by Bashorsselenberg** [comment]
So now, i used to upload function. Downloaded https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img and renamed it to disk.img.
Converted it to .raw. and uploaded to the PVC. Still no luck.. no bootable device again..
All the pods are running and i can connect though VNC

**Comment by Bashorsselenberg** [comment]
Well, thnx for the help guys. I create a new issue for vm's that doesn't want to boot. this original issue for uploading into PV is fixed.

**Comment by awels** [comment]
The no bootable disk is almost certainly a problem with the storage, not VM/VMI.  You didn't give us the definition of your PV/PVC, assuming its some kind of hostPath storage, you could try to locate the disk.img file on your node file system. CDI should have resized the disk.img to the size of the PVC in your case 10G (it doesn't update the guest OS partition table though). You should be able to run qemu-img on the disk.img file to get the same information as you got from the original.

**Comment by rmohr** [comment]
@Bashorsselenberg you can use `kubectl exec` to enter the pod of the VMI. Then you can do `virsh list` and `virsh dumpxml`. There you should then see the path in the pod to the image. `qemu-img` is also in the pod. I hope that helps.

**Comment by rmohr** [comment]
@Bashorsselenberg once you have the path,  you can also use `kubectl cp` to copy the image out of the container and try to start it manually with libvirt or qemu, to be sure that it is valid.

**Comment by Bashorsselenberg** [comment]
Yes, here is another step by step what i did. Where i try to verify the hostPath storage location.
- Downloaded Ubuntu from: https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img and renamed it to disk.img
- placed the file in a folder ~/vms/ubuntu
- converted the .qcow2 format to raw (using qemu-img convert)
- when i run `qemu-img info disk.img`

```
image: disk.img
file format: raw
virtual size: 2.2G (2361393152 bytes)
disk size: 1.0G
```

- created a pv-pvc.yaml file containing the following files:

```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ubuntu
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/xxxxx/vms/ubuntu/disk.img"   #directory of the downloaded and converted ubuntu file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ubuntu-disk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15G
```
- then `kubectl describe pv ubuntu`

```
Name:            ubuntu
Labels:          type=local
Annotations:     kubectl.kubernetes.io/last-applied-configuration:
                   {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"ubuntu"},"spec":{"accessModes"...
                 pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Bound
Claim:           default/ubuntu-disk
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        15G
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /home/xxxxx/vms/ubuntu/disk.img
    HostPathType:  
Events:            <none>
```
- Desciption of the PVC
```
Name:          ubuntu-disk
Namespace:     default
StorageClass:  manual
Status:        Bound
Volume:        ubuntu
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"ubuntu-disk","namespace":"default"},"spec":{"access...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      15G
Access Modes:  RWO
VolumeMode:    Filesystem
Events:        <none>
Mounted By:    virt-launcher-ubuntu-vm01-g24j4
```

- So i used this method now for pv, pvc local storage with the disk.img
- Applied the ubuntu-vm.yaml 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntu-vm01
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: ubuntu-disk
status: {}
```
- Noted that VMs and pods are running, connected though the virtctl but no bootable device.

**Comment by slintes** [comment]
> hostPath:
    path: "/home/xxxxx/vms/ubuntu/disk.img"

just thinking loud, but afaik this should be `/home/xxxxx/vms/ubuntu` without `disk.img`?

**Comment by Bashorsselenberg** [comment]
@rmohr 
- when i execute `kubectl exec -it virt-launcher-ubuntu-vm01-g24j4 -- sh -c 'virsh list'`
```
 Id   Name                  State
-------------------------------------
 1    default_ubuntu-vm01   running
```
- Sorry i'm new to this but i missed domain name for: `kubectl exec -it virt-launcher-ubuntu-vm01-g24j4 -- sh -c 'virsh dumpxml'`
```
error: command 'dumpxml' requires <domain> option
command terminated with exit code 1
```

**Comment by rmohr** [comment]
In your case it is `virsh dumpxml default_ubuntu-vm01`

**Comment by awels** [comment]
I agree with @slintes that your PV is not configured correctly. I am not even sure what happens when you point the path to virtual disk image, the host path should point to a directory, the kubernetes cluster will write files to that directory. That is why for our testing setup, we have /mnt/local-volume/disk1 /mnt/local-volume/disk2, etc for the PVs.

So your PVs should look like this:
```yaml
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ubuntu
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/xxxxx/vms/pv1
```
And make a pv2 for the scratch space as well.
Then create the matching PVCs, once you upload into your PVC, there should be a file called disk.img in /home/xxxxx/vms/pv1. This will write the file with the right permissions into that directory.
