### ISSUE TITLE
Virtctl vnc fails intermittently for Windows VM

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/kubevirt#2201]
/kind bug

**What happened**:
`virtctl vnc` for Windows VM fails intermittently. It fails to connect majority of the times and even when it connects it gets disconnected after sometime. I see the following on the console
```
[root@10 ~]# kubectl get vmis
NAME         AGE   PHASE     IP            NODENAME
testvm-win   5h    Running   10.244.8.35   10.0.1.6
[root@10 ~]# ./virtctl vnc testvm-win --v=9
{"component":"virtctl","level":"info","msg":"Config loaded from file/root/.kube/config","pos":"loader.go:359","timestamp":"2019-04-19T16:09:34.946229Z"}
{"component":"virtctl","level":"info","msg":"curl -k -v -XGET  -H \"User-Agent: virtctl/v0.0.0 (linux/amd64) kubernetes/$Format\" 'wss://10.0.1.9:6443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm-win/vnc'","pos":"round_trippers.go:386","timestamp":"2019-04-19T16:09:34.947855Z"}
{"component":"virtctl","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2019-04-19T16:09:35.017590Z"}
{"component":"virtctl","level":"info","msg":"Executing commandline: 'remote-viewer [vnc://127.0.0.1:35067 --debug]'","pos":"vnc.go:225","timestamp":"2019-04-19T16:09:35.017786Z"}
Error encountered: websocket: close 1006 (abnormal closure): unexpected EOF
```
Virt-api logs
```
{"component":"virt-api","kind":"VirtualMachineInstance","level":"error","msg":"failed to exectue command [/usr/share/kubevirt/virt-launcher/sock-connector /var/run/kubevirt-private/2faebaef-62ce-11e9-beb9-98860989b666/virt-vnc] on the pod connection failed: error sending request: Post https://10.96.0.1:443/api/v1/namespaces/default/pods/virt-launcher-testvm-win-g5s2j/exec?command=%2Fusr%2Fshare%2Fkubevirt%2Fvirt-launcher%2Fsock-connector\u0026command=%2Fvar%2Frun%2Fkubevirt-private%2F2faebaef-62ce-11e9-beb9-98860989b666%2Fvirt-vnc\u0026container=compute\u0026container=compute\u0026stderr=true\u0026stdin=true\u0026stdout=true: dial tcp 10.96.0.1:443: connect: no route to host","name":"testvm-win","namespace":"default","pos":"subresource.go:115","timestamp":"2019-04-19T23:06:38.658409Z","uid":"2faebaef-62ce-11e9-beb9-98860989b666"}
{"component":"virt-api","level":"info","msg":"http: response.WriteHeader on hijacked connection\n","pos":"server.go:2979","timestamp":"2019-04-19T23:06:38.658505Z"}
{"component":"virt-api","kind":"VirtualMachineInstance","level":"error","msg":"error ecountered reading from websocket stream","name":"testvm-win","namespace":"default","pos":"subresource.go:127","reason":"read tcp 10.244.8.37:8443-\u003e10.244.2.1:41400: use of closed network connection","timestamp":"2019-04-19T23:06:38.658704Z","uid":"2faebaef-62ce-11e9-beb9-98860989b666"}
{"component":"virt-api","contentLength":0,"level":"info","method":"GET","pos":"filter.go:46","proto":"HTTP/1.1","remoteAddress":"10.244.2.1","statusCode":500,"timestamp":"2019-04-19T23:06:38.658819Z","url":"/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm-win/vnc","username":"-"}
{"component":"virt-api","level":"info","msg":"http: TLS handshake error from 10.0.1.6:36850: EOF\n","pos":"server.go:2979","timestamp":"2019-04-19T23:06:46.246493Z"}
{"component":"virt-api","level":"info","msg":"http: TLS handshake error from 10.0.1.6:36862: EOF\n","pos":"server.go:2979","timestamp":"2019-04-19T23:06:56.246421Z"}
{"component":"virt-api","kind":"VirtualMachineInstance","level":"info","msg":"Websocket connection upgraded","name":"testvm-win","namespace":"default","pos":"subresource.go:105","timestamp":"2019-04-19T23:06:58.028369Z","uid":"2faebaef-62ce-11e9-beb9-98860989b666"}
{"component":"virt-api","level":"warning","msg":"Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.","pos":"client_config.go:548","timestamp":"2019-04-19T23:06:58.028526Z"}
{"component":"virt-api","kind":"VirtualMachineInstance","level":"error","msg":"failed to exectue command [/usr/share/kubevirt/virt-launcher/sock-connector /var/run/kubevirt-private/2faebaef-62ce-11e9-beb9-98860989b666/virt-vnc] on the pod connection failed: error sending request: Post https://10.96.0.1:443/api/v1/namespaces/default/pods/virt-launcher-testvm-win-g5s2j/exec?command=%2Fusr%2Fshare%2Fkubevirt%2Fvirt-launcher%2Fsock-connector\u0026command=%2Fvar%2Frun%2Fkubevirt-private%2F2faebaef-62ce-11e9-beb9-98860989b666%2Fvirt-vnc\u0026container=compute\u0026container=compute\u0026stderr=true\u0026stdin=true\u0026stdout=true: dial tcp 10.96.0.1:443: connect: no route to host","name":"testvm-win","namespace":"default","pos":"subresource.go:115","timestamp":"2019-04-19T23:06:58.029678Z","uid":"2faebaef-62ce-11e9-beb9-98860989b666"}
{"component":"virt-api","level":"info","msg":"http: response.WriteHeader on hijacked connection\n","pos":"server.go:2979","timestamp":"2019-04-19T23:06:58.029765Z"}
{"component":"virt-api","kind":"VirtualMachineInstance","level":"error","msg":"error ecountered reading from websocket stream","name":"testvm-win","namespace":"default","pos":"subresource.go:127","reason":"read tcp 10.244.8.37:8443-\u003e10.244.0.1:35908: use of closed network connection","timestamp":"2019-04-19T23:06:58.029948Z","uid":"2faebaef-62ce-11e9-beb9-98860989b666"}
{"component":"virt-api","contentLength":0,"level":"info","method":"GET","pos":"filter.go:46","proto":"HTTP/1.1","remoteAddress":"10.244.0.1","statusCode":500,"timestamp":"2019-04-19T23:06:58.030094Z","url":"/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm-win/vnc","username":"-"}
{"component":"virt-api","level":"info","msg":"http: TLS handshake error from 10.0.1.6:36876: EOF\n","pos":"server.go:2979","timestamp":"2019-04-19T23:07:06.246369Z"}
```

Virt-launcher pod logs has no error

**Environment**:
- KubeVirt version (use `virtctl version`):
`v0.14.0`
- Kubernetes version (use `kubectl version`):
`v1.13.3`
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
  name: testvm-win
spec:
  domain:
    clock:
      utc: {}
      timer:
        hpet:
          present: false
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
        hyperv: {}
    cpu:
      cores: 8
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        vapic: {}
        spinlocks:
          spinlocks: 8191
    resources:
      requests:
        memory: 12Gi
    devices:
       disks:
       - disk:
           bus: sata
         name: rootdisk
       interfaces:
       - bridge: {}
         model: e1000
         name: default
  terminationGracePeriodSeconds: 0
  volumes:
  - name: rootdisk
    persistentVolumeClaim:
      claimName: win-pvc
  networks:
  - name: default
    pod: {}
```
I expect it to not crash so often. I have not seen this issue on Centos but it is not at all frequent. Can anyone please help me debug this?
