### ISSUE TITLE
VMs no bootable device

### ISSUE THREAD

**Issue by Bashorsselenberg** [kubevirt/kubevirt#2206]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I downloaded Ubuntu cloud image from: https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img
renamed the file to disk.img and converted it from qcow2 to raw format. Imported it to PVC but when connected to PVC, it says: no bootable device.. all the pods and the vmi are in running state. Used the following .YAML for PV and PVC.

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ubuntu-disk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-disk
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-i386.img"
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
And created the VM with:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntu-vm01
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: ubuntu-disk
status: {}
```
When i describe the VMI:

```
Name:         ubuntu-vm01
Namespace:    default
Labels:       kubevirt.io/nodeName=k8sworker01
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachineInstance","metadata":{"annotations":{},"name":"ubuntu-vm01","namespace":"defaul...
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-04-23T08:54:52Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:        7
  Resource Version:  1037332
  Self Link:         /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/ubuntu-vm01
  UID:               75658c71-65a5-11e9-8349-56c7ecf7df74
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   pvcdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  ff7a2b41-6cc7-4207-9d4e-69970d8aaa17
    Machine:
      Type:  q35
    Resources:
      Requests:
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Name:  pvcdisk
    Persistent Volume Claim:
      Claim Name:  ubuntu-disk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI with non-shared PVCs
    Reason:                DisksNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2019-04-23T08:54:58Z
    Status:                True
    Type:                  Ready
  Interfaces:
    Ip Address:      10.244.1.24
    Mac:             0a:58:0a:f4:01:18
    Name:            default
  Migration Method:  BlockMigration
  Node Name:         k8sworker01
  Phase:             Running
Events:
  Type    Reason            Age                From                       Message
  ----    ------            ----               ----                       -------
  Normal  SuccessfulCreate  50m                virtualmachine-controller  Created virtual machine pod virt-launcher-ubuntu-vm01-gfc5g
  Normal  Created           50m (x3 over 50m)  virt-handler, k8sworker01  VirtualMachineInstance defined.
  Normal  Started           50m                virt-handler, k8sworker01  VirtualMachineInstance started.
```

**What you expected to happen**:
Expected a disk.img in the PV that is able to boot the ubuntu image when connecting to though VNC. But is says: no bootable device. The same issue happens when installing KVM virtual machines on the regular hypervisor. Upload it to PV. but that also doesn't work.

The Cirros VM does boot, but others does not.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
KVM regular hypervisor virtual machines, copied the disks (.raw) to kubevirt cluster, en uploaded it to PV. but gives also: no bootable device

    KubeVirt version v0.16.0
    Kubernetes version v1.13.4
    CDI v1.8.0
    OS Ubuntu 18.04

related to https://github.com/kubevirt/kubevirt/issues/2184
