### ISSUE TITLE
It's there has some demo about run a windows-os vmi using kubrvirt？

### ISSUE THREAD

**Issue by DeepLJH0001** [kubevirt/kubevirt#2282]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

I‘m so sorry to ask this kind question ......
I‘m a beginner learning kubevirt， 
I want to know there is possible run a windows vmi on linux host？
and where can i get more demo about launch a windows vmi

**Comment by Apokleos** [comment]
It maybe help you, here(https://github.com/kubevirt/kubevirt/tree/master/cluster/examples)

**Comment by DeepLJH0001** [comment]
> It maybe help you, here(https://github.com/kubevirt/kubevirt/tree/master/cluster/examples) 
I see this (https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vmi-windows.yaml) but don't understand what should embed in this pv
```
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: disk-windows
```

**Comment by DeepLJH0001** [comment]
> It maybe help you, here(https://github.com/kubevirt/kubevirt/tree/master/cluster/examples) 
I see this (https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vmi-windows.yaml) but don't understand what should embed in this pv
```
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: disk-windows
```
