### ISSUE TITLE
How to make cdi-upload-server pods to run only on linux nodes in hybrid cluster ?

### ISSUE THREAD

**Issue by gkgth** [kubevirt/kubevirt#2300]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
In a hybrid cluster "cdi-uploadserver:v1.9.0" image gets scheduled to windows node.
**What you expected to happen**:
cdi-upload server should get deployed on the same node selector as "cdi-deployment"
**How to reproduce it (as minimally and precisely as possible)**:

Deploy CDI with below yaml (in a hybrid cluster which has both windows and Linux nodes),

```
cdi-apiserver-768574b5fb-qqxfd     1/1     Running   0          36m   10.244.2.33   linuxnode01   <none>           <none>
cdi-deployment-85bbbbb5b4-npvzb    1/1     Running   0          36m   10.244.2.35   linuxnode01   <none>           <none>
cdi-uploadproxy-65598ddb8f-jwc9c   1/1     Running   0          36m   10.244.2.34   linuxnode01   <none>           <none>

```
 

try to upload an iso image .
```
virtctl image-upload --uploadproxy-url=https://10.93.31.87:31001 --pvc-name=win10-virtio-disk --pvc-size=1Gi --image-path=virtio-win.iso --insecure --no-create
```

```
cdi-upload-win10-virtio-disk     0/1     ImagePullBackOff   0          26m    10.244.1.11   win-sp14qb7lg7r   <none>     
```

How to make the upload server pod respect the same node selector ?

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: datavolumes.cdi.kubevirt.io
spec:
  group: cdi.kubevirt.io
  names:
    kind: DataVolume
    plural: datavolumes
    shortNames:
    - dv
    - dvs
    singular: datavolume
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata: {}
        spec:
          properties:
            pvc:
              properties:
                accessModes:
                  type: array
                resources:
                  properties:
                    requests:
                      properties:
                        storage:
                          type: string
                  required:
                  - requests
                storageClassName:
                  type: string
              required:
              - resources
              - accessModes
            source:
              properties:
                blank: {}
                http:
                  properties:
                    secretRef:
                      type: string
                    url:
                      type: string
                  required:
                  - url
                pvc:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                  - namespace
                  - name
                registry:
                  properties:
                    secretRef:
                      type: string
                    url:
                      type: string
                  required:
                  - url
                s3:
                  properties:
                    secretRef:
                      type: string
                    url:
                      type: string
                  required:
                  - url
                upload: {}
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdiconfigs.cdi.kubevirt.io
spec:
  group: cdi.kubevirt.io
  names:
    kind: CDIConfig
    plural: cdiconfigs
    singular: cdiconfig
  scope: Cluster
  version: v1alpha1


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi
subjects:
- kind: ServiceAccount
  name: cdi-sa
  namespace: cdi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  verbs:
  - get
  - list
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-apiserver
subjects:
- kind: ServiceAccount
  name: cdi-apiserver
  namespace: cdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: cdi-apiserver
  namespace: cdi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-sa
  namespace: cdi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: containerized-data-importer
    cdi.kubevirt.io: ""
  name: cdi-deployment
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerized-data-importer
  strategy: {}
  template:
    metadata:
      labels:
        app: containerized-data-importer
        cdi.kubevirt.io: ""
    spec:
      nodeSelector:
        kubernetes.io/os: linux    
      containers:
      - args:
        - -v=1
        env:
        - name: IMPORTER_IMAGE
          value: kubevirt/cdi-importer:v1.9.0
        - name: CLONER_IMAGE
          value: kubevirt/cdi-cloner:v1.9.0
        - name: UPLOADSERVER_IMAGE
          value: kubevirt/cdi-uploadserver:v1.9.0
        - name: UPLOADPROXY_SERVICE
          value: cdi-uploadproxy
        - name: PULL_POLICY
          value: IfNotPresent
        image: kubevirt/cdi-controller:v1.9.0
        imagePullPolicy: IfNotPresent
        name: cdi-controller
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 2
          periodSeconds: 5
        resources: {}
      serviceAccountName: cdi-sa
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-insecure-registries
  namespace: cdi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver
  namespace: cdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver
  namespace: cdi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-apiserver
subjects:
- kind: ServiceAccount
  name: cdi-apiserver
  namespace: cdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-apiserver
  namespace: cdi
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-extension-apiserver-authentication
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-extension-apiserver-authentication
subjects:
- kind: ServiceAccount
  name: cdi-apiserver
  namespace: cdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cdi.kubevirt.io: ""
  name: cdi-extension-apiserver-authentication
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cdi.kubevirt.io: cdi-apiserver
  name: cdi-api
  namespace: cdi
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cdi.kubevirt.io: cdi-apiserver
  name: cdi-apiserver
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      cdi.kubevirt.io: cdi-apiserver
  strategy: {}
  template:
    metadata:
      labels:
        cdi.kubevirt.io: cdi-apiserver
    spec:
      nodeSelector:
        kubernetes.io/os: linux    
      containers:
      - args:
        - -v=1
        image: kubevirt/cdi-apiserver:v1.9.0
        imagePullPolicy: IfNotPresent
        name: cdi-apiserver
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 5
        resources: {}
      serviceAccountName: cdi-apiserver

---
apiVersion: v1
kind: Service
metadata:
  labels:
    cdi.kubevirt.io: cdi-uploadproxy
  name: cdi-uploadproxy
  namespace: cdi
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cdi.kubevirt.io: cdi-uploadproxy
  name: cdi-uploadproxy
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      cdi.kubevirt.io: cdi-uploadproxy
  strategy: {}
  template:
    metadata:
      labels:
        cdi.kubevirt.io: cdi-uploadproxy
    spec:
      nodeSelector:
        kubernetes.io/os: linux    
      containers:
      - args:
        - -v=1
        env:
        - name: APISERVER_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: id_rsa.pub
              name: cdi-api-signing-key
        - name: UPLOAD_SERVER_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              key: tls.key
              name: cdi-upload-server-client-key
        - name: UPLOAD_SERVER_CLIENT_CERT
          valueFrom:
            secretKeyRef:
              key: tls.crt
              name: cdi-upload-server-client-key
        - name: UPLOAD_SERVER_CA_CERT
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: cdi-upload-server-client-key
        - name: SERVICE_TLS_KEY
          valueFrom:
            secretKeyRef:
              key: tls.key
              name: cdi-upload-proxy-server-key
        - name: SERVICE_TLS_CERT
          valueFrom:
            secretKeyRef:
              key: tls.crt
              name: cdi-upload-proxy-server-key
        image: kubevirt/cdi-uploadproxy:v1.9.0
        imagePullPolicy: IfNotPresent
        name: cdi-uploadproxy
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 5
        resources: {}
```

Thanks !

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.0", GitCommit:"a067696ed6c25b0eab9dfcd01bbdc045f500f8ca", GitTreeState:"clean", BuildDate:"2019-05-06T14:58:11Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration: VMWare
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
```
Linux master01 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
