### ISSUE TITLE
Wrong HostDisk size when using PersistentVolumeClaim (volumeMode filesystem)

### ISSUE THREAD

**Issue by fedepaol** [kubevirt/kubevirt#2357]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Was not able to launch a vmi with a disk using a volume of type `PersistentVolumeClaim` (default volumeMode:filesystem).

The host has ~35 Gigs and the VolumeCaim requested 2 Gigs

From the launcher logs:

```
cluster/kubectl.sh logs virt-launcher-simplevmpvc-cj2dx compute

{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"simplevmpvc","namespace":"default","pos":"server.go:160","reason":"preparing host-disks failed: unable to create /var/run/kubevirt-private/vmi-disks/pvdisk/disk.img, not enough space, demanded size 39728447488 B is bigger than available space 35301134336 B, also after taking 10 % toleration into account","timestamp":"2019-06-07T13:50:36.658484Z","uid":"126200db-892b-11e9-9a97-525500d15501"}
```

Since I did not specified the first size anywhere and it felt strange, I started looking around.

If this is a bug, the cause could be in
https://github.com/kubevirt/kubevirt/blob/master/pkg/host-disk/host-disk.go#L62
in ` ReplacePVCByHostDisk` which does what its name suggests (only if the pvc is not of type block, which was the case).

It replaces the `volumeSource.PersistentVolumeClaim` with a `HostDisk` (as described in the [docs](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html)).

I expect the size to be `PersistentVolumeSize.Spec.Resources.Requests[k8sv1.ResourceStorage]` (my 2 gigs) and not `pvc.Status.Capacity[k8sv1.ResourceStorage]` which I suspect is the size of the backing Persistent Volume.

If my analysis sounds correct and this is a real bug, I could use it as a test bed for learning the dev process.

**What you expected to happen**:
The vm started correctly.

**How to reproduce it (as minimally and precisely as possible)**:
From a checkout:
`cluster/up.sh`

wait for the cluster to be ready, then

```

export RELEASE=v0.18.0
cluster/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/$RELEASE/kubevirt-operator.yaml
cluster/kubectl.sh apply -f https://github.com/kubevirt/kubevirt/releases/download/$RELEASE/kubevirt-cr.yaml
cluster/kubectl.sh -n kubevirt wait kv kubevirt --for condition=Ready

cat <<EOF | cluster/kubectl.sh apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: simplevmpvc
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - name: pvdisk
        disk:
          bus: virtio
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/cirros-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: pvdisk
    persistentVolumeClaim:
      claimName: mypvc
EOF
```

**Anything else we need to know?**:

**Environment**:
Checkout from master, revision `ee10b26edc39171ef8fedd9453ab6edfd2d826ba`
