### ISSUE TITLE
It's possible set specific cpu mode like qemu64 or define custom xml ?

### ISSUE THREAD

**Issue by DeepLJH0001** [kubevirt/kubevirt#2372]
I want to set cpu model like this， because my cpu is not AMD & Intel 
```
<cpu mode='host-model'>
    <model fallback='allow'>qemu64</model>
</cpu>
```

**Comment by petrkotas** [comment]
Hi @DeepLJH0001 it is possible. You can use the the CPU setting from the Domain. The VM would look e.g. like this:
<details><summary>Example</summary>
<p>

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    cpu:
      model: x86_qemu64
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-registry-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```

</p>
</details>

The cpu model is taken directly from the libvirt: https://github.com/libvirt/libvirt/tree/master/src/cpu_map
and the details about CPU config can be found in our API: https://kubevirt.io/api-reference/master/definitions.html#_v1_cpu

I hope this clarifies the issue.
