### ISSUE TITLE
kubevirt How to open the USB bus?

### ISSUE THREAD

**Issue by yinjingjiu** [kubevirt/kubevirt#2392]
**What happened**:
Using VNC to connect to a virtual machine, the mouse offset does not display correctly

**What you expected to happen**:
How to open the USB bus ('-machine usb=on')

**Environment**:
- KubeVirt version v0.17.0
- Kubernetes version v1.13.5

**How to reproduce it (as minimally and precisely as possible)**:
<details>
<summary>my yaml:</summary>

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows1
  name: vmi-windows1
spec:
  domain:
    cpu:
      cores: 2
    devices:
      inputs:
      - type: tablet
        bus: usb
        name: tablet1
      disks:
      - disk:
          bus: virtio
        name: cloudinitdisk
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f221
    resources:
      requests:
        memory: 2Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: cloudinitdisk
    containerDisk:
      image: www.eanregistry.com:5000/yinjjwin7base:latest
```
</details>

![image](https://user-images.githubusercontent.com/8465157/59587060-f78c8400-9116-11e9-940e-f8f21063180a.png)

![Video_2019-06-17_154938_edit](https://user-images.githubusercontent.com/8465157/59587965-12f88e80-9119-11e9-8d7b-ae98d5809adf.gif)

Thanks in advance.

**Comment by petrkotas** [comment]
Hi @yinjingjiu can you please try to switch the bus to 'virtio' and see if it helps in your case?
Thanks for reporting this issue on windows.

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows1
  name: vmi-windows1
spec:
  domain:
    cpu:
      cores: 2
    devices:
      inputs:
      - type: tablet
        bus: virtio
        name: tablet1
      disks:
      - disk:
          bus: virtio
        name: cloudinitdisk
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f221
    resources:
      requests:
        memory: 2Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: cloudinitdisk
    containerDisk:
      image: www.eanregistry.com:5000/yinjjwin7base:latest
```

**Comment by yinjingjiu** [comment]
Hi @petrkotas  I tried, can't solve the mouse problem
```yaml
......
devices:
      inputs:
      - type: tablet
        bus: virtio
        name: tablet1
......
```
The result is still usb=off
```shell
/usr/bin/qemu-system-x86_64 ... -machine pc-q35-3.1, accel=kvm, usb=off ...
```
