### ISSUE TITLE
DataVolume feature gate is not enabled even thought the config map is created 

### ISSUE THREAD

**Issue by moadqassem** [kubevirt/kubevirt#2494]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
While I was trying to create a VirtualMachine with DataVolume enabled, I always get this error:
`The  "" is invalid: spec.template.spec.volumes[0]: DataVolume feature gate is not enabled `

Even though the configmap for enabling the DataVolume Feature Gate is actually created.

**What you expected to happen**:
I expect the VM to be created with DataVolumes enabled.

**How to reproduce it (as minimally and precisely as possible)**:
Create the VM from the yaml file as explained in the VM or VMI specifications section.

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- VM or VMI specifications:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
  labels:
    kubevirt.io: ""
data:
  feature-gates: "DataVolumes"
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
  namespace: kubevirt
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: alpine-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      source:
        http:
          url: http://cdi-http-import-server.kubevirt/images/alpine.iso 
```

- OS (e.g. from /etc/os-release):
Ubuntu-18.04 LTS 

- Kernel (e.g. `uname -a`):
`Linux Ubuntu-1804-bionic-64-minimal 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
