### ISSUE TITLE
Failed migrations are not properly reflected on the VMI

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2495]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

After a failed migration I see 

```
  migrationState:
    migrationUid: b0a83915-a7b6-11e9-a058-525500d15501
    sourceNode: node01
    targetNode: node02
    targetPod: virt-launcher-vmi-migratable-46t7x
```

on the VMI. If I try to create a new migration, I get

```
Error from server: error when creating "examples/migration-job.yaml": admission webhook "migration-create-validator.kubevirt.io" denied the request: in-flight migration detected. Active migration job (b0a83915-a7b6-11e9-a058-525500d15501) is currently already in progress for VMI vmi-migratable.
```

The migration object was not even present anymore and I did not do a force-delete, so with finalizers it would have been able to  clean this up.

**What you expected to happen**:

If a migration fails, the VMI status should be updated accordingly.

**How to reproduce it (as minimally and precisely as possible)**:

The target pod crashed when it was in the `PreMigrationTarget` preparations.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
