### ISSUE TITLE
Interfaces set in domain.spec ignored if networks field left as default

### ISSUE THREAD

**Issue by plwhite** [kubevirt/kubevirt#2577]
**BUG REPORT**

/kind bug

**What happened**:

When creating a VMI (either directly or through a VM or a VMIRS), the VMI ended up with the default values for interfaces, even if something different was supplied. In other words, create a VMI with (say)
~~~
interfaces:
- name: default
  model: e1000
~~~
using `kubectl apply`. As soon as you have done so, get the object you just created with `kubectl get -o yaml`. The interfaces part of the spec is now the default, i.e.  
~~~
interfaces:
- name: default
  bridge: {}
~~~
Note that I have tried a range of different things in interfaces (different model names, multiple interfaces, and so on). In every case the interfaces struct got changed to the default as if not specified.

The controller correctly seems to reject invalid values for interfaces if I try that.

**What you expected to happen**:

The interfaces field would be respected.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply -f ubuntuvmi.yaml` using the YAML below.

**Anything else we need to know?**:

Underlying issue here is that I am trying to run with an image old enough to not support virtio, and was investigating using a standard ubuntu 14.04 cloud image. That needs an interface type which is not virtio but e1000 (or something it supports).

**Environment**:
- KubeVirt version (use `virtctl version`): 0.19.0
- Kubernetes version (use `kubectl version`): 1.12.8
- VM or VMI specifications: See below
Running in an Azure cluster (default AKS configuration) though I do not think that is relevant.

~~~
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntuvmi
  labels:
    billy: bob
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
        cpu: 2
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: sata
      - name: emptydisk
        disk:
          bus: sata
      - disk:
          bus: sata
        name: cloudinitdisk
      interfaces:
      - name: default
        model: e1000       
  volumes:
  - name: containerdisk
    containerDisk:
      image: metaswitchglobal.azurecr.io/ubuntu:1404
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: ubuntu
        chpasswd: { expire: False }
        ssh_pwauth: True
~~~

**Comment by rmohr** [comment]
@plwhite our validation seems to fail, if only an interface is set, but not backing network.

Here the diff on how the VMI should look like:

```diff
$ diff vm.yaml vmi1.yaml 
27a28,30
>   networks:
>   - name: default
>     pod: {}
```

and the full spec:

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntuvmi
  labels:
    billy: bob
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
        cpu: 2
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: sata
      - name: emptydisk
        disk:
          bus: sata
      - disk:
          bus: sata
        name: cloudinitdisk
      interfaces:
      - name: default
        model: e1000       
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: metaswitchglobal.azurecr.io/ubuntu:1404
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: ubuntu
        chpasswd: { expire: False }
        ssh_pwauth: True
```
