### ISSUE TITLE
PodUnschedulable condition is added over and over instead of being replaced

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2581]
**Is this a BUG REPORT or FEATURE REQUEST?**:

We add pod conditions to the VMI, to make it more obvious if things go wrong. This logic does not seem to work. Instead of replacing an existing condition, it just appends it over and over.

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

just create a VMI without a PVC: `kubectl.sh create -f  examples/vmi-windows.yaml`.

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  - lastProbeTime: null
    lastTransitionTime: 2019-08-08T10:48:25Z
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: FailedPvcNotFound
    status: "False"
    type: Synchronized
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'failed to render launch manifest: didn''t find PVC disk-windows'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
