### ISSUE TITLE
Add `interfaceName` parameter to `pod` network option

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#2604]
/kind enhancement

We currently allow our users to use default `pod` interface (`eth0`), `multus` and `genie` networks as connections and plug them to their VMs [1]. However, there is one scenario, raised by our user, that we are not able to cover. In their setup, they use CNI plugin (for the default network) which plugs two interfaces in their pod, `eth0` and `mgmt0`. While the former is passed to the VM, latter is not and there is no way to make KubeVirt do that.

I suggest we should add a new attribute to `pod` network type. This attribute, let's call it `interfaceName`, would just specify name of an interface available in the pod, and override the default `eth0`. This interface may have been added there by CNI, initContainer, device plugin, we don't care.

The mentioned user would then be able to use following configuration to get access to both of their interfaces.

```yaml
kind: VM
spec:
  domain:
    devices:
      interfaces:
        - name: default
          masquerade: {}
        - name: mgmt
          bridge: {}
  networks:
  - name: default
    pod: {} # Stock pod network (eth0)
  - name: mgmt
    pod: # Secondary network created by CNI
      interfaceName: mgmt0
```

The one think I'm concern about is, that users would try to mount interfaces created by us (bridges). But I guess that should not affect anyone but the user.

Implementation-wise, it should be pretty straightforward, make `eth0` a default that can be overwritten by `interfaceName`, part of `pod` handling code.

[1] https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html#backend
