### ISSUE TITLE
IPv6 networking not working in Kubevirt VM

### ISSUE THREAD

**Issue by bharatnc** [kubevirt/kubevirt#2618]
> /kind bug

This is related to https://github.com/kubevirt/kubevirt/issues/1017

**What happened**:
```
# ping -6 google.com
ping: google.com: Name or service not known
# ping -6 2a00:1450:4009:809::200e
connect: Network is unreachable
```
Getting IPv6 Network unreachable

We have a IPv6 interface for Kubevirt VM but it's not working when we try to use IPv6 to reach out to other services in cluster or to the web.

**What you expected to happen**:
 I would expect ping to work on IPv6 and resolve

**How to reproduce it (as minimally and precisely as possible)**:

Followed this to get a basic interface setup: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html

cc: @fabiand

**Comment by fabiand** [comment]
hey, thanks for reporting - but I think this is known, but:

Please share your VM definition.
Did oyu use a multus backed or pod-network?

In KubeVirt the pod network is known to not support IPv& (yet) - even if
the underlying Kubernetes is configured in a native IPv6 way.

All in all IPv6 support is something we want to add - no question.

**Comment by kacpercf** [comment]
Hi, thanks for a quick answer!

We're using a pod network, happy to change if there is a workaround. 

VMIRS definition
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: agent-replica-set
  namespace: app-agents
  labels:
    app: app-agents
    role: replicaset
spec:
  replicas: 24
  selector:
    matchLabels:
      role: agent
  template:
    metadata:
      name: k8s-agent-
      namespace: app-agents
      labels:
        app: app-agents
        role: agent
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - name: emptydisk
            disk:
              bus: virtio
          - disk: {}
            name: agent-config-disk
            serial: CONFIGDISK
          interfaces:
          - name: default
            bridge: {}
        firmware:
          bootloader:
            efi: {}
        resources:
          requests:
            memory: 32Gi
      networks:
        - name: default
          pod: {}
      livenessProbe:
          initialDelaySeconds: 300
          tcpSocket:
            port: 8888
      terminationGracePeriodSeconds: 30
      volumes:
      - containerDisk:
          image: path_to_an_image
        name: containerdisk
      - name: emptydisk
        emptyDisk:
          capacity: 64Gi
      - configMap:
          name: agent-config
        name: agent-config-disk
```
