### ISSUE TITLE
An error occurred while uploading a local disk image to a PVC using CDI

### ISSUE THREAD

**Issue by biliwewe** [kubevirt/kubevirt#2710]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
An error occurred while uploading a local disk image to a PVC using CDI
```shell
$ ./virtctl image-upload --uploadproxy-url=https://192.168.1.101:31001  --image-path=/home/biliwewe/hostvm/win.img  --pvc-name=mypvc1  --pvc-size=50Gi --insecure --no-create
Using existing PVC default/mypvc1
Waiting for PVC mypvc1 upload pod to be running...
timed out waiting for the condition

```
**How to reproduce it (as minimally and precisely as possible)**:

1.  install cdi 
```shell
$ kubectl get pods -n cdi
NAME                               READY   STATUS    RESTARTS   AGE
cdi-apiserver-5b96f56bbb-l9hmp     1/1     Running   0          49m
cdi-deployment-7bd68f9b66-rhxsz    1/1     Running   0          49m
cdi-operator-68cbdf6596-mw25f      1/1     Running   0          51m
cdi-uploadproxy-597bcf6978-tnrmv   1/1     Running   0          49m
```
2. expose cdi-uploadproxy service(Use NodePort)
```shell
$ kubectl get svc -n cdi
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
cdi-api                    ClusterIP   10.43.176.241   <none>        443/TCP         51m
cdi-uploadproxy            ClusterIP   10.43.25.10     <none>        443/TCP         51m
cdi-uploadproxy-nodeport   NodePort    10.43.51.76     <none>        443:31001/TCP   49m

```
2. create StorageClass and pv, pvc:
 ```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/biliwewe/data/pv1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual

```
4. upload local image
```shell
$ ./virtctl image-upload --uploadproxy-url=https://192.168.1.101:31001  --image-path=/home/biliwewe/hostvm/win.img  --pvc-name=mypvc1  --pvc-size=50Gi --insecure --no-create
Using existing PVC default/mypvc1
Waiting for PVC mypvc1 upload pod to be running...
timed out waiting for the condition
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.21.0
- Kubernetes version (use `kubectl version`): v1.14.6
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 5.2.11-1.el7.elrepo.x86_64
