### ISSUE TITLE
new CRD for VirtualMachineImage

### ISSUE THREAD

**Issue by WoohyungHan** [kubevirt/kubevirt#2894]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
We can upload vm image using virtlctl image-upload with image path. However every time creating VM, we have to know exact image path or PVC to copy. If we have image repository with what image is included and its metadata, It can be very useful.

We have container registry disk and it works similarly, however the difference is VirtualMachineImage is admin by k8s and we can handle as kubernetes object.

**What you expected to happen**:
We can declare new CRD, like VirtualMachineImage.

```
kind: VirtualMachineImage
metadata:
  name: myvmi
  label:
  - os: ubuntu18.04
spec:
  fromUrl:
    url: <url of ubuntu 18.04 cloud image>
(or)
  fromPvc:
    pvcName: <pvc of ubuntu 18.04>
(or)
  fromRegistryDisk
    image: vmdisks/fedora25:latest
```

**How to reproduce it (as minimally and precisely as possible)**:
None

**Anything else we need to know?**:
None

**Environment**:
None

**Comment by JacksonKrauss** [comment]
Hello, I was thinking about working on this issue. Any tips on how to get started?

**Comment by petrkotas** [comment]
Hi @WoohyungHan I have a question, How do you image `VirtualMachineImage` would be used together with `VirtualMachine`? Thank you.

**Comment by WoohyungHan** [comment]
> Hello, I was thinking about working on this issue. Any tips on how to get started?

> Hi @WoohyungHan I have a question, How do you image `VirtualMachineImage` would be used together with `VirtualMachine`? Thank you.

@JacksonKrauss @petrkotas hi, i'm not sure 100% this is worth for now... however I think we can learn from the relationship of glance and cinder service in openstack. We can provision a VM with DataVolume and the DataVolume has a source of image. for now, this source is form of raw file or http url. I think we can change this as image service id (or name).

first user create VirtualMachineImageStore. VMIS has a pvc and it stores real image with metadata in etcd.

```yaml
kind: VirtualMachineImageStore
spec:
  pvc:
    name: {name of image store}
```

user can upload their image by using VirtualMachineImage. our contoller accept this CRD and download from source and store to pvc.

```yaml
kind: VirtualMachineImage
metadata:
  name: ubuntu 18.04
spec:
  source:
    http: "http..."
```

and then user can create a DataVolume with the VirtualMachineImage

```yaml
kind: DataVolume
spec:
  source:
    VirtualMachineImage: ...
  pvc:
     ...
```

so what's diff with previous? We can see our vm images like this.

```shell
kubectl get VritualMachineImage

name                 source (...)
ubuntu18.04        ...
```
