### ISSUE TITLE
Add Sysprep support

### ISSUE THREAD

**Issue by patricklundquist** [kubevirt/kubevirt#2902]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
We would like Sysprep support, similar to how there is some support for cloud-init and ignition. It will help us deploy Window's VMs.

**What you expected to happen**:
Enable Sysprep support via a feature flag. Add VM annotation to use it. 

**Anything else we need to know?**:
Found Sysprep mentioned [in the docs](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/startup-scripts.html#sysprep), but didn't see any corresponding issue, so filed this for tracking and to show interest.

**Comment by rmohr** [comment]
I wonder how big such files usually are. We should ensure that our VMIs are not too big. We are actually limiting the max size of cloud-init payload to `2048` byte.

What are typical `Unattended.xml` and `Autounattended.xml` file sizes? If `2048` is impractically small, I wonder if we should in general only allow attaching these via secrets/configmaps.

By the way, as far as I know sysprep and setup.exe are looking for these files on removable devices. Could you in principle just create a `secret` or `configmap` which looks like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysprep-config
data:
  Unattended.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <unattend xmlns="urn:schemas-microsoft-com:unattend"
    [...]
    </unattend>
  Autounattended.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <unattend xmlns="urn:schemas-microsoft-com:unattend"
    [...]
    </unattend>
```

and attach it as cdrom:

```yaml
metadata:
  name: testvmi-sysprep
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 10G
    devices:
      disks:
      - name: sysprep
        cdrom:
          bus: virtio
      - name: mypvcdisk
        disk:
          bus: virtio
  volumes:
    - name: mypvcdisk
      persistentVolumeClaim:
        claimName: windows-image
    - name: sysprep
      configmap:
        name: sysprep-config
```

In this example I assume that the attached PVC contains an image which is prepared for sysprep (would consume `Unattended.xml`), but  it could as well be used with an empty PVC and an install iso attached as cdrom (would consume `Autounattended.xml`).
