### ISSUE TITLE
suggest to add pvc definition into examples

### ISSUE THREAD

**Issue by jichenjc** [kubevirt/kubevirt#2912]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
when using examples/vmi-pvc.yaml , I got an error than vmi enter pending status
and complained the pvc is not found, actually the vmi and pv are created 
so we need create a pvc sample e.g
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-alpine
spec:
  volumeName: host-path-disk-alpine
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
