### ISSUE TITLE
Slow traffic rate through VM created through Kubevirt

### ISSUE THREAD

**Issue by mbhatnagar21** [kubevirt/kubevirt#2918]
Kubevirt version = 15.0
Kubernetes version = 1.14.1-00

While passing traffic through VM created created through Kubevirt , I am getting really low traffic rate . Expected rate is around 1 Gbps but I am just getting 64 Mbps . Can you pease suggest some way to increase this traffic rate . 

Please find below yaml file I have used for creation of VM.

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vmfx-multi-inf
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: dfx2
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: sata
            name: rootfs
          interfaces:
          - name: default
            bridge: {}
          - name: enp2s0
            bridge: {}
          - name: enp3s0
            bridge: {}
          - name: enp4s0
            bridge: {}
        resources:
          requests:
            memory: 4048M
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: ovs-conf
        name: enp2s0
      - multus:
          networkName: ovs-conf
        name: enp3s0
      - multus:
          networkName: ovs-conf
        name: enp4s0
      volumes:
        - name: rootfs
          containerDisk:
            image: fxp-singledisk-cdisk
```
