### ISSUE TITLE
Windows VM failed to start that has larger size

### ISSUE THREAD

**Issue by surazzarus** [kubevirt/kubevirt#2928]
- KubeVirt version: v0.24.0
- Kubernetes version: v1.15.5
- OS: Ubuntu 16.04.6 LTS (Xenial Xerus)
- Kernel: Linux dab7ece2-01a7-4ac0-ae18-515b4294b3f0 4.15.0-65-generic #74~16.04.1-Ubuntu SMP Wed Sep 18 09:51:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I use software emulation using the configmap, since the hardware doesn't support virtualization as described in: https://kubevirt.io/user-guide/docs/latest/administration/intro.html#virtualization-support

Installed kubevirt with the yaml: https://github.com/kubevirt/kubevirt/releases/download/v0.24.0/kubevirt.yaml

VMI Specification for windows:
https://github.com/kubevirt/kubevirt/blob/master/examples/vmi-windows.yaml
But I am not using PVC instead used containerDisk as below:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: winserver2012-vmi
  labels:
    kubevirt.io/vm: qc-kubevirt-vm
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 3
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - name: virtiocontainerdisk
        cdrom:
          bus: sata
      interfaces:
      - masquerade: {}
        model: e1000
        name: default
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
    machine:
      type: q35
    resources:
      requests:
        memory: 3Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  nodeSelector:
    kubernetes.io/hostname: 10.0.3.7
  volumes:
    - name: containerdisk
      containerDisk:
        image: myregistry/vms/winserver2012:latest
        imagePullPolicy: IfNotPresent
        imagePullSecret: secret
    - name: virtiocontainerdisk
      containerDisk:
        image: kubevirt/virtio-container-disk
    - name: emptydisk
      emptyDisk:
        capacity: 50Gi
```

I build the image out of qcow2 as described : https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerdisk

**What happened**:

Since the VM image i build is large 6gb approx, whenever I try to deploy, it shows me an error approx after 10mins (I think it is normal to wait for 10mins or more since it has to pull this 6gb image). But everytime it fails and the error can be seen in the logs below:

Virt-launcher logs:
![image_2019_12_10T08_54_08_382Z](https://user-images.githubusercontent.com/9981502/70524541-a9948e00-1b45-11ea-9bdc-ced64af67b65.png)

Virt-handler logs:
![image_2019_12_10T08_55_24_643Z](https://user-images.githubusercontent.com/9981502/70524602-d3e64b80-1b45-11ea-917f-1ca9c763ceb9.png)

And the pod never gets started. 
This is first issue i am having for larger images.

So, for the workaround I manually pulled the image on the node and since I have `imagePullPolicy: IfNotPresent` , it can take the image from the node. 
Again the VMI doesn't gets deployed and it failed. 
When I see `kubectl get vmi`, it was showing the status `scheduled` for a while and finally it failed.
Below is the new log form Virt-launcher.
![image_2019_12_10T11_12_08_434Z](https://user-images.githubusercontent.com/9981502/70525291-49065080-1b47-11ea-85b6-069d3c245280.png)

Please let me know what steps should I follow or did wrong during the process. 
Also to let you know, linux VMs work fine for me.
