### ISSUE TITLE
No bootable device detected for Windows Server 2012 Evaluation image. 

### ISSUE THREAD

**Issue by tssavita** [kubevirt/kubevirt#2931]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
No bootable device detected, when connecting to VM through VNC. 

![Screenshot from 2019-12-12 13-37-44](https://user-images.githubusercontent.com/2744118/70707121-b9dc7280-1cd7-11ea-90b0-ecd25ceacc6d.png)

**What you expected to happen**:
Windows installation should start. 

**How to reproduce it (as minimally and precisely as possible)**:
Download Windows Server 2012 image from: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012
Convert it to img. 
kubectl create -f vmi.yaml
vmi.yaml: 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: win12k
  name: win12k
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: sata
        name: host-disk
    machine:
      type: ""
    resources:
      requests:
        memory: 12G
  terminationGracePeriodSeconds: 0
  volumes:
  - hostDisk:
      path: /home/gamer/Downloads/win12eval.img
      type: Disk
    name: host-disk
status: {}
```

**Anything else we need to know?**:
- The same image works in QEMU/KVM. 
First suspicion was that firmware used by Kubevirt was not detecting disk as bootable. I've tried setting the bootOrder for the disk to 1 and machine type to "q35". (For whatever it may be worth..) But no success. 
- I also tried the "Inject a VirtualMachineInstance disk into a container image" from here: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html, using a the qcow2 image of an existing Windows VM. It yields the same result as above. 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.22.0
- Kubernetes version (use `kubectl version`): v1.17.0
- VM or VMI specifications: Mentioned in yaml file above. 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 19.04
- Kernel (e.g. `uname -a`): Linux gamer-eap-gpu 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmohr** [comment]
The following things come to my mind:

 1) vewrifying that the img contains what you expect
 2) Should the disk be a `cdrom` drive?

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: win12k
  name: win12k
spec:
  domain:
    devices:
      disks:
      - cdrom:
          bus: sata
        name: host-disk
    machine:
      type: ""
    resources:
      requests:
        memory: 12G
  terminationGracePeriodSeconds: 0
  volumes:
  - hostDisk:
      path: /home/gamer/Downloads/win12eval.img
      type: Disk
    name: host-disk
status: {}
```

**Comment by tssavita** [comment]
Thanks so much for the quick reply! 

1. I booted the image using QEMU/KVM and it was the right file. (Assuming that's what you meant by verifying the image..)
2. I tried using the disk type as cdrom(the above yaml). But the VMI gets stuck in Scheduling state. 

However, I got one step ahead: I explicitly **set the firmware to UEFI by adding the following under spec.**
```
firmware:
  bootloader:
    efi: {}
```
The VM booted and the Windows Setup shows up. 

1. I can't scroll down to access the Next button. (See screenshot below)
2. I tried zooming out but the result is just the same. Next button doesn't appear in the frame. (Diagram below)

![image](https://user-images.githubusercontent.com/2744118/70738064-43119a80-1d14-11ea-93da-73ae74949f69.png)

**Comment by tssavita** [comment]
Forgot to add this: My keyboard and mouse are not usable inside the VNC viewer. So I can't press tab multiple times and reach the Next button.

**Comment by rmohr** [comment]
@tssavita I think that you need to add an input device. Can you try adding 

```yaml
inputs:
  - type: tablet
    bus: usb
    name: tablet1
```

to the `devices` section?

More info here: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/virtualized-hardware-configuration.html#input-devices.

I personally find it always confusing that I have to add a `tablet` device to get a mouse, but I hope that solves it for you.

**Comment by rmohr** [comment]
Oh btw. I think that you should also enable a few more features to get a better experience with windows in kubevirt. That example has most setting: https://github.com/kubevirt/kubevirt/blob/master/examples/vm-template-windows2012r2.yaml.

It is especially interesting that we also set an explicit uuid for the machine in the spec, so that the OS does not think that it runs on a different vm on each start. That is btw. something which you don't have to care about when you use a `VirtualMachine`. It ensures that the uuid does not change between restarts.

**Comment by DrissiReda** [comment]
I have the same problem, but even with UEFI mode, it doesn't work. qcow2 and raw images that work perfectly with qemu, do not work with kubevirt.

**Comment by rmohr** [comment]
Can you share your vm yaml?

**Comment by DrissiReda** [comment]
This is how I create the pvc nanodisk using CDI and virtctl
```bash
virtctl image-upload --pvc-name=nanodisk --image-path=/home/red/nanoserver.qcow2 --pvc-size=2Gi
```

My vmi-windows.yaml:

```yaml
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows
  name: vmi-windows
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: sata
        name: pvcdisk
      interfaces:
      - masquerade: {}
        model: e1000
        name: default
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
      bootloader:
        efi: {}
    machine:
      type: q35
    resources:
      requests:
        memory: 2Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: nanodisk

```
