### ISSUE TITLE
VMI with a configmap specified as volume failed to be created

### ISSUE THREAD

**Issue by luckyfengyong** [kubevirt/kubevirt#2943]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
The VMI with a configmap specified as volume failed to be created
**What you expected to happen**:
The VMI is created successfully

**How to reproduce it (as minimally and precisely as possible)**:
Create VMI with the following spec

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-config
spec:
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: host03
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - disk: {}
        name: app-config-disk
        # set serial
        serial: CVLY623300HK240D
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
        - name: default
          bridge: {} 
  networks:
  - name: default
    pod: {}
  volumes:
  - configMap:
      name: app-config
    name: app-config-disk
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
        bootcmd:
          # mount the ConfigMap
          - "mkdir /mnt/app-config"
          - "mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
```
And then I get

```
# kubectl describe vmi testvmi-config
Name:         testvmi-config
Namespace:    default
Labels:       kubevirt.io/nodeName=host03
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachineInstance","metadata":{"annotations":{},"name":"testvmi-config","namespace":"def...
              kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-12-19T11:44:47Z
  Generation:          1760
  Resource Version:    23837224
  Self Link:           /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvmi-config
  UID:                 eabbcb41-6f63-4fa4-bb04-c9f1a5dadc9c
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
        Name:    app-config-disk
        Serial:  CVLY623300HK240D
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   emptydisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Machine:
      Type:  
    Resources:
      Requests:
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Node Selector:
    kubernetes.io/hostname:          host03
  Termination Grace Period Seconds:  30
  Volumes:
    Config Map:
      Name:  app-config
    Name:    app-config-disk
    Container Disk:
      Image:  kubevirt/fedora-cloud-container-disk-demo:latest
    Name:     containerdisk
    Empty Disk:
      Capacity:  2Gi
    Name:        emptydisk
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
bootcmd:
  # mount the ConfigMap
  - "mkdir /mnt/app-config"
  - "mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
    Name:  cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI with a bridge interface connected to a pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
  Guest OS Info:
  Interfaces:
    Ip Address:      192.168.25.227
    Name:            default
  Migration Method:  BlockMigration
  Node Name:         host03
  Phase:             Scheduled
  Qos Class:         Burstable
Events:
  Type     Reason            Age                     From                       Message
  ----     ------            ----                    ----                       -------
  Normal   SuccessfulCreate  6m40s                   virtualmachine-controller  Created virtual machine pod virt-launcher-testvmi-config-drpw5
  Warning  SyncFailed        5m25s (x25 over 5m26s)  virt-handler, host03       server error. command SyncVMI failed: "LibvirtError(Code=20, Domain=20, Message='missing target information for device /var/run/kubevirt-private/config-map-disks/app-config-disk.iso')"
```

The file of  `/var/run/kubevirt-private/config-map-disks/app-config-disk.iso` actually is created in the container of `virt-launcher`

```
# nsenter -t 86393 --ipc --uts --net --pid --mount /bin/bash
# ls -l /var/run/kubevirt-private/config-map-disks/app-config-disk.iso
-rw-r--r--. 1 qemu qemu 376832 Dec 19 11:45 /var/run/kubevirt-private/config-map-disks/app-config-disk.iso
```
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.24.0
- Kubernetes version (use `kubectl version`): v1.15.1
- VM or VMI specifications: See above
- Cloud provider or hardware configuration: VM created from Openstack
- OS (e.g. from /etc/os-release):  CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):  3.10.0-693.el7.x86_64
- Install tools:  kubeadm for k8s cluster, install doc for kubevirt
- Others:
