### ISSUE TITLE
When setting a deafult network with multus, need to specify the namespace.

### ISSUE THREAD

**Issue by zakkg3** [kubevirt/kubevirt#3069]
/kind bug
this works:
```
networks:
  - name: access
    multus: # multus network as default
      default: true
      # WORKAROUND: due to bug (probably) in kubevirt need to namespace
      # prefix the network when not using the default pod network.
      networkName: {{ namespace }}/access
```

this does not work (its looking for the network attach definition on the kube-system namespace...)

```
networks:
  - name: access
    multus: # multus network as default
      default: true
      networkName: access
```
