### ISSUE TITLE
Add priorityClassName support to VirtualMachineInstanceSpec

### ISSUE THREAD

**Issue by HenriTEL** [kubevirt/kubevirt#3089]
/kind enhancement
It would be great to have the ability to configure VMIs like:  
```yaml
kind: VirtualMachineInstance
metadata:
  name: my-vmi
spec:
  priorityClassName: my-prio
```
So that the `virt-launcher` pod can be scheduled in priority.
