### ISSUE TITLE
Failed to create VM in the enviroment with the devicemapper as the storage driver of Docker

### ISSUE THREAD

**Issue by luckyfengyong** [kubevirt/kubevirt#3117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
In the enviroment with the devicemapper as the storage driver of Docker, VMI failed to be started with error message of `failed to detect root mount info of containerDisk` in the log of `virt-hanlder`. 

The root cause probably is that `virt-handler` assume in the pods of `virt-launcher`, the rootfs of `/` is mount from `/` which is true with the overlay fs as the storage driver of Docker. However, when devicemapper is configured as the storage driver of Docker, it is mouted from `/rootfs`. 

In /proce/$pid/mountinfo, it is shown as something like

```
...
1626 850 253:29 /rootfs / rw,relatime - ext4 /dev/mapper/docker-253:2- .....
...
```
With a fix to allow `/rootfs` to be recognized as root mount info of containerDisk, the issue is resolved and VM is created successfully.

**What you expected to happen**:

Create VM successfully in the enviroment with the devicemapper as the storage driver of Docker

**How to reproduce it (as minimally and precisely as possible)**:
Configure devicemapper as the storage driver of Docker and then create VMI according to kube-virt user doc.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.26.0
- Kubernetes version (use `kubectl version`): v1.15.0
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-yong1
  namespace: fst-manage
spec:
  terminationGracePeriodSeconds: 30
  domain:
    clock:
      timezone: "Asia/Shanghai"
      timer: {}
    resources:
      requests:
        cpu: 2
        memory: 2048M
    devices:
      disks:
      - name: containerdisk
        disk: 
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
  - name: containerdisk
    containerDisk:
      image: 192.39.12.230:20202/kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 3.10.0
