### ISSUE TITLE
Failed to create VM in the environment with the default umask of OS configued other than `0022`

### ISSUE THREAD

**Issue by luckyfengyong** [kubevirt/kubevirt#3118]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
In our product environment, the umask of OS is configured as `0077` by default.  In such enviroment, Kubevirt failed to create VM with the following error message from `virt-launcher`.

```
Cannot access storage file `/var/run/libvirt/empty-disks/emptydisk.qcow2` (as uid:107, gid:107): Permission denied`
```
The directory of `/var/run/libvirt/empty-disks` is created with the access mode of `drwxr-s---` of owner of `root`.

Even though in `CreateTemporaryDisks()`, the directory of `/var/run/libvirt/empty-disks/` is created by `os.MkdirAll(EmptyDiskBaseDir, 0777)`, because of the `umask`, the perm of `0777` is changed to `0700`.  There actually are more permission issues of directories used by qume to create VM. They share the same root cause of `umask`.

After add the following tmp fix in main() of virt-launcher, the issue is resolved. 

```
  mask := syscall.Umask(0)
  defer syscall.Umask(mask)
```

**What you expected to happen**:
Kubevirt work in the env with the umask of OS configured as `0077`.

**How to reproduce it (as minimally and precisely as possible)**:
Configure the umask of OS as `00770, and then deploying docker/k8s and kubevirt, after that create VMI according to kube-virt user doc.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.26.0
- Kubernetes version (use `kubectl version`): v1.15.0
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-yong1
  namespace: fst-manage
spec:
  terminationGracePeriodSeconds: 30
  domain:
    clock:
      timezone: "Asia/Shanghai"
      timer: {}
    resources:
      requests:
        cpu: 2
        memory: 2048M
    devices:
      disks:
      - name: containerdisk
        disk: 
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
  - name: containerdisk
    containerDisk:
      image: 192.39.12.230:20202/kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 3.10.0
