### ISSUE TITLE
Add and option to add disk capacity to a containerDisk

### ISSUE THREAD

**Issue by alosadagrande** [kubevirt/kubevirt#3130]
/kind enhancement

**What happened**:
containerDisk creates a VM with the block size and root filesystem size specified in the image (qcow2/raw). In case I want to have the same container image in different sizes I need to resize the qcow2 and expand the partition. Then containerized the image and push it to a container registry. 

Eventually I end up with the same "base" image copied multiple times due to the needs of being resized and root filesystem expanded (different size flavours)

The process is the following:

```
$ qemu-img resize golden-devstation-centos8-disk.qcow2 10G
Image resized.
```
The expansion is executed on the root partition, which in case of our golden image is /dev/vda2 partition. It must be checked previously. Note that a copy of the golden image has been created and that’s the one expanded.

```
$ cp golden-devstation-centos8-disk.qcow2 golden-devstation-centos8-disk-10G.qcow2

$ virt-resize --expand /dev/vda2 golden-devstation-centos8-disk.qcow2 golden-devstation-centos8-disk-10G.qcow2
[   0.0] Examining golden-devstation-centos8-disk.qcow2
**********

Summary of changes:

/dev/sda1: This partition will be left alone.

/dev/sda2: This partition will be resized from 2.7G to 9.0G.  The
filesystem xfs on /dev/sda2 will be expanded using the ‘xfs_growfs’
method.

**********
[   2.2] Setting up initial partition table on golden-devstation-centos8-disk-10G.qcow2
[   3.1] Copying /dev/sda1
[   4.0] Copying /dev/sda2
 100%
[   8.5] Expanding /dev/sda2 using the ‘xfs_growfs’ method

Resize operation completed with no errors.  Before deleting the old disk,
carefully check that the resized disk boots and works correctly.
Finally, verify that the image meets the expected values:
```
```
$ qemu-img info golden-devstation-centos8-disk-10G.qcow2
image: golden-devstation-centos8-disk-10G.qcow2
file format: qcow2
virtual size: 10G (10737418240 bytes)
disk size: 1.8G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

**What you expected to happen**:
I would probably expect to set the capacity of a containerDisk in a similar way it is specified with an emptyDisk.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
There is a blog post being reviewed that explains how to create custom-built containerized images. This is the https://github.com/kubevirt/kubevirt.github.io/pull/535 - probably will be published in KubeVirt's blog next week. In there I talk about the resizing and expansion, since the exposed use case is a software factory that allows its developers to run standardized VMs to check their code in a specific environment before commiting it.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.26.1
- Kubernetes version (use `kubectl version`): 1.16.2

**Comment by rmohr** [comment]
That would be a nice feature. However I am not sure how this should work. We could indeed add a `capacity` field. That would also lead to a bigger overlay disk, but it would still not increase the root partition size. We would potentially also have to know about the partition which should be extended and we would have to support the file system format in the conversion process.

Finally, depending on the file system we may then also not really profit much from the container layer cache, if we modify the whole partition.

@davidvossel any thoughts?

**Comment by davidvossel** [comment]
> @davidvossel any thoughts?

My expectation is that if someone is wanting to use a container disk with VMI's that need dynamic storage capacity, that that dynamic capacity would be added using an emptyDir rather than modifying the partitions within the containerDisk's qcow image.

I wouldn't anticipate many people would be in a situation where the root partition needs to be dynamically resized on a per VMI basis.

**Comment by rmohr** [comment]
Would you just need capacity in the sense of specifying it on a pod emptyDir, to limit it, or would you need disk resizing?

/reopen

**Comment by rmohr** [comment]
I think we never researched this end to end. If it would be possible to resize a disk without having to touch a backing-disk this may be possible. Otherwise we would loose the overlay benefit, since touching the base file would copy it completely.

**Comment by davidvossel** [comment]
> Hello, I have similar requirement. Did we have feature to add capacity field for primary partition(root partition)?

hey @prtkdave, before we go too far down this path of trying to resize container disks, i just wanted to verify that using an [emptyDisk](http://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#emptydisk) isn't sufficient for your use case?

**Comment by prtkdave** [comment]
hi @davidvossel , we want to attach or want flexibility to mention the size of root partition not additional disk. For example, when we create any instance on AWS we mention OS image and then get the flexibility to select the root partition size. Similar thing we are trying with kube-virt. Hope this helps. Let me know , if you need any further information

**Comment by davidvossel** [comment]
> For example, when we create any instance on AWS we mention OS image and then get the flexibility to select the root partition size. Similar thing we are trying with kube-virt. 

You can do this today with containerDisks if you're willing to use PVCs. I believe during DataVolume import, that containerDisks are automatically expanded to fit the pvc size. So, for example, in the yaml below that alpine image should get expanded to 200Gi once it is imported to the PVC using the DataVolume flow.


```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: alpine-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: local
      source:
        http:
          url: docker://registry:5000/kubevirt/alpine-container-disk-demo:devel
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1

```
