### ISSUE TITLE
panic: Search domain is not valid: 'DHCP'

### ISSUE THREAD

**Issue by watermelon-brother** [kubevirt/kubevirt#3187]
**What happened**:
when I run the vm ,define below
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: testvm1
  name: testvm1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: testvm1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/cirros-container-disk-demo:latest
      - cloudInitNoCloud:
          userDataBase64: IyEvYmluL3NoCgplY2hvICdwcmludGVkIGZyb20gY2xvdWQtaW5pdCB1c2VyZGF0YScK
        name: cloudinitdisk
```
the vmi virt-launcher-testvm-vc7g9 states:
```shell
NAME                         READY   STATUS    RESTARTS   AGE
test-7b48b75784-79sv7        1/1     Running   0          112m
virt-launcher-testvm-vc7g9   0/2     Error     0          34s
```
locking in the logs:
```shell
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: eth0, IP: 10.42.0.54, Mask: ffffff00, MAC: 0a:58:0a:2a:00:36, Gateway: 10.42.0.1, MTU: 1450}","name":"vm-http-datavolume","namespace":"default","pos":"podinterface.go:258","timestamp":"2020-03-21T08:07:35.905419Z","uid":"3c3582a6-edfe-4ab1-8d67-2b527998a0b1"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n+\u0000\n","pos":"converter.go:1508","timestamp":"2020-03-21T08:07:35.905569Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local DHCP","pos":"converter.go:1509","timestamp":"2020-03-21T08:07:35.905640Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-private/vmi-disks/datavolumevolume/disk.img set tonone","pos":"converter.go:175","timestamp":"2020-03-21T08:07:35.905896Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2020-03-21T08:07:35.905995Z"}
{"component":"virt-launcher","level":"error","msg":"failed to run DHCP: Search domain is not valid: 'DHCP'","pos":"common.go:291","timestamp":"2020-03-21T08:07:35.906065Z"}
panic: Search domain is not valid: 'DHCP'
goroutine 63 [running]:
```
my k8s pod everything is ok except the kubevirt virt-launch-pod.

my host machine /etc/resolve.conf
```shell
[vagrant@rke-helm kubevirt-v0.26.0]$ sudo vim /etc/resolv.conf
# Generated by NetworkManager
search DHCP
nameserver 10.0.2.3
```
why this problem happen? Please help me....
**Environment**:
- KubeVirt version (0.26)
- Kubernetes version (1.17.x)
