### ISSUE TITLE
Cannot start VM with clock timezone set

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/kubevirt#3304]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I tried to create VM with following clock configuration:
```yaml
    spec.template.spec:
      domain:
        clock:
          timezone: "America/New_York"
          timer: {}
```
and the VM startup fails due to (virt-launcher log):
```
{"code":1,"component":"virt-launcher","level":"error","msg":"internal error: missing 'timezone' attribute for clock with offset='timezone'","pos":"virDomainDefParseXML:20623","subcomponent":"libvirt","thread":"37","timestamp":"2020-04-16T12:21:47.979000Z"}
```

**What you expected to happen**:
I expect the VM to start correctly and have clock configured with given timezone.

**How to reproduce it (as minimally and precisely as possible)**:
With vm specification (listed later) in `fedora.yaml` file:
`kubectl apply -f fedora.yaml`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.28.0 
`Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes version (use `kubectl version`): v1.16.2 (CRC)
`Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"aa10b5b", GitTreeState:"clean", BuildDate:"2020-03-16T18:11:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
`
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    app: fedora
    vm.kubevirt.io/template: fedora-server-tiny
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.9.0
  name: fedora
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora
        kubevirt.io/size: tiny
    spec:
      domain:
        clock:
          timezone: "America/New_York"
          timer: {}
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: rootdisk
        dataVolume:
          name: fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: fedora
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        http:
          url: https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.raw.xz
```
- Cloud provider or hardware configuration: Lenovo T490s
- OS: Fedora 31 (Workstation Edition)
- Kernel: 5.5.13-200.fc31.x86_64
- Install tools: N/A
- Others: N/A
