### ISSUE TITLE
port-forward with masquerade binding does not work from outside the cluster

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

VM is not accessible via NodePort Service type.

**What you expected to happen**:

It should be accessible.

**How to reproduce it (as minimally and precisely as possible)**:

Create a VM and expose its ssh (port 22) with `port-forward`.

**Anything else we need to know?**:

The issue is caused by the fact that while ClusterIP services are forwarded to the PodIP of virt-launcher, with NodePort (used for external accessibility of services) they are forwarded to loopback device of the port. KubeVirt does not push the traffic from the loopback device further to the VM. In order to avoid this issue, ports exposed by the service have to be explicitly stated in the VM definition as described here:  https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=masquerade

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mazzystr** [comment]
Is this issue still applicable?  I don't see this behavior with the following vm and service manifests....

vm manifest...
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: win2k19
    special: key
  name: testvm
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: testvm
        special: key
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          blockMultiQueue: true
          disks:
          - disk:
              bus: sata
            name: disk0
            cache: none
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: testvm
```

service manifest...
```
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
    - port: 8096
      nodePort: 30761
      targetPort: 8096
  selector:
    special: key
  type: NodePort
```

**Comment by phoracek** [comment]
@mazzystr try setting the target port in the masquerade binding. I believe it should fix this issue. Just note that it would employ masquerade binding instead of bridge, so you would see a different IP in the VM.

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: win2k19
    special: key
  name: testvm
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: testvm
        special: key
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          blockMultiQueue: true
          disks:
          - disk:
              bus: sata
            name: disk0
            cache: none
          interfaces:
          - name: default
            masquerade: {}
            ports:
            - name: special
              port: 8096
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: testvm
```

https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=frontend
