### ISSUE TITLE
multus-multiple-net  connect failed 

### ISSUE THREAD

**Issue by llhhbc** [kubevirt/kubevirt#3331]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I have two vmi with linux image, get multi network. but can't connect with eth1. (eth0 is pod's network, It's work.  eth1 is macvlan network, It's not work.)

**What you expected to happen**:
Both network should work.

**How to reproduce it (as minimally and precisely as possible)**:
I have install multus (https://github.com/intel/multus-cni) ,  and It is work when I create two pod with busybox, can connect to each other.
Then I try to crate vmi use multus network, It doesn't work.

**Anything else we need to know?**:
Here is my vm ip addr info:
```shell
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc pfifo_fast state UP qlen 1000
    link/ether 2a:d1:d2:ba:e9:30 brd ff:ff:ff:ff:ff:ff
    inet 101.244.217.144/32 brd 101.244.217.144 scope global dynamic eth0
       valid_lft 86310011sec preferred_lft 86310011sec
    inet6 fe80::28d1:d2ff:feba:e930/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UP qlen 1000
    link/ether e2:6c:f8:5b:4d:e8 brd ff:ff:ff:ff:ff:ff
    inet 172.168.1.207/24 brd 172.168.1.255 scope global dynamic eth1
       valid_lft 86310015sec preferred_lft 86310015sec
    inet6 fe80::e06c:f8ff:fe5b:4de8/64 scope link
       valid_lft forever preferred_lft forever
```

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "br_eth_cls",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.168.1.0/24",
        "rangeStart": "172.168.1.200",
        "rangeEnd": "172.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.168.1.1"
      }
    }'
```
my Host network info:
```
11: br_eth_cls: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether 90:e2:ba:84:93:d5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.3/24 brd 192.168.2.255 scope global br_eth_cls:1
       valid_lft forever preferred_lft forever
    inet 172.160.0.1/24 scope global br_eth_cls
       valid_lft forever preferred_lft forever
    inet6 fe80::92e2:baff:fe84:93d5/64 scope link
       valid_lft forever preferred_lft forever
```

**Environment**:
- KubeVirt version (use `virtctl version`): 0.27
- Kubernetes version (use `kubectl version`): 1.18
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: testbase
  name: testbase
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      interfaces:
      - bridge: {}
        name: default
      - bridge: {}
        name: macvlan
    machine:
      type: ""
    resources:
      requests:
        memory: 2G
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: kube-system/macvlan-conf
    name: macvlan
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: base-linux:v1.0
    name: containerdisk
```
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.4
- Kernel (e.g. `uname -a`): Linux qfusion 3.10.0-693.el7.x86_64
- Install tools: 
- Others:
