### ISSUE TITLE
Allow for customization of virt-operator created deployments, daemonset

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#3365]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What you expected to happen**:

Allow arbitrary json patches to be provided to virt-operator in order to customize virt-handler daemonset, virt-api deployment, and virt-controller deployment. Use cases include setting environment variables, configuring cpu/memory limits, applying custom labels or selectors for scheduling pods, and more.

**Comment by davidvossel** [comment]
Did you have any thoughts on how the patches could be provided? Essentially, where would these patches live, and how would virt-operator know to apply them?

**Comment by ashleyschuett** [comment]
If we want to do this as stated would it make sense that these patches get stored in a ConfigMap as such? 

```
apiVersion: v1
kind: ConfigMap
metadata:
 name: kubevirt-patch-xxx
 namespace:  kubevirt
data: 
  component: "handler|api|controller"
  patch: 
    spec:
      template:
        spec:
          env:
          - name: OPERATOR_IMAGE
            value: "some-custom-image/kubevirt"
```
This seems like it could be complicated to know if each component is in the correct state at all times. As we would have to calculate the desired state form multiple configmaps and I'm not sure how that would work for setting the `targetDeploymentConfig` on the kubevirt CR. 

Another option could also be to do something similar to my PR #3402. 
Example: 
```
type KubeVirtSpec struct {
       ... 
	HandlerConfiguration    ComponentConfiguration `json:"handlerConfiguration,omitempty"`
	APIConfiguration        ComponentConfiguration `json:"apiConfiguration,omitempty"`
	ControllerConfiguration ComponentConfiguration `json:"controllerConfiguration,omitempty"`
}

type ComponentConfiguration struct {
	Env         corev1.EnvVar               `json:"env,omitempty"`
	Labels      map[string]string           `json:"labels,omitempty"`
	Annotations map[string]string           `json:"annotations,omitempty"`
	Selector    metav1.LabelSelector        `json:"selectors,omitempty"`
	Resources   corev1.ResourceRequirements `json:resources",omitempty"`
	Flags       map[string]string           `json:"flags,omitempty"`
}
```

This would be less flexible however. But we can then predictably merge these fields (like is being done in the previously mentioned PR) when creating the deployments/ds and then the `targetDeploymentConfig` would work as it currently does.

**Comment by davidvossel** [comment]
> If we want to do this as stated would it make sense that these patches get stored in a ConfigMap as such?

Building off that configmap idea, what if added a patch list to the kubevirt object itself.

```
type ComponentPatch struct {
        // defines the component's type
        metav1.TypeMeta              `json:",inline"`
        // name of the component
        Name    string `json:"componentName"`
        // patch data
        Patch    string `json:"patch"`
        // defines how to apply the patch
        PatchType               types.PatchType `json:"patchType"`
}

type KubeVirtSpec struct {
       ... 
        ComponentPatches []ComponentPatch `json:"componentPatches`
}
```

This would kind of align with usage of the kubectl patch [1] command that people are probably already familiar with.

so, taking one of the examples in [1]

```
kubectl patch sa default --type='json' -p='[{"op": "add", "path": "/secrets/1", "value": {"name": "whatever" } }]'
```

would become something like

```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  imagePullPolicy: IfNotPresent
  componentPatches
  - name sa
    type: Secret
    patch: '[{"op": "add", "path": "/secrets/1", "value": {"name": "whatever" } }]'
    patchType: 'json'
```

would that make sense you think?

1. https://kubernetes.io/docs/reference/kubectl/cheatsheet/#patching-resources

**Comment by rmohr** [comment]
I would suggest to patch the objects after they are loaded from the dumped install strategy. We can enable the status/spec separation for CRDs, so that we get the generation metadata bumped whenever the spec changes. Like deployments, we can on every generation bump make a snapshot (controller revisions), compare the two different revisions, and detect this way theoretically even on a per-object level if we need to do something again.

**Comment by fabiand** [comment]
+1 on a list of patches in general,

however I wonder if we should have the api to be a bit more specific and also allow - in future - to introduce alternative ways to modify the deployment, i.e.

```
kind: KubeVirt
spec:
  customizeComponents:
    patches:
    - name: sa
      type: Secret
      patch: '[{"op": "add", "path": "/secrets/1", "value": {"name": "whatever" } }]'
      patchType: 'json'
# OR in future we could add
    componentPrototype:
    …
```
