### ISSUE TITLE
Readiness probe status should be shown in the describe output of VMI instead of the virt launcher pod

### ISSUE THREAD

**Issue by Manuri** [kubevirt/kubevirt#3430]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

> Uncomment only one, leave it on its own line:
>
> /kind bug

kind enhancement

**What happened**:
Added a readiness probe to a VM definition. The probe status was not shown in VMI's describe output, but in virt launcher pod's describe output.

**What you expected to happen**:
Probe status should have been shown in VMI's describe output, because the probe was applied to VM definition and a user would expect that. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a readiness probe to VM definition
2. Create a VM
3. Describe VMI - cannot see probe status
4. Describe relevant virt launcher pod - can see probe status

**Anything else we need to know?**:
This might be the case for liveness probes as well. So may need to fix there as well.

**Environment**:
- KubeVirt version (use `virtctl version`): 
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

This is the case for some time now:
```
    conditions:
    - lastProbeTime: null
      lastTransitionTime: null
      message: cannot migrate VMI which does not use masquerade to connect to the
        pod network
      reason: InterfaceNotLiveMigratable
      status: "False"
      type: LiveMigratable
    - lastProbeTime: null
      lastTransitionTime: "2020-11-12T13:04:52Z"
      status: "True"
      type: Ready
```
