### ISSUE TITLE
LVM issue in kickstart

### ISSUE THREAD

**Issue by jlindholm** [kubevirt/kubevirt#3508]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: Centos7 ISO Boot install failed on LVM to partition physical volume (see attached screenshot). 

<img width="717" alt="capture" src="https://user-images.githubusercontent.com/1453864/83655782-c3f77380-a58c-11ea-8248-c4768d2ce4cf.png">

We build an appliance based on CentOS7 minimal with our services included into a bootable ISO. This ISO then is installed from a CD mount. We use the same ISO under test in VirtualBox but with Kubevirt it fails to partition. 

**What you expected to happen**: ISO to boot and install without issue as it does on VirtualBox

**How to reproduce it (as minimally and precisely as possible)**:

ISO kickstart file contains the following for configuring the logical volume: 

```
clearpart --all --initlabel --drives=sda
part pv.01 --fstype="lvmpv" --size 1 --grow --ondisk=sda
volgroup vg01 pv.01
logvol / --vgname=vg01  --fstype="xfs"  --size=2048 --grow --name=lv_root
logvol swap --vgname=vg01 --fstype="swap" --recommended --name=swap
```

The VM Yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-hd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: gateway-vm
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: gateway-vm
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - name: cdromiso
            bootOrder: 1
            cdrom:
              bus: sata
          - name: harddrive
            bootOrder: 2
            disk:
              bus: sata
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: gateway-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: gateway-hd
```

**Anything else we need to know?**: This same ISO boots and installs fine on VirtualBox directly.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.29.2
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: (see above)
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
