### ISSUE TITLE
VMs error after upgrading to v0.30.0

### ISSUE THREAD

**Issue by timstoop** [kubevirt/kubevirt#3587]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We're currently running v.0.27.0 on a GCE VMs in europe-west1, using Haskell+ CPUs with nested kvm enabled. We've been running this since about v0.17 without many problems. After upgrading to v0.30.0, VMs no longer want to start and error with this error:

```
{"component":"virt-launcher","kind":"","level":"error","msg":"Starting the VirtualMachineInstance failed.","name":"app2","namespace":"production","pos":"manager.go:1236","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2020-06-16T21:00:57.287355Z qemu-kvm: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]\n2020-06-16T21:00:57.287377Z qemu-kvm: warning: host doesn't support requested feature : MSR(48BH).vmx-vmfunc [bit 13]\n2020-06-16T21:00:57.287403Z qemu-kvm: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]\n2020-06-16T21:00:57.287438Z qemu-kvm: warning: host doesn't support requested feature: MSR(48CH).vmx-ept-execonly [bit 0]\n2020-06-16T21:00:57.287476Z qemu-kvm: warning: host doesn't support requested feature: MSR(48CH).vmx-eptad [bit 21]\n2020-06-16T21:00:57.287505Z qemu-kvm: warning: host doesn't support requested feature: MSR(491H).vmx-eptp-switching [bit 0]\n2020-06-16T21:00:57.288240Z qemu-kvm: error: failed to set MSR 0x48b to 0x59ff00000000\nqemu-kvm: /builddir/build/BUILD/qemu-4.2.0/target/i386/kvm.c:2684: kvm_buf_set_msrs: Assertion `ret == cpu-\u003ekvm_msr_buf-\u003enmsrs' failed.')","timestamp":"2020-06-16T21:00:57.378709Z","uid":"2c4bd986-9703-4b80-a81f-4e12f2149e82"}                                                                                                            
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"app2","namespace":"production","pos":"server.go:161","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2020-06-16T21:00:57.287355Z qemu-kvm: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]\n2020-06-16T21:00:57.287377Z qemu-kvm: warning: host doesn't support requested feature: MSR(48BH).vmx-vmfunc [bit 13]\n2020-06-16T21:00:57.287403Z qemu-kvm: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]\n2020-06-16T21:00:57.287438Z qemu-kvm: warning: host doesn't support requested feature: MSR(48CH).vmx-ept-execonly [bit 0]\n2020-06-16T21:00:57.287476Z qemu-kvm: warning: host doesn't support requested feature: MSR(48CH).vmx-eptad [bit 21]\n2020-06-16T21:00:57.287505Z qemu-kvm: warning: host doesn't support requested feature: MSR(491H).vmx-eptp-switching [bit 0]\n2020-06-16T21:00:57.288240Z qemu-kvm: error: failed to set MSR 0x48b to 0x59ff00000000\nqemu-kvm: /builddir/build/BUILD/qemu-4.2.0/target/i386/kvm.c:2684: kvm_buf_set_msrs: Assertion `ret == cpu-\u003ekvm_msr_buf-\u003enmsrs' failed.')","timestamp":"2020-06-16T21:00:57.378821Z","uid":"2c4bd986-9703-4b80-a81f-4e12f2149e82"}
```

We're unsure how to fix this and think this is a bug.

**What you expected to happen**:

We expected that a restart of virt-launcher would just restart the VM, like normal.

**How to reproduce it (as minimally and precisely as possible)**:

That's the hard part, we're not exactly sure what could be the problem here. My guess is that there's something in the cpu features, but we do not set anything in particular. We're using the machine type `q35`, but that always used before without any issue.

**Anything else we need to know?**:

Reverting to v0.27.0 (which was quite a hassle by itself) solved the issue and VMs could start again like normal.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.30.0
- Kubernetes version (use `kubectl version`): v1.15.10
- VM or VMI specifications: 

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:        
  annotations:      
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
  labels:         
    kubevirt.io/os: linux       
    tier: production      
    vm-name: app2.domain
  name: app2       
  namespace: production       
spec:        
  running: true                 
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      creationTimestamp: null
      labels:
        tier: production
        vm-name: app2.domain
        vm-type: app-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: vm-name
                operator: In
                values:
                - app1.domain
            topologyKey: kubernetes.io/hostname
            topologyKey: kubernetes.io/hostname
      domain:
        devices:
          disks:
          - disk: {}
            name: disk0
          interfaces:
          - bridge: {}
            name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: "6"
            memory: 24Gi
          requests:
            cpu: "4"
            memory: 24Gi
      networks:
      - name: default
        pod: {}
      readinessProbe:
        httpGet:
          path: /status/loadbalancer/
          port: 80
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 30
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: app2
```

- Cloud provider or hardware configuration:

Google Cloud using Haskell+ CPUs with nested kvm support in the images set.

- OS (e.g. from /etc/os-release):

Debian GNU/Linux 10 (buster) using the 5.4.0-0.bpo.2-cloud-amd64 kernel from backports.

- Kernel (e.g. `uname -a`):

Linux hostname 5.4.0-0.bpo.2-cloud-amd64 #1 SMP Debian 5.4.8-1~bpo10+1 (2020-01-07) x86_64 GNU/Linux

- Install tools:

Kops, mostly.

- Others:
