### ISSUE TITLE
copy on write volumes as delta for read only volumes.

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#3638]
/kind enhancement

The feature request here is to facilitate copy on write backing volumes for read-only volumes.

We already have a feature called an "ephemeralVolume" which allows us to attach a read-only PVC to a VMI, and automatically generate an ephemeral copy on write backing disk for that read only disk. However, that cow disk is completely ephemeral and only exists for the lifetime of the VMI. This means it can't be used to persistently store data that will survive a VM restart.

For a persistent cow disk, we need the ability to assign a PVC as a backing volume for a read only volume. I think we're looking at a new volume type to achieve this. Perhaps something like a ```copyOnWriteVolume```

The struct could look something like this.

```
type CopyOnWriteVolume struct {
    // BaseVolume is the read only source volume
    BaseVolume VolumeSource `json:"baseVolume"`

    // BaseVolumeSHA256 is the optional sha256 hash of the base volume used to validate the contents haven't mutated.
    BaseVolumeSHA256 string `json:"baseVolumeSHA256"`

    // PersistentVolumeClaim is the pvc to store the copy on write delta file
    PersistentVolumeClaim VolumeSource `json:"persistentVolumeClaim"`
}
```

## example VMI with copyOnWriteVolume with containerDisk

In this example, we use a containerDisk as the backing volume, and the PVC named `my-pvc` to maintain the cow delta file. 

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: my-cow-volume
        resources:
          requests:
            memory: 64M
      volumes:
      - copyOnWriteVolume:
        name: my-cow-volume
        baseVolume:
            containerDisk:
                image: kubevirt/fedora32@sha123123123
        persistentVolumeClaim:
            name: my-pvc
```

## example VMI with copyOnWriteVolume with read only PVC

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: my-cow-volume
        resources:
          requests:
            memory: 64M
      volumes:
      - copyOnWriteVolume:
        name: my-cow-volume
        baseVolume:
            persistentVolumeClaim:
                name: my-golden-read-only-image
        persistentVolumeClaim:
            name: my-delta-pvc
```

## SHA validation of the base volume

We can back propagate a sha256 hash of the containerDisks contents to the VMI's status field and ultimately back to the VM's status in order to capture the sha256 hash the first time the VM runs. This hash could then be used the next time the VMI is executed to guarantee that the contents align as expected and that the containerDisk did not mutate.

This back propagating of a sha is likely most useful when we consider a read only PVC as the base volume though. I think for containerDisks as the base image, we should simply require the container image's sha to be used instead of a floating tag.

## SnapShot considerations

Snapshotting the copyOnWrite volume's delta PVC should be possible just like a normal PVC snapshot. In this case we'd simply be copying the delta PVC and ensuring we couple that PVC with the correct base volume during restore. The sha validation will guarantee we catch any issues that might occur if the source mutates.

## Usage Dangers.

There's only so much we can do to protect users from messing this logic up. If a user mutates the source volume behind the scenes, that's not something we can control. The best we can do is catch when this occurs using a hash. For container disks, I think it would be wise to require the usage of a sha hash reference instead of a floating tag. For PVCs we'll have to depend on our own sort of hash validation. 

# Implementation

## phase 1: container disks + cow

Decide what the API should look like and limit copy on write persistent storage to a single volume source (containerDisks). Since container disks use container images, we already have a solution to the sha issue. We simply require containerDisks with a cow delta file to be referenced using the image sha and not a floating tag.

## phase 2. PVCs + cow

Once we feel comfortable with the api and have proven it for container disks, we can approach the more complicated PVC use case. This will require expanding on what we did in phase 1 to provide some sort of sha validation for read only disks on PVCs.
