### ISSUE TITLE
Externally managed certificates for KubeVirt components

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#3648]
This feature request is to enable KubeVirt to allow other mechanisms for certificate management. Currently virt-operator is responsible for creating certificates as secrets, updating the secrets, and configuration for the deployments to consume those secrets. It should be possible to "turn off" virt-operator's certificate management and let users implement the means to manage these secrets per their site certificate requirements.

This feature would consist of several parts that may come in individual PRs. Notably:

1) Enable/disable virt-operator's cert/secret management process via configuration. Something like:

```
certificateRotateStrategy:
  externallyManaged: true
```
or maybe by means of explicitly turning off selfSigned strategy:

```
certificateRotateStrategy:
  selfSigned:
    enabled: false
```

2) Add configuration to virt-handler, virt-controller, virt-api to allow for varying rules around certificate validation.  Note that this is not strictly necessary for users to make use of an externally managed certificate process - If users manage the right secrets, and put the right CN in the certs, and don't use intermediate CAs, then the existing validation would work. However, it is unlikely that an externally managed certificate strategy would have its own root CA, usually this is driven by requirements to use corporate CAs or some other trusted entity that is not a self-signed CA. 

    This is all controlled by code in ./pkg/util/webhooks/tls.go - it has been requested that we leave this code and the self-signed validation as-is, so we would have alternative functions and/or package that are called based on the configuration flags provided to virt-api, virt-handler, and virt-controller. There are a few common configurables that would probably be required for certificate validation in the majority of non-self-signed cases:

   1) Configurable certificate and key file paths (perhaps CA path as well)
   2) Allow client's intermediate certs to be used in building up the chain of trust in cert validation
   3) Address the hard-coded CN for virt-handler cert validation. It is hardcoded to "kubevirt.io:system:client:virt-handler" and this is checked by virt-api when connecting for console/VNC. Odds are good that there could be unique CNs for each virt-handler in any externally managed system, or at least differ from the hard coded one.

3) Allow configuration for virt-handler, virt-controller, and virt-api to flow through virt-operator. This is optional and would be necessary in the case where users are using virt-operator to manage KubeVirt and do want to change certificate paths, change volumeMounts for secrets, etc. This could leverage the work eventually coming from #3365 

   It may also be possible to put the virt-handler, virt-controller, virt-api configurations into the certificateRotateStrategy configuration:

   ```
   certificateRotateStrategy:
     externallyManaged:
       certKeyPath: /etc/certificates/foo.key
       certPath: /etc/certificates/foo.crt
       caPath: /etc/certificates/foo-ca.crt
   ...
   ```

   These would be translated into configuration of the various components during virt-operator building up of the deployments.

**Comment by rmohr** [comment]
> certificateRotateStrategy:
>   externallyManaged: true

How about:

```
certificateRotateStrategy:
  externallyManaged: {}
```

**Comment by mlsorensen** [comment]
> > certificateRotateStrategy:
> > externallyManaged: true
> 
> How about:
> 
> ```
> certificateRotateStrategy:
>   externallyManaged: {}
> ```

Yes, certainly if there is ever to be any configuration associated with it then it will need to be more than a boolean. #3 above hints to the fact that this is likely to be the case.

**Comment by rmohr** [comment]
Something like `certManager` strategy would indeed be nice to have. I could see the following strategies emerging:

 ```
certificateRotateStrategy:
  externallyManaged: {} # potentially may required to use our patch-support in the operator or may get some options
  selfSigned: {} # what we have right now
  certManager: {} # cert-manager does the work, our components adapt to it
  csr: {} # k8s certificat signing requests.
```
