### ISSUE TITLE
VM getting stuck on boot

### ISSUE THREAD

**Issue by akkibatra** [kubevirt/kubevirt#3820]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**: 
I am trying to instantiate pfSense VM and it is getting stuck while mounting.

```
mounting from ufs:/dev/ufsid/<someid> failed with error 19
Loader variables:
  vfs.root.mountfrom=ufs:/dev/ufsid/<sameid>
  vfs.root.mountfrom.options=rw,noatime

Manual root filesystem specification:
  <fstype>:<device> [options]
  Mount <device> using filesystem <fstype>
  and with the specified (optional) option list.

  eg. ufs:/dev/da0s1a
  zfs:tank
  cd9660:/dev/acd0 ro
  (which is equivalent to: mount -t cd9660 -o ro /dev/acd0 /)

  ?  List valid disk boot devices
  .  Yield 1 second (for background tasks)
  <empty line>  Abort manual input

mountroot>
```

and when i try

`mountroot> ?`

i get

`Invalid file system specifications.`

I have tried same process with other os like ubuntu, it works fine. Seems like while launching it is corrupting the partition or changing the partition format, resulting in getting stuck and not finding GEOM managed drives.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to Reproduce:

1. Use virt-manager to create VM and configure pfSense. A qcow2. image is created at this point.
2. Created a docker image
`FROM kubevirt/registry-disk-v1alpha
ADD pfsense.qcow2 /disk/`
3. Ran docker build and push.
4. Instantiated a VM using yaml.
5. virtctl vnc <vmname>

**Environment**:
- KubeVirt version (use `virtctl version`): 0.15.0
- Kubernetes version (use `kubectl version`): 1.14.1
- OS (e.g. from /etc/os-release): ubuntu 16.04.6 LTS
- Install tools: virt-manager

**Comment by rmohr** [comment]
@akkibatra could you share your VM/VMI definition? What are GEOM managed drives?

**Comment by shmoon-kt** [comment]
@akkibatra Have you solved this problem? I am also having the same problem after creating pfsense qcow2 image.

**Comment by sfxworks** [comment]
Same problem. Also happens with freebsd in general. 
Using rook ceph as a backend.
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: opnsense
  labels:
    router: opnsense
spec:
  #networks: 
  #- name: default
  #  pod: {}
  domain:
    devices:
      interfaces:
      - bridge: {}
        name: external-br
      - bridge: {}
        name: internal-br
      #interfaces:
      #- name: default
      #  macAddress: 36:5e:6e:12:0d:84
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 8192M
        cpu: "4"
      limits:
        memory: 8192M
        cpu: "4"
  terminationGracePeriodSeconds: 0
  networks:
  - multus:
      networkName: external-br
    name: external-br
  - multus:
      networkName: internal-br
    name: internal-br
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: opnsense
```
