### ISSUE TITLE
update of VMI object is restricted when update image in the containerDisk

### ISSUE THREAD

**Issue by identw** [kubevirt/kubevirt#3827]
**Is this a BUG REPORT or FEATURE REQUEST?**:
I don’t know if it is a bug or not. Maybe a bug
 /kind bug

**What happened**:
I create a virtual machine using the following manifest:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: fedora
spec:
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  domain:
    resources:
      requests:
        memory: 8Gi
        cpu: 4
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - name: emptydisk
          disk:
            bus: virtio
        - disk:
            bus: virtio
          name: cloudinitdisk
    machine:
      type: "q35"
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:v0.31.0
    - name: emptydisk
      emptyDisk:
        capacity: "2Gi"
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
```
Then I change the image in the contaierDIsk field (kubevirt/fedora-cloud-container-disk-demo:latest) and apply this. But getting the error:
```
The request is invalid: : update of VMI object is restricted
```
I tried using VirtualMachineInstanceReplicaSet, but nothing happens when the image is changed:
```
virtualmachineinstancereplicaset.kubevirt.io/fedora unchanged
```
**What you expected to happen**:
I expected the virtual machine to restart with a new image

**Environment**:
- KubeVirt version (use `virtctl version`): v0.26.0
- Kubernetes version (use `kubectl version`): 1.16.7
- VM or VMI specifications:
- Cloud provider or hardware configuration: Bare-metal (Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz)
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.18.0-25-generic
