### ISSUE TITLE
Feature request: downwardAPI as supported volume type

### ISSUE THREAD

**Issue by y2kenny** [kubevirt/kubevirt#3858]
/kind enhancement

Currently supported volume type are listed here:
https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=volumes

- cloudInitNoCloud
- cloudInitConfigDrive
- persistentVolumeClaim
- dataVolume
- ephemeral
- containerDisk
- emptyDisk
- hostDisk
- configMap
- secret
- serviceAccount

I would like to expose some of the Kubernetes metadata (namespace, node name, etc.) into the VirtualMachineInstance.  But when I try to specify volume type downwardAPI, I get the following error:

`The request is invalid: : spec.volumes.downwardAPI in body is a forbidden property`

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.26.0", GitCommit:"cc1fd38226718b0c07fc3e567148912110c25ee1", GitTreeState:"clean", BuildDate:"2020-02-05T02:18:58Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Fedora 30
- Install tools: kubeadm

**Comment by davidvossel** [comment]
This feature is similar in concept to how our [secret](https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=secret) and [configmap](https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=configmap) volumes work today.

Note that neither the secret or configmap volumes support update propagation at the moment, so they are static to what the values are when the VMI starts. For propagation, we need virtio-fs support, which in [on the way](https://github.com/kubevirt/kubevirt/pull/3493). 

For now, i think it's reasonable to support the downward api as a new volume type in our VMI api by re-using the[ volume structures used for pods today ](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) Internally, we'd statically build a static disk image containing the contents provided by the downward api at boot time just like we do with secrets and configmaps.


Below is an example of how this api could end up looking in a VMI. I'd expect that the api will need further discussion though

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk: {}
        name: downward-api-volume
        # set serial
        serial: CVLY623300HK240D
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
        bootcmd:
          # mount the ConfigMap
          - "mkdir /mnt/app-config"
          - "mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
    name: cloudinitdisk
  - downwardAPI:
    name: downward-api-volume
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
```
