### ISSUE TITLE
migration failed due to "Cannot migrate empty or read-only disk sda"

### ISSUE THREAD

**Issue by chenhaiq** [kubevirt/kubevirt#3920]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
migration failed.

```
[root@i-ojseoqbe ~]# kubectl logs virt-launcher-focal3-gsgbc | tail -n 10
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed","name":"focal3","namespace":"default","pos":"manager.go:619","reason":"virError(Code=84, Domain=10, Message='Operation not supported: Cannot migrate empty or read-only disk sda')","timestamp":"2020-07-31T10:02:54.339720Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 1 received","pos":"client.go:336","timestamp":"2020-07-31T10:02:54.371283Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:231","timestamp":"2020-07-31T10:02:54.373168Z"}
{"component":"virt-launcher","level":"info","msg":"7) OSINFO IN EVENT CALLBACK: \u003cnil\u003e","pos":"client.go:253","timestamp":"2020-07-31T10:02:54.373219Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: default_focal3","pos":"client.go:312","timestamp":"2020-07-31T10:02:54.374612Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to migrate vmi","name":"focal3","namespace":"default","pos":"server.go:105","reason":"migration job already executed","timestamp":"2020-07-31T10:02:54.382534Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.401993Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.418283Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.429603Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.435719Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
[root@i-ojseoqbe ~]# kubectl logs virt-launcher-focal3-gsgbc | tail -n 20
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled vmi migration","name":"focal3","namespace":"default","pos":"server.go:111","timestamp":"2020-07-31T10:02:52.771922Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled vmi migration","name":"focal3","namespace":"default","pos":"server.go:111","timestamp":"2020-07-31T10:02:52.857121Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled vmi migration","name":"focal3","namespace":"default","pos":"server.go:111","timestamp":"2020-07-31T10:02:53.349912Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","level":"error","msg":"Operation not supported: Cannot migrate empty or read-only disk sda","pos":"virNetClientProgramDispatchError:172","subcomponent":"libvirt","thread":"34","timestamp":"2020-07-31T10:02:54.185000Z"}
{"component":"virt-launcher","level":"info","msg":"6840 bytes written oubound connection","pos":"migration-proxy.go:406","timestamp":"2020-07-31T10:02:54.187936Z"}
{"component":"virt-launcher","level":"info","msg":"564 bytes read from oubound connection","pos":"migration-proxy.go:399","timestamp":"2020-07-31T10:02:54.188092Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed.","name":"focal3","namespace":"default","pos":"manager.go:474","reason":"virError(Code=84, Domain=10, Message='Operation not supported: Cannot migrate empty or read-only disk sda')","timestamp":"2020-07-31T10:02:54.265695Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:443","reason":"accept tcp 127.0.0.1:22222: use of closed network connection","timestamp":"2020-07-31T10:02:54.265871Z"}
{"component":"virt-launcher","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:443","reason":"accept tcp 127.0.0.1:49153: use of closed network connection","timestamp":"2020-07-31T10:02:54.265949Z"}
{"component":"virt-launcher","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:443","reason":"accept tcp 127.0.0.1:49152: use of closed network connection","timestamp":"2020-07-31T10:02:54.265980Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed","name":"focal3","namespace":"default","pos":"manager.go:619","reason":"virError(Code=84, Domain=10, Message='Operation not supported: Cannot migrate empty or read-only disk sda')","timestamp":"2020-07-31T10:02:54.339720Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 1 received","pos":"client.go:336","timestamp":"2020-07-31T10:02:54.371283Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:231","timestamp":"2020-07-31T10:02:54.373168Z"}
{"component":"virt-launcher","level":"info","msg":"7) OSINFO IN EVENT CALLBACK: \u003cnil\u003e","pos":"client.go:253","timestamp":"2020-07-31T10:02:54.373219Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: default_focal3","pos":"client.go:312","timestamp":"2020-07-31T10:02:54.374612Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to migrate vmi","name":"focal3","namespace":"default","pos":"server.go:105","reason":"migration job already executed","timestamp":"2020-07-31T10:02:54.382534Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.401993Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.418283Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.429603Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"focal3","namespace":"default","pos":"server.go:167","timestamp":"2020-07-31T10:02:54.435719Z","uid":"22f1e14b-628d-4b8e-9f6f-0cb8a5544c05"}
```

**What you expected to happen**:
vm can be live migrated to another node

**How to reproduce it (as minimally and precisely as possible)**:
create a vm with:
1. ovs cni network
2. nfs pv
3. focal-server-cloudimg-amd64.img

**Anything else we need to know?**:
kubernetes cluster has 2 nodes. Both of them can run vm instance.

```
# cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1G
# cat pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    name: mynfs # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.5
    path: "/mnt/vol"
```

**Environment**:
- KubeVirt version (use `virtctl version`):v0.30.5
- Kubernetes version (use `kubectl version`):v1.18.6
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: focal3
  name: focal3
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          rng: {}
          interfaces:
            - name: test1
              bridge: {}
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      terminationGracePeriodSeconds: 0
      volumes:
      - name: datavolumevolume
        persistentVolumeClaim:
          claimName: nfs-pvc
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: focal
            ssh_pwauth: True
            disable_root: false
            password: ubuntu
            chpasswd: { expire: False }
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKt7BRaZhhzQoHs/uvl/D8TXOB1xKOJYD3YoWieEPdrtJHkiJWXWxtPuaoKM8NiIK4JjhIedeYnZw0j1Bxxu4u++OFmntZdOYmQ0Er60jkEdjBCyVm5lO5iQXg3UGi2HOg2/2wPq0YqU50NRAaZigRJ05IMO3PDIfezzZzpaqKEZ+01vyvIlQY6nuDwGCzao9R5Wcyqr/fsR0Nq5yYoFQT0IIcV09Vv8zMMlpYBkKO1SVhpZJBnKVlPXT0D8fGFGr+NjGBdhjfN2XhwiCb19NjLzTWUbxbgpASzjM5Tpj97OrtNbVWsrcealnV3X1ZZwkhhRVyOvagjR1JCJEr+Oul root@i-ojseoqbe
        name: cloudinitdisk
      networks:
      - name: test1
        multus:
          networkName: ovs-net-vlan100
```
- Cloud provider or hardware configuration: kvm with nested-kvm enabled
- OS (e.g. from /etc/os-release): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1127.13.1.el7.x86_64
- Install tools:kubeadm
- Others:
