### ISSUE TITLE
virtctl image-upload get stack and access-mode flag doesn't apply for the image-scratch pvc

### ISSUE THREAD

**Issue by ipolonsk** [kubevirt/kubevirt#3985]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug
> /kind enhancement

**What happened**:
I'm trying to upload a disk image (Centos 8) using the 'virtctl image-upload': 
```
virtctl image-upload dv centos8 
  --image-path /home/kni/CentOS-Stream-GenericCloud-8-20200113.0.x86_64.qcow2 
  --size 10Gi 
  --storage-class managed-nfs-storage 
  --access-mode=ReadWriteMany 
  --insecure
```
using the flag **--access-mode=ReadWriteMany**
This is the output of the command: 
```
DataVolume my-project/centos8 created
Waiting for PVC centos8 upload pod to be ready...
Pod now ready Uploading data to https://cdi-uploadproxy-openshift.domain
705.68 MiB / 705.68 MiB 
[==================================================================
=====================================================================] 100.00% 5s
Uploading data completed successfully, waiting for processing to complete, you can hit ctrl-c without interrupting the progress
```
and no "Processing completed successfully" output even after few hours. 
while checking the PVC, I noticed the mode for the centos8 is as provided in the command but the centos8-scratch I still have **RWO access-mode**. 
```
[root@provisioner ~]# oc get pvc
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE                                                   
centos8           Bound    pvc-74870e02-c4c8-49e0-8c25-edf0b21c6dc1   10Gi       RWX            managed-nfs-storage   102s                                                  
centos8-scratch   Bound    pvc-46c73f89-fd9a-4238-b2f0-e510bccbb606   10Gi       RWO            managed-nfs-storage   102s                   
```

**What you expected to happen**:
I expected the upload command to have output those lines, that suggest the upload was successful and have the relavent  datavolumes resource 'Succeeded' status:
```
Processing completed successfully
Uploading CentOS-Stream-GenericCloud-8-20200113.0.x86_64.qcow2 completed successfully
```
```
[root@provisioner nfs-client]# oc get dv
NAME             PHASE         PROGRESS   RESTARTS   AGE
centos8        UploadReady   N/A        0          35s
```
**and more importantly,** I was expected to see the access mode for the both of my PVC to be RWX because of flag I pass to the uploader. 

**How to reproduce it (as minimally and precisely as possible)**:
1. I created an NFS storage class, using the following YAMLs: 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: storage.io/nfs
parameters:
  archiveOnDelete: "false"
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: openshift-nfs-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: storage.io/nfs
            - name: NFS_SERVER
              value: hostname.domian
            - name: NFS_PATH
              value: /var/nfsshare
      volumes:
        - name: nfs-client-root
          nfs:
            server: hostname.domian
            path: /var/nfsshare
```
I tested the NFS server before setting up the storage class and then tested the class storage with test PVC and test pods.

2. Run the virtctl upload-image command:
```
virtctl image-upload dv centos8 
  --image-path /home/kni/CentOS-Stream-GenericCloud-8-20200113.0.x86_64.qcow2 
  --size 10Gi 
  --storage-class managed-nfs-storage 
  --access-mode=ReadWriteMany 
  --insecure
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.30.5", GitCommit:"53b764825eb80321b18eb39a5767c25a77ea470b", GitTreeState:"clean", BuildDate:"2020-07-23T18:57:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.30.5", GitCommit:"53b764825eb80321b18eb39a5767c25a77ea470b", GitTreeState:"clean", BuildDate:"2020-07-23T20:09:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: it's a bare-metal host
- OS (e.g. from /etc/os-release): RHEL 8
- Kernel (e.g. `uname -a`): 
```
Linux provisioner 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Mon Jun 1 20:24:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:
The server has enough storage space for this image size.
```
[root@provisioner nfs-client]# oc get dv
NAME             PHASE         PROGRESS   RESTARTS   AGE
centos8        UploadReady   N/A        0          35s
```
```
[root@provisioner ~]# oc get sc
NAME                  PROVISIONER      RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE                                                                       
managed-nfs-storage   storage.io/nfs   Delete          Immediate           false                  27h  
```
```
[root@provisioner ~]# oc get pvc
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE                                                   
centos8           Bound    pvc-74870e02-c4c8-49e0-8c25-edf0b21c6dc1   10Gi       RWX            managed-nfs-storage   102s                                                  
centos8-scratch   Bound    pvc-46c73f89-fd9a-4238-b2f0-e510bccbb606   10Gi       RWO            managed-nfs-storage   102s           
```
```
[root@provisioner ~]# oc get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                        STORAGECLASS          REASON   AGE              
pvc-46c73f89-fd9a-4238-b2f0-e510bccbb606   10Gi       RWO            Delete           Bound    my-project/centos8-scratch   managed-nfs-storage            2m               
pvc-74870e02-c4c8-49e0-8c25-edf0b21c6dc1   10Gi       RWX            Delete           Bound    my-project/centos8           managed-nfs-storage            2m           
```
```
[root@provisioner ~]# oc get pods
NAME                 READY   STATUS    RESTARTS   AGE
cdi-upload-centos8   1/1     Running   1          2m15s
```
```
[root@provisioner ~]# oc logs cdi-upload-centos8
I0812 11:04:24.670015       1 uploadserver.go:63] Upload destination: /data/disk.img
I0812 11:04:24.670129       1 uploadserver.go:65] Running server on 0.0.0.0:8443
```
