### ISSUE TITLE
KubeVirt for HA 

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#3999]
Hi, first I want to say you developed a cool Kubernetes plugin! :)
I start to check kubevirt for HA and I have a couple of qus:
- can I use with kubevirt for HA? if yes, what I should take care of? 
- Today I'm using with Rancher. do you have a recommendation for other platforms?

and i'll happy to get help with a different thing,
I'm able to run VM and VM,  right now I'm using with same demo image.
but I can't for some reason to use with virtctl to start/stop/vnc to control on the VM instance 

for example :

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm
spec:
  #terminationGracePeriodSeconds: 30
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/cirros-registry-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=

 kubectl virt start testvm2 -v 10
Error starting VirtualMachine the server has asked for the client to provide credentials

Environment: HA Rancher 
KubeVirt version (use virtctl version):
./virtctl version
Client Version: version.Info{GitVersion:"v0.32.0", GitCommit:"44d3011eb09b1488d181439dd0bf54f58ebb148b", GitTreeState:"clean", BuildDate:"2020-08-11T19:31:18Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
the server has asked for the client to provide credentials

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

please help

**Comment by talcoh2x** [comment]
btw, if I'm changing the spec to  '{"spec":{"running":true}}' its working and I'm able to run ssh to Host. but still virtctl does not work

**Comment by rmohr** [comment]
@talcoh2x regarding the virtctl issue, I think that you need to configure your rancher account a little bit different than the default is. Check out https://github.com/kubevirt/kubevirt/issues/3760, it should describe what you have to do.

**Comment by rmohr** [comment]
@talcoh2x kubevirt can support a range of HA scenarios, but it depends on what you actually need. Do you just want that the VM gets automatically restarted when it is shut down or crashes? Do you want a standby machine for e.g. web applications?

**Comment by talcoh2x** [comment]
Hi @rmohr 
ill check the link that you sent me regarding the virtctl thanks!

about the Kubevirt, my plan ( and I still don't know if it's possible ) is  to use with kubevirt to lunch number of VM per KVM it can be 1 or more (e.g: 6,7,8 ...) 
for each one, I need to define the number of PCI devices that I want to expose ( PCI device I mean like a GPU device) and on top of that, I can run my workload. so I can manage all ( Container and VM ) in the same way.

Another option, if its possible is to create VM per request ( Just for a small number of VM ) run something and dispose ( per User request)

*automatically restarted can be nice.

**Comment by talcoh2x** [comment]
@rmohr thanks! with #3760, it took me 5 min to fix the issue.

I have just one thing, I'm able to open the serial console with 
**./virtctl console  testvm2**  and even with **kubectl virt console testvm2**

but **./virtctl vnc testvm2** show me black screen witout the option to do/see something.

any idea?

**Comment by talcoh2x** [comment]
@rmohr  UP

**Comment by rmohr** [comment]
@talcoh2x could you check with a very minimalistic VM? Just to ensure that it is not an OS issue:


```
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-nocloud
  name: vmi-nocloud
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk:
          bus: virtio
        name: emptydisk
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/cirros-container-disk-demo
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/sh

        echo 'printed from cloud-init userdata'
    name: cloudinitdisk
  - emptyDisk:
      capacity: 2Gi
    name: emptydisk

```
