### ISSUE TITLE
VM with VFIO stuck in pending

### ISSUE THREAD

**Issue by peng-isi** [kubevirt/kubevirt#4002]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 kind bug
> /kind enhancement

**What happened**:
When I created a VM instance configure with SRIOV network interface (Mellanox IB interface), the VMI stuck in pending status.  I appended the config map, network attachment definition and debugging information. I am not sure what is wrong with my configuration.  

Any help and suggestion is appreciated.

- I use the following config map 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config-vfio
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "vfio_ib_sriov",
                "rootDevices": ["21:00.1"],
                "sriovMode": true,
                "deviceType": "vfio"
                }
                ]
    }
```

- I use the following network attachment definition

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: vfio-ib-sriov-network
annotations:
k8s.v1.cni.cncf.io/resourceName: vfio_ib_sriov
spec:
config: '{
"type": "ib-sriov",
"cniVersion": "0.3.1",
"name": "vfio-sriov-network",
"ipam": {
"type": "host-device",
"subnet": "10.56.217.0/24",
"routes": [{
"dst": "0.0.0.0/0"
}]
}
}'
```

- the output of "kubectl describe vmi XXXX"
```
Name:         linux-vm-16.04-ib
Namespace:    default
Labels:       kubevirt.io/domain=linux-vm-16.04-ib
              kubevirt.io/size=small
Annotations:  kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2020-08-17T19:29:37Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generate Name:  linux-vm-16.04-ib
  Generation:     2
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:generateName:
        f:labels:
          .:
          f:kubevirt.io/domain:
          f:kubevirt.io/size:
        f:ownerReferences:
      f:spec:
        .:
        f:domain:
          .:
          f:cpu:
            .:
            f:cores:
          f:devices:
            .:
            f:disks:
            f:interfaces:
          f:firmware:
            .:
            f:uuid:
          f:machine:
            .:
            f:type:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:networks:
        f:volumes:
      f:status:
        .:
        f:conditions:
        f:guestOSInfo:
        f:phase:
    Manager:    virt-controller
    Operation:  Update
    Time:       2020-08-17T19:29:38Z
  Owner References:
    API Version:           kubevirt.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  linux-vm-16.04-ib
    UID:                   af8cdb6a-5ac9-4f6f-aca8-c35ab3b08c65
  Resource Version:        9961219
  Self Link:               /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/linux-vm-16.04-ib
  UID:                     941271e1-d702-4a9a-8f27-f6d2e30ddd49
Spec:
  Domain:
    Cpu:
      Cores:  4
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   myhddr
      Interfaces:
        Masquerade:
        Name:  default
        Name:  sriov-net
        Sriov:
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  ddaea759-9e77-5b22-afa9-375e5727bf5f
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  4G
  Networks:
    Name:  default
    Pod:
    Multus:
      Network Name:  vfio-ib-sriov-network
    Name:            sriov-net
  Volumes:
    Name:  myhddr
    Persistent Volume Claim:
      Claim Name:  upload-datavolume-test2
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2020-08-17T19:32:20Z
    Message:               failed to create virtual machine pod: Pod "virt-launcher-linux-vm-16.04-ib-mdw8z" is invalid: [spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers]
    Reason:                FailedCreate
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Phase:  Pending
Events:
  Type     Reason        Age                From                       Message
  ----     ------        ----               ----                       -------
  Warning  FailedCreate  52m (x9 over 63m)  virtualmachine-controller  (combined from similar events): Error creating pod: Pod "virt-launcher-linux-vm-16.04-ib-wsplv" is invalid: [spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers]
  Warning  FailedCreate  41m                virtualmachine-controller  Error creating pod: Pod "virt-launcher-linux-vm-16.04-ib-mfxsw" is invalid: [spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers]
  Warning  FailedCreate  24m                virtualmachine-controller  Error creating pod: Pod "virt-launcher-linux-vm-16.04-ib-4fjhx" is invalid: [spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers]
  Warning  FailedCreate  8m6s               virtualmachine-controller  Error creating pod: Pod "virt-launcher-linux-vm-16.04-ib-ql5wt" is invalid: [spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[vfio_ib_sriov]: Invalid value: "vfio_ib_sriov": must be a standard resource for containers]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.29.0
- Kubernetes version (use `kubectl version`): v1.18.9
- VM or VMI specifications:
-------------------

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: linux-vm-16.04-ib
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: linux-vm-16.04-ib
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: myhddr
          interfaces:
            - masquerade: {}
              name: default
            - name: sriov-net
              sriov: {}
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: vfio-ib-sriov-network
        name: sriov-net
      volumes:
      - name: myhddr
        persistentVolumeClaim:
          claimName: upload-datavolume-test2
status: {}
```
---------------

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):4.4.0-142-generic #168-Ubuntu SMP ... x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
