### ISSUE TITLE
Validator rejects cloudInit section that does not contain userData, even though it already has networkData

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#4033]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

KubeVirt validator tries to prevent user from creating an empty `cloudInitNoCloud` section by making sure that it contains `userData` sub-section. However, that is not the only subsection it may contain, there is also `networkData`.

And when I provide only` networkData` and on `cloudData`, which should be valid, the validation returns an error.

**What you expected to happen**:

When only `networkData` are provided, it should successfully create the VM. Even without `userData` being provided.

**How to reproduce it (as minimally and precisely as possible)**:

Try to create a VMI:

```yaml
cat <<EOF | ./cluster-up/kubectl.sh create -f -
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi1
  name: vmi1
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: default
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: default
    pod: {}
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo
    name: containerdisk
  - cloudInitNoCloud:
      networkData: |
        version: 2
        ethernets:
          eth0:
            dhcp4: true
            addresses: [ fd10:0:2::2/120 ]
            gateway6: fd10:0:2::1
    name: cloudinitdisk
EOF
```

It fails with:

```
The request is invalid: spec.volumes[1].cloudInitNoCloud: spec.volumes[1].cloudInitNoCloud must have one exactly one userdata source set.
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Taken from master, v0.32.0-b49317749
