### ISSUE TITLE
Implement basic restartPolicies for VMIs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#413]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

Right now, our VMIs are started once and then go to `Succeeded` or `Failed` phase. This is a good start. A higher level controller or the user then has to restart/repost the vm.

**What you expected to happen**:

I want to be able to define restart policies like on pods. This is a very valuable tool to keep your VMIs running without having to bother the cluster.

This brings the following advantages:

 * Restarting failing or shutdown guest without doing possible expensive rescheduiling
 * Fast because it is done on the node level
 * Controllers and user-scripts which focus on availability can make `Always` restart policy mandatory and do not have to care about cleaning up.  We are also following the k8s pattern for such controllers.

As a consequence, which is mandatory in k8s **anyway**, proper node-error-detection is necessary to evacuate pods and vms if workloads can't be restarted because of node issues.

**Anything else we need to know?**:

We can follow the Pod pattern here and add the following restart policies:
* `RestartPolicy: Never`: Until we support something health-checks and readiness-checks, a VM can be considered to have run once, as soon as libvirt reports them as running.

* `RestartPolicy: Always`: Always try to start the VM again.

* `RestartPolicy: OnFailure`: Right now, limit this to libvirt reporting a crash. Once probes are there we can improve it.

Example of a vmi which is in running phase and the domain is up and running:

```yaml
spec:
  RestartPolicy: Always
status:
    phase: Running
    conditions:
    - type: Ready
      status: "True"
      lastProbeTime: null
      lastTransitionTime: 2018-01-01T00:00:00Z
```
Example of a vmi which is in running phase and the domain is down and will be restarted (and for instance a soft shutdown in the vm was triggered):

```yaml
spec:
  RestartPolicy: Always
status:
    phase: Running
    conditions:
    - type: Ready
      status: "False"
      lastProbeTime: null
      lastTransitionTime: 2018-01-01T00:00:00Z
```
