### ISSUE TITLE
server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: host doesn't support passthrough of host PCI devices')"

### ISSUE THREAD

**Issue by rupang790** [kubevirt/kubevirt#4226]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

I tried to create VM with SR-IOV which uses PCI-Passthrough on OKD 4.5 platform.
I already check that SR-IOV VF interface was attached and active well with container Pod.
However, it was not work on KubeVirt vm and I can see the error message as below on OKD dashboard.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/40801176/93847525-1696a000-fce2-11ea-90ff-613e73081c0e.png">

Check the Worker Node as below:
> [core@worker03 ~]$ dmesg | grep -e DMAR -e IOMMU
[    0.010074] ACPI: DMAR 0x000000007B7FD000 00030A (v01 INTEL  INTEL ID 00000001 ?    00000001)
[    0.224127] DMAR: IOMMU enabled
[    2.039783] DMAR: Host address width 46
[    2.044110] DMAR: DRHD base: 0x000000fbffc000 flags: 0x0
[    2.050066] DMAR: dmar0: reg_base_addr fbffc000 ver 1:0 cap d2078c106f0466 ecap f020df
[    2.058942] DMAR: DRHD base: 0x000000c7ffc000 flags: 0x1
[    2.064899] DMAR: dmar1: reg_base_addr c7ffc000 ver 1:0 cap d2078c106f0466 ecap f020df
[    2.073771] DMAR: RMRR base: 0x0000007918d000 end: 0x0000007918ffff
[    2.080776] DMAR: RMRR base: 0x000000791eb000 end: 0x000000791eefff
[    2.087779] DMAR: RMRR base: 0x000000791db000 end: 0x000000791eafff
[    2.094783] DMAR: RMRR base: 0x000000791c8000 end: 0x000000791d8fff
[    2.101785] DMAR: RMRR base: 0x000000791d9000 end: 0x000000791dafff
[    2.108787] DMAR: RMRR base: 0x0000005a7a1000 end: 0x0000005a7e0fff
[    2.115796] DMAR-IR: IOAPIC id 10 under DRHD base  0xfbffc000 IOMMU 0
[    2.122992] DMAR-IR: IOAPIC id 8 under DRHD base  0xc7ffc000 IOMMU 1
[    2.130092] DMAR-IR: IOAPIC id 9 under DRHD base  0xc7ffc000 IOMMU 1
[    2.137191] DMAR-IR: HPET id 0 under DRHD base 0xc7ffc000
[    2.143238] DMAR-IR: Queued invalidation will be enabled to support x2apic and Intr-remapping.
[    2.153412] DMAR-IR: Enabled IRQ remapping in x2apic mode
[    8.209968] DMAR: No ATSR found
[    8.214242] DMAR: dmar0: Using Queued invalidation
[    8.219827] DMAR: dmar1: Using Queued invalidation
[    9.552431] DMAR: Intel(R) Virtualization Technology for Directed I/O
[   10.164376] ehci-pci 0000:00:1a.0: DMAR: 32bit DMA uses non-identity mapping
[   10.277427] ehci-pci 0000:00:1d.0: DMAR: 32bit DMA uses non-identity mapping
[   10.418842] uhci_hcd 0000:01:00.4: DMAR: Setting identity map [0x5a7a1000 - 0x5a7e0fff]
[   10.428233] uhci_hcd 0000:01:00.4: DMAR: Setting identity map [0x791d9000 - 0x791dafff]
[   10.444748] uhci_hcd 0000:01:00.4: DMAR: Setting identity map [0x791c8000 - 0x791d8fff]
[   10.461831] uhci_hcd 0000:01:00.4: DMAR: Setting identity map [0x791db000 - 0x791eafff]
[   10.461832] uhci_hcd 0000:01:00.4: DMAR: Setting identity map [0x791eb000 - 0x791eefff]
[   10.461851] uhci_hcd 0000:01:00.4: DMAR: 32bit DMA uses non-identity mapping
[   13.042680] hpsa 0000:03:00.0: DMAR: 32bit DMA uses non-identity mapping

> [core@worker03 ~]$ cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt1)/ostree/fedora-coreos-5745fc400d160a75dcc276a1177e34fbf2a198402ed8809c30e4336428c3706e/vmlinuz-5.6.19-300.fc32.x86_64 systemd.unified_cgroup_hierarchy=0 console=tty0 console=ttyS0,115200n8 ignition.platform.id=metal ostree=/ostree/boot.1/fedora-coreos/5745fc400d160a75dcc276a1177e34fbf2a198402ed8809c30e4336428c3706e/0 intel_iommu=on iommu=pt

And I wrote the `.yaml` file about vm as below:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: centos-vm-sriov
  namespace: default
  labels:
    apps: centosvm
spec:
  nodeSelector:
    env: sriov
  domain:
    devices:
      disks:
      - name: pvc-disk
        disk:
          bus: virtio
        name: pvc-disk
      - disk:
          bus: virtio
        name: cloudinit
      interfaces:
        - masquerade: {}
          name: default
        - name: sriovnet
          sriov: {}
    resources:
      requests:
        cpu: 4000m
        memory: 8192M
  networks:
    - name: default
      pod: {}
    - multus:
        networkName: default/sriov-net-vm
      name: sriovnet
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvc-disk
    persistentVolumeClaim:
      claimName: centos-pvc
  - name: cloudinit
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        package_upgrade: true
        packages:
          - git
          - net-tools
          - vim
          - traceroute
          - tcpdump
          - qemu-guest-agent
        write_files:
          - content: | # Bugfix https://bugs.centos.org/view.php?id=16282
            owner: root:root
            path: /etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned

```

What am I missing to use KubeVirt with SR-IOV?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.26.1
- Kubernetes version (use `kubectl version`): v1.18.3 (OKD version: Client Version: 4.5.0-0.okd-2020-09-18-202631
Server Version: 4.5.0-0.okd-2020-09-18-202631)
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 32.20200629.3.0 (CoreOS)
- Kernel (e.g. `uname -a`): 5.6.19-300.fc32.x86_64
- Install tools:
- Others:
