### ISSUE TITLE
How to config static IP address to SR-IOV interface on Kubevirt vmi ?

### ISSUE THREAD

**Issue by rupang790** [kubevirt/kubevirt#4240]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:
Trying to attach SR-IOV interface to KubeVirt VMI, but I could not set static IP address on the interface on yaml file.
Do you have any Ideas about this?
I share my SR-IOV and VM yaml file to understand.

**SR-IOV Node Policy**
<img width="433" alt="image" src="https://user-images.githubusercontent.com/40801176/93980061-187f6280-fdb9-11ea-9e0e-4e443786655a.png">

**SR-IOV Network Attachment**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/40801176/93980103-28974200-fdb9-11ea-9424-d3bcef432701.png">

**VMI**
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: centos-vm-sriov
  namespace: default
  labels:
    apps: centosvm
spec:
  nodeSelector:
    env: sriov
  domain:
    devices:
      disks:
      - name: pvc-disk
        disk:
          bus: virtio
        name: pvc-disk
      - disk:
          bus: virtio
        name: cloudinit
      interfaces:
        - masquerade: {}
          name: default
        - name: sriovnet
          sriov: {}
      rng: {}
    resources:
      requests:
        cpu: 4000m
        memory: 8192M
  networks:
    - name: default
      pod: {}
    - multus:
        networkName: default/sriov-net-vm
      name: sriovnet
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvc-disk
    persistentVolumeClaim:
      claimName: centos-pvc
  - name: cloudinit
    cloudInitNoCloud:
      networkData: |
        network:
          version: 1
          config:
            - type: physical
              name: eth0
              subnets:
                - type: dhcp
            - type: physical
              name: ens1f0
              subnets:
                - type: static
                  address: 192.168.2.121/24
                  gateway: 192.168.2.254
      userData: |-
        #cloud-config
        package_upgrade: true
        packages:
          - git
          - net-tools
          - vim
          - traceroute
          - tcpdump
          - qemu-guest-agent
        write_files:
          - content: | # Bugfix https://bugs.centos.org/view.php?id=16282
            owner: root:root
            path: /etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned
        users:
          - name: root
            password: .dlfndhs
            ssh_pwauth: True
            sudo: ALL=(ALL) NOPASSWD:ALL

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
