### ISSUE TITLE
Adding disk to running virtual machine

### ISSUE THREAD

**Issue by banksyian** [kubevirt/kubevirt#4250]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Editing running virtualMachine spec and adding a disk to use an existing PVC.
The additional disk is not detected by the `virt-launcher` pod or the virtualMachine until the virtual machine is restarted. 

**What you expected to happen**:
I am trying to add a disk to the running virtual machine without having to restart it. I am not sure if it is possible and I am going about it in the wrong way, or have a misconfiguration somewhere?

**How to reproduce it (as minimally and precisely as possible)**:
Create a PVC.
Edit running virtualMachine spec and add:
```
          disks:
          - disk:
              bus: virtio
            name: disk1

      volumes:
      - name: disk1
        persistentVolumeClaim:
          claimName: new-pvc
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.32.0
- Kubernetes version (use `kubectl version`): v1.19.1
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): 5.4.0-47-generic
- Install tools: 
- Others:
