### ISSUE TITLE
DataVolumeTemplates API regression

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#4268]
/kind bug

When I made the recent change to the DataVolumeTemplate section of the VirtualMachine API in this pr #4261 it resulted in an unexpected regression.

Previously, the DataVolumeTemplate referenced a list of DataVolume objects, which contained a Status.  The new revision removed the Status struct. Even though the status struct is marked as "omitempty", it is still persisted in etcd for each DataVolumeTemplate entry that was created before my changes in #4261 

This means upgrades are broken. Existing VMs with the DataVolumeTemplate can not be processed if they contain the Status: {} field.

Example. While the status is never used by the template and the user has no control over those values, it is still persisted in etcd on the template.
```
  spec:
    dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: test-dv
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        source:
          blank: {}
      status: {}
```

Now that Status no longer exists for the DataVolumeTemplate, it causes the VM objects to be rejected by our validation and mutation webhooks.
