### ISSUE TITLE
support tolerations

### ISSUE THREAD

**Issue by wyyxd2017** [kubevirt/kubevirt#4284]
/kind enhancement

## What happened:
The pod can't be scheduled when node be tanited.I can add deployment.spec.template.spec.tolerations to reschedule the pod on the tanited node.It is stupid.

## What you expected to happen:
Add the code to enhance for the pod  can always scheduler on the nodes which is tanited, eg  virt-handler-xx.

## Anything else we need to know?:
[EDIT]
add a env, which could indicate what taints the pod can tolerate.

Environment:

- KubeVirt version (use virtctl version):
- Kubernetes version (use kubectl version):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. uname -a):
- Install tools:
- Others:

**Comment by wyyxd2017** [comment]
thanks!

**Comment by salanki** [comment]
This is implemented in master by https://github.com/kubevirt/kubevirt/pull/4092.

Example usage:
```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration: {}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  infra:
    nodePlacement:
      nodeSelector:
        topology.kubernetes.io/region: ORD1
        node.coreweave.cloud/class: control-plane
  workloads:
    nodePlacement:
      nodeSelector:
        node.coreweave.cloud/hypervisor: "true"
      tolerations:
        - key: node.coreweave.cloud/hypervisor
          operator: Exists
        - key: is_gpu
          operator: Exists
        - key: is_cpu_compute
          operator: Exists
```
