### ISSUE TITLE
[virt-controller] Remove redundant initcontainer when there is no ContainerDisk defined in VM

### ISSUE THREAD

**Issue by DanielQujun** [kubevirt/kubevirt#4365]
When I create a `VirtualMachine` as below:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-hostdisk
  name: vm-hostdisk
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-hostdisk
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: hostdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - hostDisk:
          path: /tmp/vm-hostdisk/a.qcow2
          type: DiskOrCreate
        name: hostdisk
```

I notice that there is an initcontainer  was added to the VM's POD, IIUC, this container was designed to copy the `container-disk` binary which used for hanging a container image which acting as a ContainerDisk.
```
  initContainers:
  - command:
    - /usr/bin/cp
    - /usr/bin/container-disk
    - /init/usr/bin/container-disk
    image: system/virt-launcher:v0.34.0
    imagePullPolicy: IfNotPresent
    name: container-disk-binary
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        memory: 1M
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/usr/bin
      name: virt-bin-share-dir
```

IMHO, if there isn't ContainerDisk defined for the VM, maybe we do not need to add it.

EDIT: update volume's name from containerdisk to hostdisk.
