### ISSUE TITLE
Support Affinity and Anti-Affinity

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#438]
As a first step, it should be pretty painless, to pass through affinity rules from the VM to the Pod. E.g. add an `affinity` section to VM spec

```yaml
metadata:
  kind: VM
spec:
    affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```
and directly pass it through to the underlying Pod during creation and migration. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity for more details.
