### ISSUE TITLE
Failed to start centos 6.8 with kernel panic

### ISSUE THREAD

**Issue by yichengliu58** [kubevirt/kubevirt#4382]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I downloaded minimal version `centos-6.8` from official website (https://archive.kernel.org/centos-vault/6.8/isos/x86_64/CentOS-6.8-x86_64-minimal.iso) and installed it using `VirtualBox` on my laptop, after starting the system I also installed `cloud-init` with version `0.7.9` then powered off.

I used `qemu-img` tool to convert the `vhd` format of this centos OS mirror to `qcow2`, command is `qemu-img convert -t none -p -f vpc -O qcow2 centos-6.10.vhd centos-6.10.qcow2`.

I uploaded this `centos-6.10.qcow2` mirror to a PV in my K8S cluster using CDI, then used that PVC to start a Kubevirt virtual machine. The pvc is called test-vm-sys as shown below in the yaml.

After VM is running, I used `virtctl vnc` to attach the vm, and saw this:
![image](https://user-images.githubusercontent.com/6440770/96554857-a92e5d00-12e9-11eb-9c3b-2b27315f61e4.png)

Obviously the kernel failed to start with a kernel panic.

But the vm on my Virtualbox could run perfectly without any issues.

**What you expected to happen**:
The VM should have booted without any issues and `cloud-init` should have run successfully.

**How to reproduce it (as minimally and precisely as possible)**:
As described above.

**Anything else we need to know?**:
I also tried `centos-6.10` and `centos-7.0` they both have this same issue.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.30.5
- Kubernetes version (use `kubectl version`): 1.17.6
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: test-vm
  name: test-vm
  namespace: demo
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: sys
          - disk:
              bus: virtio
            name: init
          interfaces:
          - bridge: {}
            name: default
        features:
          acpi:
            enabled: true
        resources:
          limits:
            cpu: "8"
            memory: 32Gi
          requests:
            cpu: "2"
            memory: 8Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: sys
        persistentVolumeClaim:
          claimName: test-vm-sys
      - name: init
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            ssh_pwauth: true
            chpasswd:
              list: |
                root:1@w4__98&^%xxs
              expire: false
            system_info:
              default_user:
                name: root
```
- Cloud provider or hardware configuration: none
- OS (e.g. from /etc/os-release): centos-6.8
- Kernel (e.g. `uname -a`): 2.6.32
- Install tools:
- Others:

**Comment by yichengliu58** [comment]
I tried `centos 6` official cloud image: https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1907.qcow2.xz , this one also failed to start:

![image](https://user-images.githubusercontent.com/6440770/96836255-49fe5300-1477-11eb-8b14-1113799c92ef.png)

I used `virtctl vnc` to attach and the shell just froze, not responsible to my key pressing...

There might be some bug in kubevirt...

**Comment by maya-r** [comment]
While experimenting with this, I managed to reproduce the "boot hangs after Probing EDD... ok" when I supplied the VM too little RAM (64M).
This doesn't seem to be the case in the VirtualMachine definition you provided, though.

**Comment by rmohr** [comment]
Another possibility may be the host cpu. Maybe qemu has issues with it. We use `host-passthrough` right now. Could you try using `host-model` like described in https://kubevirt.io/user-guide/#/creation/devices?id=cpu-model-special-cases?

**Comment by yichengliu58** [comment]
@maya-r I tried setting RAM to 1Gi and also more, the kernel still hangs...this issue might not be related to resource
@rmohr I tried this `host-model` but nothing changes...
So I'm wondering if there are some kernel configs related? Or is this a real bug of qemu...?

**Comment by vladikr** [comment]
perhaps add `edd=off` to your kernel parameters?

**Comment by yichengliu58** [comment]
@vladikr There was no kernel selecting window at all...The kernel hadn't started yet, looks like the kernel wasn't able to be loaded from disk and the booting process stopped there...
I also tried `debian` 8.3, it also had the same problem. Is this something wrong with `qemu` ? Looks like older OS versions are all not able to boot...

**Comment by rmohr** [comment]
@yichengliu58 could it be that they don't like the new `q35` architecture and instead need ` i440fx` architecture?

**Comment by rmohr** [comment]
@yichengliu58 oh wait, I think @vladikr is right. I think that this edd message is already from the kernel.

**Comment by yichengliu58** [comment]
@rmohr I tried updating kernel to 4.4 and the system successfully started, I haven't tried 3.10 kernel yet, but 2.6 (original `centos` kernel) is definitely not able to start. So there must be some compatibility issues with `qemu` or `libvirt` that causes kernel 2.6 failed to start.

**Comment by rmohr** [comment]
@yichengliu58 I think you need an older machine type. This kernel very likely does not understand `q35` properly. Can you try the following?


Create in the `kubevirt` namespace the following configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
  labels:
    kubevirt.io: ""
data:
  emulated-machines: "q35*,pc-q35*,pc*"
```

The `pc*` is what is added to the implicit default value of `q35*,pc-q35*`.

Then set the `pc-i440fx-31` machine type on the VMI like this:

```
spec:
  domain:
    machine:
      type: pc-i440fx-3.1
```

Will be interesting to  see if it boots then.
