### ISSUE TITLE
With our switch to CRDs it is now possible to give our VM it's final name "VirtualMachine"

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#439]
So far, we used for our VirtualMachine object the name `VM`, to allow us  doing simple things at the client side, like `kubectl get vms` in contrast to `kubectl get virtualmachine`. Now with CRDs in place, we can change it and use the proper `VirtualMachine` Kind and still keep the vm/vms convenience.

Our CRD should look like this:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.kubevirt.io
spec:
  group: kubevirt.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: virtualmachines
    singular: virtualmachine
    kind: VirtualMachines
    shortNames:
    - vm
    - vms
```
Minor code adjustments might be necessary (Replacing e.g. "VM" with "VirtualMachine").
