### ISSUE TITLE
vm booted by pvc has no default network interface

### ISSUE THREAD

**Issue by todaygood** [kubevirt/kubevirt#4410]
**What happened**: vm booted by pvc has no default network interface, but vm booted by containerDisk is normal.

I found some clues 🔢 
1. the qumu process's args  has no  "-device  virtio-net-pci" arg
2.  no interface-cache-default.json file  in launcher pod "/var/run/kubevirt-private" directory.
3.  no  k6t-eth0 bridge  in launcher's pod.

**What you expected to happen**:  vm booted by pvc has default network interface.

**How to reproduce it (as minimally and precisely as possible)**:
In my environment , It is 100% reproducible.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.33.0
- Kubernetes version (use `kubectl version`): 1.15.4
- VM or VMI specifications:
- Cloud provider or hardware configuration:  baremetal
- OS (e.g. from /etc/os-release):  CentOS  7.4.1708
- Kernel (e.g. `uname -a`):  3.10.0-693
- Install tools: k8s is installed by binary file.

**Comment by rmohr** [comment]
@todaygood could you compare the two pod specs? Can it be that on one of the two specs you have `autoattachPodNetwork=false`?

**Comment by todaygood** [comment]
no  autoattachPodNetwork=false ,  the vm spec is  as following.

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: centos78qcow
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos78qcow
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: centos7-qcow2
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: centos78qcow
            ssh_pwauth: True
            disable_root: False
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtHHGS2elXqjc8QepM5MNMr+THkkijlbyz7ex1myMzJnzsSnwN/IeealBwtaYlmjLRHR/mqGa3nXoYOFQK+TrLdcWMesZ1kVO7bB8vUqDNKwypceMAHRpP9Bza07RWDC9U4bgAWJb5BtawAcn13gSacUX4GhLgM8MSEMzMmNOs1MXDmS8jhMaDtmolE9B3sEkAseNxd0AWJLZzeYgCyS6mzx0hKCTEjqZgIW8upU2JXzluJjXEFJe8j9B3Rhb2ARM6utCNhh8Xn0RFMTMwtoJrjX4idWoZyjmBuhXkU5jCXiStnWdcNMct/GCgV0oj3Cjezd788efQDj4HEgjJzjOv root@pcentos
        name: cloudinitdisk
```
