### ISSUE TITLE
access services exposed via IPv6 addresses not working

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#4428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Using `batchv1.Job` to access services exposed via ipv6 family IP addresses fails when a particular port is specified.

**What you expected to happen**:
The batch job should successfully access the service.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VMI using IPv6 masquerade binding mechanism. Use the yaml below (adapted from [the vmi-masquerade example](https://github.com/kubevirt/kubevirt/blob/master/examples/vmi-masquerade.yaml)):

```yaml
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-masquerade
  name: vmi-masquerade
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: testmasquerade
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: testmasquerade
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
    name: containerdisk
  - cloudInitNoCloud:
      networkData: |
        version: 2
        ethernets:
          eth0:
            addresses: [ fd10:0:2::2/120 ]
            dhcp4: true
            gateway6: fd10:0:2::1
      userData: |-
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        dnf install -y nmap-ncat
    name: cloudinitdisk
```

2. Start a process inside the VMI listening to a port; use netcat, which is what the functional tests use. Log into the VM and execute the following command, in the background.

```bash 
$ nc -klp 1500 --sh-exec 'echo -e "Hello World!"'
```

3. Create a service entity exposing the port where the process is listening to. Use the following yaml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  ports:                                                                                                                                      
  - port: 1500                                                                                                                                
    protocol: TCP                                                                                                                             
    targetPort: 1500                                                                                                                          
  ipFamily: IPv6                                                                                                                              
  selector:                                                                                                                                   
    special: vmi-masquerade                                                                                                                   
  type: ClusterIP                                                                                                                                                       
```

4. Create a `batchv1.Job` that contacts the aforementioned service. For this, you'll need to know the IP of the service - e.g. `kubectl get services <service name> -o=custom-columns=service_ip:.spec.clusterIP `. Please refer to the following yaml:

```yaml 
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: client
    kubevirt.io: test
  name: client-kw86m
spec:
  activeDeadlineSeconds: 480
  backoffLimit: 3
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
  template:
    spec:
      containers:
      - args:
        - set -x; x="$(head -n 1 < <(nc <service IP or service name> 1500
          -i 3 -w 3))"; echo "$x" ; if [ "$x" = "Hello World!" ]; then echo "succeeded";
          exit 0; else echo "failed"; exit 1; fi
        command:
        - /bin/bash
        - -c
        image: registry:5000/kubevirt/vm-killer:devel
        imagePullPolicy: IfNotPresent
        name: netcat
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30

```

**Anything else we need to know?**:
Modifying the client to ping the service before attempting to contact a port makes it work, as shown in the [test helper](https://github.com/kubevirt/kubevirt/blob/master/tests/job.go#L114).

**Environment**:
- KubeVirt version (use `virtctl version`): v0.34.0
- Kubernetes version (use `kubectl version`): v1.19
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
