### ISSUE TITLE
kubevirt device-plugin "Failed to read from '/sys/bus/pci/devices"

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#4563]
**What happened**:
provision VM with DP ( To expose PCI  device ) failed with the following error:

BTW, virt console works 
```
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to read from '/sys/bus/pci/devices/0000:b1:00.0/config' : No such file or directory","pos":"virPCIDeviceRead:345","subcomponent":"libvirt","thread":"52","timestamp":"2020-11-17T09:56:20.853000Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain defined.","name":"vm1","namespace":"default","pos":"manager.go:1269","timestamp":"2020-11-17T09:56:20.859659Z","uid":"c585a070-73e8-4f41-b364-7c976eba8aa0"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 0 received","pos":"client.go:358","timestamp":"2020-11-17T09:56:20.859765Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Shutoff(5):Unknown(0)","pos":"client.go:241","timestamp":"2020-11-17T09:56:20.861421Z"}
{"component":"virt-launcher","level":"info","msg":"Successfully connected to domain notify socket at /var/run/kubevirt/domain-notify-pipe.sock","pos":"client.go:136","timestamp":"2020-11-17T09:56:20.862266Z"}
{"component":"virt-launcher","level":"info","msg":"Detected domain with UUID 133bf63e-9459-5126-9b21-b56e9b3d17b3","pos":"virt-launcher.go:217","timestamp":"2020-11-17T09:56:20.864060Z"}
{"component":"virt-launcher","level":"info","msg":"Monitoring loop: rate 1s start timeout 5m0s","pos":"monitor.go:164","timestamp":"2020-11-17T09:56:20.864094Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: default_vm1","pos":"client.go:334","timestamp":"2020-11-17T09:56:20.864801Z"}
{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vm1/noCloud.iso","pos":"cloud-init.go:499","timestamp":"2020-11-17T09:56:20.865012Z"}
{"component":"virt-launcher","level":"error","msg":"At least one cgroup controller is required: No such device or address","pos":"virCgroupDetect:416","subcomponent":"libvirt","thread":"50","timestamp":"2020-11-17T09:56:20.876000Z"}
{"component":"virt-launcher","level":"info","msg":"2020-11-17 09:56:20.870+0000: starting up libvirt version: 6.0.0, package: 16.fc31 (Unknown, 2020-04-07-15:55:55, ), qemu version: 4.2.0qemu-kvm-4.2.0-27.fc31, kernel: 3.10.0-1062.9.1.el7.x86_64, hostname: vm1","subcomponent":"qemu","timestamp":"2020-11-17T09:56:20.888135Z"}
```

**What you expected to happen**:
one vm up and running and 1 PCI Device as requested.

```
**How to reproduce it (as minimally and precisely as possible)**:
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: vm1
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          gpus:
          - deviceName: nvidia.com/goya
            name: gpu1
          rng: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 15Gi
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: fedora
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: vm1
            chpasswd:
              list: |
                cloud-user:rhel
                root:rheladmin
              expire: False
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa .....
        name: cloudinitdisk
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
