### ISSUE TITLE
Need a way to inject static ip on multus controlled interface

### ISSUE THREAD

**Issue by jseguillon** [kubevirt/kubevirt#4564]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind bug

/kind enhancement

**What happened**:
I'm using a bridge interface via multus and I'd like to inject static ip on it. 

Im' using a bridge a second interface via : 
```
  template:
    spec:
      networks:
      - name: default
        pod: {}
      - name: test
        multus:
          networkName: a-bridge-network
```

I'd like to inject static ip on the multus interafce as described here  : https://github.com/intel/multus-cni/issues/278#issuecomment-482765376 => define static ipam and inject IP in the `k8s.v1.cni.cncf.io/networks` annotation of the Pod : 
```
  annotations:
     k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "macvlan-conf-1",
          "ips": ["10.2.2.42", "2001:db8::5"]
        }
      ]
```

**What you expected to happen**:

Since kube-virt does handle the whole creation of the `k8s.v1.cni.cncf.io/networks:` annotation I cannot control the IP injection. 
I wish I could inject the ip into the VM yaml description. 

A generic mechanism that could merge json generated by kubevirt plus free json fields added in the VM spec may be usefull for other use cases (?) 

**How to reproduce it (as minimally and precisely as possible)**:

Create VM with multus plus static ipam and try to inject static IP on multus controlled interfaces. 

**Anything else we need to know?**:

Can "workaround" by insert `ips` field after Pod is created.

More details on gist here : https://gist.github.com/jseguillon/538f3f2474785c12c719be88b1a3a100

**Environment**:
- KubeVirt version (use `virtctl version`):
virtctl version 
Client Version: version.Info{GitVersion:"v0.33.0", GitCommit:"1ac45c6f119296b1a83550840dada59d2facadaa", GitTreeState:"clean", BuildDate:"2020-09-22T07:50:34Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: see gist  https://gist.github.com/jseguillon/538f3f2474785c12c719be88b1a3a100
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by jseguillon** [comment]
Searched a bit on multus git. I think here is the list of fields that  should be defined to cover any use-case : https://github.com/intel/multus-cni/blob/master/types/types.go#L119-L150

Plus one example of test done by Multus : https://github.com/intel/multus-cni/blob/master/e2e/default-route1.yml#L25

**Comment by zakkg3** [comment]
Need this. +1
Trying to workarround this by giving the net-attach-def a range of 1 ip. and create one of them per ip. then in the Vm i can specify this network-attach-deff.
ofc this does not scale. and its a workarround.  
I guess its not too tricky to implement: add a filed on the vm object, something like "pod-annotations:" and then render this to the pod will do the trick and also enable other features...

**Comment by zakkg3** [comment]
i am finally working arround this by using this network attach definition:

```
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: static-57-20
  namespace: test
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "plugins": [{
        "type": "bridge",
        "bridge": "bridge.2933",
        "mtu": 9000,
        "ipam": {
          "type": "static",
            "addresses": [
              {
                "address": "10.212.57.20/21"
              }
            ]
        }
      }]
    }
```

on the vm cloud-init you need to dhcp 
```
          networkData: |-
            version: 1
            config:
            - type: physical
              name: eth0
              subnets:
                - type: dhcp
```

----
In your case if you cant dhcp... and only if its not your default interface (if is the default it stucks on podinitilizing)  you could do:


```
    {
      "cniVersion": "0.3.1",
      "name": "bridge-no-ipam",
      "plugins": [{
        "type": "bridge",
        "bridge": "bridge.1234",
        "ipam": {}
      }]
    }
```

And then use cloud-init to set your ip in your VM yaml:

```
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                eth1:
                  addresses: [ 10.212.57.20/21 ]
```

**Comment by jseguillon** [comment]
Thanks for feedback @zakkg3 
 Sure this workarounds but this also requires the one network attachment per VMs

I still think  a feature for "one network attachment for all - supercharge per VM" would be welcomed

**Comment by zakkg3** [comment]
Finally found a best workarround:

use the net-attach-def with ipam: {}
But dont add the default filed in the vm object so it does not get stuck on PodInitializing

```
kind: VirtualMachine
...
    - name: network-name
        multus:
          # Uncomment this and the virt-launcher pod is no longer initialzed. bug 1
          #default: true
          networkName: a-namespace/the-net-attcah-def-name
          # if you dont specify the nanmespace it must exist on the defualt namespace  bug2
...
      volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 1
              config:
                - type: physical
                  name: eth0
                  subnets:
                     - type: static
                       address: 10.212.59.5/21
                       gateway: 10.212.56.1
```

this works and is for me an acceptable workaround we are going into production with this setup :trollface:
