### ISSUE TITLE
How to bind VM NIC MACAddress with pod auto-assigned MACAddress?

### ISSUE THREAD

**Issue by chenyg0911** [kubevirt/kubevirt#4566]
I've try to move virtualmachine to managed by k8s. When use pvc persistent disk, when the VM shutdown then start, the pod assigned mac address is changed, It's different with /etc/netplan/50-cloud-init.yaml (Ubuntu-20.04) Or /etc/sysconfig/network-scripts/ifcfg-eth0(CentOS7), So dhcp can't aqure IP for VM. I've edit the 50-cloud-init.yaml MACAddress to match the VM NIC MACAddress, and `netplan apply` to requre the IP, after network service restart, the VM work normal. 

I try to set a fix MAC address, like that:
```
          interfaces:
          - bridge: {}
            macAddress: ba:0e:8b:f3:43:6d

```
the vm can aquire IP through DHCP, but network isolated, VM can't accessable, even can't ping the pod inside k8s cluster. 

attach my vm manifest files:
pvc-ubuntu.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "ubuntu"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint:  "http://image-repo/focal-server-cloudimg-amd64.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: hostpath

```

ubuntu-vm.yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: ubuntu-focal
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-focal
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            # macAddress: ba:0e:8b:f3:43:6d
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: ubuntu
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ubuntu
            ssh_pwauth: yes
            chpasswd:
                list: |
                  ubuntu:password
                  root:password
                expire: False
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3N...
        name: cloudinitdisk

```
