### ISSUE TITLE
cannot start vmi with containerDisk

### ISSUE THREAD

**Issue by hougangliu** [kubevirt/kubevirt#4613]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

see my vmi example as below from [here](https://github.com/kubevirt/kubevirt/blob/master/examples/vmi-fedora.yaml):

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```
however it cannot work well (vmi cannot change to `Running`), and the corresponding node virt-handler pod says as below
```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vmi-fedora","namespace":"default","pos":"vm.go:1314","reason":"failed to find a sourceFile in containerDisk containerdisk: Failed to check /proc/1/root/var/lib/docker/devicemapper/mnt/f98b595a54f0d1deec6b86c21996eacd3ce7cf3963d123d7dd0af9d59869f40f/disk for disks: open /proc/1/root/var/lib/docker/devicemapper/mnt/f98b595a54f0d1deec6b86c21996eacd3ce7cf3963d123d7dd0af9d59869f40f/disk: no such file or directory","timestamp":"2020-12-02T07:16:18.389979Z","uid":"e9862fab-d9a2-41ca-a9f3-22e86433a111"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vmi-fedora","pos":"vm.go:922","reason":"failed to find a sourceFile in containerDisk containerdisk: Failed to check /proc/1/root/var/lib/docker/devicemapper/mnt/f98b595a54f0d1deec6b86c21996eacd3ce7cf3963d123d7dd0af9d59869f40f/disk for disks: open /proc/1/root/var/lib/docker/devicemapper/mnt/f98b595a54f0d1deec6b86c21996eacd3ce7cf3963d123d7dd0af9d59869f40f/disk: no such file or directory","timestamp":"2020-12-02T07:16:18.390088Z"}

```

when I attach the corresponding node virt-handler pod, and I find there is /proc/1/root/var/lib/docker/devicemapper/mnt/f98b595a54f0d1deec6b86c21996eacd3ce7cf3963d123d7dd0af9d59869f40f/rootfs/disk in the pod, then add `path` filed in containerDisk field.

```
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
      path: /rootfs/disk
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```
it cannot still work, and the corresponding node virt-handler pod says
```
{"component":"virt-handler","kind":"","level":"info","msg":"Bind mounting container disk at /var/lib/docker/devicemapper/mnt/f07a06cc78216b536344741606bfbb40dd9fdc8739c88e86baa0bbf80933f6b6/rootfs/disk to /var/lib/kubelet/pods/f7624b4f-1e61-4109-a752-c3f2f981fcee/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img","name":"vmi-fedora","namespace":"default","pos":"mount.go:252","timestamp":"2020-12-02T07:17:58.807724Z","uid":"77812b4f-f9e8-4281-8a09-37c8687a126c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vmi-fedora","namespace":"default","pos":"vm.go:1314","reason":"failed to bindmount containerDisk containerdisk: Error: not a directory\nUsage:\n  virt-chroot mount [flags]\n\nFlags:\n  -h, --help             help for mount\n  -o, --options string   comma separated list of mount options\n  -t, --type string      fstype\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nnot a directory\n : exit status 1","timestamp":"2020-12-02T07:17:58.829772Z","uid":"77812b4f-f9e8-4281-8a09-37c8687a126c"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vmi-fedora","pos":"vm.go:922","reason":"failed to bindmount containerDisk containerdisk: Error: not a directory\nUsage:\n  virt-chroot mount [flags]\n\nFlags:\n  -h, --help             help for mount\n  -o, --options string   comma separated list of mount options\n  -t, --type string      fstype\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nnot a directory\n : exit status 1","timestamp":"2020-12-02T07:17:58.829947Z"}
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
