### ISSUE TITLE
volumeClaimTemplates for VirtualMachineInstanceReplicaSet

### ISSUE THREAD

**Issue by rony36** [kubevirt/kubevirt#4640]
/kind enhancement

**What happened**:
VirtualMachineInstanceReplicaSet need volumeClaimTemplates

**What you expected to happen**:
Currently Kubevirt supports ephemeral, containerDisk and emptyDisk for vmirs.
These volumes use local node storage.
If applicaton need large cache space, it force unnecessary inflation of node storage for workers.

I excpect VirtualMachineInstanceReplicaSet will support volumeCliamTemplates.

Here is an example:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: testreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      myvmi: myvmi
  template:
    metadata:
      name: test
      labels:
        myvmi: myvmi
    spec:
      domain:
        devices:
          disks:
          - disk:
            name: myvolume
        resources:
          requests:
            memory: 64M
  volumeClaimTemplates:
  - metadata:
      name: myvolume
    spec:
       accessModes: [ "ReadWriteOnce" ]
       storageClassName: standard
         resources:
           requests:
             storage: 5Gi
        dataSource:
          name: existing-src-pvc-name
          kind: PersistentVolumeClaim
```
