### ISSUE TITLE
VM created with dataVolume doesn't start, stuck in Pending

### ISSUE THREAD

**Issue by KostadinKrushkov** [kubevirt/kubevirt#4651]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I uploaded an image with the command
./virtctl image-upload dv ubuntu--disk --size=2Gi --image-path=/root/kubevirt/vms/ubuntu-20.10-live-server-amd64.iso
The dataVolume pod got create and is in ready state:
NAME                          READY   STATUS    RESTARTS   AGE
cdi-upload-ubuntu--disk       1/1     Running   0          26m

Due to bug [#2930](https://github.com/kubevirt/kubevirt/issues/2930) I checked and it's status is ready as well
kubectl get pvc ubuntu--disk -o yaml | grep storage.pod.ready
    cdi.kubevirt.io/storage.pod.ready: "true"
          f:cdi.kubevirt.io/storage.pod.ready: {}

So I tried to create a VM using this template

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntu-vm
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: dvdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 2048M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: dvdisk
    dataVolume:
      name: ubuntu--disk
status: {}

```

But it's stuck in pending. Because of [2933](https://github.com/kubevirt/kubevirt/issues/2933) I checked the controller logs and I see the log
"Delaying pod creation while DataVolume populates", yet that pod is active and as far as I see healthy

**What you expected to happen**:
The virtual machine to start, or to give reason why it is staying in Pending state.

**How to reproduce it (as minimally and precisely as possible)**:
Use steps in description.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.34.2", GitCommit:"48956f60864ece98118d7894327caf7513c5b942", GitTreeState:"clean", BuildDate:"2020-11-17T13:47:56Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications:
Showed template in bug description.
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):
Linux ...-kubevirt 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
