### ISSUE TITLE
VM with Block type DataVolume / PVC is broken in master

### ISSUE THREAD

**Issue by salanki** [kubevirt/kubevirt#4658]
/kind bug
> /kind enhancement

**What happened**:

It seems to be looking for a non existent disk image in a mount point that doesn't exist since it is mapped to a device.

```
{"component":"virt-launcher","level":"error","msg":"Cannot access storage file '/var/run/kubevirt-private/vmi-disks/dv/disk.img': No such file or directory","pos":"virStorageFileReportBrokenChain:5168","subcomponent":"libvirt","thread":"65","timestamp":"2020-12-10T23:27:50.039000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Starting the VirtualMachineInstance failed.","name":"halting-earthquake","namespace":"tenant-themolecule","pos":"manager.go:1387","reason":"virError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vmi-disks/dv/disk.img': No such file or directory')","timestamp":"2020-12-10T23:27:50.040826Z","uid":"883f7591-c8e2-4d0c-a8cd-6a61f480a1e0"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"halting-earthquake","namespace":"tenant-themolecule","pos":"server.go:161","reason":"virError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vmi-disks/dv/disk.img': No such file or directory')","timestamp":"2020-12-10T23:27:50.040900Z","uid":"883f7591-c8e2-4d0c-a8cd-6a61f480a1e0"}
```

**How to reproduce it (as minimally and precisely as possible)**:

```
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: halting-earthquake
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 465Gi
        storageClassName: block-nvme-ewr1
        volumeMode: Block
      source:
        http:
          url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
```
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): master @ dbb25d27ddd685c8daf5fac8e73d85825a160a43
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
