### ISSUE TITLE
Delay in the time taken for the VMI to go to Running state with v0.35.0

### ISSUE THREAD

**Issue by sseetharaman6** [kubevirt/kubevirt#4696]
> /kind bug

**What happened**:
I have been using kubevirt v0.24.0 for a while and when trying to upgrade to v0.35.0, I noticed that there is a huge delay from the time VMI is scheduled to the time VMI is Running and it looks like a possible regression. This is reproducible for a VMIs using sidecars and  with VMIs using just container disk as well.

The main bottleneck seems to be after connecting to libvirt daemon, there are failures to notify domain sock and eventually the libvirt connection is lost, a new libvirt connection is established. So between the initial connection to libvirt and marking as ready, there is close to ~90 sec.
 
The following are logs for a VM with sidecar :
On the virt-launcher pod's compute container
```
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:396","timestamp":"2020-12-17T19:00:02.473460Z"}
{"component":"virt-launcher","level":"info","msg":"failed to dial notify socket: /var/run/kubevirt/domain-notify-pipe.sock","pos":"client.go:116","reason":"context deadline exceeded","timestamp":"2020-12-17T19:00:04.474206Z"}
...
{"component":"virt-launcher","level":"info","msg":"failed to dial notify socket: /var/run/kubevirt/domain-notify-pipe.sock","pos":"client.go:116","reason":"context deadline exceeded","timestamp":"2020-12-17T19:01:20.481461Z"}
{"component":"virt-launcher","level":"error","msg":"Connection to libvirt lost","pos":"libvirt.go:276","timestamp":"2020-12-17T19:01:22.475879Z"}
{"component":"virt-launcher","level":"info","msg":"Established new Libvirt Connection","pos":"libvirt.go:301","timestamp":"2020-12-17T19:01:32.478175Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:74","timestamp":"2020-12-17T19:01:38.483314Z"}
```
virt-launcher logs : https://gist.github.com/sseetharaman6/7f098b2a3ea54b0b47cfdc245a3c447d
virt-handler logs: https://gist.github.com/sseetharaman6/b11ef5af0a2fee5e99f845ad46b79aa8

For comparison, when creating a VMI
```
v0.35.0
e2e time for VM to be Running: 98.218897000 seconds
Breakdown - Time taken to connect to libvirt domain : 0.506636000 seconds, Time taken for "Marked as ready" : 97.13499000 seconds, Time taken for Domain to be started : 0.698762000 seconds
v0.24.0
e2e time for VM to be Running : 4.715450000 seconds
Breakdown - Time taken to connect to libvirt domain : 0.502805000 seconds,  Time taken for "Marked as ready" : 3.974930000 seconds, Time taken for Domain to be started : 0.237715000 seconds
```
Let me know if you need any other data

**What you expected to happen**:
Expectation is no regression in terms of the time taken for the VMI to come up. 

**How to reproduce it **:
Create a VMI with an older version of Kubevirt(v0.24.0 for example) and latest kubevirt version (v0.35.0) and compare the time taken for the VM to go to Running state. 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.24.0 / v0.35.0
- Kubernetes version (use `kubectl version`): v1.17.8

**Comment by rmohr** [comment]
/bug

Will have a look. Did you also try starting once a VMI without hooks, just to see if it works usually fast?

**Comment by davidvossel** [comment]
>  This is reproducible for a VMIs using sidecars and with VMIs using just container disk as well.

just so we're working from the same baseline here, would you see if this simple vmi has the same startup timing issues for you?

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-example
  name: vmi-example
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/cirros-container-disk-demo
    name: containerdisk
```
