### ISSUE TITLE
Cannot login with cloud init credentials into Ubuntu VM

### ISSUE THREAD

**Issue by mel1nn** [kubevirt/kubevirt#4762]
/kind bug

**What happened**:

I created a datavolume composed of an Ubuntu 20.04 cloud image (https://cloud-images.ubuntu.com/focal/20201210/focal-server-cloudimg-amd64.img). Then I create the VMI that references this datavolume with a cloud init config that specifies username and password but when I want to login using the `virtlctl console` command, it tells me that the login is incorrect.

Here is my VMI:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubuntu-20-04-vm
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: dvdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
    machine:
      type: ""
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
  terminationGracePeriodSeconds: 0
  volumes:
  - name: dvdisk
    dataVolume:
      name: dv-ubuntu-20-04
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        users:
        - name: user
          lock_passwd: false
          passwd: 098f6bcd4621d373cade4e832627b4f6
          ssh_pwauth: true
```

Thanks for your help !

**Environment**:
- KubeVirt version (use `virtctl version`): v0.36.0
- Kubernetes version (use `kubectl version`): v1.19.2
