### ISSUE TITLE
Enable to set the error policy

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#4799]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Libvirt has the field error policy and this defines how qemu is going to treat IO errors. More details in the [libvirt documentation](https://libvirt.org/formatdomain.html). The possible values are :
  - stop 
  - report 
  - ignore 
  - enospace

Currently, the value is not set and the default is `report`.

I tried locally to set the error_policy for the errdev0 disk (a faulty disk)  on a test guest:
1 Create the faulty disk:

```bash
$ dmsetup create errdev0 << EOF
0 204791 error
EOF
```
and pass it to the VM and set the error_policy=stop
```xml
<driver name='qemu' type='raw' error_policy='stop'/>
<source dev='/dev/mapper/errdev0' index='1'/>
```
In this case, the VM is paused:
```bash
$ sudo virsh list
Id Name State
---------------------
2 test paused

$ virsh qemu-monitor-command --hmp test 'info block'
libvirt-2-format: /home/afrosi/test.qcow2 (qcow2)
Attached to: /machine/peripheral/virtio-disk0/virtio-backend
Cache mode: writeback

libvirt-1-format: /dev/mapper/errdev0 (raw)
Attached to: /machine/peripheral/virtio-disk1/virtio-backend
I/O status: failed
Cache mode: writeback

$ virsh qemu-monitor-command --hmp test 'info status'
VM status: paused (io-error)
```
I tried to reproduce a similar setup with the faulty device in a kubevirt environment and the VM was not paused, and the IO errors were reported from the guest OS. This is the default behavior and when the `error_policy` is set to `report`.

**What you expected to happen**:
I expect that the user is able to set the error policy they want to use for the VM. For example, setting to `stop` or `enospace`. I'd like just to ask if you've already considered setting this option.

**Comment by alicefr** [comment]
If I set the error_policy to `stop`, the VM is paused in libvirt.
More details:
Diff:
```diff
index afb0a865f..4953905e6 100644
--- a/pkg/virt-launcher/virtwrap/converter/converter.go
+++ b/pkg/virt-launcher/virtwrap/converter/converter.go
@@ -206,10 +206,12 @@ func Convert_v1_Disk_To_api_Disk(c *ConverterContext, diskDevice *v1.Disk, disk
                }
        }
        disk.Driver = &api.DiskDriver{
-               Name:  "qemu",
-               Cache: string(diskDevice.Cache),
-               IO:    string(diskDevice.IO),
+               Name:        "qemu",
+               Cache:       string(diskDevice.Cache),
+               IO:          string(diskDevice.IO),
+               ErrorPolicy: "stop",
        }
+
        if numQueues != nil && disk.Target.Bus == "virtio" {
                disk.Driver.Queues = numQueues
        }
```
Setup:
For simplicity create single node cluster with `make cluster-up`. 
Create a faulty disk:
```bash
cluster-up/ssh.sh node01
sudo dmsetup create errdev0 << EOF
0 204791 error
EOF
```
Apply these yamls:
- faulty-disk.yaml:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ioerror-disk
spec:
  volumeMode: Block
  storageClassName: device
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /dev/mapper/errdev0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ioerror-pvc
spec:
  volumeMode: Block
  storageClassName: device
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
- faulty-vm.yaml:
```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-block
  name: vm-block
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-block
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk  
          - disk:
              bus: virtio
            name: ioerror-disk
        machine:
          type: ""
        resources:
          requests:
            memory: 2G
      terminationGracePeriodSeconds: 0
      volumes:
      - name: ioerror-disk
        persistentVolumeClaim:
          claimName: ioerror-pvc
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: containerdisk
```
After you create the VM:
```bash
$ cluster-up/kubectl.sh get po
NAME                             READY   STATUS    RESTARTS   AGE
local-volume-provisioner-tnstg   1/1     Running   0          21m
virt-launcher-vm-block-m72cc     2/2     Running   0          6m54s
$ cluster-up/kubectl.sh exec -ti virt-launcher-vm-block-m72cc -- virsh list
Defaulting container name to compute.
Use 'kubectl describe pod/virt-launcher-vm-block-m72cc -n default' to see all of the containers in this pod.
 Id   Name               State
---------------------------------
 1    default_vm-block   paused
```
