### ISSUE TITLE
[Proposal] Possible to add VMImage CRD?

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#4869]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

As cluster admin, we want to simplify the creation process of vms. Users are from different namespaces want to create vms with common os releases easily.

**What you expected to happen**:

 I'm wondering if we could have cluster-wide VMImage CRD like following:
```
kind: VMImage
metadata:
  name: centos76
spec:
  source: xxxxx
```
and OSDisk CRD to use VMImages like following:
```
kind: OSDisk
metadata:
  name: test-vm-os
spec:
  image: centos76
  size: 40Gi
```
osdisk controller will create pvc with the samename, and then users can use the pvc in VirtualMachine CRD.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
