### ISSUE TITLE
RBAC rolebinding kubevirt.io:edit failed to list kubevirts in kubevirt.io

### ISSUE THREAD

**Issue by knfoo** [kubevirt/kubevirt#4888]
/kind bug

**What happened**:
I have installed the kubevirt operator from upstream manifest.
 kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.37.1/kubevirt-operator.yaml

I have created a rolebinding to allow users in a namespace to use kubevirt.io:edit clusterrole.
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt.io:edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: testgroup
```

When I run `kubectl get all` I get a permission error.
``` 
Error from server (Forbidden): kubevirts.kubevirt.io is forbidden: User "knfoo" cannot list resource "kubevirts" in API group "kubevirt.io" in the namespace "testapp"
```

**What you expected to happen**:
When I run `kubectl get all` I get a list of 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the install instructions for the operator and cr.
Create a user in a namespace with a rolebinding for the clusterrole kubevirt.io:edit 

**Anything else we need to know?**:
I can fix it by adding this to the clusterrole kubevirt.io:edit
```
- apiGroups:
  - kubevirt.io
  resources:
  - kubevirts
  verbs:
  - list
```
But maybe not the best solution to give everybody access to list the kubevirts

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.35.0", GitCommit:"b77b858ac9345ae6858cf409e1833f4548ec2809", GitTreeState:"clean", BuildDate:"2020-11-09T13:38:36Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.37.1-dirty", GitCommit:"f270b5befe16c20a11c34f22efecf2407f9591bc", GitTreeState:"dirty", BuildDate:"2021-01-21T20:13:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
