### ISSUE TITLE
Deploying a vm with uefi fails

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#4897]
BUG REPORT 

/kind bug

**What happened**:
Deploying a vm with uefi fails with a message about secure boot

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"virtualmachine-validator.kubevirt.io\" denied the request: spec.template.spec.domain has EFI SecureBoot enabled. SecureBoot requires SMM, which is currently disabled.","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"spec.template.spec.domain has EFI SecureBoot enabled. SecureBoot requires SMM, which is currently disabled.","field":"spec.template.spec.domain"}]},"code":422}

**What you expected to happen**:
Vm would launch

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    kcli/image: quay.io/karmab/debian-container-disk-demo
    kcli/plan: kvirt
    kcli/profile: quay.io/karmab/debian-container-disk-demo
  labels:
    kubevirt.io/os: linux
    special: vmi-migratable
  name: lonely-ptolemy
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: lonely-ptolemy
        kubevirt.io/provider: kcli
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: lonely-ptolemy-disk0
          - cdrom:
              bus: sata
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/karmab/debian-container-disk-demo
        name: lonely-ptolemy-disk0
      - cloudInitNoCloud:
          secretRef:
            name: lonely-ptolemy-userdata-secret
        name: cloudinitdisk
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.37
- Kubernetes version (use `kubectl version`): v1.20.2
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jean-edouard** [comment]
I think what you want is to turn off Secure Boot, which is enabled by default for security reasons:
```
        firmware:
          bootloader:
            efi:
              secureBoot: false
```

Thanks for the heads-up @vladikr!
