### ISSUE TITLE
Unable to connect to http data source: Get https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz: dial tcp: lookup download.fedoraproject.org: Temporary failure in name resolution

### ISSUE THREAD

**Issue by akashrpo** [kubevirt/kubevirt#4981]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
I was trying to run a VM in Kubevirt following https://kubevirt.io/labs/kubernetes/lab2 guide. However, after following "Use the CDI" step executing "kubectl create -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/pvc_fedora.yml" command. The PVC and its importer-fedora pod gets created but after some time it goes from running state to error state and while describing the PVC it states the Warning message as "Unable to connect to http data source: Get https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz: dial tcp: lookup download.fedoraproject.org: Temporary failure in name resolution"

**What you expected to happen**:
Expected to successfully create VM following the https://kubevirt.io/labs/kubernetes/lab2 guide.

**How to reproduce it (as minimally and precisely as possible)**:
Link: https://kubevirt.io/labs/kubernetes/lab2
1. Follow Install the CDI steps
2. Use the CDI: In this step, the pods get created, and then after few minutes its goes from running state to error state along with the above error message which can be seen by describing the PVC as:
 kubectl describe pvc fedora
or the pods as:
 kubectl describe pods importer-fedora

**Anything else we need to know?**:
-

**Environment**:
- KubeVirt version: Client Version: version.Info{GitVersion:"v0.37.2", GitCommit:"0e63b5f9d5debd68e5247c5fb83f285d66d618a3", GitTreeState:"clean", BuildDate:"2021-01-27T21:35:58Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
the server is currently unable to handle the request

- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

- Kernel (e.g. `uname -a`):
Linux niral 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Output:**

kubectl get pods
NAME              READY   STATUS   RESTARTS   AGE
importer-fedora   0/1     Error    0          65s

kubectl get pv
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM            STORAGECLASS   REASON   AGE
task-pv-volume   4Gi        RWO            Retain           Bound    default/fedora   hostpath                65m

kubectl get pvc
NAME     STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
fedora   Bound    task-pv-volume   4Gi        RWO            hostpath       65m

kubectl describe pvc fedora
![image](https://user-images.githubusercontent.com/64877812/107181439-df126100-6a00-11eb-98ef-a4b6441a5f24.png)

kubectl describe pods importer-fedora
```
Name:         importer-fedora
Namespace:    default
Priority:     0
Node:         knode2/192.168.1.28
Start Time:   Mon, 08 Feb 2021 11:33:02 +0530
Labels:       app=containerized-data-importer
              cdi.kubevirt.io=importer
              prometheus.cdi.kubevirt.io=
Annotations:  cdi.kubevirt.io/storage.createdByController: yes
              cni.projectcalico.org/podIP: 172.16.69.218/32
              cni.projectcalico.org/podIPs: 172.16.69.218/32
Status:       Running
IP:           172.16.69.218
IPs:
  IP:           172.16.69.218
Controlled By:  PersistentVolumeClaim/fedora
Containers:
  importer:
    Container ID:  docker://43c2492bb7d2bcd4567c151848e38441b0c81de4e58e1aaf57fcf4d643a0a090
    Image:         kubevirt/cdi-importer:v1.28.3
    Image ID:      docker-pullable://kubevirt/cdi-importer@sha256:19b1ef32d81275b6b9397aabfc4769fada244af8d4d0a8e79a903925010d4092
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      -v=1
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Message:      Unable to connect to http data source: Get https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz: dial tcp: lookup download.fedoraproject.org: Temporary failure in name resolution
      Exit Code:    1
      Started:      Mon, 08 Feb 2021 12:36:01 +0530
      Finished:     Mon, 08 Feb 2021 12:36:42 +0530
    Ready:          False
    Restart Count:  15
    Limits:
      cpu:     0
      memory:  0
    Requests:
      cpu:     0
      memory:  0
    Environment:
      IMPORTER_SOURCE:               http
      IMPORTER_ENDPOINT:             https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
      IMPORTER_CONTENTTYPE:          kubevirt
      IMPORTER_IMAGE_SIZE:           4Gi
      OWNER_UID:                     1f9dd87c-70d3-4c30-9872-68f2e4b87aa5
      FILESYSTEM_OVERHEAD:           0.055
      INSECURE_TLS:                  false
      IMPORTER_DISK_ID:              
      IMPORTER_UUID:                 
      IMPORTER_BACKING_FILE:         
      IMPORTER_THUMBPRINT:           
      IMPORTER_CURRENT_CHECKPOINT:   
      IMPORTER_PREVIOUS_CHECKPOINT:  
      IMPORTER_FINAL_CHECKPOINT:     
      PREALLOCATION:                 false
    Mounts:
      /data from cdi-data-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-58wp4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  cdi-data-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  fedora
    ReadOnly:   false
  default-token-58wp4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-58wp4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Normal   Pulled   21m (x13 over 66m)   kubelet  Container image "kubevirt/cdi-importer:v1.28.3" already present on machine
  Warning  BackOff  71s (x243 over 64m)  kubelet  Back-off restarting failed container

```

**Comment by akashrpo** [comment]
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath

```

In this .yaml file, I even tried giving file:// URL. However, it stated the following error as:
Unable to connect to http data source: Get file://Fedora-Cloud-Base-33-1.2.x86_64.raw.xz: unsupported protocol scheme "file"

**Comment by akashrpo** [comment]
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath

```

In this .yaml file, I even tried giving file:// URL. However, it stated the following error as:
Unable to connect to http data source: Get file://Fedora-Cloud-Base-33-1.2.x86_64.raw.xz: unsupported protocol scheme "file"
