### ISSUE TITLE
[snapshot] When the pvc related to volume is from a clone, vm snapshot will create failed

### ISSUE THREAD

**Issue by cumirror** [kubevirt/kubevirt#5081]
I recently used the snapshot feature of vm, and the following error occurred during use:
```
E0128 07:24:08.404961       1 util.go:125] VirtualMachineSnapshotContent.snapshot.kubevirt.io "vmsnapshot-content-19a6f130-9dd7-4be7-8cc3-65c40b0a0199" is invalid: spec.volumeBackups.persistentVolumeClaim.spec.dataSource.apiGroup: Invalid value: "null": spec.volumeBackups.persistentVolumeClaim.spec.dataSource.apiGroup in body must be of type string: "null"
```

vm's volume relation pvc is as following:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpl-vol-ym0w2c6o
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    apiGroup: null
    kind: PersistentVolumeClaim
    name: ubuntu
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-076ba029-2680-459b-acaf-cb5978a4a686
```

Through analysis, it should be because the apiGroup field in  dataSource has no "omitempty" flags, resulting in null when json is serialized, and an error occurs when deserialization from configuration.

By modifying the json attribute of the related field in the vendor, i solved this problem.
```
# git diff vendor/k8s.io/api/core/v1/types.go
diff --git a/vendor/k8s.io/api/core/v1/types.go b/vendor/k8s.io/api/core/v1/types.go
index fcd455402..0543803da 100644
--- a/vendor/k8s.io/api/core/v1/types.go
+++ b/vendor/k8s.io/api/core/v1/types.go
@@ -4992,7 +4992,7 @@ type TypedLocalObjectReference struct {
        // If APIGroup is not specified, the specified Kind must be in the core API group.
        // For any other third-party types, APIGroup is required.
        // +optional
-       APIGroup *string `json:"apiGroup" protobuf:"bytes,1,opt,name=apiGroup"`
+       APIGroup *string `json:"apiGroup,omitempty" protobuf:"bytes,1,opt,name=apiGroup"`
        // Kind is the type of resource being referenced
        Kind string `json:"kind" protobuf:"bytes,2,opt,name=kind"`
        // Name is the name of resource being referenced
```

The reproduction method:
1. create a pvc from clone
2. give it to volume
3.  then do a snapshot of vm
