### ISSUE TITLE
How to setup the default mount path of emptyDisk ?

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5085]
Hello, 

Following is my VMI specifications,

```yaml
--
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vm-test01
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: harddisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 512M
  networks:
    - name: default
      pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt-base-centos7-img
    - name: harddisk
      emptyDisk:
        capacity: 50Gi
```

after the VM starts up, I can see flowing info from `lsblk`

[root@vm-test01 ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0    8G  0 disk
└─vda1 253:1    0    8G  0 part /
vdb    253:16   0   50G  0 disk

I want to use the device vdb directly, while it doesn't have a mount point , so I have to setup mount point manually.
I wonder, if the mount path of emptyDisk  "harddisk" can be setup defaultly from the VMI specifications ? and how to make it ?

Thanks in advance~
