### ISSUE TITLE
Resize OS volume that was uploaded using virtctl image-upload  

### ISSUE THREAD

**Issue by sanzende** [kubevirt/kubevirt#5125]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I did not find options to increase of the volume hence used the method described below. 

Edited the pvc spec(yaml) that was created as part of virtctl image-upload command to increase the size from 80Gi to 100Gi. In the kubectl describe pvc it does show the modified value. If I exec into the pod that is hosting VM using the kubectl exec command, I see the increased size of the volume but but if I login to the VM which is running in this pod, I see the volume is still showing the old size(80Gi) in the output of fdisk and lsblk commands.   

**What you expected to happen**:

The output of lsblk and/or fdisk command in the linux vm should have shown the new size. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Linux (for eg. Centos) VM using kubevirt wherein you upload centos.qcow2 image using the virtctl command which will create a PVC that will have centos.qcow2 image and apply VM spec file.

2. Start VM using virtctl start <VM> which will also create a pod to host a VM.
3. Log into the machine and verify the size of disk 'vda' (80Gi)
4. Stop VM using virtctl stop <VM> which will also delete the pod that was hosting the VM.
5. Edit the PVC that was created as part of virtctl image-upload command to reflect the new value(100Gi)
6. Start VM using virtctl command.
7. ssh to Centos VM and verify the disk which still shows 80Gi
8. kubectl exec to pod hosting the VM and verify the disk size. It shows the new value.

**Anything else we need to know?**:

**Environment**:
-virtclt version: v0.30.6
- KubeVirt version : v0.30.6
- Kubernetes version : 1.16
- VM or VMI specifications:

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos1
    spec:
      nodeSelector:
        kubernetes.io/hostname: test1
      domain:
        ioThreadsPolicy: auto
        cpu:
          cores: 16
        devices:
          blockMultiQueue: true
          disks:
          - disk:
              bus: virtio
            name: harddrive
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: centos1-os
```

- Cloud provider or hardware configuration:
- OS : CentOS Linux release 7.6.1810 (Core)
- Kernel : Linux appserv66 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
