### ISSUE TITLE
Run vmi on ssd nodes, how to persistent the datas between vmi restarts ?

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5173]
**What happened**:
I am running VMI on SSD nodes, and the volume types i used are containerDisk and emptyDisk. After the VMI restarts, the data on the disks are gone. From the user-guide https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#volumes
  it seems if i want to persistent the data between VMI restarts,  i have to use local PV/PVC ?  
do you have any suggestions or "best practice" on running VMI on SSD nodes ?

thanks very much~

**What you expected to happen**:
vm data remains between VMI restarts.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.37
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications:
--
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vm-c7-name01
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: harddisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 512M
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
  networks:
    - name: default
      pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt-base-centos7-image
    - name: harddisk
      emptyDisk:
        capacity: 50Gi
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogY2VudG9zCmNocGFzc3dkOiB7IGV4cGlyZTogRmFsc2UgfQpzc2hfcHdhdXRoOiBGYWxzZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWK0MyTDVjQ3pqN0ZuREJGNVJjaHZrU3pFVlhMVjVNampMejRPRzhNSjhTcTl0VUdoZGMzKzdDYUgzcXZnV2lZVko1SkFQdE9jcVNGNzEzZzd6aWp1SGg5dGxvclpkVXdLeEJFY2I2N1l0aXUyUHhUcE5CZWs2bEdybzhGLzh0SFl2bk9YQnRQTVNqUEhiemx5R3hrTDdrNng5RnArZkpPZkVpTzhweXJISmVOa01aNy81UEViaCtRenN6c2VkbjdnUkNJM0htZ0Z5KzI1M1VpdnZNbTdwNE1uZTVxQVpwemNHZnpBYWhPUks3akZnWDkvQVk4NnZPWjFFeStuVEFhVjhnZWt2bldtMjFLU0htYUdYOExTK3hhODgxM3NmVklLcSsxeEN6L0h6UjRpeUZXejBIWmZHMmFUSFRySmVrbHovbG9BRzIreXFabGdlMG4xenFYSCBjZW50b3NAZ2gtY2xvdWQtdGVzdC10ZXN0MDIubXQKCmJvb3RjbWQ6CiAgLSBwYXJ0ZWQgLXMgL2Rldi92ZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAtcyAtYSBvcHRpbWFsIC9kZXYvdmRiIC0tIHVuaXQgcyBta3BhcnQgcHJpbWFyeSBleHQ0IDAlIDEwMCUKICAtIG1rZnMgLXQgZXh0NCAvZGV2L3ZkYjEKCm1vdW50czoKICAtIFsgL2Rldi92ZGIxLCAvb3B0LCAiZXh0NCIsICJkZWZhdWx0cyxub2ZhaWwiLCAiMCIsICIwIiBdCg==

--
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
We are using local storage on the production environments, and we don't have ceph or other distributed storage on our production environments.

**Comment by davidvossel** [comment]
Hey, I'd recommend using a VirtualMachine rather than a VirtualMachineInstance.

With a VirtualMachine you can dynamically create a PVC to host a disk and impoart your container disk into that PVC. This will allow the data to persist across restarts. You can accomplish this by installing cdi and using the DataVolumeTemplate section of the VM spec.


```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: alpine-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: local
      source:
        registry:
          url: docker://some-registry/some-image:some-tag
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        machine:
          type: ""
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1

```
