### ISSUE TITLE
virt-controller should update vmi status phase based on pod status

### ISSUE THREAD

**Issue by fanzhangio** [kubevirt/kubevirt#5195]
**BUG REPORT**:

/kind bug

**What happened**:
Controller normally has two types of resources to care about in reconciliation: 1) primary resources which are the ones controller is going to update status. 2) secondary resources are the ones that controller will operate (CRUD) or being for lookups.

Currently, after creating a launcher pod, in following virt-controller's VMI updateStatus progress, it checks vmi status as well as if pod object exists to update vmi status with Pending or Scheduling. In a situation that pod is not in scheduling (still pending or unset) but virt-controller has made a series of status updates (Pending , Scheduling) onto vmi. It is a misleading of Scheduling and VMI status changes. 

**What you expected to happen**:
In kubevirt case, after initially created launcher pod, vmiController should watch pod's real status phase and update vmi status in **updateStatus(vmi, pod, datavolumes, syncErr)**  

**How to reproduce it (as minimally and precisely as possible)**:
In a case of large bulk vm creation, hundreds of VMI requests and objects are created into k8s apiserver. virt-controller takes actions to create launcher pod if pod does not exits. In the next worker pulling cycle, the vmi is directly set to Pending as pod object is created. And then the next worker pulling cycle, the vmi is set to Scheduling even if the pod is still in pending.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):  0.24+
- Kubernetes version (use `kubectl version`): v1.19.3+
- VM or VMI specifications:
    ```
    apiVersion: kubevirt.io/v1alpha3
    kind: VirtualMachineInstance
    metadata:
      name: testvm
      namespace: default
      labels:
        my.com/preset: defaultPreset
        name: testvm
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              name: default
        resources:
          requests:
            cpu: 100m
            memory: 100M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: testvm-pvc
    ```
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): 
    ```
    NAME="CentOS Linux"
    VERSION="8 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="8"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="CentOS Linux 8 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:8"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-8"
    CENTOS_MANTISBT_PROJECT_VERSION="8"
    REDHAT_SUPPORT_PRODUCT="centos"
    ```
- Kernel (e.g. `uname -a`):
   ```
   Linux nd-zrsjc6j-bs-1602020310020-2a.nd-zrsjc6j.nvmetal.net 4.18.0-80.el8.27782638.x86_64 #1 SMP Wed Mar 25 08:21:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Install tools: kubevirt-operator
- Others:
