### ISSUE TITLE
save vm stats after restart (vmi is recreated)

### ISSUE THREAD

**Issue by llhhbc** [kubevirt/kubevirt#5209]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

**What happened**:
I an create a vm spec like:

```yaml
  spec:
    running: true
    template:
      metadata:
        creationTimestamp: null
        labels:
          special: istio-vm
      spec:
        domain:
          cpu:
            cores: 8
          devices:
            disks:
            - disk:
                bus: virtio
              name: containerdisk
            interfaces:
            - bridge: {}
              name: default
          machine:
            type: q35
          resources:
            requests:
              cpu: "4"
              memory: 8G
        networks:
        - name: default
          pod: {}
        nodeSelector:
          kubernetes.io/hostname: 10-10-40-162
        terminationGracePeriodSeconds: 0
        volumes:
        - containerDisk:
            image: <docker image: build from my centos img >
          name: containerdisk
```

**What you expected to happen**:

I want to save vm info after the vm is restarted. 
pod will be deleted after vm is restart. and all data volume is emptyDir, the data will all lost. How can I set to keep this data?

```yaml
    volumes:
    - emptyDir: {}
      name: sockets
    - emptyDir: {}
      name: virt-bin-share-dir
    - emptyDir: {}
      name: libvirt-runtime
    - emptyDir: {}
      name: ephemeral-disks
    - emptyDir: {}
      name: container-disks
    - emptyDir: {}
      name: hotplug-disks
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.36.0
- Kubernetes version (use `kubectl version`): 1.18
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 4.19.113-300.el7.x86_64
- Install tools:
- Others:
