### ISSUE TITLE
hostname of created VM is not same to VMI name

### ISSUE THREAD

**Issue by jichenjc** [kubevirt/kubevirt#5275]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

not sure whether it's a valid one, just open here to get some opinion 

use `vmi-ephemeral` (example/vmi-ephemeral.yaml) then created a VMI 
and found hostname is same to my KVM hypervisor hostname 
```
$ hostname
jjtesttemp2
```

**What you expected to happen**:

the hostname should be `vmi-ephemeral` because examples/vmi-ephemeral.yaml

```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-ephemeral
  name: vmi-ephemeral
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 128Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/cirros-container-disk-demo:devel
    name: containerdisk

```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
