### ISSUE TITLE
PVCs for the same VM were getting assigned to different nodes

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5362]
Hi,
I hit an issue when using hpp and cdi together, following is my VM specification. After a couple of VMs have been created in our cluster by using cdi and hpp, the VM got stuck in scheduling state with error message: "Unable to schedule default/virt-launcher-vm-c7-datavolume-name50-zclsv: no fit: 0/2 nodes are available: 2 node(s) had volume node affinity conflict.; waiting". Looks the persistent volumes were assigned to different nodes cause the VM staying in scheduling state, how to resolve this issue, could you help me  ? 

Thanks in advance~

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-c7-datavolume-name50
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: sysdv-name50
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: docker://registry.sk.com/kubevirt-base-centos7:latest
          secretRef: endpoint-secret
  - metadata:
      creationTimestamp: null
      name: datadv-name50
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: hostpath-provisioner
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-c7-datavolume-name50
    spec:
      domain:
        devices:
          disks:
            - name: sysdvdisk
              disk:
                bus: virtio
            - name: datadvdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 512M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: sysdvdisk
          dataVolume:
            name: sysdv-name50
        - name: datadvdisk
          dataVolume:
            name: datadv-name50
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogY2VudG9zCmNocGFzc3dkOiB7IGV4cGlyZTogRmFsc2UgfQpzc2hfcHdhdXRoOiBGYWxzZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWK0MyTDVjQ3pqN0ZuREJGNVJjaHZrU3pFVlhMVjVNampMejRPRzhNSjhTcTl0VUdoZGMzKzdDYUgzcXZnV2lZVko1SkFQdE9jcVNGNzEzZzd6aWp1SGg5dGxvclpkVXdLeEJFY2I2N1l0aXUyUHhUcE5CZWs2bEdybzhGLzh0SFl2bk9YQnRQTVNqUEhiemx5R3hrTDdrNng5RnArZkpPZkVpTzhweXJISmVOa01aNy81UEViaCtRenN6c2VkbjdnUkNJM0htZ0Z5KzI1M1VpdnZNbTdwNE1uZTVxQVpwemNHZnpBYWhPUks3akZnWDkvQVk4NnZPWjFFeStuVEFhVjhnZWt2bldtMjFLU0htYUdYOExTK3hhODgxM3NmVklLcSsxeEN6L0h6UjRpeUZXejBIWmZHMmFUSFRySmVrbHovbG9BRzIreXFabGdlMG4xenFYSCBjZW50b3NAZ2gtY2xvdWQtdGVzdC10ZXN0MDIubXQKCmJvb3RjbWQ6CiAgLSBwYXJ0ZWQgLXMgL2Rldi92ZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAtcyAtYSBvcHRpbWFsIC9kZXYvdmRiIC0tIHVuaXQgcyBta3BhcnQgcHJpbWFyeSBleHQ0IDAlIDEwMCUKICAtIG1rZnMgLXQgZXh0NCAvZGV2L3ZkYjEKCm1vdW50czoKICAtIFsgL2Rldi92ZGIxLCAvb3B0LCAiZXh0NCIsICJkZWZhdWx0cyxub2ZhaWwiLCAiMCIsICIwIiBdCg==
--
```

and following is the storage class i am using:
(following this guide: https://github.com/kubevirt/hostpath-provisioner-operator)

```yaml
--
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
creationTimestamp: "2021-03-15T12:02:04Z"
name: hostpath-provisioner
resourceVersion: "13170855"
selfLink: /apis/storage.k8s.io/v1/storageclasses/hostpath-provisioner
uid: 5174ed00-3651-450a-b4f0-98e9ec264ce1
provisioner: kubevirt.io/hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
