### ISSUE TITLE
a new launcher pod should be created after the temporary launcher pod is deleted

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5372]
/kind bug

**What happened**:
Create 9 VMs at a time, 1 VM got stuck in Pending state.

From the output of `kubectl describtion `, looks the  temporary launcher pod is deleted successfully, but no new pod is created caused this issue.

```yaml
$ kubectl describe vmi vm-c7-datavolume-name10
Name:         vm-c7-datavolume-name10
Namespace:    default
Labels:       kubevirt.io/domain=vm-c7-datavolume-name10
              kubevirt.io/size=small
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2021-04-01T06:43:31Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  3
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  vm-c7-datavolume-name10
    UID:                   ea45dc7a-9c80-4670-b21d-2d1a123b12bf
  Resource Version:        18576697
  Self Link:               /apis/kubevirt.io/v1/namespaces/default/virtualmachineinstances/vm-c7-datavolume-name10
  UID:                     851f859a-1d6f-413d-ad25-d6e0fef1b720
Spec:
  Domain:
    Cpu:
      Cores:    1
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   sysdvdisk
        Disk:
          Bus:  virtio
        Name:   datadvdisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  f7c422b4-1cb9-5bfb-8637-4a439889d2af
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  512M
  Networks:
    Name:  default
    Pod:
  Volumes:
    Data Volume:
      Name:  sysdv-name10
    Name:    sysdvdisk
    Data Volume:
      Name:  datadv-name10
    Name:    datadvdisk
    Cloud Init No Cloud:
      userDataBase64:  I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogY2VudG9zCmNocGFzc3dkOiB7IGV4cGlyZTogRmFsc2UgfQpzc2hfcHdhdXRoOiBGYWxzZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWK0MyTDVjQ3pqN0ZuREJGNVJjaHZrU3pFVlhMVjVNampMejRPRzhNSjhTcTl0VUdoZGMzKzdDYUgzcXZnV2lZVko1SkFQdE9jcVNGNzEzZzd6aWp1SGg5dGxvclpkVXdLeEJFY2I2N1l0aXUyUHhUcE5CZWs2bEdybzhGLzh0SFl2bk9YQnRQTVNqUEhiemx5R3hrTDdrNng5RnArZkpPZkVpTzhweXJISmVOa01aNy81UEViaCtRenN6c2VkbjdnUkNJM0htZ0Z5KzI1M1VpdnZNbTdwNE1uZTVxQVpwemNHZnpBYWhPUks3akZnWDkvQVk4NnZPWjFFeStuVEFhVjhnZWt2bldtMjFLU0htYUdYOExTK3hhODgxM3NmVklLcSsxeEN6L0h6UjRpeUZXejBIWmZHMmFUSFRySmVrbHovbG9BRzIreXFabGdlMG4xenFYSCBjZW50b3NAZ2gtY2xvdWQtdGVzdC10ZXN0MDIubXQKCmJvb3RjbWQ6CiAgLSBwYXJ0ZWQgLXMgL2Rldi92ZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAtcyAtYSBvcHRpbWFsIC9kZXYvdmRiIC0tIHVuaXQgcyBta3BhcnQgcHJpbWFyeSBleHQ0IDAlIDEwMCUKICAtIG1rZnMgLXQgZXh0NCAvZGV2L3ZkYjEKCm1vdW50czoKICAtIFsgL2Rldi92ZGIxLCAvb3B0LCAiZXh0NCIsICJkZWZhdWx0cyxub2ZhaWwiLCAiMCIsICIwIiBdCg==
    Name:              cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  Provisioning
  Guest OS Info:
  Phase:  Pending
Events:
  Type    Reason            Age                From                       Message
  ----    ------            ----               ----                       -------
  Normal  SuccessfulCreate  18m                virtualmachine-controller  Created virtual machine pod virt-launcher-vm-c7-datavolume-name10-vzg98
  Normal  SuccessfulDelete  18m (x2 over 18m)  virtualmachine-controller  Deleted temporary pod virt-launcher-vm-c7-datavolume-name10-vzg98
```

**What you expected to happen**:
All 9 VMs should be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
Create more than 9 VMs at a time.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.37.0
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-c7-datavolume-name10
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: sysdv-name10
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: docker://registry.sk.com/custom_dev/com.sankuai.hulknode.kubelet.union/kubevirt-base-centos7:latest
          secretRef: endpoint-secret
  - metadata:
      creationTimestamp: null
      name: datadv-name10
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: hostpath-provisioner
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-c7-datavolume-name10
    spec:
      domain:
        devices:
          disks:
            - name: sysdvdisk
              disk:
                bus: virtio
            - name: datadvdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 512M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: sysdvdisk
          dataVolume:
            name: sysdv-name10
        - name: datadvdisk
          dataVolume:
            name: datadv-name10
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogY2VudG9zCmNocGFzc3dkOiB7IGV4cGlyZTogRmFsc2UgfQpzc2hfcHdhdXRoOiBGYWxzZQpzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWK0MyTDVjQ3pqN0ZuREJGNVJjaHZrU3pFVlhMVjVNampMejRPRzhNSjhTcTl0VUdoZGMzKzdDYUgzcXZnV2lZVko1SkFQdE9jcVNGNzEzZzd6aWp1SGg5dGxvclpkVXdLeEJFY2I2N1l0aXUyUHhUcE5CZWs2bEdybzhGLzh0SFl2bk9YQnRQTVNqUEhiemx5R3hrTDdrNng5RnArZkpPZkVpTzhweXJISmVOa01aNy81UEViaCtRenN6c2VkbjdnUkNJM0htZ0Z5KzI1M1VpdnZNbTdwNE1uZTVxQVpwemNHZnpBYWhPUks3akZnWDkvQVk4NnZPWjFFeStuVEFhVjhnZWt2bldtMjFLU0htYUdYOExTK3hhODgxM3NmVklLcSsxeEN6L0h6UjRpeUZXejBIWmZHMmFUSFRySmVrbHovbG9BRzIreXFabGdlMG4xenFYSCBjZW50b3NAZ2gtY2xvdWQtdGVzdC10ZXN0MDIubXQKCmJvb3RjbWQ6CiAgLSBwYXJ0ZWQgLXMgL2Rldi92ZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAtcyAtYSBvcHRpbWFsIC9kZXYvdmRiIC0tIHVuaXQgcyBta3BhcnQgcHJpbWFyeSBleHQ0IDAlIDEwMCUKICAtIG1rZnMgLXQgZXh0NCAvZGV2L3ZkYjEKCm1vdW50czoKICAtIFsgL2Rldi92ZGIxLCAvb3B0LCAiZXh0NCIsICJkZWZhdWx0cyxub2ZhaWwiLCAiMCIsICIwIiBdCg==
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
