### ISSUE TITLE
launcher pod on the target node is not cleaned up after a migration is canceled

### ISSUE THREAD

**Issue by gitlawr** [kubevirt/kubevirt#5373]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The launcher pod on target node stays running for ~5min then turns into error status.
```
kubectl get po -w -owide
NAME                    READY   STATUS    RESTARTS   AGE     IP           NODE   NOMINATED NODE   READINESS GATES
virt-launcher-t-2dlpg   1/1     Running   0          24m     10.52.1.36   n3     <none>           <none>
virt-launcher-t-n4kxm   1/1     Running   0          4m46s   10.52.2.38   n2     <none>           <none>
virt-launcher-t-n4kxm   0/1     Error     0          5m20s   10.52.2.38   n2     <none>           <none>
```

**What you expected to happen**:
Clean up the target pod when migration is canceled

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a VM.
2. create a VMIM, then remove it.
```
kubectl apply -f migration.yaml && sleep 2 && kubectl delete -f migration.yaml
```
3. check pod status

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.36.0", GitCommit:"398cd404dba9ced6c298824a1bf681d387dd3a1c", GitTreeState:"clean", BuildDate:"2020-12-16T15:01:21Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v0.38.1-dirty", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"dirty", BuildDate:"2021-02-08T20:30:01Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: t
  namespace: default
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: t-disk-0-reyc2
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-image-x6fp2
        volumeMode: Block
      source:
        blank: {}
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk-0
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: t
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: t-disk-0-reyc2
        name: disk-0
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: 123456
            chpasswd:
              expire: false
        name: cloudinitdisk
```
- VMIM specification
```
# migration.yaml

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceMigration
metadata:
  name: test
spec:
  vmiName: t
```
