### ISSUE TITLE
Alert "VirtAPIDown" doesn't work

### ISSUE THREAD

**Issue by erkanerol** [kubevirt/kubevirt#5383]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
VirtAPIDown alert doesn't work. The reason is here:

```
kubectl -n kubevirt get prometheusrule prometheus-kubevirt-rules -o yaml
```
Output:
```
...
    rules:
    - expr: sum(up{namespace='kubevirt', pod=~'virt-api-.*'})
      record: num_of_running_virt_api_servers
    - alert: VirtAPIDown
      annotations:
        summary: All virt-api servers are down.
      expr: num_of_running_virt_api_servers == 0
      for: 5m
...
```

The query has the namespace label. However, the namespace is dropped from metrics because of the conf below.

```
kubectl get servicemonitor prometheus-kubevirt-rules -n openshift-monitoring -o yaml
```
Output:
```
    relabelings:
    - action: labeldrop
      regex: namespace
    scheme: https
```

Therefore, the metrics don't have namespace labels, and the query return empty. The other problem is here that the expr checks whether the result is zero or not. When the result is empty, it is false and the alert is not triggered. 

**Environment**:
- KubeVirt version (use `virtctl version`):
0.39.0
