### ISSUE TITLE
unknown field "nodeSelector" in io.kubevirt.v1alpha3.VirtualMachine.spec

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt#5420]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
Tried creating VM using Node Selector got an error below however I was able to successfully create VM using validation off but why this occoured.
error validating "node-selector.yaml": error validating data: ValidationError(VirtualMachine.spec): unknown field "nodeSelector" in io.kubevirt.v1alpha3.VirtualMachine.spec;

node-selector.yaml
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm-node-selector
spec:
  nodeSelector:
    cpu: slow
    storage: fast
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm-node-selector
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**: It should not return an error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v0.39.0", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"clean", BuildDate:"2021-03-10T15:29:59Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.39.0-dirty", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"dirty", BuildDate:"2021-03-10T15:56:17Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xpivarc** [comment]
Hi,
It should be 
```
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm-node-selector
    spec:
     nodeSelector:
      cpu: slow
      storage: fast
```
