### ISSUE TITLE
virt-launcher-xxx pod cannot be deleted, keeping terminating after deleting vmi

### ISSUE THREAD

**Issue by actor168** [kubevirt/kubevirt#5446]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
when `virtctl stop centos1`, it shows
```bash
NAME                          READY   STATUS        RESTARTS   AGE
virt-launcher-centos1-qd9dr   0/2     Terminating   0          15h
```
**What you expected to happen**:
should stop gracefully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
kubelet log shows:
```
Pod "virt-launcher-centos1-qd9dr(fcf92054-d335-4dac-a90c-c90794702bb5)" is terminated, but some volumes have not been cleaned up
pod "fcf92054-d335-4dac-a90c-c90794702bb5" found, but volumes not yet removed.  Reducing cpu to minimum

[nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/empty-dir/fcf92054-d335-4dac-a90c-c90794702bb5-container-disks podName:fcf92054-d335-4dac-a90c-c90794702bb5 nodeName:}" failed. No retries permitted until 2021-04-13 11:44:19.192875261 +0800 CST m=+1119.367966383 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown faileT m=+1119.367966383 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"container-disks\" (UniqueName: \"kubernetes.io/empty-dir/fcf92054-d335-4dac-a90c-c90794702bb5-container-disks\") pod \"fcf92054-d335-4dac-a90c-c90794702b unlinkat /vdata/kubelet/pods/fcf92054-d335-4dac-a90c-c90794702bb5/volumes/kubernetes.io~empty-dir/container-disks volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: device or resource busy"
```
/proc/mounts
```
overlay /vdata/kubelet/pods/fcf92054-d335-4dac-a90c-c90794702bb5/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img overlay rw,relatime,lowerdir=/vdata/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/300/fs,upperdir=/vdata/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/303/fs,workdir=/vdata/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/303/work 0 0
```
**Environment**:
- KubeVirt version (use `virtctl version`): v0.36.0
- Kubernetes version (use `kubectl version`): community v1.19.9 
- VM or VMI specifications: 
```yaml
  spec:
    runStrategy: Manual
    template:
      metadata:
        annotations:
        creationTimestamp: null
        name: centos2
      spec:
        accessCredentials:
        - userPassword:
            propagationMethod:
              qemuGuestAgent: {}
            source:
              secret:
                secretName: xxxx
        domain:
          cpu:
            cores: 1
            sockets: 1
          devices:
            disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: hostdisk
            - disk:
                bus: virtio
              name: cloudinit
            - disk:
                bus: virtio
              name: serviceaccount
            interfaces:
            - bridge: {}
              model: virtio
              name: default
          machine:
            type: q35
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
        networks:
        - name: default
          pod: {}
        volumes:
        - containerDisk:
            image: xxx/kubevirt/centos7-5-1809-registry-disk:v0.0.1
          name: hostdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: True
              chpasswd: { expire: false }
          name: cloudinit
        - name: serviceaccount
          serviceAccount:
            serviceAccountName: default
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): centos7.6
- Kernel (e.g. `uname -a`): 4.19.112
- Install tools: kubeadm, kubevirt-opeartor
- Others:
- container engine: **_containerd_**
```toml
  [plugins.cri.containerd]
    snapshotter = "overlayfs"
    no_pivot = false
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"
        privileged_without_host_devices = false
        [plugins.cri.containerd.runtimes.runc.options]
          NoPivotRoot = false
          NoNewKeyring = false
          ShimCgroup = ""
          IoUid = 0
          IoGid = 0
          BinaryName = "runc"
          Root = ""
          CriuPath = ""
          SystemdCgroup = false
```
