### ISSUE TITLE
should report error when VMI:cores is <=0

### ISSUE THREAD

**Issue by jichenjc** [kubevirt/kubevirt#5450]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

should report error when VMI cores is <=0 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-ephemeral
  name: vmi-ephemeral
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    machine:
      type: ""
    cpu:
      cores: 0

```

succeed in create teh VMI

**What you expected to happen**:

should report error and block VMI creation

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
