### ISSUE TITLE
VMI has second network/IP but no connectivity

### ISSUE THREAD

**Issue by teo-tsou** [kubevirt/kubevirt#5483]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

I created a VMI with a secondary multus macvlan network interface on it. It seems that the attachment was successful as I can see the eth1 interface and the IP address correctly assigned, but I cannot access no one from the eth1.

More specifically I want to communicate with the other pods that have also a secondary macvlan interface (e.g POD interface:  net1: 172.16.0.5) which is connected to the same subnet with the VM's secondary interface (e.g VMI interface:  eth1: 172.16.0.6) . But when I ping from the VMI : ping -I eth1 172.16.0.5 , I am getting host unreachable. The  POD to POD communication is successful. But the  POD to VMI **or** VMI to VMI  communication via the multus interface is unsuccessful. 

**What you expected to happen**:
 Successful POD to VMI **or** VMI to VMI  communication via the multus interface.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.38.1
- Kubernetes version (use `kubectl version`): v1.20.0
- VM or VMI specifications:

- OS (e.g. from /etc/os-release): NAME=Fedora
VERSION="32 (Cloud Edition)"

**The macvlan conf file:**
```

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: mec
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth1", "ipam": { "type": "static", "addresses": [ { "address": "172.16.0.6/24",
    "gateway": "172.16.0.1" } ] } }'
```

**The VMI conf file:**

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-multus-multiple-net
  name: vmi-multus-multiple-net
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: default
      - bridge: {}
        name: mec
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: mec
    name: mec
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        dhclient eth1
    name: cloudinitdisk
```
