### ISSUE TITLE
Migration status is not reported in VMI.status

### ISSUE THREAD

**Issue by gitlawr** [kubevirt/kubevirt#5503]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
VMIM resource is in failed phase, but migration state in VMI.status is empty.

**What you expected to happen**:
From [kubevirt docs](https://kubevirt.io/user-guide/operations/live_migration/#migration-status):
>The migration progress status is being reported in the VMI VMI.status. Most importantly, it indicates whether the migration has been Completed or if it Failed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VM
2. Create a VMIM to migrate the VM.
3. Delete the new launcher pod when it is in ContainerCreating status.

**Anything else we need to know?**:
VMIM yaml:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceMigration
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: test-5nrcb
  namespace: default
spec:
  vmiName: test
status:
  phase: Failed
```

VMI yaml:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  finalizers:
  - foregroundDeleteVirtualMachine
  - wrangler.cattle.io/VMIController.UnsetOwnerOfDataVolumes
  labels:
    kubevirt.io/nodeName: n2
  name: test
  namespace: default
spec:
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk-0
      interfaces:
      - masquerade: {}
        model: virtio
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: feec480d-31a1-59fa-9199-a330c83aa404
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
  evictionStrategy: LiveMigrate
  hostname: test
  networks:
  - name: default
    pod: {}
  volumes:
  - dataVolume:
      name: test-disk-0-h2amw
    name: disk-0
status:
  activePods:
    8fc51e4f-1ec4-4de7-8402-aeb28a116957: n2
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-21T07:55:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  guestOSInfo: {}
  interfaces:
  - ipAddress: 10.52.2.17
    ipAddresses:
    - 10.52.2.17
    mac: 52:54:00:b9:d6:0e
    name: default
  migrationMethod: LiveMigration
  nodeName: n2
  phase: Running
  qosClass: Burstable
  volumeStatus:
  - name: disk-0
    target: vda
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.38.1
- Kubernetes version (use `kubectl version`): v1.20.4+k3s1
- Others: Running in [Harvester](https://github.com/harvester/harvester) v0.2.0-rc3
