### ISSUE TITLE
Create stateless subresources api endpoint and remove haproxy

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#553]
Create an aggregated api server for the Console/Spice virtual machine subresources and remove haproxy entirely.

The Console/Spice subresources are stateless. This means we can adopt an aggregated API server for those subresources and continue to use CRDs for persistence of our cluster objects.

The api server spec should look something like this.
```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.subresources.kubevirt.io
spec:
  insecureSkipTLSVerify: true
  group: subresources.kubevirt.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: virt-apiserver-service
    namespace: default
  version: v1alpha1
```

This is an intermediate step that lets us remove haproxy while we continue to sort through how persistence should be handled. Once we get the persistence issue sorted out, we'll simply drop the "subresources" part of the group subresources.kubevirt.io and handle all the objects CRUD like operations.
