### ISSUE TITLE
Able to post VM with cloudinit without disk for cloudinit

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#5556]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When I post the following yaml, I expect it to get rejected because there is no disk for the cloud init
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: fedora
  name: fedora-1619580640-1816523
spec:
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-1619580640-1816523
        kubevirt.io/domain: fedora-1619580640-1816523
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        machine:
          type: ''
        resources:
          requests:
            memory: 1024Mi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - containerDisk:
          image: quay.io/openshift-cnv/qe-cnv-tests-fedora:33
        name: containerdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }      
  running: true
```
**What you expected to happen**:
The validation to reject the yaml as it is invalid.
**How to reproduce it (as minimally and precisely as possible)**:
Apply the specified yaml

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.40
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
