### ISSUE TITLE
resource limits cpu/memory on resources created by kind: KubeVirt

### ISSUE THREAD

**Issue by strowi** [kubevirt/kubevirt#5617]
**Is this a BUG REPORT or FEATURE REQUEST?**:
kind enhancement

**What happened**: 
No resource limits on resources created by `kind: KubeVirt`( virt-api/controller/handler ).
We have a policy that requires limits on *every* Pod.

**What you expected to happen**:
Being able to set resource limits on the CRD-created Deployments/Pods.

**How to reproduce it (as minimally and precisely as possible)**:
Run the Quckstart - https://kubevirt.io/quickstart_cloud/
- VM or VMI specifications: 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.40.0
- Kubernetes version (use `kubectl version`): v1.20.5

regards,
strowi

**Comment by phoracek** [comment]
@davidvossel does this sounds like a reasonable RFE?

**Comment by davidvossel** [comment]
> We have a policy that requires limits on every Pod.

@strowi You can accomplish this today.

I'll start with the bottom up.

The workload pods that the virtualmachines run in are influenced by the VMI spec, there you can set cpu/mem request/limits which ultimately get transfered to the VMI pod.

For our control plane components, those are all influenced by the KubeVirt CR definition. There is a field called `customizeComponents` where you can add patches to every control plane component. Below is an example I pulled from the pr that introduced this change, https://github.com/kubevirt/kubevirt/pull/3612. With this functionality, you can add request/limits using patches to all deployements/daemonsets. 

```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration: {}
  customizeComponents: 
    patches:
    - resourceType: Deployment
      resourceName: virt-controller
      patch: '[{"op": "remove", "path": "/spec/template/spec/containers/0/livenessProbe"}]'
      type: json
    - resourceType: Deployment
      resourecName: virt-controller
      patch: '{"metadata":{"annotations":{"patch": "true"}}}'
      type: strategic
  imagePullPolicy: IfNotPresent
```


And lastly, the virt-operator deployment. You have direct control  over this manifest when you post it to the cluster, simply add your request/limits there within the manifest before posting.

All of that should result in running KubeVirt + all KubeVirt related workloads with requests/limits
