### ISSUE TITLE
upgrade to v0.41.0, virt-launcher can't forword network traffic to VM.

### ISSUE THREAD

**Issue by chenyg0911** [kubevirt/kubevirt#5680]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
upgrade from v0.34 to 0.41, vm instance can't  access directly.
I'm using calico cni with setting:
```
      "container_settings": {
        "allow_ip_forwarding": true
      },
```
with set router bgp, all inter user can access VM with the podip like a usual host.

ALL work fine in kubevirt v0.34.0.
I can ssh user@podip as a normal machine.

After upgrade to v0.41.0, it not work now.
I try to rollback to v0.34, but it seems just rollback the operator docker image to v0.34.

I describe the pods which started before upgrade 
compare the docker image, the pod use quay.io/kubevirt/virt-launcher:v0.41.0 can't forword traffic to vm and virt-launcher:v0.34.0 (index.docker.io/kubevirt/virt-launcher@sha256:cadfb07ba28197a656fdad4fd9c44b238172cdc02631094ca7e958d003ae6efe)  working fine.

it seems new virt-launcher change some setting.

**What you expected to happen**:
new kubevirt launcher can support forword trafic to VM.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.30.7
- Kubernetes version (use `kubectl version`): v1.20.2
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
For the rollback, please stick to the 0.41 operator. The version change should be defined in the `KubeVirt` CR:

```json
kubectl patch kv kubevirt -n kubevirt --type=json -p '[{ "op": "add", "path": "/spec/imageTag", "value": "v0.34.0" }]'
```

For the Calico issue, we are running Calico on our CI, so it is surprising to see it fail. Could you describe what kind of connectivity does not work and what does? Are you able to ping the VM from another pod/VM? Are you able to get to the outside network from the VM?

**Comment by chenyg0911** [comment]
Yes, I can ping the pod but I can't ping to VM, it seems pod can't forword traffic to vm as expect.

**Comment by chenyg0911** [comment]
On kubevirt cluster I have 2 type vm pods. Some vm is create before upgrade, and some in create after that. The pods which created before still running normally but the new pods (create after) can't ssh or ping to vm. I check the pod between them. The olny differents is the virt-launcher:
After upgrade:
```
Controlled By:  VirtualMachineInstance/ubuntu-fixip
Init Containers:
  container-disk-binary:
    Container ID:  docker://7a90ce2a9786c10f07eadb8162ec5fec8264ad1818eaf25424c8228532788fe2
    Image:         quay.io/kubevirt/virt-launcher:v0.41.0
    Image ID:      docker-pullable://quay.io/kubevirt/virt-launcher@sha256:4e67b203f05e9ed593a6952956d123
```
Before upgrade:
```
Controlled By:  VirtualMachineInstance/ubuntu-xiedi
Init Containers:
  container-disk-binary:
    Container ID:  docker://5195173e41405b2c29e53e62a37f666ffb2ac56e6806490d43de9944ec69a3c6
    Image:         index.docker.io/kubevirt/virt-launcher@sha256:cadfb07ba28197a656fdad4fd9c44b238172cdc02631094ca7e958d003ae6efe
```

Another question is : How can I roll back the virt-launcher to 0.34? I've rollbacked the operate version, but it still launch new vm-pod with v0.41.

**Comment by qinqon** [comment]
@chenyg0911  can you share the VM/VMI yaml ?

**Comment by chenyg0911** [comment]
@qinqon FYI.
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu-fixip
spec:
  running: false
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.233.93.55\"]"
      labels: 
        kubevirt.io/size: small
        kubevirt.io/domain: ubuntu-fixip
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            # bridge: {}
        resources:
          requests:
            memory: 8G 
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containervolume
          containerDisk:
            image: chenu2/ubuntu-focal-container-disk-40g:20.04
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: yes
              chpasswd:
                list: |
                  ubuntu:ubuntu
                expire: False

```

**Comment by chenyg0911** [comment]
@qinqon FYI.
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu-fixip
spec:
  running: false
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.233.93.55\"]"
      labels: 
        kubevirt.io/size: small
        kubevirt.io/domain: ubuntu-fixip
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            # bridge: {}
        resources:
          requests:
            memory: 8G 
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containervolume
          containerDisk:
            image: chenu2/ubuntu-focal-container-disk-40g:20.04
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: yes
              chpasswd:
                list: |
                  ubuntu:ubuntu
                expire: False

```
