### ISSUE TITLE
The vm memory is not the same as specified in the yaml

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5730]
**What happened**:

Create a VM with 4096M memory specified in the yaml，but the actual VM memory is only 3907M， I am not clearly on the logic why this happen, could you help me ?

qemu process:
`
107       34531  1.6  2.4 9245072 3168728 ?     Sl   May26  30:00 /usr/libexec/qemu-kvm -name guest=default_vm-with-testwin7-01,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-default_vm-with-test/master-key.aes -machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off -cpu IvyBridge,ss=on,pcid=on,hypervisor=on,arat=on,tsc-adjust=on,umip=on,xsaveopt=on,pdpe1gb=on,hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff -m 3907 -overcommit mem-lock=off -smp 4,sockets=1,dies=1,cores=4,threads=1 -object iothread,id=iothread1 -uuid 5d307ca9-b3ef-428c-8861-06e72d69f226 -smbios type=1,manufacturer=KubeVirt,product=None,uuid=5d307ca9-b3ef-428c-8861-06e72d69f226,family=KubeVirt -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=18,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device qemu-xhci,id=usb,bus=pci.0,addr=0x4 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x5 -device ahci,id=sata0,bus=pci.0,addr=0x7 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -blockdev {"driver":"file","filename":"/var/run/kubevirt/container-disks/disk_0.img","node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-3-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-3-storage","backing":null} -blockdev {"driver":"file","filename":"/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-2-storage","backing":"libvirt-3-format"} -device virtio-blk-pci,bus=pci.0,addr=0x8,drive=libvirt-2-format,id=ua-containerdisk,bootindex=1,write-cache=on -blockdev {"driver":"file","filename":"/var/run/libvirt/empty-disks/harddisk.qcow2","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":null} -device ide-hd,bus=sata0.0,drive=libvirt-1-format,id=ua-harddisk,write-cache=on -netdev tap,fd=20,id=hostua-default -device e1000,netdev=hostua-default,id=ua-default,mac=02:00:00:4f:f7:8b,bus=pci.0,addr=0x3,romfile= -chardev socket,id=charserial0,fd=21,server,nowait -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,fd=22,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -device usb-tablet,id=ua-tablet1,bus=usb.0,port=1 -vnc vnc=unix:/var/run/kubevirt-private/8b668006-fdea-4386-acf5-90e8b4b521cd/virt-vnc -device VGA,id=video0,vgamem_mb=16,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x9 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
`

VM yaml:

```yaml
--
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "vm-with-testwin7-02"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: "vm-with-testwin7-02"
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 4
        devices:
          inputs:
            - type: tablet
              bus: usb
              name: tablet1
          disks:
            - name: containerdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: harddisk
              disk: {}
          interfaces:
          - name: default
            masquerade: {}
            model: e1000
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f226
        resources:
          requests:
            memory: 4096M
        machine:
          type: pc
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: testwin7
        - name: harddisk
          emptyDisk:
            capacity: 80Gi
```

**Environment**:
- KubeVirt version (use `virtctl version`): 0.37
- Kubernetes version (use `kubectl version`): 1.16

**Comment by vladikr** [comment]
I see that you have requested `4096M` (megabyte 1000) which translates to `3906.25 Mib` (mebibytes)
you just need to request `4096Mi` instead

**Comment by yangxiaoliang** [comment]
> I see that you have requested `4096M` (megabyte 1000) which translates to `3906.25 Mib` (mebibytes)
> you just need to request `4096Mi` instead

Thank you @vladikr , request 4096Mi works as expect.

I have another question, from the output of `kubectl describe virt-launcher-xxx`, I noticed that the requested memory of virt-launcher pod is larger than 4096Mi, so  it means if I create a VM with 4096Mi memory requested, the target host would consumes more than 4096Mi memory, as the virt-launcher pod would consumes some additional memory, right ?

```yaml

$ kubectl describe pods virt-launcher-vm-with-testwin7-03-9grxw
Name:         virt-launcher-vm-with-testwin7-03-9grxw
Namespace:    default
...
Controlled By:  VirtualMachineInstance/vm-with-testwin7-03
Init Containers:
  container-disk-binary:
    Container ID:  docker://d0e61655dc153b5528d6795dc212a856604af22616912564bfc8a8cc4527986a
    ...
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M    <----
    ...
  volumecontainerdisk-init:
    Container ID:  docker://8cc627515f1a5e2c5f3f0344cc966370f67685c510e17e2bb29f092b9c757a28
    ...
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M  <----
    ...
Containers:
  compute:
    Container ID:  docker://22906dc562afa646fe92eb9438590c6c3ddcdafd0697bf50a7a1e6c431497741
    ...
    Limits:
      devices.kubevirt.io/kvm:  1
      devices.kubevirt.io/tun:  1
    Requests:
      cpu:                      100m
      devices.kubevirt.io/kvm:  1
      devices.kubevirt.io/tun:  1
      memory:                   4506779649    <--- larger than 4096Mi
    ...
  volumecontainerdisk:
    Container ID:  docker://c7d2796f8019863aa33a84b3a895d252288f9f79b5bf2b77b5d15095896ff240
    ...
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M  <---
    ...
```
