### ISSUE TITLE
[KEP] Improve the reconciliation in virt-controller for VMI status update

### ISSUE THREAD

**Issue by fanzhangio** [kubevirt/kubevirt#5733]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
For creating a huge number of VMIs, we noticed that there is always a systematical latency happens between pod being running and vmi status being updated. 

<img width="903" alt="Systematical latency between Pod and VMI" src="https://user-images.githubusercontent.com/22812247/119843132-1af00a00-bebc-11eb-8d2b-e7d5d1d09dc9.png">

As investigated into this latency, some factors are impacting the latency
1. Every event is enqueued into workqueue, which causes :
   - workqueue length increases too fast
   - Increasing worker threads number does not mitigate queue length as events are processed and queued even fasters
   - Many operations not relating to VMI status phase update are also enqueued to workqueue, which delays the overall processing time 
   
2. virt-controller creates launcher Pod by sync(). Creation/Deletion operation is the one-off effort to "rolling the ball", but as the keys are queued at the end, so it has to wait a while for an available thread worker to consume. In practice, it could take over 3 min (500 VMS) and the waiting time grows linear as the queue grows. 

3. virt-controller updates VMI status phases by updateStatus(), it makes a move to next phase of VMI based on the switches of "current" VMI status phases. The phase update workflow is like:  
`
Unset -> Pending -> Scheduling -> Scheduled -> Running -> Failed
`
Phases can jump to Failed if deletion or failure condition happens.
However, in practice, Pod scheduling and being running is much faster than VMI status being processed by updateStatus(). As we can see it is normally no more than 20 sec to have launcher pod being in Running status (all container are running too),  but it would wait for a couple of minutes for available thread workers to pull the vmi key off the queue and move step by step for many rounds. 

e.g. 

At T0 sec, VMI is created and VMI status is "Unset", enqueue. Wait T1 (queue time) for a worker thread to consume off the queue, it starts creating Pod and also enqueue. Creation of Pod takes PCT (Pod Creation Time) sec. Before next available worker thread to consume this "create pod event" from workqueue, the VMI status is still Unset whatever Pod is Running or not. Let's say Pod is running (as PCT is very small), next worker polled the key off the workqueue and run sync() -> updateStatuts() will find that current VMI object has a Pod exist. Here the problem happens, virt-controller updates the VMI to Scheduling and enqueue again for next available worker to handle. There will be another latency T3 sec (waiting in queue). But actually, the VMI can be directly updated to Running as all criteria are met. 

**What you expected to happen**:
The Pod Running time and VMI Running time should be very close. virt-controller should update VMI status phase almost take the same pace of Pod status update

**How to reproduce it (as minimally and precisely as possible)**:
Burst creation of 500vms or more at one time. Profile the metrics of vmi creaion rate by time and pod creation by time.

**Anything else we need to know?**:
The goal of thie KEP is for achiving a better effective performance.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.35
- Kubernetes version (use `kubectl version`): 1.19
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvm
  namespace: default
spec:
  nodeSelector:
    ngn2.nvidia.com/hosttype: GS
  domain:
    devices:
      disks:
        - name: rootdisk
          disk:
            bus: virtio
      interfaces:
        - bridge: {}
          name: default
    resources:
      requests:
        cpu: 100m
        memory: 100M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: rootdisk
      persistentVolumeClaim:
        claimName: testpvc
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
