### ISSUE TITLE
ping virt-launcher pod(VM) IP failed with pod network and bridge type

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/kubevirt#5735]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Use default pod network and bridge type, I can not connect to virt-launcher pod IP. 

The pod:
virt-launcher-vm-cirros-zfl56              1/1     Running            0          174m   192.168.5.158   10.2.0.139   <none>           <none>

Ping 192.168.5.158 failed.

The net links in pod:  pod original interface eth0 state is DOWN, bridge k6t-eth0 connects eth0-nic and tap0, I think it is correct.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: eth0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN
    link/ether fa:bd:80:ef:7c:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.158/32 brd 192.168.5.158 scope global eth0
       valid_lft forever preferred_lft forever
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 5a:96:49:2c:80:22 brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.1/16 brd 169.254.255.255 scope global k6t-eth0
       valid_lft forever preferred_lft forever
5: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master k6t-eth0 state UP qlen 1000
    link/ether aa:6e:86:f4:73:8e brd ff:ff:ff:ff:ff:ff
11536: eth0-nic@if11537: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master k6t-eth0 state UP
    link/ether 5a:96:49:2c:80:22 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

The VM net links: It got the pod's original IP and default gateway is 169.254.1.1, but no MAC address for 169.254.1.1. When I ping the VM IP (also the virt-launcher pod IP) and execute tcpdump on k6t-eth0 bridge in the virt-launcher pod, I catch the ARP request from VM 'ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 169.254.1.1 tell 192.168.5.158'.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast qlen 1000
    link/ether 5a:96:49:97:d9:52 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.158/32 brd 192.168.5.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5896:49ff:fe97:d952/64 scope link
       valid_lft forever preferred_lft forever
```
```
$ ip route
default via 169.254.1.1 dev eth0
169.254.1.1 dev eth0
$ arp -n
? (169.254.1.1) at <incomplete>  on eth0
```

Finally, I add an ARP record in the VM, it works：
```
 arp -s 169.254.1.1 82:94:d5:57:56:ae
```
The MAC of 169.254.1.1 is the veth pair of the pod virt-launcher on the host.

**What you expected to happen**:

ping virt-launcher pod IP (VM IP) ok

**How to reproduce it (as minimally and precisely as possible)**:
VirtualMachine defination
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            cpu: "1"
            memory: 1024Mi
      volumes:
      - dataVolume:
          name: cirros-dv
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: cirros-dv
    spec:
      pvc:
        storageClassName: localpv
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        registry:
          url: docker://xxx/kubevirt/cirros-container-disk-demo:latest
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.40.0-rc.2
- Kubernetes version (use `kubectl version`): v1.16.6
- VM or VMI specifications:  use cirros-container-disk-demo image and 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
