### ISSUE TITLE
Support runtimeClassName in VirtualMachine template spec

### ISSUE THREAD

**Issue by mazocode** [kubevirt/kubevirt#5744]
/kind enhancement

The template spec of the VirtualMachine CRs  does not allow specifying **runtimeClassName**. This should be supported for the following szenarios:

a) The nodes default runtime is not useful for running kubevirt workloads (i.e. kata) 

b) Improves UX:  by simplifying tolerations and node selection, which can be done at a central place (RuntimeClass), ie:

`runtimeClassName: gpu-workload`

vs

```
  nodeSelector:
    kubernetes.io/role: virtualization
    foo: bar
  tolerations:
     - effect: NoSchedule
        key: gpu-node
        operator: Equal
        value: true
  ...
```

**Comment by mlsorensen** [comment]
Following up on our other conversation on #5754:

I do wonder how an end user is expected to know which runtimeClasses work with Kubevirt VMs - perhaps the runtime class is labeled so the users can see this if they 'kubectl get runtimeclasses', or maybe KubeVirt itself looks at the runtime classes and validates the selected one is labeled somehow to support in-pod virtualization. Maybe that is too prescriptive.

As far as tolerations, nodeSelector. I wonder how these would be presented in Kubevirt configuration cleanly such that users are only selecting runtimeClassName and KubeVirt knows what arbitrary tolerations the admin expects. I think the runtime class resource itself has functionality to apply tolerations and nodeSelectors automatically to pods that choose a given runtimeClassName via the "scheduling" flag. In the event that nodes with a given runtime class are subdivided and additional tolerations or node selectors are required to target a specific subset, I'm not sure how that would work or if that's the intended use case for having KubeVirt associate a runtimeClassName with specific tolerations.

**Comment by mazocode** [comment]
Good points! I guess as a user I would like to specify three things: OS, capacity and hardware features needed. As an admin, I can already provide the user with the parameters required for the OS via the VMI presets.  Would it make sense also being able to predefine nodes according to their hardware features? 

For example something like:
```
kind: VirtualMachineNodeSet
metadata:
  name: ai-workload
spec:
  runtimeContextName: runc
  # additional to whatever the runtimeClassName provided:
  tolerations:
  nodeSelector:
```

VMI could then look like this:
```
metadata:
  labels:
    kubevirt.io/flavor: rhel8.3
    kubevirt.io/nodeset: ai-workload
```

The kubevirt CR could reference a default nodeset in case the user did not select any.
