### ISSUE TITLE
Support admin-configured custom runtimeClassName on virt-launcher pods

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#5754]
/kind enhancement

Support configuring the runtimeClassName for the virt-launcher pod, for situations where clusters offer multiple runtime classes. We can use the KubeVirt CR for admins to control this runtime selection.

Can follow the same pattern used for things like SELinuxLauncherType

https://github.com/kubevirt/kubevirt/blob/31ca00e3acce0e2431e6403c50e9be8c23b073a2/staging/src/kubevirt.io/client-go/api/v1/types.go#L1765
https://github.com/kubevirt/kubevirt/blob/31ca00e3acce0e2431e6403c50e9be8c23b073a2/pkg/virt-controller/services/template.go#L1287

**Comment by mazocode** [comment]
@mlsorensen I think you can use customizeComponents for this:
```
  customizeComponents:
    patches:
    - resourceType: Daemonset
      resourceName: virt-handler
      patch: '[{"path": "/spec/template/spec/runtimeClassName", "op": "add", "value": "runc" }]'
      type: json
```
