### ISSUE TITLE
windows vm can be launched on v0.37.0, but can not be launched on v0.38.1/v0.39.1/v0.40.0

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5768]
> /kind bug

**What happened**:
VM with Windows7 can be launched successfully and works fine on v0.37.0. But using the same yaml, exec `kubectl create testwin7.yaml`, it can not be launched and started successful on kubevirt v0.38.1/v0.39.1/v0.40.0.

**What you expected to happen**:
VM with Windows7 can be launched successfully.

**How to reproduce it (as minimally and precisely as possible)**:
On kubevirt v0.38.1/v0.39.1/v0.40.0 , using following yaml to create vm.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.40.0

- Kubernetes version (use `kubectl version`): 1.16

- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-with-win7-containerdisk-03
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-with-win7-containerdisk-03
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 4
        devices:
          inputs:
          - type: tablet
            bus: usb
            name: tablet1
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            model: e1000
            masquerade: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        resources:
          requests:
            memory: 4096Mi
        machine:
          type: pc
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: testwin7
```

- Others:
On kubevirt v0.37.0, exec `kubectl create -f testwin7.yaml` , vm can be started, but on kubevirt v0.38.1/v0.39.1/v0.40.0, the vm can not be started.
