### ISSUE TITLE
Auto-provision of empty PVC results in disk.img virtual size too large to fit

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#5810]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I ran into a case where a VM would not start up. This surfaced at virt launcher as:
```
"preparing host-disks failed: stat /var/run/kubevirt-private/vmi-disks/pvcdisk2/disk.img: permission denied"
```
Looking into it further, it seems the runtime could not apply selinux labels:

```
failed to set file label ...: no space left on device
```

This disk image was created automatically by KubeVirt on an empty 1000Gi PVC using XFS:

```
PVC fs total: 1073217536000
 PVC fs used: 1073217515520 
PVC fs available as reported by 'df': 20480  

disk.img virtual: 1073183752192
 disk.img stopped at: 1073183731712 
 disk.img was short of max virtual by 20480 
```

Based on these numbers it seems that:
1) The 20k 'available' is not really available. Perhaps this is due to journaling or just the overhead required to be able to rewrite filesystem metadata
2) KubeVirt created the disk.img to match the 'available' exactly

**What you expected to happen**:

The disk.img should be able to grow to its max virtual size without becoming unusable, at least in this case where it was created automatically - we can't necessarily account for cases where users have over provisioned an image into a PVC that is smaller than a disk image they provide.

**How to reproduce it (as minimally and precisely as possible)**:

Create PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mls-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
```

Create VMI:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: fedora-pvc
spec:
  terminationGracePeriodSeconds: 0
  domain:
    cpu:
      cores: 2
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    devices:
      disks:
      - disk:
          bus: virtio
        name: containervolume
      - disk:
          bus: virtio
        name: cloudinitvolume
      - disk:
          bus: virtio
        name: pvc
  volumes:
  - name: containervolume
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo
  - name: pvc
    persistentVolumeClaim:
      claimName: mls-test
  - name: cloudinitvolume
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```

Log into VM, fill up PVC:
```
[fedora@fedora-pvc ~]$ sudo su -
[root@fedora-pvc ~]# dd if=/dev/zero of=/dev/vdc bs=1M
dd: error writing '/dev/vdc': No space left on device
client_loop: send disconnect: Broken pipe
```

Note VM becomes unresponsive once the disk fills up.

Looking at the node level, VM is paused:
```
% kubectl exec -it virt-launcher-fedora-pvc-h2x9q -- virsh list
Defaulting container name to compute.
 Id   Name                                 State
---------------------------------------------------
 1    test-ns_fedora-pvc   paused
 ```
 
 Looking at disk image, comparing 8344896 to 8345376 it never reached its full size:
 ```
[root@fedora-pvc /]# qemu-img info /run/kubevirt-private/vmi-disks/pvc/disk.img --output json
{
    "virtual-size": 8545665024,
    "filename": "/run/kubevirt-private/vmi-disks/pvc/disk.img",
    "format": "raw",
    "actual-size": 8545173504,
    "dirty-flag": false
}

[root@fedora-pvc /]# df -h /run/kubevirt-private/vmi-disks/pvc
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/5b72996700000499  8.0G  8.0G  480K 100% /run/kubevirt-private/vmi-disks/pvc
```

**Anything else we need to know?**:
This may only reproduce on PVCs that use a certain FS type or have certain FS features enabled, or are a certain size.

**Environment**:
- KubeVirt version (use `virtctl version`): reproduced on v0.41.0 and v0.35.0
