### ISSUE TITLE
TCP socket maintenance after Live Migration

### ISSUE THREAD

**Issue by teo-tsou** [kubevirt/kubevirt#5816]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:

I have a VMI that runs a python TCP Socket Server. Clients from other VM's connect fine to the server. But when I Live Migrate the VMI , most of the times the connection is lost at the begining of live migration (while clients are sending messages) and the clients getting this error: socket.error: [Errno 104] Connection reset by peer. Although the migration is successful and server keeps running. How can I have a more stable behavior?
The server binds on L2 IP (172.16.0.6/24 net2) which is attached by MULTUS. The multus interface is mapped to a hosts bridge interface that contains a vlan interface (eth1.10). The source-target host machine have the same bridge configuration.

Is there any way to have stable TCP connection during live migrations?
Thank you!

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.40.0
- Kubernetes version (use `kubectl version`): v1.21.1
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**The yaml file**

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: ubuntu
  name: ubuntu
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk

      interfaces:
      - masquerade: {}
        name: default
      - bridge: {}
        name: net1
      - bridge: {}
        name: net2
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: net1
    name: net1
  - multus:
      networkName: net2
    name: net2
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: camelcasenotation/ubuntu1604-containerdisk:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        users:
          - name: root
        ssh_pwauth: True
        chpasswd:
          expire: False
          list: |-
             root:kubernetes


    name: cloudinitdisk

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net1
spec:
  config: '{ "cniVersion": "0.3.0", "type": "bridge", "bridge": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.203/24",
    "gateway": "192.168.18.1" } ] } }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net2
spec:
  config: '{ "cniVersion": "0.3.0", "type": "bridge", "bridge": "br0", "ipam": { "type": "static", "addresses": [ { "address": "172.16.0.6/24",
    "gateway": "172.16.0.1" } ] } }
```
