### ISSUE TITLE
kubevirt tries to create existing network device eth0

### ISSUE THREAD

**Issue by telmich** [kubevirt/kubevirt#5837]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

I tried to create a VM using the following manifest:

```
[0:35] nb2:kubevirt% cat vm1.yaml 
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```

With this configuration the following errors appear in the log:

```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-nocloud","namespace":"default","pos":"vm.go:1654","reason":"failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: file exists","timestamp":"2021-06-15T22:35:06.576062Z","uid":"5d01086a-c7b5-44be-a89e-058e591faef8"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvmi-nocloud","pos":"vm.go:1311","reason":"failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: file exists","timestamp":"2021-06-15T22:35:06.576349Z"}
{"component":"virt-handler","level":"info","msg":"resyncing virt-launcher domains","pos":"cache.go:385","timestamp":"2021-06-15T22:35:52.984348Z"}
{"component":"virt-handler","level":"info","msg":"resyncing virt-launcher domains","pos":"cache.go:385","timestamp":"2021-06-15T22:36:19.382623Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/testvmi-nocloud","pos":"vm.go:1515","timestamp":"2021-06-15T22:36:28.497380Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"testvmi-nocloud","namespace":"default","pos":"vm.go:1517","timestamp":"2021-06-15T22:36:28.497512Z","uid":"5d01086a-c7b5-44be-a89e-058e591faef8"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1524","timestamp":"2021-06-15T22:36:28.497567Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"testvmi-nocloud","namespace":"default","pos":"mount.go:376","timestamp":"2021-06-15T22:36:28.511887Z","uid":"5d01086a-c7b5-44be-a89e-058e591faef8"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"testvmi-nocloud","namespace":"default","pos":"mount.go:379","timestamp":"2021-06-15T22:36:28.511969Z","uid":"5d01086a-c7b5-44be-a89e-058e591faef8"}
{"component":"virt-handler","level":"info","msg":"updated MAC for eth0 interface: old: a2:6b:12:38:8c:81 -\u003e new: a2:6b:12:c7:e8:0b","pos":"common.go:356","timestamp":"2021-06-15T22:36:28.514421Z"}
{"component":"virt-handler","level":"error","msg":"failed to create a bridge","pos":"podinterface.go:600","reason":"file exists","timestamp":"2021-06-15T22:36:28.514529Z"}
{"component":"virt-handler","level":"error","msg":"failed to prepare pod networking","pos":"podinterface.go:243","reason":"file exists","timestamp":"2021-06-15T22:36:28.514587Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-nocloud","namespace":"default","pos":"vm.go:1654","reason":"failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: file exists","timestamp":"2021-06-15T22:36:28.514739Z","uid":"5d01086a-c7b5-44be-a89e-058e591faef8"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvmi-nocloud","pos":"vm.go:1311","reason":"failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: file exists","timestamp":"2021-06-15T22:36:28.515002Z"}
```

**What you expected to happen**:

A running VM

**How to reproduce it (as minimally and precisely as possible)**:

Install a cluster with IPv6, calico and try to create that particular VM.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.42.1
- Kubernetes version (use `kubectl version`): 1.21.1
- VM or VMI specifications: see above
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): alpine Linux
- Kernel (e.g. `uname -a`): 5.10.43-0-lts
- Install tools:
- Others:

**Comment by qinqon** [comment]
Can you verify if virt-handler got restarted in the middle of the deploy ? 
```
kubectl get pod -n kubevirt -l kubevirt.io=virt-handler
```

**Comment by telmich** [comment]
That does not look to be the case:

```
[17:17] nb3:~% kubectl get pod -n kubevirt -l kubevirt.io=virt-handler
NAME                 READY   STATUS    RESTARTS   AGE
virt-handler-7dp2f   1/1     Running   0          40h
virt-handler-b5j6g   1/1     Running   0          40h
virt-handler-t4rxw   1/1     Running   0          40h
[17:17] nb3:~% 
```

I have also just recreated the VMI and the describe of it looks like this:

```
[17:22] nb3:~% kubectl describe vmi testvmi-nocloud
Name:         testvmi-nocloud
Namespace:    default
Labels:       kubevirt.io/nodeName=server49
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2021-06-16T15:18:24Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  6
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:domain:
          .:
          f:devices:
            .:
            f:disks:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:terminationGracePeriodSeconds:
        f:volumes:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-06-16T15:18:24Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:labels:
          .:
          f:kubevirt.io/nodeName:
      f:status:
        f:activePods:
          .:
          f:263f4293-bf73-4b6c-9c97-761ebf945673:
        f:nodeName:
        f:phase:
        f:qosClass:
    Manager:      virt-controller
    Operation:    Update
    Time:         2021-06-16T15:18:43Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:migrationMethod:
    Manager:         virt-handler
    Operation:       Update
    Time:            2021-06-16T15:18:48Z
  Resource Version:  656995
  UID:               639e2cf8-bbdd-42c8-a8bf-b01ccada720e
Spec:
  Domain:
    Cpu:
      Cores:    1
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   emptydisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  aa928526-21bf-4f22-97f5-34a39091b773
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  30
  Volumes:
    Container Disk:
      Image:              kubevirt/fedora-cloud-container-disk-demo:latest
      Image Pull Policy:  Always
    Name:                 containerdisk
    Empty Disk:
      Capacity:  2Gi
    Name:        emptydisk
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
    Name:  cloudinitdisk
Status:
  Active Pods:
    263f4293-bf73-4b6c-9c97-761ebf945673:  server49
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2021-06-16T15:18:48Z
    Message:               failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 25405: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: exit status 1, output: Error: failed to create tap device named tap0. Reason: [0]: no such file or directory
[1]: no such file or directory
[2]: no such file or directory
[3]: no such file or directory
[4]: no such file or directory
Usage:
  virt-chroot create-tap [flags]

Flags:
      --gid uint              the group of the owner of the tap device
  -h, --help                  help for create-tap
      --mtu uint32            the link MTU of the tap device (default 1500)
      --queue-number uint32   the number of queues to use on multi-queued devices
      --tap-name string       the name of the tap device (default "tap0")
      --uid uint              the owner of the tap device

Global Flags:
      --cpu uint32      cpu time in seconds for the process
      --memory uint32   memory in megabyte for the process
      --mount string    mount namespace to use
      --user string     switch to this targetUser to e.g. drop privileges

failed to create tap device named tap0. Reason: [0]: no such file or directory
[1]: no such file or directory
[2]: no such file or directory
[3]: no such file or directory
[4]: no such file or directory

    Reason:  Synchronizing with the Domain failed.
    Status:  False
    Type:    Synchronized
  Guest OS Info:
  Migration Method:  BlockMigration
  Node Name:         server49
  Phase:             Scheduled
  Qos Class:         Burstable
Events:
  Type     Reason            Age    From                       Message
  ----     ------            ----   ----                       -------
  Normal   SuccessfulCreate  4m12s  virtualmachine-controller  Created virtual machine pod virt-launcher-testvmi-nocloud-b5r7d
  Warning  SyncFailed        3m48s  virt-handler               failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 25405: failed running command /usr/bin/virt-chroot create-tap --tap-name tap0 --uid 0 --gid 0 --queue-number 0 --mtu 1480, err: exit status 1, output: Error: failed to create tap device named tap0. Reason: [0]: no such file or directory
[1]: no such file or directory
[2]: no such file or directory
[3]: no such file or directory
[4]: no such file or directory
Usage:
  virt-chroot create-tap [flags]

Flags:
      --gid uint              the group of the owner of the tap device
  -h, --help                  help for create-tap
      --mtu uint32            the link MTU of the tap device (default 1500)
      --queue-number uint32   the number of queues to use on multi-queued devices
      --tap-name string       the name of the tap device (default "tap0")
      --uid uint              the owner of the tap device

Global Flags:
      --cpu uint32      cpu time in seconds for the process
      --memory uint32   memory in megabyte for the process
      --mount string    mount namespace to use
      --user string     switch to this targetUser to e.g. drop privileges

failed to create tap device named tap0. Reason: [0]: no such file or directory
[1]: no such file or directory
[2]: no such file or directory
[3]: no such file or directory
[4]: no such file or directory
  Warning  SyncFailed  64s (x15 over 3m48s)  virt-handler  failed to configure vmi network: failed plugging phase1 at nic 'eth0': Critical network error: file exists
[17:22] nb3:~% 
```

Checking the modules on the host:

```
[17:23] server49.place7:~# lsmod | grep -e vhos -e tun -e tap
vhost_net              24576  0
tun                    57344  1 vhost_net
vhost                  45056  1 vhost_net
vhost_iotlb            16384  1 vhost
tap                    28672  1 vhost_net
tunnel4                16384  1 ipip
ip_tunnel              32768  1 ipip
[17:23] server49.place7:~# 
```

**Comment by qinqon** [comment]
There are two different errors here the one from the description 
```
{"component":"virt-handler","level":"error","msg":"failed to create a bridge","pos":"podinterface.go:600","reason":"file exists","timestamp":"2021-06-15T22:36:28.514529Z"}
```

And the one for the second run 
```
failed to create tap device named tap0. Reason: [0]: no such file or directory
```

By default the type of we are using "bridge", can you try with "masquerade" ? it would be like this

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:                                                               
      - masquerade: {}                                                          
        name: default                                                    
  networks:                                                                     
  - name: default                                                        
    pod: {}         
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```
