### ISSUE TITLE
Lab 2: Cannot SSH into Fedora VM

### ISSUE THREAD

**Issue by lhchang** [kubevirt/kubevirt#5860]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Following Lab 2 Tutorial and cannot SSH into the Fedora machine
**What you expected to happen**:
Being able to SSH into the Fedora machine using client's private SSH key
**How to reproduce it (as minimally and precisely as possible)**:
insert client public key into downloaded YAML file using sed, create VM as per instructions, expose port, ssh using the ip provided by `minikube ip`.

**Anything else we need to know?**:
minikube environment
**Environment**:
- KubeVirt version (use `virtctl version`): 0.42.1
- Kubernetes version (use `kubectl version`): 1.20.2
- VM or VMI specifications: Spec file as defined in vm1_pvc.yaml
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): macOS 10.15.7
- Kernel (e.g. `uname -a`): Darwin 19.6.0
- Install tools: 
- Others:

**Comment by lhchang** [comment]
Similar to an issue found about a year ago, but after the changes were made: https://github.com/kubevirt/kubevirt/issues/3934

**Comment by teo-tsou** [comment]
I had the same issue. I found a workaround by changing the vm name (corresponds to the hostname) to fedora (default hostname) and configure a password for it. 

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: fedora
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - name: fedora
                 ssh-authorized-keys:
                     - $YOUR_KEY_HERE
            ssh_pwauth: True
            disable_root: false
            password: fedora
            chpasswd:
              expire: False
              list: |-
                 fedora:fedora
        name: cloudinitdisk
```
