### ISSUE TITLE
VM has second networks using multus but not configured

### ISSUE THREAD

**Issue by gojoy** [kubevirt/kubevirt#5881]
> /kind bug

**What happened**:
I create VM with secondary networks using [multus](https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#multus) , but the second nic in vm is not configured with dhcp and has no IP assgined.

```
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 0a:58:0a:55:f4:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.85.244.243/24 brd 10.85.244.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::858:aff:fe55:f4f3/64 scope link tentative flags 08
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 0a:58:0a:55:f8:2e brd ff:ff:ff:ff:ff:ff
```

**What you expected to happen**:
the second nic in vm has IP configured by dhcp

**How to reproduce it (as minimally and precisely as possible)**:
create vm with with secondary networks using multus.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications:

The VM yaml:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vmmulnet2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vmmulnet2
    spec:
      nodeSelector:
        idc: xx
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - name: add1
            bridge: {}
        resources:
          requests:
            memory: 512M
      networks:
      - name: default
        pod: {}
      - name: add1
        multus:
          networkName: bridge-conf-2
      volumes:
        - name: containerdisk
          containerDisk:
            image: xxx/cirros:latest
```

The bridge yaml:
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  generation: 1
  name: bridge-conf-2
  namespace: default
spec:
  config: '{ "cniVersion":"0.2.0", "name":"mynet1", "type":"bridge", "master":"br0",
    "ipam":{ "type":"my-ipam", "serverURL":"http://xxx"
    } }'
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos6
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
