### ISSUE TITLE
write_files , runcmd  cloudinit configuration not working for VM manifest

### ISSUE THREAD

**Issue by k-p-ani** [kubevirt/kubevirt#5885]
kind bug
> /kind enhancement

**What happened**:
I am trying to configure network data for my Ubuntu VM image from within "**cloudInitNoCloud**".
I was going through below link
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#injecting-ssh-keys-with-cloud-inits-cloud-config
. In the above link there is reference to another link "**Cloud-init Examples**" (see below link) which has more examples on how to use **write_files** and **runcmd**
https://cloudinit.readthedocs.io/en/latest/topics/examples.html#writing-out-arbitrary-files
https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot

I followed above two links and created sample VM manifest file (**below is important cloud init configuration part**)
volumes:

```yaml
      - name: networkInit
        **cloudInitNoCloud**:
          **write_files**:
          _- path: /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
            permissions: '0644'
            content: |
              network: {config: disabled}
          - path: /etc/netplan/new-config.yaml
            permissions: '0644'
            content: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true_
          **runcmd**:
            _- rm /etc/netplan/00-installer-config.yaml
            - netplan generate
            - netplan apply_
```

When I try to create VM resource the Yaml schema validation fails.
error: error validating "vm-ubuntu-network.yaml": error validating data: [ValidationError(VirtualMachine.spec.template.spec.volumes[0].cloudInitNoCloud): **unknown field "runcmd"** in io.kubevirt.v1alpha3.VirtualMachine.spec.template.spec.volumes.cloudInitNoCloud, ValidationError(VirtualMachine.spec.template.spec.volumes[0].cloudInitNoCloud): **unknown field "write_files"** in io.kubevirt.v1alpha3.VirtualMachine.spec.template.spec.volumes.cloudInitNoCloud]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
Expected that yaml would have worked and did the job. Also expecting 

**How to reproduce it (as minimally and precisely as possible)**:
Try to create VM resource having above mentioned "**cloudInitNoCloud**" configuration

**Anything else we need to know?**:
I tried to set the required networking configurations to my VM instance using below configuration in VM manifest file , but this didn't worked, after logging into VM instance when I see network configuration not reflecting as below.
  - **cloudInitNoCloud**:
      **networkData**: |
        _version: 2
        ethernets:
          enp1s0:
            dhcp4: true_

**Environment**:
- KubeVirt version (use `virtctl version`):
_Client Version: version.Info{GitVersion:"v0.42.1", GitCommit:"3e4ea2d9b8d4405dc307e885bc49f10c8ce5372c", GitTreeState:"clean", BuildDate:"2021-06-10T01:42:11Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.0-dirty", GitCommit:"b7f322409e310ebaf7edb9f657d9864ad5730ab0", GitTreeState:"dirty", BuildDate:"2021-05-12T15:11:03Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}_

- Kubernetes version (use `kubectl version`):
_Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:21:41Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:20:09Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}_

- Cloud provider or hardware configuration: _Bare metal_

- OS (e.g. from /etc/os-release):
_NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal_

- Kernel (e.g. `uname -a`):
_Linux ip-10-0-0-249 5.8.0-1035-aws #37~20.04.1-Ubuntu SMP Tue Jun 1 09:54:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux_
- Install tools:
- Others:
