### ISSUE TITLE
kubectl get vm command,miss STATUS field, when there are lots of VMS in the cluster

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#5947]
/kind bug

Create around 500 stopped VMs, run `kubectl get vm -A`

**What happened**:
Some VMs miss STATUS field,
and from some point of the output all the VMs miss the field

```
default     test-vm188    3m3s    Stopped   
default     test-vm189    3m3s    Stopped   
default     test-vm19     3m1s              
default     test-vm190    3m2s    Stopped   
default     test-vm191    3m2s    Stopped   
default     test-vm192    3m2s    Stopped   
default     test-vm193    3m2s    Stopped   
default     test-vm194    3m2s    Stopped   
default     test-vm195    3m2s    Stopped   
default     test-vm196    3m1s    Stopped   
default     test-vm197    3m1s    Stopped   
default     test-vm198    3m1s    Stopped   
default     test-vm199    3m1s              
default     test-vm2      2m44s             
default     test-vm20     2m59s             
default     test-vm200    3m1s      
```

Note that `kubectl get vm <NAME>` of one of those who miss the field, do show the STATUS

**What you expected to happen**:
All VMs should show the sttatus

**How to reproduce it (as minimally and precisely as possible)**:
Spin latest kubevirt k8s-1.21 provider, with CNAO (not sure mandatory, but if it doesnt happen without try with it)

**Anything else we need to know?**:

Create this yaml named test_vm1.yaml 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: oper-test-vm
  name: test-vm1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: ""
        resources:
          requests:
            memory: 128Mi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/redhat/cnv-tests-fedora-staging
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
```

Duplicate it with diff VM name
```
#!/bin/bash
for i in {2..500}
do
   cp test_vm1.yaml "test_vm"${i}.yaml
   sed -i "s/test-vm1/test-vm${i}/" "test_vm"${i}.yaml
done
```

Create them all
`ls -1 | awk '{system("oc create -f" $0)}'`

Run the kubectl get command as above and check all fields that they have or miss STATUS
