### ISSUE TITLE
VM doesn't show multiple Disks mounted as PVC

### ISSUE THREAD

**Issue by rraj-gautam** [kubevirt/kubevirt#5966]
**BUG REPORT**:

> /kind bug

**VM with multiple Disks boots, but the additional disk ( other than virtio ) is not shown inside  window10 os.**:

**Expected Result**:
I want to add additional/secondary hardisk to the vm.

**Here is my vm yaml**:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win10-home
  labels:
    kubevirt.io/domain: windows10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows10
        prometheus.kubevirt.io: "node-exporter"
    spec:
      domain:
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191    
        cpu:
          cores: 4
        devices:
          autoattachGraphicsDevice: True
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - cdrom:
              bus: sata
            name: virtiocontainerdisk            
          - disk: 
              bus: virtio
            name: harddrive
          - disk: 
              bus: sata
            name: shareddisk
          interfaces:
          - masquerade: {}
            model: e1000e 
            name: default               
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
        - name: default
          pod: {}              
      volumes:
      - dataVolume:
          name: win10-bootdisk
        name: cdromiso  
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10-harddisk
      - name: shareddisk
        persistentVolumeClaim:
          claimName: shared-harddisk
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk

```
