### ISSUE TITLE
cloudinit ConfigDrive iso can not be generated intermittently in window vm

### ISSUE THREAD

**Issue by fanzhangio** [kubevirt/kubevirt#5969]
**BUG REPORT**:

/kind bug

**What happened**:
This issue is reproduced when create a bulk of vmis at the same time with same UUID and a cloudinit configDrive as a cdrom SATA disk (attache to window vm as D: drive).  In some of the times, the configdrive iso file is missing in launcher pod, which does not match the VMI spec and generated XML. The windows vm does not have D drive. The windows hasn't had the IPs configured properly thus locally assigned a 169.254 IANA address and then qemu-guest agent hands over this IANA value to `kubectl describe vmi`. 

e.g.
using cloudint for a cdrom disks:
```
    devices:
      blockMultiQueue: true
      disks:
      - cdrom:
          bus: sata
          readonly: true
          tray: closed
        name: cloudinitdisk
```        
The cloudinitdsk provides the content:
```
  - cloudInitConfigDrive:
      secretRef:
        name: configdrive
    name: cloudinitdisk
```

the iso file read from cloudInitConfigDrive is missing in launcher pod. It can not be generated to
the path which is expected `/var/run/kubevirt-ephemeral-disks/cloud-init-data/nq-01/vmi-2/configdrive.iso`

```
{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/nq-01/vmi-2/configdrive.iso","pos":"cloud-init.go:478","timestamp":"2021-06-30T20:30:08.353055Z"}
{"component":"virt-launcher","level":"info","msg":"Successfully connected to domain notify socket at /var/run/kubevirt/domain-notify-pipe.sock","pos":"client.go:138","timestamp":"2021-06-30T20:30:08.359655Z"}
```
But the file does not exit, and there is no any error through

```
[root@vmi-2 kubevirt-ephemeral-disks]# ls -la /var/run/kubevirt-ephemeral-disks/cloud-init-data/nq-01/vmi-2/configdrive.iso
ls: cannot access '/var/run/kubevirt-ephemeral-disks/cloud-init-data/nq-01/vmi-2/configdrive.iso': No such file or directory
```

**What you expected to happen**:
Windows VMI has its rootdisk from PVC have cloudInit clouddrive iso attached as cdrom. 

**Anything else we need to know?**:

**Environment**: 
- KubeVirt version (use `virtctl version`):  release-0.35
- Kubernetes version (use `kubectl version`): 1.19+
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
    virtualmachinepreset.kubevirt.io/g6.half: kubevirt.io/v1alpha3
    vm.kubevirt.io/baseDiskName: "3194562522234434308"
    vm.kubevirt.io/deltaDiskName: rootdisk
  finalizers:
  - foregroundDeleteVirtualMachine
  generation: 1427
  labels:
    kubevirt.io/nodeName: gs-node.nvmetal.net
  name: vmi-2
  namespace: ns-01
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv:
          present: true
        pit:
          present: true
          tickPolicy: delay
        rtc:
          present: true
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
      customCpuPlacement: true
      threads: 2
    devices:
      blockMultiQueue: true
      disks:
      - disk:
          bus: virtio
        name: rootdisk
      - cdrom:
          bus: sata
          readonly: true
          tray: closed
        name: cloudinitdisk
      - disk:
          bus: virtio
        name: "1651147752775056495"
      gpus:
      - deviceName: nvidia.com/GeForce_RTX_T10-8
        name: gpu1
      interfaces:
      - bridge: {}
        model: e1000
        name: APP
      - name: STORAGE
        sriov: {}
      - name: STREAM
        sriov: {}
    features:
      acpi:
        enabled: true
      hyperv:
        frequencies:
          enabled: true
        relaxed:
          enabled: true
        runtime:
          enabled: true
        spinlocks:
          enabled: true
          spinlocks: 4096
        synic:
          enabled: true
        synictimer:
          enabled: true
        vapic:
          enabled: true
        vendorid:
          enabled: true
          vendorid: NVP Hv
        vpindex:
          enabled: true
    firmware:
      uuid: d7421be9-7d1e-4e13-8a6b-a402739c919e # hardcoded UUID
    machine:
      type: q35
    memory:
      hugepages:
        pageSize: 1Gi
    resources:
        cpu: 100m
        memory: 7Gi
  networks:
  - name: APP
    pod: {}
  - multus:
      networkName: sriov-storage
    name: STORAGE
  - multus:
      networkName: sriov-stream
    name: STREAM
  volumes:
  - name: rootdisk
    persistentVolumeClaim:
      claimName: rootdiskpvc
  - cloudInitConfigDrive:
      secretRef:
        name: configdrive
    name: cloudinitdisk
  - hostDisk:
      capacity: "0"
      path: /data/windows.qcow2
      type: Disk
    name: "1651147752775056495"
```

- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): 
    ```
    NAME="CentOS Linux"
    VERSION="8 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="8"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="CentOS Linux 8 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:8"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-8"
    CENTOS_MANTISBT_PROJECT_VERSION="8"
    REDHAT_SUPPORT_PRODUCT="centos"
    ```
- Kernel (e.g. `uname -a`):
   ```
   Linux gs-node.nvmetal.net 4.18.0-193.13.2.el8.1622008870.664c92a05.x86_64 #1 SMP Wed May 26 13:04:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Install tools:
- Others:
