### ISSUE TITLE
process "qemu-kvm" with high cpu load

### ISSUE THREAD

**Issue by 66545shiwo** [kubevirt/kubevirt#5999]
Hello,

When I execute the jps command in my VirtualMachineInstance,  this command hangs there , and  the process "qemu-kvm" was with high cpu load.

​         

```                                                                                                                                                    
top

   PID USER       PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                            
 49443 qemu      20   0 6428280   1.9g  21188 S 312.9  0.5 168:32.34 qemu-kvm 
```

```
top -Hp 49443 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                             
 49451 qemu      20   0 6428280   1.9g  21188 R 99.3  0.5 142:35.05 CPU 3/TCG                                                                                                                                                           
 49452 qemu      20   0 6428280   1.9g  21188 R 99.3  0.5   3:58.55 CPU 4/TCG                                                                                                                                                           
 49449 qemu      20   0 6428280   1.9g  21188 R 99.0  0.5   2:52.80 CPU 1/TCG                                                                                                                                                           
 49443 qemu      20   0 6428280   1.9g  21188 R  7.6  0.5  10:54.96 qemu-kvm                                                                                                                                                            
 49454 qemu      20   0 6428280   1.9g  21188 S  5.0  0.5   3:23.31 CPU 6/TCG                                                                                                                                                           
 49455 qemu      20   0 6428280   1.9g  21188 S  3.0  0.5   1:31.03 CPU 7/TCG                                                                                                                                                           
 49448 qemu      20   0 6428280   1.9g  21188 S  0.3  0.5   3:20.26 CPU 0/TCG                                                                                                                                                           
 49445 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   0:00.28 qemu-kvm                                                                                                                                                            
 49446 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   0:00.02 IO iothread1                                                                                                                                                        
 49447 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   0:01.44 IO mon_iothread                                                                                                                                                     
 49450 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   1:03.74 CPU 2/TCG                                                                                                                                                           
 49453 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   1:22.49 CPU 5/TCG                                                                                                                                                           
 49457 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   0:00.00 vnc_worker                                                                                                                                                          
 37817 qemu      20   0 6428280   1.9g  21188 S  0.0  0.5   0:00.00 worker                      
```

```
vm.yalm:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: centos
    spec:
      domain:
        cpu:
          cores: 4
          threads: 2
        devices:
          disks:
          - name: cdromiso
            disk:
              bus: virtio                
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: "4Gi"
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: centos-pvc
```

​                                                                                                                            

```
kubevirt version: v0.37.0
kubernetes version: v1.20.6
img version:  CentOS Linux release 7.8.2003 (Core) 
host version: CentOS Linux release 7.9.2009 (Core)
```

Could you please help me see what's wrong with the VirtualMachineInstance?
