### ISSUE TITLE
V0.43 failed to enable NUMA topology

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#6127]
Hi all, I have an issues with V0.43.  as of now I'm working with 0.37 with dedicatedCpuPlacement (cpuManager) all is working fine. I want test now the new numa topology. for that i uninstalled kubevirt and install 0.43
I updated the kubevirt-config with the new NUMA feature-gate but still get an error: NUMA feature gate is not enabled in kubevirt-config
cpumanager label is always false. i have the same k8s installation on  0.37 all is working fine there . kubelet config below.
@rmohr @vladikr

```yaml
kubeReserved:
  cpu: 100m
  memory: 256Mi
resolvConf: "/run/systemd/resolve/resolv.conf"
cpuManagerPolicy: static
featureGates:
  CPUManager: true
reservedSystemCPUs: '1'
eventRecordQPS: 5
```

**Anything else we need to know?**:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: numavm
spec:
  domain:
    cpu:
      cores: 4
      dedicatedCpuPlacement: true
      numa:
        guestMappingPassthrough : {}
```

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@talcoh2x can you share your `KubeVirt` CR? `kubectl get kubevirt -n kubevirt kubevirt`. Also can you ensure that you are not still using a configmap for configuration? `kubectl get configmaps -n kubevirt kubevirt-config`?

**Comment by talcoh2x** [comment]
kubectl get kubevirt -n kubevirt kubevirt
NAME       AGE    PHASE
kubevirt   109m   Deployed


my kubevirt-config is under "default" namespace

kubectl get configmaps -n kubevirt kubevirt-config
Error from server (NotFound): configmaps "kubevirt-config" not found

 kubectl get configmaps  kubevirt-config
NAME              DATA   AGE
kubevirt-config   2      87m

~/ws-test-numa# kubectl describe configmaps  kubevirt-config
Name:         kubevirt-config
Namespace:    default
Labels:       kubevirt.io=
Annotations:  <none>

Data
====
feature-gates:
----
DataVolumes,SRIOV,LiveMigration,CPUManager,ExperimentalVirtiofsSupport,HostDisk,GPU,NUMA
permittedHostDevices:
----
pciHostDevices:
- pciVendorSelector: 1da3:1000
  resourceName: habana.ai/gaudi
- pciVendorSelector: 1da3:0001
  resourceName: habana.ai/goya
Events:  <none>

**Comment by rmohr** [comment]
@talcoh2x you say that your config map is under `default`. In which namespace do `virt-operator`, `virt-api`, ... run?

**Comment by talcoh2x** [comment]
@rmohr  virt-operator, virt-api is  under kuebvirt namespace. it's a 
problem ?

```
kubevirt             virt-api-866b4fb4f4-bdj8r                  1/1     Running   0          98m
kubevirt             virt-api-866b4fb4f4-hq7c9                  1/1     Running   0          132m
kubevirt             virt-controller-67d4bf4947-jb57l           1/1     Running   0          98m
kubevirt             virt-controller-67d4bf4947-vj5js           1/1     Running   1          131m
kubevirt             virt-handler-5kdtz                         1/1     Running   0          131m
kubevirt             virt-handler-crf77                         1/1     Running   0          131m
kubevirt             virt-handler-p6nqj                         1/1     Running   0          131m
```

**Comment by rmohr** [comment]
> @rmohr virt-operator, virt-api is under kuebvirt namespace. it's a
> problem ?

Yes, it means that the configmap is ignored. It has to run in the same namespace. You do not yet use our operator?

**Comment by talcoh2x** [comment]
yes I am.
kubevirt             virt-api-866b4fb4f4-bdj8r                  1/1     Running   0          98m
kubevirt             virt-api-866b4fb4f4-hq7c9                  1/1     Running   0          132m
kubevirt             virt-controller-67d4bf4947-jb57l           1/1     Running   0          98m
kubevirt             virt-controller-67d4bf4947-vj5js           1/1     Running   1          131m
kubevirt             virt-handler-5kdtz                         1/1     Running   0          131m
kubevirt             virt-handler-crf77                         1/1     Running   0          131m
kubevirt             virt-handler-p6nqj                         1/1     Running   0          131m
kubevirt             virt-handler-xjggk                         1/1     Running   3          131m
kubevirt             virt-operator-657df5ccf9-cjhlq             1/1     Running   0          132m
kubevirt             virt-operator-657df5ccf9-l59wr             1/1     Running   0          98m


let me check it again

**Comment by talcoh2x** [comment]
@rmohr  ok it working now. cool so something changed from 0.37 you read from same namespace only now. 

now seems it failed because cpumanager is false and not true. 

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  33s   default-scheduler  0/7 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 Insufficient hugepages-2Mi, 4 node(s) didn't match node selector.
  Warning  FailedScheduling  33s   default-scheduler  0/7 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 Insufficient hugepages-2Mi, 4 node(s) didn't match node selector.

**Comment by rmohr** [comment]
> yes I am.

Ok, then I would recommend adding your configuration to the kubevirt `cr` (kubectl edit kubevirt -n kubevirt kubevirt`. Something like this:

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration: 
      featureGates:
        - DataVolumes
        - SRIOV
        - LiveMigration
        - CPUManager
        - ExperimentalVirtiofsSupport
        - HostDisk
        - GPU
        - NUMA
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: 1da3:1000
        resourceName: habana.ai/gaudi
      - pciVendorSelector: 1da3:0001
        resourceName: habana.ai/goya        
```
