### ISSUE TITLE
A Disk not attached to multiple VMs as readwrite

### ISSUE THREAD

**Issue by rraj-gautam** [kubevirt/kubevirt#6148]
**I am trying to mount a  NFS PVC to VirtualMachineInstanceReplicaSet inorder to get a additional disk(readwrite) shared among different  virtualmachines (similar to NFS mounts on different vms)**
Following is the issue I got which says that we cannot attach a disk as readwrite on multiple vms at a time.
```
Generated from virt-handler
server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor:
2021-07-28T17:01:48.136803Z qemu-kvm: -device ide-hd,bus=ide.2,drive=libvirt-3-format,id=ua-shareddrive,bootindex=4,write-cache=on: 
Failed to get \"write\" lock\nIs another process using the image [/var/run/kubevirt-private/vmi-disks/shareddrive/disk.img]?')"
```

**Is there any way to achieve this?**

**VM yaml**
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: win10
spec:
  replicas: 4
  selector:
    matchLabels:
      kubevirt.io/domain: windows
  template:
    metadata:
      name: win10
      labels:
        kubevirt.io/domain: windows
    spec:
      domain:
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191    
        cpu:
          cores: 4
        devices:
          autoattachGraphicsDevice: True
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            cdrom:
              bus: sata
            name: virtiocontainerdisk            
          - bootOrder: 3
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 4
            disk:
              bus: sata
            name: shareddrive
          interfaces:
          - masquerade: {}
            model: e1000e 
            name: default               
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
        - name: default
          pod: {}              
      volumes:
      - dataVolume:
          name: win10-bootdisk
        name: cdromiso  
      - name: harddrive
        ephemeral: 
          persistentVolumeClaim:
            claimName: win10-harddisk
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
      - name: shareddrive
        persistentVolumeClaim:
          claimName: shared-harddisk
```

**Domain XML**
```
<domain type='kvm'>
  <name>default_win10vwwjs</name>
  <uuid>e0b1f4b5-6c5c-4bf3-8d76-527c49f0b33f</uuid>
  <metadata>
    <kubevirt xmlns="http://kubevirt.io">
      <uid>67b49339-4deb-4232-ab79-04c5d6631e0b</uid>
      <graceperiod>
        <deletionGracePeriodSeconds>30</deletionGracePeriodSeconds>
      </graceperiod>
    </kubevirt>
  </metadata>
  <memory unit='KiB'>7812500</memory>
  <currentMemory unit='KiB'>7812500</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <iothreads>1</iothreads>
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>KubeVirt</entry>
      <entry name='product'>None</entry>
      <entry name='uuid'>e0b1f4b5-6c5c-4bf3-8d76-527c49f0b33f</entry>
      <entry name='family'>KubeVirt</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-q35-rhel8.3.0'>hvm</type>
    <smbios mode='sysinfo'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
  </features>
  <cpu mode='host-model' check='partial'>
    <topology sockets='1' dies='1' cores='4' threads='1'/>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw' cache='none'/>
      <source file='/var/run/kubevirt-private/vmi-disks/cdromiso/disk.img'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <boot order='1'/>
      <alias name='ua-cdromiso'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/var/run/kubevirt-ephemeral-disks/disk-data/virtiocontainerdisk/disk.qcow2'/>
      <backingStore type='file'>
        <format type='raw'/>
        <source file='/var/run/kubevirt/container-disks/disk_2.img'/>
      </backingStore>
      <target dev='sdb' bus='sata'/>
      <readonly/>
      <boot order='2'/>
      <alias name='ua-virtiocontainerdisk'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='none'/>
      <source file='/var/run/kubevirt-private/vmi-disks/shareddrive/disk.img'/>
      <target dev='sdc' bus='sata'/>
      <boot order='4'/>
      <alias name='ua-shareddrive'/>
      <address type='drive' controller='0' bus='0' target='0' unit='2'/>
    </disk>
    <disk type='file' device='disk' model='virtio-non-transitional'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/var/run/kubevirt-ephemeral-disks/disk-data/harddrive/disk.qcow2'/>
      <backingStore type='file'>
        <format type='raw'/>
        <source file='/var/run/kubevirt-private/vmi-disks/harddrive/disk.img'/>
      </backingStore>
      <target dev='vda' bus='virtio'/>
      <boot order='3'/>
      <alias name='ua-harddrive'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='none'/>
    <controller type='scsi' index='0' model='virtio-non-transitional'>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='virtio-serial' index='0' model='virtio-non-transitional'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <interface type='ethernet'>
      <mac address='52:54:00:17:89:2b'/>
      <target dev='tap0' managed='no'/>
      <model type='e1000e'/>
      <mtu size='1480'/>
      <alias name='ua-default'/>
      <rom enabled='no'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/67b49339-4deb-4232-ab79-04c5d6631e0b/virt-serial0'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/67b49339-4deb-4232-ab79-04c5d6631e0b/virt-serial0'/>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' socket='/var/run/kubevirt-private/67b49339-4deb-4232-ab79-04c5d6631e0b/virt-vnc'>
      <listen type='socket' socket='/var/run/kubevirt-private/67b49339-4deb-4232-ab79-04c5d6631e0b/virt-vnc'/>
    </graphics>
    <video>
      <model type='vga' vram='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <stats period='10'/>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```

**Environment**:
VM OS: windows10
