### ISSUE TITLE
kubevirt0.41.2 cannot install windows with virtio driver

### ISSUE THREAD

**Issue by wonleing** [kubevirt/kubevirt#6244]
/kind bug

**What happened**:
There are 2 kinds of virtio driver (viostar, vioscsi) pops up, but none of them can make disk installable
The disk error is:
The computer's Hardware may not support to this disk. Ensure that the disk controller is enabled in the computer's BIOS menu

**How to reproduce it (as minimally and precisely as possible)**:
load win10.yml (with virtio-container-disk and win10 iso)
content see below

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.34.2", GitCommit:"48956f60864ece98118d7894327caf7513c5b942", GitTreeState:"clean", BuildDate:"2020-11-17T13:47:56Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.2-dirty", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"dirty", BuildDate:"2021-07-28T16:57:02Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):1.18.5
- VM or VMI specifications:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: hostpath
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win10-install
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-install
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: win10
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
- Cloud provider or hardware configuration: SSD PC
- OS (e.g. from /etc/os-release): debian10
- Kernel (e.g. `uname -a`): 4.19.90
- Install tools: none
- Others:
