### ISSUE TITLE
VM cannot set PF netcard in front of SR-IOV

### ISSUE THREAD

**Issue by h807892124** [kubevirt/kubevirt#6245]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The VM network interface order cannot customize. SR-IOV netcard always in front of PF.

**What you expected to happen**:
I want to using VM with two netcard, PF be default like eth0, SR-IOV be second like eth1.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.41.0", GitCommit:"b7f322409e310ebaf7edb9f657d9864ad5730ab0", GitTreeState:"clean", BuildDate:"2021-05-12T14:43:31Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: host-nic
              sriov: {}
            - name: sriov-nic
              sriov: {}
          networkInterfaceMultiqueue: true
      networks:
        - multus:
            networkName: pf/host-nic
          name: host-nic
        - multus:
            networkName: sriov/sriov-nic
          name: sriov-nic
```
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): CentOS7
- Kernel (e.g. `uname -a`):
```
Linux xxx 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
