### ISSUE TITLE
use sriov cni set ip failed.

### ISSUE THREAD

**Issue by silenceper** [kubevirt/kubevirt#6255]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement
/kind bug

**What happened**:

I follow this document to configure step by step, https://github.com/kubevirt/kubevirt/blob/main/docs/sriov.md
And successfully started the vmi container, but found in the container, and did not see the network card configured by sriov-cni.

pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.244.1.142"
          ],
          "mac": "92:0a:34:12:76:1e",
          "default": true,
          "dns": {}
      },{
          "name": "intelnics",
          "interface": "net1",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"intelnics","namespace":"default"}]'
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.244.1.142"
          ],
          "mac": "92:0a:34:12:76:1e",
          "default": true,
          "dns": {}
      },{
          "name": "intelnics",
          "interface": "net1",
          "dns": {}
      }]
    kubevirt.io/domain: vmi-perf
    traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
.....
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):v0.42.0
- Kubernetes version (use `kubectl version`):v1.18.17
- VM or VMI specifications:
vmi:
```
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-perf
  name: vmi-perf
spec:
  domain:
    cpu:
      cores: 1
    resources:
      requests:
        memory: "4Gi"
      limits:
        memory: "4Gi"
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: default
      - name: sriov-net
        sriov: {}
      rng: {}
    machine:
      type: ""
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: default/intelnics
    name: sriov-net
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: docker.io/kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "centos" |passwd centos --stdin
        dhclient eth1
    name: cloudinitdisk
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux release 7.9 (Final)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
