### ISSUE TITLE
use SR-IOV can not set ip address

### ISSUE THREAD

**Issue by silenceper** [kubevirt/kubevirt#6268]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
I successfully deployed the relevant components according to this document https://github.com/kubevirt/kubevirt/blob/main/docs/sriov.md. You can see the new second network card in the vm, but the network card’s ip is not set.

According to the investigation(ref:https://github.com/k8snetworkplumbingwg/sriov-cni/pull/142#issuecomment-901033073), it is because the sriov-cni plug-in does not set the ip information, and the program in the vm needs to be actively set.

**What you expected to happen**:
ip information is automatically set

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by silenceper** [comment]
Is there a way to successfully set the ip in vm in kubevirt? For example, through cloud-init?

**Comment by silenceper** [comment]
After a detailed test, using `cloudInitConfigDrive` to configure networkData can succeed in the windows virtual machine, but it fails in the linux vm.
```
- cloudInitConfigDrive:
      userData: |-
        #cloud-config
        write_files:
      networkData: |
        {"networks":[{"network_id":"fbddc7a6-6d2b-4957-a880-aa89238ab011","type":"ipv4","netmask":"255.255.255.192","link":"Ethernet 3","routes":[{"network":"0.0.0.0","netmask":"0.0.0.0","gateway":"10.107.2.65"}],"ip_address":"10.107.2.120","id":"Ethernet 3"}]}
```

Configuring networkData through cloudInitNoCloud can succeed in linux but fail under windows.
```
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        dhclient eth0
      networkData: | 
        version: 2
        ethernets:
          eth1: 
            addresses:
              - 10.107.2.114/26
            gateway4: 10.107.2.65
    name: cloudinitdisk
```
