### ISSUE TITLE
Can't vnc into virtal machine. Can't connect to websocket (504): websocket: bad handshake

### ISSUE THREAD

**Issue by Dines97** [kubevirt/kubevirt#6313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I am trying to follow this guide https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html. At the last stage, I cannot vnc into the virtual machine. 

```
virtctl  vnc win2k12-iso
Can't access VMI win2k12-iso: Can't connect to websocket (504): websocket: bad handshake
```

**What you expected to happen**:
See the virtual machine screen as in the picture.

**How to reproduce it (as minimally and precisely as possible)**:
Basically follow the guide. I used the method https://github.com/kubevirt/containerized-data-importer/blob/main/doc/upload.md to upload the iso. `virtctl image-upload` I was unable to use, uploaded with curl.

**Anything else we need to know?**:
For the cluster, I am using GKE.

**Environment**:
- KubeVirt version (use `virtctl version`):

```
Client Version: version.Info{GitVersion:"v0.44.1", GitCommit:"01805c72083902832ecbd08559f4d3aa88110ea1", GitTreeState:"clean", BuildDate:"2021-08-12T12:35:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.44.1-dirty", GitCommit:"01805c72083902832ecbd08559f4d3aa88110ea1", GitTreeState:"dirty", BuildDate:"2021-08-12T12:57:12Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```
- VM or VMI specifications:

win2k12.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win2k12-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: win-server-19
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
- Cloud provider or hardware configuration:
GKE

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
Linux Denis-U 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:
