### ISSUE TITLE
How to add the resources limits to the virt-api/virt-controller/virt-handler pods ?

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#6343]
/king consulting

**What happened**:
I want add resources limits to the virt-api , virt-controller and virt-handler pods, following is the cr yaml:

```yaml
$ cat kubevirt-cr-v0.41.0.yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents:
    patches:
    - resourceType: Deployment
      resourceName: virt-api
      patch: '[{ "op": "add", "path": "/spec/template/spec/containers/0/resources/limits", "value": {"cpu": 2, "memory": "4096Mi"} }]'
      type: strategic
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```
but it seems not works after execute `kubectl apply -f kubevirt-cr-v0.41.0.yaml`, 
and even if I edit the deploy directly , it not take effect too, anybody can help me ?

**What you expected to happen**:
the resources limits can be added to virt-api, virt-controller, virt-handler pods.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0
- Kubernetes version (use `kubectl version`): v1.16
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
