### ISSUE TITLE
VirtualMachine doesn't support "setHostnameAsFQDN: true" filed

### ISSUE THREAD

**Issue by 66545shiwo** [kubevirt/kubevirt#6371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

**What happened**:
VirtualMachine doesn't support "setHostnameAsFQDN: true" filed, but k8s pod support this filed.

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos.wdh1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: centos
        expose: me
    spec:
      setHostnameAsFQDN: true
      hostname: "wdh1"
      subdomain: "com"

     ...
```
```
error: error validating "vmcdi.yaml": error validating data: ValidationError(VirtualMachine.spec.template.spec): unknown field "setHostnameAsFQDN" in io.kubevirt.v1alpha3.VirtualMachine.spec.template.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v0.37.0", GitCommit:"e7bb186ff71a565732da0a5ef979016feff51236", GitTreeState:"clean", BuildDate:"2021-01-18T21:20:11Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.42.1-dirty", GitCommit:"3e4ea2d9b8d4405dc307e885bc49f10c8ce5372c", GitTreeState:"dirty", BuildDate:"2021-06-10T02:06:01Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):  v1.20.6

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
