### ISSUE TITLE
virtualmachinesnapshot-validator error

### ISSUE THREAD

**Issue by 23r096** [kubevirt/kubevirt#6383]
/kind bug

**What happened**:
I'm trying to create a snapshot of a VM, but when i try to create it i get this error:
```console
Error from server: error when creating "snap.yml": admission webhook "virtualmachinesnapshot-validator.snapshot.kubevirt.io" denied the request: snapshot feature gate not enabled
```
i followed this guide:  https://github.com/kubevirt/kubevirt/blob/main/docs/snapshot-restore.md

I enabled the feature gates in the kubevirt deploy and in the /etc/kubenetes/manifiset/* files

**Anything else we need to know?**:
snap.yml file:
```yaml
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  name: snap-1
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: testvm

```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.43.0
- Kubernetes version (use `kubectl version`): v1.21.3
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Debian 10
- Kernel (e.g. `uname -a`): 4.19.0-17-cloud-amd64
