### ISSUE TITLE
VM stuck on Pending

### ISSUE THREAD

**Issue by francisco-pc7063** [kubevirt/kubevirt#6402]
**This a BUG REPORT**:
/kind bug

**What happened**:
Similar to #4748

```
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
default       virt-launcher-testvm-dr6gs         0/2     Pending   0          9m17s
```

```
38s         Warning   FailedScheduling          pod/virt-launcher-testvm-dr6gs   0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
```
**What you expected to happen**:
VM should start

**How to reproduce it (as minimally and precisely as possible)**:
Fresh minikube install (script in install tools)

**Anything else we need to know?**:
```
Capacity:
  cpu:                            2
  devices.kubevirt.io/kvm:        1k
  devices.kubevirt.io/tun:        1k
  devices.kubevirt.io/vhost-net:  1k
  ephemeral-storage:              17784752Ki
  hugepages-2Mi:                  0
  memory:                         4029232Ki
  pods:                           110
Allocatable:
  cpu:                            2
  devices.kubevirt.io/kvm:        0
  devices.kubevirt.io/tun:        1k
  devices.kubevirt.io/vhost-net:  1k
  ephemeral-storage:              17784752Ki
  hugepages-2Mi:                  0
  memory:                         4029232Ki
  pods:                           110
```
ls -l
`crw-rw----+ 1 root kvm 10, 232 Sep 13 17:39 /dev/kvm`

lsmod | grep kvm
```
kvm_intel             233472  4
kvm                   757760  1 kvm_intel
irqbypass              16384  6 kvm
```

I have (offline) existing libvirt VM's
**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.45.0", GitCommit:"c9e87c4cb6292af33ccad8faa5fb9bf269c0fbf4", GitTreeState:"clean", BuildDate:"2021-09-08T14:05:28Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.45.0-dirty", GitCommit:"c9e87c4cb6292af33ccad8faa5fb9bf269c0fbf4", GitTreeState:"dirty", BuildDate:"2021-09-08T14:30:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 512M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

- Cloud provider or hardware configuration:
Intel i5-10600KF
16GB RAM

- OS (e.g. from /etc/os-release):
Debian GNU/Linux 10 (buster)

- Kernel (e.g. `uname -a`):
Linux intel-deb 4.19.0-17-amd64 # 1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
- Install tools:
[script](https://github.com/francisco-pc7063/personal/blob/final/KUBERNETES/install-kubevirt.sh)
Minikube; Kubectl; Krew; Virtcl
