### ISSUE TITLE
Cannot Connect to VM over NodePort service after VM restart

### ISSUE THREAD

**Issue by mjschmidt** [kubevirt/kubevirt#6410]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Create a VM and a corresponding ssh NodePort Service. Then Restart the VM by deleting the pod.
**What you expected to happen**:
After VM starts back up I expected to reconnect to the VM
**How to reproduce it (as minimally and precisely as possible)**:
Using an ubuntu image, but any image should do. Just create a vm listed on a NodePort then once the vm has started up fully delete the pod and have it start back up. Give it a few minutes then try to ssh into the vm. You should get a connection timeout.

**Anything else we need to know?**:
I am able to see that the vm endpoints are being updated in Kubernetes
I am also able to see tcpdump traffic coming into the container, but not making it to the VM. Is it possible the container is not building that network back up correctly when a NodePort is listed as the service type?
ubuntu-20.04-minimal-cloudimg-amd64.img

**Environment**:
- KubeVirt version (use `virtctl version`): v0.45.0
- Kubernetes version (use `kubectl version`): v1.20.6
- VM or VMI specifications: Can't copy paste this, but the VM works
- Cloud provider or hardware configuration: Hardware, can't list specifications
- OS (e.g. from /etc/os-release): Ubuntu is loaded on the hardware
- Kernel (e.g. `uname -a`): cannot list
- Install tools: the vm is deployed by helm chart, but cannot list
- Others:

**Comment by maiqueb** [comment]
We need at least the VMI spec to be able to reproduce this.

**Comment by mjschmidt** [comment]
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: michael-testme-vm
  labels:
    kubevirt.io/vm: michael-testme-vm
  spec:
    pvc:
      accessMode:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
        volumeMode: Block
      source:
        http: https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200423/ubuntu-20.04-minimal-cloud-amd64.img
      running: true
      template:
        metadata:
          labels:
            kubevirt.io/vm: michael-testme-vm
        spec:
          domain:
            cpu:
              cores: 2
              sockets: 1
              threads: 1
            devices:
              disk:
              - disk:
                  bus: virtio
                name: disk-0
              -  disk:
                  bus: virtio
                name: cloudinitdisk
              inputs:
              - bus: usb
                name: tablet
                type: tablet
              interfaces:
              - masquerade: {}
                model: virtio
                name: default
            machine:
              type: q35
            resources:
              requests:
                memory: 4Gi
          hostname: michael-testme-vm
          networks:
          - name: default
            pod: {}
          volumes:
          - dataVolume:
              name: michael-testme-vm
            name: disk-0
          - cloudInitNoCloud:
            userData: |
              password: testpass
              chpasswd:
                expire: false
              ssh_pwauth: true
            name: cloudinitdisk
```

**Comment by mjschmidt** [comment]
something like this ^

**Comment by mjschmidt** [comment]
There may be typos... I don't have a cluster on the internet I can test on

**Comment by mjschmidt** [comment]
Were you guys able to reproduce the issue?

**Comment by mjschmidt** [comment]
I have checked this with a loadbalancer service. it still does not work which makes given the pod is the thing not passing on the network traffic to the VM on boot up

**Comment by phoracek** [comment]
We should extend the expose e2e test suite with this scenario.

@mjschmidt I'll keep you posted.

**Comment by mjschmidt** [comment]
Thank you! @phoracek

**Comment by mjschmidt** [comment]
You can't use the virtctl client for the test, virtctl client works, but direct ssh and rdp do not

**Comment by alonSadan** [comment]
Thanks @mjschmidt. I was now able to recreate the issue with my own vm: 

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-ssh
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-ssh
        special: vm-ssh
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: testmasquerade
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: testmasquerade
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/bash
            echo "fedora" | passwd fedora --stdin
```

The thing is, I tried a few times after I got `no route to host` and eventually it worked out after a minute or two:
```
[vagrant@node02 ~]$ ssh fedora@192.168.66.102 -p 30577
ssh: connect to host 192.168.66.102 port 30577: No route to host
[vagrant@node02 ~]$ ssh fedora@192.168.66.102 -p 30577
ssh: connect to host 192.168.66.102 port 30577: No route to host
[vagrant@node02 ~]$ ssh fedora@192.168.66.102 -p 30577
ssh: connect to host 192.168.66.102 port 30577: Connection refused
[vagrant@node02 ~]$ ssh fedora@192.168.66.102 -p 30577
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:lfrQgzv97Uyd+ON2SKzfj7tb46/V6vlZcKZ4XRMqH+Q.
Please contact your system administrator.
Add correct host key in /home/vagrant/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/vagrant/.ssh/known_hosts:1
ECDSA host key for [192.168.66.102]:30577 has changed and you have requested strict checking.
Host key verification failed.
[vagrant@node02 ~]$ rm -rf ~/.ssh/known_hosts 
[vagrant@node02 ~]$ ssh fedora@192.168.66.102 -p 30577
The authenticity of host '[192.168.66.102]:30577 ([192.168.66.102]:30577)' can't be established.
ECDSA key fingerprint is SHA256:lfrQgzv97Uyd+ON2SKzfj7tb46/V6vlZcKZ4XRMqH+Q.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[192.168.66.102]:30577' (ECDSA) to the list of known hosts.
fedora@192.168.66.102's password: 

```
