### ISSUE TITLE
VMI migration with dedicated CPUs nil pointer dereference

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#6432]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Migration of a VMI with dedicated CPUs fails with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1410b45]

goroutine 60 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/converter/vcpu.cpuChunksToCells(0xc0005c3a30, 0x2, 0x2, 0x0, 0xc0005c6c60, 0xf, 0x7f319057c5e0)
        pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:141 +0x145
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/converter/vcpu.newCPUPool(0xc0005c3a40, 0x0, 0xc0005c3a30, 0x2, 0x2, 0xc0005c6c01, 0x1)
        pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:115 +0xad
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/converter/vcpu.NewRelaxedCPUPool(...)
        pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:110
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/converter.Convert_v1_VirtualMachineInstance_To_api_Domain(0xc000204a00, 0xc00038b900, 0xc00024bc20, 0x0, 0x29f0501)
        pkg/virt-launcher/virtwrap/converter/converter.go:1591 +0x163d
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).prepareMigrationTarget(0xc00013ac80, 0xc000204a00, 0x0, 0xc000253340, 0xc000204a00)
        pkg/virt-launcher/virtwrap/live-migration-target.go:77 +0x212
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).PrepareMigrationTarget(0xc00013ac80, 0xc000204a00, 0xc000253300, 0x0, 0xc000253240)
        pkg/virt-launcher/virtwrap/manager.go:292 +0x3e
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server.(*Launcher).SyncMigrationTarget(0xc001a61a40, 0x1d379a0, 0xc00008f560, 0xc000253240, 0xc001a61a40, 0xc00008f560, 0xc001ac2ba0)
        pkg/virt-launcher/virtwrap/cmd-server/server.go:164 +0x8c
kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1._Cmd_SyncMigrationTarget_Handler(0x1a5ce40, 0xc001a61a40, 0x1d379a0, 0xc00008f560, 0xc00025a000, 0x0, 0x1d379a0, 0xc00008f560, 0xc0000e0000, 0x137f)
        bazel-out/k8-fastbuild/bin/pkg/handler-launcher-com/cmd/v1/kubevirt_cmd_go_proto_/kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1/cmd.pb.go:2451 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c3180, 0x1d4aa38, 0xc00027e480, 0xc000176c00, 0xc0001cd050, 0x28d8e98, 0x0, 0x0, 0x0)
        external/org_golang_google_grpc/server.go:1171 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003c3180, 0x1d4aa38, 0xc00027e480, 0xc000176c00, 0x0)
        external/org_golang_google_grpc/server.go:1494 +0xccf
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004fe4f0, 0xc0003c3180, 0x1d4aa38, 0xc00027e480, 0xc000176c00)
        external/org_golang_google_grpc/server.go:834 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        external/org_golang_google_grpc/server.go:832 +0x1fd
```

**Anything else we need to know?**:
- Following the stack trace, looks like a non-nil node topology is expected in the `cpuChunksToCells` function in the case of dedicated CPUs without numa passthrough here: https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/converter.go#L1591

- I think it is related to the latest changes to CPU pinning here: https://github.com/kubevirt/kubevirt/pull/6251

- VMI Spec: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: fedora-migratable
  name: fedora-migratable
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: fedora
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 5Gi
      source:
        pvc:
          name: fedora-container-disk
          namespace: kubevirt
  - metadata:
      creationTimestamp: null
      name: fedora-side
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 5Gi
      source:
        pvc:
          name: fedora-container-disk-2
          namespace: kubevirt
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora
    spec:
      domain:
        ioThreadsPolicy: auto
        cpu:
          cores: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        devices:
          interfaces:
            - masquerade: {}
              name: default
          disks:
          - dedicatedIOThread: true
            disk:
              bus: virtio
            name: datavolumedisk1
          - dedicatedIOThread: true
            disk:
              bus: virtio
            name: datavolumedisk2
        machine:
          type: ""
        resources:
          requests:
            memory: 1Gi
      terminationGracePeriodSeconds: 0
      networks:
        - name: default
          pod: {}
      volumes:
      - dataVolume:
          name: fedora
        name: datavolumedisk1
      - dataVolume:
          name: fedora-side
        name: datavolumedisk2
```
- To reproduce, fetch latest `main`, run `make cluster-up cluster-sync`, create the above VMI, migrate it and watch the target pod logs

/cc @rmohr @vladikr @jean-edouard 

**Environment**:
- KubeVirt version (use `virtctl version`): Latest main
