### ISSUE TITLE
Error launching VMI: the number of GPU/s do not match the number of devices

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#6459]
/kind bug
kubevirt 0.45

Copying from the gpu dp bug report:
```
I am facing below error when launching a VMI.

server error. command SyncVMI failed: "failed to creade GPU host-devices: the number of GPU/s do not match the number of devices:\nGPU: [{gpu1 nvidia.com/20b0}]\nDevice: []"

I see above error when I do "kubectl describe vmi vmi_name"

I am running a centos node with kubevirt v0.45.0 and nvidia's kubevirt-gpu-device plugin.

If i do "kubectl describe node my_node" then I do see one GPU listed as Allocatable resources.
```

Looks to be introduced by https://github.com/kubevirt/kubevirt/pull/6069.

https://github.com/NVIDIA/kubevirt-gpu-device-plugin/issues/26

**Comment by rthallisey** [comment]
@EdDev can you have a look?

**Comment by phoracek** [comment]
I don't think that Edy is too savvy of the GPU plugin. Maybe @vladikr would know?

**Comment by brianventuro** [comment]
We found a work around for this problem last night. With nvidia-device-plugin still running on the host (unsure if this is needed), enumerating all PCI IDs for GPUs required like this works:

```
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: "10DE:1EB1"
          resourceName: "nvidia.com/gpu"
          externalResourceProvider: false
```

The key was setting `externalResourceProvider` to `false`.
