### ISSUE TITLE
re-enable release update functional test for non-root test lanes. 

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#6473]
https://github.com/kubevirt/kubevirt/pull/6472 disabled the update test for non-root in order to unblock PRs. non root is still experimental, so this shouldn't be considered a release blocker.

We still need to re-enable this test `test_id:3145` quickly for non-root given how important update guarantees are.

**Comment by davidvossel** [comment]
@xpivarc is this something you can look at?

The issue here is that the non root lanes are failing our update test that tests the previous release can update to whatever is currently in a PR.

The test failure doesn't look super complicated or anything. What's failing this [line](https://github.com/kubevirt/kubevirt/blob/22827c34372f6e22cae03ab5a28692ca3f64ea1d/tests/operator_test.go#L1332) where we're waiting for a VM to hit the "Ready=True" condition. 

I tested this locally, and the update test passed fine for me. We need to figure out why waiting for those vms to hit ready when NonRoot is enabled times out for the previous version of KubeVirt when performing the update test.  The 180 second timeout period seems generous and hasn't been causing a problem in the past. 

for context, here's the actual yaml of the timed out VM
```
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  labels:
    kubevirt.io/vm: vm-v1
  name: vm-v1
  namespace: kubevirt-test-default1
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: test-dv0
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      source:
        blank: {}
  runStrategy: Manual
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-v1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk:
              bus: virtio
            name: datavolumedisk1
        machine:
          type: q35
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: test-dv0
        name: datavolumedisk1
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo:v0.45.0
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk

```
