### ISSUE TITLE
Console and VNC disconnection

### ISSUE THREAD

**Issue by eddienko** [kubevirt/kubevirt#6493]
/kind bug

**What happened**:

When connecting to a virtual image instance using either `virtctl console` or `virtual vnc` there is a websocket error almost exactly after 21s in case there is no interaction with the console. In detail, connection with:

```
./virtctl-v0.45.0-darwin-amd64 console --kubeconfig=~/.kube/config   centos
```

If then I run e.g. `top` in the console it keeps going. However when I leave the console without anything running on it and I do not type any command, it times out after 21s with the error:

```
You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF
```

In the `virt-handler` pod:

```
{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from client (virt-api) websocket","name":"centos","namespace":"kubevirt","pos":"console.go:240","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2021-09-30T19:41:54.094643Z","uid":"19c2aacd-951b-4b6f-84c2-40aedf1ffebb"}
{"component":"virt-handler","kind":"","level":"error","msg":"Error in proxing websocket and unix socket","name":"centos","namespace":"kubevirt","pos":"console.go:249","reason":"websocket: close 1006 (abnormal closure): unexpected EOF","timestamp":"2021-09-30T19:41:54.094779Z","uid":"19c2aacd-951b-4b6f-84c2-40aedf1ffebb"}
{"component":"virt-handler","level":"info","msg":"http: response.WriteHeader on hijacked connection from kubevirt.io/kubevirt/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader (response.go:220)\n","pos":"server.go:3119","timestamp":"2021-09-30T19:41:54.094890Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"error encountered reading from unix socket","name":"centos","namespace":"kubevirt","pos":"console.go:234","reason":"read unix @-\u003e/var/run/kubevirt-private/19c2aacd-951b-4b6f-84c2-40aedf1ffebb/virt-serial0: use of closed network connection","timestamp":"2021-09-30T19:41:54.094974Z","uid":"19c2aacd-951b-4b6f-84c2-40aedf1ffebb"}
```

**What you expected to happen**:

Console and VNC connections using virtctl should not disconnect.

**How to reproduce it (as minimally and precisely as possible)**:

See VMI specification below, using a generic centos cloud image (same problem with any other image).

**Environment**:
- KubeVirt version (use `virtctl version`): 0.45.0 (Darwin, linux)
- Kubernetes version (use `kubectl version`): 1.22.2
- VM or VMI specifications:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: centos
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 8096M
        cpu: 12
    devices:
      disks:
      - name: pvcdisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: disk-centos
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: centos
        chpasswd: { expire: False }
```

same with the test one provided in the docs

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 4096M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "10Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```

- OS (e.g. from /etc/os-release): RHEL 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.42.2.el7.x86_64
- Install tools: KubeVirt 0.45.0 installed using kubevirt-cr.yaml and kubevirt-operator.yaml
