### ISSUE TITLE
Operation not permitted in setting unpriv_sgio  with scsi lun

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#6507]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
If you want to use lun disk with scsi, the VM fails to start because libvirt cannot set unpriv_sgio

**How to reproduce it (as minimally and precisely as possible)**:
Start a VM with a block PVC:
```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-lun
  name: vmi-lun
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - lun:
          bus: scsi
        name: blockpvcdisk
    resources:
      requests:
        memory: 128Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/cirros-container-disk-demo:devel
    name: containerdisk
  - name: blockpvcdisk
    persistentVolumeClaim:
      claimName: pvc-test
```

Check the virt-launcher log:
```bash
$ k logs -c  compute virt-launcher-vmi-lun-dhwg5
[...]
{"component":"virt-launcher","level":"error","msg":"failed to set /sys/dev/block/251:0/queue/unpriv_sgio: Operation not permitted","pos":"virSetDeviceUnprivSGIO:1417","subcomponent":"libvirt","thread":"31","timestamp":"2021-10-04T11:00:43.570000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"vmi-lun","namespace":"default","pos":"manager.go:814","reason":"virError(Code=38, Domain=0, Message='failed to set /sys/dev/block/251:0/queue/unpriv_sgio: Operation not permitted')","timestamp":"2021-10-04T11:00:43.591709Z","uid":"b3715891-d9a6-4c47-ba98-5d28368dbea3"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vmi-lun","namespace":"default","pos":"server.go:184","reason":"virError(Code=38, Domain=0, Message='failed to set /sys/dev/block/251:0/queue/unpriv_sgio: Operation not permitted')","timestamp":"2021-10-04T11:00:43.592120Z","uid":"b3715891-d9a6-4c47-ba98-5d28368dbea3"}
[...]
```
Xml:
```xml
    <disk type='block' device='lun'>
      <driver name='qemu' type='raw' cache='none' error_policy='stop' io='native' discard='unmap'/>
      <source dev='/dev/blockpvcdisk'/>
      <target dev='sda' bus='scsi'/>
      <alias name='ua-blockpvcdisk'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>

```

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2010306

**Comment by alicefr** [comment]
For this bug, there are actually 2 distinct problems. 

First of all, sysfs is always mounted as read-only (also for privileged containers). In order to workaround this issue, it is possible to pass sysfs as an additional volume to a privileged container:
```yaml
      volumeMounts:
        - mountPath: /sys
          name: sysfs

  volumes:
    - hostPath:
        path: /sys
        type: Directory
      name: sysfs
```
We should avoid for security reasons passing sysfs as rw volume and the privileged option to the virt-launcher pod. For this reason, virt-handler should set the value when the volume uses scsi as bus.

The second problem is that libvirt always tries to write under `/sys/dev/block/<maj:min>/queue/unpriv_sgio` even if the value is already set to the correct one.  In our case, libvirt should simply check if the value is correct without trying to write.
