### ISSUE TITLE
Enable virtio graph with VNC, and related input device

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#6614]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

Continue the conversation in https://github.com/kubevirt/kubevirt/issues/3558#issuecomment-943928779

**Comment by zhlhahaha** [comment]
There is an experimental branch for this issue and it works fine. https://github.com/zhlhahaha/kubevirt/tree/virtio-gpu
In order to work with virtio-gpu the following configuration is necessary:
```
    devices:
      autoattachGraphicsDevice: true
      inputs:
      - type: tablet
        bus: virtio
        name: tablet1
      - type: keyboard
        bus: virtio
        name: keyboard1
```
We can use `virtctl vnc vmi-xxx` to connect to the server.
