### ISSUE TITLE
Connectivity issues to and from VMs when using masquerade mode

### ISSUE THREAD

**Issue by nicolacdnll** [kubevirt/kubevirt#6620]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Hi, I'm experiencing connectivity issues to and from kubevirt VMs when using an interface in `masquerade` mode.
In other words, I can't ssh into the VMs and VMs do not have connectivity to the outside (e.g., `ping 1.1.1.1` fails).

(Although I've seen that there are many open issues regarding connectivity, I've decided to open a separate issue because I'm not sure if they are related or not. Some recent and possibly related issues: https://github.com/kubevirt/kubevirt/issues/6567, https://github.com/kubevirt/kubevirt/issues/6195, and https://github.com/kubevirt/kubevirt/issues/5860)

I'm testing with two VMs, one using `cirros-container-disk-demo` and one custom VM based on `CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2`. The VMs are up and running, I can enter their consoles (`./virtctl console vmname`), I can ping them (well, the pod), but when I try to ssh to them, from the host node, I always get `ssh: connect to host <IP> port 22: Connection refused`. In both VMs port 22 is being listened to and, on centos, `sshd` is working well. Furthermore, I've also noticed that both VMs do not have connectivity to the outside!

Note that I just want to ssh from the host node itself, and not from outside the node, so I understand there is no need to use services. Although, I've tried and it doesn't work either.

```bash
$ kubectl get vmis -A
NAMESPACE   NAME       AGE   PHASE     IP               NODENAME                               READY
default     testvm     9s    Running   10.244.184.215   602381c0-6957-48c0-9c5d-0829e9c8db47   True
default     vm-rhel8   31m   Running   10.244.184.229   602381c0-6957-48c0-9c5d-0829e9c8db47   True

$ ping 10.244.184.215
PING 10.244.184.215 (10.244.184.215) 56(84) bytes of data.
64 bytes from 10.244.184.215: icmp_seq=1 ttl=64 time=0.084 ms
^C
--- 10.244.184.215 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.084/0.084/0.084/0.000 ms

$ ping 10.244.184.229
PING 10.244.184.229 (10.244.184.229) 56(84) bytes of data.
64 bytes from 10.244.184.229: icmp_seq=1 ttl=64 time=0.096 ms
^C
--- 10.244.184.229 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.096/0.096/0.096/0.000 ms

$ ssh centos@10.244.184.229
ssh: connect to host 10.244.184.229 port 22: Connection refused

$ ssh cirros@10.244.184.215
ssh: connect to host 10.244.184.215 port 22: Connection refused
```

**What you expected to happen**:
I expected to be able to ssh into the VMs and to be able to have connectivity from the VMs to the outside.

**How to reproduce it (as minimally and precisely as possible)**:
Just try to apply the VMI manifest below.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.45.0
- Kubernetes version (use `kubectl version`): v1.19.5 with Multus v3.7 and Calico. `"allow_ip_forwarding": true` is set on both CNIs.
- VM or VMI specifications: see below
- Cloud provider or hardware configuration: A VMware VM with 8 Xeon Gold 6230R cores and 8 GB of DRAM
- OS (e.g. from /etc/os-release): CentOS 7.9
- Kernel (e.g. `uname -a`): `3.10.0-1160.42.2.el7.x86_64`
- Install tools: Kubbvirt was manually installed following https://kubevirt.io/user-guide/operations/installation/#installing-kubevirt-on-kubernetes
- Others: N/A

Cirros VM:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

CentOS 8 VM:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: vm-rhel8
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-rhel8
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: vmdisks/centos8-2105:dev
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: centos
              password: centos
              ssh_pwauth: True
              chpasswd: {expire: False}
```
