### ISSUE TITLE
Windows virtual machine in kubevirt cannot use sriov's network

### ISSUE THREAD

**Issue by newhuangchuan** [kubevirt/kubevirt#6671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
I currently deploy the multus-cni, sriov-cni, sriov-network-device-plugin components in the kubernetes cluster, and currently install the virtual machine resources of Linux, the network is a cni network, the other is a sriov network, but I installed Windows After the system is installed, only one network card driver can be installed, and another network card driver is installed. There is no related driver in virtio. Do you know that sriov needs to install other drivers?
**What you expected to happen**:
Windows can also use sriov's network.
**How to reproduce it (as minimally and precisely as possible)**:
1

**Anything else we need to know?**:
no
**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.41.2", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"clean", BuildDate:"2021-07-28T16:23:53Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.2-dirty", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"dirty", BuildDate:"2021-07-28T16:57:02Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2021-04-30T03:59:16Z", GoVersion:"go1.14.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2021-04-30T05:32:18Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: hostpath
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows-static-1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-static-1
    spec:
      domain:
        cpu:
          model: host-passthrough
          sockets: 2
          cores: 4
          threads: 2
          dedicatedCpuPlacement: true
        resources: 
          requests: 
            intel.com/intel_sriov_dpdk: '1'
            memory: 8G
          limits: 
            intel.com/intel_sriov_dpdk: '1'
            memory: 8G
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces: 
          - name: default 
            bridge: {}
          - name: sriov-net1
            sriov: {}
          rng: {}
        machine:
          type: q35
      networks: 
      - name: default
        pod: {}
      - multus: 
          networkName: default/sriov-net1
        name: sriov-net1
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: windows-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd-static
      - containerDisk:
          image: kubevirt/virtio-container-disk
          imagePullPolicy: Never
        name: virtiocontainerdisk
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@ormergi  could you have a look?

**Comment by ormergi** [comment]
> The driver whose device type is vfio-pci cannot use virtio to update the driver.
@newhuangchuan maybe you need to select other device on the device-manager, and install the driver to it
check this out: https://kubevirt.io/user-guide/virtual_machines/windows_virtio_drivers/

You can also try to configure the SRIOV interface with e1000 model until you figure out how to install virtio drivers
```
spec:
  template:
    spec:
      domain:
        devices:
          interfaces: 
          - name: sriov-net1
            sriov: {}
            model: e1000    <------ 
```
