### ISSUE TITLE
Initial job after installing kubevirt-cr not adhering to nodePlacement rules

### ISSUE THREAD

**Issue by tulanian** [kubevirt/kubevirt#6764]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I have added nodePlacement rules to the kubevirt-cr.yaml  for both infra and workloads, but after applying it the first batch job that runs is scheduled on an incorrect node. This causes it to hang, so everything else that's meant to run after this job completes is stuck. If I taint the incorrect node then the install proceeds normally.
**What you expected to happen**:
All pods that run after applying  kubevirt-cr.yaml follow the nodePlacement rules.
**How to reproduce it (as minimally and precisely as possible)**:
Add this to kubevirt-cr.yaml and apply:
```
  infra:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
  workloads:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
```
Not sure what this job is meant to do but it gets stuck because it's being scheduled on a Windows node in the cluster:
`kubevirt-6e84caadc475f4101c16511f07983d103af20e72-jobtsb7wt9f7r   0/1     ImagePullBackOff   0          7m8s`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.42.1
- Kubernetes version (use `kubectl version`): v1.21.5+rke2r2
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
