### ISSUE TITLE
About the virtual machine hot plug problem

### ISSUE THREAD

**Issue by newhuangchuan** [kubevirt/kubevirt#6770]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
Hello, I am hot-plugging the disk into the virtual machine, whether it is Windows or Linux operating system, when the hot-plugged disk is recognized, it can be recognized as an unformatted empty disk.
But after I format this disk, I cannot perform `removevolume` operation on the disk.
```
$ virtctl removevolume ubuntu --volume-name=example-volume-hotplug
Error removing volume, admission webhook "virtualmachineinstances-update-validator.kubevirt.io" denied the request: Number of permanent volumes has changed
```
**What you expected to happen**:
My understanding is that hot plugging can be used to plug and unplug available disks while the virtual machine is powered on.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-volume-hotplug
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
```
```
virtctl addvolume ubuntu --volume-name=example-volume-hotplug
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
