### ISSUE TITLE
virt-operator job's pod has no parameters to specify nodeSelector 

### ISSUE THREAD

**Issue by strus38** [kubevirt/kubevirt#6813]
> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
When deploying kubevirt it does not seem possible to specify which nodes are allowed to execute the jobs.

**What you expected to happen**:
Being able to add nodeSelector parameter to execute the jobs only on specific nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with different labels for the worker nodes. The job will be executed randomly on those nodes.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by strus38** [comment]
So you mean updating the CR by adding:
```
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration: {}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  workloads:
    nodePlacement:
      nodeSelector:
        node-role/kubernetes.io/worker: worker
```

**Comment by strus38** [comment]
does not seem to work .. it is still trying to deploy the job on a worker which is not labeled this way.

**Comment by rmohr** [comment]
> @rmohr I think this about a job that is generating strategy.

Thanks, yep I missed that. So you can try:


```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration: {}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  infra:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
```
Note the `infra`. I am however not sure if it also covers this one-time job. If not I would consider it potentially an issue to fix.

**Comment by strus38** [comment]
Does not work either. Sorry :-).
![image](https://user-images.githubusercontent.com/5890515/142429093-caf290ad-6fd0-4975-ae7b-592fb3f2209f.png)

Here an exemple of the target node:
![image](https://user-images.githubusercontent.com/5890515/142429169-b530ae4f-2109-4e80-8f4e-08595d04339b.png)

**Comment by rmohr** [comment]
Yes so the `operator` itself and this one job are not affected by `infra`. Why do you need this one job to not be general schedulable?

**Comment by strus38** [comment]
That is because I have a few workers made for some purposes only. This dozer8 node is targetted to only execute jobs from another software, it is not a 'general' purpose node for the K8S core services.

**Comment by rmohr** [comment]
> That is because I have a few workers made for some purposes only. This dozer8 node is targetted to only execute jobs from another software, it is not a 'general' purpose node for the K8S core services.

Ok. The general way of ensuring that would be to give workloads from the special software a special tolerance and taint the nodes, so that other workloads do not have to deal with all exceptions. Basically flipping the ownership of the target selection. Does that make sense for you?

**Comment by rmohr** [comment]
> give workloads from the special software a special tolerance and taint the nodes

Here the documentation on how that works: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by strus38** [comment]
well, my nodes are tainted that is why I want this kubevirt job executed on specifc nodes which have this specific label.
Typically on all my service deployments, I have updated them to tell them to execute on those specifc nodes only.
Here, It does not seem to work.

**Comment by rmohr** [comment]
> well, my nodes are tainted that is why I want this kubevirt job executed on specifc nodes which have this specific label.
> Typically on all my service deployments, I have updated them to tell them to execute on those specifc nodes only.
> Here, It does not seem to work.

Ok, I think for that case we need a code change, where `infra` would take the job into account. Thanks for reporting.

**Comment by strus38** [comment]
you are welcome. I will follow up the fix and test it when available.

**Comment by johannespetereit** [comment]
/remove-lifecycle stale
 Any update on this? 
We are running a mixed OS cluster, where this issue regularly leads to issues -> when scheduled on a windows machine, kubevirt can't install correctly, as the job doesn't finish (imagepullbackoff). 
Adding taints for all windows projects would work, but be a bit much for a very specific issue...

**Comment by toelke** [comment]
/remove-lifecycle rotten

We are running into this exact issue, in our cluster all nodes are tainted to control the placement of pods+vms between certain classes of host (available hardware resources, ...).

The `--dump-install-strategy`-job is thus not able to start at all:

```
Warning  FailedScheduling  29s (x3 over 11m)  default-scheduler  0/4 nodes are available: 1 node(s) had untolerated taint {gpu-host: true}, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```

After a cursory read of #6863 I think that that PR already contains the correct solution.

**Comment by munjalpatel** [comment]
@rmohr any updates here? We are also running into this issue where jobs get scheduled on `arm64` nodes which `kubevirt` doesn't support yet. For that, we need to specify `nodeAffinity` and `toleration` for `amd64` nodes.

**Comment by rmohr** [comment]
I updated https://github.com/kubevirt/kubevirt/pull/6863 last week and @xpivarc approved but did not lgtm. I guess he will come back to it at done point. But a lot of PTOs at the moment.

**Comment by ikandars** [comment]
> /remove-lifecycle rotten
> 
> We are running into this exact issue, in our cluster all nodes are tainted to control the placement of pods+vms between certain classes of host (available hardware resources, ...).
> 
> The `--dump-install-strategy`-job is thus not able to start at all:
> 
> ```
> Warning  FailedScheduling  29s (x3 over 11m)  default-scheduler  0/4 nodes are available: 1 node(s) had untolerated taint {gpu-host: true}, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
> ```
> 
> After a cursory read of #6863 I think that that PR already contains the correct solution.

For those having issue like this one, so here my approach to fix it:

```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration: {}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
infra:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
```

The point is in part `infra.nodePlacement.nodeSelector` with value `kubernetes.io/os: linux`
