### ISSUE TITLE
cannot run memory locked vm in kubevirt

### ISSUE THREAD

**Issue by yuchen-sun** [kubevirt/kubevirt#6824]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I implemented a hook that sets hard_limit and mem locked for each virtual machine.However, I can't start the virtual machine normally and properly.
**What you expected to happen**:
Virtual machines that require memory locking to run properly
**How to reproduce it (as minimally and precisely as possible)**:
use this yaml
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-gpu
  name: vmi-gpu
  annotations:
  # Request the hook sidecar
    hooks.kubevirt.io/hookSidecars: '[{"image": "xxx/memlock-hook:v0.1"}]'
  # Overwrite base board manufacturer name
    memory.locked: "true"
spec:
  domain:
    cpu:
      sockets: 1
      cores: 16
      threads: 2
      dedicatedCpuPlacement: true
      numa:
        guestMappingPassthrough: { }
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      gpus:
      - deviceName: nvidia.com/3080ti
        name: gpu1
      - deviceName: nvidia.com/3080tisk
        name: gpu1sk
      rng: {}
    resources:
      requests:
        memory: 32Gi
    memory:
      hugepages:
        pageSize: 2Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
       image: fedora-with-test-tooling-container-disk:devel
    name: containerdisk
```

**Anything else we need to know?**:
logs
```bash
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"vmi-gpu","namespace":"default","pos":"manager.go:747","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2021-11-20T05:52:47.848233Z qemu-kvm: mlockall: Cannot allocate memory\n2021-11-20T05:52:47.848258Z qemu-kvm: locking memory failed')","timestamp":"2021-11-20T05:52:48.052879Z","uid":"011e110d-900e-4db4-ae73-f0b4075322cd"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vmi-gpu","namespace":"default","pos":"server.go:184","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2021-11-20T05:52:47.848233Z qemu-kvm: mlockall: Cannot allocate memory\n2021-11-20T05:52:47.848258Z qemu-kvm: locking memory failed')","timestamp":"2021-11-20T05:52:48.053046Z","uid":"011e110d-900e-4db4-ae73-f0b4075322cd"}
```
**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
@yuchen-sun 
Can you please explain what does this hook do?
Virt-launcher is not a privileged component, therefore, it won't be able to do things like `prlimit`.

**Comment by yuchen-sun** [comment]
> @yuchen-sun 你能解释一下这个钩子的作用吗？ Virt-launcher 不是特权组件，因此，它无法执行诸如`prlimit`.
@vladikr Thanks!
I have a GPU workload where the cuda pinned mem bandwidth is 8GB/s without mem locked, but it should actually be close to the PCIE limit (PCIE3:13, PCIE4:26).
So, I added locked to the xml in the hook, but I got an error.
```xml
<memoryBacking>
   <locked/>
</memoryBacking>
```
But if I go into the launch pod via exec, do a virsh edit vm, add the above to the xml, and reboot vm, I will get the normal cuda pinned mem bandwidth.

**Comment by vladikr** [comment]
@yuchen-sun Thanks for the details. Interesting. 
I wonder if this is not just an effect of a restart...

We are already locking the memory for any VMI that uses VFIO[1]
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/isolation/detector.go#L155

**Comment by yuchen-sun** [comment]
@vladikr thanks！
But I found that there doesn't seem to be a real lock on the memory.
![image](https://user-images.githubusercontent.com/37729051/143382411-9ab62389-3015-4d11-beaf-30b91ed46267.png)

**Comment by yuchen-sun** [comment]
@vladikr 
If the memory is already locked, then why is my memory bandwidth only normal after adding locked.

**Comment by yuchen-sun** [comment]
I have started a virtual machine with a GPU, but I noticed that it doesn't seem to lock up memory.
```yaml
spec:
  domain:
    devices:
      gpus:
      - deviceName: nvidia/3080
        name: gpu1
      - deviceName: nvidia/3080
        name: gpu2
   resources:
      requests:
        cpu: "16"
        memory: 32Gi
........
status:
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2021-11-25T07:37:52Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2021-11-25T07:37:52Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2021-11-25T07:37:57Z"
  - phase: Running
```
```bash
 cat /proc/meminfo |grep lock
Mlocked:             928 kB
```
