### ISSUE TITLE
How to pass flags to kube-api-master

### ISSUE THREAD

**Issue by stu-gott** [kubevirt/kubevirt#687]
For the implementation of https://github.com/kubevirt/kubevirt/pull/652, a change is required to core Kubernetes. Because the initializers feature of Kubernetes is still alpha, in order to use it, a flag passed to kube-apiserver is required to enable it.

```--runtime-config=admissionregistration.k8s.io/v1alpha1```

This is currently being implemented as a call to patch to edit `/etc/kubernetes/manifests/kube-apiserver.yaml` inside each vagrant node, however I believe there's a more programmatic means of passing in command line flags.

**Comment by rmohr** [comment]
@stu-gott have a look here: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-args

**Comment by stu-gott** [comment]
Thanks @rmohr. For anybody else looking into this, there is no command line flag to kubeadm to add extra arguments to the various components. The only mechanism for doing so is to provide a kubeadm config file. Command line arguments cannot be mixed in--if you switch to using a config, *all* parameters must be passed in that way.

```yaml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
apiServerExtraArgs:
  runtime-config: admissionregistration.k8s.io/v1alpha1
pod-network-cidr: 10.244.0.0/16
```
