### ISSUE TITLE
Sidecar with virt-xml to add unsupported xml options for development and testing

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#6962]
/kind enhancement

**What happens**:
From time to time people are asking how to try libvirt options not supported by KubeVirt API. The current solution is to develop an ad-hoc sidecar that sets those options. We have a tool called [virt-xm](http://manpages.ubuntu.com/manpages/xenial/man1/virt-xml.1.html)  from virt-manager that allows modifying the xml from the command line. 
I have been experimenting how to integrate `virt-xml` as sidecar (the code is available [here](https://github.com/alicefr/kubevirt-hook-virt-xml)). 

At least, I have been able to set the smbios flags and iotune values using this single sidecar. Unfortunately,  I had to modify KubeVirt because virt-xml requires to be able to talk to libvirt. I simply added the `libvirt-runtime`  volume to the sidecar. 

This is supposed to be a developer feature to avoid the need to develop your own sidecar.

Example of the VMI that uses this sidecar and set the iotune values of all the disks:
```yaml

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha2", "--args", "--disk=iotune.total_bytes_sec=52428800,iotune.total_iops_sec=1000|--edit=all"], "image":"registry:5000/kubevirt/virt-xml:latest", "imagePullPolicy": "Always"}]'
  labels:
    special: vmi-with-sidecar-hook
  name: vmi-with-sidecar-hook-2
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-with-test-tooling-container-disk:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk                        
```
Result:
```bash
$ k exec -ti virt-launcher-vmi-with-sidecar-hook-2-9b2j8 -c compute -- virsh dumpxml default_vmi-with-sidecar-hook-2
<domain type='kvm' id='1'>
  <name>default_vmi-with-sidecar-hook-2</name>
  <uuid>42582d40-f317-4c8d-bafe-d5dadefc6623</uuid>
[...]
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='disk' model='virtio-non-transitional'>
      <driver name='qemu' type='qcow2' cache='none' error_policy='stop' discard='unmap'/>
      <source file='/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2' index='2'/>
      <backingStore type='file' index='3'>
        <format type='qcow2'/>
        <source file='/var/run/kubevirt/container-disks/disk_0.img'/>
      </backingStore>
      <target dev='vda' bus='virtio'/>
      <iotune>
        <total_bytes_sec>52428800</total_bytes_sec>
        <total_iops_sec>1000</total_iops_sec>
      </iotune>
      <alias name='ua-containerdisk'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </disk>
    <disk type='file' device='disk' model='virtio-non-transitional'>
      <driver name='qemu' type='raw' cache='none' error_policy='stop' discard='unmap'/>
      <source file='/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-with-sidecar-hook-2/noCloud.iso' index='1'/>
      <backingStore/>
      <target dev='vdb' bus='virtio'/>
      <alias name='ua-cloudinitdisk'/>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </disk>
   [...]
</domain>
```
**What is missing**:
* Sharing of the libvirt-runtime volume between the compute and hook-sidecar container (trivial fix)
* Where to host the code for this sidecar
