### ISSUE TITLE
Port-forward doesn't work when interface is Bridge

### ISSUE THREAD

**Issue by candidoma** [kubevirt/kubevirt#6987]
/kind bug

**What happened**:
I Created a VM with the following yaml

```YAML
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    labels:
      vmimage: vm-test-1
      kubevirt.io/os: linux
    name: vma
    namespace: test1
  spec:
    running: true
    template:
      metadata:
        labels:
          kubevirt.io/domain: vma
      spec:
        hostname: vma
        subdomain: test1
        domain:
          cpu:
            cores: 2
          devices:
            disks:
            - disk:
                bus: sata
              name: vm-disk
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
            interfaces:
            - bridge: {}
              model: e1000e
              name: default
          machine:
            type: q35
          resources:
            limits:
              cpu: "2"
              memory: 4096M
            requests:
              cpu: "2"
              memory: 4096M
        networks:
        - name: default
          pod: {}
        volumes:
        - name: vm-disk
          persistentVolumeClaim:
            claimName: vma
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd: { expire: False }
              hostname: vma
          name: cloudinitdisk
```

I'm not able to connect using port-forward to some services running inside the VM, for example VNC or SSH.
I'm able to connect to SSH or VNC from any other pod using Service name or VM IP.

**What you expected to happen**:

Using port-forward I expect to be able to connect to the VM through ssh or vnc.
If I change the interface type from **bridge** to **masquerade**, port-forward is working well again.

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.47.1", GitCommit:"c34de42a48f5564f4fd2c21b6cbda7b96664c65b", GitTreeState:"clean", BuildDate:"2021-11-11T16:01:45Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.46.1-dirty", GitCommit:"5ed15d782ae5bfb7e1323e65defae6cc84ca8175", GitTreeState:"dirty", BuildDate:"2021-10-19T16:13:52Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
OnPrem
