### ISSUE TITLE
Multus Network, bridge over vlan, does not work as secondary interface

### ISSUE THREAD

**Issue by itmwiw** [kubevirt/kubevirt#7001]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
When I try to launch a VM with multus Network as second interface,  the VM don't start and I get the following error event:
`failed to configure vmi network: failed plugging phase1 at nic 'net1': No gateway address found in routes for net1`
**What you expected to happen**:
The VM start correctly.
**How to reproduce it (as minimally and precisely as possible)**:
I've created the following NetworkAttachmentDefinition:
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kubevirt-net-london
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "kubevirt-network",
      "capabilities": {
        "ips": true
      },
      "plugins": [
        {
          "type": "ipvlan",
          "mode": "l2",
          "master": "ens6",
                
          "ipam": {
            "type": "whereabouts",
            "range": "10.1.0.1/19",
            "exclude": [
               "10.1.0.1/30",
               "10.1.0.196/32"
            ],
            "routes": [
                { "dst": "0.0.0.0/0", "gw" : "10.1.0.1" }
            ],
            "gateway": "10.1.0.1"
          }
        }
      ]
    }
```
and the following VM:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      nodeSelector:
        reserved: multus-network
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: multus-net
            bridge: {}
        resources:
          requests:
            memory: 256M
      networks:
      - name: default
        pod: {}
      - name: multus-net
        multus: # Secondary multus network
          networkName: kubevirt/kubevirt-net-london
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

**Environment**:
- KubeVirt version : v0.41.3
- Kubernetes version (use `kubectl version`): v1.21.2
