### ISSUE TITLE
cannot ssh to vm when in masquerade mode

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#7006]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Can not ssh to vm when the vm in masquerade mode.
And the VM cannot access the Internet and cannot connect to the node.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootfs
            - disk: {}
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
              ports:
                - port: 22
        machine:
          type: q35
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
      networks:
        - name: default
          pod: {}
```
But I got the result is:
```sh
ssh root@192.168.80.4
ssh: connect to host 192.168.80.4 port 22: Connection refused
```

**Anything else we need to know?**:
This problem exists with both the kube-ovn and calico network CNI plugin.

On the same network CNI plugin, when I dropped the kubevirt version down to 0.36.0, it worked and the above problem disappeared

**Environment**:
- KubeVirt version (use `virtctl version`): v0.44.1+
- Kubernetes version (use `kubectl version`): v1.21.4
- VM or VMI specifications: as above
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):3.10.0
- Install tools:
- Others:
   The same problem exists in version `kubevirt v0.48.x`

**Comment by zhhray** [comment]
Is it a bug in 0.44.1 version of kubevirt?
Is it the same issue with this issue? https://github.com/kubevirt/kubevirt/issues/6620

**Comment by zhhray** [comment]
This problem persists when kubevirt is upgraded to the latest version.
Can anyone answer this question?
@rmohr

**Comment by rmohr** [comment]
@zhhray can you verify that other pods can reach the internet, and in addition, can you try connecting to the vm via `virtctl console` (serial console) or `virtctl vnc` (remote desktop) and check its network setup? Maybe it does not run `dhcp` by default?

**Comment by zhhray** [comment]
> @zhhray can you verify that other pods can reach the internet, and in addition, can you try connecting to the vm via `virtctl console` (serial console) or `virtctl vnc` (remote desktop) and check its network setup? Maybe it does not run `dhcp` by default?

I can reach the internet and nodes in virt-launcher Pod. But I can’t in VM when I connect to the vm via `virtctl vnc`.
Ping the IP address of the node in the VM, the source IP address is 10.0.0.2, which is a private NAT network address.
I think the source IP address should be the IP address of the Virt-Launcher Pod. 
So  I guess that, the code of virt-Launcher Pod is having problems configuring the network for the VM.

**Comment by zhhray** [comment]
Is there any key information or log that I can provide?

**Comment by maiqueb** [comment]
I'm interested in the VMI status (just making sure you're sshing to the correct address). Can you show us the interface status of the VM ? 
`kubectl get vmi <vm name> -ojsonpath="{ @.status.interfaces }"` 

Also, does the issue persist if your VMI spec does not feature the list of allowed ports ? (i.e. drop the `ports` key from the interface spec portion).

**Comment by rhrazdil** [comment]
Hello @zhhray, this does seem to be the same issue as described here: https://github.com/kubevirt/kubevirt/issues/6620

Could you please provides us with the virt-handler logs (collected from the virt-handler pod that runs on the same node as your VM is scheduled on) and NAT table as described in this comment? https://github.com/kubevirt/kubevirt/issues/6620#issuecomment-1008942320

**Comment by zhhray** [comment]
> I'm interested in the VMI status (just making sure you're sshing to the correct address). Can you show us the interface status of the VM ? `kubectl get vmi <vm name> -ojsonpath="{ @.status.interfaces }"`
> 
> Also, does the issue persist if your VMI spec does not feature the list of allowed ports ? (i.e. drop the `ports` key from the interface spec portion).

1. Firstly, the interfaces of vmi status are:
```sh
kubectl get vmi -n kubevirt-test natcentos -o yaml -ojsonpath="{ @.status.interfaces }"
[{"interfaceName":"eth0","ipAddress":"192.168.80.193","ipAddresses":["192.168.80.193"],"mac":"02:73:44:00:00:01","name":"default"}]
```
2.Secondly,I modified my YAML content as follows:
```yaml
spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootfs
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
```
But the problems mentioned above still exist.

**Comment by zhhray** [comment]
> Hello @zhhray, this does seem to be the same issue as described here: #6620
> 
> Could you please provides us with the virt-handler logs (collected from the virt-handler pod that runs on the same node as your VM is scheduled on) and NAT table as described in this comment? [#6620 (comment)](https://github.com/kubevirt/kubevirt/issues/6620#issuecomment-1008942320)

THX.
```sh
ssh to the node where the VM is running
Run $ docker ps or $ crictl ps and finc the container ID for a virt-launcher pod
Run $ docker inspect <the container ID> | grep pid to get the PID of the virt-launcher process
Run $ sudo nsenter -t <PID> -n
Run nft list table nat
```
The result is :
```sh
nft list table nat
table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100; policy accept;
		iifname "eth0" counter packets 0 bytes 0 jump KUBEVIRT_PREINBOUND
	}

	chain input {
		type nat hook input priority 100; policy accept;
	}

	chain output {
		type nat hook output priority -100; policy accept;
		ip daddr { 127.0.0.1 } counter packets 0 bytes 0 dnat to 10.0.2.2
	}

	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		ip saddr 10.0.2.2 counter packets 0 bytes 0 masquerade
		oifname "k6t-eth0" counter packets 0 bytes 0 jump KUBEVIRT_POSTINBOUND
	}

	chain KUBEVIRT_PREINBOUND {
		counter packets 0 bytes 0 dnat to 10.0.2.2
	}

	chain KUBEVIRT_POSTINBOUND {
		ip saddr { 127.0.0.1 } counter packets 0 bytes 0 snat to 10.0.2.1
	}
}
```

**Comment by zhhray** [comment]
By the way, my configuration in Kubevirt's CR is already like this. However, the startup argument `-v` of all virt-xxx components still has a value of `2`. I killed all pods in kubevirt namespace.But it didn't work.
```yaml
 spec:
    configuration:
      developerConfiguration:
        logVerbosity:
          virtAPI: 4
          virtController: 4
          virtHandler: 4
          virtLauncher: 4
          virtOperator: 4
```
I looked through virt-handler's logs and didn't get any valuable error messages.
