### ISSUE TITLE
Incorrect operation of the device plugin

### ISSUE THREAD

**Issue by D1abloRUS** [kubevirt/kubevirt#7012]
/kind bug

**What happened**:

I added several host devices:
```yaml
permittedHostDevices:
  pciHostDevices:
      - externalResourceProvider: false
        pciVendorSelector: 11NE:1E07
        resourceName: test.com/test
      - externalResourceProvider: false
        pciVendorSelector: 11NE:1E04
        resourceName: test.com/test
```

These are the same devices, but they have a different device id. But in the capaicty of the node, I see only one of them, not the sum.

```yaml
Capacity:
  cpu:                            128
  devices.kubevirt.io/kvm:        1k
  devices.kubevirt.io/tun:        1k
  devices.kubevirt.io/vhost-net:  1k
  ephemeral-storage:              818537984Ki
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         528184312Ki
  test.com/test:                  1
  pods:                           110
```

**What you expected to happen**:

In order for the device plugin to group different device IDs into one device

**How to reproduce it (as minimally and precisely as possible)**:

Create different devices with the same resourceName

**Anything else we need to know?**:

**Environment**: dev
- KubeVirt version (use `virtctl version`): 0.47.1
- Kubernetes version (use `kubectl version`): 1.19.7
- VM or VMI specifications:
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release):  `18.04.4 LTS (Bionic Beaver)`
- Kernel (e.g. `uname -a`): `Linux node3 5.10.81-051081-generic #202111211333 SMP Sun Nov 21 14:43:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:
