### ISSUE TITLE
Some questions about the docs and code

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt#704]
hi, I'm a new team member of cnv-qe, also a part-time reviewer/maintainer of kubernetes  : )

I took a look of the kubevirt code and docs briefly yesterday and have three questions here: 

1. about VMs, do we currently have a load balancer mechanism for VMs ?  just like service vs pod in kubernetes cluster.

2. about virt-launcher: it used for provide the cgroups and namespaces for launching VMs, but here's the situation, what if a node which a pod being scheduled on it is not having enough resource to launching VMs, is that a problem ? do we having some mechanism to make sure every pod being scheduled is also eligible to launch a VMs on it's hosted node ? is that controlled by the filed of this part in vm definition file?
```
spec:
  terminationGracePeriodSeconds: 0
  domain:
    resources:
      requests:
        memory: 64M
``` 

3. about virt-dhcp do we have any docs about that part ? 

@fabiand @rmohr @vladikr thanks!!

/kind question
