### ISSUE TITLE
virtctl: error DataVolume.storage spec is missing accessMode and volumeMode

### ISSUE THREAD

**Issue by ikandars** [kubevirt/kubevirt#7078]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Found this following error when creating DV:

```bash
datavolume-controller  DataVolume.storage spec is missing accessMode and volumeMode
```

**What you expected to happen**:

DataVolume cirros created

**How to reproduce it (as minimally and precisely as possible)**:

When I run this following command in virtctl version v0.47.1:

```bash
virtctl -n testing image-upload dv cirros --size=300Mi --image-path=./cirros-0.4.0-x86_64-disk.img --uploadproxy-url=https://127.0.0.1:31001 --insecure
```

The DataVolume fail to create with following error:

```bash
kubectl -n testing describe dv cirros

Events:
  Type     Reason            Age                  From                   Message
  ----     ------            ----                 ----                   -------
  Warning  ErrClaimNotValid  24s (x16 over 3m8s)  datavolume-controller  DataVolume.storage spec is missing accessMode and volumeMode, cannot get access mode from StorageProfile longhorn
```

But everything works fine if I use virtctl version v0.42.1

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

```bash
virtctl version
Client Version: version.Info{GitVersion:"v0.47.1", GitCommit:"c34de42a48f5564f4fd2c21b6cbda7b96664c65b", GitTreeState:"clean", BuildDate:"2021-11-11T16:01:45Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.49.0", GitCommit:"f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3", GitTreeState:"clean", BuildDate:"2022-01-11T17:37:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):

```bash
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rmohr** [comment]
@mhenriks can you have a look at this one?

Maybe specific to longhorn. @vasiliy-ul thinks that maybe setting some defaults in CDI can help if some defaults are not set on a storage provider.

/triage accepted

**Comment by brybacki** [comment]
I suppose it is happening because of change introduced to virtclt: "virtctl imageupload now uses DataVolume.spec.storage"
https://github.com/kubevirt/kubevirt/pull/6367

I need to check if maybe some kind of handling the defaults was lost and if we can fix it.

**Comment by brybacki** [comment]
Previously virtctl used `ReadWriteOnce` if accessMode was not specified. But now, as we want to use possibilities provided by StorageProfiles, it does not set accessMode. 

If StorageProfile has it, we have much better PVC. If StorageProfile does not have accessMode we end up with the `  Warning  ErrClaimNotValid  24s (x16 over 3m8s)  datavolume-controller  DataVolume.storage spec is missing accessMode and volumeMode, cannot get access mode from StorageProfile longhorn`.

**Comment by vasiliy-ul** [comment]
I had a similar issue. fixed that using:
```yaml
kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
EOF

# Patch local storage profile with default accessModes
kubectl patch --type merge -p '{"spec": {"claimPropertySets": [{"accessModes": ["ReadWriteOnce"]}]}}' StorageProfile local
```
