### ISSUE TITLE
Update the devices of an already started device plugin

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#7084]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
If you change the per pciHostDevices in KubeVirt CR of an already started device plugin, the plugin is not update with the current list without the need of restarting virt-handler

**What you expected to happen**:
Be able to modify the pciHostDevices in KubeVirt CR and see the update in the node description

**How to reproduce it (as minimally and precisely as possible)**:
Add two devices in KubeVirt CR:
```yaml
  configuration:
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: 8086:2415
        resourceName: test.com/test
      - pciVendorSelector: 8086:2668
        resourceName: test.com/test
```
Check node description:
```
$ k describe no node01
[...]
Capacity:

  test.com/test:                  2
Allocatable:

  test.com/test:                  2
```
Then remove one device from the CR and recheck the node description:
```bash
$ k describe no node01
[...]
Capacity:

  test.com/test:                  2
Allocatable:

  test.com/test:                  2
```
The current workaround is to restart virt-handler of the node where you want the update:
```bash
k delete po -n kubevirt virt-handler-h76nj
pod "virt-handler-h76nj" deleted
# After a while
$ k describe no node01
[..]
Capacity:
..
  test.com/test:                  1
Allocatable:
...
  test.com/test:                  1

```
