### ISSUE TITLE
Nvidia vGPU failed on Windows 10, driver error code 12: The device cannot find enough free resources that it can use.

### ISSUE THREAD

**Issue by mokarage** [kubevirt/kubevirt#7109]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
I am trying to create a windows 10 vm with the following config:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows10-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows10-iso
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          gpus:
          - deviceName: nvidia.com/GRID_M10-0Q
            name: vgpu1
          disks:
          - bootOrder: 1
            cdrom:
              bus: virtio
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk

          rng: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}

        machine:
          type: ""
        resources:
          requests:
            memory: 8Gi
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: upload-win10-dv
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd0
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
I am using latest nvidia kubevirt gpu device plugin (v1.1.0) and following kubevirt-cr.yml:
```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    mediatedDevicesConfiguration:
      mediatedDevicesTypes:
        - nvidia-36
    permittedHostDevices:
      mediatedDevices:
      - mdevNameSelector: "GRID M10-0Q"
        resourceName: "nvidia.com/GRID_M10-0Q"
        externalResourceProvider: true

    developerConfiguration:
      featureGates: 
        - GPU
        - DataVolumes
        - HostDevices
        - CPUManager
        - HostDisk
        - ExperimentalVirtiofsSupport
        - CPUNodeDiscovery
        - HypervStrictCheck
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```
after starting vm and installing windows 10 & nvidia display drivers, in windows 10 vm device manager under Display adapters I get Code 12 for my `GRID M10-0Q` device. 
here is my virt-launcher logs:
```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:74","timestamp":"2022-01-19T10:17:27.371783Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:77","timestamp":"2022-01-19T10:17:27.371855Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:495","timestamp":"2022-01-19T10:17:27.373786Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:503","timestamp":"2022-01-19T10:17:27.375932Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 7.6.0, package: 6.el8s (CBS \u003ccbs@centos.org\u003e, 2021-10-29-15:04:36, )","subcomponent":"libvirt","thread":"63","timestamp":"2022-01-19T10:17:27.394000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: windows10-iso","subcomponent":"libvirt","thread":"63","timestamp":"2022-01-19T10:17:27.394000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2749","subcomponent":"libvirt","thread":"63","timestamp":"2022-01-19T10:17:27.394000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:511","timestamp":"2022-01-19T10:17:27.877679Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:507","timestamp":"2022-01-19T10:17:27.883038Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:80","timestamp":"2022-01-19T10:17:27.883298Z"}
{"component":"virt-launcher","level":"warning","msg":"PCI_RESOURCE_NVIDIA_COM_GRID_M10-0Q not set for resource nvidia.com/GRID_M10-0Q","pos":"addresspool.go:50","timestamp":"2022-01-19T10:17:30.151129Z"}
{"component":"virt-launcher","level":"info","msg":"host-device created: 7af80cb2-f8a2-4d19-a06d-2dad024c272e","pos":"hostdev.go:83","timestamp":"2022-01-19T10:17:30.151171Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"windows10-iso","namespace":"kubevirt","pos":"manager.go:454","timestamp":"2022-01-19T10:17:30.151667Z","uid":"481bd28c-be44-4b17-98cf-869b39e37de6"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"windows10-iso","namespace":"kubevirt","pos":"manager.go:475","timestamp":"2022-01-19T10:17:30.151693Z","uid":"481bd28c-be44-4b17-98cf-869b39e37de6"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n+\u0000\n","pos":"network.go:274","timestamp":"2022-01-19T10:17:30.152554Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf:","pos":"network.go:275","timestamp":"2022-01-19T10:17:30.152579Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"server.go:64","timestamp":"2022-01-19T10:17:30.152643Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-private/vmi-disks/cdromiso/disk.img set to none","pos":"converter.go:423","timestamp":"2022-01-19T10:17:30.160774Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-private/vmi-disks/harddrive/disk.img set to none","pos":"converter.go:423","timestamp":"2022-01-19T10:17:30.165527Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-ephemeral-disks/disk-data/virtiocontainerdisk/disk.qcow2 set to none","pos":"converter.go:423","timestamp":"2022-01-19T10:17:30.169244Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain XML generated. Base64 dump PGRvbWFpbiB0eXBlPSJrdm0iIHhtbG5zOnFlbXU9Imh0dHA6Ly9saWJ2aXJ0Lm9yZy9zY2hlbWFzL2RvbWFpbi9xZW11LzEuMCI+Cgk8bmFtZT5rdWJldmlydF93aW5kb3dzMTAtaXNvPC9uYW1lPgoJPG1lbW9yeSB1bml0PSJiIj4yMTQ3NDgzNjQ4MDwvbWVtb3J5PgoJPG9zPgoJCTx0eXBlIGFyY2g9Ing4Nl82NCIgbWFjaGluZT0icTM1Ij5odm08L3R5cGU+CgkJPHNtYmlvcyBtb2RlPSJzeXNpbmZvIj48L3NtYmlvcz4KCTwvb3M+Cgk8c3lzaW5mbyB0eXBlPSJzbWJpb3MiPgoJCTxzeXN0ZW0+CgkJCTxlbnRyeSBuYW1lPSJ1dWlkIj5hNzVhOGQyNy03MWY3LTVmNzQtYWQ5YS1jZTA0ODEwNjJlYzg8L2VudHJ5PgoJCQk8ZW50cnkgbmFtZT0ibWFudWZhY3R1cmVyIj5LdWJlVmlydDwvZW50cnk+CgkJCTxlbnRyeSBuYW1lPSJmYW1pbHkiPkt1YmVWaXJ0PC9lbnRyeT4KCQkJPGVudHJ5IG5hbWU9InByb2R1Y3QiPk5vbmU8L2VudHJ5PgoJCQk8ZW50cnkgbmFtZT0ic2t1Ij48L2VudHJ5PgoJCQk8ZW50cnkgbmFtZT0idmVyc2lvbiI+PC9lbnRyeT4KCQk8L3N5c3RlbT4KCQk8Ymlvcz48L2Jpb3M+CgkJPGJhc2VCb2FyZD48L2Jhc2VCb2FyZD4KCQk8Y2hhc3Npcz48L2NoYXNzaXM+Cgk8L3N5c2luZm8+Cgk8ZGV2aWNlcz4KCQk8aW50ZXJmYWNlIHR5cGU9ImV0aGVybmV0Ij4KCQkJPHNvdXJjZT48L3NvdXJjZT4KCQkJPHRhcmdldCBkZXY9InRhcDAiIG1hbmFnZWQ9Im5vIj48L3RhcmdldD4KCQkJPG1vZGVsIHR5cGU9InZpcnRpby1ub24tdHJhbnNpdGlvbmFsIj48L21vZGVsPgoJCQk8bWFjIGFkZHJlc3M9IjNhOjE0OmI1OjIzOmVkOjdjIj48L21hYz4KCQkJPG10dSBzaXplPSIxNDUwIj48L210dT4KCQkJPGFsaWFzIG5hbWU9InVhLWRlZmF1bHQiPjwvYWxpYXM+CgkJCTxyb20gZW5hYmxlZD0ibm8iPjwvcm9tPgoJCTwvaW50ZXJmYWNlPgoJCTxjaGFubmVsIHR5cGU9InVuaXgiPgoJCQk8dGFyZ2V0IG5hbWU9Im9yZy5xZW11Lmd1ZXN0X2FnZW50LjAiIHR5cGU9InZpcnRpbyI+PC90YXJnZXQ+CgkJPC9jaGFubmVsPgoJCTxob3N0ZGV2IHR5cGU9Im1kZXYiIG1hbmFnZWQ9IiIgbW9kZT0ic3Vic3lzdGVtIiBtb2RlbD0idmZpby1wY2kiIGRpc3BsYXk9Im9uIiByYW1mYj0ib24iPgoJCQk8c291cmNlPgoJCQkJPGFkZHJlc3MgdHlwZT0iIiBidXM9IiIgdXVpZD0iN2FmODBjYjItZjhhMi00ZDE5LWEwNmQtMmRhZDAyNGMyNzJlIj48L2FkZHJlc3M+CgkJCTwvc291cmNlPgoJCQk8YWxpYXMgbmFtZT0idWEtZ3B1LXZncHUxIj48L2FsaWFzPgoJCTwvaG9zdGRldj4KCQk8Y29udHJvbGxlciB0eXBlPSJ1c2IiIGluZGV4PSIwIiBtb2RlbD0ibm9uZSI+PC9jb250cm9sbGVyPgoJCTxjb250cm9sbGVyIHR5cGU9InNjc2kiIGluZGV4PSIwIiBtb2RlbD0idmlydGlvLW5vbi10cmFuc2l0aW9uYWwiPjwvY29udHJvbGxlcj4KCQk8Y29udHJvbGxlciB0eXBlPSJ2aXJ0aW8tc2VyaWFsIiBpbmRleD0iMCIgbW9kZWw9InZpcnRpby1ub24tdHJhbnNpdGlvbmFsIj48L2NvbnRyb2xsZXI+CgkJPHZpZGVvPgoJCQk8bW9kZWwgdHlwZT0idmdhIiBoZWFkcz0iMSIgdnJhbT0iMTYzODQiPjwvbW9kZWw+CgkJPC92aWRlbz4KCQk8Z3JhcGhpY3MgdHlwZT0idm5jIj4KCQkJPGxpc3RlbiB0eXBlPSJzb2NrZXQiIHNvY2tldD0iL3Zhci9ydW4va3ViZXZpcnQtcHJpdmF0ZS80ODFiZDI4Yy1iZTQ0LTRiMTctOThjZi04NjliMzllMzdkZTYvdmlydC12bmMiPjwvbGlzdGVuPgoJCTwvZ3JhcGhpY3M+CgkJPG1lbWJhbGxvb24gbW9kZWw9InZpcnRpby1ub24tdHJhbnNpdGlvbmFsIj4KCQkJPHN0YXRzIHBlcmlvZD0iMTAiPjwvc3RhdHM+CgkJPC9tZW1iYWxsb29uPgoJCTxkaXNrIGRldmljZT0iY2Ryb20iIHR5cGU9ImZpbGUiPgoJCQk8c291cmNlIGZpbGU9Ii92YXIvcnVuL2t1YmV2aXJ0LXByaXZhdGUvdm1pLWRpc2tzL2Nkcm9taXNvL2Rpc2suaW1nIj48L3NvdXJjZT4KCQkJPHRhcmdldCBidXM9InNhdGEiIGRldj0ic2RhIiB0cmF5PSJjbG9zZWQiPjwvdGFyZ2V0PgoJCQk8ZHJpdmVyIGNhY2hlPSJub25lIiBlcnJvcl9wb2xpY3k9InN0b3AiIG5hbWU9InFlbXUiIHR5cGU9InJhdyI+PC9kcml2ZXI+CgkJCTxyZWFkb25seT48L3JlYWRvbmx5PgoJCQk8YWxpYXMgbmFtZT0idWEtY2Ryb21pc28iPjwvYWxpYXM+CgkJCTxib290IG9yZGVyPSIxIj48L2Jvb3Q+CgkJPC9kaXNrPgoJCTxkaXNrIGRldmljZT0iZGlzayIgdHlwZT0iZmlsZSI+CgkJCTxzb3VyY2UgZmlsZT0iL3Zhci9ydW4va3ViZXZpcnQtcHJpdmF0ZS92bWktZGlza3MvaGFyZGRyaXZlL2Rpc2suaW1nIj48L3NvdXJjZT4KCQkJPHRhcmdldCBidXM9InNhdGEiIGRldj0ic2RiIj48L3RhcmdldD4KCQkJPGRyaXZlciBjYWNoZT0ibm9uZSIgZXJyb3JfcG9saWN5PSJzdG9wIiBuYW1lPSJxZW11IiB0eXBlPSJyYXciIGRpc2NhcmQ9InVubWFwIj48L2RyaXZlcj4KCQkJPGFsaWFzIG5hbWU9InVhLWhhcmRkcml2ZSI+PC9hbGlhcz4KCQkJPGJvb3Qgb3JkZXI9IjIiPjwvYm9vdD4KCQkJPGZpbGVzeXN0ZW1PdmVyaGVhZD4wLjA1NTwvZmlsZXN5c3RlbU92ZXJoZWFkPgoJCQk8Y2FwYWNpdHk+CgkJCQk8Rm9ybWF0PkJpbmFyeVNJPC9Gb3JtYXQ+CgkJCTwvY2FwYWNpdHk+CgkJPC9kaXNrPgoJCTxkaXNrIGRldmljZT0iY2Ryb20iIHR5cGU9ImZpbGUiPgoJCQk8c291cmNlIGZpbGU9Ii92YXIvcnVuL2t1YmV2aXJ0LWVwaGVtZXJhbC1kaXNrcy9kaXNrLWRhdGEvdmlydGlvY29udGFpbmVyZGlzay9kaXNrLnFjb3cyIj48L3NvdXJjZT4KCQkJPHRhcmdldCBidXM9InNhdGEiIGRldj0ic2RjIiB0cmF5PSJjbG9zZWQiPjwvdGFyZ2V0PgoJCQk8ZHJpdmVyIGNhY2hlPSJub25lIiBlcnJvcl9wb2xpY3k9InN0b3AiIG5hbWU9InFlbXUiIHR5cGU9InFjb3cyIiBkaXNjYXJkPSJ1bm1hcCI+PC9kcml2ZXI+CgkJCTxyZWFkb25seT48L3JlYWRvbmx5PgoJCQk8YWxpYXMgbmFtZT0idWEtdmlydGlvY29udGFpbmVyZGlzayI+PC9hbGlhcz4KCQkJPGJhY2tpbmdTdG9yZSB0eXBlPSJmaWxlIj4KCQkJCTxmb3JtYXQgdHlwZT0icmF3Ij48L2Zvcm1hdD4KCQkJCTxzb3VyY2UgZmlsZT0iL3Zhci9ydW4va3ViZXZpcnQvY29udGFpbmVyLWRpc2tzL2Rpc2tfMi5pbWciPjwvc291cmNlPgoJCQk8L2JhY2tpbmdTdG9yZT4KCQk8L2Rpc2s+CgkJPHNlcmlhbCB0eXBlPSJ1bml4Ij4KCQkJPHRhcmdldCBwb3J0PSIwIj48L3RhcmdldD4KCQkJPHNvdXJjZSBtb2RlPSJiaW5kIiBwYXRoPSIvdmFyL3J1bi9rdWJldmlydC1wcml2YXRlLzQ4MWJkMjhjLWJlNDQtNGIxNy05OGNmLTg2OWIzOWUzN2RlNi92aXJ0LXNlcmlhbDAiPjwvc291cmNlPgoJCTwvc2VyaWFsPgoJCTxjb25zb2xlIHR5cGU9InB0eSI+CgkJCTx0YXJnZXQgdHlwZT0ic2VyaWFsIiBwb3J0PSIwIj48L3RhcmdldD4KCQk8L2NvbnNvbGU+CgkJPHJuZyBtb2RlbD0idmlydGlvLW5vbi10cmFuc2l0aW9uYWwiPgoJCQk8YmFja2VuZCBtb2RlbD0icmFuZG9tIj4vZGV2L3VyYW5kb208L2JhY2tlbmQ+CgkJPC9ybmc+Cgk8L2RldmljZXM+Cgk8Y2xvY2sgb2Zmc2V0PSJ1dGMiIGFkanVzdG1lbnQ9InJlc2V0Ij4KCQk8dGltZXIgbmFtZT0icnRjIiB0aWNrcG9saWN5PSJjYXRjaHVwIiBwcmVzZW50PSJ5ZXMiPjwvdGltZXI+CgkJPHRpbWVyIG5hbWU9InBpdCIgdGlja3BvbGljeT0iZGVsYXkiIHByZXNlbnQ9InllcyI+PC90aW1lcj4KCQk8dGltZXIgbmFtZT0iaHBldCIgcHJlc2VudD0ibm8iPjwvdGltZXI+CgkJPHRpbWVyIG5hbWU9Imh5cGVydmNsb2NrIiBwcmVzZW50PSJ5ZXMiPjwvdGltZXI+Cgk8L2Nsb2NrPgoJPG1ldGFkYXRhPgoJCTxrdWJldmlydCB4bWxucz0iaHR0cDovL2t1YmV2aXJ0LmlvIj4KCQkJPHVpZD40ODFiZDI4Yy1iZTQ0LTRiMTctOThjZi04NjliMzllMzdkZTY8L3VpZD4KCQkJPGdyYWNlcGVyaW9kPgoJCQkJPGRlbGV0aW9uR3JhY2VQZXJpb2RTZWNvbmRzPjMwPC9kZWxldGlvbkdyYWNlUGVyaW9kU2Vjb25kcz4KCQkJPC9ncmFjZXBlcmlvZD4KCQk8L2t1YmV2aXJ0PgoJPC9tZXRhZGF0YT4KCTxmZWF0dXJlcz4KCQk8YWNwaT48L2FjcGk+CgkJPGFwaWM+PC9hcGljPgoJCTxoeXBlcnY+CgkJCTxyZWxheGVkIHN0YXRlPSJvbiI+PC9yZWxheGVkPgoJCQk8dmFwaWMgc3RhdGU9Im9uIj48L3ZhcGljPgoJCQk8c3BpbmxvY2tzIHN0YXRlPSJvbiIgcmV0cmllcz0iODE5MSI+PC9zcGlubG9ja3M+CgkJPC9oeXBlcnY+CgkJPGt2bT4KCQkJPGhpZGRlbiBzdGF0ZT0ib24iPjwvaGlkZGVuPgoJCTwva3ZtPgoJPC9mZWF0dXJlcz4KCTxjcHUgbW9kZT0iaG9zdC1tb2RlbCI+CgkJPHRvcG9sb2d5IHNvY2tldHM9IjEiIGNvcmVzPSI4IiB0aHJlYWRzPSIxIj48L3RvcG9sb2d5PgoJPC9jcHU+Cgk8dmNwdSBwbGFjZW1lbnQ9InN0YXRpYyI+ODwvdmNwdT4KCTxpb3RocmVhZHM+MTwvaW90aHJlYWRzPgo8L2RvbWFpbj4=","name":"windows10-iso","namespace":"kubevirt","pos":"libvirt_helper.go:126","timestamp":"2022-01-19T10:17:30.173884Z","uid":"481bd28c-be44-4b17-98cf-869b39e37de6"}
{"component":"virt-launcher","level":"info","msg":"Reaped pid 88 with status 0","pos":"virt-launcher.go:549","timestamp":"2022-01-19T10:17:30.238087Z"}
{"component":"virt-launcher","level":"info","msg":"Reaped pid 90 with status 9","pos":"virt-launcher.go:549","timestamp":"2022-01-19T10:17:30.351723Z"}
{"component":"virt-launcher","level":"info","msg":"Reaped pid 96 with status 0","pos":"virt-launcher.go:549","timestamp":"2022-01-19T10:17:30.372084Z"}
{"component":"virt-launcher","level":"info","msg":"Reaped pid 98 with status 9","pos":"virt-launcher.go:549","timestamp":"2022-01-19T10:17:30.405846Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain defined.","name":"windows10-iso","namespace":"kubevirt","pos":"manager.go:807","timestamp":"2022-01-19T10:17:30.448197Z","uid":"481bd28c-be44-4b17-98cf-869b39e37de6"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 0 received","pos":"client.go:433","timestamp":"2022-01-19T10:17:30.448442Z"}
{"component":"virt-launcher","level":"error","msg":"At least one cgroup controller is required: No such device or address","pos":"virCgroupDetectControllers:455","subcomponent":"libvirt","thread":"49","timestamp":"2022-01-19T10:17:30.463000Z"}
```
**What you expected to happen**:
successfully install nvidia driver and use vgpu on windows10 vm.
**How to reproduce it (as minimally and precisely as possible)**:
upload windows 10 enterprise image iso using datavolume and apply the aforementioned manifests.

**Anything else we need to know?**:
I tried the same procedure for ubuntu 20.04 and I was able to successfully use vgpu.
**Environment**:
- KubeVirt version (use `virtctl version`):  0.48.1
- Kubernetes version (use `kubectl version`): 1.21.7
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): OpenSUSE Leap 15.3 
- Kernel (e.g. `uname -a`): 5.3.18
- Install tools:
- Others:

**Comment by vladikr** [comment]
Hi, 

Thanks for raising this issue.

Making this specific vGPU work properly on Windows 10 is largely depending on the compatibility of the NVIDIA grid driver on the host and the guest driver as well as NVIDIAs' licensing of using this device on Windows.

From what you are describing I don't see any specific issue with either with KubeVirt, nor with the device plugin, you are using. (especially if this device works on other OS)

I'm curious, have you tried using a different mdev type (for example GRID M10-1Q)?
Also, could you please mention what version of the nvidia host / guest drivers are you using?

Thanks

/cc @rthallisey 
/cc @vasiliy-ul

**Comment by mokarage** [comment]
I must also add that I'm using the exact mdev type on ESXi and it's working.

**Comment by mokarage** [comment]
I managed to fix this by disabling `autoattachGraphicsDevice` and `virtualGPUOptions` after installing NVIDIA Display Drivers:
```yaml
devices:
    autoattachGraphicsDevice: false
    # adding gpu device will disable vnc access
    gpus:
    - deviceName: nvidia.com/GRID_M10-0Q
    name: vgpu1
    virtualGPUOptions:
        display:
        enabled: false
        ramFB: 
            enabled: false
```
