### ISSUE TITLE
Make Kubevirt network model selectable

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt#718]
according to comments here: https://github.com/kubevirt/demo/issues/34#issuecomment-363328856

cc @fabiand 

# API
```yaml
kind: VM
spec:
  devices:
    interfaces:
      # Today, only one source: default
      # This issue is about intorducing the API to specify the NIC model
      - name: nic-ip
        model: e1000
```

# Future API considerations
Furtehr down the road the bigger picture would be alogn the lines:

```yaml
kind: VM
spec:
  devices:
    interfaces:
      # In the next iteration it's about the ability to specify the source (once we have multiple sources)
      - name: nic-ip
        model: e1000
        source:
          default:
            bind: ip  # we have this today

      # #787 is about this mode
      - name: nic-ports
        model: e1000
        source:
          default:
            bind: ports  # #787 is about this mode
        ports:  # only needed in 'ports' mode
        - port: 42
          protocol: tcp (optional)
          name: foo (optional)

        # @phoracek is working on additional nics
        # IDEA: Example for resource based nic (not part of this PR)
        - name: nic-resource
          source:
            resource: bridge.k6t.io/mybr0  ## mode for selecting which resource use
```
