### ISSUE TITLE
[Feature Request]How to use VGPU in VirtualMachineInstanceReplicaSet

### ISSUE THREAD

**Issue by wonleing** [kubevirt/kubevirt#7202]
I want to assign different VGPU to each VMI Replicas. So we can make sure each VMI Replicas has strong graphic process ability.
Can we do that with some similar yaml like following?
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: testreplicaset
spec:
  replicas: 10
  selector:
    matchLabels:
      myvmi: myvmi
  template:
    metadata:
      name: test
      labels:
        myvmi: myvmi
    spec:
      domain:
        devices:
          gpu:
          - pool: myvgpupool
          disks:
          - disk:
            name: myvolume
        resources:
          requests:
            memory: 4Gi
```
