### ISSUE TITLE
Support disk without volumes

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#725]
Sometimes a VM needs a disk without a volume, i.e. CD drivers:

```yaml
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: rhel72
spec:
    devices:
      disks:
      - name: disk-1
        disk:
          bus: virtio
        volumeName: volume-1
      - name: disk-2   # HERE
        cdrom:
          bus: ide
  volumes:
    - name: volume-1
      persistentVolumeClaim:
        name: rhel72-disk-1
```

Do we want to support this?
