### ISSUE TITLE
User name & password not working with RHCOS

### ISSUE THREAD

**Issue by cloudcafetech** [kubevirt/kubevirt#7317]
I have download Image for RHCOS from **https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-metal.x86_64.raw.gz** using CDI.

Then added following userdata in VM manfest.

```
          userData: |
            #cloud-config
            hostname: k8s-worker
            user: root
            password: passwd
            chpasswd: { expire: False }
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3......
```

I m getting console login and provided above user (root) & password (passwd) but **its not working.**

If I do ```ssh root@10.244.1.16```

I got 

**Permission denied (publickey,gssapi-keyex,gssapi-with-mic).**

Do I need anything to be added in VM manifest ?
