### ISSUE TITLE
cpuAllocationRatio does not take effect

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#7334]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
I configured the value of cpuAllocationRatio in kubevirt CR, but it does not take effect.
```yaml
kind: KubeVirt
metadata:
    name: kubevirt-kubevirt-hyperconverged
    namespace: kubevirt
spec:
    certificateRotateStrategy:
      selfSigned:
        ca:
          duration: 87600h0m0s
          renewBefore: 720h0m0s
        server:
          duration: 87600h0m0s
          renewBefore: 720h0m0s
    configuration:
      developerConfiguration:
        cpuAllocationRatio: 4
        diskVerification:
          memoryLimit: 2G
        featureGates:
        - DataVolumes
        - SRIOV
        - CPUManager
        - CPUNodeDiscovery
        - Snapshot
        - HotplugVolumes
        - ExpandDisks
        - GPU
        - HostDevices
        - DownwardMetrics
        - NUMA
        - WithHostModelCPU
        - HypervStrictCheck
        - SRIOVLiveMigration
      migrations:
        completionTimeoutPerGiB: 800
        parallelMigrationsPerCluster: 5
        parallelOutboundMigrationsPerNode: 2
        progressTimeout: 150
      network:
        defaultNetworkInterface: masquerade
      obsoleteCPUModels:
        "486": true
        Conroe: true
        athlon: true
        core2duo: true
        coreduo: true
        kvm32: true
        kvm64: true
        n270: true
        pentium: true
        pentium2: true
        pentium3: true
        pentiumpro: true
        phenom: true
        qemu32: true
        qemu64: true
      selinuxLauncherType: virt_launcher.process
      smbios:
        family: KubeVirt
        manufacturer: KubeVirt
        product: None
    customizeComponents: {}
    infra:
      replicas: 1
    uninstallStrategy: BlockUninstallIfWorkloadsExist
    workloadUpdateStrategy:
      batchEvictionInterval: 1m0s
      batchEvictionSize: 10
      workloadUpdateMethods:
      - LiveMigrate
```
Then I create the virtual machine, as defined in YAML：
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm
  namespace: test-ns
spec:
  template:
    spec:
      domain:
        cpu:
          cores: 12
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
```
And then , the configuration you see in vmi looks like this:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: test-vm
  namespace: test-ns
spec:
  domain:
    cpu:
      cores: 12
      sockets: 1
      threads: 1
      model: host-model
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
```
However, the resource.cpu value of the virt-launcher pod is always 1000m.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: virt-launcher-test-vm-cnzxg
  namespace: test-ns
spec:
  containers:
  - name: compute
    resources:
      limits:
        cpu: "1"
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        memory: 2222Mi
      requests:
        cpu: "1"
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        ephemeral-storage: 50M
        memory: 2222Mi
```
But I think, according to Kubevirt's code logic, pod cpu request value should be 12/4=3?
Here is code https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go#L883

**What happened**:

cpuAllocationRatio does not take effect

**What you expected to happen**:

cpuAllocationRatio take effect

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.48.1
- Kubernetes version (use `kubectl version`):  v1.22.3
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhhray** [comment]
> ```yaml
> cpuAllocationRatio: 4
> ```
I mean that, if cpuAllocationRatio is 4, the request cpu of resource of virt-launcher pod shoud be 3, but not 1.
Not sure if this is a bug, or is the configuration incorrect somewhere？

**Comment by dhiller** [comment]
Sounds legit.

/triage accepted

@xpivarc I am not sure who might be able to look into this, can you tell?

**Comment by xpivarc** [comment]
@dhiller 
I can have a look :)

**Comment by zhhray** [comment]
> @dhiller I can have a look :)
Thank you for taking the time to look at this.
By the way, my Kubevirt was installed into the K8S cluster by the HCO operator（https://github.com/kubevirt/hyperconverged-cluster-operator）

**Comment by zhhray** [comment]
> Hi @zhhray, I couldn't reproduce the issue. I see you are using HCO. Can it be that HCO reconciled the Kubevirt object to previous state?

Thanks very much for your reply.
Once again, I only deployed kubevirt and cdi operators, not hco, but the cpuAllocationRatio was still not in effect in my environment.
Can you describe your reproduce steps to me? I want to know the difference between your operation and mine.
In particular, VirtualMachine YAML and virt-launcher pod YAML.

**Comment by zhhray** [comment]
I found the reason because I set limitrange on my namespace.
vmi.spec.domain.resources is set to the value of limitrange default. The virt-launcher pod cpu value calculated from the `cpuAllocationRatio` is overridden.
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: test-ns
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 1000m
      memory: 1000Mi
    max:
      cpu: "8"
      memory: 16000Mi
    type: Container
```
But I don't think it makes sense. When I set up a `cpuAllocationRatio` should ignore the value of `vmi.spec.domain.resources.cpu`.

**Comment by xpivarc** [comment]
I think we can distinguish when a user requested cpu request and when the `LimitRange` was applied. In the latter case, I would say that `cpuAllocationRatio` should override the `LimitRange`. What do you think?

**Comment by zhhray** [comment]
> I think we can distinguish when a user requested cpu request and when the `LimitRange` was applied. In the latter case, I would say that `cpuAllocationRatio` should override the `LimitRange`. What do you think?

Yes, but I think it makes more sense.
Regardless of `LimitRange` or user requested CPU request, as long as the `cpuAllocationRatio` is set, the virt-launcher pod CPU should be set according to the value calculated by the cpuAllocationRatio.
Not only evaluate request to (float64(vcpus) / float64(cpuAllocationRatio)), but also set limit to (vcpus). It is generally risky for a pod not to set its limit in K8S.

For the example above, the cpu resources for virt-launcher pod should look like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: virt-launcher-test-vm-cnzxg
  namespace: test-ns
spec:
  containers:
  - name: compute
    resources:
      limits:
        cpu: "12"
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        memory: 2222Mi
      requests:
        cpu: "3"
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        ephemeral-storage: 50M
        memory: 2222Mi
```
