### ISSUE TITLE
coreos-installer not installing on /dev/vda found busy partitions

### ISSUE THREAD

**Issue by cloudcafetech** [kubevirt/kubevirt#7365]
My goal is setting up OCP 4.9 on top of Kubernetes using Kubevirt VMs. So target is **Nested Kubernetes [Kubernetes  (Openshift) in Kubernetes]**

Base K8S Cluster build using kubeadm with Flannel along with Multus NW on AWS EC2 and Persistent Storatge (kubevirt.io/hostpath-provisioner)

- Master (t2.medium) Ubuntu 18.4 
- Node (c5.metal) Ubuntu 18.4,  where all Kubevirt VMs deployed.

**Created 6 Kubevirt VMs (Bootstrap, Master1, Master2, Master3, Worker1 & Worker2) using RHOCS image (quay.io/containerdisks/rhcos:4.9) using CDI.**

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: coreos
  name: coreos
spec:
  dataVolumeTemplates:
  - metadata:
      name: coreos-dv
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hostpath-storage
      source:
        registry:
          url: "docker://quay.io/containerdisks/rhcos:4.9"
          pullMethod: node # [(Not node name) node pullMode uses host cache for container images]
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: coreos
    spec:
      dnsConfig:
        nameservers:
        - 10.244.1.215
        - 10.96.0.10
        - 8.8.8.8
        searches:
        - cloudcafe.in
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      hostname: coreos
      dnsPolicy: None
      nodeSelector:
        kubernetes.io/hostname: node
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: dv
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            bridge: {}
          - name: eth2
            bridge: {}
        resources:
          requests:
            memory: 16G
            cpu: "8000m"
      networks:
      - name: default
        pod: {}
      - name: eth2
        multus:
          networkName: default/coreos-eth2
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: coreos-dv
        name: dv
      - cloudInitConfigDrive:
          userData: |
            {
              "ignition": {
                "config": {},
                "proxy": {},
                "security": {},
                "timeouts": {},
                "version": "3.2.0"
              },
              "passwd": {
                "users": [
                  {
                    "name": "coreos",
                    "sshAuthorizedKeys": [
                      "ssh-rsa PUBLIC_SSH_KEY"
                    ]
                  }
                ]
              },
              "storage": {},
              "systemd": {
                "units": [
                  {
                    "dropins": [
                      {
                        "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure`\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\n",
                        "name": "autologin-core.conf"
                      }
                    ],
                    "name": "serial-getty@ttyS0.service"
                  }
                ]
              }
            }
          networkData: |
            {
              "version": 2,
              "ethernets": {
                "enp1s0": {
                  "dhcp4": true
                },
                "enp2s0": {
                 "dhcp4": true
                }
              }
            }
        name: cloudinitdisk
```

**Created 1 Kubevirt VMs (Jumhost) using CentOS image (quay.io/containerdisks/centos:8.4) using CDI, this **jumphost** used for (DNS, DHCP, HAPROXY, Webserver), VM yaml close to similar as above.**

When executing below command in **bootstrap** host...

```sudo coreos-installer install /dev/vda --insecure --image-url http://10.244.1.215:8080/ocp4/rhcos  --ignition-url http://10.244.1.215:8080/ocp4/bootstrap.ign --insecure-ignition```

Getting following error ..

```
Partitions in use on /dev/vda:
    /dev/vda3 mounted on /boot
    /dev/vda4 mounted on /sysroot
Error: checking for exclusive access to /dev/vda

Caused by:
    found busy partitions
```

- bootstrap lsblk command

```
$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0 94.5G  0 disk
|-vda1 252:1    0    1M  0 part
|-vda2 252:2    0  127M  0 part
|-vda3 252:3    0  384M  0 part /boot
`-vda4 252:4    0   94G  0 part /sysroot
vdb    252:16   0    1M  0 disk
```

**Not sure what I am missing ?**

**Comment by alicefr** [comment]
@cloudcafetech why do you want to execute `coreos-installer` on the bootstrap node? Coreos should be already installed or do you want to prepare a custom image? I'm missing this part

**Comment by cloudcafetech** [comment]
>why do you want to execute coreos-installer on the bootstrap node?

That is as per openshift cluster installation procedure.

**Comment by cloudcafetech** [comment]
Same way we used to install in normal VMs.

https://www.linuxtechi.com/install-openshift-baremetal-upi/

Mentioned in above URL Step4

**Comment by alicefr** [comment]
could you please point me to the documentation of the installation procedure you want to use? Is it the user provisioned? Because for me, you already have installed coreos on the boostrap node and it is normal that it is failing in opening `/dev/vda`.

**Comment by cloudcafetech** [comment]
>Is it the user provisioned

Yes

https://www.linuxtechi.com/install-openshift-baremetal-upi/

Mentioned in above URL Step4

**Comment by alicefr** [comment]
Ok, you want to run coreos live installation and this is not what is happening in your example. The installation has already occurred and firstboot and ignition has already been configured. The proof is that you have already installed the ssh key

**Comment by cloudcafetech** [comment]
Correct, I also little bit understood but not sure how to mitigate this issue.

**Comment by cloudcafetech** [comment]
>But what you need is a configuration that uses rhcos as ISO and starts a live installation on a PVC :).

It's a long process, same I have to do for all 6 Kubevirt VMs (Bootstrap, Master1, Master2, Master3, Worker1 & Worker2). 🤔

**Comment by alicefr** [comment]
yes, maybe you could pass the already generate ignition files to each VMs and have some kind of automatic installation.

**Comment by cloudcafetech** [comment]
>yes, maybe you could pass the already generate ignition files to each VMs and have some kind of automatic installation.

That is also not possible bcoz it's a one time job.

Challenge is if I restart VMI, that will again execute. 🙄

**Comment by alicefr** [comment]
are you sure that it will execute again? Because after the firstboot the /boot/ignition.firstboot file should be disappeared and ignition should not run again. Are you on slack :)?

**Comment by cloudcafetech** [comment]
>are you sure that it will execute again?

Yes, if you put it in ```userdata``` of VM yaml.

>Are you on slack :)?

No

**Comment by alicefr** [comment]
I just tried and you can remove the userdata from the VM definition. So, once rhcos has been installed you could patch the VM and remove the userdata definition

**Comment by cloudcafetech** [comment]
Can you share what you did.

Is it using image or ISO.

**Comment by alicefr** [comment]
I used the container disk and I simply edit the VM definition with `kubectl edit VM <vm-name>` are removed the userdata but you can also patch it

**Comment by cloudcafetech** [comment]
Okay, but for my original issue I can't use container image.

**Comment by cloudcafetech** [comment]
@alicefr 

I tried with ISO image but same issue **busy partition**

![image](https://user-images.githubusercontent.com/68260844/158324153-501ab57b-dc29-4022-bed1-5921114e2b6f.png)

**Comment by alicefr** [comment]
@cloudcafetech I don't think you can install the OS on the same device as the ISO. You need a second disk

**Comment by cloudcafetech** [comment]
@alicefr 

> I don't think you can install the OS on the same device as the ISO. You need a second disk

what is alternative? I can add second disk but after that lets say I have installed in second disk then how to boot from there?

**Comment by alicefr** [comment]
My understanding is that you need to boot from rhcos image and install it on a device and reboot from that device. I never install RHCOS on KubeVirt but this is the usual way you do the installation for UPI. Coreos installer cannot overwrite the /dev/vda because is in use. Maybe there is an in place installation

**Comment by cloudcafetech** [comment]
@alicefr 

I did installed on 2nd hdd using modify the VM yaml

-  bootstrap.yaml

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: bootstrap
  name: bootstrap
spec:
  dataVolumeTemplates:
  - metadata:
      name: bootstrap-iso
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hostpath-storage
      source:
        http:
          #url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/rhcos-live.x86_64.iso"
          url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/latest/rhcos-live.x86_64.iso"
  - metadata:
      name: bootstrap-hdd
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 90Gi
        storageClassName: hostpath-storage
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: bootstrap
    spec:
      dnsConfig:
        nameservers:
        - 10.244.1.215
        - 10.96.0.10
        - 8.8.8.8
        searches:
        - cloudcafe.in
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      hostname: bootstrap
      dnsPolicy: None
      nodeSelector:
        kubernetes.io/hostname: node
      domain:
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: cloudinitdisk
          interfaces:
          - name: default
            bridge: {}
          - name: eth2
            bridge: {}
        resources:
          requests:
            memory: 16G
            cpu: "8000m"
      networks:
      - name: default
        pod: {}
      - name: eth2
        multus:
          networkName: default/bootstrap-eth2
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: bootstrap-iso
        name: cdromiso
      - dataVolume:
          name: bootstrap-hdd
        name: harddrive
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: cloudinitdisk
```

But little confuse what is below boot order does ? from **cdromiso** or **harddrive**.

```
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
```

**Comment by cloudcafetech** [comment]
if you want I can do live session, let me know ?

**Comment by alicefr** [comment]
Did you use the same yaml? I think you need to remove ignition and the cdrom when you reboot

**Comment by alicefr** [comment]
Maybe you could have 2 VM yamls. One for the installation with the cdrom and the other for the post-installation with a VM that simply use the second hdd.

**Comment by cloudcafetech** [comment]
can u help to prepare 2nd vm yaml (post installation).

**1st yaml** below

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: bootstrap
  name: bootstrap
spec:
  dataVolumeTemplates:
  - metadata:
      name: bootstrap-iso
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hostpath-storage
      source:
        http:
          #url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/rhcos-live.x86_64.iso"
          url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/latest/rhcos-live.x86_64.iso"
  - metadata:
      name: bootstrap-hdd
      annotations:
        kubevirt.io/provisionOnNode: node
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 90Gi
        storageClassName: hostpath-storage
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: bootstrap
    spec:
      dnsConfig:
        nameservers:
        - 10.244.1.215
        - 10.96.0.10
        - 8.8.8.8
        searches:
        - cloudcafe.in
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      hostname: bootstrap
      dnsPolicy: None
      nodeSelector:
        kubernetes.io/hostname: node
      domain:
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: cloudinitdisk
          interfaces:
          - name: default
            bridge: {}
          - name: eth2
            bridge: {}
        resources:
          requests:
            memory: 16G
            cpu: "8000m"
      networks:
      - name: default
        pod: {}
      - name: eth2
        multus:
          networkName: default/bootstrap-eth2
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: bootstrap-iso
        name: cdromiso
      - dataVolume:
          name: bootstrap-hdd
        name: harddrive
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: cloudinitdisk
```

**Comment by cloudcafetech** [comment]
Help me to boot from harddrive

**Comment by alicefr** [comment]
OK, I got some clean example with 2 VM.
First of all, you need to create a PVC that is the target where rhcos will be install and I used a blank DV:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhcos-dv
spec:
  source:
      blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
```
After, you need to start a temporary VM that install on `/dev/vdb` rhcos. Here, what I used:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhcos-dv
spec:
  source:
      blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
[afrosi@fedora rhcost-install-kubevirt]$ cat vm-installation.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-installation 
  name: vm-installation
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-installation
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: installer
          - disk:
              bus: virtio
            name: target-dv
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 2G
            cpu: "2000m"
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/rhcos:4.9
          name: installer
        - dataVolume:
            name: rhcos-dv
          name: target-dv
        - cloudInitConfigDrive:
            userData: |
              {
                "ignition": {
                  "version": "3.3.0"
                },
                "systemd": {
                  "units": [
                    {
                      "dropins": [
                        {
                          "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure`\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\n",
                          "name": "autologin-core.conf"
                        }
                      ],
                      "name": "serial-getty@ttyS0.service"
                    }
                  ]
                }
              }
          name: cloudinitdisk
```
I access the console of the VM:
```bash
$ virtctl console vm-install
$ [core@vm-installation ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0   16G  0 disk 
|-vda1 252:1    0    1M  0 part 
|-vda2 252:2    0  127M  0 part 
|-vda3 252:3    0  384M  0 part /boot
`-vda4 252:4    0 15.5G  0 part /sysroot
vdb    252:16   0 17.2G  0 disk 
vdc    252:32   0    1M  0 disk 
$ sudo coreos-installer install /dev/vdb
```
Once, the installation is successful you need to delete the first VM but the datavolume persist. You can now boot from this datavolume. Like:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-rhcos 
  name: vm-rhcos
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-rhcos
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: dv
        resources:
          requests:
            memory: 2G
            cpu: "2000m"
      volumes:
        - dataVolume:
            name: rhcos-dv
          name: dv
```
