### ISSUE TITLE
Question: Is there a way to deploy just enough to expose /dev/kvm to containers?

### ISSUE THREAD

**Issue by fadams** [kubevirt/kubevirt#7504]
For context my _real_ use case is a requirement to deploy existing containers that launch VMs and the main prerequisite is access to `/dev/kvm` from the container (they also use `/dev/net/tun` but that works just using a volume mount).

I came across this: https://github.com/kubevirt/kubevirt/issues/1276 and used that as the basis of an experiment:
```
apiVersion: v1
kind: Pod
metadata:
  name: kvm-and-tun-consumer
spec:
  containers:
  - name: alpine
    image: alpine:3.5
    command: ["/bin/sleep", "36000"]
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
    volumeMounts:
    - mountPath: /dev/net/tun
      name: dev-tun
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: false
  volumes:
  - hostPath:
      path: /dev/net/tun
      type: CharDevice
    name: dev-tun
```
I deployed the kubevirt-operator.yaml and kubevirt-cr.yaml following the quickstart instructions

After I got over my initial issues with AppArmor and finally got KubeVirt deployed I was able to deploy the yaml above and successfully `kubectl exec` to the Pod then install and launch qemu
```
apk add --update qemu-system-x86_64 bzip2 wget
wget http://mirrors.us.softlayer.com/coreos/stable/2135.5.0/coreos_production_qemu_image.img.bz2
bzip2 -d coreos_production_qemu_image.img.bz2
qemu-system-x86_64 -m 1024 -enable-kvm -hda coreos_production_qemu_image.img -nographic
```
That all looks pretty promising for my needs.

But as I say all I _really_ need is the kvm device and as nice as KubeVirt is for being able to integrate traditional/legacy virtualised workloads I don't really need all of the features, so my question really is whether there is a way to deploy "just enough" to expose the kvm device to my containers to be usable in a similar way to the Pod definition above?

In issue 1276 that I cribbed for this it mentions "The device manager of virt-handler creates a device plugin for both `/dev/kvm` and `/dev/net/tun`." which suggests that (maybe) just the virt-handler Daemon Set is the minimal thing needed to expose `/dev/kvm` as above.

TBH I have no familiarity with the KubeVirt code and wouldn't know where to begin, so I was hoping for some expert pointers.... I had come across the kvm device plugin in the kubernetes-device-plugins subdirectory https://github.com/kubevirt/kubernetes-device-plugins/blob/master/docs/README.kvm.md however although that is logically a very close fit to what I actually want to achieve that is marked as archived so I was hoping to be able to achieve the same based on the main KubeVirt images as that feels maybe like a more "sustainable" approach.

MTIA
