### ISSUE TITLE
ipAddress in the vmi.status.interfaces was lost when the vm was first created and started

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#7508]
**What happened**:
ipAddress in the vmi.status.interfaces was lost when the vm was first created and started.

vmi status yaml at first like this
```yaml
  interfaces:
  - infoSource: domain
    ipAddress: 10.8.0.2
    ipAddresses:
    - 10.8.0.2
    mac: 00:00:00:2f:e1:b1
    name: default
```
But after a while, this is going to look like this
```yaml
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    mac: 00:00:00:2f:e1:b1
    name: default
```
And then after a long time get change to this:
```yaml
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    ipAddress: 10.8.0.2
    ipAddresses:
    - 10.8.0.2
    - fe80::200:ff:fe2f:e1b1
    mac: 00:00:00:2f:e1:b1
    name: default
```

**What you expected to happen**:
The ipAddress  do not lost while updating information about the interfaces.

**How to reproduce it (as minimally and precisely as possible)**:
Create a vm, with bridge mode network.
The yaml is:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: vm-ip-miss
  namespace: virt-ns
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: vm-ip-miss-rootfs
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: metal-rbd
          volumeMode: Block
        source:
          registry:
            url: docker://registry.init.cn/vmdisks/centos:7.9
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootfs
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: vm-ip-miss-rootfs
          name: rootfs
        - cloudInitNoCloud:
            networkData: |-
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
          name: cloudinitdisk

```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.51.0
- Kubernetes version (use `kubectl version`): v1.22.7
- VM or VMI specifications: 
vmi spec yaml:
```yaml
spec:
    domain:
      cpu:
        cores: 1
        model: host-model
        sockets: 1
        threads: 1
      devices:
        disks:
        - disk:
            bus: virtio
          name: rootfs
        - disk:
            bus: virtio
          name: cloudinitdisk
        interfaces:
        - bridge: {}
          name: default
      features:
        acpi:
          enabled: true
      firmware:
        uuid: b38fa4d7-d81b-5bd7-a2f3-01f1a920a43f
      machine:
        type: q35
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
    networks:
    - name: default
      pod: {}
    volumes:
    - dataVolume:
        name: vm-ip-miss-rootfs
      name: rootfs
    - cloudInitNoCloud:
        networkData: |-
          network:
            version: 1
            config:
              - type: physical
                name: eth0
                subnets:
                  - type: dhcp
              - type: physical
                name: enp1s0
                subnets:
                  - type: dhcp
      name: cloudinitdisk
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by zhhray** [comment]
Use `kubectl get vmi vm-ip-miss -n virt-ns -w -o yaml` to capture the content of the first startup after the creation of virtual machine.
Notice the part of yaml that marks # miss
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
status:
  activePods:
    a581741f-5a9f-4dfd-be14-8e374c23f1ca: 192.168.80.80
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T07:17:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC vm-ip-slow-rootfs is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentVersionNotSupported
  guestOSInfo: {}
  interfaces:
  - infoSource: domain
    ipAddress: 10.8.0.2
    ipAddresses:
    - 10.8.0.2
    mac: 00:00:00:2f:e1:b1
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.51.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 192.168.80.80
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-04-01T07:17:17Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-04-01T07:17:20Z"
  qosClass: Guaranteed
  virtualMachineRevisionName: revision-start-vm-3270ba94-513e-4473-a441-ec37913e6215-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0"
      preallocated: true
      requests:
        storage: 20Gi
      volumeMode: Block
    target: vda
---
# miss
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
status:
  activePods:
    a581741f-5a9f-4dfd-be14-8e374c23f1ca: 192.168.80.80
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T07:17:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC vm-ip-slow-rootfs is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentVersionNotSupported
  guestOSInfo: {}
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    mac: 00:00:00:2f:e1:b1
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.51.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 192.168.80.80
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-04-01T07:17:17Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-04-01T07:17:20Z"
  qosClass: Guaranteed
  virtualMachineRevisionName: revision-start-vm-3270ba94-513e-4473-a441-ec37913e6215-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0"
      preallocated: true
      requests:
        storage: 20Gi
      volumeMode: Block
    target: vda
---
# miss
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
status:
  activePods:
    a581741f-5a9f-4dfd-be14-8e374c23f1ca: 192.168.80.80
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T07:17:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC vm-ip-slow-rootfs is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentVersionNotSupported
  guestOSInfo:
    id: centos
    kernelRelease: 3.10.0-1160.11.1.el7.x86_64
    kernelVersion: '#1 SMP Fri Dec 18 16:34:56 UTC 2020'
    name: CentOS Linux
    prettyName: CentOS Linux 7 (Core)
    version: "7"
    versionId: "7"
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    mac: 00:00:00:2f:e1:b1
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.51.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 192.168.80.80
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-04-01T07:17:17Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-04-01T07:17:20Z"
  qosClass: Guaranteed
  virtualMachineRevisionName: revision-start-vm-3270ba94-513e-4473-a441-ec37913e6215-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0"
      preallocated: true
      requests:
        storage: 20Gi
      volumeMode: Block
    target: vda
---
# miss
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
status:
  activePods:
    a581741f-5a9f-4dfd-be14-8e374c23f1ca: 192.168.80.80
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T07:17:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC vm-ip-slow-rootfs is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  guestOSInfo:
    id: centos
    kernelRelease: 3.10.0-1160.11.1.el7.x86_64
    kernelVersion: '#1 SMP Fri Dec 18 16:34:56 UTC 2020'
    name: CentOS Linux
    prettyName: CentOS Linux 7 (Core)
    version: "7"
    versionId: "7"
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    mac: 00:00:00:2f:e1:b1
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.51.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 192.168.80.80
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-04-01T07:17:17Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-04-01T07:17:20Z"
  qosClass: Guaranteed
  virtualMachineRevisionName: revision-start-vm-3270ba94-513e-4473-a441-ec37913e6215-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0"
      preallocated: true
      requests:
        storage: 20Gi
      volumeMode: Block
    target: vda
---
kind: VirtualMachineInstance
status:
  activePods:
    a581741f-5a9f-4dfd-be14-8e374c23f1ca: 192.168.80.80
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-01T07:17:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC vm-ip-slow-rootfs is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: "2022-04-01T07:19:19Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  guestOSInfo:
    id: centos
    kernelRelease: 3.10.0-1160.11.1.el7.x86_64
    kernelVersion: '#1 SMP Fri Dec 18 16:34:56 UTC 2020'
    name: CentOS Linux
    prettyName: CentOS Linux 7 (Core)
    version: "7"
    versionId: "7"
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    ipAddress: 10.8.0.2
    ipAddresses:
    - 10.8.0.2
    - fe80::200:ff:fe2f:e1b1
    mac: 00:00:00:2f:e1:b1
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.51.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 192.168.80.80
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-04-01T07:17:05Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-04-01T07:17:17Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-04-01T07:17:20Z"
  qosClass: Guaranteed
  virtualMachineRevisionName: revision-start-vm-3270ba94-513e-4473-a441-ec37913e6215-1
  volumeStatus:
  - name: cloudinitdisk
    size: 1048576
    target: vdb
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0"
      preallocated: true
      requests:
        storage: 20Gi
      volumeMode: Block
    target: vda
```

**Comment by mzzgaopeng** [comment]
we also met

**Comment by EdDev** [comment]
The `infoSource` hints what is happening here.

> vmi status yaml at first like this
> 
> ```yaml
>   interfaces:
>   - infoSource: domain
>     ipAddress: 10.8.0.2
>     ipAddresses:
>     - 10.8.0.2
>     mac: 00:00:00:2f:e1:b1
>     name: default
> ```

The information is based on the pod & domain (as seen by libvirt). The IP is the one assigned to the pod.

> 
> But after a while, this is going to look like this
> 
> ```yaml
>   interfaces:
>   - infoSource: domain, guest-agent
>     interfaceName: eth0
>     mac: 00:00:00:2f:e1:b1
>     name: default
> ```

This info comes also from the guest-agent, which is what is seen in the guest itself and is more accurate. It overrides data seen previous on the pod.
It means that no IP was yet to be set in the guest.

> 
> And then after a long time get change to this:
> 
> ```yaml
>   interfaces:
>   - infoSource: domain, guest-agent
>     interfaceName: eth0
>     ipAddress: 10.8.0.2
>     ipAddresses:
>     - 10.8.0.2
>     - fe80::200:ff:fe2f:e1b1
>     mac: 00:00:00:2f:e1:b1
>     name: default
> ```

It should not take too long, but it is dependent on the guest itself.

The time until you are expected to see the IP is usually partially spent on waiting for the dhcp kicking in (from boot) and a refresh of the status (on the vmi).

Hope this helps.

**Comment by mzzgaopeng** [comment]
> 
When we use the bridge network mode, this problem occurs, but by printing the corresponding log file

```go
func executeAgentCommands(commands []AgentCommand, con cli.Connection, agentStore *AsyncAgentStore, domainName string) {
	for _, command := range commands {
		// replace with direct call to libvirt function when 5.6.0 is available
		cmdResult, err := con.QemuAgentCommand(`{"execute":"`+string(command)+`"}`, domainName)
		if err != nil {
			// skip the command on error, it is not vital
			continue
		}

		// parse the json data and convert to domain api
		// for libvirt 5.6.0 json conversion deprecated
		switch command {
		case GET_INTERFACES:
			interfaces, err := parseInterfaces(cmdResult)
			if err != nil {
				log.Log.Errorf("Cannot parse guest agent interface %s", err.Error())
			}
			agentStore.Store(GET_INTERFACES, interfaces)
			log.Log.Infof("interface is : %s", interfaces) // this log to debug "qemu-guest-agent print"
```

Through the printed log, the qemu-guest-agent is obtained normally, and the problem is that the vmi is not updated (rsynced vmi)
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/22125180/162560630-dd830ab0-159e-43af-80d6-0c207b29bceb.png">

Under normal circumstances, there will be rsynced vmi for each acquisition

**Comment by EdDev** [comment]
@mzzgaopeng , I have hard time to understand what you are trying to say here.
The Guest Agent is reporting interfaces without IP/s first. When an IP is assigned (dynamically I suspect), it reports it as well.
After some time, it will be propagated to virt-launcher and from there to virt-handler which will then post it on the api-server (i.e. the VMI object).
This is what I meant by:
> ... and a refresh of the status (on the vmi).

If you think something is not as expected, please elaborate and explain what you expect to happen and why.

**Comment by zhhray** [comment]
There are obvious problems here. Just like @mzzgaopeng said above.
>
> This info comes also from the guest-agent, which is what is seen in the guest itself and is more accurate. It overrides data   seen previous on the pod.
> It means that no IP was yet to be set in the guest.

```yaml
  interfaces:
  - infoSource: domain, guest-agent
    interfaceName: eth0
    mac: 00:00:00:2f:e1:b1
    name: default
```
The value of `vmi.status.interfaces` should not be like this. Because at this point, executing this command in pod will obviously get the IP address of the network interface of the VM.
```bash
virsh qemu-agent-command 1 '{"execute":"guest-network-get-interfaces"}'
```

And what should not be that in bridge mode, the vmi has displayed the pod IP, but when the qemu-agent updates it, it has discarded the displayed IP. I think the IP address should at least be retained?

**Comment by EdDev** [comment]
> @EdDev There are obvious problems here.

I claim there is no problem, it is behaving as expected.

> Just like @mzzgaopeng said above. The value of `vmi.status.interfaces` should not be like this. Because at this point, executing this command in pod will obviously get the IP address of the network interface of the VM.
> 
> ```shell
> virsh qemu-agent-command 1 '{"execute":"guest-network-get-interfaces"}'
> ```

You are pointing out that the exposed status in the VMI status is not updated immediately.
kubevirt is refreshing the information at a reasonable rate, it will not do so every second.

If I am not mistaken, [this](https://github.com/kubevirt/kubevirt/blob/901ccb61047077616bbbda445b8ba148f7f7b8b9/cmd/virt-launcher/virt-launcher.go#L339) is the refresh rate once it stabilized (it starts at [10sec](https://github.com/kubevirt/kubevirt/blob/901ccb61047077616bbbda445b8ba148f7f7b8b9/pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go#L50) and increases exponentially to that stable value).

And all the above is only the refresh of virt-launcher accessing the guest-agent, there is also the feedback to virt-handler which eventually will write to the api-server.
The bottom line is, you should not expect this information to be real-time.
But if you want to shorten the feedback loop, you can launch the virt-launcher with shorter refresh rates based on your discretion.

> 
> And what should not be that in bridge mode, the vmi has displayed the pod IP, but when the qemu-agent updates it, it has discarded the displayed IP. I think the IP address should at least be retained?

Kubevirt is trying to expose reality as much as possible.
If there is no guest-agent, then the address would have been assumed to be the one seen on the pod initially (no other information is available to say otherwise).
However, if the guest-agent is active, it will be the the most trustful source of truth and therefore its report will be exposed.
If you consider that some guests may not support dhcp-client, then the IP would not have reached the guest and reporting that is the correct thing to do.

You are welcome to propose a PR and change this algorithm, just bring it with a good enough reasoning to convince the community it is a better fit than the current one.

**Comment by mzzgaopeng** [comment]
The problem we found was with the refresh rate after stabilization (it started at 10 seconds and increased exponentially to that stable value)
This time interval 10.20.40.80.160 These time points the guest-agent gets the IPaddress, it just doesn't write write to api-server.

**Comment by EdDev** [comment]
> The problem we found was with the refresh rate after stabilization (it started at 10 seconds and increased exponentially to that stable value) This time interval 10.20.40.80.160 These time points the guest-agent gets the IPaddress, it just doesn't write write to api-server.

The only relevant fix related to something that resembles what you are describing was [this](https://github.com/kubevirt/kubevirt/pull/7131).

Your provided [log](https://github.com/kubevirt/kubevirt/issues/7508#issuecomment-1093756591) shows the IP was seen after at least 1min and 10sec. And that is at the virt-launcher polling of the guest-agent.
So I am not clear why you think the IP was seen after 10sec.

**Comment by zhhray** [comment]
> > The problem we found was with the refresh rate after stabilization (it started at 10 seconds and increased exponentially to that stable value) This time interval 10.20.40.80.160 These time points the guest-agent gets the IPaddress, it just doesn't write write to api-server.
> 
> The only relevant fix related to something that resembles what you are describing was [this](https://github.com/kubevirt/kubevirt/pull/7131).
> 
> Your provided [log](https://github.com/kubevirt/kubevirt/issues/7508#issuecomment-1093756591) shows the IP was seen after at least 1min and 10sec. And that is at the virt-launcher polling of the guest-agent. So I am not clear why you think the IP was seen after 10sec.


I checked that [this](https://github.com/kubevirt/kubevirt/pull/7131) fix did shorten the time it took for the IP address to be written back, but it didn't solve the underlying problem.
My appeal is this:
When the contents of interfaces in the status of the vmi look like this:
```yaml
  interfaces:
  - infoSource: domain
    ipAddress: 10.8.0.2
    ipAddresses:
    - 10.8.0.2
    mac: 00:00:00:2f:e1:b1
    name: default
```
When guest-agent comes to update, if the content of ipAddress field is empty, please do not rush to overwrite the existing ipAddress. The guest-agent overwrites the ipAddress until the agent actually obtains the ipAddress. Can you do that?
