### ISSUE TITLE
VMI was terminated because of "Still missing PID for uuid=*****, Process uuid=***** not found in /proc" on ARM64 environment

### ISSUE THREAD

**Issue by carpediemtal** [kubevirt/kubevirt#7603]
**What happened**:
When I create the VMI on my **ARM64** computer by `kubectl create -f vmi.yaml` virt-launcher pod will log "Still missing PID for uuid=*****, Process uuid=***** not found in /proc" repeatedly:
`{"component":"virt-launcher","level":"info","msg":"Still missing PID for uuid=91efe376-bd6c-4289-9c9f-9273cde376d6, Process uuid=91efe376-bd6c-4289-9c9f-9273cde376d6 not found in /proc","pos":"monitor.go:123","timestamp":"2022-04-21T05:14:16.828347Z"}
{"component":"virt-launcher","level":"info","msg":"uuid=91efe376-bd6c-4289-9c9f-9273cde376d6 not found after timeout","pos":"monitor.go:127","timestamp":"2022-04-21T05:14:16.828407Z"}`

I can use SSH to login the VM now, but after 5min, VM and launcher pod will be terminated because of **timeout** :

```
{"component":"virt-launcher","level":"info","msg":"uuid=91efe376-bd6c-4289-9c9f-9273cde376d6 not found after timeout","pos":"monitor.go:127","timestamp":"2022-04-21T05:14:16.828407Z"}
{"component":"virt-launcher","level":"info","msg":"Waiting on final notifications to be sent to virt-handler.","pos":"virt-launcher.go:270","timestamp":"2022-04-21T05:14:16.828426Z"}
{"component":"virt-launcher","level":"info","msg":"Timed out waiting for final delete notification. Attempting to kill domain","pos":"virt-launcher.go:290","timestamp":"2022-04-21T05:14:31.829519Z"}
```

**What you expected to happen**:
I've done this well in my x86_64 computer, PID can be found and VM runs with good condition
So I wonder is this a BUG on ARM64 arch and how to fix it?

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f vm.yaml
kubectl logs virt-launcher-pod

**Additional context**:

**Environment**:

- KubeVirt version (use `virtctl version`): 
  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)
  LATEST=20220421

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}

- VM or VMI specifications: 

  ```yaml
  metadata:
    name: fedora35
    labels:
      slt: fedora35
  apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachineInstance
  spec:
    domain:
      resources:
        requests:
          memory: 1000M
      devices:
        disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        interfaces:
          - name: default
            masquerade: {}
    networks:
      - name: default
        pod: {}
    volumes:
      - name: containerdisk
        containerDisk:
          image: m1n999/virt:fedora35-arm64
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: fedora35
            ssh_pwauth: True
            disable_root: false
            password: password
            chpasswd: { expire: False }
  ```

  

- Cloud provider or hardware configuration: N/A

- OS (e.g. from /etc/os-release): 

  ```
  NAME="openEuler"
  VERSION="22.03 LTS"
  ID="openEuler"
  VERSION_ID="22.03"
  PRETTY_NAME="openEuler 22.03 LTS"
  ANSI_COLOR="0;31"
  ```

  

- Kernel (e.g. `uname -a`): 

  ```
  Linux localhost.localdomain 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
  ```

  

- Install tools:  

  ```shell
  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-operator-arm64.yaml
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-cr-arm64.yaml
  ```

  

- Others: N/A

**Comment by rmohr** [comment]
/assign @zhlhahaha

who may be able to diagnose the issue better since we talk about an arm deployment. In general you can probably see in the event log `kubectl get events --all-namespace` what the root cause of the issue is. That VMs are teared down due to no qemu being started is normally only a symptom of a more fundamental problem.

**Comment by zhlhahaha** [comment]
Let me give it a try.

**Comment by carpediemtal** [comment]
Thanks for your reply,  but I get nothing from `kubectl get events` :
```
[root@localhost ming]# kubectl get events --all-namespaces=true
No resources found
```

**Comment by rmohr** [comment]
@carpediemtal the event log flushes entries after some time. You may have to recreate the issue.

**Comment by zhlhahaha** [comment]
Hi @carpediemtal 
I am unable to pull your vmi image, so I tried my fedora vmi image and it works fine on most resent kubeVirt commit. Would you mind to try my setting:
```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: zhlhahaha/fedora-cloud-container-disk-demo:aarch64
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```

**Comment by zhlhahaha** [comment]
I can reproduce the issue on my environment. It seems that there are something wrong when creating network. If I remove
```
      interfaces:
        - name: default
          masquerade: {}
  networks:
    - name: default
      pod: {}
```
vmi can boot successfully. I need sometime to see why it happen.

**Comment by carpediemtal** [comment]
@zhlhahaha 
Thanks for your help, 
I have pushed my vmi image to repo just now, I think you can pull it now.
And I also tried your image and config file, the problem is still not solved(vmi will crash after time out).

when I run "kubectl get events", I get this: 
```
8m22s       Normal    Pulled             pod/virt-launcher-vmi-fedora-n4sln   Successfully pulled image "zhlhahaha/fedora-cloud-container-disk-demo:aarch64" in 2m37.07217736s
8m21s       Normal    Created            pod/virt-launcher-vmi-fedora-n4sln   Created container volumecontainerdisk-init
8m21s       Normal    Started            pod/virt-launcher-vmi-fedora-n4sln   Started container volumecontainerdisk-init
8m20s       Normal    Pulled             pod/virt-launcher-vmi-fedora-n4sln   Container image "quay.io/kubevirt/virt-launcher:20220421_533a36469-arm64" already present on machine
8m20s       Normal    Created            pod/virt-launcher-vmi-fedora-n4sln   Created container compute
8m20s       Normal    Started            pod/virt-launcher-vmi-fedora-n4sln   Started container compute
8m20s       Normal    Pulled             pod/virt-launcher-vmi-fedora-n4sln   Container image "zhlhahaha/fedora-cloud-container-disk-demo:aarch64" already present on machine
8m20s       Normal    Created            pod/virt-launcher-vmi-fedora-n4sln   Created container volumecontainerdisk
8m20s       Normal    Started            pod/virt-launcher-vmi-fedora-n4sln   Started container volumecontainerdisk
7m25s       Normal    Killing            pod/virt-launcher-vmi-fedora-n4sln   Stopping container compute
7m25s       Normal    Killing            pod/virt-launcher-vmi-fedora-n4sln   Stopping container volumecontainerdisk
11m         Normal    SuccessfulCreate   virtualmachineinstance/vmi-fedora    Created virtual machine pod virt-launcher-vmi-fedora-n4sln
7m11s       Warning   SyncFailed         virtualmachineinstance/vmi-fedora    server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2022-04-21T08:55:43.949879Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2\",\"node-name\":\"libvirt-2-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': Permission denied')"
7m10s       Warning   SyncFailed         virtualmachineinstance/vmi-fedora    server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2022-04-21T08:55:44.176885Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2\",\"node-name\":\"libvirt-2-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': Permission denied')"
7m          Warning   SyncFailed         virtualmachineinstance/vmi-fedora    (combined from similar events): server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2022-04-21T08:55:54.189845Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2\",\"node-name\":\"libvirt-2-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': c')"
6m49s       Normal    Started            virtualmachineinstance/vmi-fedora    VirtualMachineInstance started.
2m20s       Normal    Stopped            virtualmachineinstance/vmi-fedora    The VirtualMachineInstance was shut down.
2m20s       Normal    Deleted            virtualmachineinstance/vmi-fedora    Signaled Deletion
```

I solved the "Permission denied" problem  by  "chmod 777 -R /var/lib/kubelet/pods" manually and it works fine


And in my environment , delete these lines does not help.
```
interfaces:
        - name: default
          masquerade: {}
  networks:
    - name: default
      pod: {}
```
QAQ
