### ISSUE TITLE
cloud server failure to scheduling win10 vmi, the reason is:4 Insufficient devices.kubevirt.io/kvm

### ISSUE THREAD

**Issue by FireLv** [kubevirt/kubevirt#7614]
**What happened**:
After I create vmi,the k8s schedule failure,and the reason is "4 Insufficient devices.kubevirt.io/kvm"

**What you expected to happen**:
k8s create vim success

**How to reproduce it (as minimally and precisely as possible)**:
create a vmi with yaml file

**Additional context**:
The value "devices.kubevirt.io/kvm" I get on both cloud server and hardware server is 0, is there any way to increase it ?

the part of yaml file of cloud server node:
```
  allocatable:
    cpu: "4"
    devices.kubevirt.io/kvm: "0"
    devices.kubevirt.io/tun: 1k
    memory: 16163984Ki
    pods: "110"
  capacity:
    cpu: "4"
    devices.kubevirt.io/kvm: 1k
    devices.kubevirt.io/tun: 1k
    memory: 16266384Ki
    pods: "110"
```

the part of yaml file of hardware:
```
  allocatable:
    cpu: "40"
    devices.kubevirt.io/kvm: "0"
    devices.kubevirt.io/sev: "0"
    devices.kubevirt.io/tun: "0"
    memory: 65605112Ki
    pods: "110"
  capacity:
    cpu: "40"
    devices.kubevirt.io/kvm: "0"
    devices.kubevirt.io/sev: "0"
    devices.kubevirt.io/tun: "0"
    memory: 65707512Ki
    pods: "110"
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.47.1
- Kubernetes version (use `kubectl version`): v1.18.4
- VM or VMI specifications: win10
- Cloud provider or hardware configuration: JingDong
- OS (e.g. from /etc/os-release): CentOS 7.6.1810
- Kernel (e.g. `uname -a`): 3.10.0-957
- Install tools: N/A
- Others: N/A
