### ISSUE TITLE
Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': Permission denied

### ISSUE THREAD

**Issue by carpediemtal** [kubevirt/kubevirt#7722]
**What happened**:

The VM will be terminated because of `Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': Permission denied`, I have to execute `chmod 777 -R /var/lib/kubelets/pods` timely to avoid the problem.

**What you expected to happen**:
I want this error disappear

**How to reproduce it (as minimally and precisely as possible)**:

I create the container image by this way following the user-guide([[Disks and Volumes - KubeVirt User-Guide](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example)](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example)) :

```bash
cat << END > Dockerfile
FROM scratch
ADD --chown=107:107 fedora25.qcow2 /disk/
END

docker build -t vmidisks/fedora25:latest .
```

Then I create the VMI by this way:

`kubectl create -f vmi.yaml`

```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: zhlhahaha/fedora-cloud-container-disk-demo:aarch64
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```

`kubectl logs virt-launcher-vmi-fedora-mncs9`

```tex
{"component":"virt-launcher","level":"error","msg":"internal error: qemu unexpectedly closed the monitor: 2022-05-11T01:35:41.666600Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2\",\"node-name\":\"libvirt-2-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2': Permission denied","pos":"qemuProcessReportLogError:2051","subcomponent":"libvirt","thread":"211","timestamp":"2022-05-11T01:35:41.718000Z"}
```

Few seconds later,  VM will be terminated.

**Additional context**:

I execute `ls` command on virt-launcher-pod, and I noticed that the user and group of disk.qcow2 are **root** rather than **qemu**.

 I think this might be the reason why qemu cannot open it,  but I don't know how to solve this problem.

```
[root@localhost fedora]# kubectl get pods
kuNAME                             READY   STATUS      RESTARTS   AGE
virt-launcher-vmi-fedora-mncs9   0/2     Completed   0          7m50s

[root@localhost fedora]# kubectl exec pod/virt-launcher-vmi-fedora-mncs9 -- /usr/bin/ls -la /var/run/kubevirt-ephemeral-disks/disk-data/containerdisk
total 204
drwxr-x--- 2 root root   4096 May 11 01:35 .
drwxr-x--- 3 root root   4096 May 11 01:35 ..
-rw-r----- 1 root root 196672 May 11 01:35 disk.qcow2
```

And this problem might be related to my os-release(openEuler 22.03 LTS), I guess, because on my fedora environment, it works fine.

**Environment**:

- KubeVirt version (use `virtctl version`): 

  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)

  LATEST=20220509

- Kubernetes version (use `kubectl version`): 

  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}

- VM or VMI specifications: 

  ```yaml
  ---
  apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  metadata:
    labels:
      special: vmi-fedora
    name: vmi-fedora
  spec:
    domain:
      devices:
        disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
        rng: {}
      resources:
        requests:
          memory: 1024M
    terminationGracePeriodSeconds: 0
    volumes:
    - containerDisk:
        image: zhlhahaha/fedora-cloud-container-disk-demo:aarch64
      name: containerdisk
    - cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
      name: cloudinitdisk
  ```

  

- Cloud provider or hardware configuration: N/A

- OS (e.g. from /etc/os-release): 

  NAME="openEuler"
  VERSION="22.03 LTS"
  ID="openEuler"
  VERSION_ID="22.03"
  PRETTY_NAME="openEuler 22.03 LTS"
  ANSI_COLOR="0;31"

- Kernel (e.g. `uname -a`): 

  Linux localhost.localdomain 5.10.0-60.20.0.52.oe2203.aarch64 #1 SMP Wed Apr 13 10:27:16 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

- Install tools: 

  ```bash
  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-operator-arm64.yaml
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-cr-arm64.yaml
  ```

  

- Others: N/A
