### ISSUE TITLE
How can I pass two identical pciDevices?

### ISSUE THREAD

**Issue by alizshow** [kubevirt/kubevirt#7755]
I have two identical GPUs with the same vendor/product id and in the same IOMMU group and I wish to pass them both to a single VM.
The Kubevirt-gpu-device-plugin provided by Nvidia detects one of them only, so I tried adding and naming these under different names in the `permittedHostDevices` of the config (although there is no way for me to differentiate between the two) and passing them to the VM directly.

```
permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: 10de:1e07
        resourceName: example.com/2080_Ti
      - pciVendorSelector: 10de:1e07
        resourceName: example.com/2080_Ti2
```
```
hostDevices:
    - deviceName: example.com/2080_Ti
      name: gpu1
    - deviceName: example.com/2080_Ti2
      name: gpu2
```

Which is somewhat pointless since only one of the devices show up on the node description with non-empty capacity:
```
Capacity:
  example.com/2080_Ti:                         0
  example.com/2080_Ti2:                        1
```

I am using KubeVirt v0.41.3

TL;DR
Have two GPUs in the same IOMMU group and want to pass them to a single VM, which should be possible.
