### ISSUE TITLE
Passwd and sshkeys always be coverd by qume-guest-agent

### ISSUE THREAD

**Issue by xujunjie-cover** [kubevirt/kubevirt#7813]
**What happened**:
create vm with passwd and sshkey secret
```yaml
          accessCredentials:
          - sshPublicKey:
              source:
                secret:
                  secretName: my-pub-key
              propagationMethod:
                qemuGuestAgent:
                  users:
                  - "fedora"
                  - "root"
          - userPassword:
              source:
                secret:
                  secretName: my-user-pass
              propagationMethod:
                qemuGuestAgent: {}

```
then change passwd in vm；after seconds，passwd and sshkey be coverd by qemu-guest-agent

**What you expected to happen**:
Don't set passwd or sshkey when secret not changed

**Environment**:
- KubeVirt version (use `virtctl version`): release-0.51
