### ISSUE TITLE
The downstream bandwidth is much smaller than the upstream bandwidth from other node to the vm

### ISSUE THREAD

**Issue by caohuilong** [kubevirt/kubevirt#7831]
**What happened**:
I have a cluster with two node A and B. I create a vm in node A, run `iperf3 -s` in the vm, and try to test the upstream and downstream bandwidth from node B to the vm. But I found The downstream bandwidth is much smaller than the upstream bandwidth. Just like the screenshot:
![iperf3异常结果2](https://user-images.githubusercontent.com/26712324/170906456-5155b60d-8015-4fca-9928-645502e8aaab.png)
> `192.168.134.55` is the ip address of the vm.

**What you expected to happen**:
The upstream and downstream bandwidth from all the node are similar.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a vm in one node
2. run `iperf3 -s` in the vm
3. test the upstream and downstream bandwidth from other node.

**Additional context**:
CNI is Calico IPIP mode.

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.49.0`
- Kubernetes version (use `kubectl version`): `v1.18.3`
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: centos7
  name: centos7
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos7    
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
        resources:
          requests:
            cpu: 2
            memory: 2G
      volumes:
        - containerDisk:
            image: centos7
            imagePullPolicy: IfNotPresent
          name: containerdisk
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 10 (buster)`
- Kernel (e.g. `uname -a`): `4.19.0-19-amd64`
- Install tools: `operator`
- Others: N/A
