### ISSUE TITLE
create vmi failed "Emulator '/usr/libexec/qemu-kvm' does not support virt type 'kvm'"

### ISSUE THREAD

**Issue by tomjamescn** [kubevirt/kubevirt#7913]
**What happened**:
create a vmi, but failed.
content of vmi.yaml is:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```

`kubectl get vmi` output:
```
NAME              AGE     PHASE       IP    NODENAME
testvmi-nocloud   5m13s   Scheduled         office-dev
```

`kubectl describe vmi testvmi-nocloud` output:
```
Name:         testvmi-nocloud
Namespace:    default
Labels:       kubevirt.io/nodeName=office-dev
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachineInstance","metadata":{"annotations":{},"name":"testvmi-nocloud","namespace":"de...
              kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2022-06-14T10:20:08Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  8
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:domain:
          .:
          f:devices:
            .:
            f:disks:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:terminationGracePeriodSeconds:
        f:volumes:
    Manager:      kubectl
    Operation:    Update
    Time:         2022-06-14T10:20:08Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:labels:
          .:
          f:kubevirt.io/nodeName:
      f:status:
        .:
        f:activePods:
          .:
          f:b235ea8a-b7d0-4a80-89fd-96f49d93970d:
        f:guestOSInfo:
        f:nodeName:
        f:qosClass:
    Manager:      virt-controller
    Operation:    Update
    Time:         2022-06-14T10:20:20Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:migrationMethod:
        f:phase:
    Manager:         virt-handler
    Operation:       Update
    Time:            2022-06-14T10:25:56Z
  Resource Version:  20168
  UID:               eb1aa7e6-8531-45a5-b1a5-090bafc24779
Spec:
  Domain:
    Cpu:
      Cores:    1
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   emptydisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  b8a365b8-8c7a-41f1-a71c-c5816df1acfe
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  30
  Volumes:
    Container Disk:
      Image:              kubevirt/fedora-cloud-container-disk-demo:latest
      Image Pull Policy:  Always
    Name:                 containerdisk
    Empty Disk:
      Capacity:  2Gi
    Name:        emptydisk
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
    Name:  cloudinitdisk
Status:
  Active Pods:
    b235ea8a-b7d0-4a80-89fd-96f49d93970d:  office-dev
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
  Guest OS Info:
  Migration Method:  BlockMigration
  Node Name:         office-dev
  Phase:             Failed
  Qos Class:         Burstable
Events:
  Type     Reason            Age                     From                       Message
  ----     ------            ----                    ----                       -------
  Normal   SuccessfulCreate  5m49s                   virtualmachine-controller  Created virtual machine pod virt-launcher-testvmi-nocloud-cnq2g
  Warning  SyncFailed        2m46s (x16 over 5m37s)  virt-handler, office-dev   server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: Emulator '/usr/libexec/qemu-kvm' does not support virt type 'kvm'')"
  Warning  Stopped           2s                      virt-handler, office-dev   The VirtualMachineInstance crashed.
```

**What you expected to happen**:
create a vmi succeful.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f vmi.yaml`

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.35.0
- Kubernetes version (use `kubectl version`): v1.21.13+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux office-dev 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A
