### ISSUE TITLE
vm can not obtain ip address via dhcp in bridge mode

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#7979]
**What happened**:
kubevirt  virtualmachine can not get IP address via dhcp.

**What you expected to happen**:
vm can get IP address via dhcp.

**How to reproduce it (as minimally and precisely as possible)**:
This is a rare problem, but when it does occur, the VM cannot obtain an IP address

**Additional context**:

What other information do I need to get ?

**Environment**:
- KubeVirt version (use `virtctl version`): 0.53.1
- Kubernetes version (use `kubectl version`): 1.22
- VM or VMI specifications: 
domain:
```yaml
        devices:
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: q35
      networks:
        - name: default
          pod: {}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  centos 7
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by zhhray** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/8120555/175282043-42b030f6-3d01-437b-8263-6e3afe92f38c.png">

**Comment by zhhray** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/8120555/175282247-a1c042b9-1f18-494d-892d-808d26328372.png">

**Comment by zhhray** [comment]
How do I know that the DHCP server in the virt-launcher pod is providing the right service?

**Comment by xpivarc** [comment]
@rhrazdil Could you have a look?

**Comment by rhrazdil** [comment]
Hello @zhhray 
You can check the DHCP configuration that is generated for a VMI in virt-handler logs. You need to configure logVerbosity to 5 in kubevirt CR
```
    developerConfiguration:
      logVerbosity:
        virtHandler: 5
        virtLauncher: 5
```

Then in virt-handler logs, you should find the following message
```
{"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: \u003cnil\u003e, MTU: 0, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"podnic.go:200","timestamp":"2022-07-01T11:05:54.455497Z"}
```

This generated config is consumed in virt-handler, in virt-handler logs you should find something like:
```
virt-launcher pod logs snippet with DHCP config:
{"component":"virt-launcher","level":"info","msg":"The imported dhcpConfig: DHCPConfig: { Name: eth0, IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: 169.254.75.10, MTU: 1480, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"podnic.go:253","timestamp":"2022-07-01T11:05:54.567214Z"}
{"component":"virt-launcher","level":"info","msg":"StartDHCP network Nic: DHCPConfig: { Name: eth0, IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: 169.254.75.10, MTU: 1480, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"common.go:317","timestamp":"2022-07-01T11:05:54.567268Z"}
```

The DHCP server is fairly simple, you can find it implemented here: https://github.com/kubevirt/kubevirt/blob/main/pkg/network/dhcp/server/server.go#L190

It would be interesting to see what is in the vir-launcher log after message
```
Serving a new request
```

Could you please attach virt-launcher log?

**Comment by zhhray** [comment]
> Hello @zhhray You can check the DHCP configuration that is generated for a VMI in virt-handler logs. You need to configure logVerbosity to 5 in kubevirt CR
> 
> ```
>     developerConfiguration:
>       logVerbosity:
>         virtHandler: 5
>         virtLauncher: 5
> ```
> 
> Then in virt-handler logs, you should find the following message
> 
> ```
> {"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: \u003cnil\u003e, MTU: 0, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"podnic.go:200","timestamp":"2022-07-01T11:05:54.455497Z"}
> ```
> 
> This generated config is consumed in virt-handler, in virt-handler logs you should find something like:
> 
> ```
> virt-launcher pod logs snippet with DHCP config:
> {"component":"virt-launcher","level":"info","msg":"The imported dhcpConfig: DHCPConfig: { Name: eth0, IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: 169.254.75.10, MTU: 1480, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"podnic.go:253","timestamp":"2022-07-01T11:05:54.567214Z"}
> {"component":"virt-launcher","level":"info","msg":"StartDHCP network Nic: DHCPConfig: { Name: eth0, IPv4: 10.244.196.155/32 eth0, IPv6: \u003cnil\u003e, MAC: 22:db:76:c4:18:cf, AdvertisingIPAddr: 169.254.75.10, MTU: 1480, Gateway: 169.254.1.1, IPAMDisabled: false}","pos":"common.go:317","timestamp":"2022-07-01T11:05:54.567268Z"}
> ```
> 
> The DHCP server is fairly simple, you can find it implemented here: https://github.com/kubevirt/kubevirt/blob/main/pkg/network/dhcp/server/server.go#L190
> 
> It would be interesting to see what is in the vir-launcher log after message
> 
> ```
> Serving a new request
> ```
> 
> Could you please attach virt-launcher log?

Thanks  very much for your reply.
This is an occasional problem that has cropped up again recently.
But when I went to adjust the log level, but it didn't work.
I use Kubevirt, which is deployed by the [hco operator](https://github.com/kubevirt/hyperconverged-cluster-operator).
Although the configuration appears to be successful, but the pod startup parameters remain unchanged.
The hco operator version is : v1.6.0
Kubevirt version is : v0.53.1
The configuration of hco cr is:
```yaml
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    kubevirt.kubevirt.io/jsonpatch: |-
      [
        {
          "op": "add",
          "path": "/spec/configuration/developerConfiguration",
          "value": {"logVerbosity": {"virtAPI": 5, "virtController": 5, "virtHandler": 5,"virtLauncher": 5,"virtOperator": 5}}
        }
      ]
```
The configuration of kubevirt cr is:
```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  finalizers:
    - foregroundDeleteKubeVirt
  labels:
    app: kubevirt-hyperconverged
    app.kubernetes.io/component: compute
    app.kubernetes.io/managed-by: hco-operator
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 1.6.0
  name: kubevirt-kubevirt-hyperconverged
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      logVerbosity:
        virtAPI: 5
        virtController: 5
        virtHandler: 5
        virtLauncher: 5
        virtOperator: 5
```
However, the pod log level is still 2.
virt-handler:
```yaml
  containers:
    - command:
        - virt-handler
        - '--port'
        - '8443'
        - '--hostname-override'
        - $(NODE_NAME)
        - '--pod-ip-address'
        - $(MY_POD_IP)
        - '--max-metric-requests'
        - '3'
        - '--console-server-port'
        - '8186'
        - '--graceful-shutdown-seconds'
        - '315'
        - '-v'
        - '2'
```
virt-operator:
```yaml
  containers:
    - command:
        - virt-operator
        - '--port'
        - '8443'
        - '-v'
        - '2'
```
