### ISSUE TITLE
ExperimentalVirtiofsSupport feature gate appears to not be configurable after upgrading kubevirt

### ISSUE THREAD

**Issue by hickersonj** [kubevirt/kubevirt#7980]
**What happened**:
I was able to use the virtiofs feature to expose the hosts path to the VM. I'm applying the following yaml as before, but now when deploying the VM it complains that the virtiofs feature gate is not enabled.
```
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - ExperimentalVirtiofsSupport
```
**Error**
```
kubectl apply -f client-vm.yaml -n fedora
The request is invalid: spec.template.spec.Filesystems: virtiofs feature gate is not enabled in kubevirt-config
```
This is what the chart looks like with the virtiofs filesystem configured:
```
cat client-vm.yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: client-vm
  namespace: fedora
spec:
  spec:
  runStrategy: "Always"
  template:
    metadata:
      labels:
        kubevirt.io/vm: client-vm
    spec:
      domain:
        devices:
          filesystems:
          - name: content
            virtiofs: {}
          disks:
          - name: storage
            disk:
              bus: virtio
            serial: PVCTEST
          - name: cloudinitdisk
            disk:
              bus: virtio
          - disk:
              bus: sata
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: image-disk
            bootOrder: 1
        resources:
          limits:
            cpu: 500m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 2Gi
      terminationGracePeriodSeconds: 0
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: content
      - name: storage
        persistentVolumeClaim:
          claimName: local-storage
      - emptyDisk:
          capacity: 512M
        name: datavolumedisk1
...
```
**What you expected to happen**:
I expect that the chart will be deployed.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
I updated from v0.43.1 -> v0.54.0 of the kubevirt-operator.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.54.0
- Kubernetes version (use `kubectl version`): 1.23.5+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by usrbinkat** [comment]
I see you are using the current CR in your snippet:
```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
```

By chance, since upgrading from previous versions, is the deprecated configmap still created in your cluster?

**Comment by xpivarc** [comment]
> > I see you are using the current CR in your snippet:
> > ```
> > apiVersion: kubevirt.io/v1
> > kind: KubeVirt
> > metadata:
> >   name: kubevirt
> >   namespace: kubevirt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > By chance, since upgrading from previous versions, is the deprecated configmap still created in your cluster?
> 
> @usrbinkat can you provide me a way to determine that? Really appreciate it!

It should be something like `kubectl -n kubevirt get configmap`

**Comment by hickersonj** [comment]
Ok I discovered why it was resetting.  The `kubevirt-cr.yaml` manifest file didn't have the `- ExperimentalVirtiofsSupport` feature gate set and seemed to be overriding the patch, not entirely sure why that is. This file resides in the K3S_DATA folder `k3s/server/manifests`. 

However, since I've updated it to include the feature gate it no longer is a problem.
This is the updated `kubevirt-cr.yaml`
```yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - ExperimentalVirtiofsSupport
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  infra:
  workloadUpdateStrategy: {}
```
