### ISSUE TITLE
Windows 10 VM GPU problem

### ISSUE THREAD

**Issue by Zigko** [kubevirt/kubevirt#8024]
**Environment**:
- KubeVirt version (use `virtctl version`): 0.54
- Kubernetes version (use `kubectl version`): 1.24.2
- VM or VMI specifications: yaml bellow
- OS (e.g. from /etc/os-release): Debian 11 bullseye
- Kernel (e.g. `uname -a`): Linux debian 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

Hi,

I have tried several windows (server 2012, server 2012 and now windows 10)
I'm trying to pass the GPU for my windows VM, and the firsts attempts the device manager wouldn't recognize the GPU host that is passing with vfio-pci driver.

Currently, I'm using a Windows 10 VM and I can the GPU on the device manager:
![image](https://user-images.githubusercontent.com/56871305/176732880-1c50cfa9-9264-4a45-acc7-1cbe9653a81f.png)
but is not appearing on the Task Manager:
![image](https://user-images.githubusercontent.com/56871305/176732940-1e6e7ac1-d83f-43bf-b199-31e23e09ac81.png)
## When I try to install the NVIDIA drivers the VM crashes with a blue screen giving the next error:
![image](https://user-images.githubusercontent.com/56871305/176733034-a3037e0a-b45a-49de-804c-b0cdd0fddeec.png)

--- 
My VM,PVC and PV:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-volume 
    labels:
      type: local
spec:
    storageClassName: manual 
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/mnt/data" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
        #storageClassName: storage-nonblock 
  storageClassName: manual
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows-10-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-10-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - cdrom:
              bus: sata
            name: win-iso
            bootOrder: 2
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
          - cdrom:
              bus: sata
              readonly: true
            name: virtio-drivers
            bootOrder: 3
          gpus:
          - deviceName: nvidia.com/gpu_geforce_1660
            name: gpu1
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: win-iso
        containerDisk:
          image: localhost:5000/windows-10-iso:latest
      - name: virtio-drivers
        containerDisk:
          image: kubevirt/virtio-container-disk
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd2
```
---
Is this related to the drivers that were loaded on the VM?
And what can be the solution?
