### ISSUE TITLE
VMI spec.affinity missing validation checks

### ISSUE THREAD

**Issue by alaypatel07** [kubevirt/kubevirt#8100]
**What happened**:
Create a VMI with invalid `spec.affinity` field values, the VMI is accepted by the server and stays in Pending state.

VMI spec:

```
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: ""
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      interfaces:
      - bridge: {}
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 084b4e18-0724-4ab2-8838-f3306991da01
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
  networks:
  - name: default
    pod: {}
  volumes:
  - containerDisk:
      image: kubevirt/cirros-container-disk-demo:v0.24.0
      imagePullPolicy: IfNotPresent
    name: containerdisk
```

**What you expected to happen**:
I expected server side validation to reject creation of vmi with invalid YAML. https://github.com/alaypatel07/kubernetes/blob/07d0b4a8bcbb0ebd942ed485376e3f08cdf3b43e/pkg/apis/core/types.go#L2568-L2569 The types clearly suggest that empty topology field is not allowed.

Instead of reject the vmi creation, the VMI was indeed created and stayed in pending state. Following is the status condition of the vmi

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-14T15:53:41Z"
    message: 'failed to create virtual machine pod: Pod "virt-launcher-alayp-vmi-container-disk-2-kwkxq"
      is invalid: [spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey:
      Required value: can not be empty, spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey:
      Invalid value: "": name part must be non-empty, spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey:
      Invalid value: "": name part must consist of alphanumeric characters, ''-'',
      ''_'' or ''.'', and must start and end with an alphanumeric character (e.g.
      ''MyName'',  or ''my.name'',  or ''123-abc'', regex used for validation is ''([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'')]'
    reason: FailedCreate
    status: "False"
    type: Synchronized
  guestOSInfo: {}
  phase: Pending
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-07-14T15:53:41Z"
 ```

**How to reproduce it (as minimally and precisely as possible)**:
``` sh
$ kubectl create -f vmi.yaml
```
Where vmi.yaml has the invalid spec as specified above.

**Additional context**:
If I try to create a deployment with the same spec, it gets rejected by the system during creation time.

```
kubectl create -f validate-affinity-deployment.yaml
The Deployment "busybox-deployment" is invalid:
* spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Required value: can not be empty
* spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "": name part must be non-empty
* spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

The Deployment Spec Validation [here](https://github.com/alaypatel07/kubernetes/blob/905e7510c84676fe5c6428f1038996e099a30f68/pkg/apis/apps/validation/validation.go#L494) ends up calling [ValidatePodSpec](https://github.com/alaypatel07/kubernetes/blob/a86afc12df023e8a45a1c3b6523aed38c3e6cd18/pkg/apis/core/validation/validation.go#L3283) which calls [validateAffinity](https://github.com/alaypatel07/kubernetes/blob/a86afc12df023e8a45a1c3b6523aed38c3e6cd18/pkg/apis/core/validation/validation.go#L3014) which might be missing in kubevirt [ValidateVirtualMachineInstanceSpec](https://github.com/kubevirt/kubevirt/blob/8e7bfbc712a4e980e17099ad1844510cdbd637eb/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L119)
