### ISSUE TITLE
instancetype: MemoryInstancetype.Guest not required

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#8171]
**What happened**:

`Guest` within `MemoryInstancetype` is not a required field while `Memory` is within `VirtualMachineInstancetypeSpec`.

**What you expected to happen**:

`Guest` should be requried within `MemoryInstancetype`.

**How to reproduce it (as minimally and precisely as possible)**:
```
# cat examples/csmall.yaml
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: csmall
spec:
  cpu:
    guest: 1 
  memory: {}
# ./cluster-up/kubectl.sh apply -f examples/csmall.yaml
# ./cluster-up/kubectl.sh apply -f examples/vm-cirros-csmall.yaml
# ./cluster-up/virtctl.sh start vm-cirros-csmall
# ./cluster-up/kubectl.sh get vms/vm-cirros-csmall -o json | jq .status.conditions[1].message
selecting docker as container runtime
"Failure while starting VMI: admission webhook \"virtualmachineinstances-create-validator.kubevirt.io\" denied the request: no memory requested, at least one of 'spec.domain.memory.guest', 'spec.domain.memory.hugepages.size' or 'spec.domain.resources.requests.memory' must be set"
```

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
