### ISSUE TITLE
Is DiskBusIDE supported or not?  expect it is supported.

### ISSUE THREAD

**Issue by w13915984028** [kubevirt/kubevirt#8175]
**What happened**:
Is `DiskBusIDE` supported or not?  expect it is supported.

We find it is said supported in kubevirt doc, but not supported in source code. And we expect it could be supported.

Per https://kubevirt.io/api-reference/v0.6.4/definitions.html,

It said `Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi, ide`

![image](https://user-images.githubusercontent.com/31133476/180806714-f71d3444-7aad-4807-b8d5-f3eab16256a8.png)

But in source code, the `ide` is not supported.

https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go#L608
```
type DiskBus string

const (
	DiskBusSCSI   DiskBus = "scsi"
	DiskBusSATA   DiskBus = "sata"
	DiskBusVirtio DiskBus = "virtio"
)
```

https://github.com/kubevirt/kubevirt/blob/8cf967899be8a6ef45836a49c103dd7bf13c24f3/tests/vmi_configuration_test.go#L2810

**What you expected to happen**:

Qemu supports use `ide` type of `hard disk` to boot directly. 
```
qemu-system-x86_64 --help
...
Block device options:
-fda/-fdb file  use 'file' as floppy disk 0/1 image
-hda/-hdb file  use 'file' as IDE hard disk 0/1 image
-hdc/-hdd file  use 'file' as IDE hard disk 2/3 image
-cdrom file     use 'file' as IDE cdrom image (cdrom is ide1 master)
-blockdev [driver=]driver[,node-name=N][,discard=ignore|unmap]
          [,cache.direct=on|off][,cache.no-flush=on|off]
          [,read-only=on|off][,auto-read-only=on|off]
          [,force-share=on|off][,detect-zeroes=on|off|unmap]
          [,driver specific parameters...]
                configure a block backend
```

With such command, we can run qemu based VM from one qcow2 file.

`sudo qemu-system-x86_64 -m 4G -accel kvm -hda /var/lib/libvirt/images/CentOS7.qcow2`

but in kubevirt, no matter how to try, the VM can not be boot

![image](https://user-images.githubusercontent.com/31133476/180810362-327b0e16-1da1-49e3-a3bd-0a680c38535b.png)

Disktype `scsi` won't work, and if we change it to `ide`, it said `not supporting`

```
type: kubevirt.io.virtualmachine
metadata:
  namespace: default
  annotations:
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"centos-hda-test-disk-0-ysrku","annotations":{"harvesterhci.io/imageId":"default/image-ntjgq"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"50Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-ntjgq"}}]
    network.harvesterhci.io/ips: '[]'
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: redhat
  name: centos-hda-test
__clone: true
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      labels:
        harvesterhci.io/vmName: centos-hda-test
    spec:
      domain:
        machine:
          type: ''
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          disks:
            - name: disk-0
              disk:
                bus: scsi
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          limits:
            memory: 4Gi
            cpu: 2
        features:
          acpi:
            enabled: true
      evictionStrategy: LiveMigrate
      hostname: centos-hda
      networks:
        - name: default
          pod: {}
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: centos-hda-test-disk-0-ysrku
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: centos-hda-test-96bta
            networkDataSecretRef:
              name: centos-hda-test-96bta
```

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

In an earlier issue, it looked `IDE` is supported.
https://github.com/kubevirt/kubevirt/issues/102
```
      disks:
      - type: file
        shapshot: internal
        device: disk
        driver:
          name: qemu
          type: qcow2
        diskSource:
          file: /var/lib/libvirt/images/cirros-0.3.4-x86_64-disk.img
        diskTarget:
          dev: hda
          bus: ide
```

**Environment**:
- KubeVirt version (use `virtctl version`): kubevirt master-head
- Kubernetes version (use `kubectl version`): N/A v1.18
- VM or VMI specifications: N/A X86 KVM/QEMU
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A Ubuntu
- Kernel (e.g. `uname -a`): N/A 5.*
- Install tools: N/A
- Others: N/A
