### ISSUE TITLE
Booting from an external source  (Kernel) causes error

### ISSUE THREAD

**Issue by daghaian** [kubevirt/kubevirt#8191]
**What happened**:
 
Currently, when attempting to deploy a Virtual Machine that has been provided an explicit kernel, kernel artifact verification fails and consequently the VM fails to start. The only way that this issue was able to be rectified was by disabling verification inside the `mountKernelArtifacts` function called in [pkg/virt-handler/container-disk/mount.go](https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go). Manually going into the virt-handler container and checking the path that has been mounted containing the kernel confirms that the mount was successful but in the environment tested, the verification is failing. Specifically, https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go#L512 is the line that returns back an error. The return from the mount command on https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go#L502 is successful so it would appear the criteria for verifying mount status is not working as intended.

**What you expected to happen**:

I would expect the kernel mount verification to complete successfully and for the VM to start without issue given that I was able to manually confirm that the mount was successful and the kernel is visible at the expected path. 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Simply deploy a VM/VMI which contains the following kernel block:

```yml
spec:
  domain:
    devices: {}
    firmware:
      kernelBoot:
        container:
              image: [ANY KERNEL CONTAINER IMAGE SHOULD DO]
              kernelPath: /boot/vmlinuz-virt
              imagePullPolicy: Always
              imagePullSecret: IfNotPresent
        kernelArgs: console=ttyS0
```

**Additional context**:

N/A

**Environment**:
- KubeVirt version (use `virtctl version`): Currently working off the main branch as of 7/26/22
- Kubernetes version (use `kubectl version`): 1.21
- VM or VMI specifications: N/A

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: my-test-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: testdomain
    spec:
      domain:
        firmware:
          kernelBoot:
            container:
              imagePullPolicy: IfNotPresent
              image: kubevirtvrack/alpine-ext-kernel-boot-demo
              kernelPath: /boot/vmlinuz-virt
            kernelArgs: console=ttyS0
        memory:
          guest: 1300M
        devices:
          disks:
          - name: disk-1
            disk:
              bus: virtio
          - name: disk-2
            disk:
              bus: virtio
          interfaces:
          - name: network1
            bridge: {}
          - name: network2
            bridge: {}
          - name: network3
            bridge: {}
          - name: network4
            bridge: {}
        resources:
          overcommitGuestOverhead: true
          limits:
            cpu: 3
            memory: 1500M
          requests:
            cpu: 3
            memory: 1Gi
      networks:
              - name: network1
                multus:
                  networkName: testdomain/my-test-vm
              - name: network2
                multus:
                  networkName: testdomain/my-test-vm
              - name: network3
                multus:
                  networkName: testdomain/my-test-vm
              - name: network4
                multus:
                  networkName: testdomain/my-test-vm
      volumes:
           - name: disk-1
             emptyDisk:
               capacity: 50G
           - name: disk-2
             emptyDisk:
               capacity: 50G
```

- Cloud provider or hardware configuration:  AWS EKS with Non-Fargate EC2 Instances
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`):  `Linux ip-10-2-169-42 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A
