### ISSUE TITLE
Latest release kubevirt-cr.yaml is invalid

### ISSUE THREAD

**Issue by ProjectInitiative** [kubevirt/kubevirt#8251]
**What happened**:
`kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/v0.55.0/kubevirt-cr.yaml`
output:
`The KubeVirt "kubevirt" is invalid: spec.infra: Invalid value: "null": spec.infra in body must be of type object: "null"`

**What you expected to happen**:
`kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/v0.55.0/kubevirt-cr.yaml`
output:
`kubevirt.kubevirt.io/kubevirt configured`

**How to reproduce it (as minimally and precisely as possible)**:
Follow current install [guide](https://kubevirt.io/quickstart_cloud/)

**Additional context**:
Problem is fixed by adding back `replica: 2` from previous releases:
```yaml
----
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  infra:
    replica: 2
  workloadUpdateStrategy: {}

```

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): 1.18.15
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
