### ISSUE TITLE
how to find sriov interface in vm corresponding to net1 in virt-launcher container?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#8253]
eth1, eth2 in vm, and net1, net2 in virt-launcher, how to ensure eth1 is corresponding to net1 or net2?

**Comment by dankenigsberg** [comment]
This seems related to https://github.com/kubevirt/kubevirt/issues/7444 and the discussion at https://github.com/kubevirt/community/pull/185 . Please review the discussion there.

**Comment by ormergi** [comment]
Currently, there is no way to do such mapping out-of-box, you can set each interface with a custom MAC address in the VMI spec and compare it to the guest interface MAC addresses.
For example:
```
kind: VirtualMachine
...
spec:
  domain:
    devices:
      interfaces:
      - name: sriovnet-vlan100
        sriov: {}
        macAddress: "02:02:02:02:02:02"
        ...
 ...
 networks:
 - name: sriovnet-vlan100
   multus:
     networkName: sriov-network-vlan100
   ...
```
