### ISSUE TITLE
Consider placing kubevirt-export-ca  behind VMExport feature gate

### ISSUE THREAD

**Issue by jrcichra** [kubevirt/kubevirt#8260]
**What happened**:
Providing a `certificateRotateStrategy` in the `KubeVirt` spec does not set/update the duration of the `kubevirt-export-ca` secret. The duration for `kubevirt-export-ca` is always `168h` (7 days).

**What you expected to happen**:
When specifying a config such as:
```
  certificateRotateStrategy:
    selfSigned:
      caOverlapInterval: 4392h
      caRotateInterval: 8760h
      certRotateInterval: 4368h
```
...in the KubeVirt spec, the `kubevirt.io/duration` for `secret/kubevirt-exporter-ca` should be `8760h`. It works as expected for the `kubevirt-ca`.

**How to reproduce it (as minimally and precisely as possible)**:
Specify a `certificateRotateStrategy` on KubeVirt `v0.55.0`. Check the duration of the `kubevirt-exporter-ca` secret with `-o yaml`.

**Additional context**:
I have not set the exportproxy feature flag. This secret was statically added in https://github.com/kubevirt/kubevirt/pull/7863.

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.55.0`
- Kubernetes version (use `kubectl version`): `v1.21.13`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g. from /etc/os-release): Debian Buster
- Kernel (e.g. `uname -a`): `5.15.40` variant
- Install tools: Github Releases YAML
- Others: N/A
