### ISSUE TITLE
Error when attempting to use Datavolume supplied disks with VM

### ISSUE THREAD

**Issue by daghaian** [kubevirt/kubevirt#8274]
**What happened**:
Currently, after deploying built Kubevirt from the latest code in **main**, datavolume-driven disks are unable to successfully be attached to the VM during initialization. From what can be seen, the following error is seen:

`preparing host-disks failed: chown /proc/239102/root/var/run/kubevirt-private/vmi-disks/gateway-disk/disk.img: operation not permitted`

At first, I thought that perhaps this was an issue with CDI, however updating to the latest has not had any effect. It should also be noted that the import process for CDI completes successfully but when attempting to attach the disks to the VM, the above error is seen. Additionally, when reverting the version of KubeVirt to v0.45.0 which is what we run in production, the issue goes away while using the same containerDIsks.

**What you expected to happen**:

I would expect for the datavolumes to be created and for the disks to be successfully attached to the specified VM spec.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

Simply running the latest Kubevirt codebase and deploying a VM which uses disks backed by datavolumes which are sourced from container disks.

**Additional context**:

N/A

**Environment**:
- KubeVirt version (use virtctl version): Currently working off the main branch as of 7/26/22
- Kubernetes version (use kubectl version): 1.21
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: persistencerack
  namespace: persistencerack
spec:
  dataVolumeTemplates:
  - metadata:
      name: persistencerack-disk-1-dv-unit0
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50G
        storageClassName: efs-persistencerack
      source:
        blank: {}
  - metadata:
      name: persistencerack-disk-2-dv-unit0
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 56G
        storageClassName: efs-persistencerack
      source:
        registry:
          certConfigMap: CERTS
          secretRef: SECRET
          url: DOCKER_IMAGE
  - metadata:
      name: persistencerack-disk-3-dv-unit0
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 56G
        storageClassName: efs-persistencerack
      source:
        registry:
          certConfigMap: CERTS
          secretRef: SECRET
          url: DOCKER_IMAGE
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: persistencerack
        vm: is
    spec:
      domain:
        devices:
          disableHotplug: true
          disks:
          - disk:
              bus: sata
            name: is-disk-1
          - disk:
              bus: sata
            name: is-disk-2
          - disk:
              bus: sata
            name: is-disk-3
          - bootOrder: 1
            disk:
              bus: virtio
            name: is-bootloader-disk
          interfaces:
          - bridge: {}
            name: network1
          - bridge: {}
            name: network2
          - bridge: {}
            name: network3
          - bridge: {}
            name: network4
        machine:
          type: q35
        memory:
          guest: 1800M
        resources:
          limits:
            cpu: "2"
            memory: 2G
          overcommitGuestOverhead: true
          requests:
            cpu: 100m
            memory: 512M
      networks:
      - multus:
          networkName: persistencerack/persistencerack
        name: network1
      - multus:
          networkName: persistencerack/persistencerack
        name: network2
      - multus:
          networkName: persistencerack/persistencerack
        name: network3
      - multus:
          networkName: persistencerack/persistencerack
        name: network4
      volumes:
      - dataVolume:
          name: persistencerack-is-disk-1-dv-unit0
        name: is-disk-1
      - dataVolume:
          name: persistencerack-is-disk-2-dv-unit0
        name: is-disk-2
      - dataVolume:
          name: persistencerack-is-disk-3-dv-unit0
        name: is-disk-3
      - containerDisk:
          image: IMAGE
          imagePullSecret: regcred
        name: is-bootloader-disk
```
- Cloud provider or hardware configuration:  AWS EKS with Non-Fargate EC2 Instances
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`):  `Linux ip-10-2-169-42 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A
