### ISSUE TITLE
Ability to specify custom images and imagePullSecrets

### ISSUE THREAD

**Issue by kvaps** [kubevirt/kubevirt#8302]
**Is your feature request related to a problem? Please describe**:

I'm on a way to implement KubeVirt module into [Deckhouse](https://github.com/deckhouse/deckhouse) Kubernetes platform. We use [werf](https://github.com/werf/werf) tool for building and deploying all our images.
The problem is that werf is using different logic for calculating image names, which is not fits into KubeVirt logic:

- KubeVirt always expects that for explicit image names in the registry: `/virt-operator`, `/virt-controller`, `virt-api`, `virt-handler` and `virt-launcher`, the version is calculated according to the tag name.
- Werf is always stores every project in same image, and calculating specific tag names for them using specific algorithm.

**Describe the solution you'd like**:

I want to have an opportunity to specifying image names for kubevirt-operator.

**Describe alternatives you've considered**:

I considered using built-in patch mechanism, it isn't ideal but I already found some workarounds which might work, eg:

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: d8-kubevirt
  labels:
    heritage: deckhouse
    module: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: {}
  customizeComponents:
    flags:
      controller:
        launcher-image: "dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075"
        exporter-image: "dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075"
    patches:
    - resourceType: Deployment
      resourceName: virt-api
      patch: '{"spec":{"template":{"spec":{"containers":[{"image":"dev-registry.deckhouse.io/sys/deckhouse-oss:4e2ba3443dfa40ad930db2794dd08aacf82ec2a20fd1d99c1e33c1ef-1660426475418","name":"virt-api"}],"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
    - resourceType: Deployment
      resourceName: virt-controller
      patch: '{"spec":{"template":{"spec":{"containers":[{"image":"dev-registry.deckhouse.io/sys/deckhouse-oss:d9abb8dde1ec39edb4466f28ff604d42af547f7836510c077e19a8cc-1660426386817","name":"virt-controller"}],"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
    - resourceType: DaemonSet
      resourceName: virt-handler
      patch: '{"spec":{"template":{"spec":{"containers":[{"image":"dev-registry.deckhouse.io/sys/deckhouse-oss:a15d9fbd82dea6f421b034c454f015716af5573f4629ab2ce166d8f5-1660426419120","name":"virt-handler"}],"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
  imagePullPolicy: IfNotPresent
  infra:
    replicas: 1
  workloadUpdateStrategy: {}
  imagePullPolicy: IfNotPresent
```
But I see the following problems:

 Only `deploy/virt-api`, `deploy/virt-controller`, `deploy/virt-exportproxy` and `ds/virt-handler` can be patched
  - **problem**: there is no opportunity to replace image for `kubevirt-install-strategy-generator` job.
  Image for this job could be specified in `OPERATOR_IMAGE` variable for operator deployment, but it will unable to start with the following error:
    ```
    can not parse operator image env var dev-registry.deckhouse.io/sys/deckhouse-oss:7d4f87dc31b995395b9eec3fb02749c31ede1bb13c2c03f023f1ce62-1660426437260\n
    ```
    **workaround:** (not found)

   - **problem**: there is no opportunity to specify `imagePullSecrets` for `kubevirt-install-strategy-generator` job
     **workaround:** imagePullSecret can be specified in `ServiceAccount` for `kubevirt-operator`, however the same approach will not work for other components, because [current implementation](https://github.com/kubevirt/kubevirt/blob/68d85f44697307855a8bb44e74ab9963ffbe58c1/pkg/virt-operator/resource/apply/patches.go#L122-L153) does not allow to patch `ServiceAccounts`

  - **problem**: there is no opportunity to specify `imagePullSecrets` for `virt-launcher` and `pv-hotplug` pods
    **workaround**: patch default serviceacount in namespace running vms:
    ```
    kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "deckhouse-registry"}]}'
    ```
  -  **problem**: specifying `launcher` and `exporter` images via flags is not working, because they are applied into `command` flags which are always be overriden by flags from `args`:

      ```yaml
      containers:
        command:
        - virt-controller
        - --exporter-image
        - dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075
        - --launcher-image
        - dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075
        args:
        - --launcher-image
        - quay.io/kubevirt/virt-launcher:v0.55.0
        - --exporter-image
        - quay.io/kubevirt/virt-exportserver:v0.55.0
        - --port
        - "8443"
        - -v
        - "2"
      ```
      **workaround:** Of course we can add another patch, which will modify args directly:

     ```yaml
     - resourceType: Deployment
       resourceName: virt-controller
       patch: '[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--launcher-image=dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075"}]'
       type: json
     - resourceType: Deployment
       resourceName: virt-controller
       patch: '[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--exporter-image=dev-registry.deckhouse.io/sys/deckhouse-oss:f0a89735f76b3d17a3bb8b96312323b974c1cc7995ce13b790db40f0-1660426450075"}]'
       type: json
     ```
      
**Additional context**:
