### ISSUE TITLE
[v2] [tracker] Collection of v2 changes which we want to consider for v2

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#8360]
Going on the API to v2 gives us the chance to change defaults and remove deprecated functionality. This issue tracks suggestions:

 * Change default bus type from `sata` to `virtio-blk` or `virtio-scsci` (https://github.com/kubevirt/kubevirt/pull/7007#issuecomment-1219434436)
 * Remove VirtualMachineInstancePresets (https://github.com/kubevirt/kubevirt/pull/8069#discussion_r951112515)

**Comment by ormergi** [comment]
@rmohr where is the appropriate place for proposing other suggestions for v2?

**Comment by rmohr** [comment]
@ormergi maybe there is another place already which I missed, but if there is no one, just drop your suggestions here.

**Comment by lyarwood** [comment]
@rmohr quick idea for `v2`. I've been [toying](https://github.com/kubevirt/kubevirt/pull/7969) with the idea of somehow making the `DomainSpec` optional for `VirtualMachines` but required for `VirtualMachineInstances`. The goal being to remove the final bit of cruft from the following valid definition when you use instance types and preferences with `v1`:

```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros
spec:
  instancetype:
    name: server.micro
  preference:
    name cirros
  running: true
  template:
    spec:
      domain:
        devices: {}
      volumes:
      - persistentVolumeClaim:
          claimName: cirros
        name: cirros-disk
```

This would instead be something like this with `v2`:

```
---
apiVersion: kubevirt.io/v2
kind: VirtualMachine
metadata:
  name: cirros
spec:
  instancetype:
    name: server.micro
  preference:
    name cirros
  running: true
  template:
    spec:
      volumes:
      - persistentVolumeClaim:
          claimName: cirros
        name: cirros-disk
```

Do you think this is a valid suggestion for `v2`?
