### ISSUE TITLE
virt-chroot mount expects a directory

### ISSUE THREAD

**Issue by josueneo** [kubevirt/kubevirt#8387]
**What happened**:
With a fresh installation of microk8s kubevirt v0.56.0 cannot create a test VMI with ephemeral disk.

**What you expected to happen**:
A running VMI, it works in v0.50.0

**How to reproduce it (as minimally and precisely as possible)**:
On a fedora 36 OS:

```
sudo dnf install snapd
sudo snap install microk8s
sudo microk8s start
export RELEASE="v0.56.0"
Deploy the KubeVirt operator

kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml 
```
Then apply the below yaml file (vmi.yaml)
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
        cache: writethrough
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
```
Then run
```
kubectl apply -f vmi.yaml
```

**Additional context**:
After a few minutes you could see the bellow message, and the VMI is in failed state, note that in v0.50.0 works without issues, reproduce steps and set `RELEASE="v0.50.0`
```
failed to bindmount containerDisk containerdisk: Error: mount target invalid: not a directory
Usage:
  virt-chroot mount [flags]

  Flags:
  -h, --help             help for mount
  -o, --options string   comma separated list of mount options
  -t, --type string      fstype

  Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

      mount target invalid: not a directory
 : exit status 1
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.56.0
- Kubernetes version (use `kubectl version`): 1.24.1
- VM or VMI specifications: Template attached
- Cloud provider or hardware configuration: baremetal / microk8s
- OS (e.g. from /etc/os-release): Fedora 36
- Kernel (e.g. `uname -a`): Linux fedora 5.17.5-300.fc36.x86_64 1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by hickersonj** [comment]
@josueneo thanks for submitting this, I'm having the same issue specifically when upgrading from `v0.55.0` -> `v0.55.1` and the issue is the same with `v0.56.0`.  I've noticed a lot of changes wrt path security, https://github.com/kubevirt/kubevirt/compare/v0.55.0...v0.55.1?diff=split

Here are my details as well:
Environment:
- KubeVirt version (use virtctl version): `v0.55.1` / `v.0.56.0`
- Kubernetes version (use kubectl version): `v1.23.5+k3s1`
- VM or VMI specifications: Can add if needed
- Cloud provider or hardware configuration: `baremetal / k3s`
- OS (e.g. from /etc/os-release): `Fedora 34`
- Kernel (e.g. uname -a): **Custom:** `Linux node1 5.10.99 #23 SMP Tue Jun 28 12:29:23 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by rmohr** [comment]
Seems like this i s related to k3s and microk8s. Something seems to be different there than on "stock" k8s installs.

**Comment by xpivarc** [comment]
> Just a thought: what if e.g. `/var/lib/kubelet` is already a symlink. I wonder how safepath will handle it.

Shouldn't this fail early?

**Comment by vasiliy-ul** [comment]
> Shouldn't this fail early?

Not 100% sure... It just reminds me about the issue raised some time ago. KubeVirt does not work with 'non-standard' kubelet directories. The proposed workaround at that time was to symlink such directories to `/var/lib/kubelet`. If I remember correctly, it was also failing on containerdisk mount.

**Comment by alicefr** [comment]
I just tried a quick installation of microk8s and the kubelet pod dir is different than the default path. Im virt-handler
```bash
bash-4.4# findmnt /pods/
TARGET SOURCE                                                                            FSTYPE OPTIONS
/pods  /dev/mapper/luks-5f5013f7-64a2-4d9d-8df2-7218b1ead106[/root/var/lib/kubelet/pods] btrfs  rw,relatime,seclabel,compress=zstd:1,ssd,space_cache,subvolid=257,subvol=/roo

```
IIRC, we need to set a flag and pass the custom directory?

**Comment by alicefr** [comment]
I've tried the example, I don't get the same failure but a very very close issue as in https://github.com/kubevirt/kubevirt/issues/8288

**Comment by rmohr** [comment]
> I've tried the example, I don't get the same failure but a very very close issue as in #8288

Thanks for that! Would be interesting to see if you have the same failure if you create a symlink to the expected directory.

**Comment by alicefr** [comment]
@rmohr yes, the sym link is causing the issue:
```sh
[root@fedora ~]# ls -lsh /var/lib/kubelet
4.0K lrwxrwxrwx. 1 root root 41 Sep  6 13:06 /var/lib/kubelet -> /var/snap/microk8s/common/var/lib/kubelet
```
I applied the same yaml and I got in virt-handler: 
```sh
 {"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"testvmi-nocloud","namespace":"default","pos":"vm.go:1633","timestamp":"2022-09-06T11:10:40.983154Z","uid":"2a4ec521-24ca-418b-baf5-fac16230da6d"}
{"component":"virt-handler","kind":"","level":"info","msg":"Bind mounting container disk at root: /proc/1/root, relative: /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io/69c466925e70ef334572f9236346d18c230a5a7eb79b8478682a9768ba6707dc/rootfs/disk/downloaded to root: /var/lib/kubelet/pods/9b094830-1b80-4610-9d1d-993ba5206195/volumes/kubernetes.io~empty-dir/container-disks, relative: /disk_0.img","name":"testvmi-nocloud","namespace":"default","pos":"mount.go:306","timestamp":"2022-09-06T11:10:40.987852Z","uid":"2a4ec521-24ca-418b-baf5-fac16230da6d"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-nocloud","namespace":"default","pos":"vm.go:1771","reason":"failed to bindmount containerDisk containerdisk: Error: mount target invalid: not a directory\nUsage:\n  virt-chroot mount [flags]\n\nFlags:\n  -h, --help             help for mount\n  -o, --options string   comma separated list of mount options\n  -t, --type string      fstype\n\nGlobal Flags:\n      --cpu uint       cpu time in seconds for the process\n      --memory uint    memory in bytes for the process\n      --mount string   mount namespace to use\n      --user string    switch to this targetUser to e.g. drop privileges\n\nmount target invalid: not a directory\n : exit status 1","timestamp":"2022-09-06T11:10:41.030321Z","uid":"2a4ec521-24ca-418b-baf5-fac16230da6d"}
```

**Comment by rmohr** [comment]
A potential fix to at least restore the support for `/var/lib/kubelet` being a symlink is this: https://github.com/kubevirt/kubevirt/issues/8429#issuecomment-1241728252 need a little bit to get back to it.

**Comment by josueneo** [comment]
I confirm this is fixed in v0.58.0-rc.0

**Comment by sherif84** [comment]
hi team, any eta on a fix for this issue ? we are seeing the same issue with rke2 based clusters

**Comment by rmohr** [comment]
> To confirm this is on my setup, `/var/lib/kubelet` is not a symlink, however `pods` is:

Oh, can be that `/var/lib/kubelet/pods` should be then no sumlink.

**Comment by wizpresso-steve-cy-fan** [comment]
This is also an issue for k0s when it is symlinked:

```
root@WIZPRESSO-13-linux:/var/lib/kubelet/pods/983e690d-4ac9-4635-8e97-24835fb45192/volumes/kubernetes.io~empty-dir/container-disks# ls -lsh /var/lib/kubelet
1.0K lrwxrwxrwx 1 root root 20 Oct 27 18:23 /var/lib/kubelet -> /var/lib/k0s/kubelet
```

**Comment by hickersonj** [comment]
> > To confirm this is on my setup, `/var/lib/kubelet` is not a symlink, however `pods` is:
> 
> Oh, can be that `/var/lib/kubelet/pods` should be then no symlink.

Ok I've verified that on my setup it was indeed the pods link that was causing the issue. I linked it because it needed to reside in non-volatile storage, but now I'm bind mounting `/var/lib/kubelet` to non-volatile storage.  This also allows ephemeral-storage to now work correctly for me. :) 
```bash
# previously had a pods link
ll /var/lib/kubelet/
total 24
-rw------- 1 root root   62 Mar 10 08:19 cpu_manager_state
drwxr-xr-x 2 root root 4096 Mar 10 08:26 device-plugins
-rw------- 1 root root   61 Mar 10 08:19 memory_manager_state
drwxr-x--- 2 root root 4096 Mar 10 08:19 plugins
drwxr-x--- 2 root root 4096 Mar 10 08:19 plugins_registry
drwxr-x--- 2 root root 4096 Mar 10 08:19 pod-resources
lrwxrwxrwx 1 root root   30 Mar 10 08:18 pods -> /home/user/pods
```

I've since removed that pods link and am bind mounting /var/lib/kubelet to the non-volatile location and it's now working:
```
mkdir -p /var/lib/kubelet /home/user/kubelet
mount --bind /home/user/kubelet /var/lib/kubelet
mount --make-rshared /var/lib/kubelet
```

**Comment by josueneo** [comment]
This is still an issue with microk8s v1.26 and kubevirt v0.59.0, @hickersonj workaround works.

**Comment by mike-matera** [comment]
I'm on Microk8s and applying the following configuration fixed this issue: 

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration: {}
  customizeComponents:
    patches:
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '{"spec": {"template": {"spec": {
            "volumes": [
              {"name": "kubelet-pods", "hostPath": {"path": "/var/snap/microk8s/common/var/lib/kubelet/pods"}},
              {"name": "kubelet-pods-shortened", "hostPath": {"path": "/var/snap/microk8s/common/var/lib/kubelet/pods"}},
              {"name": "device-plugin", "hostPath": {"path": "/var/snap/microk8s/common/var/lib/kubelet/device-plugins"}}
            ],
            "containers": [{
              "name": "virt-handler",
              "volumeMounts": [
                {"name": "kubelet-pods", "mountPath": "/var/snap/microk8s/common/var/lib/kubelet/pods", "mountPropagation": "Bidirectional"},
                {"name": "device-plugin", "mountPath": "/var/snap/microk8s/common/var/lib/kubelet/device-plugins"}
              ]
            }]
          }}}}'
        type: strategic
    flags:
      handler:
        kubelet-pods-dir: /var/snap/microk8s/common/var/lib/kubelet/pods
        kubelet-root: /var/snap/microk8s/common/var/lib/kubelet
```
