### ISSUE TITLE
Sidecar pods not closed after sucessfully VMI migration

### ISSUE THREAD

**Issue by yumingzhangmtk** [kubevirt/kubevirt#8395]
**What happened**:
VM setup with annoation: example-hook-sidecar. by trigger virtctl migrate <VM> to other Nodes.
VM is migrated to others Node with sidecar enable as expect. But the old sidecar pods didn't shutdown by itself. 

**What you expected to happen**:
sidecar pod also being shutdown automatically after successfully migration.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
virtctl migrate <VMI>
kubeget pods -o wide you will see something like this
 1/2     NotReady    0        

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.56
- Kubernetes version (use `kubectl version`): 1.23.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Thanks for the issue! Seems to me like the real issue. Are you looking to contribute the fix?

**Comment by yumingzhangmtk** [comment]
> Thanks for the issue! Seems to me like the real issue. Are you looking to contribute the fix?

YES. I'm tracking why this bug happened and try to fix in my local testing environment.

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten

@yumingzhangmtk Did you manage to fix this?

**Comment by rayjanoka** [comment]
I ran into this issue as well. I'm using a sidecar-injector to add containers to the `virt-launcher` pod and looking for a way to signal a shutdown after the `DOMAIN_SHUTDOWN_ACPI_POWER_BTN` stops the compute container after the migration. 

I tested the hookSidcar and found it had the same behavior.

**Comment by AmazingPangWei** [comment]
Hi, I've noticed this issue for a while. After learning about kubevirt source code, my analysis is as follows.

As we all know, virt-launcher uses sidecar hook to modify domain spec. There are some mechanisms to ensure that virt-launcher stops correctly if QEMU process exits. **Instead, There are no some mechanisms to notify sidecar hook containers to stop when virt-launcher exits.**

So In this issue, source QEMU process exits after VMI migration sucessfully and virt-launcher/virt-launcher-monitor process also exits, but sidecar hook containers keep running. 

**Maybe we should discuss a way about how virt-launcher-monitor tells  sidecar hook containers to stop itself.**

For example, sidecar hook containers implement a Shutdown() function, and virt-launcher-monitor call this function before it exits.

**Comment by victortoso** [comment]
Hi,

> So In this issue, source QEMU process exits after VMI migration sucessfully and virt-launcher/virt-launcher-monitor process also exits, but hook sidecar containers keep running.

That's correct. Also, a good description of the issue was made at https://github.com/kubevirt/kubevirt/issues/9838 - The Sidecar container does not receive the `SIGTERM`. After migration, most containers terminate properly like

```yaml
  volumecontainerdisk:
    Container ID:  cri-o://5706d6c112adcf840925a88fc36e02e1a5cac8963742ac90eee7a937c45727dc
    ...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 03 Jul 2023 20:18:37 +0200
      Finished:     Mon, 03 Jul 2023 20:19:33 +0200
    Ready:          False
    ...
```

While the `sidecar` container is still active:

```yaml
  hook-sidecar-0:
    Container ID:  cri-o://dc3343851b80c91e5a940db755c179dc7cd607e396ad8a0ebc224133702393eb
    ...
    State:          Running
      Started:      Mon, 03 Jul 2023 20:18:37 +0200
    Ready:          True 
```

> So In this issue, source QEMU process exits after VMI migration sucessfully and virt-launcher/virt-launcher-monitor process also exits, but hook sidecar containers keep running.

That's because `virt-handler` and `virt-launcher` do exchange temination messages, plus `virt-launcher-monitor` watches for SIGTERM and do proper cleanup/notification. Yes, that does not happen for `Sidecars`

> For example, hook sidecar containers implement a Shutdown() function, and virt-launcher-monitor call this function before it exits.

IIUC, `virt-launcher-monitor` does not see the `sidecar` container process, it would need `shareProcessNamespace` for that and not sure it would be enough to be able to pkil the `sidecar` process. So, the `Shutdown()` method looks reasonable, albeit it would mean generating a [v1alpha3](https://github.com/kubevirt/kubevirt/tree/main/pkg/hooks).

Another important point is that, the sidecar could potentially exit after the callback being called as both methods are meant to be used prior the VM start.

All in all, this is also a limitation in k8s, considering that the `compute` container terminated but the Pod stays dangling. It is being tracked by https://github.com/kubernetes/kubernetes/pull/116429
