### ISSUE TITLE
Could we set hostDisk to readonly mount while using it as a virtio-fs shared dir into VM

### ISSUE THREAD

**Issue by weixiao-huang** [kubevirt/kubevirt#8406]
**Is your feature request related to a problem? Please describe**:
I want to share host path readonly into the VM, so I write the vm yaml below

```
        devices:
          filesystems:
          - virtiofs: {}
            name: client-tools
      volumes:
      - hostDisk:
          path: /opt/client-tools/
          type: Disk
        name: client-tools
```

However, I found that there's no options for me to set the path `/opt/client-tools/` readonly into the VM. I must use `mount -t virtiofs -o ro client-tools /client-tools` to make it readonly in the guest os. But the user can also `umount /client-tools` and use `mount -t virtiofs client-tools /client-tools` to remount it as readWrite.

**Describe the solution you'd like**:

Add ReadOnly options in the `HostDisk`

```

// Represents a disk created on the cluster level
type HostDisk struct {
	// The path to HostDisk image located on the cluster
	Path string `json:"path"`
	// Contains information if disk.img exists or should be created
	// allowed options are 'Disk' and 'DiskOrCreate'
	Type HostDiskType `json:"type"`
	// Capacity of the sparse disk
	// +optional
	Capacity resource.Quantity `json:"capacity,omitempty"`
	// Shared indicate whether the path is shared between nodes
	Shared *bool `json:"shared,omitempty"`

	// Readonly indicate whether the path is readOnly in the guest VM
	ReadOnly *bool `json:"readOnly,omitempty"`
}
```

and readOnly mount the path from host to the vm pod if it's set to `true`

**Describe alternatives you've considered**:

Another option is to use a host path PVC. However, this solution is a little complicated since I've already known the host path but I must create the PVC to match the path ever. It seems stupid to create the PVC.

**Additional context**:
No
