### ISSUE TITLE
when using node port, the VM is accessible only from via the node it is actually running on

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#848]
According to documentation, as well as the behavior in case of containers, the VM should be accessible via the node port on any of the nodes of the cluster.
To reproduce, I use the kubevirt demo: https://github.com/kubevirt/demo and use the following yaml to expose SSH as a service from the cirros VM:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: testvm
  name: testnp
spec:
  ports:
  - name: testnp
    port: 22
  type: NodePort
  selector:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: testvm
status:
  loadBalancer: {}
```
Then, on a multi-node cluster I try to access the port on all nodes:
`ssh cirros@<node-public-ip> -p <node-port>`
It works only when I use the IP of the node, on which the VM actually runs. On the other nodes I get a connection timeout.
