### ISSUE TITLE
CloudInitConfigDrive has bad format if userData and networkData is passed at the same time

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#8551]
**What happened**:
When the following VMI is started

```yaml
apiVersion: kubevirt.io/v1                                                      
kind: VirtualMachineInstance                                                    
metadata:                                                                       
  name: fedora                                                                  
spec:                                                                           
  domain:                                                                       
    cpu:                                                                        
      cores: 2                                                                  
      model: host-model                                                         
    devices:                                                                    
      disks:                                                                    
      - disk:                                                                   
          bus: virtio                                                           
        name: containervolume                                                   
      - disk:                                                                   
          bus: virtio                                                           
        name: cloudinitvolume                                                   
      interfaces:                                                               
      - bridge: {}                                                              
        name: default                                                           
      - bridge: {}                                                              
        name: secondary                                                         
    resources:                                                                  
      requests:                                                                 
        memory: 1024M                                                           
  evictionStrategy: External                                                    
  networks:                                                                     
  - name: default                                                               
    pod: {}                                                                     
  - multus:                                                                     
      networkName: bridge-network-kvcluster                                     
    name: secondary                                                             
  volumes:                                                                      
  - containerDisk:                                                              
      image: registry:5000/kubevirt/fedora-with-test-tooling-container-disk:devel
      imagePullPolicy: IfNotPresent                                             
    name: containervolume                                                       
  - cloudInitNoCloud:                                                           
      networkData: |                                                            
        version: 2                                                              
        ethernets:                                                              
          eth0:                                                                 
            dhcp4: true                                                         
            dhcp6: true                                                         
          eth1:                                                                 
            addresses: [ 192.168.3.3/24 ]                                       
            dhcp4: false                                                        
            dhcp6: false                                                        
            gateway4: 192.168.3.1                                               
      userData: |-                                                              
        #cloud-config                                                           
        password: fedora                                                        
        chpasswd: { expire: False }                                             
    name: cloudinitvolume                                                       
```

The cloud-init is not loaded and failing with error 

```
 cloud-init[653]: 2022-09-30 08:54:56,336 - util.py[WARNING]: Broken config drive: /dev/vdb
```

**What you expected to happen**:
The cloud-init sectin to be applied correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the VMI from the description and virtctl console it.

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.53.0
- Kubernetes version (use `kubectl version`): 1.23
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
