### ISSUE TITLE
Can't add spec.nodeSelector in vmi object.

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#8581]
**What happened**:
I want to select the target when migration vmi. Just like https://github.com/kubevirt/kubevirt/issues/7105 said, I try to edit or add `spec.nodeSelector` in VMI object, but update is restricted.

**What you expected to happen**:
add or update `spec.nodeSelector` in VMI object succeed
or someone can tell me how to select a target when migration vmi.

**How to reproduce it (as minimally and precisely as possible)**:
create a vm zal-cirros-vm

yaml

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-cirros-datavolume
  name: zal-cirros-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-datavolume
    spec:
      domain:
        devices:
          interfaces:
          - name: default
            masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: zal-upload-dv
        name: datavolumevolume
      networks:
      - name: default
        pod: {} # Stock pod network

```

virtctl start vm zal-cirros-vm

kubectl edit vmi zal-cirros-vm

just add spec.nodeSelector 

![image](https://user-images.githubusercontent.com/49519342/194984330-9c0ffdd7-490e-403a-aaee-405bf6f5673c.png)

but update is restricted

**Additional context**:
I find some discussion may be related to my issue, https://github.com/kubevirt/kubevirt/pull/6550

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
