### ISSUE TITLE
virt-handler: error registering with device plugin manager

### ISSUE THREAD

**Issue by fengye87** [kubevirt/kubevirt#8589]
**What happened**:
I tried to run the sample VM on a vanilla Kubernetes + KubeVirt cluster, and the launcher pod failed to be scheduled with the error `0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm, 1 Insufficient devices.kubevirt.io/tun, 1 Insufficient devices.kubevirt.io/vhost-net, 1 node(s)  │
│ didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.`.

virt-handler is constantly printing the following log:

```json
{"component":"virt-handler","level":"error","msg":"Error starting tun device plugin","pos":"device_controller.go:69","reason":"error registering with device plugin manager: rpc error: code = Unknown desc = failed to dial device plugin:
context deadline exceeded","timestamp":"2022-10-12T02:21:49.376221Z"}
{"component":"virt-handler","level":"error","msg":"Error starting kvm device plugin","pos":"device_controller.go:69","reason":"error registering with device plugin manager: rpc error: code = Unknown desc = failed to dial device plugin:
context deadline exceeded","timestamp":"2022-10-12T02:21:49.377623Z"}
{"component":"virt-handler","level":"error","msg":"Error starting vhost-net device plugin","pos":"device_controller.go:69","reason":"error registering with device plugin manager: rpc error: code = Unknown desc = failed to dial device pl
ugin: context deadline exceeded","timestamp":"2022-10-12T02:21:49.430850Z"}
```

**What you expected to happen**:
The sample VM should be scheduled and run.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install KubeVirt following the doc
2. Create the sample VM

**Additional context**:
This is a nested virt cluster, but I can confirm the nested virt is on using `virsh capabilities` command on each k8s node.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.57.1
- Kubernetes version (use `kubectl version`): v1.25.2
- VM or VMI specifications: 

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: emptydisk
          disk:
            bus: virtio
        - disk:
            bus: virtio
          name: cloudinitdisk
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
    - name: emptydisk
      emptyDisk:
        capacity: "2Gi"
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Rocky 8
- Kernel (e.g. `uname -a`): `Linux kube-1 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Tue Aug 2 16:19:42 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A
