### ISSUE TITLE
OVM static endpoint

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#861]
OVMs are meant to be immortal, but the underlying tech that supports OVMs (pods) are mortal. Between each OVM start/stop/start sequence, a new pod is created to host the VM.  This means that the same OVM will have multiple pod IPs throughout it's lifecycle.

Users who want access a OVM using an address that is static and consistent between restarts will have to couple OVMs with a k8s service using a ClusterIP. This requires manually maintaining both the individual OVM object and the Service object.

If this relationship between OVM and k8s service is desirable enough, we should consider providing a shortcut that allows users to specific ports that they want to be statically accessible throughout the OVMs lifecycle. The OVM controller would then automatically generate the service endpoint for the OVM.

Example: Create an OVM and specify that you want static ssh and rdp access. Behind the scenes the OVM controller creates a ClusterIP that can be used to access those ports.  The ClusterIP will be accessible in the OVMs status field after creation.
```
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  name: testvm
spec:
  running: true
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
    - port: 3389
      targetPort: 3389
      protocol: TCP
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 64M
        devices:
          disks:
            - name: registrydisk
              volumeName: registryvolume
              disk:
                bus: virtio
      volumes:
        - name: registryvolume
          registryDisk:
            image: kubevirt/cirros-registry-disk-demo:devel
```
