### ISSUE TITLE
[CI] [SR-IOV] - Failures about "Could not find available sriov PFs on host"

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#8656]
**What happened**:
SR-IOV jobs fails lately a lot due to missing PFs.

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8605/pull-kubevirt-e2e-kind-1.22-sriov-nonroot/1582284078319669248#1:build-log.txt%3A1093

**What you expected to happen**:
The PFs should be available and the job should pass.
The under cloud CNI allocates 2 PFs per job.

**How to reproduce it (as minimally and precisely as possible)**:
Currently it seems to happen on CI when the node schedules jobs of all kinds.

**Additional context**:
It seems that it happens when 2 jobs of SR-IOV run at the same time (same node bare-metal-sriov-2)
check the timestamps in the log itself (not the ones of the spyglass plugin), see there is an overlap
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-kind-1.22-sriov/1584289666981433344
`21:05:04 - 21:26:54`
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8628/pull-kubevirt-e2e-kind-1.22-sriov/1584290688520949760
`21:09:03 - 21:31:41`
We can see that the 2nd started before the first finished (both on 23/10, times are UTC)
Currently the SR-IOV lane assumes as prerequisites that it runs serially only on each node.

Note that looking on the pod yaml, it seems that some labels are missing
for example "sriov-pod".
This label controllers the anti affinity so the job won't run parallel on each node.
Note that more labels are missing (i.e preset-dind-enabled), but we
do see in the logs "Docker in Docker enabled, initializing..."
So I wonder if it is only visible.
However we do see the timestamps overlap.

Reference of a job that failed for "regular" reasons, in order to see the labels that are there.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8641/pull-kubevirt-e2e-kind-1.22-sriov/1583553261384765440

Note that I ran 20 times (serially) SR-IOV lane until after cluster-up, and all passed,
when the node was idle.

Maybe the bad ones are the tide ones ?
`created-by-tide: "true"` (i see tide on them)
possible that the annotations are missing when running with tide ?
`k8s.v1.cni.cncf.io/networks: multus-cni-ns/sriov-passthrough-cni,multus-cni-ns/sriov-passthrough-cni`
(and their results in the manifest + their effect which is PF allocation)
Unless we never see the info on tide jobs.

Here we can see a job which is not a batch and miss the label / annotation etc
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8442/pull-kubevirt-e2e-kind-1.22-sriov/1584472825538809856
(note that it indeed ran by tide on a lgtm approve PR IIUC)

We might able to see the running pods themselves and check if indeed they miss annotation.
We can also create a better pairing between the CNI logs and the jobs.
To understand the CNI did run on them (for example the CNI can create a file in the job).

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rmohr** [comment]
I don't see a pod anti affinity on the sriov jobs. That is probably what you need, since even limiting the jobs to 1 may not be a solution for tide. Can that be?

**Comment by rmohr** [comment]
Oh, now I see it:

```
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: sriov-pod
            operator: In
            values:
            - "true"
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchExpressions:
          - key: sriov-pod-multi
            operator: In
            values:
            - "true"
        topologyKey: kubernetes.io/hostname
        ```
        
        but maybe double-checking it makes sense.
