### ISSUE TITLE
Hotplug Volume Problem

### ISSUE THREAD

**Issue by MLintin** [kubevirt/kubevirt#8695]
**Is your feature request related to a problem? Please describe**:
I create a vm with set the cdrom to hotplug.  after the vm running,  console can't enter the cdrom install process

**Describe the solution you'd like**:
i want hotplug the cdrom after install complete.

**Additional context**:
```
spec:
  dataVolumeTemplates:
  - metadata:
      name: dv-disk-1
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 30Gi
        storageClassName: xxxxx
        volumeMode: Block
      source:
        blank: {}
  running: true
  template:
    metadata:
    spec:
      domain:
        cpu:
          cores: 1
          model: host-model
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            cache: none
            disk:
              bus: virtio
            name: disk-1
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdrom-1
          interfaces:
            - masquerade: {}
              name: default
        firmware:
          bootloader:
            bios:
              useSerial: true
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
      - dataVolume:
          name: dv-disk-1
        name: disk-1
      - dataVolume:
          hotpluggable: true
          name: ubuntu
        name: cdrom-1
```
```
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 8Gi
    storageClassName: xxxxxxx
  source:
    http:
      url: http://xxxxxxxxxxx:8008/download/CentOS-8.2.2004-x86_64-dvd1.iso
```

![image](https://user-images.githubusercontent.com/38847719/198819478-6607dd4b-5985-47fe-981f-8aa8755555fe.png)
