### ISSUE TITLE
Support live migrate a vm to a specified node

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8713]
**Is your feature request related to a problem? Please describe**:

I've looked live migration related docs and APIs, but seems there's no way to make a vm live migrate to a specified node.  

**Describe the solution you'd like**:

Maybe add a target object to `vmim` spec , like below : 
```go
type VirtualMachineInstanceMigrationSpec struct {
    // The name of the VMI to perform the migration on. VMI must exist in the migration objects namespace
    VMIName string `json:"vmiName,omitempty" valid:"required"`
    // The name of the target node where the VMI want 
    TargetNodeName string `json:"targetNodeName,omitempty"`
}
```

**Describe alternatives you've considered**:

n/a

**Additional context**:

n/a

**Comment by ormergi** [comment]
Hi @chenxinlong, note that the idea is to let the scheduler figure out where the VM should be migrated to.
Have you tried adding some affinity rules?

**Comment by chenxinlong** [comment]
I haven't try it.  

How should I do ?  Firstly update the spec of vmi(modify schedule related properties) and then create a vmim ?

**Comment by ormergi** [comment]
> How should I do ? Firstly update the spec of vmi(modify schedule related properties) and then create a vmim ?

Create the VM, apply node affinity rule and start the migration.
See the following node-affinity rule example, it should make the VM schedule at "node02.example.com" node:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
  name: vm-cirros
spec:
  running: true
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02.example.com
...
```
