### ISSUE TITLE
CRDs for hotplug volumes and interfaces

### ISSUE THREAD

**Issue by bc185174** [kubevirt/kubevirt#8763]
**Is your feature request related to a problem? Please describe**:

Currently, we can only use the `virtctl` CLI or send a request to the API to add/remove hotplug disks (and soon from this [PR](https://github.com/kubevirt/kubevirt/pull/6852) hotplug NICs). The `virtctl` binary is ideal for manual intervention by a user; however, this is a brittle solution when it comes to automation and running commands on the host. In terms of upgrading, it also goes against Kubernetes best-practices where the binary cannot be updated using convention OCI images. It could be packaged and released in a pod but again, it is still a brittle solution when it comes to automation. On the other hand, using the API requires the end-user to deploy some controller or code to send those requests and is prone to errors. 

**Describe the solution you'd like**:

We can use the existing patterns in Kubernetes which KubeVirt already employs for snapshot management and create CR's to trigger a process. This is consistent with the existing implementation in KubeVirt.

Example for Hotplug Volumes:

```
apiVersion: volumes.kubevirt.io/v1alpha1
kind: VirtualMachineAddVolume
metadata:
  name: <name>
spec:
  source:
    volumeName: <volume-name>
    serial: <serial>
    persist: <boolean>
```

```
apiVersion: volumes.kubevirt.io/v1alpha1
kind: VirtualMachineRemoveVolume
metadata:
  name: <name>
spec:
  source:
    volumeName: <volume-name>
```

**Describe alternatives you've considered**:

N/A

**Additional context**:

Hotplug NICs is dependant on https://github.com/kubevirt/kubevirt/pull/6852.

**Comment by alicefr** [comment]
@bc185174 
A couple of comments, I don't think we need 2 CRDs but a single one that you create or delete. I don't see the VM name where to attach the storage, is it missing?

**Comment by bc185174** [comment]
Yes definitely missing the VM name. I think for clarity and consistency (with existing implementations), they should be separate CRDs - more so because they trigger two different behaviours.

```yaml
apiVersion: volumes.kubevirt.io/v1alpha1
kind: VirtualMachineAddVolume
metadata:
  name: <name>
spec:
  source:
    vm: <vm-name>
    volume: <volume-name>
    serial: <serial>
    persist: <boolean>
```

```yaml
apiVersion: volumes.kubevirt.io/v1alpha1
kind: VirtualMachineRemoveVolume
metadata:
  name: <name>
spec:
  source:
    vm: <vm-name>
    volume: <volume-name>
```

Otherwise with one CRD it would look something like the following which is a bit brittle given the different parameters and behaviours.

```yaml
apiVersion: volumes.kubevirt.io/v1alpha1
kind: VirtualMachineHotplugVolume
metadata:
  name: <name>
spec:
  source:
    vm: <vm-name>
    volume: <volume-name>
    type: <remove or add>
    serial: <serial>
    persist: <boolean>
```
