### ISSUE TITLE
Broken VMI migration for hostpath-csi PVC

### ISSUE THREAD

**Issue by wigust** [kubevirt/kubevirt#8771]
VMI provisioned to hostpath-csi [1] use live migration type instead of block type [2]:
```
$ kubectl describe virtualmachineinstance.kubevirt.io/myvm
...
Migration Method:                  LiveMigration
```

Probably because of this migration does not work with hostpath-csi.

Also Kubernetes scheduler reports:
```
7 node(s) had volume node affinity conflict.
```
where cluster has 8 nodes in total (1 of 8 node running virtual machine `myvm`).

[1] https://github.com/kubevirt/hostpath-provisioner-operator/releases/tag/v0.14.0
[2] Constants describing migration methods:  https://github.com/kubevirt/kubevirt/blob/d11ac64e45d434cdafb11bd82090f1eb9f91eb9b/staging/src/kubevirt.io/api/core/v1/types.go#L676-L681

**What you expected to happen**:

Virtual machine with hostpath-csi as a PVC storage Migration Method is setted to BlockMigration

**How to reproduce it (as minimally and precisely as possible)**:

Install the hostpath-csi operator.
https://github.com/kubevirt/hostpath-provisioner-operator/releases/tag/v0.14.0

Configure as describe in the operator's documentation.
``` yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-csi
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePool: local
```

``` yaml
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: Always
  storagePools:
    - name: "local"
      path: "/var/hpvolumes"
  workload:
    nodeSelector:
      kubernetes.io/os: linux
```

Create a virtual machine.
``` yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm
spec:
  dataVolumeTemplates:
    - metadata:
        name: myvm-data-volume
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 16Gi
          storageClassName: hostpath-csi
        source:
          http:
            url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2 # any other qcow
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: myvm
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          disks:
            - disk:
                bus: virtio
              name: myvm-data-volume-disk
        resources:
          requests:
            memory: 2G
      volumes:
        - name: myvm-data-volume-disk
          dataVolume:
            name: myvm-data-volume
      networks:
        - name: default
          pod: {}
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): v1.25.3
- VM or VMI specifications: VMI
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): NixOS 22.11 (Raccoon)
- Kernel (e.g. `uname -a`): 5.15.76
- Install tools: N/A
- Others: N/A
