### ISSUE TITLE
dedicatedCPUPlacement is not usable when set within an instance type 

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#8867]
/area instancetype

**What happened**:

`dedicatedCPUPlacement` is not currently usable when set on an instance type as instance types do not currently support resource requests. This will eventually cause the following VMI create validation check to fail:

https://github.com/kubevirt/kubevirt/blob/55f993a1a8f9385b60d0b74ba73ac7fb9113789f/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1074

https://github.com/kubevirt/kubevirt/blob/55f993a1a8f9385b60d0b74ba73ac7fb9113789f/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1237-L1249

```
**The request is invalid: spec.template.spec.domain.resources.limits.memory: spec.template.spec.domain.resources.requests.memory or spec.template.spec.domain.resources.limits.memory should be provided**
```

Work is however on going to support resource requests within instance types below:

https://github.com/kubevirt/kubevirt/pull/8729

**What you expected to happen**:

We should always reject an instance type during submission if `dedicatedCPUPlacement` is set without any resource requirements.

**How to reproduce it (as minimally and precisely as possible)**:

Create and apply the following instance type to a `VirtualMachine` :
```
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: VirtualMachineInstancetype
metadata:
 name: demo
 namespace: default
spec:
 cpu:
  dedicatedCPUPlacement: true
  guest: 1
 memory: 
  guest: 128Mi
```

Launching the `VirtualMachine` will lead to a validation error.

**Additional context**:
N/A

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
