### ISSUE TITLE
SyncVMI failed LibvirtError noCloud.iso: Permission denied

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#8880]
**What happened**:
When I started a VM, I saw that the virt-launcher pod kept crashing and restarting.
Its log display references this image.
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/8120555/204790231-85f26cac-0697-4e10-ae0a-d89d06d175f3.png">

**What you expected to happen**:
The virtual machine starts properly

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.53.1
- Kubernetes version (use `kubectl version`): v1.21.10
- VM or VMI specifications: 
```yaml
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: a2-rootfs
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: local-rook-cephfs-sc
          volumeMode: Filesystem
        source:
          registry:
            url: docker://192.168.181.210:60080/3rdparty/vmdisks/ubuntu:18.04
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootfs
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      nodeSelector:
        vm.cpaas.io/baremetal: 'true'
      volumes:
        - dataVolume:
            name: a2-rootfs
          name: rootfs
        - cloudInitNoCloud:
            networkData: |-
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
            userData: |-
              #cloud-config
              disable_root: false
              ssh_pwauth: true
              users:
                - default
                - name: root
                  lock_passwd: false
                  hashed_passwd: $6$qjie1r78$ai8vARndAPh38jRRFiX0ywKKuCu/c/SbY/Mg0PI7Csc9gGyToXSzrd/LzCBLp5nFccggTu/Hb1nbr1t.swaq2.
          name: cloudinitdisk
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  
```bash
cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
```
- Kernel (e.g. `uname -a`): 
```sh
Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.x86_64 #1 SMP Mon May 24 12:14:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: N/A
- Others: N/A
