### ISSUE TITLE
domain configuration does not support video model 'virtio' on ARM64 

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#8900]
**What happened**:
The virtual machine fails to start. The virt-launcher pod log is displayed as follows
```sh
2022-12-02 {"component":"virt-launcher","level":"error","msg":"unsupported configuration: domain configuration does not support video model 'virtio'","pos":"qemuValidateDomainDeviceDefVideo:2471","subcomponent":"libvirt","thread":"29","timestamp":"2022-12-02T08:55:04.288000Z"}
2022-12-02 {"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"armvm","namespace":"guojing-arm","pos":"libvirt_helper.go:133","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: domain configuration does not support video model 'virtio'')","timestamp":"2022-12-02T08:55:04.288852Z","uid":"4a648f44-d009-42cc-93cd-71356410f6d4"}
2022-12-02 {"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"armvm","namespace":"guojing-arm","pos":"server.go:184","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: domain configuration does not support video model 'virtio'')","timestamp":"2022-12-02T08:55:04.288885Z","uid":"4a648f44-d009-42cc-93cd-71356410f6d4"}
```

**What you expected to happen**:
The VM can be started and connected to using vnc.

**How to reproduce it (as minimally and precisely as possible)**:
My VM spec yaml is
```yaml
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: armvm-rootfs
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: arm-vm-topo
          volumeMode: Block
        source:
          registry:
            url: docker://192.168.254.222:11443/3rdparty/vmdisks/centos:7.9
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootfs
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: virt
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - dataVolume:
            name: armvm-rootfs
          name: rootfs
        - cloudInitNoCloud:
            networkData: |-
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
                  - type: physical
                    name: enp1s0
                    subnets:
                      - type: dhcp
            userData: >-
              #cloud-config

              disable_root: false

              ssh_pwauth: true

              users:
                - default
                - name: root
                  lock_passwd: false
                  hashed_passwd: $6$u47cgg1a$vjJPYxCGeH6mJe2YGG3h78iJH4q6c.VEBcuLpDmpNjuE7/IIxZGveO6.faEBufo0gDSgfWyHU4bqKefjM0Bz91
          name: cloudinitdisk
```

**Additional context**:
We can start VMs normally in other ARM physical machine environments, but this environment is the only one that has problems.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.53.1
- Kubernetes version (use `kubectl version`): v1.23.13
- VM or VMI specifications: 
   It has been provided above.
- Cloud provider or hardware configuration: 
  CPU: 96core  Memery: 512G
- OS (e.g. from /etc/os-release):
```sh
cat /etc/os-release
PRETTY_NAME="UnionTech OS Server 20 Enterprise"
NAME="UnionTech OS Server 20 Enterprise"
VERSION_ID="20"
VERSION="20"
ID=UOS
HOME_URL="https://www.chinauos.com/"
BUG_REPORT_URL="http://bbs.chinauos.com"
VERSION_CODENAME=fou
```
- Kernel (e.g. `uname -a`):
```sh
Linux arm-60 4.19.0-arm64-server #3017 SMP Thu Nov 12 19:54:04 CST 2020 aarch64 GNU/Linux
```
- Install tools: N/A
- Others: N/A
