### ISSUE TITLE
Unable to open /dev/kvm: Permission denied

### ISSUE THREAD

**Issue by tydic-com** [kubevirt/kubevirt#8949]
**What happened**:
vmi: 
```
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  44s                 virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-host-network-jptfp
  Warning  SyncFailed        19s (x13 over 39s)  virt-handler               lstat /proc/344846/root/sys/class/net/ns1: no such file or directory
```
virt-launcher pod log: 
```
Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
Unable to open /dev/kvm: Permission denied
internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory
```

**What you expected to happen**:
virtual instance up and running

**How to reproduce it (as minimally and precisely as possible)**:
Deployed below yaml on kubevirt v0.58.0:

```
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: macvtapnetwork
  namespace: ns1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/eth0
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvtapnetwork",
      "type": "macvtap",
      "mtu": 1500
    }'
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-host-network
  name: vmi-host-network
  namespace: ns1
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - macvtap: {}
        name: hostnetwork
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 4024M
  networks:
  - multus:
      networkName: ns1/macvtapnetwork
    name: hostnetwork
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-with-test-tooling-container-disk:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
    name: cloudinitdisk
```

**Additional context**:
```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2022-12-14T10:40:04.895432Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2022-12-14T10:40:04.895484Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/libvirt-sock","pos":"libvirt.go:497","timestamp":"2022-12-14T10:40:04.896097Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:505","timestamp":"2022-12-14T10:40:04.896515Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 8.0.0, package: 2.module_el8.6.0+1087+b42c8331 (CentOS Buildsys \u003cbugs@centos.org\u003e, 2022-02-08-22:20:52, )","subcomponent":"libvirt","thread":"45","timestamp":"2022-12-14T10:40:04.913000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vmi-host-network","subcomponent":"libvirt","thread":"45","timestamp":"2022-12-14T10:40:04.913000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1325","subcomponent":"libvirt","thread":"45","timestamp":"2022-12-14T10:40:04.913000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:128","subcomponent":"libvirt","thread":"45","timestamp":"2022-12-14T10:40:04.913000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:101","subcomponent":"libvirt","thread":"45","timestamp":"2022-12-14T10:40:04.913000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:513","timestamp":"2022-12-14T10:40:05.397628Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:510","timestamp":"2022-12-14T10:40:05.400177Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:74","timestamp":"2022-12-14T10:40:05.400343Z"}
... ...
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): v1.25.4
- VM or VMI specifications: centos based iso (Non cloud)
- Cloud provider or hardware configuration: DELL
- OS (e.g. from /etc/os-release):  openEuler 22.09
- Kernel (e.g. `uname -a`): Linux 5.10.0-106.18.0.68.oe2209.x86_64
- Install tools: containerd v1.6.12/qemu-10:6.2.0-49.oe2209.x86_64/libvirt-6.2.0-45.oe2209.x86_64
- Others: Multus plugin installed

**Comment by usrbinkat** [comment]
Thanks for raising this issue.

openEuler is new to me, is this AppArmor based? My first guess will be to investigate that as a possible root cause for this permission error on /dev/kvm

**Comment by tydic-com** [comment]
> Thanks for raising this issue.  

> openEuler is new to me, is this AppArmor based? My first guess will be to investigate that as a possible root cause for this permission error on /dev/kvm

**Comment by tydic-com** [comment]
> > Thanks for raising this issue.
> 
> > openEuler is new to me, is this AppArmor based? My first guess will be to investigate that as a possible root cause for this permission error on /dev/kvm

It is based on SELINUX:
cat /etc/sysconfig/selinux
SELINUX=disabled
SELINUXTYPE=targeted

**Comment by vwbusguy** [comment]
Seeing this now myself on Fedora 37, with or without SELinux enforcing.  Running with kind rootless via podman.  Tried with or without systemd-run and same result.

**Comment by vwbusguy** [comment]
It appears to be a problem with running podman rootless.  When creating the cluster and resources with `sudo`, it deploys.  As regular user, it fails to deploy with a crash backoff loop.

**Comment by xpivarc** [comment]
@vwbusguy For the kind case, can you check what devices are allowed on the node(container) and in the virt-launcher?

**Comment by xujunjie-cover** [comment]
It's a bug. I'm trying to reslov it.

**Comment by zakkg3** [comment]
see the same on ubuntu + crio +  k0s.
 
 I had to make a few [workarrounds](https://github.com/kubevirt/kubevirt/issues/10123#issuecomment-1717525723) to make it work (for a few minutes)...
 
 I finally get the same virt-launcher logs:
 
 ```shell
 {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-09-14T08:51:14.335802Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-09-14T08:51:14.336181Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:524","timestamp":"2023-09-14T08:51:14.337547Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:532","timestamp":"2023-09-14T08:51:14.345522Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )","subcomponent":"libvirt","thread":"39","timestamp":"2023-09-14T08:51:14.362000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: fedora","subcomponent":"libvirt","thread":"39","timestamp":"2023-09-14T08:51:14.362000Z"}

{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"39","timestamp":"2023-09-14T08:51:14.362000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"39","timestamp":"2023-09-14T08:51:14.363000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"39","timestamp":"2023-09-14T08:51:14.363000Z"}


{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:540","timestamp":"2023-09-14T08:51:14.847410Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:539","timestamp":"2023-09-14T08:51:14.856936Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-09-14T08:51:14.857246Z"}

{"component":"virt-launcher","level":"info","msg":"Received signal terminated","pos":"virt-launcher.go:457","timestamp":"2023-09-14T08:51:17.571295Z"}
{"component":"virt-launcher","level":"info","msg":"stopping cmd server","pos":"server.go:611","timestamp":"2023-09-14T08:51:17.571345Z"}
{"component":"virt-launcher","level":"info","msg":"cmd server stopped","pos":"server.go:620","timestamp":"2023-09-14T08:51:17.571445Z"}
{"component":"virt-launcher","level":"info","msg":"Exiting...","pos":"virt-launcher.go:493","timestamp":"2023-09-14T08:51:17.571464Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 0","pos":"virt-launcher-monitor.go:125","timestamp":"2023-09-14T08:51:17.573613Z"}
```

so it tries libvirtd fails. then complain about /dev/kvm and then finally livritd connects but then receives the kill.

Vm is the fedora example:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
  namespace: vms
  labels:
    metallb-service: fedoravm
spec:
  running: true
  template:
    metadata:
      labels:
        metallb-service: fedoravm
    spec:
      nodeSelector:
        kubernetes.io/hostname: eu-k8s-stg-10.ethz.ch
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            # - disk:
            #     bus: virtio
            #   name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
        resources:
          requests:
            memory: 1024M
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: quay.io/kubevirt/fedora-cloud-container-disk-demo:v0.36.5
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              packages:
                - nginx
              runcmd:
                - [ "systemctl", "enable", "--now", "nginx" ]
          name: cloudinitdisk
```


virt-handler:

```shell
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:242","timestamp":"2023-09-14T09:28:56.724465Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[kvm995],}]","pos":"generic_device.go:243","timestamp":"2023-09-14T09:28:56.724501Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:242","timestamp":"2023-09-14T09:28:56.725108Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[tun952],}]","pos":"generic_device.go:243","timestamp":"2023-09-14T09:28:56.725135Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:242","timestamp":"2023-09-14T09:28:56.726646Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[vhost-net537],}]","pos":"generic_device.go:243","timestamp":"2023-09-14T09:28:56.726668Z"}


{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"fedora","namespace":"vms","pos":"vm.go:1759","timestamp":"2023-09-14T09:29:03.135492Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of containerdisk volume","name":"fedora","namespace":"vms","pos":"vm.go:2429","timestamp":"2023-09-14T09:29:03.150294Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of cloudinitdisk volume","name":"fedora","namespace":"vms","pos":"vm.go:2429","timestamp":"2023-09-14T09:29:03.150332Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"fedora","namespace":"vms","pos":"vm.go:1759","timestamp":"2023-09-14T09:29:03.188083Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 12a38eb8-ec89-4d76-85c7-030b26f50487","name":"fedora","namespace":"vms","pos":"vm.go:2023","timestamp":"2023-09-14T09:29:03.188140Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"fedora","namespace":"vms","pos":"mount.go:349","timestamp":"2023-09-14T09:29:03.188186Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"fedora","namespace":"vms","pos":"mount.go:769","timestamp":"2023-09-14T09:29:03.188204Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"fedora","namespace":"vms","pos":"vm.go:2057","timestamp":"2023-09-14T09:29:03.188253Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"fedora","namespace":"vms","pos":"vm.go:1759","timestamp":"2023-09-14T09:29:03.202833Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 12a38eb8-ec89-4d76-85c7-030b26f50487","name":"fedora","namespace":"vms","pos":"vm.go:2023","timestamp":"2023-09-14T09:29:03.202959Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"fedora","namespace":"vms","pos":"mount.go:349","timestamp":"2023-09-14T09:29:03.203007Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"fedora","namespace":"vms","pos":"mount.go:769","timestamp":"2023-09-14T09:29:03.203027Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"fedora","namespace":"vms","pos":"vm.go:2057","timestamp":"2023-09-14T09:29:03.203072Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"fedora","namespace":"vms","pos":"vm.go:1759","timestamp":"2023-09-14T09:29:03.234889Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 12a38eb8-ec89-4d76-85c7-030b26f50487","name":"fedora","namespace":"vms","pos":"vm.go:2023","timestamp":"2023-09-14T09:29:03.234954Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"fedora","namespace":"vms","pos":"mount.go:349","timestamp":"2023-09-14T09:29:03.234996Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"fedora","namespace":"vms","pos":"mount.go:769","timestamp":"2023-09-14T09:29:03.235016Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"fedora","namespace":"vms","pos":"vm.go:2057","timestamp":"2023-09-14T09:29:03.235062Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"fedora","namespace":"vms","pos":"vm.go:1759","timestamp":"2023-09-14T09:29:03.252710Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 12a38eb8-ec89-4d76-85c7-030b26f50487","name":"fedora","namespace":"vms","pos":"vm.go:2023","timestamp":"2023-09-14T09:29:03.252770Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"fedora","namespace":"vms","pos":"mount.go:349","timestamp":"2023-09-14T09:29:03.252806Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"fedora","namespace":"vms","pos":"mount.go:769","timestamp":"2023-09-14T09:29:03.252844Z","uid":"12a38eb8-ec89-4d76-85c7-030b26f50487"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"fedora","namespace":"vms","pos":"vm.go:2057","timestamp":"2023-09-14T09:29:03.252889Z","uid":""}
```
