### ISSUE TITLE
 Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io"

### ISSUE THREAD

**Issue by EvenChang** [kubevirt/kubevirt#9001]
**What happened**:
when I apply vm.yaml it will cause this error message.

Error from server (InternalError): error when creating "vm.yaml": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": dial tcp 10.103.152.30:443: i/o timeout

After I downgrade kubevirt and k8s will cause this error, how can I resolve it ?

**What you expected to happen**:
It should work normally.

**How to reproduce it (as minimally and precisely as possible)**:
When I downgrade k8s and kubevirt version it will happend.

**Additional context**:
```
kubevirt         virt-api-65f75df4c6-bwfqv                 1/1     Running   0          69m
kubevirt         virt-api-65f75df4c6-q4hr9                 1/1     Running   0          69m
kubevirt         virt-controller-6448c44869-77zfx          1/1     Running   0          69m
kubevirt         virt-controller-6448c44869-vhbms          1/1     Running   0          69m
kubevirt         virt-handler-trzd2                        1/1     Running   0          69m
kubevirt         virt-handler-zjsd8                        1/1     Running   0          69m
kubevirt         virt-operator-6645fc4f6-7cj6n             1/1     Running   0          70m
kubevirt         virt-operator-6645fc4f6-x2t5m             1/1     Running   0          70m
```
vm.yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
  labels:
    special: key
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`):v1.20.15
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS
- Kernel (e.g. `uname -a`):  5.4.0-135-generic  x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A
