### ISSUE TITLE
Ubuntu Desktop on Kubevirt

### ISSUE THREAD

**Issue by 0GiS0** [kubevirt/kubevirt#9007]
Hi all!

I'm testing Kubevirt and I'm trying to deploying Ubuntu Desktop the best way I can. Right now, what I have is the following YAML:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-ubuntu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi

---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: ubuntu-desktop
  name: ubuntu-desktop
spec:
  domain:
    devices:
      disks:
        - cdrom:
            bus: sata
          name: ubuntuiso
          bootOrder: 1
        - disk:
            bus: virtio
          name: hd
          bootOrder: 2
      interfaces:
        - name: default
          bridge: {}
    resources:
      requests:
        memory: 4Gi
    cpu:
      cores: 2
  networks:
    - name: default
      pod: {}
  volumes:
    - name: ubuntuiso
      persistentVolumeClaim:
        claimName: ubuntu-desktop
    - name: hd
      persistentVolumeClaim:
        claimName: disk-ubuntu
```

The first time that I need to install Ubuntu works great because the boot order is 1 for the CDROM/Ubuntu Desktop ISO. However, when I restart the VM or It needs to be restarted you cannot move forward because of the boot order. It waits for a new installation and I doesn't skip like in Windows. So my first solution was delete the VMI, change the boot order, keep the same disk (ubuntu-disk) and now It works but I assume that there is a better way to do this.... but I couldn't find it.

Any ideas?

Thank you so much!

**Comment by Longchuanzheng** [comment]
Maybe you can change the bootOrder
```
        - cdrom:
            bus: sata
          name: ubuntuiso
          bootOrder: 2
        - disk:
            bus: virtio
          name: hd
          bootOrder: 1
```
this works for me.
