### ISSUE TITLE
VM status always CrashLoopBackOff

### ISSUE THREAD

**Issue by huangpxs** [kubevirt/kubevirt#9015]
I already deployed kubevirt, but when I deploy vm that status always CrashLoopBackOff

kubevirt status:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/29647491/210515937-6645f26a-e369-433e-a7d9-817e0b7e0da3.png">

vm status:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/29647491/210517408-209fedeb-78b9-40e3-a060-258d6ea25bcd.png">

vm.yaml:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
  namespace: kubevirt
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: XXXX/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
```

describe vm:

```
Name:         testvm
Namespace:    kubevirt
Labels:       <none>
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2023-01-04T08:52:40Z
  Generation:          2
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2023-01-04T08:52:40Z
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:template:
          .:
          f:metadata:
            .:
            f:labels:
              .:
              f:kubevirt.io/domain:
              f:kubevirt.io/size:
          f:spec:
            .:
            f:domain:
              .:
              f:devices:
                .:
                f:disks:
                f:interfaces:
              f:resources:
                .:
                f:requests:
                  .:
                  f:memory:
            f:networks:
            f:volumes:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-01-04T08:52:40Z
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:running:
    Manager:      kubectl-patch
    Operation:    Update
    Time:         2023-01-04T08:53:06Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:printableStatus:
        f:startFailure:
          .:
          f:consecutiveFailCount:
          f:lastFailedVMIUID:
          f:retryAfterTimestamp:
        f:volumeSnapshotStatuses:
    Manager:         Go-http-client
    Operation:       Update
    Subresource:     status
    Time:            2023-01-04T08:53:40Z
  Resource Version:  47339936
  Self Link:         /apis/kubevirt.io/v1/namespaces/kubevirt/virtualmachines/testvm
  UID:               2ceb03e1-3b3e-4fad-9815-02b3e3d46159
Spec:
  Running:  true
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt.io/domain:  testvm
        kubevirt.io/size:    small
    Spec:
      Domain:
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   containerdisk
            Disk:
              Bus:  virtio
            Name:   cloudinitdisk
          Interfaces:
            Masquerade:
            Name:  default
        Machine:
          Type:  q35
        Resources:
          Requests:
            Memory:  64M
      Networks:
        Name:  default
        Pod:
      Volumes:
        Container Disk:
          Image:  XXXX/kubevirt/cirros-container-disk-demo:latest
        Name:     containerdisk
        Cloud Init No Cloud:
          userDataBase64:  SGkuXG4=
        Name:              cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       2023-01-04T08:53:40Z
    Last Transition Time:  2023-01-04T08:53:40Z
    Message:               VMI does not exist
    Reason:                VMINotExists
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
  Printable Status:        CrashLoopBackOff
  Start Failure:
    Consecutive Fail Count:  2
    Last Failed VMIUID:      ef81cd50-839e-4fbb-8b7d-bd7cf993bc1a
    Retry After Timestamp:   2023-01-04T08:54:16Z
  Volume Snapshot Statuses:
    Enabled:  false
    Name:     containerdisk
    Reason:   Snapshot is not supported for this volumeSource type [containerdisk]
    Enabled:  false
    Name:     cloudinitdisk
    Reason:   Snapshot is not supported for this volumeSource type [cloudinitdisk]
Events:
  Type    Reason            Age                From                       Message
  ----    ------            ----               ----                       -------
  Normal  SuccessfulDelete  28s                virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 245f9a4c-f566-4cc0-9c25-d43fd6e0109b
  Normal  SuccessfulCreate  14s (x2 over 35s)  virtualmachine-controller  Started the virtual machine by creating the new virtual machine instance testvm
  Normal  SuccessfulDelete  6s                 virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance ef81cd50-839e-4fbb-8b7d-bd7cf993bc1a

```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): 1.23.6
- VM or VMI specifications: use demo image cirros-container-disk-demo:latest
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS7

**Comment by vasiliy-ul** [comment]
Could you provide the output of `k describe vmi testvm` and the logs of the corresponding virt-launcher oid `k logs virt-launcher-testvm-...`?

**Comment by huangpx1** [comment]
I can not find vmi and no `virt-launcher-testvm-... ` pod exist

`virt-launcher-testvm-...` pod exist when execute `k apply -f vm.yaml  `  that status is `PodInitializing` to `Terminating` 
a few seconds that pod is disappear ，can not get logs

<img width="532" alt="image" src="https://user-images.githubusercontent.com/29647491/210542394-aedba1b3-f376-436d-8d6e-685748bd05d9.png">

<img width="733" alt="image" src="https://user-images.githubusercontent.com/29647491/210543885-baed7cd0-be25-44d3-871a-7dbc5a482f61.png">

**Comment by vasiliy-ul** [comment]
You can take the VMI spec from your VM yaml. That way, you will be able to run VMI directly:
```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
  name: testvm
  namespace: kubevirt
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: XXXX/kubevirt/cirros-container-disk-demo:latest
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: SGkuXG4=
```
Probably that will allow you to get the logs.

**Comment by huangpx1** [comment]
use your vmi yaml, I get `virt-launcher-testvm-...` logs 

```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-01-05T01:56:54.676168Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-01-05T01:56:54.676248Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:497","timestamp":"2023-01-05T01:56:54.686849Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:505","timestamp":"2023-01-05T01:56:54.692878Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 8.0.0, package: 2.module_el8.6.0+1087+b42c8331 (CentOS Buildsys \u003cbugs@centos.org\u003e, 2022-02-08-22:20:52, )","subcomponent":"libvirt","thread":"46","timestamp":"2023-01-05T01:56:54.725000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"46","timestamp":"2023-01-05T01:56:54.725000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2752","subcomponent":"libvirt","thread":"46","timestamp":"2023-01-05T01:56:54.725000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:513","timestamp":"2023-01-05T01:56:55.196669Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:510","timestamp":"2023-01-05T01:56:55.203010Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:74","timestamp":"2023-01-05T01:56:55.203404Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0xc00028e900, 0xc00028e720, 0xc00021ec00, {0x1d22aa0, 0xc000366410})
	cmd/virt-launcher/virt-launcher.go:244 +0x43a
main.main()
	cmd/virt-launcher/virt-launcher.go:475 +0x109a
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 13 with status 512","pos":"virt-launcher-monitor.go:125","timestamp":"2023-01-05T02:01:21.213862Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:143","timestamp":"2023-01-05T02:01:21.214420Z"}
```

<img width="582" alt="image" src="https://user-images.githubusercontent.com/29647491/210690720-6a147310-0d2f-4aea-b5c4-357cca683be5.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/29647491/210690780-ebf259e9-67e8-4b17-a61e-77e9cec7277b.png">

but this node exits `/dev/mem`.    do not exits` /var/run/libvirt`

**Comment by vasiliy-ul** [comment]
Those errors about `/dev/mem` and `/var/run/libvirt` are more like warnings. We can ignore them. Still, there is not that much useful info in the log. Could you try to run the same VMI with increased verbosity (by adding the labels: `debugLogs: "true"`, `logVerbosity: "6"`):

```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
    debugLogs: "true"
    logVerbosity: "6"
  name: testvm
  namespace: kubevirt
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: XXXX/kubevirt/cirros-container-disk-demo:latest
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: SGkuXG4=
```
