### ISSUE TITLE
Use PVC as VMI's disk, it cannot change disk.img ownership

### ISSUE THREAD

**Issue by LeiZhou-97** [kubevirt/kubevirt#9022]
**What happened**:
When I tried to use a PVC as my VM disk, it failed. Then I checked the log of virt-handler pod, it showed not permitted to change disk.img ownership.
I also tried run chown disk.img to 107 before creating datavolume, but it didn't work as well. 
```
{"component":"virt-handler","level":"error","msg":"Couldn't set Ownership on /proc/1329724/root/var/run/kubevirt-private/vmi-disks/pvcdisk/disk.img: chown /proc/1329724/root/var/run/kubevirt-private/vmi-disks/pvcdisk/disk.img: operation not permitted","pos":"host-disk.go:245","reason":"chown /proc/1329724/root/var/run/kubevirt-private/vmi-disks/pvcdisk/disk.img: operation not permitted","timestamp":"2023-01-05T03:29:47.073892Z"}

{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vmi-pvc","namespace":"default","pos":"vm.go:1781","reason":"preparing host-disks failed: chown /proc/1329724/root/var/run/kubevirt-private/vmi-disks/pvcdisk/disk.img: operation not permitted","timestamp":"2023-01-05T03:29:47.074030Z","uid":"f5f44e5f-2a18-4d13-b86d-e06306428bc6"}
```
**What you expected to happen**:
Create a VMI using PVC successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. install kubevirt, cdi
2. create datavolume (My default storage class is nfs, I don't know if it matters)
```yaml
# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: my-data-volume
spec:
  source:
    http:
      url: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
```
3. create vmi (this step fails)
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-pvc
  name: vmi-pvc
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    resources:
      requests:
        memory: 128Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: my-data-volume
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58 (virtctl:0.58, CDI:1.55.2)
- Kubernetes version (use `kubectl version`): v1.25.3
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): 5.15.0-52-generic
