### ISSUE TITLE
Packet Loss when trying to Ping a VM

### ISSUE THREAD

**Issue by naveenbansalntnx** [kubevirt/kubevirt#9024]
**What happened**:
I am trying to ping a kubevirt VM from host where Kubernetes is deployed. I am getting a pretty high packet loss (around 90%).
```
[ec2-user@master ~]$ sudo ping  10.0.150.86
PING 10.0.150.86 (10.0.150.86) 56(84) bytes of data.
64 bytes from 10.0.150.86: icmp_seq=17 ttl=64 time=0.586 ms
64 bytes from 10.0.150.86: icmp_seq=18 ttl=64 time=0.476 ms
^C
--- 10.0.150.86 ping statistics ---
60 packets transmitted, 2 received, 96% packet loss, time 60409ms
```

In case of ping flood , the results are good normally in range of 90-100% success rate
```
[ec2-user@master ~]$ sudo ping  -f 10.0.150.86
PING 10.0.150.86 (10.0.150.86) 56(84) bytes of data.
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
--- 10.0.150.86 ping statistics ---
271273 packets transmitted, 270663 received, 0% packet loss, time 17778ms
rtt min/avg/max/mdev = 0.013/0.014/0.968/0.006 ms, pipe 2, ipg/ewma 0.065/0.015 ms

```

**What you expected to happen**:
Ping to be success 100%

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubevirt setup with flannel as the Network . Mine is on c5.metal instance.
Deploy a centos VM and try to ping it.
You can remove the MAC address spec.

**Additional context**:
This is the ifconfig for the VM
```
[root@centos14 centos]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 8951
        inet 10.0.150.86  netmask 255.255.255.0  broadcast 10.0.150.255
        inet6 fe80::40:c9ff:fecf:5039  prefixlen 64  scopeid 0x20<link>
        ether 02:40:c9:cf:40:36  txqueuelen 1000  (Ethernet)
        RX packets 1112206  bytes 108846048 (103.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1108117  bytes 108603884 (103.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 20  bytes 1592 (1.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20  bytes 1592 (1.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): v1.26.0
- VM or VMI specifications: centos VM
- Cloud provider or hardware configuration: Kubernetes Setup on c5.metal . It's not EKS , it's a normal Kubernetes cluster
- OS (e.g. from /etc/os-release):Amazon Linux
- Kernel (e.g. `uname -a`):Linux master 5.10.157-139.675.amzn2.x86_64
- Install tools: N/A
- Others: N/A
This is the yaml configuration I used for VM deployment.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: centos14
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos14
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          networkInterfaceMultiqueue: true
          disks:
          - name: disk0
            disk: {}
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk 
          interfaces:
          - macAddress: xxxxxxx
            bridge: {}
            name: test1
        machine:
          type: q35
        resources:
          requests:
            memory: 8192M
      networks:
      - name: test1
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: centos
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: centos
            ssh_pwauth: true
            password: centos/4u
            disable_root: true
            ssh_authorized_keys:
            - ssh-rsa xxxx
        name: cloudinitdisk
```
