### ISSUE TITLE
Cannot create the Kubevirt VM with the pod IP and an internet connection inside

### ISSUE THREAD

**Issue by testisnullus** [kubevirt/kubevirt#9049]
**What happened**:
I am trying to create the Kubevirt VM with pod IP on the NIC inside. I was trying to use the masquerade network type but it is hiding the pod IP behind the NAT (10.0.2.2). Also, I was trying to use the bridge network type. It created a VM with the needed pod IP inside the VM, but the VM could not connect to the internet. I found that the bridge network type does not allow us to connect to the internet (https://github.com/kubevirt/kubevirt/issues/8520#issuecomment-1261012480).

**What you expected to happen**:
I expected that my Kubevirt VM will be able to use pod IP inside and will have an internet connection (at least I can ping 8.8.8.8). 

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the Kubevirt operator and its add-ons.
```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
echo $VERSION
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml
export TAG=$(curl -s -w %{redirect_url} https://github.com/kubevirt/containerized-data-importer/releases/latest)
export VERSION=$(echo ${TAG##*/})
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml
kubectl -n kubevirt patch kubevirt kubevirt --type=merge --patch '{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}'
```
2. Apply the VM manifest below.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0-alpha.0
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: test
    spec:
      domain:
        devices:
          disks:
            - name: dvdisk
              bootOrder: 1
              disk:
                bus: sata
            - name: datadisk
              bootOrder: 2
              disk:
                bus: sata
          interfaces:
            - name: default
              masquerade: {} (or bridge: {})
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: dvdisk
          persistentVolumeClaim:
            claimName: debian-test-1
        - name: datadisk
          persistentVolumeClaim:
            claimName: debian-test-2
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: user
              password: dadsaqrqwr
              chpasswd: { expire: False }
          name: cloudinitdisk
```
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): Debian 11 (bullseye)
- Kernel (e.g. `uname -a`): Debian 5.19.46-4 (2021-08-03) x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

What should I do to make it works?
Will be grateful for the help!

Regards,
Dan

**Comment by EdDev** [comment]
I am not exactly clear why you do not have access to the internet,  but both binding options you mentioned should work fine if you have access to the internet from the pod network.

Does a regular Pod on your cluster have internet access?
Sharing the guest IP configuration may help to understand the setup.

**Comment by testisnullus** [comment]
@EdDev Hi, thank you for your reply. Yes, a regular/random pod inside of my K8s cluster has internet access. The problems start when I am trying to use the bridge{} network type, which is ideally suitable for my VMs and setup.

This is the network configuration inside the virt-launcher pod:
```
bash-5.1$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0-nic@if122: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue master k6t-eth0 state UP group default 
    link/ether f2:ff:ef:3c:ff:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::f0ff:efff:fe3c:ffe1/64 scope link 
       valid_lft forever preferred_lft forever
4: eth0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 4a:20:52:d3:7c:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.21.225/32 scope global eth0
       valid_lft forever preferred_lft forever
5: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
    link/ether 7e:13:e9:a9:03:04 brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.10/32 scope global k6t-eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7c13:e9ff:fea9:304/64 scope link 
       valid_lft forever preferred_lft forever
6: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc fq_codel master k6t-eth0 state UP group default qlen 1000
    link/ether 7e:13:e9:a9:03:04 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::7c13:e9ff:fea9:304/64 scope link 
       valid_lft forever preferred_lft forever
```

Also, there are no routes here
```
bash-5.1$ ip route
bash-5.1$
```

My VM yaml manifest:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: test
    spec:
      domain:
        devices:
          disks:
            - name: dvdisk
              bootOrder: 1
              disk:
                bus: sata
            - name: datadisk
              bootOrder: 2
              disk:
                bus: sata
          interfaces:
            - name: default
              bridge: {}
              ports:
                - port: 7000
                  name: intra-node
                - port: 7001
                  name: tls-intra-node
                - port: 7199
                  name: jmx
                - port: 9042
                  name: cql
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: dvdisk
          persistentVolumeClaim:
            claimName: debian-test-1
        - name: datadisk
          persistentVolumeClaim:
            claimName: debian-test-2
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: user
              password: ty63rt24tr
              chpasswd: { expire: False }
          name: cloudinitdisk
```

Thank you!
Regards.
Dan
