### ISSUE TITLE
got connectivity issue when windows docker has been installed

### ISSUE THREAD

**Issue by meenajaeiei** [kubevirt/kubevirt#9078]
**What happened**:
Gitlab Windows machine runner unable to upload artifact file to Gitlab. it's looks like an unstable connectivity issue to external service after Docker windows have been installed on the machine.
![Screenshot 2566-01-20 at 15 48 35](https://user-images.githubusercontent.com/20944597/213654549-2a823626-e6b3-4ddb-8180-3ee74867d2e8.png)

**What you expected to happen**:
the Windows machine should have been able to connect to the external service (Gitlab) 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
I tested deploying the 2 machines with the same VM manifest file by using the same QCOW2 template ( clone it for individual machine ) the first one is the machine that hasn't docker windows installed and another one has docker windows installed.

here is the detail of routing table and interface for the first machine (purple background powershell)

<img width="529" alt="Screenshot 2566-01-20 at 15 33 47" src="https://user-images.githubusercontent.com/20944597/213661076-254ef6f7-6db2-4c88-8f77-3fba670dd85d.png">
<img width="529" alt="Screenshot 2566-01-20 at 15 34 14" src="https://user-images.githubusercontent.com/20944597/213661097-0ef9eb42-6b4f-4c0b-854f-af5344c17350.png">
<img width="534" alt="Screenshot 2566-01-20 at 16 25 33" src="https://user-images.githubusercontent.com/20944597/213661109-5aaccc29-8d19-4059-806c-ba91a0be6ecb.png">

and the upload artifact file result from the runner is successful
![image](https://user-images.githubusercontent.com/20944597/213661396-4dcd5838-2413-4e89-a874-1756388405d1.png)

here is the detail of routing table and interface for the second machine which is has docker installed (blue background powershell)

the traceroute result is quite strange. it can't find the gateway but it can reach a destination which is locate the different subnet
<img width="197" alt="Screenshot 2566-01-20 at 15 39 07" src="https://user-images.githubusercontent.com/20944597/213661856-550743fd-b6fa-4a06-abb3-4a59b600d8e4.png">
<img width="529" alt="Screenshot 2566-01-20 at 15 27 41" src="https://user-images.githubusercontent.com/20944597/213661861-6d1db0f2-3b98-4c58-9f64-e75e904886f2.png">

it also has a new interface (HNS Internal NIC) that was created by Docker installation. I removed it and test the runner again but the issue still exist

<img width="529" alt="Screenshot 2566-01-20 at 15 25 10" src="https://user-images.githubusercontent.com/20944597/213661869-01a683e0-7087-4baf-8ab3-07b670e72236.png">

and here is the result of  docker installed Windows Runner.
![Screenshot 2566-01-20 at 15 48 35](https://user-images.githubusercontent.com/20944597/213662702-59b85ae4-7d6a-44e2-8af8-42d94d47d72e.png)

**Additional context**:

As I repeatedly reproduce the step to provision the windows machine to find the root cause issue, I can confirm that issue is happen after docker has been installed but can't find a solution to resolve it.

**Environment**:

- KubeVirt version (use `virtctl version`): 0.58.0
- Kubernetes version (use `kubectl version`): 0.58.0
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kubevirt-win10-0
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vmi-kubevirt-win10-0
        gitlab.runner/concurrent: "1"
        gitlab.runner/executor: "shell"
        gitlab.runner/shell: "powershell"
        gitlab.runner/tags_list: "win-kubevirt"
        win-webhook-enabled: "true"
    spec:
      domain:
        cpu:
          cores: 8
        resources:
          requests:
            memory: 16Gi
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
            - name: sysprep
              cdrom:
                bus: sata
          interfaces:
            - masquerade: {}
              name: default
              ports:
                - name: ssh
                  port: 3389
                - name: winrm
                  port: 5985
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: pvc-kubevirt-win10-0
        - name: virtiocontainerdisk
          containerDisk:
            image: kubevirt/virtio-container-disk
        - name: sysprep
          sysprep:
            configMap:
              name: sysprep-config
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
