### ISSUE TITLE
A potential risk of kubevirt makes a worker node get the cluster's admin secret.

### ISSUE THREAD

**Issue by younaman** [kubevirt/kubevirt#9109]
Description:
*  There are three components of kubevirt with default installation: kubevirt-handler, kubevirt-controller, kubevirt-api, and kubevirt-operator, the kubevirt-handler is a daemon set running on each node, the controller&api&operator are deployments, each of them is two-pod deployments running on worker nodes randomly.
* There are different cluster roles of these components:
  *  The cluster role of the kubevirt-handler can patch nodes, which can be leveraged to make nodes unschedulable.
  * The cluster role of the kubevirt-controller can create pods/eviction, which can be leveraged to make pods evicted. While the cluster role of kubevirt-api can delete pods, which can be leveraged to make pods recreated and rescheduled to worker nodes.
  * The cluster role of the kubevirt-operator can list all secrets, which can be leveraged to get the admin secret of the entire cluster and make cluster-level privilege escalation.
* If a malicious user controls a worker node, which has kubevirt-handler, and one of kubevirt-api/controller:
  1.  He/she can leverage the kubevirt-handler to path all other nodes with unschedulable: true". And when the kubevirt-operator is rescheduled, the kubevirt-operator will be rescheduled to the malicious worker node.
  2. He/She can use the token of kubevirt-api/controller to evict/delete kubevirt-operator pods, which will be recreated and run on the malicious worker node.
  3. After the kubevirt-operator runs on the malicious worker node, he/she can leverage the operator's token to list all secrets in the whole cluster, get the cluster admin's token and make a cluster-level privilege escalation. 
* Mitigation Discussion:
  *  The cluster role of the kubevirt-operator can use the Resource Names to restrain the secrets which can be listed by the operator itself, however, it may need a careful review of the kubevirt-operator to identify all secrets needed by the operator exactly.
   *  The kubevirt-handler can remove the patch verbs of nodes, and the controller/api can remove the evict and delete of pods. However, similar to the first mitigation, it still needs a careful revisit of the components' source code.
   * The kubevirt can let the kubevirt-operator/controller/api runs on worker nodes (which we called "controller worker node") without running users' workloads, and leverage the isolation of nodes to mitigate the risk. However, if a malicious user leverages some method(i.e., scale-up of kubevirt-handler) and moves to the "controller worker node" horizontally, it still can break the worker nodes' isolation and make privilege escalation.
* Installation and environment:
   * We follow the Kubevirt's [official guide](https://kubevirt.io/user-guide/operations/installation/) to install the Kubevirt on a four-node Kubernetes cluster(1.24.2).
I'm looking forward to hearing back from you!

**Comment by younaman** [comment]
Besides, I have written an email following the private security policy of the kubevirt vulnerability report. However, I tried my school email and it's not inside the mailing white list :(. I am sorry to write a "security issue" by opening a public-accessible GitHub issue.

**Comment by rmohr** [comment]
> If a malicious user controls a worker node, which has kubevirt-handler, and one of kubevirt-api/controller:
> 1. He/she can leverage the kubevirt-handler to path all other nodes with unschedulable: true". And when the kubevirt-operator is rescheduled, the kubevirt-operator will be rescheduled to the malicious worker node.
> 2. He/She can use the token of kubevirt-api/controller to evict/delete kubevirt-operator pods, which will be recreated and run on the malicious worker node.
> 3. After the kubevirt-operator runs on the malicious worker node, he/she can leverage the operator's token to list all secrets in the whole cluster, get the cluster admin's token and make a cluster-level privilege escalation.

That is a nice abuse flow. Thanks for writing it up!

**Comment by rmohr** [comment]
> Besides, I have written an email following the private security policy of the kubevirt vulnerability report. However, I tried my school email and it's not inside the mailing white list :(. I am sorry to write a "security issue" by opening a public-accessible GitHub issue.

Sent it in your name to the list.

**Comment by younaman** [comment]
@rmohr Thanks for your reply! My school e-mail is nzyang@stu.xidian.edu.cn :) So can you add my e-mail to the white list? After that, should I discuss this potential risk by private email and close this opening issue?

**Comment by younaman** [comment]
@rmohr I have tried to send the email by using nzyang@stu.xidian.edu.cn and my GitHub account's primary email 952508578@qq.com. However, they both told me that my email is bouncing back :( How can I connect to you by sending an email?

**Comment by rmohr** [comment]
> @rmohr I have tried to send the email by using [nzyang@stu.xidian.edu.cn](mailto:nzyang@stu.xidian.edu.cn) and my GitHub account's primary email [952508578@qq.com](mailto:952508578@qq.com). However, they both told me that my email is bouncing back :( How can I connect to you by sending an email?

@aburdenthehand is this something which you can do?

**Comment by aburdenthehand** [comment]
@rmohr I'm looking into it. 
While that's happening, I can cc nzyang@stu.xidian.edu.cn onto the thread, which should work for this issue.

**Comment by younaman** [comment]
@rmohr @aburdenthehand Thanks for your reply! I am a little busy these days because revising my paper:) 
So, It means that I can send mail right now? I will try it after I finish my tasks on hand, eta 3 days.

**Comment by aburdenthehand** [comment]
@younaman Sort of. We are still investigating the problem.
I added you to the thread using your `nzyang@stu.xidian.edu.cn` address. You should be able to reply to that thread now.
I also sent you two other emails to the same address asking for a little bit of information to help us troubleshoot why you were being blocked. If you could please follow up with them, it would be most appreciated. Thank you, and good luck with your paper!

**Comment by younaman** [comment]
@aburdenthehand Thaks a lot! I checked my nzyang@stu.xidian.edu.cn just now, and I have received three emails you sent:) I will reply your mail after I finished my paper, thank you again for your patience:) Have a nice day!

**Comment by younaman** [comment]
@rmohr @aburdenthehand I can send mail to your post box,  however, the cncf mailing list (cncf-kubevirt-security@lists.cncf.io) still rejects my mail, my post box says:"Warm tips: Please contact the recipient's administrator to adjust the anti-spam rule ,or ask the recipient to add your email address to the whitelist."

Anyway, it seems like you(aburden@redhat.com) and robert.kielty(robert.kielty@cncf.io) have received my mail, can you answer the questions which I wrote in my mail? Looking forward to your reply!

**Comment by younaman** [comment]
@rmohr @aburdenthehand I write my questions in the following, and looks for more comments:
Is it a real problem in kubevirt? If the problem is real, can any of my mitigations (listed in the github issue page) works to solve this problem? Does kubevirt have any plan to fix this issue? (It looks like there exists a PR to mitigate this risk,https://github.com/kubevirt/kubevirt/pull/9162)
By the way, if it's a real issue and has been fixed, can I get a CVE-number:)
Reporter List:
Nanzi Yang(nzyang@stu.xidian.edu.cn/952508578@qq.com, github account is younaman, me)
Xin Guo(guox@stu.xidian.edu.cn)
Jietao Xiao(jietaoXiao@stu.xidian.edu.cn)
Wenbo Shen(shenwenbo@zju.edu.cn)
Jinku Li(jkli@xidian.edu.cn)
Looking forward to your reply!

**Comment by younaman** [comment]
@rmohr @aburdenthehand Knock knock! Are there any updates about my "possible CVE number"? Besides, the [PR](https://github.com/kubevirt/kubevirt/pull/9162) looks like following my first recommendations to mitigate the risks? Looking forward to your reply!

**Comment by rmohr** [comment]
> @rmohr @aburdenthehand I write my questions in the following, and looks for more comments:
> Is it a real problem in kubevirt? If the problem is real, can any of my mitigations (listed in the github issue page) works to solve this problem? Does kubevirt have any plan to fix this issue? (It looks like there exists a PR to mitigate this risk,#9162)

Yes that is because of your initiative. Just note that virt-operator only has a `Role` (not a `ClusterRole`). As such it could only read secrets in the kubevirt install namespace and not from the whole cluster. But thanks to your initiative it will now be limited even more :)

Still, the core issue remains and is not addressed yet: virt-handler can modify pod specs. It is a serious issue but luckily not critical, since a node needs at least to get compromised first.

> By the way, if it's a real issue and has been fixed, can I get a CVE-number:)

It is definitely a problem that daemonsets which can modify pod specs can "lure-in" specific deployments with extended privileges if a node gets hacked. We are discussing mitigations and fixes at the moment.

> Reporter List:
> Nanzi Yang([nzyang@stu.xidian.edu.cn](mailto:nzyang@stu.xidian.edu.cn)/[952508578@qq.com](mailto:952508578@qq.com), github account is younaman, me)
> Xin Guo([guox@stu.xidian.edu.cn](mailto:guox@stu.xidian.edu.cn))
> Jietao Xiao([jietaoXiao@stu.xidian.edu.cn](mailto:jietaoXiao@stu.xidian.edu.cn))
> Wenbo Shen([shenwenbo@zju.edu.cn](mailto:shenwenbo@zju.edu.cn))
> Jinku Li([jkli@xidian.edu.cn](mailto:jkli@xidian.edu.cn))
> Looking forward to your reply!

I am currently checking regarding a CVE.
We will make sure that you get mentioned as the discoverer. :)

**Comment by younaman** [comment]
@rmohr Thanks for your reply! Perhaps it's because I ignore the Role and regard it as a ClusterRole. Anyway, it does not downgrade the key point of my report. 

Besides, for the critical problem, notice the node escape may be easier via other co-host third-party apps:). For example, I have found and reported another issue to the cilium community, "The potential node escape issue" has been confirmed but the fix has not been discussed and opened yet:(

By the way, thank you again for the CVE number, it's an honor and appreciate for your patience and works:)

**Comment by younaman** [comment]
@rmohr As I still rejected by the mailing list, can you or @aburdenthehand CC to me a mail when there are any updates about my issue:) Both of you have my email address.

**Comment by younaman** [comment]
@RobertKielty Thanks a lot! I have joined the mailing list, and you should have received my email about "Are there any updates about mitigations?" Have a nice day:)

**Comment by younaman** [comment]
@rmohr For the cilium node escalation I mentioned in [comment](https://github.com/kubevirt/kubevirt/issues/9109#issuecomment-1420456233), it has been confirmed and fixed by cilium in cilium version 1.13, so I can report it to you now:) The cilium DaemonSet pod mounts the host's /proc/sys directory with read&write, so if a malicious user can access the cilium pod, he/she can:
* Create a malicious reverse shell script in the cilium pod.
* Modify the /proc/sys/kernel/core_pattern, and point it to the malicious shell.
* Trigger a core dump, and the core_pattern will make the host kernel execute the malicious script, and reverse a shell with the host root user to the malicious user. Thus, he/she can leverage the cilium pod to escape to the worker node, and leverage the kubevirt to make the privilege escalation that I reported here. 
I know it's not the problem of kubevirt. I just want you to know this issue and make a further consideration about "multiple third-party apps" scenario:) If you want the details, you have my email and please feel free to discuss more details with me.

**Comment by younaman** [comment]
@rmohr Knock knock! Are there any updates? Looking forward to your reply:)

**Comment by rmohr** [comment]
So, sorry for the delay. Took me a little bit to check things, since I am myself not that familiar with filing CVEs. I think the best way would be if you just file the CVE yourself, like described here: https://infosecwriteups.com/how-to-register-and-publish-a-cve-for-your-awesome-vulnerability-e68a6a5f748f. You can then hand us over the CVE number which you get (I would file a low-to-med severity CVE).

We would then publish a security note on our project referencing your CVE together with mitigations, which will serve as the public reference for your CVE to make it public as well.

I think that would be the best way to have you as an owner of this.

**Comment by younaman** [comment]
@rmohr Thanks for your reply:) However, I think it's better for you to register a CVE number because you stand for the kubevirt community. If I register the CVE myself, I am afraid that the cveform.mitre.org will NOT give me a CVE number because of some other reasons. (I believe you know what I mean.)

**Comment by younaman** [comment]
@rmohr I believe you can register the CVE, and I will do my best to assist you if needed:)

**Comment by younaman** [comment]
@rmohr I have tried to request a CVE number following the https://infosecwriteups.com/how-to-register-and-publish-a-cve-for-your-awesome-vulnerability-e68a6a5f748f, and I fill the CVE web page following the pdf file which I sent to your email(rmohr@google.com). Please feel free to contact me if you want some changes:) And please let me know you you received the mail.

**Comment by younaman** [comment]
@rmohr I tried to send you and kubevirt maintainers another mail based on your valuable comments, however, it seems that I am banned by your mail, and my e-mail has been rejected. Your e-mail says "(Proxy)Host google.com said 450 Broken pipe(CONNECT). Bounce by SDN Rule 14 (tag:8)", and the kubevirt maintainer list's e-mail says "SMTP through SDN 4, SMTP: (Proxy)Host lists.cncf.io said 500 Invalid request, no reverse DNS for 121.9.212.76 (tag:-1)" Have I do something wrong? Looking forward to your reply!

**Comment by fabiand** [comment]
Hey.

Does #9162 fix this issue?

**Comment by rmohr** [comment]
On Wed, Apr 12, 2023 at 10:48 AM Fabian Deutsch ***@***.***>
wrote:

> Hey.
>
> Does #9162 <https://github.com/kubevirt/kubevirt/pull/9162> fix this
> issue completely?
>

No. As stated in the security advisory, there is no fix at the moment
(except custom fine-tuned gatekeeper policies):
https://github.com/kubevirt/kubevirt/security/advisories/GHSA-cp96-jpmq-xrr2

Happy if someone follows up with a complete fix, which would probably
involve creating a custom KubeVirt node object where we shadow the
kubernetes nodes. virt-handlers would only update these objects, and only
one central component (virt-controller), optimally running on control-plane
nodes, would then mirror annotations and labels to the node itself.

This is a relatively big undertaking and as far as I can tell. A lot of
daemon-set based solutions out there potentially have this issue. For
instance the nividia MIG controller (
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-operator-mig.html#configuring-mig-profiles
).

**Comment by younaman** [comment]
@rmohr @fabiand Perhaps we can use the kubelet's configuration, and make the virt-handler can only "modify" the node which it runs? As the kubelet has NodeRestrictions by default, so it may needs only a few changes to solve this problem?

**Comment by enj** [comment]
At KubeCon EU 2024, some folks (whose names I cannot remember) from Red Hat / KubeVirt discussed this with me at the speaker lounge.  At the time I could not come up with an actionable solution, but thinking through the same problem at this week's SIG Auth triage meeting for https://github.com/kubernetes/kubernetes/issues/124094, I believe this problem can be easily solved in v1.30+ kube clusters via the `ServiceAccountTokenNodeBinding` and `ValidatingAdmissionPolicy` features.  @deads2k seems to have come to the same conclusion at approximately the same time via https://github.com/openshift/origin/pull/28673.  The general idea is to leverage the new node name metadata included in bound service account tokens to restrict the update of the node object to the current node that the service account is running on (along with only allowing the kube virt annotations to be mutated).  This will correctly scope the authorization of the daemonset service account.

**Comment by rmohr** [comment]
Hi Mo,


On Wed, Apr 3, 2024 at 8:33 AM Mo Khan ***@***.***> wrote:

> At KubeCon EU 2024, some folks (whose names I cannot remember) from Red
> Hat / KubeVirt discussed this with me at the speaker lounge. At the time I
> could not come up with an actionable solution, but thinking through the
> same problem at this week's SIG Auth triage meeting for
> kubernetes/kubernetes#124094
> <https://github.com/kubernetes/kubernetes/issues/124094>, I believe this
> problem can be easily solved in v1.30+ kube clusters via the
> ServiceAccountTokenNodeBinding and ValidatingAdmissionPolicy features.
> @deads2k <https://github.com/deads2k> seems to have come to the same
> conclusion at approximately the same time via openshift/origin#28673
> <https://github.com/openshift/origin/pull/28673>. The general idea is to
> leverage the new node name metadata included in bound service account
> tokens to restrict the update of the node object to the current node that
> the service account is running on (along with only allowing the kube virt
> annotations to be mutated). This will correctly scope the authorization of
> the daemonset service account.
>

Yes, that helps limit the issue. The main problem I see is that it still
allows changing the node object content in arbitrary fashions. Like I can
just give a node I took over a different role, add labels to let privileged
components get scheduled there and make my way through the cluster this
way. To limit this, it looks to me like I would still need a traditional
webhook, which means that I would have a required webhook owned by kubevirt
in a critical path for cluster health which, if failing, would block the
whole cluster.

Are there any recommendations in this direction as well?

Best regards,
Roman

**Comment by rmohr** [comment]
@RamLavi what @enj describes in https://github.com/kubevirt/kubevirt/issues/9109#issuecomment-2034938011 can solve the second part of our problem without us requiring to have a webhook for the kubevirt node objects.

**Comment by enj** [comment]
@rmohr 

> The main problem I see is that it still allows changing the node object content in arbitrary fashions. Like I can just give a node I took over a different role, add labels to let privileged components get scheduled there and make my way through the cluster this way

In my above example I included the line `along with only allowing the kube virt annotations to be mutated`.  VAP can be used to limit the specific mutations made to the node as well (this will probably require a rather complex CEL expression though).

**Comment by xpivarc** [comment]
> At KubeCon EU 2024, some folks (whose names I cannot remember) from Red Hat / KubeVirt discussed this with me at the speaker lounge. At the time I could not come up with an actionable solution, but thinking through the same problem at this week's SIG Auth triage meeting for [kubernetes/kubernetes#124094](https://github.com/kubernetes/kubernetes/issues/124094), I believe this problem can be easily solved in v1.30+ kube clusters via the `ServiceAccountTokenNodeBinding` and `ValidatingAdmissionPolicy` features. @deads2k seems to have come to the same conclusion at approximately the same time via [openshift/origin#28673](https://github.com/openshift/origin/pull/28673). The general idea is to leverage the new node name metadata included in bound service account tokens to restrict the update of the node object to the current node that the service account is running on (along with only allowing the kube virt annotations to be mutated). This will correctly scope the authorization of the daemonset service account.

Hey @enj ,
That was me and @alaypatel07 at the Kubecon. @fabiand pointed out that the `ValidatingAdmissionPolicy` is being GAed to me this week. (was not the case back when we started to look into this). I am going to have a look if we can express our needs through the CEL. Specifically if we can express that only subset of labels/annotations are allowed.

**Comment by rmohr** [comment]
> In my above example I included the line along with only allowing the kube virt annotations to be mutated. VAP can be used to limit the specific mutations made to the node as well (this will probably require a rather complex CEL expression though).

@enj ack. Yeah that would potentially be an alternative then to https://github.com/kubevirt/community/pull/246, though from a holistic perspective, I am not yet sure. Great if @xpivarc can reevaluate it in that context. Thanks for following up.

**Comment by xpivarc** [comment]
So I have tried to draft how the policy would look like, see below

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "kubevirt-node-restriction"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["*"]
        operations:  ["UPDATE"]
        resources:   ["nodes"]
  variables:
    - name: hasNodeName
      expression: ('authentication.kubernetes.io/node-name' in request.userInfo.extra)
    - name: isPartitionedServiceAccount
      expression: request.userInfo.username == "system:serviceaccount:kubevirt:kubevirt-handler"
    - name: oldNotAllowedLabels
      expression: oldObject.metadata.labels.filter(k, !k.startsWith("cpu-feature.node.kubevirt.io/") && !k.startsWith("cpu-model-migration.node.kubevirt.io/") && k != "cpu-timer.node.kubevirt.io/tsc-frequency" && k != "cpu-timer.node.kubevirt.io/tsc-scalable" && k != "cpumanager" && !k.startsWith("cpu-vendor.node.kubevirt.io/") && !k.startsWith("host-model-cpu.node.kubevirt.io/") && !k.startsWith("host-model-required-features.node.kubevirt.io/") && !k.startsWith("hyperv.node.kubevirt.io/") && !k.startsWith("cpu-model.node.kubevirt.io") && k != "kubevirt.io/ksm-enabled" && k != "kubevirt.io/schedulable")
    - name: oldLabels
      expression: oldObject.metadata.labels
    - name: newNotAllowedLabels
      expression: object.metadata.labels.filter(k, !k.startsWith("cpu-feature.node.kubevirt.io/") && !k.startsWith("cpu-model-migration.node.kubevirt.io/") && k != "cpu-timer.node.kubevirt.io/tsc-frequency" && k != "cpu-timer.node.kubevirt.io/tsc-scalable" && k != "cpumanager" && !k.startsWith("cpu-vendor.node.kubevirt.io/") && !k.startsWith("host-model-cpu.node.kubevirt.io/") && !k.startsWith("host-model-required-features.node.kubevirt.io/") && !k.startsWith("hyperv.node.kubevirt.io/") && !k.startsWith("cpu-model.node.kubevirt.io") && k != "kubevirt.io/ksm-enabled" && k != "kubevirt.io/schedulable")
    - name: newLabels
      expression: object.metadata.labels
    - name: oldNotAllowedAnnotations
      expression: oldObject.metadata.annotations.filter(k, !k.startsWith("kubevirt.io/heartbeat") && !!k.startsWith("kubevirt.io/ksm-handler-managed"))
    - name: newNotAllowedAnnotations
      expression: object.metadata.annotations.filter(k, !k.startsWith("kubevirt.io/heartbeat") && !!k.startsWith("kubevirt.io/ksm-handler-managed"))
    - name: oldAnnotations
      expression: oldObject.metadata.annotations
    - name: newAnnotations
      expression: object.metadata.annotations
  validations:
    - expression: "!variables.isPartitionedServiceAccount || (!variables.hasNodeName) || object.metadata.name == request.userInfo.extra[\"authentication.kubernetes.io/node-name\"][0]"
      message: "this user may only modify nodes that belong to the pod is running on"
    - expression: "object.spec == oldObject.spec"
      message: "this user cannot modify spec of the nodes"
    - expression: "object.status == oldObject.status"
      message: "this user cannot modify spec of the nodes"
    - expression: size(variables.newNotAllowedLabels) == size(variables.oldNotAllowedLabels)
      message: "this user cannot add or delete arbitrary labels"
    - expression: variables.newNotAllowedLabels.all(k, k in variables.oldNotAllowedLabels && variables.newLabels[k] == variables.oldLabels[k])
      message: "this user is only allowed to change subset of labels"
    - expression: size(variables.newNotAllowedAnnotations) == size(variables.oldNotAllowedAnnotations)
      message: "this user cannot add or delete arbitrary annotations"
    - expression: variables.newNotAllowedAnnotations.all(k, k in variables.oldNotAllowedAnnotations && variables.newAnnotations[k] == variables.newAnnotations[k])
      message: "this user is only allowed to change subset of annotations"
    - expression:  oldObject.metadata.filter(k, k != "labels" && k != "annotations" && k != "managedFields" && k != "resourceVersion").all(k, oldObject.metadata[k] == object.metadata[k])
      message: "this user is only allowed to change subset of labels but not other fields"
```

It seems it works but I need to write couple of tests...
