### ISSUE TITLE
How to set vmi rx_queue_size/tx_queue_size

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#9115]
**Description:**

Kubevirt could set vmi interface rx_queue_size and tx_queue_size when enable “networkInterfaceMultiqueue”.

**VMI yaml**
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-multi-queue
  name: vmi-multi-queue
spec:
  domain:
    devices:
      networkInterfaceMultiqueue: true   # enable Multiqueue:
      disks:
      - disk:
          bus: virtio
        name: host-disk
      interfaces:
      - name: default
        bridge: {}
    machine:
      type: ""
    resources:
      requests:
        cpu: 36
        memory: 2048M
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: host-disk
    hostDisk:
      capacity: 4Gi
      path: '/root/kubevirt-vm/CentOS-7.8-x86_64-nocloudinit.raw'
      type: DiskOrCreate
status: {}
```

**What you expected to happen:**
I hope kubevirt could add two fields to set rx_queue_size and tx_queue_size，vmi interface xml like this:

```
<interface>
  ...
  <driver name='vhost' queues='4' rx_queue_size='512'  tx_queue_size='512'/>
  ...
</interface>
```
