### ISSUE TITLE
Failed to apply instancetype: failed to decode object in ControllerRevision: Object 'Kind' is missing in

### ISSUE THREAD

**Issue by ruslanloman** [kubevirt/kubevirt#9261]
Hello everyone!

**What happened**:
I've upgraded kubevirt from version v0.57.1 to v0.58.1 and after that i tried to restart virtualmachine, but it's failed to start with error message:
```
  Warning  FailedCreate  11m (x37 over 5h33m)  virtualmachine-controller  Error creating virtual machine instance: Failed to apply instancetype: failed to decode object in ControllerRevision: Object 'Kind' is missing in '{"apiVersion":"","spec":"eyJjcHUiOnsiZ3Vlc3QiOjZ9LCJtZW1vcnkiOnsiZ3Vlc3QiOiIzMkcifX0="}'
```
I managed to solve this issue by removing the old controllerRevision/instancetype resource and revisionName from  the virtualmachine spec manually after that kubevirt created a new ControllerRevision/instancetype with the correct format and the virtualmachine started without issue. I would expect that kubevirt will handle this error properly and migrate resource during  the upgrade.

Instancetype from vm spec
```
spec:
  instancetype:
    kind: VirtualMachineInstancetype
    name: m4.2xlarge
    revisionName: m4.2xlarge-8fffb940-1206-41dd-9529-70cf1faba822-1
```

Old ControllerRevision/instancetype resource format:
```
apiVersion: apps/v1
data:
  apiVersion: ""
  spec: eyJjcHUiOnsiZ3Vlc3QiOjZ9LCJtZW1vcnkiOnsiZ3Vlc3QiOiIzMkcifX0=
kind: ControllerRevision
metadata:
  name: m4.2xlarge-8fffb940-1206-41dd-9529-70cf1faba822-1
```

New ControllerRevision/instancetype resource format:
```
apiVersion: apps/v1
kind: ControllerRevision
metadata:
  name: m4.2xlarge-8fffb940-1206-41dd-9529-70cf1faba822-1
data:
  apiVersion: instancetype.kubevirt.io/v1alpha2
  kind: VirtualMachineInstancetype
  metadata:
    name: m4.2xlarge
  spec:
    cpu:
      guest: 6
    memory:
      guest: 32G
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.1
- Kubernetes version (use `kubectl version`): v1.23.10
