### ISSUE TITLE
ARM64: not enough exclusive threads when using CPU Pinning

### ISSUE THREAD

**Issue by darkmuggle** [kubevirt/kubevirt#9315]
**What happened**:

CPU Pinning on ARM64 hosts fails with "no enough exclusive threads."

```
{"component":"virt-launcher","kind":"","level":"error","msg":"Conversion failed.","name":"meh-,"namespace":"virts","pos":"manager.go:840","timestamp":"2023-02-23T19:17:49.844184Z","uid":"6d2e5b9e-c35f-4101-9d1a-9c8c383ab047"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"meh","namespace":"virts","pos":"server.go:185","reason":"not enough exclusive threads provided, could not fit 6 core(s)","timestamp":"2023-02-23T19:17:49.844224Z","uid":"6d2e5b9e-c35f-4101-9d1a-9c8c383ab047"}
panic: timed out waiting for domain to be defined
```

```
---
apiVersion: kubertvirt.io/v1
kind: VirtualMachine
metadata:
  name: meh
  namespace: virts
spec:
  dataVolumeTemplates:
  - <REDACTED>
  runStrategy: Manual
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        devops.example.com/expose: virt
    spec:
      dnsPolicy: ClusterFirst
      domain:
        cpu:
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
          model: host-passthrough
          sockets: 6
        devices:
          blockMultiQueue: true
          disks:
            <REDACTED>
          interfaces:
          - bridge: {}
          - name: default
          rng: {}
          tpm: {}
        features:
          acpi: {}
          kvm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: virt
        memory:
          guest: 20Gi
        resources:
          limits:
            memory: 21Gi
          requests:
            memory: 21Gi
      hostname: meh
      networks:
      - name: default
        pod: {}
      priorityClassName: system-cluster-critical
      subdomain: vms
      volumes:
         <REDACTED>
```

```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: 15b3:101c
          resourceName: devices.kubevirt.io/mellanox-sriov
        - pciVendorSelector: 8086:1520
          resourceName: devices.kubevirt.io/intel-nic
    developerConfiguration:
      featureGates:
        - CPUManager
        - ExpandDisks
        - HostDevices
        - HostDisk
        - HotplugVolumes
        - Macvtap
        - Sidecar
        - Snapshot
```

**What you expected to happen**:

Based on reading the [docs](https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/#:~:text=In%20order%20to%20enhance%20the%20real-time%20support%20in,emulator%20thread%20from%20the%20vCPUs%20of%20the%20VMI), I would expect that CPU pinning would happen.

**Additional context**:

I've confirmed that the CPUManager label exists on all the nodes:
```
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/os: linux
    cpumanager: "true"
```

I also see that the kubelet is updating the CPU set: 
```
Feb 23 22:30:27 dev3-kv-04 k3s[89442]: I0223 22:30:27.493253   89442 state_mem.go:80] "Updated desired CPUSet" podUID="20505542-5837-4505-9322-8b4e73a0082d" containerName="compute" cpuSet="0-3,5-7"
```

I've tried using:
 - `cores` and `sockets` for the CPU
 - adding threads (but that fails)

**Environment**:
- K3S v1.26.1 (also seen on 1.23 and 1.25) on Ubuntu 22.04
- Ampere Alta ARM64, 80 core host
- KubeVirt v0.54.0
