### ISSUE TITLE
Access Credentials API not working as expected

### ISSUE THREAD

**Issue by arturiamu** [kubevirt/kubevirt#9357]
**What happened**:

I tried to configure the VirtualMachineInstance password according to the pull [Access Credentials API (with dynamic propagation) #4195](https://github.com/kubevirt/kubevirt/pull/4195) but it didn't work @davidvossel 

**What you expected to happen**:

I want to point the accessCredentials.userPassword field of a VirtualMachine to an existing secret, and the corresponding vmi user password will change when I modify the secret

**How to reproduce it (as minimally and precisely as possible)**:

First,I defined secret and vmi related yaml files like this, 
secret s1 contains a base64 encoding named root and the original text is "$6$sqbgaB1Y$4S0.viJs9nn9DQYtG.IiNS9McjNNJ/o7sOobqMSFYTbRmGQzpYODkSavMUKGKwUl9JPkNpdh8QLK/einhb/eT1".
VirtualMachine vm1 contains a accessCredentials field pointing to s1, and vm1 configured init-cloud with base64 encoding, the original is

```yaml
#cloud-config
users:
- name: root
  lock_passwd: false
  hashed_passwd: "$6$sqbgaB1Y$4S0.viJs9nn9DQYtG.IiNS9McjNNJ/o7sOobqMSFYTbRmGQzpYODkSavMUKGKwUl9JPkNpdh8QLK/einhb/eT1"
  ssh_pwauth: true

runcmd:
- [ bash, -c, "sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"]
- [ bash, -c, "sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config"]
- [ bash, -c, "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config"]
- [ bash, -c, "systemctl restart ssh"]
```

Here is the complete definition file：

```yaml
apiVersion: v1
data:
  root: JDYka09sbW92VUckRjZsWmxWQ0tveng1UjU2UDZLV3dSREovaTRzLmVmVGJvVWpzaDFUL3c0Ri5iRGY1bUs5a0txd2xVZmg4WmpMdnB1b2pBaWZBMElrNFdnNVNibnlWSzE=
kind: Secret
metadata:
  name: s1
  namespace: default
type: Opaque

---

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1
  namespace: default
spec:
  running: true
  template:
    spec:
      accessCredentials:
        - userPassword:
            source:
              secret:
                secretName: s1
            propagationMethod:
              qemuGuestAgent: {}
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk0
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: { }
              name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
      networks:
        - name: default
          pod: { }
      volumes:
        - containerDisk:
            image: docker.qiniu.io:32500/vmidisks/centos:7.6
            imagePullPolicy: IfNotPresent
          name: disk0
        - cloudInitNoCloud:
            userDataBase64: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IHJvb3QKICAgIGxvY2tfcGFzc3dkOiBmYWxzZQogICAgaGFzaGVkX3Bhc3N3ZDogIiQ2JGtPbG1vdlVHJEY2bFpsVkNLb3p4NVI1NlA2S1d3UkRKL2k0cy5lZlRib1Vqc2gxVC93NEYuYkRmNW1LOWtLcXdsVWZoOFpqTHZwdW9qQWlmQTBJazRXZzVTYm55VksxIgogICAgc3NoX3B3YXV0aDogdHJ1ZQogICAgCnJ1bmNtZDoKICAtIFsgYmFzaCwgLWMsICJzZWQgLWkgJ3MvXlNFTElOVVg9LiovU0VMSU5VWD1kaXNhYmxlZC8nIC9ldGMvc2VsaW51eC9jb25maWciXQogIC0gWyBiYXNoLCAtYywgInNlZCAtaSAncy8jUGVybWl0Um9vdExvZ2luIHByb2hpYml0LXBhc3N3b3JkL1Blcm1pdFJvb3RMb2dpbiB5ZXMvJyAvZXRjL3NzaC9zc2hkX2NvbmZpZyJdCiAgLSBbIGJhc2gsIC1jLCAic2VkIC1pICdzL1Bhc3N3b3JkQXV0aGVudGljYXRpb24gbm8vUGFzc3dvcmRBdXRoZW50aWNhdGlvbiB5ZXMvJyAvZXRjL3NzaC9zc2hkX2NvbmZpZyJdCiAgLSBbIGJhc2gsIC1jLCAic3lzdGVtY3RsIHJlc3RhcnQgc3NoIl0K
          name: cloudinitdisk
```

Then I apply it in my cluster,and I got the success info,But when I started using the virtual machine,
I found that the password of the virtual machine changes irregularly, about once every 5 minutes, and my changes to s1 do not affect the virtual machine,
This is the change I observed while continuously outputting /etc/shadow files without operating s1

```shell
[root@vm1 ~]# stat /etc/shadow
File: ‘/etc/shadow’
Size: 656       	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 1355        Links: 1
Access: (0000/----------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:shadow_t:s0
Access: 2023-03-03 07:25:21.849325637 +0000
Modify: 2023-03-03 07:24:47.505472949 +0000
Change: 2023-03-03 07:24:47.515472949 +0000
Birth: -
[root@vm1 ~]# head /etc/shadow -n 1
root:$6$sqbgaB1Y$4S0.viJs9nn9DQYtG.IiNS9McjNNJ/o7sOobqMSFYTbRmGQzpYODkSavMUKGKwUl9JPkNpdh8QLK/einhb/eT1:19419:0:99999:7:::
[root@vm1 ~]# stat /etc/shadow
File: ‘/etc/shadow’
Size: 663       	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 1356        Links: 1
Access: (0000/----------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:shadow_t:s0
Access: 2023-03-03 07:44:30.004384333 +0000
Modify: 2023-03-03 07:44:30.005384340 +0000
Change: 2023-03-03 07:44:30.005384340 +0000
Birth: -
[root@vm1 ~]# head /etc/shadow -n 1
root:$6$gax9d.a6Rw/rU5h$CKE5Eo1XPWGq3WtCw7Og/I/qUtqnhgOvTOZWsA34TQv7FFMmaKv5Igop2sCJ7nKOidTYyTzlPysPRdurTIVP4/:19419:0:99999:7:::
```

**Additional context**:

**Environment**:

- KubeVirt version (use `virtctl version`): 
  - Client Version: version.Info{GitVersion:"v0.55.0", GitCommit:"1f7c616daac748e6b11660920514eb8613d71ec2", GitTreeState:"clean", BuildDate:"2022-07-14T16:42:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
  - Server Version: version.Info{GitVersion:"v0.58.0", GitCommit:"6e41ae7787c1b48ac9a633c61a54444ea947242c", GitTreeState:"clean", BuildDate:"2022-10-13T00:33:22Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 
  - Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7"
  - GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
  - Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7" 
  - GitTreeState:"clean", BuildDate:"2022-03-16T14:02:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): 
  - NAME="Ubuntu"
  -   VERSION="18.04.6 LTS (Bionic Beaver)"
  -   ID=ubuntu
  -   ID_LIKE=debian
  -   PRETTY_NAME="Ubuntu 18.04.6 LTS"
  -  VERSION_ID="18.04"
  -  HOME_URL="https://www.ubuntu.com/"
  -  SUPPORT_URL="https://help.ubuntu.com/"
  -  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  -  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  -  VERSION_CODENAME=bionic
  -  UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A
