### ISSUE TITLE
VM mutator panics when inferring instancetype from DataSource without specifying namespace

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#9431]
**What happened**:
I tried to create a VM with instance type and preference inference enabled. The boot volume is specified as a DataSource with the according labels. The DataSource was referenced in the VM's `dataVolumeTemplate` without specifying a namespace. According to the API reference this is valid, when both resources are located in the same namespace. This led to a panic in the VM mutator webhook.

```
felix@felix-p1 » virtctl create vm --infer-instancetype --infer-preference --volume-datasource=src:fedora | kubectl create -f -
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook: Post "[https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s](https://virt-api.kubevirt.svc/virtualmachines-mutate?timeout=10s)": EOF
```

virt-api log:
```
{"component":"virt-api","level":"info","msg":"http: panic serving 192.168.66.101:32602: runtime error: invalid memory address or nil pointer dereference\ngoroutine 4099 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1850 +0xbf\npanic({0x1d6fba0, 0x36536e0})\n\tGOROOT/src/runtime/panic.go:890 +0x262\nkubevirt.io/kubevirt/pkg/instancetype.(*InstancetypeMethods).inferDefaultsFromDataVolumeSourceRef(0x50dd03?, 0xc000a19108?, {0x2082011?, 0xc0048fcf58?}, {0x2090372?, 0xc000a190e0?})\n\tpkg/instancetype/instancetype.go:797 +0x52\nkubevirt.io/kubevirt/pkg/instancetype.(*InstancetypeMethods).inferDefaultsFromDataVolumeSpec(0x0?, 0x4?, {0x2082011?, 0x498?}, {0x2090372?, 0xc001962f00?})\n\tpkg/instancetype/instancetype.go:773 +0x85\nkubevirt.io/kubevirt/pkg/instancetype.(*InstancetypeMethods).inferDefaultsFromDataVolume(0xc00489ef60, 0xc0018bf440, {0xc0058c50b0, 0x12}, {0x2082011, 0x2d}, {0x2090372, 0x32})\n\tpkg/instancetype/instancetype.go:749 +0x365\nkubevirt.io/kubevirt/pkg/instancetype.(*InstancetypeMethods).inferDefaultsFromVolumes(0x203a337?, 0xc0018bf440, {0xc0058c4f60, 0x12}, {0x2082011, 0x2d}, {0x2090372, 0x32})\n\tpkg/instancetype/instancetype.go:720 +0x23e\nkubevirt.io/kubevirt/pkg/instancetype.(*InstancetypeMethods).InferDefaultInstancetype(0x0?, 0x0?)\n\tpkg/instancetype/instancetype.go:675 +0x59\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook/mutators.(*VMsMutator).inferDefaultInstancetype(0x25e40c0?, 0xc0018bf440)\n\tpkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:187 +0x27\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook/mutators.(*VMsMutator).Mutate(0xc00458fa00?, 0xc0015a45d0)\n\tpkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:78 +0x37a\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook.serve({0x26005b0, 0xc00489a0e0}, 0x800?, {0x25e3da0, 0xc003466de0})\n\tpkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go:57 +0xfc\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook.ServeVMs(...)\n\tpkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go:80\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerMutatingWebhook.func1({0x26005b0, 0xc00489a0e0}, 0x1fa2320?)\n\tpkg/virt-api/api.go:874 +0xfc\nnet/http.HandlerFunc.ServeHTTP(0xc00489a0e0?, {0x26005b0?, 0xc00489a0e0?}, 0x2044a37?)\n\tGOROOT/src/net/http/server.go:2109 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc0048a209d?, {0x26005b0, 0xc00489a0e0}, 0xc00458fa00)\n\tGOROOT/src/net/http/server.go:2487 +0x149\nnet/http.serverHandler.ServeHTTP({0x25f1488?}, {0x26005b0, 0xc00489a0e0}, 0xc00458fa00)\n\tGOROOT/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc004367360, {0x2601738, 0xc005a97e00})\n\tGOROOT/src/net/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\tGOROOT/src/net/http/server.go:3102 +0x4db\n","pos":"server.go:3230","timestamp":"2023-03-15T08:24:19.225052Z"}
```

**What you expected to happen**:
The VM should have been created successfully and the instancetype and preference should have been inferred successfully.

**How to reproduce it (as minimally and precisely as possible)**:
- Create DataVolume that imports a bootable disk image
- Create DataSource that references the DataVolume and has appropriate inference labels
- Try to create a VM in the same namespace referencing the DataSource without specifying the namespace

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v0.59.0-rc.1.286+8d44d49361c971", GitCommit:"8d44d49361c9711ec2ec7f35cb6026d1a2e23563", GitTreeState:"clean", BuildDate:"2023-03-14T15:23:31Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.59.0-rc.1.286+8d44d49361c971", GitCommit:"8d44d49361c9711ec2ec7f35cb6026d1a2e23563", GitTreeState:"clean", BuildDate:"2023-03-14T15:27:00Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  source:
    registry:
      url: docker://quay.io/containerdisks/fedora:latest
```
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: fedora
  labels:
    instancetype.kubevirt.io/default-instancetype: n1.medium
    instancetype.kubevirt.io/default-preference: fedora
spec:
  source:
    pvc:
      namespace: default
      name: fedora
```
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: vm-prbkc
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: vm-prbkc-ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
      storage:
        resources: {}
  instancetype:
    inferFromVolume: vm-prbkc-ds-fedora
  preference:
    inferFromVolume: vm-prbkc-ds-fedora
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices: {}
        resources: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm-prbkc-ds-fedora
        name: vm-prbkc-ds-fedora
status: {}
```
- Cloud provider or hardware configuration: kubevirtci with ceph storage (`KUBEVIRT_STORAGE=rook-ceph-default` and `KUBEVIRT_MEMORY_SIZE=12000M`)
