### ISSUE TITLE
VM status always CrashLoopBackOff due to virt-launcher failed to start virtqemud

### ISSUE THREAD

**Issue by cheese** [kubevirt/kubevirt#9441]
**What happened**:
I set up KubeVirt installation in MiniKube with kvm2 driver, just following https://kubevirt.io/quickstart_minikube/. But when I try to boot the testvm, it always failed to start with CrashLoopBackOff.

I added `kubevirt.io/keep-launcher-alive-after-failure: "true"` annotation and increase log verbosity to the vmi spec, then the launcher log read:

```
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-03-13T07:28:41.208891Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0
```

But if I enter the launcher container, it is successful to start `virtqemud -f /var/run/libvirt/virtqemud.conf` manually.

**What you expected to happen**:
The vmi runs.

**How to reproduce it (as minimally and precisely as possible)**:
Follow https://kubevirt.io/quickstart_minikube/

**Additional context**:
I am new to KubeVirt, but I will be responsive to provide additional information if needed.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.26.1
- VM or VMI specifications:
```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/keep-launcher-alive-after-failure: "true"
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
    debugLogs: "true"
    logVerbosity: "6"
  name: testvm
  namespace: kubevirt
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/kubevirt/cirros-container-disk-demo
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: SGkuXG4=
```
- Cloud provider or hardware configuration: Minikube v1.29.0 with kvm2 driver default VM config
- OS (e.g. from /etc/os-release):
```
NAME=Buildroot
VERSION=2021.02.12-1-g13cabae-dirty
ID=buildroot
VERSION_ID=2021.02.12
PRETTY_NAME="Buildroot 2021.02.12"
```
- Kernel (e.g. `uname -a`): `Linux minikube 5.10.57 #1 SMP Fri Jan 27 18:05:35 UTC 2023 x86_64 GNU/Linux`
- Install tools: follows https://kubevirt.io/quickstart_minikube/
- Others: Host system: Fedora 36 x86_64

**Comment by aland-zhang** [comment]
I have the same problem，Can't find this file“ /var/run/libvirt/virtqemud-sock ”
apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager    
systemctl status libvirtd show Active: active (running)
KubeVirt version: v0.59.0
Kubernetes version: v1.21.17
VM or VMI specifications: N/A
Cloud provider or hardware configuration: bare metal cluster
OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS

```
│ {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-03-24T08:08:13.165054Z"}                                                                                                                                                            │
│ {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-03-24T08:08:13.165149Z"}                                                                                                             │
│ {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-03-24T08:08:13.166548Z"}                                                                                                              │
│ {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-03-24T08:08:13.167097Z"}                                   │
│ {"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-03-24T08:08:13.167587Z"}                                                                                                                    │
│ panic: fork/exec /usr/sbin/virtqemud: errno 0    


systemctl status libvirtd
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-24 06:21:44 CST; 9h ago
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
   Main PID: 1842 (libvirtd)
      Tasks: 19 (limit: 32768)
     Memory: 44.6M
     CGroup: /system.slice/libvirtd.service
             ├─1842 /usr/sbin/libvirtd
             ├─2098 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─2099 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

ls /var/run/libvirt/                 
hostdevmgr  interface  libvirt-admin-sock  libvirt-sock  libvirt-sock-ro  network  nodedev  nwfilter  nwfilter-binding  qemu  secrets  storage  virtlockd-admin-sock  virtlockd-sock  virtlogd-admin-sock  virtlogd-sock

Can't find the file '/var/run/libvirt/virtqemud-sock'
Please check it out https://github.com/kubevirt/kubevirt/commit/7fd94473b955cd221343b6b2e9aa2f771edf0aee
I don't know why I changed it to virtqemud ,How to install virtqemud?

```

**Comment by cheese** [comment]
As hinted by https://github.com/kubevirt/kubevirt/issues/9511#issuecomment-1486510187, I read the referenced tips and changed “masquerade” to “bridge”. The VM is able to start now.

**Comment by Vikash993468** [comment]
> As hinted by [#9511 (comment)](https://github.com/kubevirt/kubevirt/issues/9511#issuecomment-1486510187), I read the referenced tips and changed “masquerade” to “bridge”. The VM is able to start now.

changed masquerade to bridge ..that means you used this vm manifest ?

```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/keep-launcher-alive-after-failure: "true"
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
    debugLogs: "true"
    logVerbosity: "6"
  name: testvm
  namespace: kubevirt
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/kubevirt/cirros-container-disk-demo
    - name: cloudinitdisk
      cloudInitNoCloud:
        userDataBase64: SGkuXG4=
```
it is not working for me
