### ISSUE TITLE
virtctl console Not show any when I use ubuntu vm

### ISSUE THREAD

**Issue by caijian76** [kubevirt/kubevirt#9443]
ubuntu.yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu
spec:
  dataVolumeTemplates:
  - metadata:
      name: ubuntu
    spec:
      source:
        blank: {}
      pvc:
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 10Gi
        storageClassName: rook-ceph-block
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}

      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: ubuntu20-iso
      - name: harddrive
        dataVolume:
          name: ubuntu
```
I only use virttl vnc ubuntu to install and use system. virtctl console ubuntu hasn't any response.
Did I set something wrong?
