### ISSUE TITLE
About real-time virtual machine performance

### ISSUE THREAD

**Issue by zhonglin6666** [kubevirt/kubevirt#9509]
```
One virtual machine that starts with kubevirt, Another that starts directly with libvirtd on host. 
Cyclictest is a high resolution test program. 
Using cyclictest tool to test performance between two methods.
```

**1. A virtual machine  that starts with kubevirt**
```
        cpu:
          cores: 4
          dedicatedCpuPlacement: true
          features:
          - name: tsc-deadline
            policy: require
          isolateEmulatorThread: true
          model: host-passthrough
          numa:
            guestMappingPassthrough: {}
          realtime:
            mask: 2,3
          sockets: 1
          threads: 1
        devices:
          autoattachGraphicsDevice: false
          autoattachMemBalloon: false
          autoattachSerialConsole: true
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: vm-perf-rt-master
          interfaces:
          - bridge: {}
            name: default
        ioThreadsPolicy: auto
        machine:
          type: q35
        memory:
          hugepages:
            pageSize: 1Gi
        resources:
          limits:
            memory: 8Gi
          requests:
            memory: 8Gi
```

1.1 View the virtual machine XML configuration in the container:
```
  <vcpu placement='static'>4</vcpu>
  <iothreads>1</iothreads>
  <cputune>
    <vcpupin vcpu='0' cpuset='5'/>
    <vcpupin vcpu='1' cpuset='7'/>
    <vcpupin vcpu='2' cpuset='9'/>
    <vcpupin vcpu='3' cpuset='11'/>
    <emulatorpin cpuset='13'/>
    <iothreadpin iothread='1' cpuset='13'/>
    <vcpusched vcpus='2' scheduler='fifo' priority='1'/>
    <vcpusched vcpus='3' scheduler='fifo' priority='1'/>
  </cputune>
  <numatune>
    <memory mode='strict' nodeset='1'/>
    <memnode cellid='0' mode='strict' nodeset='1'/>
  </numatune>

1.2 Execute the following command in the virtual machine which locate in container:
```
taskset -c 2,3 cyclictest -t 2 -qm -i100 -p95 -h 60 -D5m
```
# Total: 002999806 002999811
# Min Latencies: 00005 00007
# Avg Latencies: 00006 00007
# Max Latencies: 00749 00782
# Histogram Overflows: 00029 00029
```

**2. A virtual machine that starts directly with libvirtd on host**
2.1 View the virtual machine XML configuration on the host:
```
  <vcpu placement='static'>4</vcpu>
  <iothreads>1</iothreads>
  <cputune>
    <vcpupin vcpu='0' cpuset='5'/>
    <vcpupin vcpu='1' cpuset='7'/>
    <vcpupin vcpu='2' cpuset='9'/>
    <vcpupin vcpu='3' cpuset='11'/>
    <emulatorpin cpuset='13'/>
    <iothreadpin iothread='1' cpuset='13'/>
    <vcpusched vcpus='2' scheduler='fifo' priority='1'/>
    <vcpusched vcpus='3' scheduler='fifo' priority='1'/>
  </cputune>

2.2 Execute the following command in the virtual machine which locates on host:
```
taskset -c 2,3 cyclictest -t 2 -qm -i100 -p95 -h 60 -D5m
```
# Total: 002999834 002999839
# Min Latencies: 00005 00007
# Avg Latencies: 00006 00007
# Max Latencies: 00024 00027
```

**Testing Result**
result 1: Max Latencies: 00749 00782
result 2: Max Latencies: 00024 00027
The performance of the `1` test result is dozens of times worse than that of the `2` method on `Max Latencies`.

**Describe the solution you'd like**:
Can you help me how to improve performance in Kubevirt environment ？
