### ISSUE TITLE
Use a custom scheduler profile for VMI pods to bypass the ImageLocality plugin

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#9570]
**Is your feature request related to a problem? Please describe**:
VMI pods are currently scheduled with the default scheduler profile (if a Pod doesn't specify a scheduler name, kube-apiserver will set it to `default-scheduler`) which includes the `ImageLocality` plugin.

The `ImageLocality` plugin favors nodes that already have the container images that the Pod runs.

In the kubevirt case, the virt-launcher image is the same for all the VMIs and it should be always already available on all the nodes being used by virt-handler in the node labelling process.

Due to this, the benefits  or the `ImageLocality` plugin for VMI scheduling is none.
On the other side, due to:
https://github.com/kubernetes/kubernetes/issues/93488
the list of images reported by a node is capped to certain limit (the default is 50) so some nodes can randomly report they already have the virt-launcher image while others will not and this could lead to an unbalanced scheduling across nodes.

**Describe the solution you'd like**:
I'd like to configure get a custom scheduler profile that skips the `ImageLocality` plugin:
```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: kubevirt
    plugins:
      score:
        disabled:
        - name: ImageLocality
```
and then have my VMI pods configured with: `.spec.schedulerName=kubevirt`

**Describe alternatives you've considered**:
Setting `nodeStatusMaxImages` to `-1` on the kubelet configuration on my cluster.
But this could potentially made the node API objects really large with side effects in terms of responsiveness and stability.

**Additional context**:
kubescheduler.config.k8s.io/v1 is stable since k8s 1.25, see: https://kubernetes.io/docs/reference/scheduling/config/
OCP/OKD implements the secondary scheduler operator: https://github.com/openshift/secondary-scheduler-operator

**Comment by tiraboschi** [comment]
According to https://kubevirt.io/user-guide/operations/scheduler/#scheduling-vms-with-the-custom-scheduler

We can already configure  a VM to be executed with:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-fedora
spec:
  running: true
  template:
    spec:
      schedulerName: kubevirt
```
and this will be enough also for the custom scheduler profile use case.

Probably what we miss here is just a way to set a shared default for all the VMs on `.spec.template.spec.schedulerName` from virt-operator.
