### ISSUE TITLE
Can't create VM from Snapshot via CDI due to missing "snapshot" in spec

### ISSUE THREAD

**Issue by dominikkaminski** [kubevirt/kubevirt#9574]
**What happened**:
It is not possible to create a new VirtualMachine from containerized-data-importer with source `snapshot` caused by `unknown field "spec.dataVolumeTemplates[0].spec.source.snapshot"` error.

See kubevirt API reference:
http://kubevirt.io/api-reference/v0.59.0/definitions.html#_v1beta1_datavolumesource

See kubevirt CDI API reference:
https://kubevirt.io/cdi-api-reference/v1.56.0/definitions.html#_v1beta1_datavolumesource

**What you expected to happen**:
VirtualMachine from Snapshot is created

**How to reproduce it (as minimally and precisely as possible)**:
```
  dataVolumeTemplates:
    - metadata:
        name: "release-name"
      spec:
        pvc:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: "10Gi"
        source:
          snapshot:
            name: "snap"
            namespace: "default"
        contentType: "kubevirt"
```

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.59.0`
- Kubernetes version (use `kubectl version`): `v1.25.6`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: `bare-metal`
- OS (e.g. from /etc/os-release): `Debian`
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
