### ISSUE TITLE
AdmissionReview is not working for creating pods

### ISSUE THREAD

**Issue by kvaps** [kubevirt/kubevirt#9578]
**What happened**:

Hi, I have the mutating webhook which is processing all the pods in a cluster:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linstor-scheduler-admission
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: linstor-scheduler-admission
      namespace: d8-linstor
      path: /mutate
      port: 4443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: scheduler-admission.linstor.deckhouse.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "*"
  sideEffects: None
  timeoutSeconds: 10
```

But virt-controller can't create pods with it:

```json
{
  "component": "virt-controller",
  "level": "info",
  "msg": "reenqueuing VirtualMachineInstance default/vm101",
  "pos": "vmi.go:273",
  "reason": "failed to create virtual machine pod: Internal error occurred: failed calling webhook \"scheduler-admission.linstor.deckhouse.io\": failed to call webhook: an error on the server (\"{\\\"kind\\\":\\\"AdmissionReview\\\",\\\"apiVersion\\\":\\\"admission.k8s.io/v1\\\",\\\"response\\\":{\\\"uid\\\":\\\"e8677a78-aa94-4e2e-b021-8584786e1a4f\\\",\\\"allowed\\\":false,\\\"status\\\":{\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"could not mutate object: an empty namespace may not be set when a resource name is provided\\\"}}}\") has prevented the request from succeeding",
  "timestamp": "2023-04-05T17:37:00.090617Z"
}
```

**What you expected to happen**:

Pods are successfully created 

**How to reproduce it (as minimally and precisely as possible)**:

- Install [linstor-scheduler-admission webhook](https://github.com/piraeusdatastore/linstor-scheduler-extender/blob/3f583c5b9fb1baeeaf1be208329bf158fe988d52/deploy/linstor-scheduler-admission.yaml)
- Set `failurePolicy` to `Fail`:
   ```
   kubectl edit mutatingwebhookconfigurations.admissionregistration.k8s.io linstor-scheduler-admission
   ```
- Try creating VM

**Additional context**:

Original error from here: 
https://github.com/kubernetes/kubernetes/blob/330b5a2b8dbd681811cb8235947557c99dd8e593/staging/src/k8s.io/client-go/rest/request.go#L887-L912

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58; 0.59
- Kubernetes version (use `kubectl version`): v1.23.17
- VM or VMI specifications:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vm101
  namespace: default
spec:
  domain:
    cpu:
      cores: 1
      model: host-model
      sockets: 4
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: boot
      - disk:
          bus: virtio
        name: cloudinit
      interfaces:
      - macvtap: {}
        model: virtio
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 51efb1b7-1c4f-5138-b1a6-c688d7488ceb
    machine:
      type: q35
    resources:
      requests:
        cpu: "4"
        memory: 2048M
  networks:
  - name: default
    pod: {}
  volumes:
  - dataVolume:
      name: disk-vm101-boot
    name: boot
  - cloudInitNoCloud:
      userData: |
        #cloud-config
        chpasswd:
          expire: false
        password: ubuntu
        user: ubuntu
    name: cloudinit
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): 5.15.0-25-generic
- Install tools: deckhouse
- Others: N/A
