### ISSUE TITLE
Does it support the rbd encryption function of ceph-csi?

### ISSUE THREAD

**Issue by Learntotolearn** [kubevirt/kubevirt#9620]
After using the rbd encryption function of ceph-csi again, I turned on the virtual machine and received the following error:
```
 MapVolume.SetUpDevice failed for volume "pvc-58b28fc2-3a49-4000-abf8-f773e799dfe5" : rpc error: code = Internal desc = rpc error: code = Internal desc = need resize check failed on devicePath /dev/mapper/luks-rbd-0001-0024-b42af140-dabb-11ed-969e-ebde09894282-0000000000000002-fb3d7a45-6ebb-4efc-9708-127b27024a8b and staingPath /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-58b28fc2-3a49-4000-abf8-f773e799dfe5/0001-0024-b42af140-dabb-11ed-969e-ebde09894282-0000000000000002-fb3d7a45-6ebb-4efc-9708-127b27024a8b, error: Could not parse fs info on given filesystem format: unknown data, probably partitions. Supported fs types are: xfs, ext3, ext4
```
It seems that Kubevirt did not decrypt the disk, resulting in the inability to recognize the system file type.

The following are the vm and sc files.
vm.yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: storage
    spec:
      domain:
        cpu: 
          cores: 1
          sockets: 4
        memory:
        devices:
          disks:
          - disk: 
              bus: virtio
            name: vm-sdisk1
          - disk:
              bus: virtio
            name: cloudinit-disk1
          - disk:
              bus: virtio
            name: empty-disk1
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      volumes:
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: root
              password: xxxx
              chpasswd: { expire: False }
          name: cloudinit-disk1
        - emptyDisk:
            capacity: 20Gi
          name: empty-disk1
        - dataVolume:
            name: storage-sc
          name: vm-sdisk1
  dataVolumeTemplates:
  - metadata:
      name: storage-sc
    spec:
      storage:
        accessModes: ["ReadWriteMany"]
        storageClassName: csi-cephrdb-sc-luks
        resources:
          requests:
            storage: 20Gi
      source:
        http:
          url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
```

sc.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephrdb-sc-luks
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  pool: test    
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-ceph-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: csi-ceph-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: csi-ceph-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"
  encryptionKMSID: "user-secrets-metadata-test"
  encryptionType: "block"
reclaimPolicy: Delete
allowVolumeExpansion: true
#mountOptions:
        #  - discard
```
