### ISSUE TITLE
virt-handler looking for wrong multus interface name in 0.59.0

### ISSUE THREAD

**Issue by cmu-rgrempel** [kubevirt/kubevirt#9633]
I originally thought this was a macvtap issue, so reported it there: https://github.com/kubevirt/macvtap-cni/issues/100
But it appears to actually be a Kubevirt issue, so I'm reporting it here now instead.

**What happened**:

In version 0.59.0 (but not 0.58.1), when I specify a multus network, `virt-handler` looks for an interface named after the name of the NetworkAttachmentDefinition. (That is, the name of the Kubernetes resource). Of course, it doesn't find that interface, since the interface is actually named `net1`. A workaround is to use `net1` as the name of the NetworkAttachmentDefinition resource.

**What you expected to happen**:

I expected virt-handler to look for the `net1` interface that it sets up.

**How to reproduce it (as minimally and precisely as possible)**:

Here is the NetworkAttachmentDefinition I'm using. Note that I saw the same behaviour for macvtap and macvlan variations of this -- I didn't try others.

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bobnet
  namespace: windows
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/vlan4
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "bobnet",
      "type": "macvtap"
    }
```

Note that leaving the `name` out of the `config` json doesn't make a difference.

And here is the relevant part of the VirtualMachine definition:

```yaml
     networks:
     - name: extra
        multus:
          networkName: bobnet
     domain:
       devices:
         interfaces:
         - name: extra
           macvtap: {}
       resources:
         limits:
          macvtap.network.kubevirt.io/vlan4: 1
```

Note that I tried it with and without a pod network as well, which doesn't make a difference.

Here's the error message I get in the `virt-handler` pod in 0.59.0 (not 0.58.1). This prevents the VM from starting.

```json
{
  "component": "virt-handler",
  "level": "info",
  "msg": "re-enqueuing VirtualMachineInstance windows/testvm",
  "pos": "vm.go:1474",
  "reason": "lstat /proc/1195600/root/sys/class/net/bobnet: no such file or directory",
  "timestamp": "2023-04-19T14:53:34.296066Z"
}
```

Note that `virt-handler` appears to be looking for an interface named `bobnet`, which is the name of the NetworkAttachmentDefinition resource, but there really isn't any reason to expect it to be the name of the interface.

**Additional context**:

As noted above, it works fine on 0.58.1 -- I'm only experiencing the problem in 0.59.0.

I originally had multus 3.9.3 installed, and then upgraded to 4.0.1, which did not help. (But works fine with 0.58.1).

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.0
- Kubernetes version (use `kubectl version`): 1.23.17
- VM or VMI specifications: Noted above
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`): 5.10.0-21-amd64
- Install tools: kubevirt operator (cluster is kubeadm)
- Others: multus 3.9.3 (and then 4.0.1). Main cni is calico.

**Comment by cmu-rgrempel** [comment]
Note that there are a few additional details in the original issue here: https://github.com/kubevirt/macvtap-cni/issues/100  -- I left out some things which appear now not to be relevant, once I determined that v. 0.58.1 worked for me.

**Comment by brianmcarey** [comment]
/cc @maiqueb  

could you please take a look at this issue?

**Comment by maiqueb** [comment]
@cmu-rgrempel can you paste the resources available on your nodes ?

**Comment by cmu-rgrempel** [comment]
I'm using a nodeSelector at the moment to lock the VM to one node. Here's the data for that node (extracted from `kubectl describe node`)

```
Capacity:
 cpu:                                16
 devices.kubevirt.io/kvm:            1k
 devices.kubevirt.io/tun:            1k
 devices.kubevirt.io/vhost-net:      1k
 ephemeral-storage:                  286237024Ki
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 macvtap.network.kubevirt.io/bond0:  0
 macvtap.network.kubevirt.io/vlan1:  50
 macvtap.network.kubevirt.io/vlan4:  50
 memory:                             132004900Ki
 pods:                               110
Allocatable:
 cpu:                                16
 devices.kubevirt.io/kvm:            1k
 devices.kubevirt.io/tun:            1k
 devices.kubevirt.io/vhost-net:      1k
 ephemeral-storage:                  263796040882
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 macvtap.network.kubevirt.io/bond0:  0
 macvtap.network.kubevirt.io/vlan1:  50
 macvtap.network.kubevirt.io/vlan4:  50
 memory:                             131902500Ki
 pods:                               110
```

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                           Requests           Limits
  --------                           --------           ------
  cpu                                12830m (80%)       35100m (219%)
  memory                             58199065152 (43%)  57812343296 (42%)
  ephemeral-storage                  150M (0%)          0 (0%)
  devices.kubevirt.io/kvm            2                  2
  devices.kubevirt.io/tun            2                  2
  devices.kubevirt.io/vhost-net      2                  2
  macvtap.network.kubevirt.io/bond0  0                  0
  macvtap.network.kubevirt.io/vlan1  2                  2
  macvtap.network.kubevirt.io/vlan4  0                  0
```

**Comment by cmu-rgrempel** [comment]
Ah, and here it is from the node's yaml (not different, really):

```
  allocatable:
    cpu: "16"
    devices.kubevirt.io/kvm: 1k
    devices.kubevirt.io/tun: 1k
    devices.kubevirt.io/vhost-net: 1k
    ephemeral-storage: "263796040882"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    macvtap.network.kubevirt.io/bond0: "0"
    macvtap.network.kubevirt.io/vlan1: "50"
    macvtap.network.kubevirt.io/vlan4: "50"
    memory: 131902500Ki
    pods: "110"
  capacity:
    cpu: "16"
    devices.kubevirt.io/kvm: 1k
    devices.kubevirt.io/tun: 1k
    devices.kubevirt.io/vhost-net: 1k
    ephemeral-storage: 286237024Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    macvtap.network.kubevirt.io/bond0: "0"
    macvtap.network.kubevirt.io/vlan1: "50"
    macvtap.network.kubevirt.io/vlan4: "50"
    memory: 132004900Ki
    pods: "110"
```
