### ISSUE TITLE
Libvirt error during LiveMigration

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/kubevirt#9643]
**What happened**:
I have faced the following error migrating a VM:

```bash
Warning  Migrated 56m  virt-handler  VirtualMachineInstance migration uid a63244d5-e8b5-4dd6-b529-c7863bb08a55 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe')
```
The VM attempted to be migrated using the `LiveMigration`method.
I have used the following VM definition:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-live
  name: vm-live
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-live
      annotations:
        descheduler.alpha.kubernetes.io/evict: "true"
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: fedora-dv
        name: datavolumedisk1
      networks:
        - name: default
          pod: {}
  dataVolumeTemplates:
  - metadata:
      name: fedora-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: local
      source:
        http:
          url: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-37-1.7.iso
```
And for the PV definition the following yaml:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /mnt/disks
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node01
          - node02
```

As far as I understand, this error is an expected behavior since `LiveMigration` method just copies the memory content of the VM to the new target VM expecting that the filesystem is shared. Since I'm using a `local` device this cannot be satisfied and the `LiveMigration` method fails (also happens with `hostPath`).

So my question is if KubeVirt should detect and reject this `LiveMigration` scenario before libvirt returns an error. Or if KubeVirt should allows the migration but using `BlockMigration`method.

**What you expected to happen**:
The migration request would be denied or switched to `BlockMigration`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the cluster:

```
$ export KUBEVIRT_NUM_NODES=2
$ make cluster-up && make cluster-sync
```

2. Create the folders and give them enough persmisions and the selinux tag in both hosts:

```bash 
$ sudo mkdir /mnt/disks
$ sudo chmod 777 /mnt/disk
$ sudo chcon -t  container_file_t /mnt/disk
```

3. Create the PV:

```bash
$ kubectl create -f pv.yaml
```

4. Create the VM:

```bash
$ kubectl create -f vm.yaml
```

5. Migrate the VM:

```bash
$ virtctl migrate vm-fedora
```

6. Inspect the failed migration:

```bash
$ kubectl describe vmis vm-live
....
  Migration Method:                  LiveMigration
....
  Normal   Migrating         80s                virt-handler               VirtualMachineInstance is migrating.
  Warning  Migrated          80s                virt-handler               VirtualMachineInstance migration uid 094c6383-b434-4c71-b829-5824b424b031 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe')

```

**Additional context**:
I've used the latest KubeVirt version and the latest KubeVirtCI version.

**Environment**:
- KubeVirt version (use `virtctl version`): `Client Version: version.Info{GitVersion:"v0.59.0-alpha.2.486+9212760b5bf299-dirty", GitCommit:"9212760b5bf29983d275d44f6c4cb4394f32c54c", GitTreeState:"dirty", BuildDate:"2023-04-18T15:17:57Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7", GitCommit:"723bcdb232300aaf5e147ff19b4df7ec8a20278d", GitTreeState:"clean", BuildDate:"2023-02-22T14:05:25Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}`
- VM or VMI specifications: above
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
