### ISSUE TITLE
failed plugging phase1 at nic 'net1': Link not found

### ISSUE THREAD

**Issue by hijak** [kubevirt/kubevirt#9658]
i cannot start vms with a 2nd nic

virt handler
```
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-3","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-25T14:26:55.169646Z"}
```
vmipool
```
              interfaces:
                - bridge: {}
                  name: lan
                - bridge: {}
                  name: default
          networks:
            - name: default
              pod: {}
            - multus:
                networkName: ceph/bridge-network
              name: lan
```

network attachment definition 
```
spec:
  config: |
    {
        "cniVersion": "0.3.1",
        "name": "br0-l2",
        "plugins": [{
            "type": "bridge",
            "bridge": "br0",
            "ipam": {}
        }]
    }
```

```
root@nuc01:~/manifests/ceph# ip a show br0
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ae:e1:8c:24:b9:b1 brd ff:ff:ff:ff:ff:ff
    inet 10.13.37.15/24 brd 10.13.37.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::ace1:8cff:fe24:b9b1/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by EdDev** [comment]
@hijak , we need more information to understand what is the problem.
You need to fill all the details as specified in the template of the issue.

Specifically, we (also) need:
- The version used.
- The full manifests of: VMI, The VMI Pod, NAD.
- The full log of the specific VMI Pod and the virt-handler pod which ran the VMI in question.

/sig network
/assign EdDev

**Comment by hijak** [comment]
im using the hyper converged operator on latest k3s its reporting
`kubevirt.io/install-strategy-version=v0.59.0`

the vmipool definition:
```
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  labels:
    kubevirt-manager.io/managed: 'true'
    kubevirt.io/vmpool: ceph
  name: ceph
  namespace: ceph
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt-manager.io/managed: 'true'
      kubevirt.io/vmpool: ceph
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt-manager.io/managed: 'true'
        kubevirt.io/vmpool: ceph
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            annotations:
              cdi.kubevirt.io/storage.deleteAfterCompletion: 'false'
            name: ceph-ceph-disk1
            namespace: ceph
          spec:
            pvc:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 32Gi
              storageClassName: longhorn
            source:
              http:
                url: >-
                  http://10.13.37.114:8000/jammy-server-cloudimg-amd64.img
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            annotations:
              cdi.kubevirt.io/storage.deleteAfterCompletion: 'false'
            name: ceph-ceph-disk2
            namespace: ceph
          spec:
            pvc:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
              storageClassName: longhorn
            source:
              blank: {}
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            annotations:
              cdi.kubevirt.io/storage.deleteAfterCompletion: 'false'
            name: ceph-ceph-disk3
            namespace: ceph
          spec:
            pvc:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
              storageClassName: longhorn
            source:
              blank: {}
      running: true
      template:
        metadata:
          labels:
            kubevirt-manager.io/managed: 'true'
            kubevirt.io/vmpool: ceph
        spec:
          domain:
            cpu:
              cores: 4
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk: {}
                  name: disk1
                - disk: {}
                  name: disk2
                - disk: {}
                  name: disk3
                - disk:
                    bus: virtio
                  name: disk4
              interfaces:
                - bridge: {}
                  name: default
                - bridge: {}
                  name: net1
            resources:
              requests:
                memory: 4Gi
          networks:
            - pod: {}
              name: default
            - multus:
#                default: true
                networkName: ceph/bridge-network
              name: net1
          #priorityClassName: vm-standard
          volumes:
            - dataVolume:
                name: ceph-ceph-disk1
              name: disk1
            - dataVolume:
                name: ceph-ceph-disk2
              name: disk2
            - dataVolume:
                name: ceph-ceph-disk3
              name: disk3
            - cloudInitNoCloud:
                userData: |
                  #cloud-config
                  manage_etc_hosts: false
                  runcmd:
                    - apt update && apt upgrade -y
                    - apt install ceph cephadm qemu-guest-agent -y
                    - groupmod -g 167 ceph && usermod -u 167 -g 167 ceph
                    - curl https://get.docker.com | sh
                  users:
                    - name: ubuntu
                      passwd: XXXX
                      shell: /bin/bash
                      lock-passwd: false
                      ssh_pwauth: True
                      chpasswd: { expire: False }
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      groups: users, admin
                      ssh_authorized_keys:
                       - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6fxvW8VLHJrEj8v7WHLjNkootX+WGquz8ARqTWcnkLYueJZq4i9YsVf1wUIyIt2dqA1bfLPc3B+ulOs7MACICvayumCOzz5NVW5xEWG8tTbQGTN0RD9uXDEx1EmcCvsZ9gKwibLNGxcwiHzVPmOmKdbp3CT4615JJHdmLtdhHcEhiJhxNc8D+Etv929VOIH95Or9cpzn+aSKs4BX6f+R5TWY6cjuLgvR5f5i9hVxwmNp1zbzhMPijKpbUH56dyl2NPlPlcMU1FLwlBWZCx5hG+tBsY2wFyyp5JZATQsJQ+t7uGzmhZbqxa1VaAJivgfWRQglP8iTz3MhlKy4g4yYd
              name: disk4
```

virt-launcher pod logs 
```
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-04-27T06:54:42.657837Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-04-27T06:54:42.657871Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-04-27T06:54:42.658381Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-04-27T06:54:42.658666Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )","subcomponent":"libvirt","thread":"43","timestamp":"2023-04-27T06:54:42.669000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: ceph-3","subcomponent":"libvirt","thread":"43","timestamp":"2023-04-27T06:54:42.669000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"43","timestamp":"2023-04-27T06:54:42.669000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"43","timestamp":"2023-04-27T06:54:42.669000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:512","timestamp":"2023-04-27T06:54:43.164266Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:537","timestamp":"2023-04-27T06:54:43.172772Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-04-27T06:54:43.173474Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0xc000127080?, 0xc000126f60, 0xc000329200, {0x1ce9698, 0xc000222410})
	cmd/virt-launcher/virt-launcher.go:246 +0x434
main.main()
	cmd/virt-launcher/virt-launcher.go:466 +0x1155
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-04-27T06:59:16.178272Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-04-27T06:59:16.178372Z"}
```

virt handler snippet
```
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"ceph-2","namespace":"ceph","pos":"mount.go:405","timestamp":"2023-04-27T07:03:00.631789Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"ceph-2","namespace":"ceph","pos":"mount.go:408","timestamp":"2023-04-27T07:03:00.631879Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"common.go:272","reason":"Link not found","timestamp":"2023-04-27T07:03:00.633108Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"ceph-2","namespace":"ceph","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:00.633274Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:00.648863Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"ceph-2","namespace":"ceph","pos":"vm.go:1684","timestamp":"2023-04-27T07:03:01.929295Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"ceph-2","namespace":"ceph","pos":"mount.go:405","timestamp":"2023-04-27T07:03:01.930398Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"ceph-2","namespace":"ceph","pos":"mount.go:408","timestamp":"2023-04-27T07:03:01.930513Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"common.go:272","reason":"Link not found","timestamp":"2023-04-27T07:03:01.932174Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"ceph-2","namespace":"ceph","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:01.932372Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:01.951650Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"ceph-2","namespace":"ceph","pos":"vm.go:1684","timestamp":"2023-04-27T07:03:04.512369Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"ceph-2","namespace":"ceph","pos":"mount.go:405","timestamp":"2023-04-27T07:03:04.513232Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"ceph-2","namespace":"ceph","pos":"mount.go:408","timestamp":"2023-04-27T07:03:04.513328Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"common.go:272","reason":"Link not found","timestamp":"2023-04-27T07:03:04.514719Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"ceph-2","namespace":"ceph","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:04.514992Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:04.530174Z"}
{"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:263","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-04-27T07:03:07.481243Z"}
{"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:321","timestamp":"2023-04-27T07:03:07.481300Z"}
{"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:322","timestamp":"2023-04-27T07:03:07.481323Z"}
{"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:323","timestamp":"2023-04-27T07:03:07.481344Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"ceph-2","namespace":"ceph","pos":"vm.go:1684","timestamp":"2023-04-27T07:03:09.650761Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"ceph-2","namespace":"ceph","pos":"mount.go:405","timestamp":"2023-04-27T07:03:09.651052Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"ceph-2","namespace":"ceph","pos":"mount.go:408","timestamp":"2023-04-27T07:03:09.651076Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"common.go:272","reason":"Link not found","timestamp":"2023-04-27T07:03:09.651448Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"ceph-2","namespace":"ceph","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:09.651496Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:09.665024Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"ceph-2","namespace":"ceph","pos":"vm.go:1684","timestamp":"2023-04-27T07:03:19.905931Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"ceph-2","namespace":"ceph","pos":"mount.go:405","timestamp":"2023-04-27T07:03:19.906589Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"ceph-2","namespace":"ceph","pos":"mount.go:408","timestamp":"2023-04-27T07:03:19.906714Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"common.go:272","reason":"Link not found","timestamp":"2023-04-27T07:03:19.908027Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"ceph-2","namespace":"ceph","pos":"vm.go:1830","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:19.908180Z","uid":"5964f5c2-900b-482d-b63a-15256d13713d"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance ceph/ceph-2","pos":"vm.go:1474","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'net1': Link not found","timestamp":"2023-04-27T07:03:19.923693Z"}
```

i have another vmi that just crashes but thats not the issue im interested in
