### ISSUE TITLE
add KubeVirt user access role to kubevirt install manifests

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#969]
the kubevirt install manifests should come with a cluster role admins can assign users to grant them access to VMs. 

example cluster role 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: allow-vm-access
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/console
      - virtualmachines/vnc
    verbs:
      - get
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - offlinevirtualmachines
      - virtualmachinepresets
    verbs:
      - get
      - delete
      - update
      - patch
      - list
      - watch
```
