### ISSUE TITLE
virtctl console not show any

### ISSUE THREAD

**Issue by scydas** [kubevirt/kubevirt#9727]
**What happened**:
userDeploying the vm according to user-guide, the console does not show any information

vm.yaml
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: true
              disable_root: false
              chpasswd:
                expire: False
                list: |-
                  root:dangerous
                  test:dangerous
```

virtctl console testvm
```
Successfully connected to testvm console. The escape sequence is ^]

```

into testvm pod
```
kubectl exec -it virt-launcher-testvm-4fkjp  bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-4.4# virsh list
Authorization not available. Check if polkit service is running or see debug message for more information.
 Id   Name             State
--------------------------------
 1    default_testvm   running

bash-4.4# virsh console default_testvm
Authorization not available. Check if polkit service is running or see debug message for more information.
Connected to domain 'default_testvm'
Escape character is ^] (Ctrl + ])
error: internal error: character device console0 is not using a PTY
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58
- Kubernetes version (use `kubectl version`): v1.23.10
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): Linux controller-node-1 3.10.0-1160.el7.x86_64
- Install tools: N/A
- Others: N/A
