### ISSUE TITLE
arm64 cannot use iso cdrom to install os

### ISSUE THREAD

**Issue by chwetion** [kubevirt/kubevirt#9792]
**What happened**:
To install os use iso, after upload iso to pvc: 
* use cdrom and bus sata, report `Arm64 not support this disk bus type, please use virtio or scsi`, 
* or use cdrom and bus other, report `spec.template.spec.domain.devices.disks[1].cdrom.bus: Bus type virtio is invalid for CD-ROM device`

**What you expected to happen**:
arm64 support cdrom for use iso to install os

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: centos
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom: {}
            name: cdromiso
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: disk0
        hostDisk:
          capacity: 50Gi
          path: /vm-disk-pool/disk.img
          type: DiskOrCreate
      - name: cdromiso
        persistentVolumeClaim:
          claimName: pvc-centos
```

**Additional context**:
or something solution can help me

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
Client Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{GitVersion:"v0.59.0-dirty", GitCommit:"78f5184d1794838c5fc5061f920273fb4e5283ed", GitTreeState:"dirty", BuildDate:"2023-05-24T18:18:05Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
```
- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`): 
```
Linux arm-node 4.18.0-147.8.1.el7.aarch64 #1 SMP Wed Apr 15 18:13:44 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
