### ISSUE TITLE
Unable to specify bus for addvolume

### ISSUE THREAD

**Issue by kvaps** [kubevirt/kubevirt#9797]
**What happened**:

Addvolume command does not support specifying bus and not respecting virtualmachine preference.
Even if vm has preference specified, the hotplug volumes always use `scsi` bus by default.

**What you expected to happen**:

Ability to hotplug virtio drives:
- command `virtctl addvolume` supports `--bus=virtio` flag
- if vm has VirtualMachinePreference assigned with `preferredDiskBus: virtio` use virtio by default for hotplug volumes too.

**How to reproduce it (as minimally and precisely as possible)**:

case 1:
  - create vm and volume
  - use virtctl to attach volume to the vm (there is no `--bus` option)
case 2:
  - create `VirtualMachinePreference`:
    ```yaml
    apiVersion: instancetype.kubevirt.io/v1alpha2
    kind: VirtualMachinePreference
    metadata:
      name: example-preference
    spec:
      devices:
        preferredDiskBus: virtio
    ```
  - create vm with this preference
  - try to hotplug any drive (result: drive attached with `scsi` interface)

**Additional context**:

**Environment**:
- KubeVirt version: v0.59.0
- Kubernetes version: v1.26.4
- VM or VMI specifications:
  ```yaml
  apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/vm: ubuntu-2204-vm
    name: ubuntu-2204-vm
  spec:
    preference:
      kind: VirtualMachinePreference
      name: example-preference
    running: true
    template:
      metadata:
        labels:
          kubevirt.io/vm: ubuntu-2204-vm
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: os
            - disk:
                bus: virtio
              name: cloudinitdisk
          resources:
            requests:
              memory: 512M
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: os
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              password: foo
              chpasswd: { expire: False }
          name: cloudinitdisk
  ```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: Deckhouse
- Others: N/A

API support this, the value is just hardcoded in virtctl:

https://github.com/kubevirt/kubevirt/blob/548ec3d95e2ae3bb801ad6ed5e2c647d4f6e8e4c/pkg/virtctl/vm/vm.go#L386-L397

<details>
<summary>API trace</summary>

https://github.com/kubevirt/kubevirt/blob/33dbfa922dc7f5c096a6ee45f6097c966500bc7b/staging/src/kubevirt.io/api/core/v1/types.go#L1534-L1537

https://github.com/kubevirt/kubevirt/blob/33dbfa922dc7f5c096a6ee45f6097c966500bc7b/staging/src/kubevirt.io/api/core/v1/types.go#L2198-L2205

https://github.com/kubevirt/kubevirt/blob/33dbfa922dc7f5c096a6ee45f6097c966500bc7b/staging/src/kubevirt.io/api/core/v1/schema.go#L569-L574

https://github.com/kubevirt/kubevirt/blob/33dbfa922dc7f5c096a6ee45f6097c966500bc7b/staging/src/kubevirt.io/api/core/v1/schema.go#L621-L625

https://github.com/kubevirt/kubevirt/blob/33dbfa922dc7f5c096a6ee45f6097c966500bc7b/staging/src/kubevirt.io/api/core/v1/schema.go#L641-L644

</details>
