### ISSUE TITLE
Windows VM will not boot with vGPU

### ISSUE THREAD

**Issue by blakjak44** [kubevirt/kubevirt#9879]
**What happened**:
I have created a Windows VM that launches correctly when no vGPU is attached but will not boot when a vGPU is attached. The VM will stall with a black screen that displays "Guest has not initialized the display (yet)."

**What you expected to happen**:
I expect the VM to boot.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a VM with a vGPU assigned.

**Additional context**:
I have the same vGPU type used with an Ubuntu VM and these VMs will boot correctly. My GPU is an A40 and the vGPU type is an A40-6Q. The NVIDIA host driver is version 525.105.14.

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.57.1", GitCommit:"4c08bf090387743b2e2c8037c941102f11e6b031", GitTreeState:"clean", BuildDate:"2022-09-14T14:05:11Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.59.1", GitCommit:"de80e5796454a23bc144b8eaec875d139597bc4d", GitTreeState:"clean", BuildDate:"2023-06-01T13:17:04Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
<details>

<summary>VM Manifest</summary>

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-gpu-test
  namespace: vms
  annotations:
    os.vms/version: "Windows 10"
spec:
  running: false
  template:
    metadata:
      labels:
        windows.vms: "windows-gpu-test"
      annotations:
        os.vms/version: "Windows 10"
    spec:
      domain:
        cpu:
          sockets: 2
          cores: 4
          threads: 2
        resources:
          requests:
            memory: 32Gi
        devices:
          gpus:
            - deviceName: nvidia.com/NVIDIA_A40-6Q
              name: gpu1
          disks:
            - name: pvcdisk
              disk:
                bus: sata
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
            - name: drivers-nvidia
              cdrom:
                bus: sata
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - name: nic-0
              bridge: {}
              ports:
               - name: rdp
                 port: 3389
               - name: ssh
                 port: 22
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
      networks:
      - name: nic-0
        pod: {}
      terminationGracePeriodSeconds: 5
      volumes:
       - name: pvcdisk
          persistentVolumeClaim:
            claimName: windows-10-gpu-image
      - name: virtiocontainerdisk
        containerDisk:
          image: quay.io/kubevirt/virtio-container-disk
      - name: drivers-nvidia
        persistentVolumeClaim:
          claimName: drivers-nvidia-windows
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
```
</details>

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kernel (e.g. `uname -a`):
```
Linux gpu-0 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: `Kubespray`
- Others: N/A
