### ISSUE TITLE
virt-api prevent VM scheduling in hybrid CPU-arch environment

### ISSUE THREAD

**Issue by gunine** [kubevirt/kubevirt#9895]
**What happened**:
The cluster is comprised of both AMD64 and ARM64 worker nodes, and multi-arch kubevirt components are built and deployed in the cluster. When a new VM is created, the webhook in virt-api prevents VM scheduling due the unsupported VirtType issue. The virt-api containers run in  both AMD64 and ARM64 worker node, and when a new VM is spawned by statically specifying the CPU type using nodeSelector, it still has chance to send the validation and other reqest to the virt-api which runs in different CPU typed machine.

**What you expected to happen**:
The VM creation process should always invoke the virt-api which runs in the corresponding CPU typed worker node. For example if an ARM64 typed VM is spawned, then virt-api which run on ARM64 typed CPU should be invoked.

**How to reproduce it (as minimally and precisely as possible)**:
Create a hybrid CPU-arch Kubernetes cluster and install multi-arch KubeVirt. Two virt-api PODs are created and run in ARM64 and AMD64 worker node respectively. Create a ARM64 typed VM by specifying the ARM64 typed worker node using nodeSelector (e.g., kubernetes.io/arch: arm64).

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.0
- Kubernetes version (use `kubectl version`): 1.26.5
- VM or VMI specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "arm64-vm"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: arm64-vm
      annotations:
        image: almalinux-8-8-arm
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: arm64
      terminationGracePeriodSeconds: 30
      domain:
        cpu:
          sockets: 2
          cores: 1
          threads: 1
        devices:
          disks:
            - name: bootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: arm64-vm-boot-dv
          name: bootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: userdata-arm64-vm
            networkDataSecretRef:
              name: networkdata-arm64-vm
  dataVolumeTemplates:
  - metadata:
      name: arm64-vm-boot-dv
    spec:
      preallocation: true
      pvc:
        storageClassName: hostpath-csi
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        pvc:
          namespace: imagevolume
          name: almalinux-8-8-arm
```
- Cloud provider or hardware configuration: multi-arch CPU worker nodes
- OS (e.g. from /etc/os-release): Rocky Linux release 8.8 (Green Obsidian)
- Kernel (e.g. `uname -a`): 4.18.0-477.13.1.el8_8.aarch64
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
/cc @xpivarc @zhlhahaha 

IIRC we still don't support mixed architecture clusters, am I wrong? Should this work?

/triage needs-information

**Comment by zhlhahaha** [comment]
As the PR https://github.com/kubevirt/kubevirt/pull/8293 has merged, we should support mixed architecture clusters. Let me take a look.

**Comment by zhlhahaha** [comment]
Hi @gunine , as I do not have hybird k8s cluster, would you like to share the error message? And can you add the following line into your configuration and try again?
```
...
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: arm64
      architecture: arm64
...
```

**Comment by gunine** [comment]
Hi @zhlhahaha,
Sure thing. I am still on kubevirt 0.59.0, and it seems like architecture attribute was introduced from kubevirt v1.0.0. I will upgrade the kubevirt to v1.0.0 first, and try your suggestion and respond to you. Stay tuned!

> Hi @gunine , as I do not have hybird k8s cluster, would you like to share the error message? And can you add the following line into your configuration and try again?
> 
> ```
> ...
>     spec:
>       nodeSelector:
>         node-role.kubernetes.io/worker: ""
>         kubernetes.io/arch: arm64
>       architecture: arm64
> ...
> ```

Hi @zhlhahaha,
Sure thing. I am still on kubevirt 0.59.0, and it seems like architecture attribute was introduced from kubevirt v1.0.0. I will upgrade the kubevirt to v1.0.0 first, and try your suggestion and respond to you. Stay tuned!

**Comment by gunine** [comment]
Hi @zhlhahaha 
With the given manifest on KubeVirt v1.0.0-rc0, I confirmed that VM provisioning in hybrid-cluster environment works.
One minor issue on the current implementation is that with host-path provisioner (hpp), the VM sometimes scheduled to the wrong node, which leads the virt-launcher POD be in pending state. The root cause of the issue is that there is no way to schedule the CDI importer POD to the corresponding CPU-arch node using labels what we have tried in VM manifest. Any hints on this? Followings are the manifest used for provisioning the VM.
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "arm64-vm"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: arm64-vm
      annotations:
        image: almalinux-8-8-arm
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: arm64
      terminationGracePeriodSeconds: 30
      architecture: arm64
      domain:
        cpu:
          sockets: 2
          cores: 1
          threads: 1
        devices:
          disks:
            - name: bootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: arm64-vm-boot-dv
          name: bootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: userdata-arm64-vm
            networkDataSecretRef:
              name: networkdata-arm64-vm
  dataVolumeTemplates:
  - metadata:
      name: arm64-vm-boot-dv
    spec:
      preallocation: true
      pvc:
        storageClassName: hostpath-csi
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        pvc:
          namespace: imagevolume
          name: almalinux-8-8-arm
```

**Comment by zhlhahaha** [comment]
> there is no way to schedule the CDI importer POD to the corresponding CPU-arch node using labels what we have tried in VM manifest. Any hints on this?

We haven't enabled CDI on Arm64, and I'm not very familiar with CDI. Therefore, I'm unsure if the CDI importer works on Arm64. 
Just to confirm, you're looking to schedule both VMI pods and CDI importer pods on the same k8s node. Is my understanding correct?

**Comment by xpivarc** [comment]
> > there is no way to schedule the CDI importer POD to the corresponding CPU-arch node using labels what we have tried in VM manifest. Any hints on this?
> 
> We haven't enabled CDI on Arm64, and I'm not very familiar with CDI. Therefore, I'm unsure if the CDI importer works on Arm64. Just to confirm, you're looking to schedule both VMI pods and CDI importer pods on the same k8s node. Is my understanding correct?

I would suggest opening an issue on CDI side if there is none yet. 
@zhlhahaha The CDI importer needs to be on the same node if hostpath provisioner is used.

**Comment by gunine** [comment]
> > there is no way to schedule the CDI importer POD to the corresponding CPU-arch node using labels what we have tried in VM manifest. Any hints on this?
> 
> We haven't enabled CDI on Arm64, and I'm not very familiar with CDI. Therefore, I'm unsure if the CDI importer works on Arm64. Just to confirm, you're looking to schedule both VMI pods and CDI importer pods on the same k8s node. Is my understanding correct?

Correct! For the VM which has a local-storage attached, we somehow need to import the disk-image (VM image) using CDI. A CDI importer POD, by default is scheduled to the node where the new PV is created, and the PV contains the copy of VM image so that the VM can boot from it. Of course, we can specify the node where the PV should be located using PVC, but the majority of dynamic provisioner (including hpp) does not support ```selector``` instruction with which we can label both amd64 and arm64. Followings are the DV manifest what I have tried, but with no luck.
```
...
dataVolumeTemplates:
  - metadata:
      name: arm64-vm-boot-dv
    spec:
      preallocation: true
      pvc:
        selector:
          matchLabels:
            kubernetes.io/arch: arm64
        storageClassName: hostpath-csi
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        pvc:
          namespace: imagevolume
          name: almalinux-8-8-arm
...
```

Error message from logs.
```
claim.Spec.Selector is not supported for dynamic provisioning
```
